### ISSUE TITLE
Unable to read very large (multi-GB) files from FilePicker web

### ISSUE THREAD

**Issue by martin-robert-fink** [miguelpruivo/flutter_file_picker#1002]
**Describe the bug**
Attempting to select a large file (> 10GB) and FilePicker returns null.

**Platform**

- [ ] Android
- [ ] iOS
- [X ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here:

        FilePickerResult? result = await FilePicker.platform.pickFiles(
            type: FileType.custom,
            withData: false,
            withReadStream: true,
            allowedExtensions: ['vcd'],
            onFileLoading: _onFileLoading,
            allowMultiple: false);
```

**Details to reproduce the issue**
I'm trying to pick VERY large multi-GB files.  I get no errors and no indications that anything has gone wrong.  Just a null result from pickFiles.  Is there is a known maximum file size?  Is there a way to get a different error (Exception) that the maximum file size has been reached?  Is there a better/different way to read VERY large files from the local machine?

**Error Log**
There are no errors - that's part of the problem

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**

```
Flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-US)
    • Flutter version 2.10.3 at /Users/mfink/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mfink/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile)          • B6EBB345-A017-4072-A4B4-7B2A98706317 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4
      (simulator)
    • iPad Pro (11-inch) (3rd generation) (mobile) • ED8AD2DC-26CD-4B7B-892E-3AE56DC7A25F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4
      (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
**Additional context**

**Comment by jcblancomartinez** [comment]
Hi,

Could anyone please take a look at this?

Thanks.

**Comment by miguelpruivo** [comment]
Sorry @martin-robert-fink I didn't have the time yet. I'm not sure why it happens.

**Comment by martin-robert-fink** [comment]
Ok, thanks for responding.  If you get a chance to look at it, it would be great.  Even if you can find what the maximum file size would be, that would helpful.

**Comment by navaronbracke** [comment]
What browser are you picking on? IIRC Safari starts doing weird at 4+ GB. Not sure on other browsers though.

**Comment by jcblancomartinez** [comment]
Hi,

Is this a plugin-specific or browser-specific issue? I wonder if youtube.com/ has similar browser-specific limits and if not, why not to take the same approach they use to be able to manage big files?

Thanks.

**Comment by navaronbracke** [comment]
The file size limit is always a browser thing. Youtube might be compressing things and/or doing uploads in smaller pieces?

**Comment by martin-robert-fink** [comment]
@navaronbracke ... I tried using multiple browsers.  Chrome is the default during dev though and therefore the most I use.  If this is a browser issue (which wouldn't surprise me), I'd love to get info, such as:  Limits per browser that I can code in and deal with.  And/Or, how do deal with the issue?  If a large file is encountered and it's above the limit, then how to deal with it.  Currently, it's a vacuum... FilePicker responds with nothing and I have no way to deal with the situation.  Thanks, Martin.

**Comment by PiercarloSlavazza** [comment]
The issue affects Firefox as well; as a workaround, the only viable solution that I have found is the one used in this SO answer (that BTW also does right the upload progress tracking by resorting to vanilla JS) https://stackoverflow.com/a/67513990/445090
