### ISSUE TITLE
App crashes if custom extensions were given

### ISSUE THREAD

**Issue by yahu1031** [miguelpruivo/flutter_file_picker#1003]
**Describe the bug**
I need to pick a file that has a custom extension called `.atKeys`. When I specify that, the app crashes with no errors/stack traces in console logs. If I use `FileType.any`, then i can't choose my custom file too, they are disabled.

**Platform**

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
15.4

**How are you picking?**
```dart
FilePickerResult? file = await FilePicker.platform.pickFiles(
  dialogTitle: 'Pick your .atKeys file',
  type: FileType.custom,
  allowMultiple: false,
  allowedExtensions: <String>['atKeys'],
);
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
[Runner logs](https://gist.githubusercontent.com/yahu1031/577b5c93a2cfee229a3aa903ed531e05/raw/4cd2f235ae753fda741e36b12a63157704b5f713/gistfile1.txt)
[Debug console logs](https://gist.githubusercontent.com/yahu1031/139136bcccf7c78077fbe85a39cdedf7/raw/6d7f03e6da1dd478167ce71d5b58d450c0f6b0dd/gistfile1.txt)

**Screenshots and/or video**
![image](https://user-images.githubusercontent.com/35523357/158983121-329e58ec-7660-4172-9c2e-c9917f5e79a9.png)

**Flutter Version details**
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.3 at /Users/minnu/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/minnu/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Users/minnu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/minnu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/minnu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • D3EC02F1-A9CE-41B7-9B41-041D0C6F986B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by miguelpruivo** [comment]
Using custom extensions isn’t supported because the pickers would have to support that as well (the native ones) and they only support valid MIME types. But, by using the `FileType.all` you shouldn’t have any issues picking those.

What if you don’t use any extension?

**Comment by yahu1031** [comment]
@miguelpruivo If I mention `FileType.any`, All the files are faded. I can't pick any.

**Comment by miguelpruivo** [comment]
@yahu1031 that's really weird, try removing the extension when using `FileType.all` or try in a different device please.

**Comment by yahu1031** [comment]
Yes checking it.

**Comment by yahu1031** [comment]
`FileType.all` works fine in android. `FileType.custom` with `allowedExtensions: <String>['atKeys']` throws `PlatformException`.

```console
PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)
```

**Comment by miguelpruivo** [comment]
@yahu1031 are you trying to pick which file in the simulator?

**Comment by yahu1031** [comment]
`@mangotangostable.atKeys`

**Comment by yahu1031** [comment]
The thing is, It used to work pretty fine. I reset the simulator but no use.

**Comment by yahu1031** [comment]
I tried with the new app, It works there. IDK what's wrong. Anything that I should change in [podfile](https://cdn.sourceb.in/bins/1uBfPnuzPb/0)?

**Comment by yahu1031** [comment]
Actually, no file was accessible when `FileType.any`.
<img width=300 src="https://user-images.githubusercontent.com/35523357/159083306-fa1d8f2b-5bf5-4793-af41-abe02ca0779e.png" />

**Comment by yahu1031** [comment]
This is being a blocker for the app rn. I can't log in if this doesn't work. Please LMK if anything more is needed like repo code, etc...

**Comment by miguelpruivo** [comment]
Sorry I’m out this weekend so I only have my phone, makes it harder to help you out.

What if you try with iOS 14? Maybe this could be some limitation introduced with iOS 15.4, I don’t know. We’ll have to figure it out.

**Comment by yahu1031** [comment]
@miguelpruivo Lemme try that too. But it works if I use this package in the new app.

**Comment by miguelpruivo** [comment]
If it works in a new app might be something in your old app.

Try:
```
cd ios && rm Podfile.lock && rm -rf Pods && pod install
```

**Comment by yahu1031** [comment]
@miguelpruivo  I tried this too, It used to work fine till I do this. Last time `fluttertoast` got some issue so I did this `pod deintegrate` and `pod install`. from then this is happening. I reinvestigated it, I added `fluttertoast` and I repeated the same. Now I couldn't pick the file. So the `fluttertoast` is the culprit for this.

**Comment by yahu1031** [comment]
@miguelpruivo any update?

**Comment by amani27** [comment]
@yahu1031 I'm also facing the same issue now, but mine used to work fine till yesterday, and I haven't added any such new changes to my project, nor have I used the fluttertoast plugin. 
If I remove the custom extensions it works otherwise crashes.
``` type: FileType.custom,
          allowedExtensions: ['jpg', 'png', 'jpeg', 'webp', 'doc', 'pdf'],```

**Comment by msalmancode** [comment]
@yahu1031 I'm also facing the same issue in the M1 iOS simulator when selecting FileType.custom. its working fine  on android devices

FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['png', 'jpeg', 'jpg', 'pdf', 'docx'],
      );

**Comment by miguelpruivo** [comment]
These simulators have been acting weirdly with M1 Macs lately 😄 the @yahu1031 issue seems to be a bit different, since the problem doesn't replicate in new projects.

You'll have to figure it out what might be triggering the issue. Try checking the Podfile, the minimum supported version, supported architectures and so on.

**Comment by yahu1031** [comment]
@miguelpruivo but the above steps reproduce it and the culprit is fluttertoast package 🥲

**Comment by edilson14** [comment]
does anyone found the solution, i am having same roblem in android < 10. :/

**Comment by yahu1031** [comment]
@edilson14 with android? Can you please provide logs?

**Comment by yahu1031** [comment]
@miguelpruivo please reopen this

**Comment by miguelpruivo** [comment]
> @miguelpruivo but the above steps reproduce it and the culprit is fluttertoast package 🥲

If the culprit is the fluttertoast package, that shouldn't be related with this package, right? 😄

**Comment by yahu1031** [comment]
@miguelpruivo Yes but there must be some fix... It has been a blocker for a very long time. Please LUK if any updates like overrides, hotfixes, etc... Consider this opening again.

**Comment by yahu1031** [comment]
This happens in M1 macbooks
