### ISSUE TITLE
Can't use this folder. To protect your privacy, choose another folder.

### ISSUE THREAD

**Issue by shareef-dweikat** [miguelpruivo/flutter_file_picker#1008]
**Describe the bug**
I can't select download directory using getDirectoryPath(); method. When i open download folder, the "USE THIS FOLDER" button is grayed out. Also, i see "Can't use this folder. To protect your privacy, choose another folder." message at the top of the screen -screenshot is attached. I think this is a bug. All google apps allow user to store files in downloads directory. Android OS allows it if you ask for permissions correctly. So it is only the flutter file picker that forbids it.

**Platform**
- [ ] Android

**Platform OS version**
Android 12

**How are you picking?**
 if (permissionStatus == PermissionStatus.granted) {
        String? result = await FilePicker.platform.getDirectoryPath();
        if (result == null) {
          return;
        }
       await canWriteToDirectory(result);
          setState(() {
            prefs?.setString(PATH, result);
          });
          
**Details to reproduce the issue**
Use flutter picker open download directory. You won't be able to select it because "USE THIS FOLDER" button is grayed out.

**Error Log**
No error logs. 

**Screenshots and/or video**
![Screenshot_1648195463](https://user-images.githubusercontent.com/10628302/160088919-978003a7-33d1-4469-a387-d8163c2b10d3.png)

**Flutter Version details**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-PS)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.2)
[✓] VS Code (version 1.46.1)
[✓] VS Code (version 1.48.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by yahu1031** [comment]
I see it's not by this plugin. This will be resolved soon. Check [here](https://issuetracker.google.com/issues/196422354?pli=1)

**Comment by miguelpruivo** [comment]
This doesn't seem to be related to the plugin itself, since it only asks the OS for a picker and then it's up to the OS to allow or not access to certain folders.
