### ISSUE TITLE
I have bug 

### ISSUE THREAD

**Issue by h770347** [miguelpruivo/flutter_file_picker#1009]
Launching lib\main.dart on SM G988N in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:28: error: unexpected element <queries> found in <manifest>.

  Command: C:\Users\Guast\.gradle\caches\transforms-2\files-2.1\26dd1351d0d9e3fd7eba128575b887fb\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Guast\AppData\Local\Android\sdk\platforms\android-32\android.jar\
          --manifest\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          comdesign.example.image_picker_test\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:28: AAPT: error: unexpected element <queries> found in <manifest>.

  Command: C:\Users\Guast\.gradle\caches\transforms-2\files-2.1\26dd1351d0d9e3fd7eba128575b887fb\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Guast\AppData\Local\Android\sdk\platforms\android-32\android.jar\
          --manifest\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          comdesign.example.image_picker_test\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\Guast\StudioProjects\image_picker_test\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin file_picker could not be built due to the issue above.

her code 
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  File _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Text("Image is not loaded")
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: (){

        },
        tooltip: 'Increment',
        child: Icon(Icons.camera_alt),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

here  app gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 32

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "comdesign.example.image_picker_test"
        minSdkVersion 16
        targetSdkVersion 32
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

**Comment by miguelpruivo** [comment]
Hi, your issue is [likely this one](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-2) referred in the FAQs.
