### ISSUE TITLE
Locally cached file is not replaced when a new file version is picked

### ISSUE THREAD

**Issue by kostaa** [miguelpruivo/flutter_file_picker#1011]
I pick a file from the Google Drive and upload it in my app. I change the content of the same file and pick/load it again and the previous version is  loaded. I can see these traces in the log file during both attempts but it seems that although the trace says 'loaded and cached' the actual file content is not replaced in the cache. Only after I clear the app cache storage then the new version is correctly loaded.

```
I/FilePickerUtils( 8204): Caching from URI: content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3Dencoded%3Dy_zYr5Jox17Vw-i3muZ3--ESnLszbq_6IvnGWlkwAE0Ciq0pMV2GoI0w5Kk%3D
D/FilePickerUtils( 8204): File loaded and cached at:/data/user/0/com.XXXXXXXXX.app.user/cache/file_picker/my-file.json
```

```
    FilePickerResult? result = await FilePicker
        .platform.pickFiles(allowMultiple: true);
```

**Platform - Android 10**

**Flutter Version details**
```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-GB)
    • Flutter version 2.10.4 at C:\Users\adamk\dev_tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\adamk\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
```

**Comment by miguelpruivo** [comment]
That happens probably because the files are cached in order to prevent multiple repeated picks of the same file, hence, improve the performance.

If you want to make sure that the files are always new, you can call the `cleanTemporaryFiles()` when needed.

**Comment by vanceism7** [comment]
Ah yea, I just got bit by this one myself. It's probably a bit on the unnecessary side, but it might be cool to turn that into an argument for the `pickFiles` function. A `bool clearCache` argument would be very super handy

**Comment by miguelpruivo** [comment]
I’ll take that suggestion in consideration, might make sense! 👌

**Comment by maheini** [comment]
Just faced the same problem. Wasn't struggling for a long time, but It can lead to a tricky situation if you don't test this scenario...

Is there such a big advantage of caching? Or is it possible to generate a checksum and eventually clearing a cache? - just some thoughts for later users, since I solved my problem.

**Comment by miguelpruivo** [comment]
@maheini on Android unfortunately there is no other way to manipulate `File` instances through Flutter other than caching. Since SDK 30 it's not possible to access the absolute path of files. On the native side you can always use the URIs to manipulate the file directly without having to rely on caches, however, that's not very useful for Flutter, unfortunately.

**Comment by maheini** [comment]
Thanks for your reply @miguelpruivo 

Well then, not a huge deal breaker. I was using your package for the first time today, and I'm totally enjoying it. Tanks for your effort! 🥇
