### ISSUE TITLE
Q: Shared storage access might be not needed

### ISSUE THREAD

**Issue by 4ntoine** [miguelpruivo/flutter_file_picker#1013]
Considering the file picking (`pickFiles()`) use case.

In [FilePickerDelegate](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java) i can see a shared storage permission is requested first and then SAF API ([`DocumentContract.`](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java#L111)) is used to access the file.

It seems no shared access is needed as the whole idea of SAF is abstracting of the storage - it might be even in-memory.

Can you confirm?

**Comment by miguelpruivo** [comment]
Might to elaborate?
