### ISSUE TITLE
can not build a release version

### ISSUE THREAD

**Issue by geekhenno** [miguelpruivo/flutter_file_picker#1014]
Hi,
I tried to build a release version but I got this error:

CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'DKImagePickerController' from project 'Pods'
<img width="1274" alt="Screen Shot 1443-09-01 at 4 14 37 PM" src="https://user-images.githubusercontent.com/25689733/161385045-b059e203-fa2a-4dc1-8877-f7f62813ae5c.png">
)

- i did flutter clean, remove pods & reinstall it 
- i remove xDrivdeData 

but still not working.

** it works fine in debug mode

**Comment by amalnaami** [comment]
any update?
