### ISSUE TITLE
Google Documents MIME type not recognised

### ISSUE THREAD

**Issue by Olly-Rea** [miguelpruivo/flutter_file_picker#1019]
Hi! 

I'm at a loss with trying to get this plugin to work with google documents files. I have tried a range of different possible MIME types in: 
```dart
FilePickerResult? file = await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: <String>[
    'application/vnd.google-apps.document',
    'vnd.google-apps.document',
    'google-apps.document',
    'document',
    'gdoc'
  ],
);
```
But without any success. I can see the google docs files in my drive if using `type: FileType.any`, but they are greyed out and unavailable to access. The error mesage I get is the following (formatted for ease of reading):

```
PlatformException (PlatformException(FilePicker, Unsupported filter. 
Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). 
This could also have happened because you are using an unsupported file extension.  
If the problem persists, you may want to consider using FileType.all instead., null, null))
```
It's probably also worth pointing out that in this message, `FileType.all` is suggested, albeit it has since been replaced by `FileType.any`. Hope someone can help as this is blocking any and all further progress I can make in my project!

**Comment by miguelpruivo** [comment]
Hi, I'm sorry but there's nothing we can do regarding this. It's even on the faqs. The MIMEs must be supported by the underlying pickers. The plugin only provides the parameters and lets the platform pickers handle for themselves.

You should use `FileType.all` and then discard unwanted file types after the user is done with picking.

Sorry for any inconvenience.
