### ISSUE TITLE
Not working properly in mobile safari browser

### ISSUE THREAD

**Issue by nidhi-concetto** [miguelpruivo/flutter_file_picker#1021]
Flie picker dialog not always opening in safari browser of mobile device, it's completely fine in chrome and safari browser of mac. But in mobile devices it is not working as expected.
Only facing issue for file picker dialog  not showing every time like choose File

Platform
- [ ] Web (Mobile Web Safari browser issue )

Platform OS version
 Safari os version 15.2

on button tap opening file picker

Here is the code snippet
void _pickFiles() async {
    try {
      _directoryPath = null;
      _paths = (await FilePicker.platform.pickFiles(
        type: _pickingType,
        allowMultiple: _multiPick,
        onFileLoading: (FilePickerStatus status) => print(status),
        allowedExtensions: (_extension?.isNotEmpty ?? false)
            ? _extension?.replaceAll(' ', '').split(',')
            : null,
      ))
          ?.files;
    } on PlatformException catch (e) {
     print('Unsupported operation' + e.toString());
    } catch (e) {
      print(e.toString());
    }
    if (!mounted) return;
    setState(() {
      _isLoading = false;
      _fileName =
      _paths != null ? _paths!.map((e) => e.name).toString() : '...';
      _userAborted = _paths == null;
    });
  }

To reproduce please verify in mobile safari browser

Flutter version
Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-GB)

**Comment by joelsongsouzza** [comment]
I'm facing the same issue

**Comment by hasbean** [comment]
For some reason, this was only happening when using RoundedLoadingButton, and I have no idea why.

I changed it to ElevatedButton and now file picker works on mobile safari/chrome
