### ISSUE TITLE
Permission when writing a file into a user-selected folder on iOS - iCloud Drive. 

### ISSUE THREAD

**Issue by devon** [miguelpruivo/flutter_file_picker#1024]
**Describe the bug**

Permission when writing a file into a user-selected folder on iOS - `iCloud Drive`. 

1. Select a directory on iOS - `iCloud driver`
2. Get the directory
3. Try to write file into the directory, error on permission

Possible solution: 

* https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories
* https://pub.dev/packages/macos_secure_bookmarks

```
await startAccessingSecurityScopedResource(resolvedFile);
// write file
await stopAccessingSecurityScopedResource(resolvedFile);
```

**Platform**

- [x] iOS

**Platform OS version**

14.0

**How are you picking?**

```
String? path = await FilePicker.platform.getDirectoryPath();
// path: /private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Growth/
String filePath = '$path/export.txt';
File file = File(filePath);
file.writeAsString('hello');
```

**Error Log**

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Growth/export.txt' (OS Error: Operation not permitted, errno = 1)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1434:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
```

**Comment by miguelpruivo** [comment]
I believe you can't write directly into iCloud directories. You should use a save/export dialog and use the Files app to save it to there.
