### ISSUE TITLE
Included example app builds in iOS with deprecated calls and will not archive

### ISSUE THREAD

**Issue by andrewknockin** [miguelpruivo/flutter_file_picker#1026]
I am having trouble with my own app, but exactly the same problems appear when trying to use the included example. The example app will compile and run as an iOS app on an M1 Macbook using the iOS simulator, but I am trying to distribute my app, so I have to go into Xcode and Archive it, which is when it fails.

After building the example in Android Studio, I select the ios directory then right click to get the drop down menu and use Flutter > Open iOS Module in Xcode.
In Xcode, I immediately see the 4 warnings of issues, including the 2 deprecated calls.
The iOS deployment target in the Example is 9.0, but changing this up to the latest 15.4 makes no difference.
If I now build again for target iOS 15.4 within Xcode, another 19 issues are found with file_picker, all deprecations.
These can mostly be automatically fixed by clicking on each warning triangle to go to the location in the code, then clicking the warning triangle in the code to bring up the detail window, which has a Fix button.
The file_picker code can be extensively updated in this manner.

But these are all warnings, and should not cause the example to fail.

In order to submit the App to Apple for the App store, the next step is to use Product > Archive and this is where the real error occurs. The app is built again but 2 errors are thrown -
Segmentation fault: 11
and
Command CompileSwiftSources failed with a nonzero exit code

These are exactly the errors that are causing my own app to fail, but obviously are within the file_picker code. In fact the main segmentation fault error is in DKImagePickerController.

This means that I can't submit an iOS app to Apple using file_picker.

macOS version 12.3.1
Android Studio Bumblebee 2021.1.1 Patch 3
Xcode 13.3.1
for OS 15.4

**Comment by andrewknockin** [comment]
stackoverflow seems to have a solution for updating DKImagePickerController here
[https://stackoverflow.com/questions/71558250/xcode-archive-failed-with-flutter-plugins](url)
which simply seems to imply that file_picker does not include the latest version.
That has got my project working now, but it would be useful if the deprecated calls were removed from file_picker soon.

**Comment by andrewknockin** [comment]
That stackoverflow link seems to have failed. It should be:
[https://stackoverflow.com/questions/71558250/xcode-archive-failed-with-flutter-plugins](url)
and the solution suggested is to use pod to get the latest DKImagePickerController directly from its github repo, remembering to clean up before re-building.

**Comment by miguelpruivo** [comment]
The URL you've provided leads to nowhere. What's your suggestion?

**Comment by andrewknockin** [comment]
That link is very strange.
If you type it in manually it works.

**Comment by andrewknockin** [comment]
Basically the linked article shows how we as users can update the version of DKImagePickerController used in your code.
But @miguelpruivo you can update it directly which would resolve my issue.

**Comment by miguelpruivo** [comment]
@andrewknockin currently it is fetching the latest version automatically so I'm not sure about what changes you'd want to be made.

**Comment by andrewknockin** [comment]
Oh.
I have the extension in my project and it will not archive when built for iOS on Mac. If I open the included example on my Mac, it also fails with the same error, so its not my code.
If I add the suggested line in podfile, which essentially overrides the fetch, then it all works.
Maybe your Mac has the latest version cached somewhere. I deliberately tested with your example code so that you would have the same test.
Is it possible for you to test on a different Mac? That link shows that others are having the same problem as I am.
Thanks for spending the time to understand this.

**Comment by thobiassilva** [comment]
> 

I have the same problem, this solution solved it for me

**Comment by thobiassilva** [comment]
> Esse link de stackoverflow parece ter falhado. Deve ser: [https://stackoverflow.com/questions/71558250/xcode-archive-failed-with-flutter-plugins](url) e a solução sugerida é usar pod para obter o DKImagePickerController mais recente diretamente de seu repositório github, lembrando de limpar antes de reconstruir.

I have the same problem, this solution solved it for me
