### ISSUE TITLE
Allowed extensions is not working

### ISSUE THREAD

**Issue by ankitTiwar** [miguelpruivo/flutter_file_picker#1028]
I am using the samsung device and i declared  ['jpg', 'png', 'pdf', 'jpeg'] this extensions and when i open my file explorer then i am able to select all types of extensions like .apk.
![Screenshot_20220502-113830_My Files](https://user-images.githubusercontent.com/102948392/166191778-1d936e6e-f9a1-40c2-a39d-41801b62e796.jpg)

**Comment by miguelpruivo** [comment]
Explained in the [first question of the FAQ](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

TL;DR: That's the platform picker's fault, unfortunately you'll have to discard the unwanted files on your end by iterating the extensions.
