### ISSUE TITLE
Stuck--Why do I die when I click the Mac OS button

### ISSUE THREAD

**Issue by marven88cn** [miguelpruivo/flutter_file_picker#1035]
Why do I die when I click the Mac OS button

The code is as follows:
FilePicker.platform.pickFiles(type: FileType.image).then((result) {
            if (result != null) {
              File file = File(result.files.single.path.toString());
              var size = result.files.first.size;
              String transSize = FileUtils.getPrintSize(size);
              var fileName =  result.files.first.name;
              print('file name -> $fileName, file size $transSize');
              sendImageDialog(body, file.path, fileName, transSize);
            }
          },onError: (value){
           showSnackBar('error');
      });

**Comment by miguelpruivo** [comment]
Sorry, I didn't get what's your issue. What do you mean by "dying"?

**Comment by marven88cn** [comment]
The application is not responding, just like android's ANR




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miguelpruivo/flutter_file_picker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miguelpruivo/flutter_file_picker] Stuck--Why do I die when I click the Mac OS button (Issue #1035)





 
Sorry, I didn't get what's your issue. What do you mean by "dying"?

**Comment by miguelpruivo** [comment]
Try building on xcode and show me the logs/stack.
