### ISSUE TITLE
[Linux] not woking

### ISSUE THREAD

**Issue by derappelt** [miguelpruivo/flutter_file_picker#1036]
**Describe the bug**
All functions not working. As soon as I call one of the methods they return null. No FilePicker is showing up and no error is thrown.
Simply nothing happens.
The exact same code works beautifully on Android.

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [x] Desktop

**Platform OS version**
Ubuntu Linux 20.04

**How are you picking?**
```
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';

void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String directory = "start";

  _open() async {
    String? selectedDirectory = await FilePicker.platform.getDirectoryPath();
    setState(() {
      directory = selectedDirectory ?? "none";
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Text(directory),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _open,
        tooltip: 'open',
        child: const Icon(Icons.folder),
      ),
    );
  }
}
```

**Error Log**
There is no error.

**Flutter Version details**
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-41-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/appelt/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

**Comment by MauroMontan** [comment]
i have the same, my app is running perfectly on android but got this error on linux 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method dir on channel miguelruivo.flutter.plugins.filepicker)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      FilePickerIO.getDirectoryPath (package:file_picker/src/file_picker_io.dart:53:14)
<asynchronous suspension>

**Comment by EdmarCaixeta** [comment]
> i have the same problem, my app is running perfectly on android but got this error on linux
> 
> ```
> [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method dir on channel miguelruivo.flutter.plugins.filepicker)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
> <asynchronous suspension>
> #1      FilePickerIO.getDirectoryPath (package:file_picker/src/file_picker_io.dart:53:14)
> <asynchronous suspension>
> ```

Same issue here, not working in Linux Build but it does work in Chrome build. Anyone solved it?

**Comment by MauroMontan** [comment]
@EdmarCaixeta, if you just added the package by `flutter pub add file_picker`, you are probably not on the most recent version of the package , try updating the package to the latest version (^4.6.1), that worked for me :)

**Comment by EdmarCaixeta** [comment]
Yeah, it worked! Thanks for helping me to solve my issue

**Comment by nicolgit** [comment]
still having this issue on linux and version (^8.0.0), any idea on how to unlock the situation?

**Comment by MADMAN-Modding** [comment]
I'm having this problem as well, it was working two days ago and now it is broken on wayland and x11. I get no error, when I press the button I have set to run FilePicker.platform.getDirectoryPath() nothing happens.

**Comment by saif-ellafi** [comment]
Having the same issue here

**Comment by AyanDas-99** [comment]
Same issue here, getDirectoryPath() or pickFiles() both not working on Ubuntu 24.04.1 LTS

**Comment by saif-ellafi** [comment]
If it helps anybody, packaging your flutter app in flatpak or snap doesn't have this issue and works well.

**Comment by MADMAN-Modding** [comment]
Idk why but it magically works for me now

    FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image, allowMultiple: false);

**Comment by AyanDas-99** [comment]
> If it helps anybody, packaging your flutter app in flatpak or snap doesn't have this issue and works well.

Yes, the issue only exists when app is run in vscode debug mode.
