### ISSUE TITLE
closed app when use custom type

### ISSUE THREAD

**Issue by omidima** [miguelpruivo/flutter_file_picker#1037]
hello.
i use the custom extention type and FilePicker.custom, but when running the FilePicker.platform.pickFile(...), application is closed.
this problem created only when use the custom type.
```
...

FilePickerResult? result = await FilePicker.platform.pickFiles(
          allowCompression: true,
          allowMultiple: true,
          type: FileType.custom,
          allowedExtensions: ['mp3', 'wav', 'amr', 'aac', 'mpeg']);

...
```

**Comment by miguelpruivo** [comment]
Which platform does this happen?

**Comment by omidima** [comment]
ios platform and I`m develop app with mac pro m1
