### ISSUE TITLE
Error getting incorrect path when selecting pdf file

### ISSUE THREAD

**Issue by Thuquanguyen** [miguelpruivo/flutter_file_picker#1039]
I have taken the path of the pdf file to upload the file to my application, but the retrieved path does not match the current path of the file.
My file is currently in the download directory but when I log out the path it is in the cache of the file_picker lib.
This leads to the wrong path relative to the location of the .
Help me explain this and how to fix them to get the correct path.
Thank!

**Comment by miguelpruivo** [comment]
This is not an issue. Please, read the documentation regarding this behaviour.

TL;DR — That's not possible since Android SDK 29. It's against Android guidelines and not reliable to use original absolute paths, hence the reason why the files are cached at the app's content.

**Comment by Thuquanguyen** [comment]
I use andorid 12 with sdk > 29 but  path  the same issue

**Comment by Thuquanguyen** [comment]
![Screenshot_20220531_095005](https://user-images.githubusercontent.com/26043884/171083155-6a62582b-856c-4384-b154-2c7642e37536.png)

**Comment by Thuquanguyen** [comment]
Can you help me?
