### ISSUE TITLE
My popup menu comes up on the bottom left!

### ISSUE THREAD

**Issue by usedatiek** [miguelpruivo/flutter_file_picker#1044]
**Describe the bug**
When I open an app on the iPhone web and use FilePicker, the popup menu comes up on the bottom left!
I would like to display this popup menu above the button I touch.
Is there a solution?
![Simulator Screen Shot - iPhone 13 Pro - 2022-06-06 at 15 17 43](https://user-images.githubusercontent.com/85816564/172106103-7325107c-72aa-4f99-a008-08bc9b43eb69.png)

**Platform**

- [ ] Android
- [x] iOS
- [x] Web
- [ ] Desktop

**Comment by MingSern** [comment]
This is still an issue

**Comment by stephane-archer** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/1628
