### ISSUE TITLE
App crashes on Android when hitting back button

### ISSUE THREAD

**Issue by rivella50** [miguelpruivo/flutter_file_picker#1046]
**Describe the bug**
When hitting the native back button on Android (device and simulator) in opened picking window the app crashes all the time.
I even cannot try/catch this issue.
I use file_picker version 4.6.1, but it also happens with 4.5.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**How are you picking?**
```
final result = await FilePicker.platform.pickFiles(
        allowMultiple: false,
        type: FileType.custom,
        allowedExtensions: ['jpg', 'pdf'],
      );
      if (result != null) {
       ...
      }
```

**Details to reproduce the issue**
Just hit the back button in picking window instead of selecting a file.

**Error Log**
I/FilePickerDelegate( 6312): User cancelled the picker request
D/SumupPlugin( 6312): onActivityResult - RequestCode: 50610 - Result Code: 0
D/AndroidRuntime( 6312): Shutting down VM
E/AndroidRuntime( 6312): FATAL EXCEPTION: main
E/AndroidRuntime( 6312): Process: com.company.staging, PID: 6312
E/AndroidRuntime( 6312): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=50610, result=0, data=null} to activity {com.company.staging/ch.vlabs.company.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property currentOperation has not been initialized
E/AndroidRuntime( 6312): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
E/AndroidRuntime( 6312): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
E/AndroidRuntime( 6312): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 6312): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 6312): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6312): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6312): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/AndroidRuntime( 6312): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6312): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6312): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6312): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime( 6312): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 6312): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property currentOperation has not been initialized
E/AndroidRuntime( 6312): 	at io.purplesoft.sumup.SumupPlugin.onActivityResult(SumupPlugin.kt:204)
E/AndroidRuntime( 6312): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime( 6312): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 6312): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:802)
E/AndroidRuntime( 6312): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime( 6312): 	at android.app.Activity.dispatchActivityResult(Activity.java:8385)
E/AndroidRuntime( 6312): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
E/AndroidRuntime( 6312): 	... 13 more

**Flutter Version details**
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-CH)
    • Flutter version 3.0.1 at /Users/valley/Development/flutter/sdk/flutter_macos_3.0.1-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/valley/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/valley/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/valley/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Mi A3 (mobile)              • f1762f0b93c3                             • android-arm64  • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554                            • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone (mobile)             • b1e07e6418181a7ddb14dab4d51974f0e722119a • ios            • iOS 15.5 19F77
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Additional context**
I wonder why i see the (also used) SumupPlugin in the error stacktrace.
On iOS everything works fine.

**Comment by rivella50** [comment]
Fixed by updating the Sumup Plugin.

**Comment by cyberneid** [comment]
Same issue here. No solution yet.
We are using file_picker 4.5.0.
Any solution?

**Comment by rivella50** [comment]
@cyberneid Check the stacktrace of the error. Probably it's also another plugin which causes the crash with a lateinit property.

**Comment by cyberneid** [comment]
Yes, found it and fixed.
many thanks
