### ISSUE TITLE
How to stop copying to the app cache folder?

### ISSUE THREAD

**Issue by PeperMarkreel** [miguelpruivo/flutter_file_picker#1048]
The filepicker copies the file to the cache folder of the app. And returns a path to the file in the app's cache folder. 

Is this intended behaviour? 

My application works with lot's of high bitrate mp3's and so the cache folder gets filled quickly. I don't want the audio files stored twice on the device of the user.

I don't want filepicker to copy the file, how do I configure it so it returns the original path?

edit:
From the wiki: 

clearTemporaryFiles()

An utility method that will explicitly prune cached files from the picker. This is not required as the system will take care on its own, however, sometimes you may want to remove them, specially if your app handles a lot of files.
--
iOS | All picked files are cached, so this will immediately remove them.
Android | Since 2.0.0, all picked files are cached, so this will immediately remove them.
Desktop & Web | Not implemented as it won't have any effect. Paths are always referencing the original files.

Is there a reason the files are 'cached'? They are still in the same type of storage (and storage speeds) so there is no speed advantage for copying them.

**Comment by miguelpruivo** [comment]
Yes, this is the intended behavior and has to be (since SDK 30). It's explained in the FAQs why.
