### ISSUE TITLE
Custom file type db is unsupported and will be ignored.

### ISSUE THREAD

**Issue by tebalink** [miguelpruivo/flutter_file_picker#1051]
[MethodChannelFilePicker] Platform exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)
E/flutter (19465): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)

**Comment by nck974** [comment]
I have experienced the same issue with this code:
```dart
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: false,
      type: FileType.custom,
      allowedExtensions: ['db'],
    );
```
Exception: 
```
I/flutter (31972): [MethodChannelFilePicker] Platform exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)

```

**Comment by philenius** [comment]
Please use our issue template. On which platform are you?

**Comment by philenius** [comment]
Also, probably a duplicate of #24 . Please refer to Miguel's response https://github.com/miguelpruivo/flutter_file_picker/issues/24#issuecomment-450750906
