### ISSUE TITLE
IOS 15:  on image selection throwing a exception  

### ISSUE THREAD

**Issue by basit192** [miguelpruivo/flutter_file_picker#1053]
I have Iphone X while selecting an image from the gallery it is throwing an error which leads to crash 

***** Picker:<PHPickerViewController: 0x1032fe8d0> didFinishPicking:(
    "<PHPickerResult: 0x283ed4160>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 443]

i am using latest file picker 4.6.1 so far 

@jamesdixon @ened  @GeertJohan @lecaros

**Comment by sumanwebidigital** [comment]
I am also facing the same issue.

<img width="948" alt="Screen Shot 2022-09-01 at 14 33 23" src="https://user-images.githubusercontent.com/77598971/187872962-ce47f499-6c98-43d6-a499-34626c78548e.png">
