### ISSUE TITLE
[Windows] MissingPluginException

### ISSUE THREAD

**Issue by Dmitrii-developer** [miguelpruivo/flutter_file_picker#1054]
Hi!
Can't use any of the functions of FilePicker.platform.
Commands flutter clean, flutter pub get do not help to solve the problem.

**Platform**
- [ ] Desktop

**Platform OS version**
Windows 10

**How are you picking?**
flutter run, click on button.

**Details to reproduce the issue**
String? selectedDirectory = await FilePicker.platform.getDirectoryPath();
FilePickerResult? selectedDirectory = await FilePicker.platform.pickFiles();
Etc.

**Error Log**
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

**Flutter Version details**
[√] Flutter (Channel stable, 3.0.2, on
    Microsoft Windows [Version
    10.0.19044.1766], locale en-US)        
    • Flutter version 3.0.2 at D:\Flutter  
    • Upstream repository
      https://github.com/flutter/flutter.gi      t
    • Framework revision cd41fdd495 (10    
      days ago), 2022-06-08 09:52:13 -0700 
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android    devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at D:\Android\SDK        
    • Platform android-32, build-tools     
      32.1.0-rc1
    • ANDROID_SDK_ROOT =
      D:\Users\Dmitriy\AppData\Local\Androi      d\Sdk
    • Java binary at: D:\Program
      Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime
      Environment (build
      11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.       

[√] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrom      e.exe

[√] Visual Studio - develop for Windows
    (Visual Studio Community 2019 16.11.9) 
    • Visual Studio at C:\Program Files    
      (x86)\Microsoft Visual
      Studio\2019\Community
    • Visual Studio Community 2019 version 
      16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0  

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Program
      Files\Android\Android Studio
    • Flutter plugin can be installed from:      
      https://plugins.jetbrains.com/plugin/      9212-flutter
    • Dart plugin can be installed from:   
      
      https://plugins.jetbrains.com/plugin/      6351-dart
    • Java version OpenJDK Runtime
      Environment (build
      11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows •        
      windows-x64    • Microsoft Windows   
      [Version 10.0.19044.1766]
    • Chrome (web)      • chrome  •        
      web-javascript • Google Chrome       
      102.0.5005.115
    • Edge (web)        • edge    •        
      web-javascript • Microsoft Edge      
      102.0.1245.44

[√] HTTP Host Availability
    • All required HTTP hosts are available
• No issues found!

**Comment by minihant** [comment]
I have the same problem, looks like not compatible with ffi-2.0
