### ISSUE TITLE
Mac OS File Picker does not get focus

### ISSUE THREAD

**Issue by dalewking** [miguelpruivo/flutter_file_picker#1059]
When using the File Picker on Mac OS the picker does not get focus, so there is always an extra click to first give the picker focus before you can choose a file.

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
FilePicker.platform
      .pickFiles(
          dialogTitle: "Choose PDF File to work with",
          allowedExtensions: ["pdf"],
          allowMultiple: false,
          type: FileType.custom)
```

**Comment by jeffmikels** [comment]
same for me

**Comment by tmpfs** [comment]
Yep, same problem here. Can you re-open this please, this should not be closed.

**Comment by rigroch** [comment]
same for me.

**Comment by benjamin-kraatz** [comment]
Same for me. Can we sometimes expect a fix?

**Comment by tmpfs** [comment]
@benjamin-kraatz doesn't look like a fix will land here anytime soon, I migrated to this:

https://pub.dev/packages/file_selector

Which does not have the focus issue.

**Comment by benjamin-kraatz** [comment]
@tmpfs great, this works. Thanks!

**Comment by vlidholt** [comment]
Also having this problem.

**Comment by philenius** [comment]
> @benjamin-kraatz doesn't look like a fix will land here anytime soon, I migrated to this:
> 
> https://pub.dev/packages/file_selector
> 
> Which does not have the focus issue.

This is the correct answer. As mentioned in various issues, we cannot provide better UX. Please migrate to Google's official `file_selector` package.

**Comment by stuartmorgan** [comment]
> As mentioned in various issues, we cannot provide better UX.

It's not possible to provide better UX with the *current* implementation, but it's certainly possible to implement correctly in a plugin.

> Please migrate to Google's official `file_selector` package.

If there's no plan to fully support macOS, and are recommending people not use the implementation, have you considered removing it so that people don't see macOS support advertised in the README and via pub.dev labels?

**Comment by philenius** [comment]
> but it's certainly possible to implement correctly in a plugin

I don't know where to start with a better implementation and I could not maintain it. Everybody is complaining, but there's no one who wants to implement or provide "the correct solution". Contributions for macOS / Linux are definitely welcome.

> If there's no plan to fully support macOS, and are recommending people not use the implementation, have you considered removing it so that people don't see macOS support advertised in the README and via pub.dev labels?

Valid question... :thinking: But that would mean, if we want to be consistent, then we would also have to drop the Linux implementation, which suffers from the same problems.

**Comment by stuartmorgan** [comment]
> > but it's certainly possible to implement correctly in a plugin
> 
> I don't know where to start with a better implementation and I could not maintain it. Everybody is complaining, but there's no one who wants to implement or provide "the correct solution". Contributions for macOS / Linux are definitely welcome.

To be clear, I wasn't suggesting you or anyone else has an obligation to fix it. I was just trying to clarify the situation; there's a critical difference between "this cannot be fixed" (in which case there would be no point in anyone even trying to contribute to it) and "this is a valid and fixable issue, but nobody is currently planning on working on it" (in which case someone could contribute a fix if they were motivated to do so).

**Comment by stuartmorgan** [comment]
> But that would mean, if we want to be consistent, then we would also have to drop the Linux implementation, which suffers from the same problems.

Would you actively advise people not to use the Linux implementation? If so, then I would certainly agree that it would make sense to be consistent about any action taken.

Obviously it's entirely up to you how to handle it, it just seems like if you are actively trying to discourage people from using those implementations, not shipping them would be the most effective way to do that.
