### ISSUE TITLE
iOS build failed in appcenter

### ISSUE THREAD

**Issue by sarimk80** [miguelpruivo/flutter_file_picker#1062]
file_picker: ^3.0.3
flutter version: 2.2.4

**Describe the bug**
/Users/runner/work/1/s/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:374:40: error: no visible @interface for 'UIImage' declares the selector 'imageByPreparingForDisplay'
            UIImage *decodedImage = [image imageByPreparingForDisplay];
                                     ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/runner/work/1/s/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:442:40: error: no visible @interface for 'UIImage' declares the selector 'imageByPreparingThumbnailOfSize:'
            UIImage *decodedImage = [image imageByPreparingThumbnailOfSize:thumbnailSize];

**Platform**


 iOS

**Platform OS version**
xcode version 13.1


This issue is with SDWebImage as it was updated on 26-june-2022 which caused this issue
https://github.com/SDWebImage/SDWebImage/releases

**Comment by hasanozkaynak26** [comment]
It's working when i upgraded my OS. 

My flutter doctor results are : 
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale
    tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
