### ISSUE TITLE
Crash app when run on web and SO Linux

### ISSUE THREAD

**Issue by deandreamatias** [miguelpruivo/flutter_file_picker#1067]
**Describe the bug**
When I run an example to web in Linux and try pick a file, web application close without any error

**Platform**

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Desktop

**Platform OS version**: Linux
What version did it happen?

**How are you picking?**
```
Example mode
```

**Details to reproduce the issue**
1. Clone this repo
2. Set Flutter 3.0.x
3. Get dependencies
4. Run example
5. Pick file
6. Error: Close web application 

**Error Log**
Don't print any error log

**Flutter Version details**

```
[✓] Flutter (Channel stable, 3.0.4, on Ubuntu 20.04.4 LTS 5.13.0-52-generic, locale en_US.UTF-8)
    • Flutter version 3.0.4 at /home/matias/develop/flutter/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (10 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/matias/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-52-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by deandreamatias** [comment]
This still an issue

**Comment by GloireMutaliko21** [comment]
Hello to all! I'm on Ubuntu 20.04, I'm trying to use file_picker in its latest version (4.6.1). I am on Flutter SDK 3.0.5. When I run the application on Chrome and click on the button to select a file, the application suddenly stops without any error or exception. I also try to run on Linux, when I click the button, nothing happens at all. I have run on a real cell phone (Android), and everything is fine.

I've been looking everywhere for a while, but I can't find any solution and I have a feeling that the problem is with my operating system maybe.

Can you give me a hand please?

**Comment by deandreamatias** [comment]
The error that you describe is exactly equal to the describe in this issue.
Is a Flutter or file_picker error.

The only way that I show to solve, is debug this package and try find de bug

**Comment by deandreamatias** [comment]
Don't close this please
