### ISSUE TITLE
NullPointerException on FilePickerPlugin$1.onActivityResult in certain Android devices

### ISSUE THREAD

**Issue by Dancovich** [miguelpruivo/flutter_file_picker#107]
My app is crashing in some Android devices with a NullPointerException.

Unfortunately I've been unable to reproduce the issue in my device. The crash logs came from Google's Developer Console and points to a NPE in `FilePickerPlugin$1.onActivityResult` but without a line number.

Taking a look into this method on version 1.3.7 pointed me to this suspect piece of code. On line 59  of `com.mr.flutter.plugin.filepicker.FilePickerPlugin` you have `if(data.getClipData() != null) {` yet on line 78 you have an else for that if written as `} else if (data != null) {`. This `else` block won't ever be reached and Android Studio even warns about that.

I don't know if `data` being null on line 59 is the cause of this NPE but the rest of the code seems fine so I would start taking a look there.

Below is the stack trace of the crash. If I'm able to reproduce this in my device I'll post more details.

> java.lang.RuntimeException: 
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3469)
>   at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3509)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2772)
>   at android.app.ActivityThread.-wrap12 (ActivityThread.java)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1507)
>   at android.os.Handler.dispatchMessage (Handler.java:102)
>   at android.os.Looper.loop (Looper.java:154)
>   at android.app.ActivityThread.main (ActivityThread.java:6236)
>   at java.lang.reflect.Method.invoke (Method.java)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:891)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:781)
> Caused by: java.lang.RuntimeException: 
>   at android.app.ActivityThread.deliverResults (ActivityThread.java:4141)
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3443)
>   at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3509)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2772)
>   at android.app.ActivityThread.-wrap12 (ActivityThread.java)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1507)
>   at android.os.Handler.dispatchMessage (Handler.java:102)
>   at android.os.Looper.loop (Looper.java:154)
>   at android.app.ActivityThread.main (ActivityThread.java:6236)
>   at java.lang.reflect.Method.invoke (Method.java)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:891)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:781)
> Caused by: java.lang.NullPointerException: 
>   at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult (FilePickerPlugin.java)
>   at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java)
>   at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java)
>   at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java)
>   at br.com.cosmiceffect.app.cosmiccollection.MainActivity.onActivityResult (MainActivity.java)
>   at android.app.Activity.dispatchActivityResult (Activity.java:6937)
>   at android.app.ActivityThread.deliverResults (ActivityThread.java:4137)
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3443)
>   at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3509)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2772)
>   at android.app.ActivityThread.-wrap12 (ActivityThread.java)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1507)
>   at android.os.Handler.dispatchMessage (Handler.java:102)
>   at android.os.Looper.loop (Looper.java:154)
>   at android.app.ActivityThread.main (ActivityThread.java:6236)
>   at java.lang.reflect.Method.invoke (Method.java)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:891)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:781)

**Comment by miguelpruivo** [comment]
Hi @Dancovich handling file paths can be tricky to debug to Android fragmentation (and with this, the custom roms) that’s why this kind of issues 95% of the time happen on Android and not iOS. There are times where custom roms use their own file explorers and handle the path themselves, hence, sometimes not returning the path in the activity result when it should.

Sometimes it’s so hard to reproduce the issues that makes it almost impossible to fix (if indeed a fix is required). 😕

Would you mind to tell me in which model and version this happened?

**Comment by Dancovich** [comment]
Hi @miguelpruivo 

The struggle of dealing with buggy apps that return unusual intent configurations is real.

Play Console lists this device: jfltexx running Android 7.1. From what I could gather this is a Samsung Galaxy S4 running some kind of custom ROM like LineageOS, which is quite an unusual configuration and could explain the error.

I forked your repo and did a few changes to protect the code against this buggy behavior. I still haven't made a PR because I'm running a few tests to check if this actually solves the issue and if I didn't cause other problems. You can check the changes below, I posted an update to my app and I'll monitor Play Console to see if the error appears again.

https://github.com/Dancovich/plugins_flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java

**Comment by miguelpruivo** [comment]
Thank you @Dancovich, feel free to issue a PR, however, have in mind that your solution should be sdk-agnostic and any modification, even though might fix a specific device issue, should not affect others.

Just let me know when you're done testing with your updates. 👍

**Comment by Dancovich** [comment]
I've done several tests on the affected device and on others. So far the issue seems to be solved. I've also tested some Android models to check if the change affects some of the negatively but so far normal behavior of the plugin seems to be unchanged.

I'll issue a PR with my change. Please let me know if it needs some adjusting before it gets accepted.

**Comment by miguelpruivo** [comment]
Fixed with #111.

**Comment by Dancovich** [comment]
No problem. Thanks for the quick response.

**Comment by miguelpruivo** [comment]
[Version 1.4.0](https://pub.dev/packages/file_picker#140) published with these changes. Thank you for your contribution. 🎉

**Comment by miguelpruivo** [comment]
@Dancovich [version 1.4.0](https://pub.dev/packages/file_picker#140) published with these changes. Thank you for your contribution. 🎉
