### ISSUE TITLE
[BUG] file_picker 4.6.1 depends on ffi ^1.1.2

### ISSUE THREAD

**Issue by zs-dima** [miguelpruivo/flutter_file_picker#1071]
Could be nice to update dependencies to fix issue:
```
file_picker 4.6.1 depends on ffi ^1.1.2
pub get failed (1; So, because app depends on both device_info_plus ^4.0.1 and file_picker ^4.6.1, version solving failed.)
exit code 1
```

**Comment by yegor-pelykh** [comment]
I also need an updated file-picker, with a dependency on ffi version 2.0.1 or greater.
When can you make this upgrade?

**Comment by Far-Se** [comment]
> I also need an updated file-picker, with a dependency on ffi version 2.0.1 or greater. When can you make this upgrade in `pub.dev`?

Use this: https://pub.dev/packages/filepicker_windows
Had the same issue, can't wait until they upgrade the version.

**Comment by yegor-pelykh** [comment]
@Far-Se unfortunately, I need version for Web

**Comment by Far-Se** [comment]
> @Far-Se unfortunately, I need version for Web

Then you only need this file: https://github.dev/miguelpruivo/flutter_file_picker/blob/c321e9d8c9ac87f7607d2957b1e2fc072c461c60/lib/_internal/file_picker_web.dart#L38
I think you need to make some changes still.

**Comment by yegor-pelykh** [comment]
@Far-Se This is clear. But it's still better to have a fully fledged third-party package supported by someone.
And the developer only needs to change the three digits of the version in pubspec.yaml 🙂

**Comment by zmeggyesi** [comment]
@miguelpruivo Is there anything we can do to help this along? It sounds like there's a real community need for an up-to-date version...

**Comment by holdenhinkle** [comment]
Someone submitted a PR to fix this - https://github.com/miguelpruivo/flutter_file_picker/pull/1066

**Comment by sergmister** [comment]
Quick fix based on #1066
```
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: b108b98d2f2623bddedb6e5dd7a07d137430e670
```

**Comment by MrCsabaToth** [comment]
Oh, that PR is nice, it has lint related changes too!
Please merge @miguelpruivo

**Comment by miguelpruivo** [comment]
Sorry I didn't look much into this repo's issues lately. On it! 💪🏻

**Comment by miguelpruivo** [comment]
Merged.
