### ISSUE TITLE
The App uses an insecure Random Number Generator

### ISSUE THREAD

**Issue by mutairibassam** [miguelpruivo/flutter_file_picker#1073]
**Describe the bug**
- CWE: CWE-330: Use of Insufficiently Random Values
- OWASP Top 10: M5: Insufficient Cryptography 
- OWASP MASVS: MSTG-CRYPTO-6

**Platform**
- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android.

**How are you picking?**
Code explanation.

**Details to reproduce the issue**
- Use the package in Android Application.
- Generate an APK file.
- Scan the APK using [mobSF](https://github.com/MobSF/Mobile-Security-Framework-MobSF) static analyzer.
- Check the Code Analysis section.

**Error Log**
<img width="1278" alt="Screen Shot 1443-12-20 at 9 57 43 PM" src="https://user-images.githubusercontent.com/54819958/179827935-bf06d9a9-e2b1-421b-aa67-44cb995fed02.png">

**Screenshots and/or video**
![Screen Shot 1443-12-19 at 2 57 00 PM](https://user-images.githubusercontent.com/54819958/179830503-c55c2062-2609-4ab4-b492-1a9ff51bf973.png)

**Flutter Version details**
[✓] Flutter (Channel stable, 3.0.4, on macOS 11.4 20F71 darwin-x64, locale
    en-SA)
    • Flutter version 3.0.4 at /Users/Bassam/Documents/sdks/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

**Comment by miguelpruivo** [comment]
There's no point to add complexity to this number, it works just as a time stamp (which would be even less "secure" from your perspective) to name the picked/cached files into the app's container. On a ideal scenario, the files would use the original name, so the number is just a fallback.

Looks like what you've there reported was some code analysis that found "numbers" in the code out of context. Not everything needs to have cryptography. 😄

**Comment by mutairibassam** [comment]
@miguelpruivo I can understand your point. I've been thinking about replacing the random number with millisecond timestamp. What do you think?

I tested the application with the below change and all cases were successful and the application behaved as expected.

Please consider this change as it will help enterprise developers to not be flagged by security tools. Also, it might be helpful to be used as a reference to sort the files by latest.

The change simply replace `new Random().nextInt(100000)` with `System.currentTimeMillis()`

Original Code:
https://github.com/miguelpruivo/flutter_file_picker/blob/b4712b8b8bfe0a373891f45f97fae928563ee969/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L131

Modified Code:
```java
 final String path = context.getCacheDir().getAbsolutePath() + "/file_picker/" + (fileName != null ? fileName : System.currentTimeMillis()); 
```

**Comment by miguelpruivo** [comment]
I am myself an enterprise dev and that's not an issue, because despite analysis tools, in the end, one should indeed evaluate what's really an issue or not 😄 

Anyhow, if it's better for you to use the milliseconds instead of just a random number, just issue a PR.
