### ISSUE TITLE
Crash app when user canceled the picker

### ISSUE THREAD

**Issue by Cuongdt1996** [miguelpruivo/flutter_file_picker#1074]
Platform:
Android 11.
Log:
E/AndroidRuntime( 8331): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
E/AndroidRuntime( 8331): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5182)
E/AndroidRuntime( 8331): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5223)
E/AndroidRuntime( 8331): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 8331): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8331): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8331): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2154)
E/AndroidRuntime( 8331): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8331): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 8331): 	at android.app.ActivityThread.main(ActivityThread.java:8107)
E/AndroidRuntime( 8331): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8331): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 8331): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by miguelpruivo** [comment]
What's the `minSdk`, `targetSdk` and `compileSdk`?

**Comment by AMBE1203** [comment]
Hello.
minSdk: 24
targetSdk: 31
compileSdk: 31

**Comment by Cuongdt1996** [comment]
Hello.
minSdk: 24
targetSdk: 31
compileSdk: 31
