### ISSUE TITLE
ios File selection issue

### ISSUE THREAD

**Issue by praveenjaiswal16** [miguelpruivo/flutter_file_picker#1079]
Could not load the picked given file: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x282d59650 {Error Domain=NSCocoaErrorDomain Code=4099 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x282df3b70 {Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 61967 on anonymousListener or serviceListener was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 61967 on anonymousListener or serviceListener was invalidated from this process.}}}}}

**Comment by praveenjaiswal16** [comment]
this issue occurred when the app installing the first time and selected more than 200 images

**Comment by ValentinVignal** [comment]
I have a pretty similar issue when trying to pick images from the gallery on iOS:

```dart
await FilePicker.platform.pickFiles(
    type: FileType.image,
    allowMultiple: true,
  )
```

```
Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x6000021fc030 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x6000021fc270 {Error Domain=PHAssetExportRequestErrorDomain Code=0 "The operation couldn’t be completed. (PHAssetExportRequestErrorDomain error 0.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (PHAssetExportRequestErrorDomain error 0.), NSUnderlyingError=0x6000021fc2d0 {Error Domain=PAMediaConversionServiceErrorDomain Code=2 "The operation couldn’t be completed. (PAMediaConversionServiceErrorDomain error 2.)" UserInfo=0x600002e30c60 (not displayed)}}}}}}, null)
```
