### ISSUE TITLE
[iOS] Document picker is broken when MEDIA is disabled

### ISSUE THREAD

**Issue by martingeorgiu** [miguelpruivo/flutter_file_picker#1080]
**Describe the bug**
When you set `Pod::PICKER_MEDIA = false` and `Pod::PICKER_AUDIO = false` in `Podfile` and you want to pick just documents, then the plugin is partially broken on iOS. If you trigger the popup via `pickFiles()` and press "Cancel" to cancel it, everything works fine. But when you drag the topbar downwards instead of pressing "Cancel" button, then the Future does not complete. The cause of the issue is that `presentationControllerDidDismiss` method (which is called when the topbar is dragged downwards) in `FilePickerPlugin.m` is wrapped in `#ifdef PICKER_MEDIA` so it is not present when the PICKER_MEDIA is disabled.

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
15.5

**Comment by martingeorgiu** [comment]
Hello @miguelpruivo, could you please reopen the issue? It is still actual, so it should be at least open:)

**Comment by stephane-archer** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/1628
