### ISSUE TITLE
Since July 20 i cant upload updates to my app in playStore due to QUERY_ALL_PACKAGES permission

### ISSUE THREAD

**Issue by yuber83** [miguelpruivo/flutter_file_picker#1085]
HI,
I was working very well with file_picker file_picker: ^4.5.1 until july 20
since that day i can not send updates to my app, because google says QUERY_ALL_PACKAGES permissions y not needed,
I only pick a kml file,
I saw in the log 
ADDED from [:file_picker] /home/yvasquez/development/proyectos/firu_reader/build/file_picker/intermediates/merged_manifest/release/AndroidManifest.xml:13:21-69
uses-permission#android.permission.QUERY_ALL_PACKAGES

I dont know how to restrict this permission, 
please someone can help me?

Sorry for my english.

**Comment by yuber83** [comment]
I was confiused. The problem was on another package

**Comment by parammittal16** [comment]
@yuber83 which package was causing the issue can you please help ?

**Comment by yuber83** [comment]
Hi,
In my case the package was
 external_app_launcher

https://es.stackoverflow.com/questions/549159/flutter-google-play-problema-con-publicaci%c3%b3n-query-all-packages/550657#550657


I Hope this help you.
