### ISSUE TITLE
filepicker can't use in android device . it showing unexpected lock protocol.

### ISSUE THREAD

**Issue by muhammedsibil** [miguelpruivo/flutter_file_picker#1088]
A problem occurred configuring project ':file_picker'.
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unexpected lock protocol found in lock file. Expected 1, found 0.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':file_picker' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':file_picker' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip         
classpath 'com.android.tools.build:gradle:7.1.2'

**Comment by xiaocode337317439** [comment]
log: I/FilePickerDelegate(30584): User cancelled the picker request

Image not available on Android device

```dart
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      allowMultiple: true,
    );
   // result == null
```
