### ISSUE TITLE
file_picker get wrong filePath, how to get a real path

### ISSUE THREAD

**Issue by tangbl93** [miguelpruivo/flutter_file_picker#1089]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**

> - file_picker: ^5.0.0
> - android; huawei p20
> - PS: only select from "File Manager" is wrong, other entry ok

When I select the file from the "File Manager" -> 'MyPhone' I get a wrong path. How should I get a real path?

the wrong path
```
/data/user/0/com.weibai.xxpie_photographer_flutter.host/cache/file_picker/3073977
```

**Platform**

- [x ] Android

**Platform OS version**
What version did it happen?

huawei p20, android 9.0

**How are you picking?**

```
FilePickerResult? result = await FilePicker.platform.pickFiles();
String? filePath = result?.files.single.path;
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by abhi16180** [comment]
> Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.
> 
> Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.
> 
> **Describe the bug**
> 
> > * file_picker: ^5.0.0
> > * android; huawei p20
> > * PS: only select from "File Manager" is wrong, other entry ok
> 
> When I select the file from the "File Manager" -> 'MyPhone' I get a wrong path. How should I get a real path?
> 
> the wrong path
> 
> ```
> /data/user/0/com.weibai.xxpie_photographer_flutter.host/cache/file_picker/3073977
> ```
> 
> **Platform**
> 
> * [x ] Android
> 
> **Platform OS version** What version did it happen?
> 
> huawei p20, android 9.0
> 
> **How are you picking?**
> 
> ```
> FilePickerResult? result = await FilePicker.platform.pickFiles();
> String? filePath = result?.files.single.path;
> ```
> 
> **Details to reproduce the issue** Provide all the details to reproduce the issue.
> 
> **Error Log** Please, post the _full_ console log of your issue, if applicable.
> 
> **Screenshots and/or video** If applicable, add screenshots or video to help explain your problem.
> 
> **Flutter Version details** Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
> 
> **Additional context** Add any other context about the problem here.

This issue is android specific. File_picker caches files and then retrieves path from cached directories instead actual path.
I have tweaked it and it will fetch the actual path  except when  downloads directory files are chosen(If you pick files from downloads folder it will cache and retrieve cached file path).
You can import this to your project and check it out.
[https://github.com/abhi16180/flutter_file_picker](url)

**Comment by tangbl93** [comment]
@abhi16180 thank you, it's works perfect.

**Comment by Nuyoahhjh** [comment]
> > Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.
> > Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.
> > **Describe the bug**
> > > * file_picker: ^5.0.0
> > > * android; huawei p20
> > > * PS: only select from "File Manager" is wrong, other entry ok
> > 
> > 
> > When I select the file from the "File Manager" -> 'MyPhone' I get a wrong path. How should I get a real path?
> > the wrong path
> > ```
> > /data/user/0/com.weibai.xxpie_photographer_flutter.host/cache/file_picker/3073977
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Platform**
> > 
> > * [x ] Android
> > 
> > **Platform OS version** What version did it happen?
> > huawei p20, android 9.0
> > **How are you picking?**
> > ```
> > FilePickerResult? result = await FilePicker.platform.pickFiles();
> > String? filePath = result?.files.single.path;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Details to reproduce the issue** Provide all the details to reproduce the issue.
> > **Error Log** Please, post the _full_ console log of your issue, if applicable.
> > **Screenshots and/or video** If applicable, add screenshots or video to help explain your problem.
> > **Flutter Version details** Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
> > **Additional context** Add any other context about the problem here.
> 
> This issue is android specific. File_picker caches files and then retrieves path from cached directories instead actual path. I have tweaked it and it will fetch the actual path except when downloads directory files are chosen(If you pick files from downloads folder it will cache and retrieve cached file path). You can import this to your project and check it out. [https://github.com/abhi16180/flutter_file_picker](url)

Why does 8.1.3 have the same problem?

**Comment by abhi16180** [comment]
> > > Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.
> > > Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.
> > > **Describe the bug**
> > > > * file_picker: ^5.0.0
> > > > * android; huawei p20
> > > > * PS: only select from "File Manager" is wrong, other entry ok
> > > 
> > > 
> > > When I select the file from the "File Manager" -> 'MyPhone' I get a wrong path. How should I get a real path?
> > > the wrong path
> > > ```
> > > /data/user/0/com.weibai.xxpie_photographer_flutter.host/cache/file_picker/3073977
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Platform**
> > > 
> > > * [x ] Android
> > > 
> > > **Platform OS version** What version did it happen?
> > > huawei p20, android 9.0
> > > **How are you picking?**
> > > ```
> > > FilePickerResult? result = await FilePicker.platform.pickFiles();
> > > String? filePath = result?.files.single.path;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Details to reproduce the issue** Provide all the details to reproduce the issue.
> > > **Error Log** Please, post the _full_ console log of your issue, if applicable.
> > > **Screenshots and/or video** If applicable, add screenshots or video to help explain your problem.
> > > **Flutter Version details** Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
> > > **Additional context** Add any other context about the problem here.
> > 
> > This issue is android specific. File_picker caches files and then retrieves path from cached directories instead actual path. I have tweaked it and it will fetch the actual path except when downloads directory files are chosen(If you pick files from downloads folder it will cache and retrieve cached file path). You can import this to your project and check it out. [https://github.com/abhi16180/flutter_file_picker](url)
> 
> Why does 8.1.3 have the same problem?

It's been reverted because of regressions. It didn't work on some later versions on Android as full permission is needed if you want to access the actual file path.
You can still check this, 
https://github.com/abhi16180/flutter_file_picker
