### ISSUE TITLE
Add option to remove caching files on android

### ISSUE THREAD

**Issue by abhi16180** [miguelpruivo/flutter_file_picker#1093]
In android file picker caches files before returning the path. This will cause issue when large files or multiple files are chosen

**Comment by bitjunk** [comment]
I ran into an issue due to the same! I don't understand why we are reading and storing the bytes in a way creating duplicate copies  instead of just using the original path and reading bytes on the fly when user requests for file data?

@abhi16180 That's not the default behavior though and it happens only when we set the `withData` flag to true. We could just read the path instead and use that to read file if needed and cache won't be clogged.

**Comment by abhi16180** [comment]
> I ran into an issue due to the same! I don't understand why we are reading and storing the bytes in a way creating duplicate copies instead of just using the original path and reading bytes on the fly when user requests for file data?
> 
> @abhi16180 That's not the default behavior though and it happens only when we set the `withData` flag to true. We could just read the path instead and use that to read file if needed and cache won't be clogged.

But  I haven't set withData flag to true.By default it is false ,I am not sure why is it still caching !

**Comment by bitjunk** [comment]
@abhi16180  Meant to say it would be an issue for large file/multiple files only if we cache the data which is apparently not the default behavior. Not sure how it would work if we don't use cache at all though? Need some place to store the picked files info right?

**Comment by abhi16180** [comment]
> @abhi16180 Meant to say it would be an issue for large file/multiple files only if we cache the data which is apparently not the default behavior. Not sure how it would work if we don't use cache at all though? Need some place to store the picked files info right?

Yeah but it is not just caching the paths I guess ,because if that is the case it wouldn't take much time to retrieve the files' path.
I have checked the same thing on windows ,it will retrieve the paths almost instantly no matter how large the file is .But in android it will cache the files. So number of files/size of file matters a lot. It is unnecessary to cache the files if we just wanna retrieve the paths of files. I don't think this is the efficient way to retrieve the paths.

**Comment by bitjunk** [comment]
@abhi16180 Oh gosh! Just checked the code and what you say is right. Here is the culprit  https://github.com/miguelpruivo/flutter_file_picker/blob/3d4d68078885d3b04a5d5d73814570896a8e1e84/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L125-L165

It does create a cached file regardless of `withData` flag.

**Comment by abhi16180** [comment]
> @abhi16180 Oh gosh! Just checked the code and what you say is right. Here is the culprit
> 
> https://github.com/miguelpruivo/flutter_file_picker/blob/3d4d68078885d3b04a5d5d73814570896a8e1e84/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L125-L165
> 
> It does create a cached file regardless of `withData` flag.

Yeah . We should use different approach for selecting files in android till someone fixes this.

**Comment by abhi16180** [comment]
@bitjunk 
I made some modifications to FileUtils.java 
It will cache only files which cannot be retrieved directly (Usually in downloads folder)
So if large files like videos or photos selected it will retrieve the path in no time now.
`    public static FileInfo openFileStream(final Context context, final Uri uri, boolean withData) {

       
        FileOutputStream fos = null;
        String path = getPath(uri, context);
        File file;
        String fileName;
        final FileInfo.Builder fileInfo = new FileInfo.Builder();

       
        if (path == null) {
            Log.i(TAG, "Caching from URI: " + uri.toString());
            fileName = FileUtils.getFileName(uri, context);
            path = context.getCacheDir().getAbsolutePath() + "/file_picker/"
                    + (fileName != null ? fileName : System.currentTimeMillis());
            file = new File(path);
            if (!file.exists()) {
                file.getParentFile().mkdirs();
                try {
                    fos = new FileOutputStream(path);
                    try {
                        final BufferedOutputStream out = new BufferedOutputStream(fos);
                        final InputStream in = context.getContentResolver().openInputStream(uri);

                        final byte[] buffer = new byte[8192];
                        int len = 0;

                        while ((len = in.read(buffer)) >= 0) {
                            out.write(buffer, 0, len);
                        }

                        out.flush();
                    } finally {
                        fos.getFD().sync();
                    }
                } catch (final Exception e) {
                    try {
                        fos.close();
                    } catch (final IOException | NullPointerException ex) {
                        Log.e(TAG, "Failed to close file streams: " + e.getMessage(), null);
                        return null;
                    }
                    Log.e(TAG, "Failed to retrieve path: " + e.getMessage(), null);
                    return null;
                }
            }
        } else {
            Log.i(TAG, "Uncached file path: " + path);
            fileName = FileUtils.getFileName(uri, context);
            file = new File(path);

        }

        Log.d(TAG, "File loaded and cached at:" + path);

        if (withData) {
            loadData(file, fileInfo);
        }

        fileInfo
                .withPath(path)
                .withName(fileName)
                .withUri(uri)
                .withSize(Long.parseLong(String.valueOf(file.length())));

        return fileInfo.build();
    }`

**Comment by rlueders** [comment]
> I made some modifications to FileUtils.java

@abhi16180 , Did you commit these changes and submit a PR?  It looks like this would close [another bug ](https://github.com/miguelpruivo/flutter_file_picker/issues/561) that has been open for almost two years.

**Comment by abhi16180** [comment]
> > I made some modifications to FileUtils.java
> 
> @abhi16180 , Did you commit these changes and submit a PR? It looks like this would close [another bug ](https://github.com/miguelpruivo/flutter_file_picker/issues/561) that has been open for almost two years.

Yeah i have submitted PR.

**Comment by miguelpruivo** [comment]
@abhi16180 there are some things that needs to be polished in your PR, hence the reason why it hasn't be merged yet. Please, take a look.

**Comment by miguelpruivo** [comment]
@abhi16180 have you tried it on latest SDKs? Because if I recall correctly, one could not access the paths directly without caching since SDK 29. Only through URIs (which are useless for Dart `File` instances).

**Comment by abhi16180** [comment]
> @abhi16180 have you tried it on latest SDKs? Because if I recall correctly, one could not access the paths directly without caching since SDK 29. Only through URIs (which are useless for Dart `File` instances).

I have added missing methods and tested it on sdk version 33 ,its working properly and currently I am using it for my [app](https://github.com/abhi16180/photon) also.

![withoutcache](https://user-images.githubusercontent.com/64468853/190469752-dbc1efa4-6f45-4465-a583-7c97f79167bf.png)


![withcache](https://user-images.githubusercontent.com/64468853/190469763-4c81878e-0590-44e1-8b72-97a3b7139e98.png)

**Comment by abhi16180** [comment]
v5.2.0 fixes this issue.

**Comment by dattasid** [comment]
@abhi16180 How is this fixed? I am using 8.1.2 and FileUtils.java still unconditionally caches files.

Also, it will cache the same file multiple times without any checks. There is also no cache management eg: set cache space usage limits. That makes this package almost unusable for media apps handling large files.

**Comment by abhi16180** [comment]
> @abhi16180 How is this fixed? I am using 8.1.2 and FileUtils.java still unconditionally caches files.
> 
> Also, it will cache the same file multiple times without any checks. There is also no cache management eg: set cache space usage limits. That makes this package almost unusable for media apps handling large files.

@dattasid Hi my PR has been reverted after some issue observed on android 11+ AFAIK. 
This is my fork- https://github.com/abhi16180/flutter_file_picker.  It was working on my device, but I am not sure if it works on all devices running android 10+. Its been long since I touched the codebase, please go through my commits and modify based on your use-case.
