### ISSUE TITLE
Typo in the wiki (FireStorage -> Firebase Storage)

### ISSUE THREAD

**Issue by nilsreichardt** [miguelpruivo/flutter_file_picker#1102]
There is a typo in the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ) (at the question "Q: How do I access the path on Web?":

> If you want to create a File instance to upload it somewhere, like FireStorage, you can do so with the bytes directly.

But I think it should be:

> If you want to create a File instance to upload it somewhere, like Firebase Storage, you can do so with the bytes directly.

**Comment by miguelpruivo** [comment]
Amended. Thank you.
