### ISSUE TITLE
V5.0.1 uses or overrides a deprecated API (Warning ⚠️) SDK 33

### ISSUE THREAD

**Issue by jyfer** [miguelpruivo/flutter_file_picker#1103]
*/.pub-cache/hosted/pub.dartlang.org/file_picker-5.0.1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java uses or overrides a deprecated API.

**Platform**

- [x ] Android
compileSdkVersion 33

**Comment by miguelpruivo** [comment]
Fixed with 5.1.0.
