### ISSUE TITLE
After some seconds the file reference doesn't exist anymore

### ISSUE THREAD

**Issue by dannycortesv** [miguelpruivo/flutter_file_picker#1108]
Hello guys, thanks for amazing plugin, i use it to pick files and upload to our server, but while user fill out a form it takes some time, once we are ready to upload video that file reference we got from picker indicates that file doesn't exist anymore. Is there any limit of time once we pick a file where the file reference expires?

**Comment by miguelpruivo** [comment]
I assume this is happening on iOS. Typically on iOS the system gets rid of the file if needed, which is why you should move/cache it to somewhere inside your app's temp directory if you want to make sure it's there (even after closing the app). That way, you can manage/handle the files yourself.
