### ISSUE TITLE
MissingPluginException on pickFiles() call

### ISSUE THREAD

**Issue by ralfeus** [miguelpruivo/flutter_file_picker#1110]
I try to open the file using `FilePicker.platform.pickFiles()`. I've just added `file_picker` and `open_file` to my `pubspec.yaml` and added following code:
```
    final result = await FilePicker.platform.pickFiles(allowMultiple: false);
    if (result == null) {
      fileName = result!.files.first.name;
    }
```
At the Android it works fine. But at Linux and Windows desktops at the first line I get an error:
> MissingPluginException (MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker))

file_picker is newly installed and there was no any previous version installed ever before.

Versions:
dart: 2.17.6
flutter: 3.0.5
file_picker: 3.0.4
linux: Ubuntu 22.04.1 LTS

**Comment by manjotsidhu** [comment]
I am facing the same issue on Windows 11.

flutter doctor -
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22621.160], locale en-IN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.71.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
```
```
❯ dart --version
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_x64"
```

**Comment by manjotsidhu** [comment]
@ishangavidusha @miguelpruivo Any help ?

**Comment by miguelpruivo** [comment]
This typically happen on a bad installation or build of the plugin(s). Just make sure you clear your build folder and dependencies cache and then run `flutter pub get` again before building. Might be a bit trial & error, but this happens with different dependencies, it's not related with a single one.
