### ISSUE TITLE
app lost connection in debug 

### ISSUE THREAD

**Issue by abdooobsl** [miguelpruivo/flutter_file_picker#1111]
hi in desktop in windows debug mood when i open picker after 5 seconds it lost connection without error and close app i have tested the app in release mode worked fine and in other platform 

![image](https://user-images.githubusercontent.com/30108060/188871262-7744fd59-d471-414a-8468-19a4f6cec78a.png)
s it worked tried flutter clean and upgrade package to latest

C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, 3.4.0-19.0.pre.88, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.4.0-19.0.pre.88 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96b72232bd (22 hours ago), 2022-09-06 09:29:05 -0400
    • Engine revision 7595e09968
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Eng Abdelrahman\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\Eng Abdelrahman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0

**Comment by miguelpruivo** [comment]
Looks like an issue related with the IDE or developing environment. Please, check your installation.
