### ISSUE TITLE
file_picker package installation failed because of open_file and ffi packages

### ISSUE THREAD

**Issue by carpentierchloe** [miguelpruivo/flutter_file_picker#1114]
I am not able to install the package because of open_file and ffi versions... What to do ?

_Because open_file 3.2.1 depends on ffi ^1.0.0 and no versions of open_file match >3.2.1 <4.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
So, because edouard_app depends on both ffi ^2.0.1 and open_file ^3.2.1, version solving failed.
pub get failed (1; So, because edouard_app depends on both ffi ^2.0.1 and open_file ^3.2.1, version solving failed.)_

**Comment by navaronbracke** [comment]
The latest version of `file_picker` depends on `ffi: 2.0.1` or higher.
You are depending on `open_file: 3.2.1` which requires `ffi: 1.0.0` or higher, but lower than the next major version (which is `ffi: 2.0.0`)

You are going to need to upgrade `to a version of `open_file` that requires `ffi: 2.0.1` or higher.
It seems that the original `open_file` has not been updated in a while.

There is however a newer version of a similar package (It is a fork of the one you used, I assume that the original is not being maintained anymore)

https://pub.dev/packages/open_filex

This package has been updated to `ffi: 2.0.1`
