### ISSUE TITLE
Could not build the precompiled application for the device.

### ISSUE THREAD

**Issue by Peisf** [miguelpruivo/flutter_file_picker#1118]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/7624529/189844677-26057daf-dfb8-45a1-980d-3ca06be6ee1f.png">

`can you fix this bug in Xcode 14?`

**Comment by appcapsergen** [comment]
Same issue
https://github.com/flutter/flutter/issues/111475

**Comment by miguelpruivo** [comment]
Dup of #1121.
