### ISSUE TITLE
I get an unexpected path by `file_picker`

### ISSUE THREAD

**Issue by YowFung** [miguelpruivo/flutter_file_picker#1119]
**My Code:**
```dart
filePath = await FilePicker.platform.saveFile(
  dialogTitle: "Select a path to save this configuration project",
  fileName: "configuration-20220913164930.touch10",
  type: FileType.custom,
  allowedExtensions: [".touch10"],
  lockParentWindow: true,
);
print("--------- The file path is [$filePath].");
```

**The path I provided:**
Note that it must be in the root directory of drive D; otherwise, it will not be recured.
![image](https://user-images.githubusercontent.com/26346560/189858474-f0056036-76ea-4340-a32b-590befeccdff.png)

**Expected:**
Output `The file path is [D:\configuration-202.touch10].`.

**Actual:**
Output `The file path is [D:\configuration-202.touch10\touch10].`. The `\touch10` character is added at the end.

**My Environment:**
- Flutter 3.3.0 (Dart 2.18.0)
- Windows 10 Enterprise LTSC 1809
- file_picker 4.6.1

**Comment by YowFung** [comment]
Hello? Any progress?

**Comment by YowFung** [comment]
Hello? Any progress?

**Comment by miguelpruivo** [comment]
@philenius are you still able to help out with desktop issues? Thank you.
