### ISSUE TITLE
 variable TIRAMISU not found in version code.

### ISSUE THREAD

**Issue by kjawadDeveloper2** [miguelpruivo/flutter_file_picker#1124]
Getting same issue like this on this packege. 

https://github.com/react-native-image-picker/react-native-image-picker/issues/2018

**Comment by alexmercerind** [comment]
@kjawadDeveloper2 Change `compileSdkVersion` in build.gradle to 33 OR pin dependency to `5.0.1` in `pubspec.yaml`.

**Comment by deakjahn** [comment]
The problem with this approach is that we're not supposed to hardwire the SDK version any more but to rely on `flutter.compileSdkVersion` as set in the Flutter SDK. So, plugin developers shouldn't force us to advance it manually and to rely on versions the SDK itself doesn't dictate yet.
