### ISSUE TITLE
Pick image with space in the path

### ISSUE THREAD

**Issue by devnoaman** [miguelpruivo/flutter_file_picker#1125]
i am running flutter 3.1 on macos on m1 , and the file_picker version is `file_picker: ^5.0.1`

when i try to open a image with space in the path i get this error 

```
(FileSystemException: Cannot open file, path = '/Volumes/Untitled/Users/noamanmonther/Downloads/Noaman2022-09-14 15/53/13.267108.png' (OS Error: No such file or directory, errno = 2))
```
is there a way to open the image without the need of removing the spaces from the path?

**Comment by miguelpruivo** [comment]
Could you try with the new version?
