### ISSUE TITLE
XCode 14 Build error: Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by cksoft0807** [miguelpruivo/flutter_file_picker#1127]
Because of the dependency DKImagePickerController i can not compile for IOS with XCode 14 (M1 System).

Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/Users/carstenkunsken/Documents/Flutter/test123/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:67:5

**Comment by dev-thinks** [comment]
any way we can overcome this issue?. bump for me as well. in XCode 14 M1.

**Comment by samtoya** [comment]
+1

**Comment by CHA7R1K** [comment]
My corrent workaround is change global platform in Podfile to :
`platform :ios, '14'`

**Comment by miguelpruivo** [comment]
Dup of #1121.

**Comment by samtoya** [comment]
This also did not work for me.

**Comment by dev-thinks** [comment]
yes .workaround is not working. (bumping to ios 14 in pod or setting up the development team explicitly)

**Comment by sticksen** [comment]
@miguelpruivo I don´t think this is a dup.  
The mentioned Issue is about signing, this one is about (possibly) a new Swift language version that was shipped with Xcode 14.

**Comment by miguelpruivo** [comment]
@sticksen anyway, this issue should be opened in the DKImagePickerController repo and followed there since it relates directly to it.

**Comment by sticksen** [comment]
@miguelpruivo Agreed, seems to be already fixed there: https://github.com/zhangao0086/DKImagePickerController/issues/705

**Comment by miguelpruivo** [comment]
@sticksen looks like the user updated the post saying that isn't also working, despite the 4.3.4 update.

**Comment by mugikhan** [comment]
+1 Also not working for me

**Comment by samtoya** [comment]
+1 Did not work for me

**Comment by SamTienz** [comment]
How can I update the DKImagePickerController to 4.3.4 by flutter `pub get`?

**Comment by miguelpruivo** [comment]
> How can I update the DKImagePickerController to 4.3.4 by flutter `pub get`?

You'll have to override the dependency in your podfile, but that doesn't solve it.

**Comment by MrObe13** [comment]
Same issue

**Comment by amantoux** [comment]
Check this out https://github.com/zhangao0086/DKImagePickerController/issues/705#issuecomment-1257483269

**Comment by miguelpruivo** [comment]
Let me know if someone find a solution for this or issue a PR with it. I don't really have much time as of now to investigate it, but I'll have an eye on it since this is a prior issue.

**Comment by SamTienz** [comment]
Hi, I'm archive successfully.

I'm not sure can help you guys. but still share my steps.

### 1. Make sure your `DKImagePickerController` is 4.3.4
I'm follow this comment in [issue](https://github.com/zhangao0086/DKImagePickerController/issues/705#issuecomment-1250706936) change my `podfile` to update my `DKImagePickerController` to 4.3.4

### 2. Add `config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'`
And follow this comment in [issue](https://github.com/zhangao0086/DKImagePickerController/issues/705#issuecomment-1257506474) make `DKImagePickerController` don't need a development team

### 3. Re - pod install completely
First, delete `podfile.lock`.
And I run these command sequentially
`pod deintegrate`
`pod repo update` (Maybe someone did [this](https://github.com/miguelpruivo/flutter_file_picker/issues/999#issuecomment-1072348845))
`pod install`

### 4. Make sure your target `Enable Bitcode` is `NO` in the build setting in Xcode14

### 5. Clean build folder in Xcode

### 6. Archive

### 7. I'm archive successfully and upload my app to TestFlight without any wrong message.

**Comment by dev-thinks** [comment]
Workaround mentioned in here, https://github.com/zhangao0086/DKImagePickerController/issues/705#issuecomment-1257483269 and https://github.com/zhangao0086/DKImagePickerController/issues/705#issuecomment-1257506474

are working.
we have to make sure we are deleting the existing podfile.lock before updating the pod.

**Comment by savasadar** [comment]
`pod update` working for me instead of `pod install`
