### ISSUE TITLE
Support for Safe Access Framework 

### ISSUE THREAD

**Issue by BataraSurya** [miguelpruivo/flutter_file_picker#1130]
I was trying to use this plugin on targe API 33 but then it is not permitted because as of API 30 all file access has been blocked and dev must adapt Safe Access Framework for file operation. I hope this will be resolved soon.

**Comment by miguelpruivo** [comment]
What if you try with 5.1.0, does it work? Just to make sure it wasn't a regression.

**Comment by BataraSurya** [comment]
> What if you try with 5.1.0, does it work? Just to make sure it wasn't a regression.

apparently it was indeed a regression. It works fine with version 5.1.0!

**Comment by miguelpruivo** [comment]
@abhi16180 another regression if you want to take a look.

**Comment by miguelpruivo** [comment]
@BataraSurya this was now reverted with 5.2.0+1.

**Comment by BataraSurya** [comment]
> @BataraSurya this was now reverted with 5.2.0+1.

Awesome Thanks
