### ISSUE TITLE
Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by lucsout** [miguelpruivo/flutter_file_picker#1131]
**Describe the bug**
On Web, when i try to pick a file, it doesn't show any dialog, console gives this error:

`Uncaught Unsupported operation: Platform._operatingSystem
    at Object.c (http://app.edilab.it/portalerevisoriagci/main.dart.js:4446:3)
    at Object.b7D (http://app.edilab.it/portalerevisoriagci/main.dart.js:7845:15)
    at Object.b7E (http://app.edilab.it/portalerevisoriagci/main.dart.js:7868:16)
    at http://app.edilab.it/portalerevisoriagci/main.dart.js:114611:22
    at a.<computed> [as v8] (http://app.edilab.it/portalerevisoriagci/main.dart.js:32:36)
    at http://app.edilab.it/portalerevisoriagci/main.dart.js:114618:24
    at a.<computed> [as aY2] (http://app.edilab.it/portalerevisoriagci/main.dart.js:32:36)
    at Object.b2g (http://app.edilab.it/portalerevisoriagci/main.dart.js:8761:6)
    at http://app.edilab.it/portalerevisoriagci/main.dart.js:114632:23
    at a.<computed> [as aPe] (http://app.edilab.it/portalerevisoriagci/main.dart.js:28:34)`

Everything works as expected in debug mode.

Platform

- [ ]  Android
- [ ]  iOS
- [x]  Web
- [ ] Desktop

Flutter version: 3.3.0

**Comment by keyfayaz** [comment]
Experiencing the same issue

**Comment by countfloyd** [comment]
I've found that if I replace
```
FilePicker.platform.pickFiles
```

with

```
FilePickerWeb.platform.pickFiles
```

it works. Of course, it only works on web.

**Comment by sarbogast** [comment]
If I try @countfloyd 's workaround, my app doesn't build anymore for iOS and Android because it uses some web specific code. Please help.

**Comment by abdugaliyev** [comment]
> FilePickerWeb.platform.pickFiles

You can use kIsWeb constant, 

`if (kIsWeb) {
  // running on the web!
} else {
  // NOT running on the web! You can check for additional platforms here.
}`

**Comment by abdugaliyev** [comment]
> I've found that if I replace
> 
> ```
> FilePicker.platform.pickFiles
> ```
> 
> with
> 
> ```
> FilePickerWeb.platform.pickFiles
> ```
> 
> it works. Of course, it only works on web.

Thanks a lot!

**Comment by lucsout** [comment]
I would add this on documentation, so anyone could benefit! 😁

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: abdugaliyev ***@***.***>
Inviato: Thursday, October 6, 2022 8:45:31 AM
A: miguelpruivo/flutter_file_picker ***@***.***>
Cc: lucsout ***@***.***>; Author ***@***.***>
Oggetto: Re: [miguelpruivo/flutter_file_picker] Unsupported operation: Platform._operatingSystem (Issue #1131)


I've found that if I replace

FilePicker.platform.pickFiles


with

FilePickerWeb.platform.pickFiles


it works. Of course, it only works on web.

Thanks a lot!

**Comment by sarbogast** [comment]
@abdugaliyev The kIsWeb constant is ineffective because FilePickerWeb is effectively in a different file (package:file_picker/_internal/file_picker_web.dart) that is internal by the way, and we should not import directly, and that file itself imports dart:html that only compiles for web apps. If you try to compile this for mobile platforms, compilation fails, even if you use kIsWeb

**Comment by miguelpruivo** [comment]
Hum, I'm not aware of this issue. If someone finds out what's causing it, please issue a PR.

**Comment by sarbogast** [comment]
And yet it is still there and very problematic. 

---
Sébastien Arbogast
http://sebastien-arbogast.com

**Comment by lucsout** [comment]
I made it working by using this:

`FilePickerWeb.platform.pickFiles`

BUT, in order to make it compile on both windows and web, i had to use conditional compilation, which i think could be implemented inside the package itself. That's how it turned out:

A global file which contains the global definition (pickFile is defined in both picker_windows.dart and picker_web.dart, it has to be called the same way in order to be called correctly)


```
import 'package:file_picker/file_picker.dart';
import 'package:myproject/picker_implementation/picker_stub.dart'
    if (dart.library.io) 'package:myproject/picker_implementation/picker_windows.dart'
    if (dart.library.html) 'package:myproject/picker_implementation/picker_web.dart';

class PickerGeneric {
  Future<FilePickerResult?> pickFileGeneric() {
    return pickFile();
  }
```

and implementation (WEB):

```
import 'package:file_picker/_internal/file_picker_web.dart';
import 'package:file_picker/file_picker.dart';

Future<FilePickerResult?> pickFile() async {
  FilePickerResult? result =
      await FilePickerWeb.platform.pickFiles(withData: true);

  return result;
}

```

(WINDOWS):

```
import 'package:file_picker/file_picker.dart';

Future<FilePickerResult?> pickFile() async {
  FilePickerResult? result =
      await FilePicker.platform.pickFiles(withData: true);

  return result;
}

```

It compiles and works in both platform.

**Comment by gruvw** [comment]
I am still running into that exact issue in 2023.  
What is the official solution ?

**Comment by jawsandteeth** [comment]
Yes. Running flutter clean solved. Thanks @gruvw

**Comment by anujyadav140** [comment]
I had deployed my app on firebase and the filepicker was working fine on mobile (android) and even the local web ... but whenever i used it on the firebase domain i encountered this issue ...

flutter clean and then building the app and deploying it again SOLVED the issue for me. thanx.

**Comment by PrimeTimeTran** [comment]
Confirmed this worked for me as well sorta(I also upgraded Flutter and the dependencies.)

Thanks so much!

**Comment by unix14** [comment]
Thank you guys, made my day!!
