### ISSUE TITLE
pickFiles on version 5.2.0 doesn't work on Android 

### ISSUE THREAD

**Issue by alevittoria** [miguelpruivo/flutter_file_picker#1133]
Hi! I've updated the library to version 5.2.0 and with this when I try to take a file it says always that the file doesn't exist.
I downgraded it to 5.1.0 and it works like a charm. I think that the problem is linked to the new mechanism of caching.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform.pickFiles();
PlatformFile fileRes = result.files.single;
var exist = await file.exists();  //with 5.2.0 return false

```

**Comment by b14cknc0d3** [comment]
**me too** ```E/FilePickerUtils(21464): Document URI
E/FilePickerUtils(21464): External Document URI
E/FilePickerUtils(21464): Primary External Document URI
D/FrameIndicator(21464): support status: 1 0x746dcf4018 0x746dcf44c4
I/FilePickerUtils(21464): Uncached file path: /storage/emulated/0/Android/data/xxx/files/Download/Telegram/AddPurchasePrice.xlsx
D/FrameIndicator(21464): support status: 1 0x746dcf4018 0x746dcf44c4
E/FilePickerUtils(21464): File not found: /storage/emulated/0/Android/data/xxx/files/Download/Telegram/AddPurchasePrice.xlsx: open failed: ENOENT (No such file or directory)
D/FilePickerDelegate(21464): File path:[com.mr.flutter.plugin.filepicker.FileInfo@f0eab65]
E/flutter (21464): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Could not find End of Central Directory Record```

**Comment by axilesoft** [comment]
Maybe same issue:   getPath gets wrong path when open a zip in Picture dir

**Comment by abhi16180** [comment]
Which android version are you using ?
@b14cknc0d3 @alevittoria

**Comment by alevittoria** [comment]
Android 12, my device is a Samsung S20 FE

> Which android version are you using ? @b14cknc0d3 @alevittoria

**Comment by abhi16180** [comment]
> Android 12, my device is a Samsung S20 FE
> 
> > Which android version are you using ? @b14cknc0d3 @alevittoria

I'm still figuring out why this isn't working on some devices. I have used it with my own app and people tested it.

**Comment by abhi16180** [comment]
@b14cknc0d3  @alevittoria 
Can you please try and tell me if this is working you ? 
👇
[File-picker-fix](https://github.com/abhi16180/flutter_file_picker.git)

**Comment by miguelpruivo** [comment]
@abhi16180 this looks like a regression, I'll probably revert it until you find a fix.

**Comment by alevittoria** [comment]
> @b14cknc0d3 @alevittoria Can you please try and tell me if this is working you ? 👇 [File-picker-fix](https://github.com/abhi16180/flutter_file_picker.git)

I tried it but it doesn't resolve the issue. 
Nothing of particular into the console:

```
E/FilePickerUtils(10917): Getting for API 19 or abovecontent://com.android.externalstorage.documents/document/primary%3ADownload%2FTelegram%2Fmodel.zip
I/ViewRootImpl@70c4a8[MainActivity](10917): stopped(false) old=false
E/FilePickerUtils(10917): Document URI
E/FilePickerUtils(10917): External Document URI
E/FilePickerUtils(10917): Primary External Document URI
I/FilePickerUtils(10917): Uncached file path: /storage/emulated/0/Android/data/com.transformandlighting.emb3d/files/Download/Telegram/model.zip
...
D/FilePickerDelegate(10917): File path:[com.mr.flutter.plugin.filepicker.FileInfo@e87df62]
```

**Comment by miguelpruivo** [comment]
I reverted the 5.2.0 with 5.2.0+1 which should be working again until @abhi16180 understands why it broke functionality in some devices.

**Comment by abhi16180** [comment]
> I reverted the 5.2.0 with 5.2.0+1 which should be working again until @abhi16180 understands why it broke functionality in some devices.

I couldn't reproduce the issue , I will check it with some other device.
