### ISSUE TITLE
iPhone notch covers the part of the gallery

### ISSUE THREAD

**Issue by tobolski** [miguelpruivo/flutter_file_picker#1136]
iPhone notch covers the part of the gallery when picking photos. It seems that Safe Area is not applied to the photo tiles. It only appears on Photos tab; it is displayed correctly on Albums.

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Screenshots and/or video**
![unnamed](https://user-images.githubusercontent.com/13032980/191903056-dad8199e-0a40-4131-a316-dcb54e802016.png)

**Comment by miguelpruivo** [comment]
You'll want to open an issue in the [DKImagePickerController](https://github.com/zhangao0086/DKImagePickerController) which is the underlying package for some features of this package. If this doesn't happen with single pick, it's probably it.
