### ISSUE TITLE
Signatures are required for each run

### ISSUE THREAD

**Issue by sunjianan9900** [miguelpruivo/flutter_file_picker#1137]
**Describe the bug**

using 5.2.0

The signature needs to be set every time it is run on the real iPhone. Whether I run it inside Android studio or inside xCode, it won't start and the error message is as shown

![image](https://user-images.githubusercontent.com/10936316/191949349-a941e221-3e84-411e-a5dd-4783314f3d06.png)

![image](https://user-images.githubusercontent.com/10936316/191949461-e55920c5-b41d-432f-82a6-62ff751e8f2b.png)

**Platform**

iOS

**Platform OS version**
iOS 16.0
Xcode Version 14.0 (14A309)
 
 **Flutter version**
 [✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm (Rosetta),
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ Android SDK file not found
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] VS Code (version 1.71.0)

**Comment by sunjianan9900** [comment]
It's not my project file that needs to be signed, but this project's dependency DKPhotoGallery - DKPhotoGallery & DKImagePickerController-DKImagePickerController needs to be signed

**Comment by sunjianan9900** [comment]
![image](https://user-images.githubusercontent.com/10936316/191953995-9d258905-a4cf-4f0a-9158-02437118145e.png)
I chose to manage it automatically, but every time I open xcode, it fails

**Comment by sunjianan9900** [comment]
100% occurs when switching between debug and proflie modes

**Comment by miguelpruivo** [comment]
Related with #1121.
