### ISSUE TITLE
Improper compression with 120fps videos

### ISSUE THREAD

**Issue by rlueders** [miguelpruivo/flutter_file_picker#1139]
When setting allowCompression =  false, calls to pickFiles() skips compression when opening most video files on IOS.  Even 1+ GB files import in just a few seconds.    However, when opening a video file that is 120fps, the compression seems to be enabled despite allowCompression =  false.  The 120 fps video will take 3+ minutes to open because of the compression step. Also, the compressed video that is passed back to the app is encoded incorrectly as a 30 fps video while still having all of the original frames.  That is, it is now a 120 fps video playing back at 30fps (essentially slowmo).  Opening videos encoded as 30 and 60fps work fine.

I have only observed this behavior on IOS.

**Platform OS version**
IOS 16.0

**How are you picking?**
FilePicker.platform.pickFiles(type: FileType.video, allowCompression: false, withData: false, withReadStream: true);

**Error Log**
No errors or anything out of the ordinary in the log

**Flutter Version details**
Running Flutter 3.3.2

**Comment by miguelpruivo** [comment]
Could be something related with iOS 16. Might need investigation.
