### ISSUE TITLE
Can you change the way it runs on macOS?

### ISSUE THREAD

**Issue by rigroch** [miguelpruivo/flutter_file_picker#1145]
In summary, use Channel like iOS.

Please use beginSheetModal instead of runModal. (runModal works the same as the way uses osascript you were written.)

```
guard let keywindow = NSApplication.shared.keyWindow else {
    result(nil)
    return
}

NSOpenPanel().beginSheetModal(for: keywindow) { response in
    
}
```

It appears more beautiful appearance, and to solve the [issue](https://github.com/miguelpruivo/flutter_file_picker/issues/1059).

**Comment by stuartmorgan** [comment]
> runModal works the same as the way uses osascript you were written.

This isn't actually correct; an in-process `runModal` call would already be vastly better than `osascript`. The latter is not intended for use in GUI applications, and shows the dialog in *a completely separate process*, which creates significant issues around focus and window management.

**Comment by Hixie** [comment]
I imagine this would also fix https://github.com/miguelpruivo/flutter_file_picker/issues/1445

**Comment by navaronbracke** [comment]
Closing this issue as a duplicate of https://github.com/miguelpruivo/flutter_file_picker/issues/1492 since that issue has a better explanation of what needs to change.
