### ISSUE TITLE
Not working for Web

### ISSUE THREAD

**Issue by alex9153** [miguelpruivo/flutter_file_picker#1146]
`FilePickerResult? result = await FilePicker.platform.pickFiles(allowMultiple: false, type: FileType.custom, allowedExtensions: ["txt"]);`

result is always null

**Comment by alexlozdev** [comment]
import 'dart:io' as IO;

if you use dart:io package in that file , please use it like above.
After that, got the file result normally.

**Comment by zambetpentru** [comment]
Having this issue as well only on some clients, it's proving hard to track down. Any ideas on how to isolate it?  As mentioned in another issue I will try to extend the timeout.


FilePickerResult? files = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowMultiple: enableUploadMultiple,
      allowedExtensions: ['pdf'],
      allowCompression: false, 
      withData: false, 
      withReadStream: true, 
    );

**Comment by zambetpentru** [comment]
I think I have an answer for this, it was particularly affecting Safari. It appears there are multiple events triggered sometimes.

```
 void changeEventListener(e) {
      if (changeEventTriggered) {
        return;
      }

      //Ignore this event if we don't yet have the list of files
      if (uploadInput.files != null) {
        changeEventTriggered = true;
      }

```

**Comment by zambetpentru** [comment]
I'm not sure this is the best so for GitHub... better to have them open at least as a record until fixed
