### ISSUE TITLE
File Explorer Dialog stays to bottom of screen on iOS mobile

### ISSUE THREAD

**Issue by andcachia** [miguelpruivo/flutter_file_picker#1149]
When trying to pick a custom file on iOS mobile web, the dialog box that pops up remains fixed to the bottom left of the screen and not under the button. Have verified that on other random websites, the dialog box normally pops up under the button that was pressed.

I believe this must be related to the fact that a canvas is being used rather than HTML elements, so the dialog attaches to the canvas and not button, which makes it appear below the canvas and thus at the bottom.

Is there a way to specify where the dialog should appear, or at least get the dialog to show in the middle of the screen?

**Platform**

- iOS Mobile Web, both Safari and Chrome

**Platform OS version**

- Multiple Versions

**How are you picking?**
```
final FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png', 'pdf'],
    );
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

In the example in the screenshot, the 'Upload' button was pressed. Ideally, the dialog box should appear below the upload button.

![image](https://user-images.githubusercontent.com/26323098/195846029-ad5a0fbe-c09f-4306-b006-3dc0ef866876.png)

**Other attempts**

I tried also to update the HTML Input element `__file_picker_web-file-input` that is automatically generated and hidden behind the canvas. I set the CSS to move it to the middle of the screen hoping that the dialog might base it's position on that, but no luck.

**Comment by MingSern** [comment]
@andcachia Any solution to this?

**Comment by lighttt** [comment]
Hi is there any update on this one? I am still facing this issue on version `5.5.0`

**Comment by niklasbartsch** [comment]
This is still an issue with `file_picker: ^6.1.1`
