### ISSUE TITLE
Web not working for compiled JS app

### ISSUE THREAD

**Issue by fjwbarnard** [miguelpruivo/flutter_file_picker#1151]
**Describe the bug**
Using with Flutter Web in IDE has no issues, but when compiled as Web App (JS) nothing at all happens on calling `FilePicker.platform.pickFiles()` - no dialog is shown.

**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Platform OS version**
Chrome Version 105.0.5195.125 (Official Build) (64-bit) on Ubuntu

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ["pdf"],
        allowMultiple: true
    );
```

**Details to reproduce the issue**
Use FilePicker.platform.pickFiles() in a `flutter build web` app - no dialog is shown

**Flutter Version details**
Flutter 3.3.4

**Comment by fjwbarnard** [comment]
using `flutter build web --web-renderer canvaskit --release` seems to solve it. Might be `html` web-renderer related

**Comment by Javierd** [comment]
I have the same problem and it was also solved by using the canvaskit renderer. 
On the browser js console a PlatformException is shown. What's even more strange is that it doesn't happen on debug mode, only on release mode.

**Comment by Slexom** [comment]
I've the same issue. In debug and profile, everything work fine, but once build in release it throw the following error in console.
```
Unsupported operation: Platform._operatingSystem
```
Using canvaskit as web renderer solve the issue.

Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale it-IT)
file_picker ^5.2.5
