### ISSUE TITLE
Project Won't Build because of an iOS dependency of file_picker

### ISSUE THREAD

**Issue by Dall127** [miguelpruivo/flutter_file_picker#1156]
iOS will not build because of an issue with a dependency. 

It seems that the issue has been fixed on the dependent plugin, but file_picker must not be using the latest version of DKPhotoGallery

**Platform**

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
iOS 16.1
Mac OS 13.0
Xcode 14.0.1

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

Build for an iOS device 

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

```
    /Users/user/CodeFiles/TrueLake/Frontend/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'DKImagePickerController-DKImagePickerController' from project 'Pods')


    /Users/user/CodeFiles/TrueLake/Frontend/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'DKImagePickerController' from project 'Pods')


    Result bundle written to path:


    	/var/folders/x4/6ljd529n7dd3_bs0n_yt39mm0000gn/T/flutter_tools.C3MNU4/flutter_ios_build_temp_dirM6hCzf/temporary_xcresult_bundle


Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/Users/user/CodeFiles/TrueLake/Frontend/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:67:5



Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

[✓] Flutter (Channel stable, 3.3.5, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.5 on channel stable at /Users/user/LocalFrameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dallin/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.68.1)
    • VS Code at /Volumes/Ventura/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

**Additional context**

It seems that the issue has been fixed on the dependent plugin, but this must not use the latest version of DKPhotoGallery

**Comment by Vikas-shuk** [comment]
> iOS will not build because of an issue with a dependency.
> 
> It seems that the issue has been fixed on the dependent plugin, but file_picker must not be using the latest version of DKPhotoGallery
> 
> **Platform**
> 
> * [ ]  Android
> * [x]  iOS
> * [ ]  Web
> * [ ]  Desktop
> 
> **Platform OS version** What version did it happen? iOS 16.1 Mac OS 13.0 Xcode 14.0.1
> 
> **Details to reproduce the issue** Provide all the details to reproduce the issue.
> 
> Build for an iOS device
> 
> **Error Log** Please, post the _full_ console log of your issue, if applicable.
> 
> ```
>     /Users/user/CodeFiles/TrueLake/Frontend/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'DKImagePickerController-DKImagePickerController' from project 'Pods')
> 
> 
>     /Users/user/CodeFiles/TrueLake/Frontend/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'DKImagePickerController' from project 'Pods')
> 
> 
>     Result bundle written to path:
> 
> 
>     	/var/folders/x4/6ljd529n7dd3_bs0n_yt39mm0000gn/T/flutter_tools.C3MNU4/flutter_ios_build_temp_dirM6hCzf/temporary_xcresult_bundle
> 
> 
> Could not build the precompiled application for the device.
> Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
> /Users/user/CodeFiles/TrueLake/Frontend/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:67:5
> 
> 
> 
> Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> ```
> 
> **Screenshots and/or video** If applicable, add screenshots or video to help explain your problem.
> 
> **Flutter Version details** Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
> 
> [✓] Flutter (Channel stable, 3.3.5, on macOS 13.0 22A380 darwin-arm, locale en-US) • Flutter version 3.3.5 on channel stable at /Users/user/LocalFrameworks/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700 • Engine revision 3ad69d7be3 • Dart version 2.18.2 • DevTools version 2.15.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0) • Android SDK at /Users/dallin/Library/Android/sdk • Platform android-32, build-tools 31.0.0 • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763) • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1) • Xcode at /Applications/Xcode.app/Contents/Developer • Build 14A400 • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.1) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
> 
> [✓] VS Code (version 1.72.2) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.50.0
> 
> [✓] VS Code (version 1.68.1) • VS Code at /Volumes/Ventura/Applications/Visual Studio Code.app/Contents • Flutter extension version 3.50.0
> 
> **Additional context** Add any other context about the problem here.
> 
> It seems that the issue has been fixed on the dependent plugin, but this must not use the latest version of DKPhotoGallery

facing same issue
