### ISSUE TITLE
Deprecated code error on flutter build

### ISSUE THREAD

**Issue by hey24sheep** [miguelpruivo/flutter_file_picker#116]
FilePicker have deprecated code error on latest flutter AndroidX build, I am using latest version 1.3.8 in my pubspec.

First deprecation error on 
```

FilePickerPlugin.java:186: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated
        Uri uri = Uri.parse(Environment.getExternalStorageDirectory().getPath() + File.separator);
```

Second error on

```
FileUtils.java:53: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated
                    return Environment.getExternalStorageDirectory() + "/" + split[1];
```

**Comment by miguelpruivo** [comment]
Hi, thank you for pointing it out. Which API version are you targeting and also running on?

Nevertheless, it shouldn’t prevent its correct usage right now.

Thank you.

**Comment by hey24sheep** [comment]
I was targeting 27 and I changed it to 28 and 29, I get error on all, usage is not a problem but deprecated code gives warnings which are treated as errors on CI-CD. Which causes build fails. I might fix it and create a pr for the same if I get the time.

**Comment by miguelpruivo** [comment]
@hey24sheep I'll take a look into it. Thank you.

**Comment by hey24sheep** [comment]
@miguelpruivo Thank you so much. If you know the solution, let me know I will fix it. I need it in my prod environment.

**Comment by miguelpruivo** [comment]
@hey24sheep this should be fixed right now in the `1.4.0` that is yet on `beta`. Could you please try replacing in your **pubspec.yaml** like so:
```
file_picker:
    git:
      url: https://github.com/miguelpruivo/plugins_flutter_file_picker.git
      ref: beta
```
and let me know if it's working for you? 

Thank you.

**Comment by miguelpruivo** [comment]
[Version 1.4.0](https://pub.dev/packages/file_picker#140) published with a fix for this. Thank you for reporting. 🎉

**Comment by hey24sheep** [comment]
@miguelpruivo  Thank you so much
