### ISSUE TITLE
I get wrong file name from file system

### ISSUE THREAD

**Issue by WenjieZhengJerry** [miguelpruivo/flutter_file_picker#1163]
**Platform**
- [ ] Android

**How are you picking?**
i want to get a file named 'xx.pdf' from file system, but i get a file named '19384' which is a random number, and it doesn't have extension name.

here is my code:
```
final FilePickerResult? res = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf'],
        onFileLoading: (FilePickerStatus status) => log.logInformation(status),
      );
```
except: 'xx.pdf'
actual: a random number without extension name

here is picture:

![image](https://user-images.githubusercontent.com/43103543/200282586-ba579007-a8ea-4d5b-bebe-1f73befaf2da.png)

version: 5.2.2

**Comment by AKA-LinCoder** [comment]
i get same question

**Comment by asadamatic** [comment]
@WenjieZhengJerry Were you able to resolve it? I'm facing this issue.

**Comment by AKA-LinCoder** [comment]
nfg

**Comment by WenjieZhengJerry** [comment]
> @WenjieZhengJerry Were you able to resolve it? I'm facing this issue.

no，can you new issue from this

**Comment by asadamatic** [comment]
@WenjieZhengJerry I noticed that this issue did not occur on selectin file from the folder that opened immediately (Recent Files), rather it occurred when I opened another folder to pick file.

**Comment by asadamatic** [comment]
@WenjieZhengJerry I had filed this issue https://github.com/miguelpruivo/flutter_file_picker/issues/1302#issuecomment-1576398000
