### ISSUE TITLE
file_picker dependency asks for compile sdk 33, why?

### ISSUE THREAD

**Issue by Diamondemon** [miguelpruivo/flutter_file_picker#1167]
Hello
This issue here is a voluntary duplicate of the wrongly closed issue  #1140

Basically, the compiler says this:
```console
Warning: The plugin file_picker requires Android SDK version 33.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/julien/Bureau/ISN/Flutter/ImproHelper/impro_helper/android/app/build.gradle:
android {
  compileSdkVersion 33
  ...
}
```

However, I want to keep my current `compileSdkVersion flutter.compileSdkVersion`, so I would like to understand why the dependency has such a requirement.

Can you please tell us, or fix that problem?

Here is my pubspec.yaml: 
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^5.2.2
```

**Comment by jandrop** [comment]
It's because the compileSdkVersion is hardcoded in the android gradle file, I just opened a PR to fix that https://github.com/miguelpruivo/flutter_file_picker/pull/1169

**Comment by navaronbracke** [comment]
@Diamondemon Why would you _not_ support the latest compile SDK version? Android 13 (SDK version 33) has been released and is the most recent version of Android.

If you can't upgrade just yet, you should pin a specific plugin version, which does not require SDK version 33.

@jandrop I double-checked what compile SDK version Flutter specifies by default on master at this time. They specify compile & target SDK version 31, so I think that specifying the latest version explicitly is the better option here, as opposed to referencing flutter.gradle for that.

**Comment by Diamondemon** [comment]
@navaronbracke It prefer not to hardcode a compile SDK for two reasons:
- Hardcoding it would mean forgetting about it later on, for me
- If SDK 33 is not on the master branch of flutter, that would mean that there is no guarantee that flutter works perfectly fine on it. Thus I would prefer not doing so.

Moreover, that's just a warning, the compilation goes on fine which means there is no necessity to be on the bleeding edge for compile sdk.

Apart from making a uselessly bothering red line show up, this does not do much...

**Comment by Diamondemon** [comment]
> If the plugin documents a change to the compile/target SDK version as a breaking change in the changelog, then I don't think you can forget?

You are right, yeah.

> This has nothing to do with this plugin?

I thought that because this is a Flutter plugin, this would have to do with the plugin. I did not think being ahead of it would be a good idea but I was probably mistaken then.

> It *does* produce compilation errors if you want to use `Build.VERSION_CODES`

Please forgive my ignorance, in which case would I use `Build.VERSION_CODES` ? That's a real question, I have no idea when it comes into play.

**Comment by jandrop** [comment]
I think, in my case, the problem is because we are using version 3.0.5 of flutter (we can't point to the latest version), so in this version, you can go in the flutter SDK to this route `flutter_sdk/packages/flutter_tools/gradle` and you can see the file `flutter.gradle`, in my case with the flutter version 3.0.5 the targetSdkVerion is 31

```
class FlutterExtension {
    /** Sets the compileSdkVersion used by default in Flutter app projects. */
    static int compileSdkVersion = 31

    /** Sets the minSdkVersion used by default in Flutter app projects. */
    static int minSdkVersion = 16

    /** Sets the targetSdkVersion used by default in Flutter app projects. */
    static int targetSdkVersion = 31
```

So the app will compile with this SDK version. If you change in the android Gradle the compileSdkVersion you are forced to use this SDK to compile the app and maybe your pipeline will break at build time.

I just solved the problem by changing the compileSdkVersion to 31, as most plugins do.

```
android {
    compileSdkVersion 31

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
      dependencies {
        implementation 'androidx.core:core:1.0.2'
        implementation 'androidx.annotation:annotation:1.0.0'
        implementation "androidx.lifecycle:lifecycle-runtime:2.1.0"
    }
}
```

and then removing the if from the FilePickerDelegate  

```
if(Build.VERSION.SDK_INT >= 33){
     return bundle.getParcelableArrayList("selectedItems", Parcelable.class);
}
```

If you guys want to check if my fix works for you, you can replace the lib line on the pubspec.yalm with my fork

```
file_picker:
    git:
      url: https://github.com/jandrop/flutter_file_picker.git
      ref: master
```

**Comment by navaronbracke** [comment]
@Diamondemon I am referring to this kind of check https://developer.android.com/training/basics/supporting-devices/platforms#version-codes

**Comment by Diamondemon** [comment]
@navaronbracke yeah right it's at runtime. Thanks for the information

**Comment by alexmercerind** [comment]
I think this should be closed. It has been resolved.
