### ISSUE TITLE
Gracefully handle MainActivity destruction on Android

### ISSUE THREAD

**Issue by sz7i** [miguelpruivo/flutter_file_picker#1170]
First, this is a really great plugin so thanks for maintaining it! 

But it misses one important feature related to handling activity destructions on Android. I strongly believe it's also a root cause for various crash reports filed here for Android.

Flutter activity destruction is normal on Android and may happen when moving the MainActivity to background after opening a native view for file picking. The same issue exists in all other plugins that show native views.

So far I've found that image_picker plugin deals with it in a relatively good way and allowed (with some work) to continue restoring the application state even after destruction. You can find all the details here https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android.

It would be great if this plugin implemens a mechanism similar to the one implemented in the image_picker.

**Comment by MilesAdamson** [comment]
This issue should not be closed
