### ISSUE TITLE
Any plan on supporting File System Access API on web ?

### ISSUE THREAD

**Issue by poirierlouis** [miguelpruivo/flutter_file_picker#1179]
Hello,

Thank you for this package. 👍 

I read this recent article [web.dev - file system access](https://web.dev/file-system-access/) which describe how Chromium provide a File System Access API on web applications (see also [MDN](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)).

I did not found a suggestion about this topic.

So here it is, the API allows to pick files to open / read / save / write files on user's device, given permissions are granted. It also works with directories.

There is a limitation regarding permissions, on a per file handle basis. Permissions granted by user shall stay alive as long as the web application is alive in user's browsers (all tabs). But it's already something they are working on, as the article says.

It's supported on Chrome, Edge and Opera for now.

Wouldn't be nice to provide such feature? I believe this package is appropriate for such an implementation. I don't know however if it requires direct specific implementation from the Flutter engine.

What do you think?

**Comment by poirierlouis** [comment]
@miguelpruivo I've made a [library](https://pub.dev/packages/file_system_access_api) of the JavaScript API. It might serves as a building block to interface with your plugin, maybe once API is marked stable.

**Comment by miguelpruivo** [comment]
Closing as this is a no-op with no ETA. Will re-open if needed.
