### ISSUE TITLE
I get wrong file name from file system

### ISSUE THREAD

**Issue by WenjieZhengJerry** [miguelpruivo/flutter_file_picker#1182]
I want to get a file named 'xx.pdf' from file system, but i get a file named '19384' which is a random number, and it doesn't have extension name.

here is my code:
```dart
final FilePickerResult? res = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf'],
        onFileLoading: (FilePickerStatus status) => log.logInformation(status),
      );
```
except: 'xx.pdf'
actual: a random number without extension name

here is picture:

![image](https://user-images.githubusercontent.com/43103543/204690145-5be03602-6025-49a0-869c-118bfbe14b5d.png)

version: 5.2.2

**Comment by philenius** [comment]
@WenjieZhengJerry which platform are you on? Please use our issue template.
