### ISSUE TITLE
File picker accidentally pops route after picking an image

### ISSUE THREAD

**Issue by kean-fetchpet** [miguelpruivo/flutter_file_picker#1184]
**Describe the bug**
File picker pops last route after picking an image.

**Platform**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 12 (API 31)

**Details to reproduce the issue**
Run the line below and it will automatically pop a route which is weird.
`final FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image);`

**Flutter Version details**
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.1219], locale en-AU)
    • Flutter version 3.0.5 at D:\flutter_projects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by Alex-Usmanov** [comment]
Hi. 

I am currently experiencing the same issue on the latest version of the plugin on pub. 
Would you mind sharing what PR this was patched in, or perhaps giving a little bit of detail of what the problem was in case it was unrelated to the plugin code itself?

**Comment by Alex-Usmanov** [comment]
@miguelpruivo would you please consider reopening this issue?
@kean-fetchpet could you please share what you did to solve this problem?

**Comment by Alex-Usmanov** [comment]
@kean-fetchpet  Thanks a lot for your input! Appreciate it

**Comment by heshesh2010** [comment]
+1
