### ISSUE TITLE
Picking 100+ photos from google photo folder - File Picker crash

### ISSUE THREAD

**Issue by svoza10** [miguelpruivo/flutter_file_picker#1187]
**Describe the bug**
I want upload to my app 200 photo from google Photo, but file picker shut down.

**Platform**
- [x] Android

**Platform OS version**
android 13 and 12

**Details to reproduce the issue**
I want pick 100+ photos from google photo. In format jpg, heic, png atd...

**Error Log**
D/FilePickerDelegate(22706): Selected type image/*
I/TRuntime.CctTransportBackend(22706): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBackend(22706): Status Code: 200
E/AndroidRuntime(23541): FATAL EXCEPTION: main
E/AndroidRuntime(23541): Process: com.google.android.apps.photos, PID: 23541
E/AndroidRuntime(23541): java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1220884 bytes
E/AndroidRuntime(23541): 	at android.app.ActivityClient.finishActivity(ActivityClient.java:168)
E/AndroidRuntime(23541): 	at android.app.Activity.finish(Activity.java:6688)
E/AndroidRuntime(23541): 	at android.app.Activity.finish(Activity.java:6705)
E/AndroidRuntime(23541): 	at agnn.finish(PG:2)
E/AndroidRuntime(23541): 	at suv.c(PG:14)
E/AndroidRuntime(23541): 	at suv.f(PG:18)
E/AndroidRuntime(23541): 	at suq.onClick(PG:63)
E/AndroidRuntime(23541): 	at android.view.View.performClick(View.java:7506)
E/AndroidRuntime(23541): 	at com.google.android.material.button.MaterialButton.performClick(PG:2)
E/AndroidRuntime(23541): 	at android.view.View.performClickInternal(View.java:7483)
E/AndroidRuntime(23541): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime(23541): 	at android.view.View$PerformClick.run(View.java:29341)
E/AndroidRuntime(23541): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(23541): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23541): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(23541): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(23541): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(23541): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23541): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(23541): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(23541): Caused by: android.os.TransactionTooLargeException: data parcel size 1220884 bytes
E/AndroidRuntime(23541): 	at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime(23541): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
E/AndroidRuntime(23541): 	at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1429)
E/AndroidRuntime(23541): 	at android.app.ActivityClient.finishActivity(ActivityClient.java:165)
E/AndroidRuntime(23541): 	... 19 more
D/TrafficStats(22706): tagSocket(83) with statsTag=0xffffffff, statsUid=-1

**Screenshots and/or video**
https://user-images.githubusercontent.com/71311571/206221286-54e7196e-3577-477e-a48d-ccc1e0b4ad60.mp4

**Flutter Version details**
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale cs)
    • Flutter version 3.3.9 on channel stable at /Users/adamsvozilik/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/adamsvozilik/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/adamsvozilik/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • adb-28091FDH200HWP-ZC8rgi._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos                                            • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)     • chrome                                           • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Additional context**

**Comment by navaronbracke** [comment]
Firstly, why would you want to pick that many photos at once?
Secondly, the stacktrace indicates what the problem is:

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1220884 bytes
```

This has nothing to do with this plugin, but rather with the fact that you run out of space by wanting to select all those files. They don't fit in memory.

**Comment by svoza10** [comment]
Its use case is our app to select many photos and from metadata create trips. Can you throw some error messages to handle this? Because filepicker only shutdown and throw nothing. Or do some queue and check memory.

**Comment by navaronbracke** [comment]
Enforcing a maximum number of files would make more sense. I.e. https://stackoverflow.com/questions/50963156/how-to-set-maximum-files-selection-count-on-intent-intent-extra-allow-multiple
