### ISSUE TITLE
Could not find gradle-3.3.0.jar (com.android.tools.build:gradle:3.3.0)

### ISSUE THREAD

**Issue by kamyar75** [miguelpruivo/flutter_file_picker#1189]
Hi, I wanna use file_picker in android but could not find gradle 3.3.0 and other errors.
my android studio could not download these files.

A problem occurred configuring project ':file_picker'.
> Could not resolve all files for configuration ':file_picker:classpath'.
   > Could not find gradle-3.3.0.jar (com.android.tools.build:gradle:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
   > Could not find builder-3.3.0.jar (com.android.tools.build:builder:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar
   > Could not find tracker-26.3.0.jar (com.android.tools.analytics-library:tracker:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.0/tracker-26.3.0.jar
   > Could not find shared-26.3.0.jar (com.android.tools.analytics-library:shared:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.0/shared-26.3.0.jar
   > Could not find crash-26.3.0.jar (com.android.tools.analytics-library:crash:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.0/crash-26.3.0.jar
   > Could not find lint-gradle-api-26.3.0.jar (com.android.tools.lint:lint-gradle-api:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.0/lint-gradle-api-26.3.0.jar
   > Could not find gradle-api-3.3.0.jar (com.android.tools.build:gradle-api:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.0/gradle-api-3.3.0.jar
   > Could not find databinding-compiler-common-3.3.0.jar (androidx.databinding:databinding-compiler-common:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.0/databinding-compiler-common-3.3.0.jar
   > Could not find manifest-merger-26.3.0.jar (com.android.tools.build:manifest-merger:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.0/manifest-merger-26.3.0.jar
   > Could not find sdk-common-26.3.0.jar (com.android.tools:sdk-common:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.0/sdk-common-26.3.0.jar
   > Could not find builder-test-api-3.3.0.jar (com.android.tools.build:builder-test-api:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.0/builder-test-api-3.3.0.jar
   > Could not find ddmlib-26.3.0.jar (com.android.tools.ddms:ddmlib:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.0/ddmlib-26.3.0.jar
   > Could not find sdklib-26.3.0.jar (com.android.tools:sdklib:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.0/sdklib-26.3.0.jar
   > Could not find layoutlib-api-26.3.0.jar (com.android.tools.layoutlib:layoutlib-api:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.0/layoutlib-api-26.3.0.jar
   > Could not find dvlib-26.3.0.jar (com.android.tools:dvlib:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.0/dvlib-26.3.0.jar
   > Could not find repository-26.3.0.jar (com.android.tools:repository:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.0/repository-26.3.0.jar
   > Could not find common-26.3.0.jar (com.android.tools:common:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.0/common-26.3.0.jar
   > Could not find jetifier-processor-1.0.0-beta02.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta02/jetifier-processor-1.0.0-beta02.jar
   > Could not find bundletool-0.6.0.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
   > Could not find jetifier-core-1.0.0-beta02.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta02/jetifier-core-1.0.0-beta02.jar
   > Could not find builder-model-3.3.0.jar (com.android.tools.build:builder-model:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.0/builder-model-3.3.0.jar
   > Could not find protos-26.3.0.jar (com.android.tools.analytics-library:protos:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.0/protos-26.3.0.jar
   > Could not find apkzlib-3.3.0.jar (com.android.tools.build:apkzlib:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.0/apkzlib-3.3.0.jar
   > Could not find apksig-3.3.0.jar (com.android.tools.build:apksig:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.0/apksig-3.3.0.jar
   > Could not find annotations-26.3.0.jar (com.android.tools:annotations:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.0/annotations-26.3.0.jar
   > Could not find databinding-common-3.3.0.jar (androidx.databinding:databinding-common:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.0/databinding-common-3.3.0.jar
   > Could not find baseLibrary-3.3.0.jar (com.android.databinding:baseLibrary:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.0/baseLibrary-3.3.0.jar
   > Could not find aapt2-proto-0.3.1.jar (com.android.tools.build:aapt2-proto:0.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':file_picker' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':file_picker' of type org.gradle.api.Project.

**Comment by AliKarimiENT** [comment]
Hello 
I have faced this issue too. I have tested upper gradle versions too but the error changed. I will attach the error image below.

dependencies {
        **classpath 'com.android.tools.build:gradle:7.4.2'**
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
 }

**distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-bin.zip**

![image](https://user-images.githubusercontent.com/57004354/221944843-48ef341d-7f9d-4e04-a0f8-a8ba6fe49bfa.png)

**Flutter Version**
![image](https://user-images.githubusercontent.com/57004354/221944990-f2ecb3c3-26ce-44b7-a293-59b826d49155.png)
