### ISSUE TITLE
in file included from file_picker-4.6.1/ios/Classes/FileUtils.m:8:

### ISSUE THREAD

**Issue by yjt1216** [miguelpruivo/flutter_file_picker#1193]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

![file_picker bug](https://user-images.githubusercontent.com/12771656/208038150-2519ccf6-7f4b-4520-9777-345b4fe2741b.png)

**Comment by yjt1216** [comment]
![flutter_version](https://user-images.githubusercontent.com/12771656/208038728-3edb061b-d995-479b-aa03-1aa1ea07866f.png)

**Comment by yjt1216** [comment]
![file_picker version](https://user-images.githubusercontent.com/12771656/208038795-7e3aeadc-509b-42c7-9260-4545f3ae3382.png)

**Comment by yjt1216** [comment]
![846F83E2-8929-4D0E-A052-ED2EA8FE74C7](https://user-images.githubusercontent.com/12771656/208044685-76821e12-382b-413c-b37e-df75fd539b08.png)

**Comment by yjt1216** [comment]
When I run on iOS, I report an error and Android runs normally.

**Comment by yjt1216** [comment]
我现在将 iOS classes 中MediaType中的MEDIA改为MEDIAS
![file_picker bug](https://user-images.githubusercontent.com/12771656/208070563-d137a46a-d3d8-4d6d-9ca2-c1c091484c98.png)
![改动](https://user-images.githubusercontent.com/12771656/208070592-87ac2c3d-16cf-43ea-a6de-552d3c5b387b.png)

**Comment by DeliriousLee** [comment]
I meet the same issue:
file_picker-4.6.1
![image](https://user-images.githubusercontent.com/24474112/216754560-0bc756f6-7a7f-47b6-abeb-77bc971407d4.png)
![image](https://user-images.githubusercontent.com/24474112/216754577-915df482-3857-40e7-af49-adc96340a4ca.png)

**Comment by yjt1216** [comment]
> I meet the same issue: file_picker-4.6.1 ![image](https://user-images.githubusercontent.com/24474112/216754560-0bc756f6-7a7f-47b6-abeb-77bc971407d4.png) ![image](https://user-images.githubusercontent.com/24474112/216754577-915df482-3857-40e7-af49-adc96340a4ca.png)

MEDIA ---> MEDIAS 
MEDIA是iOS系统关键字，与系统关键词重名了
