### ISSUE TITLE
ovpn file is not recognised  as allowed extensions ?

### ISSUE THREAD

**Issue by harryandroiddev** [miguelpruivo/flutter_file_picker#1198]
it does not use ovpn file type and throws an exception .

I have tried like this :

` FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowedExtensions: ['ovpn'],
      type:FileType.custom
    );`

**Comment by philenius** [comment]
Duplicate of https://github.com/miguelpruivo/flutter_file_picker/issues/1148. Please read https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-9.
