### ISSUE TITLE
File Picker dialog not showing on web

### ISSUE THREAD

**Issue by mikhail-poda** [miguelpruivo/flutter_file_picker#1201]
file_picker: ^5.2.4

**Describe the bug**
File Picker dialog works when started from IntelliJ (device: Chrome (Web)) but not as a web app

**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Platform OS version**
Latest Chrome on Windows, Edge on Windows, Chrome on Android

**How are you picking?**
```
final result = await FilePicker.platform.pickFiles(type: FileType.any, allowMultiple: false);
```

**Details to reproduce the issue**
Just the above code in a small web app

**Flutter Version details**

[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2251], locale en-US)
    • Flutter version 3.3.10 on channel stable at C:\Users\mikha\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[X] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\mikha\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.3
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4167.21

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability                 
    • All required HTTP hosts are available

**Comment by AsturaPhoenix** [comment]
I just ran into this as well, but after trying a bunch of things eventually `flutter clean` before `flutter build web ...` seemed to fix it. @mikhail-poda Have you tried this yet?

(In investigating I got as far as finding that for some reason the web plugin registration `FilePickerWeb.registerWith` was never running in the built/deployed version. This seems to have been somehow related to plugin discovery and build artifacts?)

**Comment by AsturaPhoenix** [comment]
The `clean` observation was previously noted in #889, and #1131 may be another incarnation of this.

**Comment by mikhail-poda** [comment]
Thank you, running `flutter clean` before `flutter build web` has solved my issue!

**Comment by hurelhuyag** [comment]
Faced the same problem. And I have no idea how `flutter clean` helps. But it worked.

**Comment by GelistirmeKF** [comment]
Faced the same problem but "flutter clean" doesn't help me. If the web build is in release mode, the problem occurs. In profile mode, dialog opens as well.

**Comment by Slexom** [comment]
I've the same issue. In debug and profile, everything work fine, but once build in release it throw the following error in console, and the page go full grey.
```
Unsupported operation: Platform._operatingSystem
```
Using canvaskit as web renderer solve the issue.
Importing conditionally `FilePicker.platform` for _io_ and `FilePickerWeb.platform` for _web_ also solve the issue.

_file_picker.io.dart_
```dart
import 'package:file_picker/file_picker.dart';

final filePicker = FilePicker.platform;
```


_file_picker.web.dart_
```dart
import 'package:file_picker/_internal/file_picker_web.dart';

final filePicker = FilePickerWeb.platform;
```



```dart
import 'file_picker.io.dart'
    if (dart.library.html) 'file_picker.web.dart';

...

class MyFilePicker {

  final FilePicker _picker;

  MyFilePicker(this._picker);
...

}

...

MyFilePicker(filePicker);

...

```

---
Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale it-IT)
file_picker ^5.2.5

**Comment by Mazlo-Dev** [comment]
Also getting this error, but only on a released build and not during development. I noticed there's no `kIsWeb` check in the `FilePicker._setPlatform()` function, why does this package say it supports web?

**Comment by rajeshbdabhi** [comment]
I am facing same issue then I build "flutter build web --web-renderer canvaskit --release" using this command file picker dialog not showing. but when I build "flutter build web --web-renderer html --release" with this renderer it is working fine. is there any way to fix this issue with canvas kit renderer.
