### ISSUE TITLE
Bug with FileType.custom and allowedExtensions param

### ISSUE THREAD

**Issue by JulioCe98** [miguelpruivo/flutter_file_picker#1203]
**Describe the bug**
In my company we are using the file_picker plugin to allow the users load pdf files into a chat. We are using the following code to reach that:

var pdf = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf']);

However we saw that with that code, the users can select media files too (photos, videos, etc). In some android versions exist a "hamburger menu" that allows the user selects other folder, like photos folder, where the user can choose wherever media file.

I was testing with the example code that was provided by file_picker devs, but I saw the same problem:

![Captura de pantalla 2023-01-04 a la(s) 11 52 03 a m](https://user-images.githubusercontent.com/38018802/210607924-269a7694-559f-4fad-885d-b3823d76001b.png)
![Captura de pantalla 2023-01-04 a la(s) 11 52 10 a m](https://user-images.githubusercontent.com/38018802/210607931-ad9c231c-3ddb-4430-888d-63c4a63fa32c.png)
![Captura de pantalla 2023-01-04 a la(s) 11 52 21 a m](https://user-images.githubusercontent.com/38018802/210607933-a321a87c-d5bc-4d63-8d6c-721282d3865d.png)
![Captura de pantalla 2023-01-04 a la(s) 11 52 33 a m](https://user-images.githubusercontent.com/38018802/210607934-2f87ce06-60a3-4a31-92cf-d64b265a8a0f.png)
![Captura de pantalla 2023-01-04 a la(s) 11 52 44 a m](https://user-images.githubusercontent.com/38018802/210607936-888c9a1c-b499-4578-b140-47006118347e.png)
![Captura de pantalla 2023-01-04 a la(s) 11 52 53 a m](https://user-images.githubusercontent.com/38018802/210607939-a821c18e-8e7f-49b1-8b2c-116aa1287330.png)

**Platform**

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
I Tested the app with android 9.0 and android 12.0

**Details to reproduce the issue**

1. Use the same following code to select  only pdf files

var pdf = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf']);

2. Then, you will see a screen that allow select the media files. Search a menu that allows you change the current folder

![Captura de pantalla 2023-01-04 a la(s) 11 52 10 a m](https://user-images.githubusercontent.com/38018802/210610461-7926f0de-9b9a-4a50-9f1b-d39fc34cf1ba.png)

![Captura de pantalla 2023-01-04 a la(s) 11 52 21 a m](https://user-images.githubusercontent.com/38018802/210607974-c9de8619-4cb4-4548-8dc5-9b446a656251.png)

3. Choose for example the photos folder

![Captura de pantalla 2023-01-04 a la(s) 11 52 33 a m](https://user-images.githubusercontent.com/38018802/210608029-6cb3d3d6-3c59-4766-8443-4c99f28a0a18.png)

4. Select wherever media file

![Captura de pantalla 2023-01-04 a la(s) 11 52 44 a m](https://user-images.githubusercontent.com/38018802/210608043-60314806-751d-4803-9bed-b2d6659e1370.png)

![Captura de pantalla 2023-01-04 a la(s) 11 52 53 a m](https://user-images.githubusercontent.com/38018802/210608095-e560cb66-dc9d-46eb-b3a7-53a092ad6a69.png)

**Comment by deepak-agendaboa** [comment]
Have the same issue.

**Comment by deepak-agendaboa** [comment]
Findings:

"Downloads" section is not able to identify the type of the file. The icon of the file is default file icon and type is also file.
And if you click on the file it says "Can't open file".

But if I go to "Download" folder (note: Its Download not Downloads) via "device -> Download" then it is working fine. Here the file icon is correct as well as the file type. Here the click is also working fine.

I don't know how to fix this. Seems that the issue is with the "Downloads" part as it is a separate application or functionality in Android.
