### ISSUE TITLE
Empty Documents folder on macOS

### ISSUE THREAD

**Issue by mgenware** [miguelpruivo/flutter_file_picker#1210]
**Describe the bug**
Pick a file using `FilePicker.platform.pickFiles`:
```dart
FilePickerResult? result = await FilePicker.platform.pickFiles();
```

Select Documents from Favorites, got an empty folder (it's not empty, I can see contents in Finder).
<img width="500" alt="image" src="https://user-images.githubusercontent.com/11565096/211451949-4c3063f4-8e44-4b3c-ab09-0f10be1367bb.png">

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [x] Desktop

**Platform OS version**

file_picker: ^5.2.5
macOS: 13.1 (22C65)
Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-CN)

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform.pickFiles();
```

**Comment by philenius** [comment]
@mgenware, this is unexpected... I would suggest to try out the official Flutter plugin named `file_selector` (https://pub.dev/packages/file_selector). This Dart package provides a more professional implementation. If it still doesn't work with the `file_selector` package, then it must be related to macOS specifics.
