### ISSUE TITLE
When using pick files  with allowMultiple: true, The path checks for name suppose 2 different images have same name and extension then. It loads the old one which is saved in the cache not the new one. 

### ISSUE THREAD

**Issue by imran-wo** [miguelpruivo/flutter_file_picker#1213]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
 void pickFromGallery() async {
    //var pickedfiles = [];
    try {
      DialogBox.handleLoadingDialog(context);

      // var pickedfiles = await imgpicker.pickMultiImage();
      pickedfiles = await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: true,
      );

      //you can use ImageCourse.camera for Camera capture
      if (pickedfiles != null) {
        //imagefiles = pickedfiles;
        // imagefiles = pickedfiles.paths.map((path) => File(path)).toList();
        List<XFile> tempFiles =
            pickedfiles!.paths.map((path) => XFile(path!)).toList();
        imagefiles.addAll(tempFiles);

        //  imagefiles.addAll(pickedfiles);
        // finalFiles.addAll(pickedfiles);
        for (int i = 0; i < imagefiles.length; i++) {
          debugPrint(
              'Each image   ${imagefiles[i].name} || ${imagefiles[i].path} ||');
        }
        debugPrint('Picked Filed  ${imagefiles.length}');
      } else {
        print('No image is selected.');
      }
      Navigator.pop(context);
    } catch (e) {
      print('<<<<  ||  error while picking file. ==> $e');
    }
    setState(() {});
  }


```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by MuhammedRefaat** [comment]
It's happening with me as well, I think it should be reopened again

**Comment by SoftWyer** [comment]
There seems to be a [PR that might fix this](https://github.com/miguelpruivo/flutter_file_picker/pull/1230). Be good if that was approved and merged 🤞

**Comment by stephane-archer** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/1628
