### ISSUE TITLE
How to restrict .txt file  

### ISSUE THREAD

**Issue by adnankhan74444** [miguelpruivo/flutter_file_picker#1216]
var data = await picker.FilePicker.platform.pickFiles(
        type: picker.FileType.custom,
        withData: true,
        allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
      );

User still able to select .txt files from folder.

**Comment by adnankhan74444** [comment]
Any update on this ?

**Comment by philenius** [comment]
Please refer to our FAQ: https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ#q-why-am-i-able-to-select-other-file-types-even-if-i-use-a-filter-or-why-doesnt-it-filter-at-all
