### ISSUE TITLE
picker in selecting multi file picks wrong file 

### ISSUE THREAD

**Issue by codingwitharko** [miguelpruivo/flutter_file_picker#1218]
Hi
i'm using the last version of file_picker: ^5.2.5
in my case in android platform when i'm use the 
FilePicker.platform.pickFiles(type: FileType.image, allowMultiple: true)
and select the images from the galley picker select wrong file.
 this is happens when i have file with same name but in different directories.

**Comment by GabrielAraujo** [comment]
Yes! Facing this same issue
