### ISSUE TITLE
Can't Pick Large files on Web

### ISSUE THREAD

**Issue by aliaafreen** [miguelpruivo/flutter_file_picker#1219]
When I am picking large file (>=1 gb) with data, will not be picked, no error is displayed, but do not get files in file variable after pickup.
What should i do for this?

flutter - 3.3.9
file_picker - ^5.2.2

**Comment by philenius** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/1002

**Comment by vidhi002** [comment]
same issue
