### ISSUE TITLE
Cannot pick files on Web

### ISSUE THREAD

**Issue by Gnoucorp** [miguelpruivo/flutter_file_picker#1221]
Hello,
After a recent pub update, I realized that I could not pick files anymore on flutter web.

It seems that the method _FilePicker.platform.pickFiles_ always returns null.

I managed to reproduce it with the example app on branch master (no matter what I pick, I see the text "User has aborted the dialog"). I use Flutter 3.7.0 on windows 11 with VS code, reproduced it on Edge and Chrome.

**Comment by getr11** [comment]
This is related to issue #1197

**Comment by pianistrevor** [comment]
Same for me, it seems to be triggered by Flutter 3.7.0

**Comment by bksbora** [comment]
Same for me , When i try to run in Chrome ... It works on mobile ...
Error: Undefined name 'FilePickerWeb'. FilePickerWeb.registerWith(registrar) ;

**Comment by jstdk** [comment]
It works for me once every three picks.

**Comment by Gnoucorp** [comment]
Reproduced on flutter v3.7.3 : nothing changed.

Any workaround available ?

**Comment by pianistrevor** [comment]
> Reproduced on flutter v3.7.3 : nothing changed.
> 
> Any workaround available ?

What I did in my app was show an error dialog if the result was null, in order to at least indicate something happened. To avoid showing the error dialog when user cancelled the pick, I gave it an `onFileLoading` callback that set a flag, which was checked before throwing the error dialog.

**Comment by clia** [comment]
I just tried to use the web example from the master branch, it's ok.
Is this a problem existing in the released version, and has been solved in the master?

**Comment by santiagomartinp** [comment]
I'm having this issue. It works as expected in debug mode but it doesn't when deployed. It returns `null`.  Any updates or workarounds? Thanks!
