### ISSUE TITLE
 RAM overflow when downloading a large number of files (Web).

### ISSUE THREAD

**Issue by promistrio** [miguelpruivo/flutter_file_picker#1227]
**Describe the bug**
As we know, the process of downloading files in the web version is different from native. In my UI, the user needs to pick a lot of images with a size of 5-10 megabytes.  All images are loaded into memory. Is there a way around this limitation? For example, sequential loading. On a computer with 8 GB of RAM, the browser crashes.

**Platform**
- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Desktop

**How are you picking?**
```
            FilePickerResult? result =
                await FilePicker.platform.pickFiles(allowMultiple: true);
            // if user selected files
            if (result != null) {
              filesProvider.xFiles = {};
              String fileName = result.files.first.name;
              List<PlatformFile> files = result.files;

              for (PlatformFile file in files) {
                if (file.bytes != null) {
                  filesProvider.xFiles[file.name] =
                      XFile.fromData(file.bytes ?? Uint8List(0));
                }
              }
              projectProvider.addXfiles();

              /*projectProvider.addFiles(files);
              if (files.isNotEmpty) {
                imagesProvider.dir = files[0].path;
              }*/
            } else {
              // User canceled the picker
            }
```
**Screenshots and/or video**
![изображение](https://user-images.githubusercontent.com/6287944/220569765-d98ab920-b58f-43e7-bfd3-5d093c3da36a.png)

**Additional context**

**Comment by callmephil** [comment]
you should try the `withReadStream` property.
