### ISSUE TITLE
Android : Issue when selecting file directly through google drive 

### ISSUE THREAD

**Issue by apleton** [miguelpruivo/flutter_file_picker#1231]
**Describe the bug**
On Android, selecting a file located on google drive does not work. After selecting the file in the File Picker screen, a file is copied in the cache folder (data/data/<appName>/cache/file_picker/<my_file>) with the right name, but containing 0 bytes, even with the parameter withData set to true. This issue does not appear when selecting local file. 

**Platform OS version**
Android 12

**How are you picking?**
```
FilePickerResult? pickFileResult = await FilePicker.platform.pickFiles(type: FileType.any, withData: true);
if (pickFileResult != null && pickFileResult.files.single.path != null) {
    File jsonFile = File(pickFileResult.files.single.path!);
    String jsonString = await jsonFile.readAsString(); // JSON STRING IS EMPTY
}
```

**Error Log**
I/FilePickerUtils(32131): Caching from URI: content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3Dencoded%3DTT3ElPcfD15Zr4VpVa-_JyAyaoFpcW1FCMDkb7-DuCQyFFQVsbs%3D
D/FilePickerUtils(32131): File loaded and cached at:/data/user/0/net.reflowstudio.music_practice/cache/file_picker/exported_exercises.json
D/FilePickerDelegate(32131): File path:[com.mr.flutter.plugin.filepicker.FileInfo@104220e]

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.2 21G320 darwin-arm64, locale en-BE)
    • Flutter version 3.7.3 on channel stable at /Users/quentin/Documents/workspace/frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (3 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/quentin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/quentin/Library/Android/sdk
    • Java binary at: /Users/quentin/Library/Java/JavaVirtualMachines/openjdk-19.0.1/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 19.0.1+10-21)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode_14-2.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 019AY1SG78 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-arm64   • macOS 12.6.2 21G320 darwin-arm64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by IlyaZadyabin** [comment]
I am experiencing the same issue with file_picker: ^6.1.1
