### ISSUE TITLE
FilePicker may load outdated files

### ISSUE THREAD

**Issue by pohuing** [miguelpruivo/flutter_file_picker#1233]
**Describe the bug**
FilePicker on Android in combination with cloud file providers, such as Nextcloud, may load outdated files if the file has changed on in storage after being loaded once before.
The native picker will show the correct file, FilePicker will load a version it had loaded earlier.
This all happens contrary to the documentation.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Pixel OS, Android 13

**How are you picking?**
```dart
FilePicker.platform.pickFiles(
      allowedExtensions: ['json', 'txt'],
      allowMultiple: false,
      withData: true,
      type: FileType.custom,
    );
```
The code of my application can be found at https://github.com/pohuing/lernapp/tree/f839f3dae77901af2cbbc45cf65d8cf5d2105f2d
File picking happens here: https://github.com/pohuing/lernapp/blob/f839f3dae77901af2cbbc45cf65d8cf5d2105f2d/lib/widgets/import_flow/import_screen.dart#L76

**Details to reproduce the issue**
Load a file through the code above.
Modify the file in another application.
Load the same file again.
FilePicker will load an outdated cached version of the file.

**Error Log**
Nothing is logged.

**Screenshots and/or video**
Here's the issue occurring in my project, using my own nextcloud setup. Note the correct updated timestamps in the file picker.

https://user-images.githubusercontent.com/24683548/222795802-c098d031-7ab4-4149-b89e-c6387f0ffce1.mp4

**Flutter Version details**
<details>
<summary>flutter doctor -v</summary>

```
PS C:\Users\patri> flutter doctor -v
[✓] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22621.1265], locale de-DE)
    • Flutter version 3.7.5 on channel stable at C:\Users\patri\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (9 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\patri\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at:
      C:\Users\patri\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33110.190
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Users\patri\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\patri\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.76.0)
    • VS Code at C:\Users\patri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • Pixel 4a (mobile)                 • 0B211JEC216722  • android-arm64  • Android 13 (API 33)
    • Subsystem for Android TM (mobile) • 127.0.0.1:58526 • android-x64    • Android 13 (API 33)
    • Windows (desktop)                 • windows         • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]    • Edge (web)                        • edge            • web-javascript • Microsoft Edge 110.0.1587.57

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Additional context**
Clearing the app's cache through the app's properties fixes the issue.
On the note of caching behaviour: The wiki states clearing the cache is this is always unnecessary and the `FilePicker.platform.pickFiles` documentation does not mention this behaviour. 
Prior issues with this same issue have been closed in reference to `clearTemporaryFiles()`. I think this should be included in the documentation, and the wiki should be updated to note this footgun.

**Comment by ssaring** [comment]
Same problem for me when loading updated files from a NextCloud folder in Android (13). There will always be the old cached content loaded.

The workaround I've found is to instruct FilePicker to delete the cache before executing the file selection dialog:

`await FilePicker.platform.clearTemporaryFiles();`

Nevertheless, would be gread when this bug could be fixed and cache cleanup is not needed anymore.
