### ISSUE TITLE
Implementing file saving for WEB

### ISSUE THREAD

**Issue by pseusys** [miguelpruivo/flutter_file_picker#1234]
This is a very simple, yet handy option:
You can't save file on web silently, but you can save it to `Downloads` folder.

This can be implemented somehow like this:
```dart
// ignore: avoid_web_libraries_in_flutter
import 'dart:html';

void saveFileFromUri(String name) {
  final file = ...; // File as bytes array
  AnchorElement(href: Uri.dataFromBytes(file).toString())..setAttribute("download", name)..click();
}
```

Please, let me know if you would like to implement it - or I'll have to make a fixture for my project.

**Comment by asetayes** [comment]
that's a very good idea :)

**Comment by asetayes** [comment]
@pseusys, I didn't find any method in this library.

**Comment by zs-dima** [comment]
Any updates are welcome

**Comment by zs-dima** [comment]
Any updates are welcome

**Comment by zs-dima** [comment]
Any updates are welcome

**Comment by miguelpruivo** [comment]
Sorry, I've not been very active on this, if anyone wants to implement the feature, I'll be happy to review/merge. Thanks.

**Comment by pseusys** [comment]
Actually I figured out that this proposal is a bit out of scope for this very project:
The `saveFile()` method does not actually save any files: it just allows user to pick a path where the file should be written to.
That is, btw to my mind, a way misleading behavior - and actual platform dependant reading and saving behaviour could've been implemented as well.
And as for picking file location for reading and/or writing, it is (AFAIK) impossible for Android or iOS, but is possible for web, using [this](https://wicg.github.io/file-system-access/#local-filesystem) not very well-known (and not very wide-implemented API).
Right now I can't contribute to the projects, but maybe will become available in a few weeks/month. Please, keep me informed if you decide to implement something of the things I mentioned in your project - and I'll try to help you!

**Comment by zs-dima** [comment]
Unstable
