### ISSUE TITLE
Setup docs need improvement, currently showing Podfile code that doesn't work

### ISSUE THREAD

**Issue by Khazbs** [miguelpruivo/flutter_file_picker#1236]
Hi! I think the [Optional Permissions](/miguelpruivo/flutter_file_picker/wiki/Setup#optional-permissions) section of the Setup docs page is quite misleading and needs improvement. The code to be added to the Podfile should be formatted in a more clear way, currently its markup encloses extra words.

**Comment by Khazbs** [comment]
Other than that, great plugin! I use it on Android — all works well. On iOS, however, I don't need these pickers, so I would like to exclude them to avoid requiring unnecessary permissions. Improving the docs on that would be very helpful!

**Comment by IanVS** [comment]
Thanks for posting this, I was having trouble.  Too bad the docs are still incorrect.

**Comment by Khazbs** [comment]
@IanVS I'm glad this helped! Maybe we should open a PR to improve the docs ourselves?
