### ISSUE TITLE
FilePicker.pickFile(initialDirectory) fails silently in release mode

### ISSUE THREAD

**Issue by Este2013** [miguelpruivo/flutter_file_picker#1239]
**Describe the bug**
The file picker's initialDirectory parameter works fine in debug mode, but fails silently in release mode (_uses last opened directory instead_).
flutter clean -> flutter build did not fix the issue;
Getting the more recent version of the package did not fix it either.

**Platform**

- Windows

**Platform OS version**
Windows 10 v22h2

**How are you picking?**

Multiple buttons reach out to this class with different parameters: 
```
class LogFilePicker {

	static Future<File?> pick({List<String>? allowedExtensions, String? baseDirectory}) async {
		FilePickerResult? result = await FilePicker.platform.pickFiles(
			type: (allowedExtensions==null) ? FileType.any : FileType.custom,
			allowMultiple: false,
			initialDirectory: baseDirectory,
			lockParentWindow: true,
			allowedExtensions: allowedExtensions,
		);
		if (result == null) return null; // user cancelled file picking

		return File(result.files.single.path!);
	}
}
```

**Details to reproduce the issue**
Through the UI: 
- A button calls LogFilePicker.pick(null, null). I click it and select a file in any folder on my desktop.
- A button calls LogFilePicker.pick(null, "%appdata%\\applicationName\\logs"). I click it.
- Note that the directory that actually opens up is the unrelated directory from my desktop (_when in release mode only!_)

**Error Log**
The bug does not happen in debug mode. Only in release, and it fails silently - the file picking mechanism still works fine. Only, the initial directory is messed up.

**Flutter Version details**
```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.19045.2604], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.76.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```
Note that I'm not interested in iOS development.

**Comment by miguelpruivo** [comment]
It doesn't support initial directory as parameter.

**Comment by philenius** [comment]
Hey @Este2013, thanks for using our issue template and for your thorough explanation.

I copied your code and followed your instructions but could not  reproduce this issue:
![pick-with-initial-directory](https://github.com/miguelpruivo/flutter_file_picker/assets/9049899/f72d358d-d5b1-4bed-a6b8-48977645f999)

The initial directory always works as expected.

I was wondering whether we have the same understanding of _release mode_? I created my _release_ version and started it like this:
```bash
flutter build windows
./build/windows/runner/Release/example.exe
```
