### ISSUE TITLE
File picker is already active thrown when permission denied on Android < API 33

### ISSUE THREAD

**Issue by KKStudios** [miguelpruivo/flutter_file_picker#1251]
When user is asked for permission while picking a file on android <13 and denies twice filepicker throws error about already running.

**Platform**

- [x ] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
<API33

**How are you picking?**
```
var res = await FilePicker.platform.pickFiles(allowMultiple: false, type: FileType.image);
```

**Details to reproduce the issue**
Use Emulator with android 10, 11 or 12 and try to pick an image file. Deny file access and try again. Error is thrown.

**Error Log**
PlatformException(already_active, File picker is already active, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)

**Comment by PrasadDhend** [comment]
### **_Adding the below lines of code worked for me!_**

**library**
`file_picker: ^5.2.6`

**android/app/build.gradle**

`compileSdkVersion 33`
`ndkVersion flutter.ndkVersion`


**android/app/src/main/AndroidManifest.xml**

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`

### Take a permission using below code

`final status = await Permission.manageExternalStorage.request();`
`     if (status.isDenied ||`
`        status.isPermanentlyDenied ||`
`       status.isRestricted) {`
`    throw "Please allow storage permission to upload files";`
` }`
