### ISSUE TITLE
file picker not focused automatically after open

### ISSUE THREAD

**Issue by jwang0512** [miguelpruivo/flutter_file_picker#1252]
**Describe the bug**
file picker not focused automatically. the focus is still on the application window

**Platform**
MacOS

**Platform OS version**
12.6

**How are you picking?**
```
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      dialogTitle: 'Select your file:',
      type: FileType.custom,
      allowedExtensions: ["abc"],
    );
```

**Flutter Version details**
3.7.7

**Comment by philenius** [comment]
Please search for similar issues before creating a new one. As numerously times explained, we cannot implement that.
Please read this https://github.com/miguelpruivo/flutter_file_picker/issues/1242#issuecomment-147871660 and use the official Flutter plugin named file_selector (https://pub.dev/packages/file_selector).
