### ISSUE TITLE
The current directory was changed after pick a file

### ISSUE THREAD

**Issue by MahmoudKhalid** [miguelpruivo/flutter_file_picker#1254]
I noticed after i picked a file, the current directory has changed!
```dart
print(Directory.current.path); // "D:\Workspace\"

// I picked a file from desktop
FilePicker.platform.pickFiles(lockParentWindow: true).then((result) {
    print(Directory.current.path);  // "C:\Users\darkn\Desktop\"
});
```

My simple solution to restore my workspace again as below
```dart
final Directory currentDir = Directory.current;

FilePicker.platform.pickFiles(lockParentWindow: true).then((result) {
    Directory.current = currentDir;
});
```

**Comment by philenius** [comment]
I would appreciate if you could search for similar issues before creating a new one. Thank you.

Related to #804. I will look into it.

**Comment by MahmoudKhalid** [comment]
@philenius Great work, Thank you

**Comment by philenius** [comment]
I'm still working on it and will most probably create a pull request tonight.

**Comment by philenius** [comment]
@MahmoudKhalid please check-out the branch of my pull request https://github.com/miguelpruivo/flutter_file_picker/pull/1256 and run the example app to check whether your issue has been resolved! Can you confirm that it is now working as it should?

**Comment by MahmoudKhalid** [comment]
@philenius Yes, I just tried it on windows 11
It works fine, Thank you

**Comment by philenius** [comment]
Thank you so much for your quick response. My pull request is now waiting for Miguel's approval. Might take a few days.
