### ISSUE TITLE
Update win32 please

### ISSUE THREAD

**Issue by kirill-21** [miguelpruivo/flutter_file_picker#1255]
![image](https://user-images.githubusercontent.com/63228361/230415815-89e38310-6cec-438e-97de-f13c1f29940d.png)

**Comment by philenius** [comment]
Good point!

Same issue: #1222

I'm planning to merge the bugfix branch that I'm currently working on and then release a new major version of `file_picker` with `win32` 4.1.1.

**Comment by philenius** [comment]
I will fix https://github.com/miguelpruivo/flutter_file_picker/issues/1257 first, and then bump the win32 version. As of right now, I'm still undecided whether we should bump our major or minor version after updating `win32`. SemVer does not specify how to handle major dependency upgrades and there are several discussions, e.g.:
* https://softwareengineering.stackexchange.com/questions/168647/best-practices-for-versioning-project-after-dependency-upgrade?rq=1
* https://github.com/semver/semver/issues/148
