### ISSUE TITLE
Windows Save Dialog overrides names when fileName is defined

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [miguelpruivo/flutter_file_picker#1257]
**Describe the bug**

I'm using Save Dialog like so:
```dart
const String defaultName = "423645783456786358628546789346789.png";
String? outputFile = await FilePicker.platform.saveFile(
	dialogTitle: 'Save Screenshot As:',
	fileName: defaultName,
	allowedExtensions: [".png"],
	type: FileType.image);

print(outputFile);
```
Now let's save the file like it is, without changing the name:
<img src="https://user-images.githubusercontent.com/54041533/230681085-5fa7fa06-4221-4408-8eb7-ad008a80c45e.png" width="450px"/>

Perfect, now let's change the name to "Test" (without the quotes) in the file picker like so:
<img src="https://user-images.githubusercontent.com/54041533/230681223-ec0592c1-efb8-40cf-8da8-c7505fa58e6d.png" width="300px"/>

And save, let's see the output path, this is what I get:
<img src="https://user-images.githubusercontent.com/54041533/230681365-cef6acfe-d583-4b99-8c8e-16abe800bcbe.png" width="450px"/>

Expected to get C:\Users\siuba\Desktop\Test.png

**Platform / OS version**
Windows 11 Pro 22H2

**Flutter Version details**
```
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.22621.1485], locale es-ES)
    • Flutter version 3.7.8 on channel stable at C:\Users\siuba\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (2 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at O:\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\siuba\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.77.1)
    • VS Code at C:\Users\siuba\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1485]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.50
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by philenius** [comment]
@YarostheLaunchpadder , thank you for using our issue template and providing detailed information. I copied your code snippet into our example app and I could not reproduce this behavior on Windows 11:
![windows](https://user-images.githubusercontent.com/9049899/231601781-c793a2e8-aef0-4e8f-80cc-1f54940ea59c.gif)

Do you still experience this issue? And if so, can you provide a screen recording (e.g. I can recommend https://www.screentogif.com/) or what are you doing differently to me?

**Comment by philenius** [comment]
@YarostheLaunchpadder, I must correct my previous statement. I can now reproduce this bug, too. Somehow, it only happens for certain directories. For example, see the following screen recording:
1. Saving a file named `Test` on desktop causes this bug.
2. Saving a file named `Test` inside another directory not necessarily causes this bug (I tested it with `C:\` and a sub-directory on my desktop.

Aölso, this bug only occurs when I provide a default file name for the file picker dialog.

![bug](https://user-images.githubusercontent.com/9049899/232342655-21b54434-8282-44fb-bd43-26b01f5b8803.gif)

I'm looking into this issue.
