### ISSUE TITLE
File 0:null

### ISSUE THREAD

**Issue by prasant10050** [miguelpruivo/flutter_file_picker#126]
I am using this plugin and m getting issue when i pick any file or files from Download section of File explorer in Nokia 5.1 plus handset but when i m picking image or images from gallery it's working fine.
I am attaching my console when i pick file from Download.
Min SDK version : 19
Compile and Target SDK version : 28

-------------------------------------------------------------------------------------------
[+44713 ms] I/FilePicker(22519): Checking permission: android.permission.READ_EXTERNAL_STORAGE
[ +649 ms] D/Surface (22519): Surface::disconnect(this=0x797e5ed000,api=1)
[        ] D/Surface (22519): Surface::disconnect(this=0x797e5ed000,api=-1)
[   +6 ms] D/Surface (22519): Surface::disconnect(this=0x7982ae2000,api=1)
[  +17 ms] V/PhoneWindow(22519): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@f2560ca, this = DecorView@ca3f23b[MainActivity]
[+4173 ms] I/FilePicker(22519): [SingleFilePick] File URI:content://com.android.providers.downloads.documents/document/1651
[        ] E/FilePickerUtils(22519): Getting for API 19 or abovecontent://com.android.providers.downloads.documents/document/1651
[   +9 ms] E/FilePickerUtils(22519): Document URI
[        ] E/FilePickerUtils(22519): Downloads External Document URI
[        ] E/FilePickerUtils(22519): Something went wrong while retrieving document path: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/1651
[   +3 ms] E/FilePickerUtils(22519): Something went wrong while retrieving document path: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/1651 from pid=22519, uid=10431 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
[        ] I/FilePickerUtils(22519): Caching file from remote/external URI
[  +25 ms] I/FilePickerUtils(22519): File loaded and cached at:/data/user/0/com.example.flutter_pract/cache/null
[        ] I/FilePicker(22519): Absolute file path:/data/user/0/com.example.flutter_pract/cache/null
[   +2 ms] V/PhoneWindow(22519): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@f2560ca, this = DecorView@ca3f23b[MainActivity]
[  +23 ms] D/Surface (22519): Surface::connect(this=0x7982ae2000,api=1)
[        ] D/mali_winsys(22519): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
[   +3 ms] D/Surface (22519): Surface::connect(this=0x797e5ed000,api=1)
[        ] D/mali_winsys(22519): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000

please fix this issue as soon as possible it's urgent

**Comment by miguelpruivo** [comment]
@prasant10050 what kind of file are you picking? Does this happen to all kind of files? Thank you.

**Comment by sulaysumaria** [comment]
@miguelpruivo , I am also facing similar issue..... I use following code to pick multiple images:

```dart
Map<String, String> resultList = await FilePicker.getMultiFilePath(type: FileType.IMAGE);
```

it returns me 
```
{null: /data/user/0/com.example.app/cache/null}
```

I am selecting multiple photos from Google Photos App but it seems to select only last photo I selected... I also got following logs:
```
E/FilePickerUtils( 6934): Getting for API 19 or abovecontent://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A54fa4baf-ff40-4749-a57b-e9320803b32a/ORIGINAL/NONE/1464321420
E/FilePickerUtils( 6934): NO DOCUMENT URI - CONTENT
I/FilePickerUtils( 6934): Caching file from remote/external URI
I/FilePickerUtils( 6934): File loaded and cached at:/data/user/0/com.example.app/cache/null
I/FilePicker( 6934): [MultiFilePick] File #0 - URI: /0/1/mediakey:/local%3A54fa4baf-ff40-4749-a57b-e9320803b32a/ORIGINAL/NONE/1464321420
E/FilePickerUtils( 6934): Getting for API 19 or abovecontent://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A0a2c42ec-1741-460b-a5a6-7fd27b7e1670/ORIGINAL/NONE/997802903
E/FilePickerUtils( 6934): NO DOCUMENT URI - CONTENT
I/FilePickerUtils( 6934): Caching file from remote/external URI
I/FilePickerUtils( 6934): File loaded and cached at:/data/user/0/com.example.app/cache/null
I/FilePicker( 6934): [MultiFilePick] File #1 - URI: /0/1/mediakey:/local%3A0a2c42ec-1741-460b-a5a6-7fd27b7e1670/ORIGINAL/NONE/997802903
E/FilePickerUtils( 6934): Getting for API 19 or abovecontent://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A66386815-1d3b-4c83-bc22-9ae1a912b091/ORIGINAL/NONE/2005870601
E/FilePickerUtils( 6934): NO DOCUMENT URI - CONTENT
I/FilePickerUtils( 6934): Caching file from remote/external URI
I/FilePickerUtils( 6934): File loaded and cached at:/data/user/0/com.example.app/cache/null
I/FilePicker( 6934): [MultiFilePick] File #2 - URI: /0/1/mediakey:/local%3A66386815-1d3b-4c83-bc22-9ae1a912b091/ORIGINAL/NONE/2005870601
```

It appears the name of files is not coming properly when the file is stored in cache by device... Thus, it replaces the files, saving them all as `null` filename and hence, returns only the last one...

Hope this details help to solve the issue, waiting for this to resolve soon...

**Comment by miguelpruivo** [comment]
Yes, I’m aware of this issue already. As soon as I have sometime I’ll try to fix it. It looks like this happens only when picking from Google Photos.

Thank you for your feedback.

**Comment by sulaysumaria** [comment]
Do you know any workaround for this?

**Comment by sulaysumaria** [comment]
That would be great.... Thanks...

**Comment by miguelpruivo** [comment]
Just to let you know that a fix for this was landed today with [1.4.1](https://pub.dev/packages/file_picker#-changelog-tab-) on pub.dev.

FYI, the name was being set to `null` for every Google Photo due to a name resolution fail, but the file should work anyway, even if the name of the file in the URI was set to `null`). Anyhow, this, of course, wouldn't provide a good readable solution and wouldn't work for multiple files though.

Just make sure you set your version to `file_picker: 1.4.1` and clean & build again.

Thank you for reporting!

**Comment by miguelpruivo** [comment]
@prasant10050 @sulaysumaria just to let you know that a fix for this was landed today with [1.4.1](https://pub.dev/packages/file_picker#-changelog-tab-) on pub.dev.

FYI, the name was being set to `null` for every Google Photo due to a name resolution fail, but the file should work anyway, even if the name of the file in the URI was set to `null`). Anyhow, this, of course, wouldn't provide a good readable solution and wouldn't work for multiple files though.

Just make sure you set your version to `file_picker: 1.4.1` and clean & build again.

Thank you for reporting!

**Comment by miguelpruivo** [comment]
@prasant10050 @sulaysumaria just to let you know that a fix for this was landed today with [1.4.1](https://pub.dev/packages/file_picker#-changelog-tab-) on pub.dev.

FYI, the name was being set to `null` for every Google Photo due to a name resolution fail, but the file should work anyway, even if the name of the file in the URI was set to `null`). Anyhow, this, of course, wouldn't provide a good readable solution and wouldn't work for multiple files though.

Just make sure you set your version to `file_picker: 1.4.1` and clean & build again. If you find any issue related to this, feel free to reopen the issue.

Thank you for reporting!

**Comment by Fluics** [comment]
@miguelpruivo We have similar issue with any file (tested on downloaded from web pdf -> pick from downloads), but only reproduced on one phone type: Umidigi A3 with Android 8.1 and with 9.0.  Any suggestions? Thank you!

`I/FilePickerUtils(32449): File loaded and cached at:/data/user/0/com.app/cache/8454
I/FilePicker(32449): Absolute file path:/data/user/0/com.app/cache/8454`

**Comment by miguelpruivo** [comment]
@Fluics to me that looks ok:  `Absolute file path:/data/user/0/com.app/cache/8454`

That happens because somehow the file can't be handled in some other way (due to custom ROM, protection, etc.) and it's copied and cached temporary and given a random id name (8454). But you should not have any issue on loading it. When it happen only in one or two device brands, always suspect from the ROM, specially those custom ROM brands.

**Comment by Fluics** [comment]
@miguelpruivo but other apps (e.g. slack) do not have any problems with this file. Is there any possibility to get the real name?

**Comment by miguelpruivo** [comment]
@Fluics that's odd. Probably because Slack is using a content provider to handle the file which the file picker is not (because otherwise it would have to handle the files in a completely different way). Could you post the full log? Are you picking the file in the exact same way with Slack?

**Comment by Fluics** [comment]
@miguelpruivo file picker is the same. One more detail. If I pick an image - filename is preserved. Here are both cases: image at first, then pdf
Gist: https://gist.github.com/7e8d786be199b2780af659da8ed807aa

same below
`
2019-09-19 18:09:06.315 32449-32449/com.fluics.dev I/FilePicker: Checking permission: android.permission.READ_EXTERNAL_STORAGE
2019-09-19 18:09:14.145 32449-5980/com.fluics.dev I/FilePicker: [SingleFilePick] File URI:content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FVSS00031.jpg
2019-09-19 18:09:14.145 32449-5980/com.fluics.dev E/FilePickerUtils: Getting for API 19 or abovecontent://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FVSS00031.jpg
2019-09-19 18:09:14.158 32449-5980/com.fluics.dev E/FilePickerUtils: Document URI
2019-09-19 18:09:14.159 32449-5980/com.fluics.dev E/FilePickerUtils: Downloads External Document URI
2019-09-19 18:09:14.161 32449-5980/com.fluics.dev I/FilePicker: Absolute file path:/storage/emulated/0/Download/VSS00031.jpg
2019-09-19 18:14:06.715 32449-6426/com.fluics.dev D/BitmapWorkerTask: Uri scheme: file
2019-09-19 18:14:46.177 32449-32449/com.fluics.dev I/FilePicker: Checking permission: android.permission.READ_EXTERNAL_STORAGE
2019-09-19 18:14:53.544 32449-6532/com.fluics.dev I/FilePicker: [SingleFilePick] File URI:content://com.android.providers.downloads.documents/document/305
2019-09-19 18:14:53.545 32449-6532/com.fluics.dev E/FilePickerUtils: Getting for API 19 or abovecontent://com.android.providers.downloads.documents/document/305
2019-09-19 18:14:53.556 32449-6532/com.fluics.dev E/FilePickerUtils: Document URI
2019-09-19 18:14:53.556 32449-6532/com.fluics.dev E/FilePickerUtils: Downloads External Document URI
2019-09-19 18:14:53.589 32449-6532/com.fluics.dev I/FilePickerUtils: Caching file from remote/external URI
2019-09-19 18:14:53.721 32449-6532/com.fluics.dev I/FilePickerUtils: File loaded and cached at:/data/user/0/com.fluics.dev/cache/60421
2019-09-19 18:14:53.721 32449-6532/com.fluics.dev I/FilePicker: Absolute file path:/data/user/0/com.fluics.dev/cache/60421
`

**Comment by miguelpruivo** [comment]
@Fluics move that file to other folder and pick it from there, does the problem still happen?

**Comment by Fluics** [comment]
@miguelpruivo Ha! This works! But this is for advanced users - I need to enable "Show internal storage" at first. Any ideas to get working from "Downloads"?

```
2019-09-19 18:50:37.377 32449-32449/com.fluics.dev I/FilePicker: Checking permission: android.permission.READ_EXTERNAL_STORAGE
2019-09-19 18:51:32.025 32449-10442/com.fluics.dev I/FilePicker: [SingleFilePick] File URI:content://com.android.externalstorage.documents/document/primary%3Atest%2FFasteningandPowerScrews.pdf
2019-09-19 18:51:32.035 32449-10442/com.fluics.dev E/FilePickerUtils: Getting for API 19 or abovecontent://com.android.externalstorage.documents/document/primary%3Atest%2FFasteningandPowerScrews.pdf
2019-09-19 18:51:32.048 32449-10442/com.fluics.dev E/FilePickerUtils: Document URI
2019-09-19 18:51:32.051 32449-10442/com.fluics.dev E/FilePickerUtils: External Document URI
2019-09-19 18:51:32.054 32449-10442/com.fluics.dev E/FilePickerUtils: Primary External Document URI
2019-09-19 18:51:32.060 32449-10442/com.fluics.dev I/FilePicker: Absolute file path:/storage/emulated/0/test/FasteningandPowerScrews.pdf
```

**Comment by miguelpruivo** [comment]
I’ll take a look as soon as I’ve some time to further investigate this. It would be easier if I could just use Content Provider to handle all files on Android devices, however that would force the dev to handle virtual uris and not actually the absolute path and it wouldn’t be possible to use it as a `File` object on Dart side.

**Comment by Fluics** [comment]
@miguelpruivo should we reopen the issue or make a new one?

**Comment by miguelpruivo** [comment]
@Fluics there was already an issue for that, but right now it will stay as it is as some users would rather keep to have the absolute path instead of provider's URIs. But feel free to leave it in the #99.

Thank you.

**Comment by braysonjohn148** [comment]
I am using file_picker: ^1.6.3+1. But still getting an error 
`I/FilePickerUtils(32449): File loaded and cached at:/data/user/0/com.app/cache/8454 I/FilePicker(32449): Absolute file path:/data/user/0/com.app/cache/8454`

When i select from Downloads/ folder. How can i fix this.
