### ISSUE TITLE
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allow reading external storage

### ISSUE THREAD

**Issue by codermonk1** [miguelpruivo/flutter_file_picker#1263]
when i click to fetch file like pdf then its give error ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allow reading external storage
 
Its only happened in android 13 , sdk33

**Comment by samir-a-ts** [comment]
Is there any information about this issue? I have the same problem.

**Comment by CoderNamedHendrick** [comment]
I'm having a similar issue with my company's app. Is there a possible fix for this problem?

**Comment by CoderNamedHendrick** [comment]
I did some digging around and found that the intent this package is sending to get files has been rescinded for Android 13 actively and should be moving to Android 11+ in the [future.](https://developer.android.com/training/data-storage/shared/documents-files#document-tree-access-restrictions)

I am going to try some things on my end if I can find a fix for it

**Comment by gerken-tss** [comment]
@CoderNamedHendrick 
Thank you for looking further into the issue! Would be very grateful for a solution 🙏. If I can be of any assistance, please let me know!

It's weird that it doesn't affect every device / manufacturer. Samsung S21 Ultra is definitely affected. Pixel 4a isn't. Some One Plus models are also not affected. This is the part I don't understand.

**Comment by CoderNamedHendrick** [comment]
@gerken-tss  slight problem. The issue doesn't seem reproducible on Android emulators. Working on getting my hands on a pixel where the error was detected via crashlytics, I'll keep you posted on my progress. Also if you have a device where the error occurs you could clone the package repository and try some of these new [intents.](https://developer.android.com/training/data-storage/shared/documents-files#java)

**Comment by gerken-tss** [comment]
@CoderNamedHendrick 
Do you have a list of devices that are linked to this error (from your Crashlytics error logging)? That would be very helpful!

**Comment by CoderNamedHendrick** [comment]
Just pixel 6 for now @gerken-tss

**Comment by miguelpruivo** [comment]
@CoderNamedHendrick feel free to issue a PR if you've already managed to fix it, I'll review/merge it right away.

**Comment by CoderNamedHendrick** [comment]
For my use-case, it seems the issue was already solved.  After numerous tests and comparing versions, I discovered it was a version problem on my end. 
@codermonk1  @gerken-tss try upgrading the package on your end. It should fix it.

**Comment by CoderNamedHendrick** [comment]
> @CoderNamedHendrick feel free to issue a PR if you've already managed to fix it, I'll review/merge it right away.

It's been fixed already, sorry for making a fuss and thanks for such a wonderful package

**Comment by codermonk1** [comment]
> > @CoderNamedHendrick feel free to issue a PR if you've already managed to fix it, I'll review/merge it right away.
> 
> It's been fixed already, sorry for making a fuss and thanks for such a wonderful package

which version used???

**Comment by CoderNamedHendrick** [comment]
> > > @CoderNamedHendrick feel free to issue a PR if you've already managed to fix it, I'll review/merge it right away.
> > 
> > It's been fixed already, sorry for making a fuss and thanks for such a wonderful package
> 
> which version used???
> 

I was on an earlier version and it's been fixed on 5.2.10. I should have checked the changelogs

**Comment by RomanPreis** [comment]
> > > > @CoderNamedHendrick feel free to issue a PR if you've already managed to fix it, I'll review/merge it right away.
> > > 
> > > 
> > > It's been fixed already, sorry for making a fuss and thanks for such a wonderful package
> > 
> > 
> > which version used???
> 
> I was on an earlier version and it's been fixed on 5.2.10. I should have checked the changelogs

I'm using 5.2.10 right now and I'm running into this bug

**Comment by codermonk1** [comment]
> > > > > @CoderNamedHendrick feel free to issue a PR if you've already managed to fix it, I'll review/merge it right away.
> 
> > > > 
> 
> > > > 
> 
> > > > It's been fixed already, sorry for making a fuss and thanks for such a wonderful package
> 
> > > 
> 
> > > 
> 
> > > which version used???
> 
> > 
> 
> > I was on an earlier version and it's been fixed on 5.2.10. I should have checked the changelogs
> 
> 
> 
> I'm using 5.2.10 right now and I'm running into this bug

remove plug in from dependency then again add from terminal if again error them change your kotin version
