### ISSUE TITLE
Doesnt work on android anymore

### ISSUE THREAD

**Issue by cyberpwnn** [miguelpruivo/flutter_file_picker#1271]
![wow](https://user-images.githubusercontent.com/10619135/235672415-c75a38e7-e354-42e8-b58c-8c7e2cc05960.gif)

```dart
FilePickerResult? result = await FilePicker.platform.pickFiles(
    type: FileType.any,
    allowMultiple: false,
  );
```

**Comment by nkenna** [comment]
Any help on this. Mine does not even open the file picker dialog.
