### ISSUE TITLE
[Android] Can't list files in folder that aren't created by the app

### ISSUE THREAD

**Issue by kirasok** [miguelpruivo/flutter_file_picker#1276]
file_picker: ^5.3.0

**Describe the bug**
Can't list files using `Directory(path).listSync()` after obtaining path using `FilePicker.platform.getDirectoryPath()` that were not created by the app itself.  
If before listing files we create some using `File(path+"/test.txt").createSync()` only this file will be in the list.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 13

**How are you picking?**
```dart
    String? result = await FilePicker.platform.getDirectoryPath();
    var dir = Directory(result ?? "~");
    File("${dir.path}/test.txt").createSync();
    files = dir.listSync();
```

**Details to reproduce the issue**
<details>
<summary>main.dart</summary>
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Storage Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<FileSystemEntity> files = [];
  void _selectFolder() async {
    String? result = await FilePicker.platform.getDirectoryPath();
    var dir = Directory(result ?? "~");
    File("${dir.path}/test.txt").createSync();
    files = dir.listSync();
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ListView.builder(
            itemBuilder: (context, index) =>
                Text("${files[index] is File} ${files[index].path}"),
            itemCount: files.length),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _selectFolder,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
</details>

**Error Log**
<details>
<summary>Console log</summary>
E/SurfaceSyncer(23248): Failed to find sync for id=0

W/Parcel  (23248): Expecting binder but got null!

D/CompatibilityChangeReporter(23248): Compat change id reported: 78294732; UID 
10363; state: ENABLED

D/FilePickerDelegate(23248): [SingleFilePick] File URI:content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FTest/document/primary%3ADocuments%2FTest

W/ge.storage_test(23248): Accessing hidden method Landroid/os/storage/StorageManager;->getVolumeList()[Landroid/os/storage/StorageVolume; (unsupported, reflection, allowed
)

E/OpenGLRenderer(23248): Unable to match the desired swap behavior.

E/SurfaceSyncer(23248): Failed to find sync for id=0

E/SurfaceSyncer(23248): Failed to find sync for id=1

</details>

**Flutter Version details**
<details>
<summary>flutter doctor -v</summary>
[!] Flutter (Channel stable, 3.7.12, on Arch Linux 6.3.1-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 3.7.12 on channel stable at /opt/flutter
    ! Warning: `dart` on your path resolves to /opt/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at /opt/flutter. Consider adding /opt/flutter/bin to the front of
      your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version openjdk version "17.0.6" 2023-01-17
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.6" 2023-01-17

[✓] Connected device (3 available)
    • M2102J20SG (mobile) • 192.168.1.2:42577 • android-arm64  • Android 13 (API 33)
    • Linux (desktop)     • linux               • linux-x64      • Arch Linux 6.3.1-zen1-1-zen
    • Chrome (web)        • chrome              • web-javascript • Chromium 113.0.5672.63 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
</details>

**Additional context**
Same code works on Linux
Also I found [1-month old question](https://stackoverflow.com/questions/75934584/cannot-list-files-inside-selected-folder-on-android) on StackOverflow that has the same problem

**Comment by tomekit** [comment]
We're using `5.3.1`, but problem exists also in older versions.
In our case we can list media files, but can't really list different file types.

**Comment by tomekit** [comment]
Our ultimate solution on Android for picking files within the folder was using: https://pub.dev/packages/saf, unfortunately we haven't yet got sub-folders to work, I am sure we will work it out eventually.
