### ISSUE TITLE
Fails to build for Android after upgrading to Flutter 3.0

### ISSUE THREAD

**Issue by venil7** [miguelpruivo/flutter_file_picker#1278]
* Where:
Build file '/Users/<user>/.pub-cache/hosted/pub.dev/file_picker-5.3.0/android/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':file_picker'.
> Could not find method namespace() for arguments [com.mr.flutter.plugin.filepicker] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by DeanPack** [comment]
I'm having the same issue

**Comment by venil7** [comment]
i literally commented out line 41 in gradle and it started building

i appreciate it's not a solution youre looking for :)

**Comment by navaronbracke** [comment]
What version of Gradle / Android Gradle Plugin are you using?
You should update to Gradle 7 at least since that version recognizes the `namespace` attribute.

**Comment by Sesa1988** [comment]
I found that I forgot to add:
```
buildscript {
    **ext.kotlin_version = '1.7.10'**
    repositories {
        google()
        jcenter()
    }

    dependencies {
        **classpath 'com.android.tools.build:gradle:7.3.0'**
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```
It builds like this, I didn't test for runtime errors but it seems its working.

**Comment by charden-daxicen** [comment]
> 

Updating **android/build.gradle** file's dependencies resolve the issue

**from**  
```
  dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
```
    
    **to**
```
  dependencies {
         classpath 'com.android.tools.build:gradle:7.3.1'
    }
```

**Comment by mw66** [comment]
> This is a fix for the build error:
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.7.10' <-----updated this one
>     repositories {
>         google()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:7.3.0' <-----updated this one
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.3'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         jcenter()
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> tasks.register("clean", Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> The build works like this but I didn't test for runtime errors in detail but it seems its working.

@Sesa1988  can you create a PR to update this file?

Thanks.
