### ISSUE TITLE
unable to run pub get after update 

### ISSUE THREAD

**Issue by fisforfaheem** [miguelpruivo/flutter_file_picker#1283]
please use latest version of packages in you yaml file so we can all benefits also add flutter 3.10 support

**Comment by philenius** [comment]
@fisforfaheem , this issue should be solved with `filer_picker` version 5.3.1. Can you confirm that?

**Comment by fisforfaheem** [comment]
No, it doesn't.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/26/23,
01:40:02 AM
