### ISSUE TITLE
'lockParentWindow = true' makes file name edit field lost initial focus

### ISSUE THREAD

**Issue by austin2408** [miguelpruivo/flutter_file_picker#1293]
If set 'lockParentWindow = true', after showing up dialog, it need to click file name edit field first and then can type anything, is it as expected ? If set false, it's fine.

**Comment by philenius** [comment]
Please use our issue template. On which platform are you? Windows, Linux, macOS?

**Comment by philenius** [comment]
Duplicate of #1295
