### ISSUE TITLE
Bug in flutter web on manage PLataformFile

### ISSUE THREAD

**Issue by Spiderbezno** [miguelpruivo/flutter_file_picker#1296]
When the project is loading I can see this problem in the bug console and the loading is stopped, I think is. anull in 

TypeError: Cannot read properties of undefined (reading 'Symbol(dartx.add)')
packages/file_picker/_internal/file_picker_web.dart 31:21                         [_ensureInitialized]
packages/file_picker/_internal/file_picker_web.dart 17:15                         __
packages/file_picker/_internal/file_picker_web.dart 14:55                         get platform
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 941:8   get
packages/file_picker/_internal/file_picker_web.dart 21:27 

Here the code where the error occurred

Future<void> pickFile() async {
    final FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      type: FileType.custom,
      allowedExtensions: <String>["pdf", "doc", "png", "jpg"],
    );
    if (result != null) {
      // List<File> files = result.paths.map((path) => File(path)).toList();
      _email.attachments = <Uint8List>[];
      _email.attachmentNames = <String>[];
      _email.attachedMultipleFiles = <String, String>{};

      for (final PlatformFile fil in result.files) {
        final Uint8List fileBytes = fil.bytes!;
        _email.attachments!.add(fileBytes);
        _email.attachmentNames!.add(fil.name);
        _email.attachedMultipleFiles!.putIfAbsent(fil.name, () => base64Encode(fil.bytes!));
      }
      setState(() {});
    } else {
      // User canceled the picker
    }
  }

**Comment by JgomesAT** [comment]
Why is this closed, in web when flutter is run the entire project is not running because of this error and you need to reload again many times until work
