### ISSUE TITLE
[Web, MacOS] Uncaught Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by ernest-ag5** [miguelpruivo/flutter_file_picker#1307]
**Describe the bug**
While developing (running the app in Android Studio), picking files will open the OS Finder as expected.
In the deployed version, this exception is thrown on Mac (not checked other OS).

**Platform**
- [ x] Web

**Platform OS version**
Mac 11.7.6

**How are you picking?**
```
FilePicker.platform.pickFiles
```

**Error Log**
```
main.dart.js:5122 Uncaught Unsupported operation: Platform._operatingSystem
    at Object.c (https://app.go-toad.com/main.dart.js:5122:3)
    at Object.b9m (https://app.go-toad.com/main.dart.js:8783:15)
    at Object.b9n (https://app.go-toad.com/main.dart.js:8815:16)
    at https://app.go-toad.com/main.dart.js:112349:22
    at a.<computed> [as rz] (https://app.go-toad.com/main.dart.js:32:36)
    at https://app.go-toad.com/main.dart.js:112356:24
    at a.<computed> [as aYz] (https://app.go-toad.com/main.dart.js:32:36)
    at Object.b3N (https://app.go-toad.com/main.dart.js:9403:6)
    at https://app.go-toad.com/main.dart.js:112364:23
    at a.<computed> [as aYd] (https://app.go-toad.com/main.dart.js:28:34)
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Flutter 3.10.4

**Comment by ernest-ag5** [comment]
seems related to https://github.com/flutter/flutter/issues/36126

and mentioned here with a suggestion for a better platform check

https://www.wafrat.com/fixing-caught-error-unsupported-operation-platform-_operatingsystem/

**Comment by felocru** [comment]
the same problem on the web-windows

**Comment by jakusb** [comment]
Please fix, I have the same issue. It should be a simple fix to apply suggestion of @ernest-ag5 above

**Comment by nithinjith-42** [comment]
We are also facing the same issue in Firebase hosted web app. Unable to pick files using this package.

**Comment by verrannt** [comment]
Have the same issue on Flutter 3.10.5 on MacOS, building with Flutter web.

Tested `file_picker` versions `5.0.0`, `5.2.5`, and `5.3.2` (latest)

Code:
```dart
await FilePicker.platform.pickFiles()
```

Since this error is caused by calling `Platform.isIos` or `Platform.isAndroid` on Flutter web, the likely cause is that `file_picker` is missing an appropriate check using the `kIsWeb` key at some place.

**Comment by verrannt** [comment]
Okay I think we're all just doing it wrong, because there is **`FilePickerWeb`** and using that, instead of the default `FilePicker`, does work for me. 

```dart
FilePickerResult? result = await FilePickerWeb.platform.pickFiles();
```

Have to say that this is unfortunately not at all clear from the documentation.

**Comment by vagadiyainfotech** [comment]
I am getting this error while picking files in web

Error: Unsupported operation: Platform._operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                   _operatingSystem
dart-sdk/lib/io/platform_impl.dart 56:40                                          get operatingSystem
dart-sdk/lib/io/platform.dart 66:45                                               get _operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 941:8   get
dart-sdk/lib/io/platform.dart 157:51                                              get isAndroid
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 941:8   get
packages/file_picker/src/file_picker.dart 50:18                                   _setPlatform
packages/file_picker/src/file_picker.dart 40:44                                   get _instance
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 941:8   get
packages/file_picker/src/file_picker.dart 42:37                                   get platform
packages/untitled7/main.dart 113:38                                               <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/untitled7/main.dart 108:88                                               <fn>
packages/flutter/src/gestures/recognizer.dart 275:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 654:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 311:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 244:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 630:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:12                           [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 465:19                                 handleEvent
packages/flutter/src/gestures/binding.dart 445:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 331:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 400:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 363:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 320:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 293:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1251:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 269:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 168:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 791:20                                    <fn>
lib/_engine/engine/pointer_binding.dart 720:14                                    <fn>
lib/_engine/engine/pointer_binding.dart 317:16                                    loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall

**Comment by verrannt** [comment]
As I said [above](https://github.com/miguelpruivo/flutter_file_picker/issues/1307#issuecomment-1640056885), there is (for whatever reason) a different class called `FilePickerWeb` that we need to use:
```dart
FilePickerResult? result = await FilePickerWeb.platform.pickFiles();
```
Would be very helpful if the existence of this class was mentioned in the documentation, I only found it by chance!

**Comment by navaronbracke** [comment]
We should not _have_ to use that, it should be the default implementation for web (using the registerWith() plugin registration method, like it's supposed to do)

Similarly, the `_setInstance()` should not do any platform checks, that should be configured in the pubspec instead.

**Comment by ThomasGHenry** [comment]
Completely killing (as opposed to just `r` or `R`) and restarting the dev server (`flutter run -d Chrome`) after installation resolved it for me.
