### ISSUE TITLE
flutter: error: PathNotFoundException: Cannot retrieve length of file, path = '/Users/dlcontrol/Library/Developer/CoreSimulator/Devices/A649551D-9EB8-4B44-9514-97CD11DBD5C8/data/Containers/Data/Application/9CAC3E97-ED48-481F-A4E3-62A68D8D1C52/tmp/uz.udevs.geoinfocomMobile-Inbox/ruxsatnoma 59825.pdf' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by blackpink7** [miguelpruivo/flutter_file_picker#1312]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by omarmgerbie** [comment]
@blackpink7 use my fork until the owner responds to my PR, I've solved this issue here #1311
