### ISSUE TITLE
Windows: Directory Picker bugged

### ISSUE THREAD

**Issue by sidetraxaudio** [miguelpruivo/flutter_file_picker#1317]
- Flutter (Channel beta, 3.12.0-1.1.pre, on Microsoft Windows [Version 10.0.22621.1928], locale en-AU)
- Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
- Latest picker dep 5.3.2

**Describe the bug**

- Folder picker crashes immediately on windows desktop. Code included below.

**Platform**

- Desktop

**Platform OS version**

- Microsoft Windows [Version 10.0.22621.1928]

**How are you picking?**
```
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart' as fp;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Center(
        child: TextButton(
            onPressed: () async {
              await pickFolder();
            },
            child: const Text('PICK FOLDEER')),
      ),
    );
  }

  Future<void> pickFolder() async {
    final String bla = await fp.FilePicker.platform.getDirectoryPath() ?? 'none';
    print(bla);
  }
}
```

**Details to reproduce the issue**

- Latest windows 11 / Latest VS / Latest flutter beta.
- Run code and either select folder or cancel selection.
- Lost connection to device or silent crash in release

**Error Log**
Lost connection to device.
Exited.

**Flutter Version details**
[√] Flutter (Channel beta, 3.12.0-1.1.pre, on Microsoft Windows [Version 10.0.22621.1928], locale en-AU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.79.2)
[√] Connected device (3 available)
[√] Network resources

**Additional context**
Using in production project I'm working on seems to actually return and assign a value to the path var. I'm able to save the path to a config file that then allows the app to run after reloading with the selected path, however always causes a crash when selecting.

**Comment by national0587** [comment]
#1297 related.
I faced the same problem. I avoided the problem by reverting the version back to 5.3.1.

**Comment by sidetraxaudio** [comment]
Thanks Inoko. I'll give that a try. I might even move to file_selector 0.9.5.
[https://pub.dev/packages/file_selector](url)

**Comment by lehoangkhang4869** [comment]
Same! My app crash after get folder on windows!

**Comment by kausikMR** [comment]
file_picker: 5.3.1, this works for me, first I was using file_picker: ^5.3.2 and I checked for my windows updates and installed them,
I am using windows 11. I tried by using just file_picker: 5.3.1 not using the "^" symbol, it works without any issues for me.

**Comment by lehoangkhang4869** [comment]
file_picker: ^5.2.2, this works for me from October last year to  Jun 25, 2023. Package works well on the long time. Problem here not is new version of the package!

**Comment by h1542462994** [comment]
I hava also this problem, when i use version 5.3.2, it will crash after show file_picker in windows platform.

**Comment by hokaso** [comment]
My usage scenario is very special. The flet upgrade from 0.7.4 to 0.8.2 reconstructs a lot of authentication code. I have made my project compatible with the latest version, and it is impossible for them to go back to the old version... So I can only wait for the flet to upgrade to the new version, this is the only way.
