### ISSUE TITLE
Sometimes the cached file is not consistent with the original file

### ISSUE THREAD

**Issue by doraemonkeys** [miguelpruivo/flutter_file_picker#1324]
I encountered a rare error, I from a specific folder (/storage/emulated /0/Download/clips /) to select a specific images, as the picture is cached, md5 showed it was changed, I tried other pictures did not appear this situation, when I choose it from system photo album, file_picker works fine again.

![IMG_20230713_235108](https://github.com/miguelpruivo/flutter_file_picker/assets/87186997/3a6a2bb0-c519-4fe6-83cc-7a5ba6b13b03)

![IMG_20230713_235125](https://github.com/miguelpruivo/flutter_file_picker/assets/87186997/2371cf0b-63fb-4edc-8202-c0da24007d24)

![IMG_20230713_235138](https://github.com/miguelpruivo/flutter_file_picker/assets/87186997/e3addae0-c99b-4129-ac3a-e6bfb64415c9)

### Platform
Android 12

### Flutter Version
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/87186997/b5b33a34-4784-4196-b7f9-fcaa3cb7aed4)

Here is a link to the original image:
https://github.com/Doraemonkeys/picture/blob/master/1/202307132352269.jpg

**Comment by lucasgsa** [comment]
i have the same problem.

I believe that the correct is to use the md5 of file to determine if has the file in cache or not.

**Comment by lucasgsa** [comment]
I have the same problem.

I believe that the correct is to use the md5 of the file to determine if is the same.

**Comment by guilhermeg2k** [comment]
Same issue had to do a clean cache thing every time my form got open

**Comment by StefanDimov** [comment]
@guilhermeg2k Can you give us some code on how to clean the cache? I am thinking of just deleting the `cache/file_picker` folder before picking a file, but I was wondering if there is a better way to do this.

**Comment by guilhermeg2k** [comment]
@StefanDimov you can clean the cache by 
```
FilePicker.platform.clearTemporaryFiles();
```
be careful where you gonna put this, because all of your picked files are "temporary files", thus if you run this code, for example after picking a file, this file that you picked becames invalid. 
I personally run every time i open my form.
