### ISSUE TITLE
Crashes on Windows Desktop

### ISSUE THREAD

**Issue by bksubhuti** [miguelpruivo/flutter_file_picker#1328]
**Describe the bug**
I was getting a crash a few seconds after the function ended .  This calls some type of destructor for the object and crashes the app with no messages.

I built a counter app and pasted the code in the counter button 
```
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          String? dir = await FilePicker.platform.getDirectoryPath();
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.

```

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [x ] **Windows** Desktop

Windows 11

I sent this code to a friend and it crashed on his computer too.  
Using latest item crashes.. my friend figured it out..

The following without the carrot ^ works fine.  
`  file_picker: 5.3.1  
`

 
**Details to reproduce the issue**
It is surely a reproducible bug.  I'm quite surprised that a heavy use pkg has this strong bug.
Please put Windows into your testing routine.

**Error Log**
No errors given

**Screenshots and/or video**
window disappears.. full crash

**Flutter Version details**
```
PS C:\git\filepicker_test> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.80.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
PS C:\git\filepicker_test> dart --version
Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "windows_x64"
PS C:\git\filepicker_test>
```
**Additional context**
Yes.. the latest crashes.. the next to latest works..

**Comment by bksubhuti** [comment]
Here is a sample project if you really need one.

[filepicker_test.zip](https://github.com/miguelpruivo/flutter_file_picker/files/12079548/filepicker_test.zip)

**Comment by Michal-MK** [comment]
I had to go all the way to 5.2.0+1 for the crashes to stop.

**Comment by bksubhuti** [comment]
> I had to go all the way to 5.2.0+1 for the crashes to stop.

There is a difference between 
```
file_picker: ^5.3.1
file_picker: 5.3.1

```    

My friend gave me a little lesson on that.  Basically, that little `^ `will upgrade to a higher number even without specifying so.

**Comment by Michal-MK** [comment]
I know, but for some reason my app crashed even with `file_picker: 5.3.1`. So I bin-searched until a version was working. And the final version was `5.2.0+1`

**Comment by nitroplr** [comment]
Only happens for me when picking a directory, picking files still works fine.

**Comment by bksubhuti** [comment]
Yes.  I only tried pocking a folder for writing a file in that folder. But
"writing a file" does not need to happen.  It happens when the picker is
initiated and the function ends which destroys the object and also the
containing program with it.(destroys the app too ). The code is included .

**Comment by pamtbaau** [comment]
Seems to be a duplicate of https://github.com/miguelpruivo/flutter_file_picker/issues/1317

**Comment by bksubhuti** [comment]
got a message that i need to ask questions here.. any response.??
Also seems to be buggy with android always asking for permission and not writing to file sometimes.

**Comment by kirill-21** [comment]
> got a message that i need to ask questions here.. any response.?? Also seems to be buggy with android always asking for permission and not writing to file sometimes.

You can temporary use my fork with this issue gotten fixed: https://github.com/miguelpruivo/flutter_file_picker/pull/1340

like this:
```yaml
  file_picker:
    git:
      url: https://github.com/kirill-21/flutter_file_picker
      ref: master
```
