### ISSUE TITLE
No signature of method: build_bo83qif5zxwqa697kkuvjbxyf.android() 

### ISSUE THREAD

**Issue by adem74** [miguelpruivo/flutter_file_picker#1329]
**Describe the bug**
When i try build app, i get this error. In normally, It was working about 1-2 months ago. I was using Flutter 3.10. I upgraded latest version. It didn't work. Also I tried use file_picker with any dependency (I saw different page). I have done clean and pub get before every possible solution.

**Platform**
Android - Samsung s10+

**Platform OS version**
Android 12

![image](https://github.com/miguelpruivo/flutter_file_picker/assets/64316318/b6297ea4-06b3-4544-b872-7c1c1bd9fbd9)

**Comment by jacksonw765** [comment]
Running into this issue as well

**Comment by Cellaryllis** [comment]
Same over here

**Comment by Cellaryllis** [comment]
Updated Gradle to a newer version and this issue seems resolved.

**Comment by surajpunemaha** [comment]
Facing same here.
Tried updating to distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip 
but didn't worked.

**Comment by Cellaryllis** [comment]
I have:

In root build.gradle
`
 dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
`
gradle-wrapper.properties:
`
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
`

That seemed to do it for me. I had to try a few versions as other dependencies started failing when I updated to a version that is too new, or too low.

**Comment by yogithesymbian** [comment]
same issue , i open here
https://github.com/fluttercommunity/plus_plugins/issues/2048 this about **connectivity plus.**
when i comment on my pubscpec.yaml for the plugins

**i got similar issue for** `# file_picker: ^5.3.3`

also here
https://stackoverflow.com/questions/76296520/android-studio-gradle-error-a-problem-occurred-evaluating-project-connectivi

then i comment plugins # file_picker: ^5.3.3 , its happend again for `package_info_plus` oh mannn .... anyone know how to solve...

**Comment by yogithesymbian** [comment]
here is the code when click the error
```
group 'com.mr.flutter.plugin.filepicker'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    
    dependencies {
        implementation 'androidx.core:core:1.0.2'
        implementation 'androidx.annotation:annotation:1.0.0'
        implementation "androidx.lifecycle:lifecycle-runtime:2.1.0"
    }

    namespace 'com.mr.flutter.plugin.filepicker'
}

```

**Comment by Reza-Babakhani** [comment]
Did anyone fix the problem?
What should we do?

**Comment by Reza-Babakhani** [comment]
I changed some versions and my problem solved.

build.gradle in project level:
```
ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

```

gradle-wrapper.properties:

`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip`

**Comment by adem74** [comment]
I have solved my problem by creating new project and move files to it. That is all.
