### ISSUE TITLE
No Callback on Cancel Pick Files - Web on iOS  

### ISSUE THREAD

**Issue by test0terter0n** [miguelpruivo/flutter_file_picker#1330]
**Describe the bug**
When picking Files using web in Safari on iPhone and picking files is canceled by the user, pickFiles does not return. Only after device is locked and unlocked, pickFiles returns result. 
On Android everything seems to work fine. 

**Platform**

- [ ] Android
- [ X ] iOS
- [ X ] Web
- [ ] Desktop

**Platform OS version**
iOS 16.5.1

**How are you picking?**
```
await FilePicker.platform.pickFiles();
```

<details>
<summary>Details to reproduce the issue</summary>

```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _loading = false;
  Future<void> _import() async {
    setState(() {
      _loading = true;
    });

    FilePickerResult? result = await FilePicker.platform.pickFiles();

    setState(() {
      _loading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text(_loading ? "loading" : "not loading")),
      floatingActionButton: FloatingActionButton(
        onPressed: _import,
        tooltip: 'import',
        child: const Icon(Icons.add),
      ), 
    );
  }
}

```
</details>

<details>
<summary>Screenshots and/or video</summary>
After canceling import still stuck in state importing.
![IMG_3441](https://github.com/miguelpruivo/flutter_file_picker/assets/48948613/dd85fc2c-7515-4cea-b7f9-b6e8cdfba891)

</details>

**Flutter Version details**
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (4 days ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Comment by miguelpruivo** [comment]
It should return `null` when you cancel it.

**Comment by test0terter0n** [comment]
@miguelpruivo  In the iOS App, null is returned, using the web version in safari no value is returned at any time.

**Comment by fabianbrandscheid** [comment]
@miguelpruivo Please stop closing unsolved issues....
