### ISSUE TITLE
Access application documents directory with FilePicker

### ISSUE THREAD

**Issue by timoffenhaeusser** [miguelpruivo/flutter_file_picker#1332]
Is it possible to use FilePicker to browse through the files in the applications documents directory? I mean, the files that are located at the path you can get with ```getApplicationDocumentsDirectory()```

I can't find a way to tell the FilePicker where to browse for the files.

Thank you for your help, Tim.

**Comment by miguelpruivo** [comment]
iOS or Android? You should be able to get those with `FileType.any` anyway in those.
