### ISSUE TITLE
How to mock the plugin for UNIT testing?

### ISSUE THREAD

**Issue by aliasgar4558** [miguelpruivo/flutter_file_picker#1334]
Can someone please let know that how we can setup the mock for it to test the app's functionality.
Right now, facing issue like picker dialog shown in test env as well, so couldn't perform actual test scenarios..

Your help would be really appreciated.

**Comment by miguelpruivo** [comment]
You should look into [how to mock Flutter plugins](https://docs.flutter.dev/testing/plugins-in-tests). Unit testing on plugins, should be done by "mocking" the plugin's response (in this case, the returned file).

**Comment by aliasgar4558** [comment]
Okay @miguelpruivo , Thanks for your prompt reply.
