### ISSUE TITLE
FileType.custom and FileType.custom doesn't work on Android 14

### ISSUE THREAD

**Issue by muttsu-623** [miguelpruivo/flutter_file_picker#1335]
**Describe the bug**

On Android 14, I tried to pick files using `type: FileType.custom` and `type: FileType.any` but it didn't work well.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**How are you picking?**
```
final result = await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: [
    'jpg',
    'jpeg',
    'png',
    'pdf',
    'txt',
    'doc',
    'docx',
    'xml',
    'xls',
    'xlsx',
    'ppt',
    'pptx',
  ],
  withData: true,
);
```

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

```
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-x64, locale ja-JP)
    • Flutter version 3.10.5 on channel stable at /Users/user/fvm/versions/3.10.5
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/user/fvm/versions/3.10.5. Consider adding /Users/user/fvm/versions/3.10.5/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.
```

**How to solve this issue**

I downloaded this package on my Project, and changed `FilePickerDelegate.javaL236`.

From: `intent = new Intent(Intent.ACTION_GET_CONTENT);`
To: `intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);`

Would you mind if I create a PR for this issue ?

**Comment by imshobhitbajpai** [comment]
I'm on Android verison 13 and Samsung One UI version 5.1. I'm able to pick .mp4 files on web app but unable to pick .png or .jpg files.

**Comment by miguelpruivo** [comment]
It's important to understand why it didn't work with GET_CONTENT. This change could break for multiple users.

**Comment by muttsu-623** [comment]
> This change could break for multiple users.

I didn't know that. Thank you for telling me.

> why it didn't work with GET_CONTENT.

I'll search the reason.

**Comment by EvertonMJunior** [comment]
> It's important to understand why it didn't work with GET_CONTENT. This change could break for multiple users.

It is breaking file picking when using custom file type on Android 13 as well.

**Comment by muttsu-623** [comment]
@EvertonMJunior 
How about "ACTION_OPEN_DOCUMENT" ?
Did it work well ?

I searched the reason but I could't find anything 😮‍💨

**Comment by muttsu-623** [comment]
@nibo 
No. There's no update.

@miguelpruivo 
Do you know how to find the reason why we occur the error on Android 13 and 14?

**Comment by julian-CStack** [comment]
I get this on Android 13. Not sure why it doesn't work but `FilePicker.platform.pickFiles` return null. 

Using @muttsu-623 's fork with 'ACTION_OPEN_DOCUMENT' does in fact return the expected file.

**Comment by muttsu-623** [comment]
@miguelpruivo
Some people tried my code and they succeeded in fixing the bug.

What should I do?

**Comment by KestasVenslauskas** [comment]
We have the same issue on android 13+ versions.
The result from `FilePicker.platform.pickFiles` is always null.
@muttsu-623 fork fixes the issue.

I wonder why is this not merged yet since this library is unusable with android 13+ versions.

**Comment by JeffTyfoom** [comment]
Up!!!

**Comment by melWiss** [comment]
ping on this!

**Comment by melWiss** [comment]
> @miguelpruivo Some people tried my code and they succeeded in fixing the bug.
> 
> What should I do?

there's a weird behavior now, when the type is image the result is null, has anyone faced that issue?

**Comment by muttsu-623** [comment]
@melWiss 
You mean that when you use my fork, there's the problem, right?

**Comment by melWiss** [comment]
Yes, the problem of type = custom is fixed but now when the type = image it's surprisingly doesn't work which is weird.

Tested on Android 11 & Android 13 devices.

**Comment by muttsu-623** [comment]
@melWiss 
As you know, I changed like that.
https://github.com/miguelpruivo/flutter_file_picker/pull/1336/files

You mentioned the `type: image/*` problem. Is it a different problem?

**Comment by melWiss** [comment]
i think it's related since it was working fine before the fix

**Comment by KestasVenslauskas** [comment]
We do not observe any issues with images

**Comment by melWiss** [comment]
The bug is spotted on samsung android 11 and android 13 devices just after this fix

**Comment by melWiss** [comment]
my very very sincere aplogies i was mistaken 🫠, it's another issue totally

**Comment by BitBlueDevStudio** [comment]
@nibo what kind of error do you see in native android logs when this issue occurs? Is it "User cancelled the picker request"?


I can't reproduce this issue, but I'm working on my fix

**Comment by shaoguanlee** [comment]
in my sense, i can't pick zip files while use "file_picker: ^10.1.2" with FileType.custom on android9 after upgrade from "^8.0.7".
on the window of file chooser,there only show picture,document,audio etc ,can't see other folder even toggle "show hidden files" on.


```
await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: ["zip"],
);
```
