### ISSUE TITLE
Android 12+ Help with getDirectoryPath()

### ISSUE THREAD

**Issue by portal305** [miguelpruivo/flutter_file_picker#1337]
**Describe the bug**
Hi I've had many problems with Android 12+. I'm developing a Front-End Emulator in flutter. The problem is in getDirectoryPath(). When I use it, the output show only the path because it's a String format. Is there a way to list all files inside the choosen folder? I've used the Permissions "READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE". Is it necessary the permission "MANAGE_EXTERNAL_STORAGE" ? When I use this permission my app gets rejected on playstore. What can I do?
 
**Platform**

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 12+

**Comment by astubenbord** [comment]
You could try the following: 

```dart
Future<List<File>> listFilesFromSelectedDirectory() async {
  final dirPath = await FilePicker.platform.getDirectoryPath(...);
  if (dirPath == null) {
    return [];
  }
  final directory = Directory(dirPath);
  return directory.list().whereType<File>();
}
```

This should return all files from the selected directory. However, I've found that on Android 12+, you cannot select all directories.

**Comment by rohintoncollins** [comment]
@astubenbord This does not work on Android 12+. You can get the folder path, but when you call list() or listAsync() you may get nothing, or only media files. Not great if you are trying to access/import all files in the folder like I am.

**Comment by rohinton-collins** [comment]
@portal305 Did you find a solution to this problem?
