### ISSUE TITLE
Enhancement: Add Camera Integration for Capturing Images

### ISSUE THREAD

**Issue by MuhammadUmair786** [miguelpruivo/flutter_file_picker#1339]
Currently, the File Picker plugin (file_picker) for Flutter provides functionality to select images from the file system and gallery. However, it lacks direct camera integration for capturing images within the plugin itself. This enhancement suggestion aims to improve the user experience by adding camera integration to the File Picker plugin, allowing users to capture images directly from their device's camera.

**Comment by miguelpruivo** [comment]
Hi thank you for the suggestion, but can you imagine people that only wanted to just pick files in their apps, having to ship the app with camera plugin dependencies (along with camera entitlements for the stores) when, in fact, their app won't use those features? 🙂 

The first versions of the plugin had the camera plugin built-in, but (with reason) some devs complaint that it would force they to add the camera entitlements when they app would not need it, also, making their app bigger. You can easily combine multiple plugins with Flutter, so this is a no-op.
