### ISSUE TITLE
Crash App after picker Directory

### ISSUE THREAD

**Issue by misagaming1437** [miguelpruivo/flutter_file_picker#1353]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [x] Desktop

**Platform OS version**
Windows 10

**How are you picking?**
```
Future<String?> pickerDirectory() async {
  return await FilePicker.platform
      .getDirectoryPath(dialogTitle: 'Select Folder store backup:');
}
```

**Details to reproduce the issue**

When click button to select folder in Windows, after finish , app random crash

**Error Log**

**Screenshots and/or video**

**Flutter Version details**

3.10.5.

**Additional context**

**Comment by sbrighth** [comment]
same problem happens to me.
even click cancel button, it is randomly crash.

**Comment by AppetiteTeam** [comment]
same

**Comment by berrygoudswaard** [comment]
Same issue...

Downgrading to file_picker 5.3.1 seems to fix the issue for me

**Comment by AppetiteTeam** [comment]
> Same issue...
> 
> Downgrading to file_picker 5.3.1 seems to fix the issue for me

It didn't help me. I think the problem is that I have a new version of Flutter.

Flutter SDK - 3.13.0
Dart SDK - 3.1.0 (Flutter)

**Comment by misagaming1437** [comment]
> 
It didn't help me

**Comment by misagaming1437** [comment]
> Downgrading to file_picker 5.3.1 seems to fix the issue for me
It didn't help me

**Comment by davidadzgi** [comment]
Same problem with Windows 11, i think it's because flutter version, i have 3.10.6

**Comment by sbrighth** [comment]
I think I found the problem.
There are problematic lines in getDirectoryPath() in file_picker_windows.dart.
I comment below lines,

line 134
`
// fileDialog.release();
`

line 154~157
`    // hr = item.release();
    // if (!SUCCEEDED(hr)) throw WindowsException(hr);

    // hr = fileDialog.release();
`

save and start from the begining(not hot reroad),
the getDirectoryPath worked without error.

**Comment by berrygoudswaard** [comment]
Downgrading to file_picker 5.3.1 in combinatie with Flutter 3.13.0 was working for me. However a colleague adviced me to use the https://pub.dev/packages/file_selector package which is developed by the Flutter team. 

Since there are multiple MR's pending for this issue, I decided to switch toe file_selector: 
https://github.com/miguelpruivo/flutter_file_picker/pull/1340
https://github.com/miguelpruivo/flutter_file_picker/pull/1356
