### ISSUE TITLE
[iOS, Android] Selecting multiple images result in duplicate Path-s

### ISSUE THREAD

**Issue by fico45** [miguelpruivo/flutter_file_picker#1359]
**Describe the bug**
After selecting multiple images with FilePicker, of FileType.image, the result contains multiple Path-s which are resulting in duplicate images being returned. The number of images returned is always exact to the number of images selected. In this case, some selected images are overridden with others (I was not able to notice any pattern of this behavior, but it's somewhat random).
I used Set as it naturally discards duplicate values, and then print that path in the console. I also print both List and Set lenght in the console. I would except these 2 values to be the same, but Set is almoust two times as lower. No selected images are indeed duplicates, every selected image is unique.

**Platform**

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
5.2.5, 5.3.4

**How are you picking?**
```
Future<List<File>?> pickImages() async {
  FilePickerResult? result = await FilePicker.platform.pickFiles(
    allowMultiple: true,
    type: FileType.image,
  );
  if (result != null) {
    final Set testSet = {};

    List<File> files = result.paths.map((path) {
      if (!testSet.add(path)) {
        print(path);
      }

      return File(path!);
    }).toList();

    print('Picked length: ${files.length}');
    print('Set length: ${testSet.length}');

    return files;
  } else {
    return null;
  }
}
```

**Details to reproduce the issue**
Try selecting the images with above function, Set and List length will differ.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
3.0.2

**Additional context**

**Comment by rigodamir** [comment]
I have the same problem
