### ISSUE TITLE
Unable to get path of a file that is quickly picked after downloading

### ISSUE THREAD

**Issue by mp-truenary** [miguelpruivo/flutter_file_picker#1363]
**Describe the bug**
Any file that is quickly picked after we download it returns FileNotFoundException. It will return the same error no matter how many times we try to pick it. However, if we try to pick other file that is downloaded giving some time, it won't throw any error.

**Platform**
iOS

**Details to reproduce the issue**
1.  Download file
2. Quickly pick up the file
3. Throws exception
4. Pick up the same file after some time, it will throw the error.

**Error Log**
```
flutter: /Users/manishpoudel/Library/Developer/CoreSimulator/Devices/73DB8BFB-4CE4-4509-854C-61F7AB7DFF3B/data/Containers/Data/Application/8EB16511-3DB3-4AB6-8B69-525C10661D09/tmp/com.svenglobal.sven-Inbox/10MB-TESTFILE.ORG.pdf

flutter: FileSystemException: Cannot retrieve length of file, path = '/Users/manishpoudel/Library/Developer/CoreSimulator/Devices/73DB8BFB-4CE4-4509-854C-61F7AB7DFF3B/data/Containers/Data/Application/8EB16511-3DB3-4AB6-8B69-525C10661D09/tmp/com.svenglobal.sven-Inbox/10MB-TESTFILE.ORG.pdf' (OS Error: No such file or directory, errno = 2)
flutter:
#0      _File.length.<anonymous closure> (dart:io/file_impl.dart:366:9)
<asynchronous suspension>
#1      multipartFileFromPath
multipart_file_io.dart:17<asynchronous suspension>
#2      FileManager.uploadFile
file_manager.dart:54<asynchronous suspension>
#3      _CertificationsBottomSheetState._onSubmitForm
certifications_bottom_sheet.dart:184<asynchronous suspension>
flutter: ----------------------------------------------------
```

**Additional context**
This issue was investigated after we got this FileNotFoundException which was reported on Firebase Crashlytics. So, I tried to reproduce it which let me discover this steps.

**Comment by Liloupar** [comment]
same issue here

**Comment by mp-truenary** [comment]
@Liloupar  Did you find any solution?

**Comment by Liloupar** [comment]
> @Liloupar Did you find any solution?
No, I didn't find any solution.
