### ISSUE TITLE
File path not exists and size = 0 when first time pick file in IOS

### ISSUE THREAD

**Issue by trunghaudinh** [miguelpruivo/flutter_file_picker#1366]
When I first granted permission and selected the file, the size of the file = 0. And when I checked its existence using File(file.path!).exists(), it returned false. But from the second time onwards, the size had a value, and the file existed.

Code: 

FilePickerResult? result = await FilePicker.platform
                          .pickFiles(
                              allowMultiple: false,
                          type: FileType.audio);

                      if (result != null) {
                        var file = result.files.first;
                        var exists = await File(file.path!).exists();
                        print("file choose path = ${file.toString()} || ${File(file.path!).existsSync()}  || $exists}");
                     }

Log first time : 

[Default] <ICMonitoredAccountStore: 0x28057f2a0> Failed to register for account monitoring. err=Error Domain=com.apple.accounts Code=7 "(null)"
[core] Attempted to register account monitor for types client is not authorized to access: {(
    "com.apple.account.iTunesStore"
)}
[Default] <ICMonitoredAccountStore: 0x28057f2a0> Failed to register for account monitoring. err=Error Domain=com.apple.accounts Code=7 "(null)"

flutter: file choose path = PlatformFile(path /private/var/mobile/Containers/Data/Application/EF19AE12-3F2A-43BB-89C8-6390D042893F/tmp/Phải Chăng Em Đã Yêu?.m4a, name: Phải Chăng Em Đã Yêu?.m4a, bytes: null, readStream: null, size: 0) || false  || false}

Log second time:

***** Exporting assets, this operation may take a while if remote (iCloud) assets are being cached.
* -[FilePickerPlugin resolvePickAudioWithMultiPick:]_block_invoke [Line 338]

flutter: file choose path = PlatformFile(path /private/var/mobile/Containers/Data/Application/EF19AE12-3F2A-43BB-89C8-6390D042893F/tmp/Phải Chăng Em Đã Yêu?.m4a, name: Phải Chăng Em Đã Yêu?.m4a, bytes: null, readStream: null, size: 5915768) || true  || true}

**Platform**

- [x] iOS

**Platform OS version**
16.6

**How are you picking?**
just pick audio file Flutter.

**Error Log**
don't show any exception

**Flutter Version details**

Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale
    en-VN)
    • Flutter version 3.13.0 on channel stable at /Volumes/Work/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

Thanks

**Comment by trunghaudinh** [comment]
`FilePickerResult? result = await FilePicker.platform
                          .pickFiles(
                              allowMultiple: false,
                          type: FileType.audio);


                      if (result != null) {
                        var file = result.files.first;
                        var exists = await File(file.path!).exists();

                        print("file choose path = ${file.toString()} || ${File(file.path!).existsSync()}  || $exists}");
`

**Comment by trunghaudinh** [comment]
`FilePickerResult? result = await FilePicker.platform
                          .pickFiles(
                              allowMultiple: false,
                          type: FileType.audio);
if (result != null) {
   var file = result.files.first;
    var exists = await File(file.path!).exists();

     print("file choose path = ${file.toString()} || ${File(file.path!).existsSync()}  || $exists}");
`

**Comment by Liloupar** [comment]
same issue
