### ISSUE TITLE
[FilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, null)

### ISSUE THREAD

**Issue by lifenautjoe** [miguelpruivo/flutter_file_picker#137]
On iOS, when calling

```
File pickedVideo =
          await ImagePicker.pickVideo(source: ImageSource.camera);
```

And picking [this file](https://srv-file7.gofile.io/download/Cjc1Vn/ag5veE6_460svh265.MP4) from my gallery, the library crashes with

```
flutter: [FilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, null)
flutter: Caught error: PlatformException(file_picker_error, Temporary file could not be created, null)
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      FilePicker._getPath (package:file_picker/file_picker.dart:65:39)
<asynchronous suspension>
#3      FilePicker.getFile (package:file_picker/file_picker.dart:46:15)
<asynchronous suspension>
#4      OBVideoPickerBottomSheet.build.<anonymous closure> (package:Okuna/pages/home/bottom_sheets/video_picker.dart:28:40)
<asynchronous suspension>
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#16     _rootRunUnary (dart:async/zone.dart:1136:13)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _invoke1 (dart:ui/hooks.dart:250:10)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
```

Strangely, when picking different files, it works... So might only be related to this one, in which case I would expect a different file specific error.

**Comment by miguelpruivo** [comment]
Hi @lifenautjoe , you are opening a issue in `file_picker` but proving `image_picker` code (which is a different plugin).

However, your stacktrace actually has a `file_picker`. I can't even open the file with the link you've provided. Nevertheless, if that happens only with that file, that might be due some file restriction (DRM protected, corrupted, etc.) and that's why a generic error is thrown when no further info is given from the underlying platform.

**Comment by miguelpruivo** [comment]
Closing as more details are required in order to further investigate this. Feel free to reopen if you still have an issue.

Thank you.

**Comment by Rohit19060** [comment]
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null),

Getting this same error in iOS for file picker

**Comment by coccyx-cyst** [comment]
[MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, null, null)

Getting this error on iOS 13.5

**Comment by nvtanhh** [comment]
Any update on this issue?
I still got this error on iOS 15.2

**Comment by muhammadkarbalaee** [comment]
> I still get this in iOS 15.5

So do I
