### ISSUE TITLE
bytes method returning null

### ISSUE THREAD

**Issue by Swastik-Neodocs** [miguelpruivo/flutter_file_picker#1373]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
after selecting the file, when i try to get bytes of that file using file.bytes it gives null and file is not empty it contains my file.

**Platform**

- [ *] Android
- [ *] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Sdk 33
IOS 17

**How are you picking?**
```
FilePickerResult? result =
                            await FilePicker.platform.pickFiles(
                          type: FileType.custom,
                          allowedExtensions: ['pdf'],
                        );
                        if (result != null) {
                          file = result.files.first;
                          _fileName = file.name;
                        Uint8List bytes = file.bytes!;
                          log(file.name);
                          isEmpty = false;
                          isCurrentUser = false;
                          setState(() {});
                        } else {
                          log("user cancelled the picker");
                        }
```

**Details to reproduce the issue**
select any pdf file as i wanted to pick a pdf file from local storage, after seleting try getting its bytes.

**Error Log**
Null is not a subtype of String

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/swastik/Desktop/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/swastik/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Additional context**

**Comment by DvKyuth** [comment]
You have to specify "withData" to true if you want byte data to be returned with FilePickerResult. You may find the code snip below.

`FilePickerResult? result =
                            await FilePicker.platform.pickFiles(
                          type: FileType.custom,
                          allowedExtensions: ['pdf'],
                          withData: true,
                        );`

**Comment by PureTryOut** [comment]
> You have to specify "withData" to true if you want byte data to be returned with FilePickerResult.

This confused me as this is not necessary on web. Behaviour changes depending on the platform it seems. I guess web can not read a file without reading the contents vs desktop/mobile, but maybe to be consistent if `withData == false` it should actively throw away the read bytes?
