### ISSUE TITLE
user can pick sounds file when I allow only images

### ISSUE THREAD

**Issue by heshesh2010** [miguelpruivo/flutter_file_picker#1376]
Hi , I'm using latest v file_picker: ^5.5.0 ,
`  FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'pdf', 'jpeg', 'png'],
    );`

but as video shows user can select audio files 

https://drive.google.com/file/d/1bLM1jhdw6wv-iyzUcd1dxdvKasbzkaXI/view?usp=sharing

**Comment by JeffTyfoom** [comment]
This issue is related to #1335
