### ISSUE TITLE
Android: image picker and file picker apps with launchMode=singleInstance doesn't work (more specifically Samsung devices)

### ISSUE THREAD

**Issue by melWiss** [miguelpruivo/flutter_file_picker#1379]
**Describe the bug**
the plugin was working just great but when we needed to make our app's launchMode=singleInstance, the picker doesn't work

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 11 and Android 13

**Details to reproduce the issue**
create android app with launchMode=singleInstance and try to pick an image or custom file and it will always return null

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Flutter 3.10.6

**Additional context**
None

**Comment by rameshniyo** [comment]
I am also facing this in the samung and other devices

**Comment by rameshniyo** [comment]
Please  include this in the latest version.Lots of users facing this issue

**Comment by TheManuz** [comment]
I'm facing the same issue, I've had to change my `android:launchMode` to `singleTask` instead of `singleInstance` as a workaround.

**Comment by melWiss** [comment]
but in some cases you need your app to be singleInstance, that's why i filed the bug.
I'll update the PR containing the fix.

**Comment by TheManuz** [comment]
> but in some cases you need your app to be singleInstance, that's why i filed the bug. I'll update the PR containing the fix.

Yes, that's my case, I've preferred to change the launchMode just to have a working filepicker.

I was just sharing my workaround, but that's exactly that: a workaround.

**Comment by petrnymsa** [comment]
Issue is not solved. Still occurss on Samsung devices, Android 14. 

In our app we need launchMode: sigleInstance.

**Comment by TheManuz** [comment]
I still have this issue too

**Comment by rivella50** [comment]
Same here, and the corresponding PR has just been closed 3 days ago...
