### ISSUE TITLE
[Question] - Can I use it to select file destination folder

### ISSUE THREAD

**Issue by angel1st** [miguelpruivo/flutter_file_picker#138]
Hi there,
I have an app and it has to support file import / export (text file as backup data option). For export mode, the app has to be able to select destination e.g. device folder where the text file will be exported. Can I achieve this by using the plugin and if yes, would you be so kind to provide a code snippet regarding the implementation?

**Comment by angel1st** [comment]
@miguelpruivo - actually, what I need is basically a [folder picker](https://pub.dev/packages/folder_picker), however the above mentioned one suffers from many issues. Anyway - I found my way out, thanks for the replay anyway!

**Comment by miguelpruivo** [comment]
I’m glad that you’ve found a solution @angel1st. 

No problem, feel free to reach me anytime you want.
