### ISSUE TITLE
can't reach photo gallery when using custom file type

### ISSUE THREAD

**Issue by heshesh2010** [miguelpruivo/flutter_file_picker#1385]
Hi , when using 
`  allowedExtensions: ['jpg', 'pdf', 'jpeg', 'png'],
        fileType: FileType.custom);
` 

I can't see there is any option on iOS to select photos from gallery , only showing google drive or local folders

**Comment by philitell** [comment]
I can confirm that - i would like to allow users to pick pdf's or images. But no images can be selected from the file-dialog.
```
 allowedExtensions: ['jpg', 'pdf', 'jpeg', 'png', 'heic', 'heif'], fileType: FileType.custom);
```

**Comment by amkfat** [comment]
same for me

**Comment by nguyenkhaimegatron** [comment]
same issue

**Comment by mehrzut** [comment]
same issue

**Comment by ahmadkhedr** [comment]
same issue

**Comment by nitinrgadhiya** [comment]
Facing same issue, will you please fix it. 
this issue specific for iOS

**Comment by FDuhen** [comment]
same issue
