### ISSUE TITLE
Android 11 File picker permission issue

### ISSUE THREAD

**Issue by Emranul-Islam** [miguelpruivo/flutter_file_picker#1386]
On android 11 (api lavel 30) file picker not pick file it says:

I/flutter ( 4125): [MethodChannelFilePicker] Platform exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
E/flutter ( 4125): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
E/flutter ( 4125): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 4125): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 4125): <asynchronous suspension>
E/flutter ( 4125): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:496:35)
E/flutter ( 4125): <asynchronous suspension>
E/flutter ( 4125): #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:91:33)
E/flutter ( 4125): <asynchronous suspension>
E/flutter ( 4125): #4      UploadController.pickFile (package:weshare/screens/upload/upload_controller.dart:111:9)
E/flutter ( 4125): <asynchronous suspension>

Note: All other Android version is working fine without this one.

**Comment by agamjotsingh-savii** [comment]
Having the exact same issue. It is not mentioned in the documentation that `read_external_storage` is required. As this should open default file picker, permission should not be needed.

**Comment by dipu0** [comment]
facing same issues in 2024 :-1:

**Comment by rohansohonee1** [comment]
Tested on Android 11(R) API 30
Facing the same issue
```console
I/flutter (10400): [MethodChannelFilePicker] Platform exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
I/flutter (10400): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (10400): The following exception was thrown Asynchronous error:
I/flutter (10400): PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
I/flutter (10400): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter (10400): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (10400): <asynchronous suspension>
I/flutter (10400): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:520:35)
I/flutter (10400): <asynchronous suspension>
I/flutter (10400): #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:99:33)
I/flutter (10400): <asynchronous suspension>
I/flutter (10400): ----------------------------------------------------
```

**Comment by rohansohonee1** [comment]
For me the issue was because I used camera plugin. See https://github.com/flutter/flutter/issues/156198

**Comment by navaronbracke** [comment]
@rohansohonee1 That seems like a bug in your code? You should check if you have permission _before_ calling the pickFile method. That the plugin throws an error because you do not have said permission, is correct.
