### ISSUE TITLE
Unhandled Exception: PlatformException(file_picker_error, Temporary file could not be created,

### ISSUE THREAD

**Issue by heshesh2010** [miguelpruivo/flutter_file_picker#1393]
Hi , on IOS 17 latest version when pick Live Photo from photo gallery with real Iphone I get this error :

flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x281709da0 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x28175ad00 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 32600 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 32600 on anonymousListener or serviceListener}}}}}, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x281709da0 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x28175ad00 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 32600 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 32600 on anonymousListener or serviceListener}}}}}, null)
#0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
#1      MethodChannel._invokeMethod
platform_channel.dart:310
<asynchronous suspension>
#2      MethodChannel.invokeListMethod
platform_channel.dart:496
<asynchronous suspension>
#3      FilePickerIO._getPath

**Comment by alexandra-flaminjoy** [comment]
Hi, I am having the same issue. Any updates on this?

**Comment by aakarapetyan** [comment]
Also have the same issue. Can somebody help?

**Comment by devibrahimkarahan** [comment]
Its happening for **live** photos

**Comment by nicklbaert** [comment]
Same here

**Comment by rhavuka148** [comment]
**Also have the same issue**. Can somebody help?

**Comment by MengLizhi** [comment]
Also have the same issue. Can somebody help?

**Comment by devibrahimkarahan** [comment]
> Also have the same issue. Can somebody help?

This PR is solving the issue, https://github.com/miguelpruivo/flutter_file_picker/pull/1369
