### ISSUE TITLE
Add `maxSdkVersion`

### ISSUE THREAD

**Issue by rohansohonee1** [miguelpruivo/flutter_file_picker#1398]
Since `READ_EXTERNAL_STORAGE` is being used till API 32, we can add the `maxSdkVersion` in the `<uses-permission>`.
See https://developer.android.com/guide/topics/manifest/uses-permission-element

We can add like this:
```
AndroidManifest.xml

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
```

**Comment by navaronbracke** [comment]
Feel free to open a PR to fix this. I'll do a review when I have some time.
