### ISSUE TITLE
hover run err

### ISSUE THREAD

**Issue by YourksChan** [miguelpruivo/flutter_file_picker#140]
go: github.com/miguelpruivo/plugins_flutter_file_picker/go@v0.0.0-20190903230439-02b11efd14f4 requires
        github.com/go-flutter-desktop/go-flutter@v0.27.0 requires
        github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1: invalid pseudo-version: does not match version-control timestamp (2019-04-09T00:40:39Z)
Go build failed: exit status 1

**Comment by miguelpruivo** [comment]
@GeertJohan do you know what it might be? Thank you.

**Comment by GeertJohan** [comment]
I think the go.mod file needs to be updated to be compatible woth go1.13

**Comment by miguelpruivo** [comment]
@GeertJohan simple updating it to `go1.13` should be enough then?

**Comment by GeertJohan** [comment]
I totally misread the initial error. It points to an error in the go.mod file that was present in go-flutter. Please update the go-flutter dependency to v0.30.0 to fix it.

**Comment by miguelpruivo** [comment]
Merged into `beta`. Thank you @GeertJohan. You can give it a try @YourksChan and let me know if it is working for you. 🙂

**Comment by Drakirus** [comment]
#144 works for me!

**Comment by YourksChan** [comment]
> Merged into `beta`. Thank you @GeertJohan. You can give it a try @YourksChan and let me know if it is working for you. 🙂

Thank you for your help, I used your solution, or not, I now downgrade golang to 1.12, he successfully operated!

**Comment by Murtuzakabul** [comment]
I am still getting this error 

go: finding github.com/miguelpruivo/plugins_flutter_file_picker/go latest
verifying github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/go.mod: github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/go.mod: reading https://sum.golang.org/lookup/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1: 410 Gone
hover: Go build failed: exit status 1

It used to work well in my project with go v1.12 and File_picker v1.4.0. I updated the go version to 1.13 and also the latest of file_picker and I started getting this error.

**Comment by pchampio** [comment]
The beta branch must be merged to master! 
(hover doesn't support the git directive in pubspec.yaml)

**Comment by miguelpruivo** [comment]
@pchampio I'll merge it this weekend and deploy on pub.dev! Have been quite busy lately. Thank you!

**Comment by miguelpruivo** [comment]
Hi again, it's now on `master` and [pub.dev](https://pub.dev/packages/file_picker#-changelog-tab-).

Thank you all.

**Comment by Murtuzakabul** [comment]
Great, let me check it out. Thanks a lot.
