### ISSUE TITLE
I think that not work in web

### ISSUE THREAD

**Issue by yanghyeongjunn** [miguelpruivo/flutter_file_picker#1410]
Unsupported Operation platform operationsystem

Did I just make a mistake?

**Comment by thisisdingo** [comment]
for me worked in local env. in release mode i catch exception Platform._operatingSystem

**Comment by Just4Ease** [comment]
> for me worked in local env. in release mode i catch exception Platform._operatingSystem

I experience the same too.

**Comment by 53huzefa-zeenwala** [comment]
I have same issue. I resolve it by using flutter clean command and rerun my application.
