### ISSUE TITLE
BUG: Picking a folder in iOS causes the original folder to be deleted.

### ISSUE THREAD

**Issue by twinkles-twinstar** [miguelpruivo/flutter_file_picker#1412]
**Describe the bug**
This is a serious bug where users' files are deleted without them noticing. If use file_picker version 5.3.3 or higher, when an ios user picks a directory, the original directory will be deleted (actually, moved to the app's sandbox tmp directory, and the user cannot access them), and file_picker returns a path in tmp directory.
In 5.3.2 and earlier versions, file_picker will return the real absolute path of the original directory.
This BUG looks to be caused by this pull: https://github.com/miguelpruivo/flutter_file_picker/pull/1311 (I'm not an ios programmer so I don't know how to fix this bug...), which moves the file or directory pointed to by the original url into the tmp directory; please restore the previous behavior (5.3.2, getting the original absolute path, which is the best, I think ?), or copy the directory to tmp (rather than moving it).

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
iOS 16.5

**How are you picking?**
```dart
if (Platform.isIOS) {
  var selection = await FilePicker.platform.getDirectoryPath();
  result = selection;
}
```

**Details to reproduce the issue**
1. open a directory picker.
2. select a directory.
3. the selected directory was deleted (moved to the `<application-sandbox-directory>/tmp` directory).
4. file_picker returnd the tmp path.

**Error Log**
None.

**Screenshots and/or video**
None.

**Flutter Version details**
Flutter 3.16, no probrlm.

**Additional context**
None.

**Comment by bypass112** [comment]
Can conform, I tried to select "AAA" folder and my app crashed with the following error:
`“Aaa” couldn’t be moved because you don’t have permission to access “tmp”.`
After downgrading to 5.3.2 it works again.

**Comment by mateusz-bak** [comment]
Observed the same issue on 6.1.1

**Comment by mateusz-bak** [comment]
Please reopen

**Comment by twinkles-twinstar** [comment]
I created a fork to fix this issue: [twinkles-twinstar/flutter_file_picker](https://github.com/twinkles-twinstar/flutter_file_picker/commit/61dc2af422d99348b26621b16e57142a55932bf9) .
When the user selects a directory, the picker will return its absolute path (/private/var/....) and will not delete the original directory.
BTW, it seems that it is possible to return the absolute path (/private/var/....) when selecting a file. I don't know if this path can be accessed in swift/objc/dart (I am not an ios developer and don't know much about the filesystem policy for ios), but I was able to operate it using c++ filesystem/fopen, if you need absolute paths, you can imitate my [CustomMethodChannel](https://github.com/twinkles-twinstar/TwinStar.ToolKit/blob/master/ShellGUI/ios/Runner/CustomMethodChannel.swift).

**Comment by Louis-He** [comment]
I think we should reopen this issue since the package is mostly unusable if someone needs to use this plugin to select a folder.

**Comment by wonli** [comment]
Are there other alternative packages available?
