### ISSUE TITLE
[Windows] The picker is pausing the ripple effect on buttons

### ISSUE THREAD

**Issue by gabrielnemeth** [miguelpruivo/flutter_file_picker#1416]
**Describe the bug**
When the picker opens the ripple in a button freezes.

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [x] Desktop

**Platform OS version**
Windows 11

**How are you picking?**
```
    ElevatedButton(
        onPressed: () async {
            String? selectedDirectory =
                await FilePicker.platform.getDirectoryPath();

            if (selectedDirectory != null) {
                sharedPreferencesProvider.setVaultPath(selectedDirectory);
            }
        },
        child: const Text('Select vault'),
    ),

```

**Screenshots and/or video**
This video is not mine, but you can see the exact same issue:
https://youtu.be/CMYErzgDNAE?si=SPURjHgdBPb4slYn&t=196

![image](https://github.com/miguelpruivo/flutter_file_picker/assets/11211316/a8ed9635-403f-4d0a-ac66-d13678f09d76)
The ripple stays in this paused state until the dialogue gets closed.

**Flutter Version details**
Flutter (Channel stable, 3.16.2)

**Comment by coldshineb** [comment]
I also encounter this problem, all file dialogs works fine except getDirectoryPath, seems it freezes the application.
This also affects some my setState code in a loop.
