### ISSUE TITLE
iOS privacy manifest required

### ISSUE THREAD

**Issue by stuartmorgan** [miguelpruivo/flutter_file_picker#1418]
This plugin is listed on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest. Some action will be required, either to clarify with Apple whether this plugin should be on the list, or to add a privacy manifest.

See https://github.com/flutter/flutter/issues/131940 for context.

**Comment by navaronbracke** [comment]
I'll have a look into adding the privacy manifest.

**Comment by navaronbracke** [comment]
Per a recent email from App Store Connect, apps should be built with the iOS 17 SDK / XCode 15, starting from April 24th 2024, so I think that is our deadline. cc @miguelpruivo

**Comment by miguelpruivo** [comment]
@navaronbracke thank you for following this. From what I understood, after April 24h _all apps_ must be supporting iOS 17 is that it? How is that relevant for the plugin implementation itself? I may be missing some point.

Had a glance into @stuartmorgan's links but really couldn't understand (easily) what action should be made to the plugin itself.

Thanks!

**Comment by navaronbracke** [comment]
I think `file_picker` could provide an empty Privacy Manifest. The package does not track user data, so that section can be left empty. For the used APIs, we should probably see which ones we use. If one of Apple's API usage identifiers can be used to describe the use for this package, we should fill that in for the specified section.

See https://github.com/flutter/packages/pull/5846 for an example.

**Comment by stuartmorgan** [comment]
> Per a recent email from App Store Connect, apps should be built with the iOS 17 SDK / XCode 15, starting from April 24th 2024, so I think that is our deadline.

That is unrelated, the deadlines for this were recently announced [here](https://developer.apple.com/news/?id=3d8a9yyh)
- Warning emails starting March 13th (so about a week from now).
- Enforcement starting May 1st.

> Had a glance into @stuartmorgan's links but really couldn't understand (easily) what action should be made to the plugin itself.

You need to add a privacy manifest describing Required Reason API usage (if any) and private data collection (if any), and reference it in the podspec so that it becomes part of the build. Without that, anyone using this plugin with `use_frameworks` will not be able to publish to the app store.

**Comment by stuartmorgan** [comment]
> I think `file_picker` could provide an empty Privacy Manifest. [...] For the used APIs, we should probably see which ones we use.

I would strongly recommend you read Apple's documentation carefully before proceeding further; I have not seen anything that describes accurate compliance with Required Reason API requirements as optional.

**Comment by miguelpruivo** [comment]
Added in version 8.0.0. Thank you for reporting.
