### ISSUE TITLE
path null

### ISSUE THREAD

**Issue by Gagandeep1408** [miguelpruivo/flutter_file_picker#1420]
Not working in android version 14 for release mode

**Comment by MohsinP07** [comment]
Hey @Gagandeep1408, Are you getting the permission error as well? I am getting same for Android 13.

**Comment by Gagandeep1408** [comment]
not permission error if you are getting permission error then add below permissions

for below 13

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    
    for 13 and above
     <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
    
    
    
    also make sure activity launch mode is singleTop.
    
                android:launchMode="singleTop"

**Comment by MohsinP07** [comment]
@Gagandeep1408 what if I want to pick excel file, is there ang specific permission for that as well?

**Comment by Gagandeep1408** [comment]
FilePickerResult? result = await FilePicker.platform
                          .pickFiles(allowedExtensions: [
                        "m4a",
                        "mp3",
                        "ogg",
                        "wav",
                      ], type: FileType.custom);  


static List<String> allowedDocumentExtensions() {
    return [
      'pdf',
      'doc',
      'zip',
      'ppt',
      'jpg',
      'jpeg',
      'gif',
      'png',
      'eps',
      'HEIF',
      'HEVC',
      'docs',
      'docx',
      'doc',
      'pptx',
      'ppt',
      'm4a',
      'mp3',
      'ogg',
      'wav',
      'mp4',
      'mkv',
      'm4v',
      'mov',
      'xlsx',
      'xls',
      'xlsb'
    ];
  }

**Comment by MohsinP07** [comment]
Will the permissions you suggested also work for files with this extension @Gagandeep1408 ? 
which are 

```
for 13 and above
 <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
```

**Comment by Gagandeep1408** [comment]
> Will the permissions you suggested also work for files with this extension @Gagandeep1408 ? which are
> 
> ```
> for 13 and above
>  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
> <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
> <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
> ```

Yes

**Comment by MohsinP07** [comment]
But still not working in my case for Android 13 @Gagandeep1408 .

**Comment by Gagandeep1408** [comment]
Did you check your manifest file?

Make sure your             android:launchMode="singleTask".

**Comment by MohsinP07** [comment]
@Gagandeep1408 Yes i did change in the manifest file as you suggested its its not working 
here is what i changed: 
` android:launchMode="singleTask"` 

it was "singleTop" before.

**Comment by Gagandeep1408** [comment]
Share the code to open file picker

**Comment by MohsinP07** [comment]
Hey @Gagandeep1408  Here it is 
` FilePickerResult? result =
                                await FilePicker.platform.pickFiles(
                              type: FileType.custom,
                              allowedExtensions: ['xlsx'],
                            );

                            if (result != null) {
                              File file = File(result.files.single.path!);
                              setState(() {
                                print(file.path);
                                filePath = file.path;
                              });`

**Comment by Gagandeep1408** [comment]
which flutter version are you using?

**Comment by MohsinP07** [comment]
Version: 3.7.10

**Comment by MohsinP07** [comment]
Hey @Gagandeep1408  any solutions?

**Comment by MohsinP07** [comment]
Hey @Gagandeep1408 Did you solved anything related to this ?

**Comment by Gagandeep1408** [comment]
No i did not get this issue after change  android:launchMode="singleTask"
