### ISSUE TITLE
Permission Error in Android Version 13.

### ISSUE THREAD

**Issue by MohsinP07** [miguelpruivo/flutter_file_picker#1421]
In my project, I am using the file_picker package for picking files. It still works perfectly in Android 12 and below. However, when I change my app's target version to 33, which is Android 13, it stops working and gives me an error:

PlatformException: PlatfomException(read_external_storage_denied, User did not allow reading external storage, null, null)

I have included all the required permissions in my manifest file, but I am still encountering this error. Additionally, in the app info, I am not seeing any requested permission for storage. This issue is specific to Android 13.

**Comment by twinkles-twinstar** [comment]
Since android13, the `READ_EXTERNAL_STORAGE` permission is no longer valid, you need to apply for `READ_MEDIA_**`.
Alternatively, it is possible to apply for the `MANAGE_EXTERNAL_STORAGE` permission directly, although this is not a good idea.

**Comment by MohsinP07** [comment]
@twinkles-twinstar  I used MANAGE_EXTERNAL_STORAGE  permission but its still not working as expected.

**Comment by yashdeveloper90** [comment]
i am also facing the same issue in my flutter project

**Comment by MohsinP07** [comment]
> i am also facing the same issue in my flutter project

Did you found any solution to this ?

**Comment by twinkles-twinstar** [comment]
> @twinkles-twinstar I used MANAGE_EXTERNAL_STORAGE permission but its still not working as expected.

Have you requested the `MANAGE_EXTERNAL_STORAGE` permission for your app and granted it at runtime?
I don’t know the details of `file_picker`. For the android side, I did not use `file_picker`, but wrote `MethodChannel` myself. You can take a look at my code [MainActivity.kt](https://github.com/twinkles-twinstar/TwinStar.ToolKit/blob/0477245cc0de5e04f8d792beed92d5b3b5033803/ShellGUI/android/app/src/main/kotlin/com/twinstar/toolkit/shell_gui/MainActivity.kt#L103C1-L103C1).
It works perfectly on Android 12 (my phone) and Android 13 (WSA emulator), requires `MANAGE_EXTERNAL_STORAGE` permission.
(Note: It is inconsistent with the behavior of file_picker, my code will try to resolve the uri to an absolute path, and only copy to the fallback directory if it cannot be resolved.)

**Comment by yashdeveloper90** [comment]
i have give the MANAGE_EXTERNAL_STORAGE permission but it does not work and check the permission is granted as well.

**Comment by MohsinP07** [comment]
@twinkles-twinstar Didn't get it bro, can you simplify. I have requested `MANAGE_EXTERNAL_STORAGE ` as well.

**Comment by MohsinP07** [comment]
> i have give the MANAGE_EXTERNAL_STORAGE permission but it does not work and check the permission is granted as well.

I am facing excatly same issue.

**Comment by yashdeveloper90** [comment]
i am also facing the same problem you facing if i found a solution then share a solution with you.

**Comment by sxzhangdashen** [comment]
So how did all the Guys ultimately solve this problem?

**Comment by twinkles-twinstar** [comment]
This seems a bit strange. . . flutter_file_picker seems to only report permission errors when sdk<33. [FilePickerDelegate.java](https://github.com/miguelpruivo/flutter_file_picker/blob/5eff0bfd9d904f6efefb53cb6f5ec9ce5a6fe459/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java#L278)
On Android 13, this exception seems like it shouldn't occur.
Did you just change the target sdk = android13, but run your app on the android12 device, or did you change the target sdk and use the android13 device to run the app?

I'm not the developer of this plugin, so it doesn't seem to solve your problem. My solution is to write my own methodchannel, you can check out my project:
[Kotlin](https://github.com/twinkles-twinstar/TwinStar.ToolKit/blob/ab642b29de152209d0203e8fa61b182f90716677/ShellGUI/android/app/src/main/kotlin/com/twinstar/toolkit/shell_gui/CustomMethodChannel.kt#L174)
[Dart](https://github.com/twinkles-twinstar/TwinStar.ToolKit/blob/ab642b29de152209d0203e8fa61b182f90716677/ShellGUI/lib/common/platform_method.dart#L38)

This is a very simple implementation, just declare the permissions in the manifest, then call checkStoragePermission/requestStoragePermission and finally call the pickPath function, it works fine on my device.
