### ISSUE TITLE
Unable to pick some files(specifically pdf) in android 13

### ISSUE THREAD

**Issue by sanketbachhav** [miguelpruivo/flutter_file_picker#1422]
In my project, I am using the file_picker package for picking files. It still works perfectly in Android 12 and below. However, when I change my app's target version to 33, which is Android 13, it stops working and gives me an error:

Platform exception: PlatformException(unknown_path, Failed to retrieve path., null, null)

I have included all the required permissions in my manifest file, but I still encounter this error. Additionally, I do not see any requested permission for storage in the app info. This issue is specific to Android 13.

**Comment by MohsinP07** [comment]
Hey @sanketbachhav, I am also facing the same problem. Did you get any solution to this?
