### ISSUE TITLE
dyld: Library not loaded: @rpath/DKImagePickerController.framework/DKImagePickerController

### ISSUE THREAD

**Issue by LogeshSharma3Frames** [miguelpruivo/flutter_file_picker#1423]
**Describe the bug**
In my project, I am using this file_picker: 5.3.1 for image and pdf picker. This package is working in Android but has the below issue while installing the iOS builds to devices/simulator

iOS build issue: The app crashed once installed and in response below is the crash report
The app crashed once installed and in response below is the crash rep
dyld[9325]: Library not loaded: @rpath/DKImagePickerController.framework/DKImagePickerController
  Referenced from: <0BC3EFBA-AABC-3DBB-ACB6-4C5FB43B674B> /Users/Library/Developer/CoreSimulator/Devices/671A271C-B244-43A5-9DF3-85B6B714D6B0/data/Containers/Bundle/Application/BB092F37-58F0-4B36-A754-4B247ECAFFF8/Runner.app/Runner
  Reason: tried: '/Users/Library/Developer/Xcode/DerivedData/Runner-guibrbalverbeydeejsuhuyztbzx/Build/Products/Debug-iphonesimulator/DKImagePickerController.framework/DKImagePickerController' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/DKImagePickerController.framework/DKImagePickerController' (no such file), '/usr/lib/swift/DKImagePickerController.framework/DKImagePickerController' (no such file, not in dyld cache), '/Users/Library/Developer/CoreSimulator/Devices/671A271C-B244-43A5-9DF3-85B6B714D6B0/data/Containers/Bundle/Application/BB092F37-58F0-4B36-A754-4B247ECAFFF8/Runner.app/Frameworks/DKImagePickerController.framework/DKImagePickerController' (no such file), '/Users/Library/Developer/CoreSimulator/Devices/671A271C-B244-43A5-9DF3-85B6B714D6B0/data/Containers/Bundle/Application/BB092F37-58F0-4B36-A754-4B247ECAFFF8/Runner.app/Frameworks/DKImagePickerController.framework/DKImagePickerController' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/DKImagePickerController.framework/DKImagePickerController' (no such file), '/usr/lib/swift/DKImagePickerController.framework/DKImagePickerController' (no such file, not in dyld cache), '/Users/Library/Developer/CoreSimulator/Devices/671A271C-B244-43A5-9DF3-85B6B714D6B0/data/Containers/Bundle/Application/BB092F37-58F0-4B36-A754-4B247ECAFFF8/Runner.app/Frameworks/DKImagePickerController.framework/DKImagePickerController' (no such file), '/Users/Library/Developer/CoreSimulator/Devices/671A271C-B244-43A5-9DF3-85B6B714D6B0/data/Containers/Bundle/Application/BB092F37-58F0-4B36-A754-4B247ECAFFF8/Runner.app/Frameworks/DKImagePickerController.framework/DKImagePickerController' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/DKImagePickerController.framework/DKImagePickerController' (no such file)

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.5 22G74 darwin-arm64, locale en-IN)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by Shailendra-3Frames** [comment]
I am also facing facing similar issue, any update on this?
