### ISSUE TITLE
File_picker doesn't behave as expected on Android 14

### ISSUE THREAD

**Issue by LiiOr** [miguelpruivo/flutter_file_picker#1427]
I have a flutter web application with multiple file adding functionality. It works as expected under previous versions of Android, and under IOS. But not since I updated Android to version 14...

![IMG_3064](https://github.com/miguelpruivo/flutter_file_picker/assets/74303710/9be2dab4-9eb7-4961-b182-085a06cd4b47)

Above is my app from an IOS phone, working as expected : A simple button offers the choice between camera or gallery. It was almost the same on Android 13. But now, it only opens the gallery...

Here is how i'm picking my files : 

```
_pickImage() async {
    try {
      FilePickerResult? result = await FilePicker.platform.pickFiles(
          type: FileType.image, allowMultiple: true, allowCompression: true);
      if (result != null && result.files.isNotEmpty) {
        for (int i = 0; i < result.files.length; i++) {
          PlatformFile file = result.files[i];
          Uint8List? imageBytes = file.bytes!;
          Uint8List? compressedImage = await compressImage(imageBytes);
          imgList.add(compressedImage);
        
        }
        setState(() {});
      }
    } catch (e) {
      throw Exception('Picking images failed : $e');
    }
  }
```
I tried updating File_Picker. I also tried other packages like image_picker... It's still the same.. 

I don't know if this is a "bug" or a "intentional" change from Android??

**Comment by sherwin** [comment]
Android  13 has this problem

**Comment by ambr89** [comment]
up
