### ISSUE TITLE
The video extension is jpeg (ios)

### ISSUE THREAD

**Issue by alim699** [miguelpruivo/flutter_file_picker#1436]
(ios) When selecting a video from the gallery and the video download from WhatsApp, the extension is entitled '.jpeg' and the video is not accepted for playback with this extension, and when dealing with it, it exits(crash) the application.

**Comment by keremsrtn** [comment]
same issue. any solution for this?

**Comment by keremsrtn** [comment]
@alim699 here is my temporary solution
