### ISSUE TITLE
File picker doesn't open or work. 

### ISSUE THREAD

**Issue by shashoug** [miguelpruivo/flutter_file_picker#1438]
I'm trying to pick a PDF file from device storage, So, I've followed all the steps in the documentation. 
Plugin version: 6.1.1 
Flutter version: 13.16.8 stable. 

So I implemented the picker with the following:

`FilePickerResult? result = await FilePicker.platfrom.pickFiles();`
`if(result !=null) {
File file = File(result.files.single.path!);`

When I click the button it doesn't response to the picker, after clicking it again it produce this error:

`[MethodChannelFilePicker] platform exception: PlatformException(multiple_request, Cancelled By second request, null, null)`

**Platform**

- [ ] iOS
Simulator and Physical device also.

**Comment by brswan** [comment]
I'm having the same issue.  Was this fixed?

**Comment by shashoug** [comment]
@brswan  I solved it, The issue was on my native method channel code, I have Applepay native code, with UIController which causing the problem, I made some refactoring and it all working now.

**Comment by brswan** [comment]
@shashoug Thanks for the follow up.  I needed to explicitly specify the audio extensions as described in #855
