### ISSUE TITLE
`FilePicker.platform.getDirectoryPath()` seems to be moving the original directory to `tmp` directory [IOS]

### ISSUE THREAD

**Issue by hasanmhallak** [miguelpruivo/flutter_file_picker#1440]
**Describe the bug**
It seems like the `FilePicker.platform.getDirectoryPath()` will move the original directory instead of copying it to tmp/cache directory.

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
IOS 17.2

**How are you picking?**
```
final path = await FilePicker.platform.getDirectoryPath();
       print(path);
```

**Details to reproduce the issue**
Try to use `FilePicker.platform.getDirectoryPath()` on any directory.

**Error Log**
N/A

**Screenshots and/or video**

https://github.com/miguelpruivo/flutter_file_picker/assets/95232508/f0e1f64f-4b6c-47c8-8bbb-a3a7328bcda4

**Flutter Version details**
```terminal
[✓] Flutter (Channel stable, 3.16.4, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources
```

**Additional context**
When invoking `FilePicker.platform.getDirectoryPath();` on Android, it successfully returns the actual path of any selected directory.

However, on iOS, due to the limitations you've outlined in your [FAQ](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ#q-why-cant-i-access-original-file-path), one must copy the file or directory to a temporary directory for access.

An issue arises with `FilePicker.platform.getDirectoryPath();` on iOS, where it **moves** the directory instead of copying it, contrary to the expected behavior. As a result, the user will permanently lose access to that directory.

**Comment by Reyrey14-1** [comment]
same here. any update on the issue?

**Comment by ElHyperion** [comment]
The FilePicker works fine on Android but on iOS it crashes my app with no permission to access "tmp", whether I want to pick an internal directory or an iCloud.

Also, awaiting the FilePicker.platform.getDirectoryPath() finishes immediately, even if the file picker is open.

Error log after picking I path:
```
File Provider Storage” couldn’t be moved because you don’t have permission to access “tmp”.
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x1808e10fc 0x199131d64 0x1809ea564 0x1808770e4 0x104dd361c 0x1836ec2dc 0x18309a524 0x1835e2748 0x182f31f18 0x183144998 0x182f9b190 0x182fb5dd0 0x182e812e8 0x182e95a5c 0x182e95bc4 0x18466aa08 0x180553670 0x180561b70 0x180899d84 0x180853f5c 0x180867468 0x19c40b38c 0x18320a5d0 0x182f88f74 0x102efcb28 0x10434daa4)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b7ecc964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1b7ecc964 <+8>:  b.lo   0x1b7ecc984               ; <+40>
    0x1b7ecc968 <+12>: pacibsp 
    0x1b7ecc96c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b7ecc970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.

Exited.```

**Comment by mrwill84** [comment]
any updated here ? I met same issue :(

**Comment by TheRedSpy15** [comment]
very frustrating this issue is seemingly ignored. this library is basically the only way to access files/folders with flutter

**Comment by ryanhoo** [comment]
Same here, any solutions? @miguelpruivo

**Comment by ElHyperion** [comment]
I tested some older versions and it seems to yield the same issue, I suppose there has been a breaking change in newer iOS versions?

**Comment by TheRedSpy15** [comment]
> I tested some older versions of this library and it seems to yield the same issue, perhaps there has been a breaking change in newer iOS versions?

I'm trying on ios 16 and no luck

**Comment by logan-oss** [comment]
Same here, we need a fix please.

**Comment by mateusz-bak** [comment]
Bump

**Comment by mateusz-bak** [comment]
Bumped

**Comment by miguelpruivo** [comment]
What's the status of this? Haven't experienced any issue in the meantime. Does this only happen on iOS 17.0? I'm not sure if I correctly understood the issue, it doesn't pick the path, is that it?

**Comment by ElHyperion** [comment]
Simply calling ``FilePicker.platform.getDirectoryPath();`` and picking -any- directory, whether internal or on iCloud, was enough for me. The issue happened every time.

**Comment by we-prajapati-c001** [comment]
For me on real devices the issue is reproducible. Works fine for simulator.

**Comment by miguelpruivo** [comment]
> Simply calling `FilePicker.platform.getDirectoryPath();` and picking -any- directory, whether internal or on iCloud, was enough for me. The issue happened every time.

But what is exactly the issue?

**Comment by ElHyperion** [comment]
@miguelpruivo selecting the directory crashes the app and throws the error that I pasted above.

**Comment by hasanmhallak** [comment]
hey @miguelpruivo, sorry for the late replay. 

When invoking `FilePicker.platform.getDirectoryPath();` on Android, it successfully returns the actual path of any selected directory.

However, on iOS, due to the limitations you've outlined in your [FAQ](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ#q-why-cant-i-access-original-file-path), one must copy the file or directory to a temporary directory for access.

An issue arises with `FilePicker.platform.getDirectoryPath();` on iOS, where it **moves** the directory instead of copying it, contrary to the expected behavior.

This concern is addressed in the issue that I've opened.

**Comment by mateusz-bak** [comment]
Bump

**Comment by mateusz-bak** [comment]
Bump

**Comment by mateusz-bak** [comment]
Bump

**Comment by we-prajapati-c001** [comment]
bump

**Comment by we-prajapati-c001** [comment]
bump

**Comment by razumeiko** [comment]
@miguelpruivo 
Here is the error
```
“Test” couldn’t be moved because you don’t have permission to access “tmp”.
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x1a115bf24 0x199012018 0x1a10fd2d8 0x10220f740 0x1a3ca3740 0x1a36157d4 0x1a3615278 0x1a366ec40 0x1a37127f4 0x1a3712478 0x1a33ee56c 0x1a33ee450 0x1a33ed168 0x1a33fa844 0x1a33fa8b4 0x1a27a11ac 0x1036067bc 0x103616d58 0x10361690c 0x1a112e750 0x1a112b954 0x1a112ad18 0x1e5c9e1a8 0x1a3767058 0x1a381b04c 0x10211c798 0x1c4b6fe4c)
libc++abi: terminating due to uncaught exception of type NSException
```
I think problem is that it's trying to move the directory, I did not find a way to add permissions to tmp, everything points that it's already should be granted.

**Comment by julian-CStack** [comment]
> @miguelpruivo Here is the error
> 
> ```
> “Test” couldn’t be moved because you don’t have permission to access “tmp”.
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
> *** First throw call stack:
> (0x1a115bf24 0x199012018 0x1a10fd2d8 0x10220f740 0x1a3ca3740 0x1a36157d4 0x1a3615278 0x1a366ec40 0x1a37127f4 0x1a3712478 0x1a33ee56c 0x1a33ee450 0x1a33ed168 0x1a33fa844 0x1a33fa8b4 0x1a27a11ac 0x1036067bc 0x103616d58 0x10361690c 0x1a112e750 0x1a112b954 0x1a112ad18 0x1e5c9e1a8 0x1a3767058 0x1a381b04c 0x10211c798 0x1c4b6fe4c)
> libc++abi: terminating due to uncaught exception of type NSException
> ```
> 
> I think problem is that it's trying to move the directory, I did not find a way to add permissions to tmp, everything points that it's already should be granted.

Also experiencing this

**Comment by we-prajapati-c001** [comment]
bump

**Comment by ElHyperion** [comment]
bump

**Comment by ElHyperion** [comment]
Are we seriously not getting any file saving support on iOS thanks to this package malfunctioning? Are there any suitable alternatives to this, if this issue isn't getting resolved?

**Comment by coderghl** [comment]
Does anyone know a solution? I also encountered this problem after calling getDirectoryPath()

“Documents” couldn’t be moved because you don’t have permission to access “tmp”.
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

**Comment by ready4sea** [comment]
Also experimenting this issue, just as described, on an iOS device.

**Comment by ready4sea** [comment]
Bump, quite problematic

**Comment by ElHyperion** [comment]
Bump. Makes this package nearly unusable.

**Comment by hasanmhallak** [comment]
Any update??

**Comment by hasanmhallak** [comment]
Bump

**Comment by hasanmhallak** [comment]
bump

**Comment by miguelpruivo** [comment]
Hi, I really don't have the time right now to look into this — just flagging for triage so it doesn't close on its own, I'd thank if anyone has the time to investigate and issue a PR. Shouldn't be a major thing, if this is related to a specific platform, I suspect of new iOS SDK breaking changes.

**Comment by ready4sea** [comment]
bump

**Comment by ElHyperion** [comment]
Bump. I don't think this issue has been flagged correctly to not close automatically, could @miguelpruivo please fix that?

**Comment by coderghl** [comment]
> Bump. I don't think this issue has been flagged correctly to not close automatically, could @miguelpruivo please fix that?

The latest version seems to have fixed this issue,you can try it.

**Comment by ElHyperion** [comment]
> The latest version seems to have fixed this issue,you can try it.

Thanks, I missed that update, works fine now 👍🏻
