### ISSUE TITLE
Any support/plan of Privacy Manifest?

### ISSUE THREAD

**Issue by percival888** [miguelpruivo/flutter_file_picker#1441]
According to the definition of "third-party SDKs" that as mentioned in the WWDC23, new documents: [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) and the new [announcement](https://developer.apple.com/news/?id=r1henawx) from Apple. It seems like file_picker require a privacy manifest and signature as well.

i'm looking forward to the completion of this feature

**Comment by navaronbracke** [comment]
This is a duplicate of #1418
