### ISSUE TITLE
The method 'getOptions' isn't defined for the class 'FileOpenDialog'.

### ISSUE THREAD

**Issue by Theunodb** [miguelpruivo/flutter_file_picker#1442]
When trying to run my app on the latest STABLE release of flutter i get the following error:

`
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/file_picker-6.1.1/lib/src/windows/file_picker_windows.dart:103:21: Error: The method 'getOptions' isn't defined for the class 'FileOpenDialog'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
`

This is the output of flutter doctor:
`
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale
    en-ZA)
    • Flutter version 3.16.9 on channel stable at /Users/theunodebruin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/theunodebruin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/theunodebruin/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/theunodebruin/Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Users/theunodebruin/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] Connected device (4 available)
    • Theuno’s iPhone 11 Pro Max (mobile) • 00008030-00161C4C1428802E
      • ios            • iOS 17.3 21D50
    • iPhone 15 Pro Max (mobile)          • 91780809-AB1C-48A4-93F5-8881DA2733D4
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                     • macos
      • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 121.0.6167.139
    ! Error: Browsing on the local area network for Theuno’s iPad. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
`

**Comment by batataw** [comment]
Same issue

Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/file_picker-5.5.0/lib/src/windows/file_picker_windows.dart:102:21: Error: The method 'getOptions' isn't defined for the class 'FileOpenDialog'.
