### ISSUE TITLE
getDirectoryPath() only gives access to media files in a directory

### ISSUE THREAD

**Issue by noob8boi** [miguelpruivo/flutter_file_picker#1446]
**Describe the bug**
getDirectoryPath() method on android gives access to media-only files but not the files like .zip, .csv etc. If this is the intended behavior then requesting MANAGE_EXTERNAL_STORAGE permission is the only way?

**Platform**
- Android

**Platform OS version**
Android 11

**How are you picking?**
```
final directoryPath = await FilePicker.platform.getDirectoryPath();
```

**Details to reproduce the issue**
1) use the method on android 11.
2) select any directory with non media files.

**Flutter Version details**
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/91360152/fb68e50f-69ae-4724-b5bd-ae4d00ab87e0)

**Comment by TheRedSpy15** [comment]
This should be marked as open

**Comment by rohinton-collins** [comment]
@noob8boi Did you find a solution to this problem?
