### ISSUE TITLE
At audio files, allowedExtensions is not working properly

### ISSUE THREAD

**Issue by KY-Jung** [miguelpruivo/flutter_file_picker#1448]
**Describe the bug**
I want to filter audio files (only mp3 files).
When I use a code like allowedExtensions: [ 'mp3' ],
m4a, m4r, mp3 files are displayed.
So strange.

**Platform**
- [ v ] Android

**Platform OS version**
Pixel 4a API 33 (Android Emulator)

**How are you picking?**
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      //type: FileType.audio,
      type: FileType.custom,
      allowedExtensions: [ 'mp3' ],  
    );

**Flutter Version details**
flutter doctor -v
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4046], locale ko-KR)
    • Flutter version 3.19.0 on channel stable at C:\_util\flutter         
    • Upstream repository https://github.com/flutter/flutter.git           
    • Framework revision bae5e49bc2 (7 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9                                           
    • Dart version 3.3.0                                                   
    • DevTools version 2.31.1                                              

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Michael\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.3.4
    • Flutter plugin version 78.1.1
    • Dart plugin version 233.13763.5

[√] VS Code (version 1.76.1)
    • VS Code at C:\Users\Michael\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by melWiss** [comment]
same here, there's a real issue with the MimeType thing
