### ISSUE TITLE
Flutter desktop - macOS

### ISSUE THREAD

**Issue by AndrsDev** [miguelpruivo/flutter_file_picker#145]
Is there any implementation for the picker on macOS? I tried to use it and I got the error:

> flutter: [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method ANY on channel file_picker)

**Comment by AndrsDev** [comment]
Sorry I've found it on the docs

**Comment by geoah** [comment]
@AndrsDev I'm playing around with flutter desktop (not go-flutter) and I was wondering how you managed to run this for macOS. Can't find anything in the docs that is not specific to go-flutter.

Thank you.
