### ISSUE TITLE
Auto Select when there are attachments that are already selected

### ISSUE THREAD

**Issue by tomari99** [miguelpruivo/flutter_file_picker#1450]
Is there a parameter for auto selecting the attachment that are already selected.

**Comment by mNouh94** [comment]
Unfortunately no, i'm facing the same issue

**Comment by miguelpruivo** [comment]
I don't get what's the issue here. If they are already selected what do you want to select?

**Comment by tomari99** [comment]
> > I don't get what's the issue here. If they are already selected what do you want to select?
> 
> When the user select some files and the user wants to add more files, in this case the user must select the previous selected files and the new once, instead of this user must see already selected files and only select the new once.

exactly! I want to pre-select when a user selects one more time if the files are selected previously.

**Comment by miguelpruivo** [comment]
Don't get me wrong folks, but I really don't see/understand what's the issue. Can you please record a video? Thanks.

**Comment by mNouh94** [comment]
@miguelpruivo Here's a recorded video

https://github.com/miguelpruivo/flutter_file_picker/assets/47349530/46c4bc4d-5725-4419-b9f6-73b307324c4d

**Comment by mNouh94** [comment]
@miguelpruivo any feedback about it?
