### ISSUE TITLE
Android: image picker and file picker apps with launchMode=singleInstance doesn't work (more specifically Samsung devices)

### ISSUE THREAD

**Issue by TheManuz** [miguelpruivo/flutter_file_picker#1456]
### Describe the bug
The plugin was working just great but when we needed to make our app's launchMode=singleInstance, the picker doesn't work
The issue was [first reported in October 2023](https://github.com/miguelpruivo/flutter_file_picker/issues/1379), but it's still present today.
The original issue was closed because it became stale. 

### Platform
Android

### Platform OS version
Android 11 and Android 13

### Details to reproduce the issue
create android app with `launchMode=singleInstance` and try to pick an image or custom file and it will always return null

### Flutter Version details
Flutter 3.19.1, but first report was on 3.10.6

**Comment by TheManuz** [comment]
Bump

**Comment by miguelpruivo** [comment]
What is the solution purposed for this? Not sure what about the consequences of limiting it for `single`. I recall that it could introduce some issues but don't remember which.

**Comment by miguelpruivo** [comment]
Looks like a dup of #1404. Let's keep it there. Closing.
