### ISSUE TITLE
unable to select file

### ISSUE THREAD

**Issue by s-j-a** [miguelpruivo/flutter_file_picker#146]
Hi,
on IOS 13 file picker doesn't select the file and return the path, I can click on the file icon but it doesn't return the screen stays as it was. Only when I hit cancel does the it return to my application with a null result.

the solution was working before the upgrade. I have added the recommended keys to the info.plist file.

any suggestions ?

thanks,
Jamil

**Comment by miguelpruivo** [comment]
Just make sure you are on the latest version (1.4.2). Do a clean a rebuild, it should work. Does that happen with all kind of files?

Miguel

**Comment by s-j-a** [comment]
I am using version 1.4.2, still the same issue after clean rebuild. I currently have PDF files and a .txt file in the folder, neither type is selectable.

Is there some additional permissions issue with IOS 13 ?, I used to be able to save email attachments to the download folder, now it just saves them to its own download folder (which I can't access). If I try to save to file it doesn't do anything. Currently I have just copied some files directly into the folder for testing.

**Comment by miguelpruivo** [comment]
@s-j-a it shouldn't. Could you please post the logs when you are trying to pick a file? Also, could you please give it a try with a video file? Thank you.

**Comment by s-j-a** [comment]
same issue with a video

looking at the system.log, nothing shows up when opening up the file explorer or clicking on a file, but there many of the following with different services

`Sep 25 14:20:44 Jamils-iMac Runner[38865]: assertion failed: 18G95 17A577a: libxpc.dylib + 83495 [9A486F3D-BBFA-36F2-9105-42A059A13A8A]: 0x7d
Sep 25 14:21:21 Jamils-iMac com.apple.CoreSimulator.SimDevice.954B9741-991F-42A5-AEC2-136F05914239[35227] (com.apple.DocumentManagerCore.Downloads): Unknown key for Boolean: EnableTransactions
Sep 25 14:21:21 Jamils-iMac com.apple.CoreSimulator.SimDevice.954B9741-991F-42A5-AEC2-136F05914239[35227] (com.apple.DocumentManagerCore.Downloads): Unknown key for Boolean: EnablePressuredExit
Sep 25 14:21:21 Jamils-iMac com.apple.CoreSimulator.SimDevice.954B9741-991F-42A5-AEC2-136F05914239[35227] (com.apple.FileProvider.ArchiveService): Unknown key for Boolean: EnableTransactions
Sep 25 14:21:21 Jamils-iMac com.apple.CoreSimulator.SimDevice.954B9741-991F-42A5-AEC2-136F05914239[35227] (com.apple.FileProvider.ArchiveService): Unknown key for Boolean: EnablePressuredExit
Sep 25 14:21:21 Jamils-iMac com.apple.CoreSimulator.SimDevice.954B9741-991F-42A5-AEC2-136F05914239[35227] (com.apple.FontServices.FontProviderLoader): Unknown key for Boolean: EnableTransactions
`

thanks for your help.

**Comment by miguelpruivo** [comment]
@s-j-a looks like something device related. Would you mind to try on a different device or emulator running iOS 13?

**Comment by s-j-a** [comment]
tested on simulator for iPhone XS Max with IOS 12.2, works fine.

'save to files' option  allows selecting my app for a location (listed under the my iPhone option), I can then see the file in my app and select it using File picker.

something changed with IOS 13 to prevent this from working.

**Comment by s-j-a** [comment]
just to add using different hardware simulators e.g. iPhone 8 but with IOS 13 did not work.

**Comment by miguelpruivo** [comment]
I'm still not sure about what's happening because I can't seem to replicate the issue. Can you do a video with the example app provided with the plugin and let me see what's happening?

**Comment by s-j-a** [comment]
small demo
[File Open Test.mp4.zip](https://github.com/miguelpruivo/flutter_file_picker/files/3657294/File.Open.Test.mp4.zip)

if you open your email from Safari, are you able to save an email attachment to any folder ? I think there are two issues here one with Safari and one with not being able to select files.

**Comment by miguelpruivo** [comment]
@s-j-a looks like you are pressing the file too much time when using the picker. Just a small click should work, otherwise you'll enter in that context window.

**Comment by miguelpruivo** [comment]
@s-j-a I'll assume this has been solved. Feel free to reopen if you still experience any issue related to this. Thank you.

**Comment by miguelpruivo** [comment]
@juriejan I didn't have enough details for this issue so I'm not sure what's happening. Feel free to describe the full steps to reproduce it.

**Comment by s-j-a** [comment]
When I tested on an actual iPhone running 13.1 it worked fine so I concluded that this was not an issue with the code rather an issue with the simulator, there were a lot of sandbox file permission error messages in the simulator console . 

ensure that you are using the latest version of Xcode and download the simulator for iPhone 11 Pro MAX - 13.1, its working for me now on this setup.

the 12.2 iPhone X stopped working after this !, anyway I have a working simulator so I can continue with my project.

hope this helps.

**Comment by DCubix** [comment]
Hello I'm using the latest version and I'm having the **exact same** issue.
I'm using iOS 13.3 on a Simulator which is iPhone 11 Pro Max.

The file selection opens up normally but it does not return to the app when we select the file...

**Comment by miguelpruivo** [comment]
@DCubix which version of the plugin are you using? And also what are the FileType that you are using.

The only time it could result in that behavior is if you select files from a provider (such as Dropbox or Google Drive) and don’t give it enough time to load the file (there is no loading progress for 3rd party providers, unfortunately).

**Comment by DCubix** [comment]
@miguelpruivo I'm using version 1.6.2, and using a custom FileType. (Trying to open a PDF file).

**Comment by miguelpruivo** [comment]
@DCubix would are you picking from iCloud or 3rd party provider?

**Comment by DCubix** [comment]
@miguelpruivo Nope, I'm just trying to pick a file from the phone's internal storage

**Comment by miguelpruivo** [comment]
@DCubix would you mind to record a video? Thanks!

**Comment by DCubix** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5081992/79644724-c0449480-8178-11ea-884f-b1db70b51083.gif)

**Comment by DCubix** [comment]
![Gravacao-de-Tela-2020-04-18-as-1](https://user-images.githubusercontent.com/5081992/79644778-1d404a80-8179-11ea-9008-be75f313a39b.gif)

**Comment by miguelpruivo** [comment]
Hum, thanks @DCubix. This looks sort like a glitch from the simulator. Does that happen on a real device? What if you try in a different folder?

**Comment by DCubix** [comment]
@miguelpruivo ah that might be the problem... I unfortunately have no iOS 13 device to test
