### ISSUE TITLE
App crashes since 6.2.0 when opening file using FileType.image on Android

### ISSUE THREAD

**Issue by m-gug** [miguelpruivo/flutter_file_picker#1460]
**Describe the bug**
After updating to 6.2.0 the app crashes on Android 13/14 when using FileType.image. Details see Exception below.
When adding the new parameter compressionQualtiy=0, it is working without a problem.
Also opening the exact same file using `allowedExtensions: ["pdf", "jpg", "png", "jpeg"], type: FileType.custom` works without a problem.

It seems like the new compressionQualtiy parameter introduced a problem when opening images.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
13 and 14

**How are you picking?**
This snippet crashes the app:
```
FilePickerResult? filePickerResult = await FilePicker.platform.pickFiles(allowMultiple: false, type: FileType.image);
```

These are working:
`FilePickerResult? filePickerResult = await FilePicker.platform.pickFiles(allowMultiple: false, type: FileType.image, compressionQuality: 0);`
or
`FilePickerResult? filePickerResult = await FilePicker.platform.pickFiles(allowMultiple: false, allowedExtensions: ["pdf", "jpg", "png", "jpeg"], type: FileType.custom);`

**Details to reproduce the issue**
- Upgrade to 6.2.0
- Launch app on Android 13 or 14
- Open file using above snippt
- App crashes

**Error Log**
```
Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Pictures/IMG_20240109_091328.jpg: open failed: EACCES (Permission denied)
E/AndroidRuntime( 4962): FATAL EXCEPTION: Thread-6
E/AndroidRuntime( 4962): Process: at.kigadu.app, PID: 4962
E/AndroidRuntime( 4962): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
E/AndroidRuntime( 4962): 	at com.mr.flutter.plugin.filepicker.FileUtils.compressImage(FileUtils.java:106)
E/AndroidRuntime( 4962): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:104)
E/AndroidRuntime( 4962): 	at java.lang.Thread.run(Thread.java:1012)
```

**Flutter Version details**
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.22631.3235], locale de-DE)
    • Flutter version 3.19.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\gug\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\gug\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.9.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.9.34701.34
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\gug\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3235]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.61

[√] Network resources
    • All expected network resources are available.

**Additional context**

**Comment by m-gug** [comment]
Just saw the PR #1458, which sounds like it fixes the problem.

**Comment by miguelpruivo** [comment]
Fixed and merged. Thanks!
