### ISSUE TITLE
Unable to pick sf2 file (sound font) on Android

### ISSUE THREAD

**Issue by KapitanPL** [miguelpruivo/flutter_file_picker#1462]
I tried to use file_picker to select sound font file with extension sf2

`FilePickerResult? result = await FilePicker.platform.pickFiles(allowedExtensions: ['sf2']);`

results in: 
`Exception: You are setting a type [FileType.any]. Custom extension filters are only allowed with FileType.custom, please change it or remove filters.`

Following the advice: 

`FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['sf2']);`

results in 
`PlatformException (PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null))`

There is no FileType.all, only FileType.any

Could you help me use the picker for this file? What is the reason for unsupported filter?

**Comment by miguelpruivo** [comment]
It's a typo, you should use `FileType.any`.

Thanks.

**Comment by KapitanPL** [comment]
@miguelpruivo Tried. Does not work. 
It then tries to get MIME type of such file. It does not as it is not a "usual" kind of file. 
And simply fails. 

I had to let user choose any file and then if the extension is not correct, display a warning message and let him choose again.

**Comment by melWiss** [comment]
do we have news about this one? i'm trying to import msg files only but i had to go with the same idea, i mean letting the user selecting anything and then i filter which isn't the best user experience i think
