### ISSUE TITLE
Choose photo on ios error

### ISSUE THREAD

**Issue by vitchum** [miguelpruivo/flutter_file_picker#1463]
***** Picker:<PHPickerViewController: 0x135f868b0> didFinishPicking:(
    "<PHPickerResult: 0x280bc1410>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 465]
4FBAD8C6-DB57-4855-9E62-B76739BC920E grantAccessClaim reply is an error: Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x280bcd140 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 609 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 609 on anonymousListener or serviceListener}}}
Error copying file type public.item. Error: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x280bcd740 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x280bcd140 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 609 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 609 on anonymousListener or serviceListener}}}}}

***** Could not load the picked given file: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x280bcd740 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x280bcd140 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 609 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 609 on anonymousListener or serviceListener}}}}}
* -[FilePickerPlugin picker:didFinishPicking:]_block_invoke [Line 497]
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x280bcd740 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x280bcd140 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 609 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 609 on anonymousListener or serviceListener}}}}}, null)

**Comment by Christian-ckh** [comment]
> I am getting the same error after updating to ios 17. It only happens with images taken after i change the image format to "most compatible" in camera settings. Was working fine in ios 16.

I experience the same problem

**Comment by GastonTestay** [comment]
> I am getting the same error after updating to ios 17. It only happens with images taken after i change the image format to "most compatible" in camera settings. Was working fine in ios 16.

I experience the same problem.

**Comment by GastonTestay** [comment]
Hello, any news about it?
