### ISSUE TITLE
2 files same name, different folder, returns same path for both files

### ISSUE THREAD

**Issue by rsanjuan87** [miguelpruivo/flutter_file_picker#1464]
**Platform**

-  Android

**Platform OS version**
Android 13 and others

**How are you picking?**
pdf

**Details to reproduce the issue**
Set 2 files with the same file name in different folders, will replace first one with the second
When return the file path  both times the same path

**Comment by miguelpruivo** [comment]
Fixed by you and already published. Thanks.
