### ISSUE TITLE
[Android] user is still able to select images when allowedExtensions contains "pdf" only

### ISSUE THREAD

**Issue by xonaman** [miguelpruivo/flutter_file_picker#1467]
On Android, using the following code, the user is still able to select images.

```dart
final FilePickerResult? result = await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: <String>['pdf'],
  allowMultiple: true,
);
```

**Comment by khurram40** [comment]
I am alson facing same issue, Any update on this please?

**Comment by miguelpruivo** [comment]
This has been discussed a lot of times and it's also under the FAQs as [the first question](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

TL;DR: Some android OS specially with custom pickers, don't respect the filters and hence allow non supposed files to be picked. Devs should _always_ validate the picked files, specially on Android implementations.
