### ISSUE TITLE
Missing the transparency when picking PNG files from storage

### ISSUE THREAD

**Issue by ameenvga** [miguelpruivo/flutter_file_picker#1468]
**bug**
When I pick PNG files using the below code , the transparent area shows black color
` final res = await FilePicker.platform.pickFiles(
        type: FileType.image,
      );`
      
But when I use the below code , using FileType.any the transparency is working...
` final res = await FilePicker.platform.pickFiles();`

But I only wants to pick image type files...

**Platform OS version**
Android 13

**Flutter Version details**
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
    • Flutter version 3.19.3 on channel stable at /Users/ameen_abdussalam/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (10 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

**Additional context**
It worked before. when I was using 6.1.1 version of File picker.

**Comment by miguelpruivo** [comment]
You may want to set `allowCompression` to `false` when using `pickFiles`. Let me know if it fixes for you, if it does, please close this.

Thanks.

**Comment by ameenvga** [comment]
It does not work. I changed to  file_picker: ^5.5.0 version. and the code  
`final res = await FilePicker.platform.pickFiles( type: FileType.image, );`
works well.

**Comment by miguelpruivo** [comment]
@ameenvga can you point me to which version the issue started?
