### ISSUE TITLE
Not Load File Bytes on Windows

### ISSUE THREAD

**Issue by gorjix** [miguelpruivo/flutter_file_picker#1470]
Hello dear developer. after call this [ FilePickerResult? result = await FilePicker.platform.pickFiles(); ] result byte is null on windows.
my Windows is 10 Enterpriseand  and Os build 19045.4170.
used version => file_picker: ^8.0.0+1
Please Solve this.
![bug](https://github.com/miguelpruivo/flutter_file_picker/assets/65368006/29a4e10c-8320-488e-98b2-b9f2c093edb9)

**Comment by sebipirpi** [comment]
Hi, I ran into the same issue on iOS and got around it using `xFile` instead of `bytes` for now.

Instead of 
`final bytes = result.files.first.bytes;`
do
`final bytes = await result.files.first.xFile.readAsBytes();`

**Comment by gorjix** [comment]
tanx @sebipirpi its solved

**Comment by gorjix** [comment]
solved
