### ISSUE TITLE
Unable to pick file bytes when Web is running on iOS

### ISSUE THREAD

**Issue by SamuelWakoli** [miguelpruivo/flutter_file_picker#1471]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

file_picker 8.0.0+1
I want my web app to pick files in almost all platforms; Currently it crushed my website when running on iOS during testing

**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
Was running Web on iOS

**How are you picking?**
```
Please, post the snippet here
```
```
onTap: () async {
late FilePickerResult? result;

                          result = await FilePicker.platform.pickFiles(
                            type: FileType.custom,
                            allowedExtensions: ['pdf', 'doc'],
                          );

                          if (result != null && result.files.isNotEmpty) {
                            resumeFileBytes = result.files.first.bytes!;

                            resumeFileName = result.files.first.name;
                            setState(() async {
                              isFileUploading = !isFileUploading;
                              widget.onInputAnswer([resumeFileName]);
                            });
                          } else {
                            // User canceled the picker
                          }
}
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.
Web works well on other platforms, including MacOS

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.
https://github.com/miguelpruivo/flutter_file_picker/assets/97802502/24d9397f-6ad6-4162-997c-f942ba1481f0

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/97802502/22b9fe3a-7399-4e81-82e7-59faef73d05d)

https://github.com/miguelpruivo/flutter_file_picker/assets/97802502/24d9397f-6ad6-4162-997c-f942ba1481f0

**Additional context**

**Comment by sebipirpi** [comment]
Hi, I ran into the same issue and got around it using `xFile` instead of `bytes` for now.

Instead of 
`final bytes = result.files.first.bytes;`
do
`final bytes = await result.files.first.xFile.readAsBytes();`

**Comment by SamuelWakoli** [comment]
Hello [sebipirpi](https://github.com/sebipirpi);
Thank you for the workaround.
