### ISSUE TITLE
[Android]`READ_EXTERNAL_STORAGE` permission

### ISSUE THREAD

**Issue by angcyo** [miguelpruivo/flutter_file_picker#1473]
Instead of using 
`Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)`,

use
`context.getExternalCacheDir()`

so we don't need `Manifest.permission.READ_EXTERNAL_STORAGE`.

**Comment by Levi-Lesches** [comment]
Hi, I think this is related to my error: 
```
 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Pictures/Screenshots/Screenshot_20240326-210404.png: open failed: EACCES (Permission denied)
```
Which crashed my app.

**Comment by angcyo** [comment]
You need permission to read sd files directly, 

but the images returned from the system album are automatically cached in the app cache directory, 

so you do not need permission to read images.

**Comment by Levi-Lesches** [comment]
Right. Turns out, as of Android API 33, we need to explicitly ask for permissions in the `AndroidManifest.xml`: 
```xml
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
```
and in Dart: 
```dart
import "package:permission_handler/permission_handler.dart";

if (await Permission.photos.request().isGranted) {
  // ...
}
```

**Comment by angcyo** [comment]
have fun.
