### ISSUE TITLE
FilePicker getDirectoryPath Temporarily Freezes App on Windows

### ISSUE THREAD

**Issue by LordLux** [miguelpruivo/flutter_file_picker#1478]
**Describe the bug**
Using `FilePicker.platform.getDirectoryPath()` on Windows completely freezes the app when waiting for the user to select a folder. (Both with and without `lockParentWindow` set to true or false.)

Using the file picker instead of the folder picker works correctly and doesn't freeze the app while waiting, so I created this issue.

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [x] Desktop

**Platform OS version**
Microsoft Whdows
Version 22H2 (OS Build 19045.4239)

**How are you picking?**
```
String? selectedDirectory = await FilePicker.platform.getDirectoryPath();
```

**Details to reproduce the issue**
Run the above stated code on your windows flutter app and see the folder picker appear.

**Error Log**
No error logs.

**Screenshots and/or video**
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/74434026/2b54cefb-2fc6-4617-8ea1-0ad72ba3cbe5)

https://github.com/miguelpruivo/flutter_file_picker/assets/74434026/7731c6dc-0298-46d0-a77d-5adb4c3559db

**Flutter Version details**
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4239], locale en-GB)
    • Flutter version 3.19.0 on channel stable at C:\Users\User\Downloads\flutter
    • Upstream repository https://github.com/flutter/flutter.git      
    • Framework revision bae5e49bc2 (7 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34525.116
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      https://plugins.jetbrains.com/plugin/9212-flutter 
    • Dart plugin can be installed from:
      https://plugins.jetbrains.com/plugin/6351-dart   
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4239]       
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by BTMuli** [comment]
> Using the file picker instead of the folder picker works correctly and doesn't freeze the app while waiting, so I created this issue.

What that mean?I face the same crash when use `FilePicker.platform.getDirectoryPath()`，is there a temp measure?

**Comment by BTMuli** [comment]
> Is there a temp measure?

`file_selector` works

**Comment by LordLux** [comment]
> What that mean?
Sorry, i didn't word it very well.
I meant that, when using `pickFiles`, this problem does not appear; it only appears when using `getDirectoryPath`. And stated that that was the reason to create this issue

**Comment by Aksoyhlc** [comment]
The problem still persists.
