### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference

### ISSUE THREAD

**Issue by ShohruhSharipov1106** [miguelpruivo/flutter_file_picker#1479]
[fb18cb9e493732c95bd566b9297767ec_crash_session_660E492C005B0001254EC5FC9E7B01B6_DNE_0_v2_stacktrace.txt](https://github.com/miguelpruivo/flutter_file_picker/files/14862604/fb18cb9e493732c95bd566b9297767ec_crash_session_660E492C005B0001254EC5FC9E7B01B6_DNE_0_v2_stacktrace.txt)

file picker version: 8.0.0+1
flutter version: stable channel 3.19.5

**Comment by krokyze** [comment]
Seeing the same issue for some users, it's more popular on Xiaomi devices than others, but it's on some Samsung, Google too.

**Comment by AdarshKSeeroo** [comment]
Noticed same exception in our flutter app with filepicker 6.2.0, it was all working fine till last month. Yesterday one of our tester reported app force closing after picking image. We were able to reproduce the same issue in latest A14 emulator.

**Comment by SoftWyer** [comment]
Possibly related to #1473

**Comment by Whaleman0423** [comment]
I have the same problem. It happened when using
Android 13 (SDK 33)
Android 14 (SDK 34)

google oriole
realme RE879AL1
samsung a52sxq
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
  at com.mr.flutter.plugin.filepicker.FileUtils.compressImage (FileUtils.java)
  at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run (FilePickerDelegate.java)
  at java.lang.Thread.run (Thread.java:1012)
```

**Comment by MohammedMahmmoud** [comment]
file_picker: ^8.0.3

SDK-> Flutter 3.22.0,  Dart 3.4.0

I also got the same crash on picking images on Android 10 (SDK 29)
Devices: 
Oppo F7, Google Pixel

`Exception java.lang.RuntimeException: java.io.IOException: Permission denied
  at com.mr.flutter.plugin.filepicker.FileUtils.compressImage (FileUtils.java)
  at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run (FilePickerDelegate.java)`
