### ISSUE TITLE
          _mp4Path = await FilePicker.getFilePath(               //图片单选               type: FileType.CUSTOM,               fileExtension: 'mp4');

### ISSUE THREAD

**Issue by 15587879187** [miguelpruivo/flutter_file_picker#148]

**Comment by miguelpruivo** [comment]
@15587879187 sorry mate, could you please provide more details (in english)? Otherwise I'll be forced to close this due to lack of understandable content.

Thank you!

**Comment by miguelpruivo** [comment]
Closing due to no further details. Feel free to reopen if you have more details. Thank you.
