### ISSUE TITLE
Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [miguelpruivo/flutter_file_picker#1480]
The short version:
  - Migrate usage of dart:html to package:web
  - Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will also compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

**Comment by amrgetment** [comment]
My PR to support WASM

https://github.com/miguelpruivo/flutter_file_picker/pull/1481

**Comment by IchordeDionysos** [comment]
Still relevant

**Comment by navaronbracke** [comment]
This will be included in the next release.
