### ISSUE TITLE
File Picker Get Directory Crash on IOS Real Device ...

### ISSUE THREAD

**Issue by Aggie85** [miguelpruivo/flutter_file_picker#1485]
**_QUICK UPDATE:_**

Just compile the example app to a real Apple IOS device to see the issue.

I also tried several versions of file_picker going back to 5.5 and they all have the same issue under IOS 17.5. Unfortunately, I only have the one IPAd and IPhone and they both are set to 17.5 of IOS.

**_ISSUE:_**

The lastest version of file_picker 8.0.0+1 trying to select a folder on a REAL IPhone15 Pro Max and IPad 12.9 in IOS beta version 17.5 causes the following exception:

Exception	NSException *	"*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array"	0x000000030322cd20
name	__NSCFConstantString *	"NSRangeException"	0x00000001f39035d0
reason	__NSCFString *	"*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array"	0x0000000301920540
userInfo	void *	NULL	0x0000000000000000
reserved	__NSDictionaryM *	3 key/value pairs	0x0000000303df8320

**_Code snippet causing the issue:_** 

      String? path = await FilePicker.platform.getDirectoryPath(
        dialogTitle: widget._dialogTitle,
        // initialDirectory: _selectedDirectory,
        lockParentWindow: false,
      );

**_Flutter Version:_**

Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (12 days ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

**_Other Notes:_**

Code works in IOS Emulator on same phone running 17.4.2, Android REAL devices, macOS, and Windows.

**Comment by najiezzeldien** [comment]
Same issue.
