### ISSUE TITLE
Compilation fails with Pod::PICKER_DOCUMENT = false 

### ISSUE THREAD

**Issue by Aulig** [miguelpruivo/flutter_file_picker#1486]
**Describe the bug**
Set Pod::PICKER_DOCUMENT = false in the Podfile as documented in the Wiki. Compilation fails on version 7.0.0 and above (it was working in 6.x.x)

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Error Log**
Semantic Issue (Xcode): Property 'documentPickerController' not found on object
of type 'FilePickerPlugin *'; did you mean 'audioPickerController'?
/Users/administrator/.pub-cache/hosted/pub.dev/file_picker-8.0.0+1/ios/Classes/F
ilePickerPlugin.m:189:9

Semantic Issue (Xcode): Property 'documentPickerController' not found on object
of type 'FilePickerPlugin *'; did you mean 'audioPickerController'?
/Users/administrator/.pub-cache/hosted/pub.dev/file_picker-8.0.0+1/ios/Classes/F
ilePickerPlugin.m:190:9

Semantic Issue (Xcode): Property 'documentPickerController' not found on object
of type 'FilePickerPlugin *'; did you mean 'audioPickerController'?
/Users/administrator/.pub-cache/hosted/pub.dev/file_picker-8.0.0+1/ios/Classes/F
ilePickerPlugin.m:191:9

Semantic Issue (Xcode): Property 'documentPickerController' not found on object
of type 'FilePickerPlugin *'; did you mean 'audioPickerController'?
/Users/administrator/.pub-cache/hosted/pub.dev/file_picker-8.0.0+1/ios/Classes/F
ilePickerPlugin.m:194:17

Semantic Issue (Xcode): Property 'directoryURL' not found on object of type
'MPMediaPickerController *'
/Users/administrator/.pub-cache/hosted/pub.dev/file_picker-8.0.0+1/ios/Classes/F
ilePickerPlugin.m:194:42

Semantic Issue (Xcode): Property 'documentPickerController' not found on object
of type 'FilePickerPlugin *'; did you mean 'audioPickerController'?
/Users/administrator/.pub-cache/hosted/pub.dev/file_picker-8.0.0+1/ios/Classes/F
ilePickerPlugin.m:197:68

**Additional context**
The problem is that documentPickerController doesn't get defined due to the flag in the Podfile, but not all references are properly removed too.

**Comment by aggeloskoutanis** [comment]
+1

**Comment by marco-palumbo** [comment]
Have you found a workaround for this issue?

**Comment by Aulig** [comment]
> Have you found a workaround for this issue?

You can set Pod::PICKER_DOCUMENT = true

**Comment by marco-palumbo** [comment]
> > Have you found a workaround for this issue?
> 
> You can set Pod::PICKER_DOCUMENT = true

Yes, but I need it to be false. I guess I have to wait for the fix.

**Comment by Aulig** [comment]
> > > Have you found a workaround for this issue?
> > 
> > 
> > You can set Pod::PICKER_DOCUMENT = true
> 
> Yes, but I need it to be false. I guess I have to wait for the fix.

I submitted a PR now https://github.com/miguelpruivo/flutter_file_picker/pull/1494

You can use my fork in your pubspec

  file_picker:
    git:
      url: https://github.com/Aulig/flutter_file_picker.git
