### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by premtemp1** [miguelpruivo/flutter_file_picker#149]
Hello,
  Can you please help... The plugin  crashes on android

Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=50868, result=-1, data=Intent { dat=content://com.dropbox.android.FileCache/filecache/8d02cbe8-789c-4167-8a0d-c1d80e8af393 typ=application/pdf flg=0x3 }} to activity {com.MyApp/com.MyApp.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist

file_picker: ^1.3.5

Brand: LGE
Model: LG Aristo
Orientation: Portrait
RAM free: 368.23 MB
Disk free: 3.51 GB
version 7

Thanks for your help..

**Comment by miguelpruivo** [comment]
@premtemp1 you are using an old version of the plugin, please upgrade to `file_picker: ^1.4.2`. Do a `flutter clean` and try again. Thank you.

**Comment by premtemp1** [comment]
Thanks for your quick response.. I will try it now 

Thank you

**Comment by miguelpruivo** [comment]
Just let me know if it worked for you. If it does, feel free to close the issue, thank you.

**Comment by premtemp1** [comment]
Issue fix .. Thank you for the quick response  and the plugin
