### ISSUE TITLE
Update regarding DKImagePickerController/PhotoGallery of Privacy Manifest?

### ISSUE THREAD

**Issue by msai0109** [miguelpruivo/flutter_file_picker#1501]
According to the definition of "third-party SDKs" that as mentioned in the WWDC23, new documents: [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) and the new [announcement]  (https://developer.apple.com/news/?id=r1henawx) from Apple. as file_picker is depend on DKImagePickerController It seems like DKImagePickerController/PhotoGallery require a privacy manifest.

i'm looking forward to the completion of this request

**Comment by navaronbracke** [comment]
That library is sadly not very well maintained. I did file #1433 to drop support for the library, because we only have one use for it currently.

**Comment by msai0109** [comment]
Thank you for the update, @navaronbracke.

Is there any possible way to overcome the privacy manifest update of DKImagePickerController/PhotoGallery? For example, if we add PrivacyInfo.xcprivacy to the app, will it overcome this issue?

**Comment by navaronbracke** [comment]
I think you can indeed add the Required Reason fields for `DKImagePickerController/PhotoGallery` to your own Privacy Manifest as a workaround. Once we know how Apple enforces things (starting from next week, we will know), we can re-evaluate if we should remove `DKImagePickerController/PhotoGallery`

**Comment by navaronbracke** [comment]
DKImagePickerController did release an updated version 0.0.18 that includes a PrivacyManifest. Since `file_picker` does not specifically pin a version, doing a `pod repo update && pod install` is sufficient to pick up this new version. (You'll have to delete your Podfile.lock though)
