### ISSUE TITLE
Flutter web wasm

### ISSUE THREAD

**Issue by SerdarYildiz06** [miguelpruivo/flutter_file_picker#1516]
When I try to make build with flutter build web --wasm it giving error "Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html';"

<img width="1171" alt="Screenshot 2024-05-21 at 13 28 59" src="https://github.com/miguelpruivo/flutter_file_picker/assets/72278145/078d682c-3608-460a-bc39-1a4b6af63828">

**Comment by navaronbracke** [comment]
We should switch to `dart:js_interop` instead of `dart:html`

**Comment by akshaybabloo** [comment]
This looks like it has been done - https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/_internal/file_picker_web.dart. Would there be a new release anytime soon?

**Comment by Brada-Groep** [comment]
Is there any update on this? This is the last package for us that is holding us back from switching to the wasm engine

**Comment by navaronbracke** [comment]
@akshaybabloo is correct, the package was made WASM compliant already. You should probably try to update to the latest version?

**Comment by Brada-Groep** [comment]
It takes issue with the file_picker_windows.dart:
../../AppData/Local/Pub/Cache/hosted/pub.dev/file_picker-8.0.7/lib/src/windows/file_picker_windows.dart:1:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';

**Comment by navaronbracke** [comment]
@Brada-Groep What Flutter version are you on? This works properly on Flutter 3.24, which is the latest stable.

There was a bug in Flutter 3.22 that broke the conditional export for `dart.library.ffi`, see https://github.com/flutter/flutter/issues/149984#issuecomment-2191014653

**Comment by Brada-Groep** [comment]
That was indeed the problem and it's fixed now. Thank you for your help and I'm sorry for wasting your time.

**Comment by navaronbracke** [comment]
No problem, thanks for confirming that this is fixed now.
