### ISSUE TITLE
Google rejects this picker library

### ISSUE THREAD

**Issue by jsy11** [miguelpruivo/flutter_file_picker#1517]
<img width="913" alt="sc 2024-05-23 at 3 31 53 PM" src="https://github.com/miguelpruivo/flutter_file_picker/assets/18429012/cec3afe6-f4a9-44d0-a9ef-35844f8e96f6">

Our use case involves allowing users to import their sheets from mobile device file storage or Google Drive using a file picker, so user can use the app with imported data.

However, Google Play rejected our app, stating that we are violating their policy.

Could you please advise on how we can better address this issue with this library?

Thanks for your help.

**Comment by navaronbracke** [comment]
You seem to be using the `MANAGE_EXTERNAL_STORAGE` permission in a way that is not allowed by the policy above.

`file_picker` does not declare this permission in its manifest, so this is coming from somewhere else. (different plugin or user code)

**Comment by rhogro** [comment]
@jsy11 managed to fix this? I have the exact same issue. I'm using the file picker to save a generated report as a .csv file. Without `MANAGE_EXTERNAL_STORAGE ` permission I get an PathAccesssException:
`Unhandled Exception: PathAccessException: Cannot open file, path = '/storage/emulated/0/1Cd/example.csv' (OS Error: Permission denied, errno = 13)`. 
And as well, my app got rejected from google play store for using this permission.
