### ISSUE TITLE
Crash app  when opening the gallary

### ISSUE THREAD

**Issue by buivanday** [miguelpruivo/flutter_file_picker#152]
I tried the example but it crashed when I opened the gallery
I use xiaomi note 7 android 9 flutter 1.10 

> I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(com.sangcomz.fishbun.adapter.view.AlbumListAdapter$ViewHolder, int) (AlbumListAdapter.java:56)
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) (AlbumListAdapter.java:25)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, java.util.List) (RecyclerView.java:6781)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) (RecyclerView.java:6823)
I/ple.imagepicke(16565):   at boolean androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, int, long) (RecyclerView.java:5752)
I/ple.imagepicke(16565):   at androidx.recyclerview.widget.RecyclerView$ViewHolder androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(int, boolean, long) (RecyclerView.java:6019)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int, boolean) (RecyclerView.java:5858)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int) (RecyclerView.java:5854)
I/ple.imagepicke(16565): Rejecting re-init on previously-failed class java.lang.Class<com.bumptech.glide.util.CachedHashCodeArrayMap>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.image.impl.GlideAdapter.loadImage(android.widget.ImageView, android.net.Uri) (GlideAdapter.java:17)
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(com.sangcomz.fishbun.adapter.view.AlbumListAdapter$ViewHolder, int) (AlbumListAdapter.java:56)
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) (AlbumListAdapter.java:25)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, java.util.List) (RecyclerView.java:6781)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) (RecyclerView.java:6823)
I/ple.imagepicke(16565):   at boolean androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, int, long) (RecyclerView.java:5752)
I/ple.imagepicke(16565):   at androidx.recyclerview.widget.RecyclerView$ViewHolder androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(int, boolean, long) (RecyclerView.java:6019)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int, boolean) (RecyclerView.java:5858)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int) (RecyclerView.java:5854)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(androidx.recyclerview.widget.RecyclerView$Recycler) (LinearLayoutManager.java:2230)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.GridLayoutManager.layoutChunk(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.RecyclerView$State, androidx.recyclerview.widget.LinearLayoutManager$LayoutState, androidx.recyclerview.widget.LinearLayoutManager$LayoutChunkResult) (GridLayoutManager.java:557)
I/ple.imagepicke(16565):   at int androidx.recyclerview.widget.LinearLayoutManager.fill(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.LinearLayoutManager$LayoutState, androidx.recyclerview.widget.RecyclerView$State, boolean) (LinearLayoutManager.java:1517)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.RecyclerView$State) (LinearLayoutManager.java:612)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.RecyclerView$State) (GridLayoutManager.java:171)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2() (RecyclerView.java:3924)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView.dispatchLayout() (RecyclerView.java:3641)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView.onLayout(boolean, int, int, int, int) (RecyclerView.java:4194)
I/ple.imagepicke(16565):   at void android.view.View.layout(int, int, int, int) (View.java:20699)
I/ple.imagepicke(16565):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6198)
I/ple.imagepicke(16565):   at void com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, int) (HeaderScrollingViewBehavior.java:142)
I/ple.imagepicke(16565):   at boolean com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, int) (ViewOffsetBehavior.java:41)
I/ple.imagepicke(16565):   at boolean com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, int) (AppBarLayout.java:1556)
I/ple.imagepicke(16565):   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:323)
I/ple.imagepicke(16565):   at void com.android.internal.policy.DecorView.onLayout(boolean, int, int, int, int) (DecorView.java:757)
I/ple.imagepicke(16565):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/ple.imagepicke(16565):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int) (RecyclerView.java:5854)
I/ple.imagepicke(16565):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6198)
I/ple.imagepicke(16565):   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:261)
I/ple.imagepicke(16565):   at void android.view.View.layout(int, int, int, int) (View.java:20699)
I/ple.imagepicke(16565): Rejecting re-init on previously-failed class java.lang.Class<com.bumptech.glide.util.CachedHashCodeArrayMap>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.image.impl.GlideAdapter.loadImage(android.widget.ImageView, android.net.Uri) (GlideAdapter.java:17)
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(com.sangcomz.fishbun.adapter.view.AlbumListAdapter$ViewHolder, int) (AlbumListAdapter.java:56)
I/ple.imagepicke(16565):   at void com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) (AlbumListAdapter.java:25)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, java.util.List) (RecyclerView.java:6781)
I/ple.imagepicke(16565):   at void androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) (RecyclerView.java:6823)
I/ple.imagepicke(16565):   at boolean androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, int, long) (RecyclerView.java:5752)
I/ple.imagepicke(16565):   at androidx.recyclerview.widget.RecyclerView$ViewHolder androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(int, boolean, long) (RecyclerView.java:6019)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int, boolean) (RecyclerView.java:5858)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int) (RecyclerView.java:5854)
I/ple.imagepicke(16565):   at android.view.View androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(androidx.recyclerview.widget.RecyclerView$Recycler) (LinearLayoutManager.java:2230)
I/Process (16565): Sending signal. PID: 16565 SIG: 9

>

**Comment by miguelpruivo** [comment]
@buivanday hi, could you please try on a different device? Thank you.

**Comment by miguelpruivo** [comment]
@buivanday any news on this?

**Comment by miguelpruivo** [comment]
Since there's no further details on this, I'll assume it has been fixed. Feel free to re-open if you still experience any issue with this.

Thank you.
