### ISSUE TITLE
no file return on android

### ISSUE THREAD

**Issue by hhcme** [miguelpruivo/flutter_file_picker#1520]
After upgrading the version, it will be file_picker: ^ 8.0.3. On Android, the file selector can be called, but it cannot receive files and keeps returning null

**Comment by sneurlax** [comment]
See https://github.com/miguelpruivo/flutter_file_picker/pull/1336#issuecomment-2146478150

Use https://github.com/muttsu-623/flutter_file_picker or https://github.com/cypherstack/flutter_file_picker if you need Windows support
