### ISSUE TITLE
pickFile()  returning null even when file is selected from device

### ISSUE THREAD

**Issue by KartikGavhale** [miguelpruivo/flutter_file_picker#1525]
**bug discription**
The file_picker is working fine with almost all devices but i have a device Redmi 10A MIUI 12.5.18 global android version 11, here the when i click button the file selector is loaded but when i select the file , the pickFile() return null.

**Platform**

- [Android

**Platform OS version**
Android 11

**Code to pick file**

FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      withData: true,
      allowedExtensions: ['pdf','jpg','png'],
    );
    print('resultPDF ${result}');
    if (result != null) {
      File file = File(result.files.single.path!);
      int sizeInBytes = file.lengthSync();
      double sizeInMb = sizeInBytes / (1024 * 1024);
      if(sizeInMb<=10) {
        return file;
      }else{
        CommWidget.showWhiteToast("Please select filesize upto 10mb.");
        return null;
      }
    } else {
      CommWidget.showWhiteToast("File not selected");
      return null;
    }

**Flutter Version details**
Flutter 3.22

**Comment by dipu0** [comment]
did you solved this problem ??@kar

> **bug discription** The file_picker is working fine with almost all devices but i have a device Redmi 10A MIUI 12.5.18 global android version 11, here the when i click button the file selector is loaded but when i select the file , the pickFile() return null.
> 
> **Platform**
> 
> * [Android
> 
> **Platform OS version** Android 11
> 
> **Code to pick file**
> 
> FilePickerResult? result = await FilePicker.platform.pickFiles( type: FileType.custom, withData: true, allowedExtensions: ['pdf','jpg','png'], ); print('resultPDF ${result}'); if (result != null) { File file = File(result.files.single.path!); int sizeInBytes = file.lengthSync(); double sizeInMb = sizeInBytes / (1024 * 1024); if(sizeInMb<=10) { return file; }else{ CommWidget.showWhiteToast("Please select filesize upto 10mb."); return null; } } else { CommWidget.showWhiteToast("File not selected"); return null; }
> 
> **Flutter Version details** Flutter 3.22

did you solved this??

**Comment by KartikGavhale** [comment]
> did you solved this problem ??@kar
> 
> > **bug discription** The file_picker is working fine with almost all devices but i have a device Redmi 10A MIUI 12.5.18 global android version 11, here the when i click button the file selector is loaded but when i select the file , the pickFile() return null.
> > **Platform**
> > 
> > * [Android
> > 
> > **Platform OS version** Android 11
> > **Code to pick file**
> > FilePickerResult? result = await FilePicker.platform.pickFiles( type: FileType.custom, withData: true, allowedExtensions: ['pdf','jpg','png'], ); print('resultPDF ${result}'); if (result != null) { File file = File(result.files.single.path!); int sizeInBytes = file.lengthSync(); double sizeInMb = sizeInBytes / (1024 * 1024); if(sizeInMb<=10) { return file; }else{ CommWidget.showWhiteToast("Please select filesize upto 10mb."); return null; } } else { CommWidget.showWhiteToast("File not selected"); return null; }
> > **Flutter Version details** Flutter 3.22
> 
> did you solved this??

 No I did not find any solution as such.
