### ISSUE TITLE
Increase minSdk to 19 for Android in order to allow builds

### ISSUE THREAD

**Issue by basvdijk** [miguelpruivo/flutter_file_picker#1528]
I got the error 

```
Task :file_picker:processDebugAndroidTestManifest FAILED

/build/file_picker/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest3410324268530054149.xml:5:5-74 Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_plugin_android_lifecycle] //build/flutter_plugin_android_lifecycle/intermediates/merged_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="io.flutter.plugins.flutter_plugin_android_lifecycle" to force usage (may lead to runtime failures)
```

On https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/build.gradle#L28 the `minSdkVersion` is `16`

Please increase it to at least `19`

When building in Flutter it gives:

```
uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_plugin_android_lifecycle] 
```

- Api 16 is from October 2012 - https://developer.android.com/tools/releases/platforms#4.1
- Api 19 from December 2013 - https://developer.android.com/tools/releases/platforms#4.4

**Comment by BalasubramaniSundaram95** [comment]
![Uploading Screenshot 2024-06-21 at 12.27.45 AM.png…]()

**Comment by BalasubramaniSundaram95** [comment]
<img width="691" alt="Screenshot 2024-06-21 at 12 31 46 AM" src="https://github.com/miguelpruivo/flutter_file_picker/assets/69121505/d851d128-1b9c-472f-80dd-a741f59d89b3">
