### ISSUE TITLE
Create thumbnail for a selected file

### ISSUE THREAD

**Issue by DavidGailmannVW** [miguelpruivo/flutter_file_picker#1535]
The package already makes working with documents much easier. I am still missing the ability to create a thumbnail for the document I selected. This would give users a preview of the document. This feature could improve user experience on an application.

**Comment by vidhi002** [comment]
> The package already makes working with documents much easier. I am still missing the ability to create a thumbnail for the do

much needed

**Comment by shubhamsinghshubham777** [comment]
> The package already makes working with documents much easier. I am still missing the ability to create a thumbnail for the document I selected. This would give users a preview of the document. This feature could improve user experience on an application.

+1 - Much needed! What are your thoughts on this @miguelpruivo?
