### ISSUE TITLE
Pick images from iOS gallery?

### ISSUE THREAD

**Issue by bitbendergames** [miguelpruivo/flutter_file_picker#154]
Hello,

I'm using your package for picking multiple images and processing them. On Android I can pick images from the gallery of pictures that I've taken with the phone camera easily using your package. On iOS I am instead presented with an empty view. Any idea as to why this behaves like that?

Regards,

Bit

**Comment by miguelpruivo** [comment]
Hi, are you using `FileType.IMAGE`?

**Comment by bitbendergames** [comment]
I'm using this call:

var paths = await FilePicker.getMultiFile(type: FileType.IMAGE);

Maybe I'm mistaken on the skope of this package though. I would like to pick files from the image gallery which holds the images from the camera app. I am using this package instead of multi_image_picker because the latter crashes on my target device. Not sure if it's my fault or if this package is capable of being used for that purpose.

**Comment by LachlanGrant** [comment]
I'm having the same issue, I get taken to the iOS File browser, no option to select from photo library

**Comment by miguelpruivo** [comment]
Would you mind to record a sample of that and post it here? What iOS version are you running on? Yes, you do need permissions to access the files (in your plist) just make sure you’ve added it by following the [instructions for the iOS setup](https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#--ios) on the wiki.

**Comment by bitbendergames** [comment]
I have that behaviour on my device, but also in the simulator on Mac simulating a iPhone 11 Pro Max - 13.0. Flutter is on Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.4 18E226. I do have the NSPhotoLibraryUsageDescription key added to the Info.plist. Here's a quick GIF:

http://www.giphy.com/gifs/SATQqi7st1rXGvvmIX

The Files button I click first invokes this (flutter_file_picker) package's method, whereas the Images button invokes the according method of the multi_image_picker package.

**Comment by miguelpruivo** [comment]
@bitbendergames that shouldn't happen if you use `FileType.IMAGE`. It should open the gallery instead of the Files app. Can you show me how are you calling the picker?

**Comment by bitbendergames** [comment]
That's how I do it:
var paths = await FilePicker.getMultiFile(type: FileType.IMAGE );

**Comment by miguelpruivo** [comment]
@bitbendergames, you must use `getSingleFile` instead and it will open the gallery. Multi picking from gallery isn’t currently supported with this plugin, sorry. 😞

**Comment by bitbendergames** [comment]
Bummer. Is this something you have on the roadmap to add in the future, or are there reasons that make it difficult to add? While this isn't supported, you might want to add some error or warning output to notify developer about it. Could have spared me a bit of time, and others potentially as well

**Comment by miguelpruivo** [comment]
@bitbendergames well, it is actually pointed out in [the docs](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#filepickergetmultifilepath). I can't display an error because when using multi file picker the user may indeed want to multi pick files from a cloud service, this is, if you have some pictures in a cloud service such as iCloud, those would appear there and you'd be able to multi pick them.

It's just because I hadn't the time yet to implement it in both platforms and there are a few other features waiting as well, but definitely it can be added in the future.

**Comment by shlima** [comment]
waiting for this a lot !
