### ISSUE TITLE
Browse Windows Share Folder

### ISSUE THREAD

**Issue by EricPreventa** [miguelpruivo/flutter_file_picker#155]
Any chance this is able to pull in files from a Windows Share folder? Few iOS apps have this capability of being able to connect to a folder.

**Comment by miguelpruivo** [comment]
Hi, could you show an example of what you’re talking about? Because I’ve no idea. 😞 thank you.

**Comment by EricPreventa** [comment]
This link and the following images hopefully will make it more clear. I believe you have a lot of the capabilities already in there, just need to somehow tie it in with this. 

https://www.maketecheasier.com/access-network-files-from-ipad/

![](https://www.maketecheasier.com/assets/uploads/2018/07/access-network-files-from-your-iPad-2.png)

![](https://www.maketecheasier.com/assets/uploads/2018/07/access-network-files-from-your-iPad-3.png)

**Comment by EricPreventa** [comment]
https://github.com/amosavian/AMSMB2
https://github.com/shaojiankui/samba-iOS

@miguelpruivo These native iOS packages (and more) already do what I'm looking for. Just hoping it can be baked into your amazing package. Will be more than happy to help out as much as I can too.

**Comment by miguelpruivo** [comment]
@EricPreventa I don't have much time currently to work on this suggestion, but feel free to issue a PR if you manage to add support for this on the plugin, it would be great, even more if it can be handy for you or anyone that want to use such feature.

Thank you.

**Comment by miguelpruivo** [comment]
I'm closing this as I don't have plans in a near future to support this. But like I said, feel free to issue a PR with your own implementation (and reopen this, if so). 

Thank you!
