### ISSUE TITLE
Unable to pick files with custom or any file type on Android 14

### ISSUE THREAD

**Issue by stan-at-work** [miguelpruivo/flutter_file_picker#1551]
Duplicate of https://github.com/miguelpruivo/flutter_file_picker/issues/1404.

Because its getting flagged as stale

**Comment by AmitBhandari7777** [comment]
var showTypeSelector = true;

     
        customTypeViewerBuilder: (types) {
          return types[0];
        },
        typeSelectors: [
          TypeSelector(
            type: FileType.media,
            selector: Visibility(
              visible: showTypeSelector,
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.cloud_upload_outlined,
                      size: 100,
                      color: Colors.grey.shade400,
                    ),
                    const Text(
                      "Upload media",
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
        onChanged: (value) {
          setState(() {
            showTypeSelector = value!.isEmpty;
          });
        },
        
        This is my current solution.
        I hope it helps.
