### ISSUE TITLE
getDirectoryPath() succeeding but cannot list directory contents

### ISSUE THREAD

**Issue by rohinton-collins** [miguelpruivo/flutter_file_picker#1552]
**The Problem**
Calling getDirectoryPath() will invoke a system Folder Picker, and will even ask the user for permission for access to the selected folder. But the returned path cannot be used with file:io to list directory contents or read files in Android 12 and up where Scoped Storage is now mandatory. Directory listing and reading files is possible on Android versions prior to Android 12 if the **requestLegacyExternalStorage** attribute is used in the *build.gradle* file.

**The Solution**
I have a fix for this. I have implemented a method channel which uses the Scoped Storage API to:
- select a folder and acquire permissions for listing/reading
- get the subdirectories in a given directory
- get the files in a given directory
- get the file bytes as 1Mb chunks which can be streamed for a particular file

The API does not use paths but instead uses content URIs which can be converted to Strings when passed back to the Flutter layer (for subsequent calls across the method channel).

I have this working on Android 9-14 and have removed the **requestLegacyExternalStorage** attribute given that I am now using the Scoped Storage API for this functionality.

If anyone needs the code please send a message here. If I get time and there is a call for it I will submit a PR to this repository with the code which supports the above functionality.

**Comment by rohinton-collins** [comment]
According to ChatGPT and this aligns with about 1 day of research by myself:
![image](https://github.com/user-attachments/assets/ca5b4365-e80b-4ca4-b4e0-260b187cbb1d)
![image](https://github.com/user-attachments/assets/62825db1-cb82-48d1-adc7-8f033a83f212)

**Comment by rohintonc** [comment]
Related issue on iOS: https://github.com/miguelpruivo/flutter_file_picker/issues/1568

**Comment by Fallenhh** [comment]
Hi @rohinton-collins , I am developing an app for sharing files. Sadly getDirectoryPath() does not work the way we expected, only files owns by the app can be accessed although the full permission for the folder is asked. Your code would be helpful to us

**Comment by rohintonc** [comment]
@Fallenhh Let me know if you want the Android or iOS code (or both). Email me at rohinton.collins@idz.com.

**Comment by azeem-swr** [comment]
Hi, @rohintonc, currently facing the same issue, thanks a lot for the code! Do you by any chance have a fork for this packages with this functionality so its a bit easier and cleaner to use? Especially because I want to use this in quite a few projects. I would try doing it myself but I'm not really that familiar with Kotlin. Thanks either way!

**Comment by rohintonc** [comment]
@azeem-swr Unfortunately not. However, I am also not a Kotlin developer, but didn't have much problem integrating this solution. Good luck.

**Comment by Bai-Jinlin** [comment]
maybe you need to use the permission_handler package to request permissions,just like this.
```dart
import 'package:permission_handler/permission_handler.dart';
if (await Permission.manageExternalStorage.request().isDenied) {
    return;
}
// file operation
```
and put `<uses-permission android:name=“android.permission.MANAGE_EXTERNAL_STORAGE” />` into AndroidManifest.xm
