### ISSUE TITLE
Missing file extenstion

### ISSUE THREAD

**Issue by bmelnychuk** [miguelpruivo/flutter_file_picker#156]
When I try to pick multiple files from google photos on android I always get this as the path to the file. 
`/data/user/0/<APP_ID>/cache/65880`
As you can see there is no extension. In my case, I want to work with all possible files so I don't limit the selection by file type or extension. Ideally, I would like to know what kind of file is selected. 
What would you suggest in this case, 
Thanks,

**Comment by miguelpruivo** [comment]
Hi @bmelnychuk this is the normal behavior from Google Photos file paths. Because they are basically remote pictures with no name associated, they're just cached temporary with a random number as name and no extension, but I suppose it's same to assume that they're JPG encoded.

**Comment by bmelnychuk** [comment]
But how do I know selected files are coming from google photos, what is other cloud providers have the same behavior?
Can I assume that every file that has no extension is the image?

**Comment by miguelpruivo** [comment]
@bmelnychuk just select it normally, having random numbers as the name shouldn't have any impact to access the files.

**Comment by aravindhkumar23** [comment]
@bmelnychuk I am also facing the same situation, I am making comparisons by file format like jpg, mp4, pdf to render the preview frame of selected files. If I load video or pdf file in image view then it results in error. @miguelpruivo any work around or solution to achieve this?
