### ISSUE TITLE
The file picker in Android 14 is not working and is prompting for memory access permission. This issue occurs in an application that was previously running without problems.

### ISSUE THREAD

**Issue by alok511** [miguelpruivo/flutter_file_picker#1560]
Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.

**Comment by gnprice** [comment]
The issue with that error message is tracked already as #1555.

The issue title sounds like a different issue. Perhaps #1559? Quoting the error message would help.

**Comment by aptexd** [comment]
I also have the same confusion, the same code, I can read the file on Android 13, but I can't get it on Android 14
