### ISSUE TITLE
File_picker is not working for iOS

### ISSUE THREAD

**Issue by roja321** [miguelpruivo/flutter_file_picker#1562]
I am using File_picker : 6.1.1, initially it was working for android as well as iOS but since 2 months it's not working for iOS. please give me any solution.

And I used File_picker: 4.6.1 , its working for iOS but for android it works till android version 12, not for android version 14, Please give me any suggetion.

**Comment by gnprice** [comment]
The current version is 8.0.6. Do the problems reproduce on that version?

Then in any case more details about what happens when it doesn't work will be needed in order to make it possible for someone to help resolve the issue.

**Comment by gnprice** [comment]
@Zelkreps those warning messages look like #1555, so let's continue discussion of them there.

**Comment by Zelkreps** [comment]
> @Zelkreps those warning messages look like #1555, so let's continue discussion of them there.

I already figured it out, and it wasn't anyone's fault but mine. Somehow, mysteriously, flutter on my development Mac was upgraded from the stable version to the development version (you can see it in the flutter doctor dump), but I didn't notice it before, so I apologize. Everything is working and thanks for the quick response! :)

**Comment by orouabdoul** [comment]
j'ai eu un probleme voici Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`. j'ai besoin d'aide

**Comment by VhiktorBrown** [comment]
> j'ai eu un probleme voici Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation. Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.
> 
> Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation. Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.
> 
> Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation. Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`. j'ai besoin d'aide

I am experiencing this issue too.

**Comment by alzihadi** [comment]
> > j'ai eu un probleme voici Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation. Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.
> > Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation. Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.
> > Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation. Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`. j'ai besoin d'aide
> 
> I am experiencing this issue too.

have you found a workaround?
