### ISSUE TITLE
Storage permission issue in Android 13 and 13 +

### ISSUE THREAD

**Issue by UmerAbbasi1515** [miguelpruivo/flutter_file_picker#1563]
When trying to pick the file  I am getting this exception 

PlatformException(read_external_storage_denied, User did not allowed reading external storage, null, null)

**Comment by PriyankP99** [comment]
I'm facing same issue with android 14

**Comment by UmerAbbasi1515** [comment]
@PriyankP99 plz use latest version of package that will work for you
