### ISSUE TITLE
Please use released web library version 1.0.0

### ISSUE THREAD

**Issue by countfloyd** [miguelpruivo/flutter_file_picker#1571]
Flutter web library has released a stable version 1.0.0. file_picker is holding me back from using it in my project.

Thanks!

**Comment by nitroplr** [comment]
This would be nice since we can't try out wasm without web 1.0.0

**Comment by sgehrman** [comment]
So annoying.  update your packages!!!!

**Comment by ifuterman** [comment]
This is becoming a real problem. It is impossible to update other packages.

**Comment by navaronbracke** [comment]
I will be addressing this issue today, unless someone else wishes to open a PR to fix it.
