### ISSUE TITLE
ios not recognize file_picker lib

### ISSUE THREAD

**Issue by rashedasaad** [miguelpruivo/flutter_file_picker#1576]
![filepicker](https://github.com/user-attachments/assets/a94dd977-f59f-4dc1-b184-9c61f7beeea4)
I'm using file_picker 8.0.7 verion, I tried fluttet pub clean and then pub get but it's still not working

**Comment by miguelpruivo** [comment]
This is likely an issue with some cache within your project. I suggest to remove your pub cache + derived data, and fetch the package again.
