### ISSUE TITLE
Suggest adding support for the “m4a” format.

### ISSUE THREAD

**Issue by siyangstar** [miguelpruivo/flutter_file_picker#1583]
FileType.audio:
        return 'Audios (*.aac,*.midi,*.mp3,*.ogg,*.wav)\x00*.aac;*.midi;*.mp3;*.ogg;*.wav\x00\x00';

didn't support "m4a", which is a kind of MPEG4 audio. Suggest adding support for the m4a format.

**Comment by miguelpruivo** [comment]
Please, free feel to add it in a PR. Thanks!
