### ISSUE TITLE
FilePicker.platform.pickFiles with FileType.custom does not allow picking filetype

### ISSUE THREAD

**Issue by auradigitaldev** [miguelpruivo/flutter_file_picker#1585]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 14

**How are you picking?**
```
FilePicker.platform.pickFiles(
      allowedExtensions: ['csv'],
      type: FileType.custom,
      allowMultiple: false,
    );
```

**Details to reproduce the issue**
- Use the above code snippet to pick CSV
- Navigate to the user's Google Drive or "Downloads" in the file picker side menu
- Observe that CSV files cannot be picked

**Error Log**
N/A

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
```
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.3 on channel stable at /Users/yuzhshen/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (6 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
```

**Additional context**
Because a file cannot be picked from "Downloads" but can be picked from "Pixel 6a" -> "Download" (this is the same folder with the same contents), I wonder if this is some permission error.

**Comment by miguelpruivo** [comment]
I think this is a dup of #1357.

**Comment by auradigitaldev** [comment]
Is there somewhere that lists the supported file filters? I thought the custom filter was intended to allow clients to specify arbitrary file extensions?
