### ISSUE TITLE
Version solving faile

### ISSUE THREAD

**Issue by skgaurav-web** [miguelpruivo/flutter_file_picker#1586]
Because file_picker >=8.1.0 depends on web ^1.0.0 and firebase_auth_web >=5.10.0 depends on web ^0.5.1, file_picker >=8.1.0 is incompatible with firebase_auth_web >=5.10.0.
And because firebase_auth >=5.1.3 depends on firebase_auth_web ^5.12.5, file_picker >=8.1.0 is incompatible with firebase_auth >=5.1.3.
So, because eshop_multivendor depends on both firebase_auth ^5.1.4 and file_picker ^8.1.2, version solving failed.

**Comment by aliumac** [comment]
same issue with  the latest version of firebase_core_web 

file_picker >=8.1.0 is incompatible with firebase_core_web ^2.17.5

**Comment by IanVS** [comment]
I have a similar problem, and I'm sorry but I'm pretty new to flutter.  

```
Because file_picker >=8.0.1 <8.1.0 depends on web ^0.5.1 and every version of flutter_test from sdk depends on web 0.3.0, file_picker >=8.0.1 <8.1.0 is incompatible with flutter_test from sdk.
```

I'm using flutter 3.16.8 right now.  Is there a version compatibility matrix somewhere, showing which versions of this package are compatible with flutter versions?  Based on https://github.com/miguelpruivo/flutter_file_picker/blob/5ee480577803a2d1af5a9bd915834d1d6f913f78/pubspec.yaml, 8.0.6 should be compatible with my flutter, but there's no tag for 8.0.7, which is what I have installed (why is there no git tag?).  I wouldn't expect the flutter compat to change in a patch release, so I assume 8.0.7 should also be fine with my flutter version, but then the error above confuses me.  Any help you can give would be appreciated!

**Comment by navaronbracke** [comment]
@IanVS The changelog lists changes to the minimum Flutter/ Dart version.

https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#810 Indicates that version 8.1.0 requires Flutter 3.22.0 / Dart 3.4

https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#600 Indicates that file_picker v6 supports Flutter 3.7 or higher. So you'll have to stick with file_picker v7 or upgrade your Flutter version.

**Comment by IanVS** [comment]
Thanks @navaronbracke , but I was using 8.0.7, which is prior to 8.1.0, so shouldn't that support flutter 3.7 and higher?  Meaning my flutter of 3.16.8 should have been fine, right?

**Comment by navaronbracke** [comment]
That is correct, if you pin `file_picker: 8.0.7` that should be fine. Not pinning it would probably cause pub to pick 8.1.0, per semantic versioning? I don't think file_picker considers Flutter/Dart upgrades as breaking changes (flutter/packages doesn't do that either)

**Comment by IanVS** [comment]
Yes, I was pinning, you can see in the error message above, `file_picker >=8.0.1 <8.1.0 depends on web ^0.5.1...`, so I think that maybe due to those versions depending on a more recent version of `web` than flutter_test, maybe they require a newer version of flutter than specified in the changelog?  Like I said, I'm pretty new to flutter dev, but it seems like file_picker in this range only works with older versions of flutter so long as `flutter_test` is not used, right?

**Comment by navaronbracke** [comment]
Does upgrading to Flutter 3.19.0 work? I didn't immediately find the required Flutter version for package:web 0.5.1

**Comment by IanVS** [comment]
No flutter 3.19.0 doesn't work, due to:

```
The current Dart SDK version is 3.3.0.

Because file_picker >=8.0.6 <8.1.0 depends on win32 >=5.5.1 which requires SDK version >=3.4.0 <4.0.0, file_picker >=8.0.6 <8.1.0 is forbidden.
```

I'm getting the impression that dependency management with flutter is a bit of a nightmare, lol.  I'll keep upgrading flutter and other dependencies, and I'm sure eventually I can get it all to mesh up.

**Comment by MisaGu** [comment]
Is it a problem to upgrade the 'web' package to its latest version in the 'file_picker' lib? Why it hasn't been done so far, if on web it only supports pickFiles method?

**Comment by navaronbracke** [comment]
> Is it a problem to upgrade the 'web' package to its latest version in the 'file_picker' lib? Why it hasn't been done so far, if on web it only supports pickFiles method?

`file_picker` already uses the latest version of `package:web`
