### ISSUE TITLE
Privacy Manifest Missing for App Store Submission

### ISSUE THREAD

**Issue by andreesgarcia2013** [miguelpruivo/flutter_file_picker#1592]
When submitting an app to the Apple App Store that includes the “Frameworks/file_picker.framework/file_picker”, the following error is encountered:

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/file_picker.framework/file_picker”, which includes file_picker, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024

I am working with flutter 3.0.5 and file_picker version 3.0.0

Thank you for your attention to this matter.

**Comment by loganSims** [comment]
Any updates on this? Seems critical with the upcoming deadline.

> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/file_picker.framework/file_picker”, which includes file_picker, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. **Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file.** Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

**Comment by loganSims** [comment]
You should just need to update the package to version 8. See this issues https://github.com/miguelpruivo/flutter_file_picker/issues/1418

If you're stuck on version 3.0.0 for other reasons, I'm not sure how you would go about manually adding the manifest to the package.
