### ISSUE TITLE
Question: NEW Android Photo and Video Permissions policy

### ISSUE THREAD

**Issue by AlexMichels** [miguelpruivo/flutter_file_picker#1594]
Our App uses the permission_handler and file_picker to set a custom wallpaper background. I suddenly saw those news from Android.
Can we continue to use permission_handler and file_picker for our app? Anyone experience with switching the way photos are ulpoaded and stored?

We do not use READ_MEDIA_IMAGES or READ_MEDIA_VIDEO in the app. We check the permission with Permission.storage.request() for Android SdkInt < 33. From Android 33 onwards, no additional permissions are required. Presumably, READ_MEDIA access is only needed if you want to access media created by other apps—which has not been relevant for us so far. Is that correct?

Last October, Android introduced the Photo and Video Permissions policy to reduce the number of apps permitted to request broad photo/video permissions ([READ_MEDIA_IMAGES](https://notifications.google.com/g/p/ANiao5qu8PUH5WZ5PgLg9pZcfhxKSziEefw3oca2y-q9bM8OR-0IcjLGHjIlbMDeNUHJEwbv0PtM18dqCRdYFTJ2C-2lNR8sLJcHbRkJA47FTDqrGQtHwj7WP-IZ3Mt3HPFTjA5lDEZvTCv1vVGMfb0st_jfxX1GC3Hs5CDDHQybU9kgsNWFPTJ9uAcMw45zhgYzzHLxJLWO6UClkJGvgPscb5XOpGp00Xa7YyruDW1PGth9bjRO8THJjR8AJiti6nY_ytcqrcEm2KGPxCrKatrN7LDi) and [READ_MEDIA_VIDEO](https://notifications.google.com/g/p/ANiao5oE9JfI1hy1N8XrZ1FIwBTvNsL5tNRGEJNMFcrTBywIbk95jYx7ZnHyVgNQSGKbzQjfE91tDF3u8EuAye6qIXu6j2IyzNXpI9pcUZTPrxg5dWYfPr4UJnhyMC4d_-CqcdAr1FGqtxPTUAkWT7MYJrVS5C0Y1r2UFVi3NxYepvr1xx-b5dmzwt4wu6Gyi80D-zJSjtERvuIt62OwNKiCw5rqAz8dYX5s6y78zagsbgZRUUr7f3yUW1m4hXm_nzg8TDAqr9mR0VQAaLHZOvhcwrg)). Starting October 31, 2024, apps may only access photos and videos for purposes directly related to app functionality. Apps that have a one-time or infrequent need to access these files are requested to use a system picker, such as the Android [photo picker](https://notifications.google.com/g/p/ANiao5rGu9ExaCEM8M16S1ZhWkn5Jyjt2-7EvGw-fvU709XIgSILKYqyEl9Qx4IbPrgaa5gDHw3_wwNH_Z60vy11LjKWwDFfAdFIuvNUAtFhV0yM6GY9xXJzhsO9triaygLyetIkCbPsyaOODN0O8pHI8V5WvlqhnTATlpyczspndPs3yrpYKnZN4c9mkAR7lOiW7abofjRZogo-KrSRQzhrqMvOq8Xhqin9QAvyRxzVd_tZfU42LQ8LHtBRSUHmzOZftJbs). [Learn more](https://notifications.google.com/g/p/ANiao5rJx17cf8aOaCF4xS4DDxShkEwWcurAxKA4lb-fD7Ub-3zXGcXQSkFeaozRf9tw5JIt-OVzX8grUdckAcre0SWfsDEGoyCrkYkdgA_r78naphR3pgtjtF_BIx_wC60giGjZS5XIoAo4uO5U-Vm6uu-4Nyfck-DHEQ8bPdI-PFvL1NLOEba_K90FCRTvCAVE5umx29x5nt5JVtTOUV8rsoGlva0FUqBoGZPcrzweUXMjIYFc-Or3NKG0l1FtC0fJ1Qpxiw)
https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES
https://support.google.com/googleplay/android-developer/answer/14115180

**Comment by oriol-farrus-apo** [comment]
The deadline is 31 of October, this should be a pressing matter.

**Comment by Lilian-C** [comment]
Same issue here.

Btw, there is a self-service option to request an extension of the compliance deadline on the Play Store (to January 22, 2025).

**Comment by djobynight** [comment]
Is there a future Flutter package  planned to prevent these problems in the next fews weeks ? @AlexMichels What are you planning to do for the app you handle ?

**Comment by felipecosta-dev** [comment]
are there any update about this problem? my app got rejected for this

**Comment by Xezolpl** [comment]
For those facing policies issues, you can use package `image_picker` for picking photos/videos without declaring the `READ_MEDIA_IMAGES` & `READ_MEDIA_VIDEO` permissions.
