### ISSUE TITLE
FilePicker.platform.pickFiles  in iOS 18

### ISSUE THREAD

**Issue by PaniniA** [miguelpruivo/flutter_file_picker#1597]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [ ] Android
- iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

![Simulator Screenshot - iPhone 16 Pro - 2024-09-19 at 17 07 38](https://github.com/user-attachments/assets/0c1de636-179c-498d-92aa-77fd2410ab2a)

**Flutter Version details**
3.24.3

**Additional context**

**Comment by Dreamersoul** [comment]
I think I'm having the same issue, the poster doesn't mention. The picker appears behind the safe area and the whole app hangs.

**Comment by PhantomRay** [comment]
> I think I'm having the same issue, the poster doesn't mention. The picker appears behind the safe area and the whole app hangs. i found this https://github.com/flutter/flutter/issues/155401

Exactly the same thing.

**Comment by PaniniA** [comment]
> > > I think I'm having the same issue, the poster doesn't mention. The picker appears behind the safe area and the whole app hangs. i found this [flutter/flutter#155401](https://github.com/flutter/flutter/issues/155401)
> > 
> > 
> > Exactly the same thing.
> 
> Check if you excluded architecture is `arm64` or any plugin in your application (aka pods) Fixing that fixed my issue [flutter/flutter#79641 (comment)](https://github.com/flutter/flutter/issues/79641#issuecomment-2299412011)

If I delete arm64, I get the error 'framework 'Pods_Runner' not found'

**Comment by Dreamersoul** [comment]
> > > > I think I'm having the same issue, the poster doesn't mention. The picker appears behind the safe area and the whole app hangs. i found this [flutter/flutter#155401](https://github.com/flutter/flutter/issues/155401)
> 
> > > 
> 
> > > 
> 
> > > Exactly the same thing.
> 
> > 
> 
> > Check if you excluded architecture is `arm64` or any plugin in your application (aka pods) Fixing that fixed my issue [flutter/flutter#79641 (comment)](https://github.com/flutter/flutter/issues/79641#issuecomment-2299412011)
> 
> 
> 
> If I delete arm64, I get the error 'framework 'Pods_Runner' not found'

Don't delete it, find the packages that use that and upgrade them or replace them with other ones.

**Comment by PaniniA** [comment]
> > > > > I think I'm having the same issue, the poster doesn't mention. The picker appears behind the safe area and the whole app hangs. i found this [flutter/flutter#155401](https://github.com/flutter/flutter/issues/155401)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Exactly the same thing.
> > 
> > 
> > > 
> > 
> > 
> > > Check if you excluded architecture is `arm64` or any plugin in your application (aka pods) Fixing that fixed my issue [flutter/flutter#79641 (comment)](https://github.com/flutter/flutter/issues/79641#issuecomment-2299412011)
> > 
> > 
> > If I delete arm64, I get the error 'framework 'Pods_Runner' not found'
> 
> Don't delete it, find the packages that use that and upgrade them or replace them with other ones.

I don't have a better alternative right now :(
![截屏2024-09-26 11 05 46](https://github.com/user-attachments/assets/0172f884-9b00-4b8f-a929-c3b7915322fd)

**Comment by EArminjon** [comment]
up

**Comment by PhantomRay** [comment]
I only see this issue in simulator.
