### ISSUE TITLE
Incorrect file extension when saving documents with the same name

### ISSUE THREAD

**Issue by mariagloin** [miguelpruivo/flutter_file_picker#1598]
**Describe the bug**
I encountered a bug while using the **saveFile()** method. When attempting to save two documents with the same name (for example, "Documents.pdf"), the second file is saved as Documents.pdf (1). This results in the file extension being incorrectly appended to the file name instead of preserving it.

It appears that the code in the package does not properly handle cases where a file with the same name already exists in the directory. As a result, the Android filesystem automatically adds a number to the end of the filename to avoid conflicts, but this adjustment does not account for the file extension.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Details to reproduce the issue**
1. Save a file using the saveFile() method with the name "Documents.pdf".
2. Attempt to save another file in the same directory with the same name.
3. The second file is saved as Documents.pdf (1) rather than Documents (1).pdf.

**Environment**
- Flutter version: 3.24.1
- File Picker version: 8.1.2

Thank you in advance for looking into this issue!

**Comment by ChanLee90** [comment]
i have the same problem

**Comment by Nimo11** [comment]
Same problem here

**Comment by Vovanella95** [comment]
Issue is still actual. Do anybody have any workarounds?

**Comment by HankeKun** [comment]
> Issue is still actual. Do anybody have any workarounds?

Hey there,
I recently started using this package and noticed the same issue when saving the same file twice on the Android Emulator.

As a workaround, I’ve been passing a unique filename to the saveFile call from file_picker.
For example, **'Document.pdf'** becomes **'Document-[#b62a8].pdf'** or **'Document-2025-03-29-12-04-12.pdf'**.

Of course, this doesn’t actually solve the underlying issue, but it allows users to save the same file twice without having to manually rename it — and without running into problems when trying to open it.

Here’s the method I use. You only need one of the strings: uniqueKeyFilename or timestampFilename. Just a heads-up: if you're using timestampFilename, you’ll need the [intl package](https://pub.dev/packages/intl).
Also, if you want consistent behavior between Android and iOS, you can remove the Platform.isAndroid check.
```
  Future<void> saveFile({required String filename}) async {
    try {
      final String uniqueKeyFilename = filename.replaceFirstMapped(RegExp(r'\.(?=[^.]+$)'), (m) => '-${UniqueKey()}.');

      final timestamp = DateFormat('yyyy-MM-dd-HH-mm-ss').format(DateTime.now());
      final String timestampFilename = filename.replaceFirstMapped(RegExp(r'\.(?=[^.]+$)'), (m) => '-$timestamp.');

      await FilePicker.platform.saveFile(
        fileName: Platform.isAndroid ? timestampFilename : filename,
        bytes: response.bodyBytes,
      );
    } catch (e, s) {
      if (kDebugMode) print(e);
      debugPrintStack(stackTrace: s);
    }
  }
```

Hopefully this helps as a temporary workaround until the package — or the Android save dialog — provides a proper fix.
