### ISSUE TITLE
Support OneDrive, Mega, and others in saveFile

### ISSUE THREAD

**Issue by saif-ellafi** [miguelpruivo/flutter_file_picker#1601]
Hey all,

For some reason, `pickFiles` does show the integration to cloud services, like OneDrive, Google Drive, and Mega. The "Open From" system dialog is very complete and comprehensive and can bring files from literally anywhere.

However, for `saveFile` in Android, I only get the option to store in my local storage, or in Google Drive, but none of the other cloud providers. Not sure why is this?

![image](https://github.com/user-attachments/assets/d81a839f-5329-405e-92ff-57927801dbc6)

Thanks!

**Comment by darielkurt** [comment]
@saif-ellafi do you have any updates about this? my problem now is the same but with the `pickFiles()`
