### ISSUE TITLE
Even on macOS with Simplified Chinese language settings, the file selection dialog is still in English.

### ISSUE THREAD

**Issue by MCDFsteve** [miguelpruivo/flutter_file_picker#1605]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/b4e3d47d-d124-4d87-8665-0fcad0e99851">
I'm not sure if this is a bug or if I need to configure the default language of the software somewhere (the default in the Info.plist is set to $(DEVELOPMENT_LANGUAGE)).

**Comment by MCDFsteve** [comment]
The normal behavior should be like this.
<img width="920" alt="image" src="https://github.com/user-attachments/assets/90c37ea4-1b86-4d17-9114-8ff5a3cee4be">

**Comment by lonelam** [comment]
Any progress?

**Comment by MCDFsteve** [comment]
> Any progress?

可以通过xcode配置项目为简体中文来让访达界面变成中文

**Comment by lonelam** [comment]
> > Any progress?
> 
> 可以通过xcode配置项目为简体中文来让访达界面变成中文

可以，尝试中，感谢。
