### ISSUE TITLE
README/pub.dev front page MUST mention that files are ALWAYS cached on Android

### ISSUE THREAD

**Issue by dattasid** [miguelpruivo/flutter_file_picker#1606]
# Action item

The documentation main page must make developers targeting Android aware that

1. All picked files are cached in temporary storage.
2. The app must implement cache management (display cache usage to user, clear cache based on some criteria). Otherwise they risk making users very angry.

# Gap in documentation

Nowhere in file_picker documentation is it mentioned that files will be cached on Android. I just happened to notice a log statement . Then I checked the cache for the media app I am building and sure enough, I was using 1GB of cache for no good reason. I was storing multiple copies of the same files that I was using for testing.

The issue is I would have greatly annoyed users, when they found the limited space on their devices rapidly dwindling. All because my app was building a pointless copy of their entire media library.

# Root Cause

In FileUtils.java , openFileStream will always create a cached copy of the file.

I can see the reason why. It works around many corner cases. Remote URI, additional permissions for accessing content URIs as files, so many issues can be easily resolved by making a quick cache of the file.

Except, without any kind of cache management, this is a dangerous thing to do. Even if the files are small, the cache might eventually become big. With media files etc, the cache will become very big very fast.

Since many developers are not even aware that this is happening, they dont even know they might need to manage the cache, or at a minimum tell the users to clear the cache if they are having space issues.

Also, the user clearing cache indiscriminately will cause problems for many apps which allow users to resume playing the same file.

I see that this has been an issue for 4+ years so I dont suppose we can have a 'dont cache' option.

# Conclusion

Please make developers aware that files on Android will be cached and the app will need to account for this.

**Comment by MichalNemec** [comment]
We found out after two weeks of debugging (more functionality in app, so hard to pinpoint)
and not even this helped us `await FilePicker.platform.clearTemporaryFiles();`

We will now try `file_selector`.

**Comment by daveTheOldCoder** [comment]
>not even this helped us await FilePicker.platform.clearTemporaryFiles(); We will now try file_selector.

Can you explain why clearTemporaryFiles() did not help?

I'm also trying to decide between file_picker and file_selector.

**Comment by MichalNemec** [comment]
> Can you explain why clearTemporaryFiles() did not help?

 
It just did not delete temporary files. I was testing it couple weeks ago and it seems my impl. was wrong and it seems like its clearing files just ok.

**Comment by dattasid** [comment]
You can also clear the files from app info ... **as long as you know about the caching!**

I was using file picker to pick large media files. I then noticed the files would stop playing overnight, because OS would detect low disk space and delete the local copy.

Since I am picking large media files, I would really really love not making a copy. I am ok with taking some extra permissions.

But the biggest problem is, the library absolutely does not mention it will make a copy of the file and there is no way to disable it. It could have also given me the real URL in case I was able to use it. It does not.

**Comment by daveTheOldCoder** [comment]
file_selector doesn't seem to have a clearTemporaryFiles() method. Does it automatically clear cached files?

**Comment by MichalNemec** [comment]
file_selector behaves differently, for example on iOS it shows me modal of actual files instead of a gallery, also i believe it does not do any caching.
this library i think can work. If you read the files as stream, do what you must and at the last step call the clearing. It should for sure remove it. You can test it if you plug in real android device and then go to the app data, there should be cache folder, i dont remember it from top of my head. When you call the clear, it should be removed. On my end it worked when i tested it.

**Comment by dattasid** [comment]
There is also flutter_cache_manager . (Did not use it myself)
