### ISSUE TITLE
Popup missplaced with Pick file on Web on iOS 

### ISSUE THREAD

**Issue by bsolca** [miguelpruivo/flutter_file_picker#1612]
**Describe the bug**
On the flutter_file_picker example demo and everywhere else. When tapping on a button that is calling 
```dart
    final result = await FilePicker.platform.pickFiles();
```
Open either the popup at the top or at the bottom which has a bad user experience.

**Platform**

- [ ] Android
- [x] iOS opening on **Web Browser** _(Safari & Brave)_
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Screenshots and/or video**
![image](https://github.com/user-attachments/assets/0b73d95d-fccf-4633-b440-20b544ad3096)

**Additional context**
  file_picker: ^8.1.2
  iOS: 18.1
  Browser tested: Brave and Safari on mobile

**Comment by anthealb** [comment]
I was looking for a solution to this issue as well

**Comment by niklasbartsch** [comment]
I have the same problem. 
Sometimes it gets shown outside of the screen...
