### ISSUE TITLE
How can I implement remove icon on image after selecting it from flie picker in flutter?

### ISSUE THREAD

**Issue by Zeeshan0201** [miguelpruivo/flutter_file_picker#163]
@miguelpruivo There is any default function in this package by this I can remove a particular image from multiple file object? 
![Screenshot from 2019-10-23 18-18-49](https://user-images.githubusercontent.com/45591301/67394948-b7f10f80-f5c2-11e9-8de3-4c3d51c60460.png)

**Comment by miguelpruivo** [comment]
What do you mean @Zeeshan0201 ?

**Comment by Zeeshan0201** [comment]
@miguelpruivo means when I select Images from Multiple Path Function Of File Picker, I got the list of all the paths, then how can I remove a specific item from list on removing that image and show them as above...

**Comment by miguelpruivo** [comment]
@Zeeshan0201 those are Dart related questions and not of this plugin. Anyway, you just need to find which item do you want to remove and remove it from the `Map` of paths/files.
```
paths.removeWhere((name,path) => name == 'nameOfTheFileYouWantToRemove');
```
