### ISSUE TITLE
getMultiFilePath + IMAGE + iOS

### ISSUE THREAD

**Issue by duzenko** [miguelpruivo/flutter_file_picker#164]
**Describe the bug**
Multi file picker seems useless. See the attached screenshots:
- Android 'just works', opening photo view and allows multi-selection
- iOS + getFilePath also works as expected
- iOS + getMultiFilePath: no photos at all, and no idea what this screen is for

**Issue details**
1. Platform: iOS
2. OS version: 12.4.1
3. File type: IMAGE
4. Steps to reproduce: `    final filePaths = await FilePicker.getMultiFilePath(type: FileType.IMAGE);`

**Screenshots and/or video**
![Screenshot_20191024-160918](https://user-images.githubusercontent.com/1481807/67488783-1082e400-f679-11e9-9e2c-f936e85ab3b2.png)
![IMG_0034](https://user-images.githubusercontent.com/1481807/67488781-1082e400-f679-11e9-89cf-27632317e728.PNG)
![IMG_0033](https://user-images.githubusercontent.com/1481807/67488784-1082e400-f679-11e9-8338-6811af0e836e.PNG)

**Flutter Version details**
```
Antons-Mac:pavement a$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-UA)
    • Flutter version 1.9.1+hotfix.5 at /Applications/flutter
    • Framework revision 1aedbb1835 (7 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Anton Duzenko’s iPhone • f5ac03e3f30e483c6a46e73fc2f730b0319c0171 • ios • iOS 12.4.1
    • iPhone 11 Pro Max      • C6DC1A16-DC7D-4B20-A9CB-AE5C13E77542     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by miguelpruivo** [comment]
Hi @daveleenew that's not actually an issue. If you read the wiki in the multi file picking API you'll find the following:
```
Picking multiple paths from iOS gallery (image and video) aren't currently supported.
```
That is the Files app from iOS which in your case doesn't have any file because you aren't probably using it at all. Anyway, there's plans to add multi picking for iOS gallery as well in a near future.

Thank you.

**Comment by duzenko** [comment]
@miguelpruivo 
Sorry, I have to disagree with your approach here
If you don't allow multi selection then at least allow to select anything at all.

**Comment by miguelpruivo** [comment]
You can select anything you have within your Files folder @duzenko such as iCloud pictures, files, and so on. You can't select anything because you don't have nothing there, it's not a bug. Try to add something to your files app. If you want to use the gallery just use `FileType.IMAGE` instead if the target platform is iOS.

**Comment by duzenko** [comment]
But I am using FileType.IMAGE

**Comment by miguelpruivo** [comment]
@duzenko like I said, currently, with multi picking, FileType.IMAGE will let you pick multiple images from Files app only (on iOS).

**Comment by guit4eva** [comment]
Hey there, has there been any updates with this? Unfortunately it still doesn't seem to be working correctly on iOS :/

**Comment by miguelpruivo** [comment]
@guit4eva do you have files in your phone under files app? This may need an additional permission if so.

**Comment by guit4eva** [comment]
@miguelpruivo Yes, there are files under the Files app. I can only access images using getFile, not getMultiFile

**Comment by miguelpruivo** [comment]
@guit4eva I've been working on V2 integration (which is not immediate) with some refactoring on the Android side so this needs to come next on the pipeline. 

Sorry, the time has not been much lately. 😞

**Comment by guit4eva** [comment]
That will really be great if you could include the iOS part in the next release - the poor chaps with iPhones have to select one image at a time if they want to add media ha ha 🙂 Well done though on an excellent package, it looks like it is really helping a lot of people 👍🏼

**Comment by miguelpruivo** [comment]
@guit4eva thank you. I’ll definitely do so. Just need sometime to get it all done. There are other things such as multi extension filter that people have been asking for a while now too.

**Comment by duzenko** [comment]
> 
> 
> That will really be great if you could include the iOS part in the next release - the poor chaps with iPhones have to select one image at a time if they want to add media ha ha 🙂 Well done though on an excellent package, it looks like it is really helping a lot of people 👍🏼

Just use another plugin for this

**Comment by AndroidNils** [comment]
> > That will really be great if you could include the iOS part in the next release - the poor chaps with iPhones have to select one image at a time if they want to add media ha ha 🙂 Well done though on an excellent package, it looks like it is really helping a lot of people 👍🏼
> 
> Just use another plugin for this

Which one?

**Comment by duzenko** [comment]
> 
> 
> > > That will really be great if you could include the iOS part in the next release - the poor chaps with iPhones have to select one image at a time if they want to add media ha ha 🙂 Well done though on an excellent package, it looks like it is really helping a lot of people 👍🏼
> > 
> > 
> > Just use another plugin for this
> 
> Which one?

https://pub.dev/packages/multi_image_picker works for me

**Comment by guit4eva** [comment]
> > > > That will really be great if you could include the iOS part in the next release - the poor chaps with iPhones have to select one image at a time if they want to add media ha ha 🙂 Well done though on an excellent package, it looks like it is really helping a lot of people 👍🏼
> > > 
> > > 
> > > Just use another plugin for this
> > 
> > 
> > Which one?
> 
> https://pub.dev/packages/multi_image_picker works for me

Unfortunately this seems to have limitations with selecting which folder to scan for images
