### ISSUE TITLE
invalid pseudo-version: does not match version-control timestamp

### ISSUE THREAD

**Issue by daveleenew** [miguelpruivo/flutter_file_picker#165]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS)
Macos
2. OS version
3. File type (filter)
4. Steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.
github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1: invalid pseudo-version: does not match version-control timestamp (2019-04-09T00:40:39Z)
**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Hi @daveleenew that's not actually an issue. If you read the wiki in the multi file [picking API](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#filepickergetmultifilepath) you'll find the following:
```
Will let you select multiple files and retrieve its path at once. Optionally you can provide a fileExtension parameter to filter the allowed selectable files. Will return a Map<String,String> with the files name (key) and corresponding path (value) of all selected files. **Picking multiple paths from iOS gallery (image and video) aren't currently supported**.
```
That is the Files app from iOS which in your case doesn't have any file because you aren't probably using it at all. Anyway, there's plans to add multi picking for iOS gallery as well in a near future.

Thank you.

**Comment by daveleenew** [comment]
Hi @miguelpruivo i just use the library with macos . import (
	"github.com/go-flutter-desktop/go-flutter"
	"github.com/miguelpruivo/plugins_flutter_file_picker/go"
)

**Comment by miguelpruivo** [comment]
Hi @daveleenew, would you mind to `flutter clean` and try today? Just deployed an update on `go-flutter` for this [1.4.2+1](https://pub.dev/packages/file_picker#-changelog-tab-).

Thank you.

**Comment by miguelpruivo** [comment]
Since there's no further details on this, I'll assume that it has been solved for you. 

Feel free to re-open if you still experience any issue related to this.

Thank you.
