### ISSUE TITLE
Problem selecting file on Android 6

### ISSUE THREAD

**Issue by Jazzin** [miguelpruivo/flutter_file_picker#166]
I am having problems selecting a file on Android 6. I have a file that has a full path name of
/storage/emulated/0/Download/What2Do_2019_10_21-22:43:01.db
I can select the file correctly on phones & tablets running Android 8, but on an older phone running Android 6 the file path I get returned is
/storage/emulated/0/Download/What2Do_2019_10_21-22
It looks like it is being truncated at the colon. I am calling file picker with the following
                String filePath = await FilePicker.getFilePath(type: FileType.ANY);
The file name is shown correctly in the picker window and some of the file_picker debug shows this..

I/FilePicker(15217): [SingleFilePick] File URI:content://com.android.externalstorage.documents/document/primary%3ADownload%2FWhat2Do_2019_10_21-22%3A43%3A01.db
E/FilePickerUtils(15217): Getting for API 19 or abovecontent://com.android.externalstorage.documents/document/primary%3ADownload%2FWhat2Do_2019_10_21-22%3A43%3A01.db

Which looks like it has got the right name. Then something in the conversion to the path string has gone wrong.

Any idea how to fix this.

thanks

**Comment by miguelpruivo** [comment]
@Jazzin hi, thank you for reporting, despite that, does it work as it should when you try to open/modify the file? Because the name handling in some SDK's may be different and doesn't mean that the file itself won't work, even the name is not exactly the same.

**Comment by Jazzin** [comment]
Hi, thanks for getting back to me. The file name I get back from file_picker doesn't work. If I try and open the file it fails. If I change the name of the original file to /storage/emulated/0/Download/What2Do_2019_10_21.db then it works. So it looks like something is not translating the colon characters properly.

**Comment by miguelpruivo** [comment]
@Jazzin ok thank you. I’ll take a look to see what might have cause that.

**Comment by miguelpruivo** [comment]
@Jazzin I was looking into that but unfortunately I can't even create a file with a `:` neither on Mac nor on Android. Even if I force it somehow, it gets replaced by a `_` or `/` because the `:` is an invalid filename character (and that's probably the reason why it gets messed when parsing the file, because some uri schemes use `:`). 

This looks like an edge case and I'd still like to help you, but you'd have to provide me with a file with such name, if possible.

Thank you.

**Comment by Jazzin** [comment]
Hi, Thanks for having a look. I generated the file on Android using the esys_flutter_share plugin. (https://pub.dev/packages/esys_flutter_share) This didn't seem to mind me using a ":" in the file name and Android was happy to let me create it in the download directory. It also lets me create the file on google drive. Like this one https://drive.google.com/open?id=1-bV6EYoMBe7EJL-FMrJjgdKbj5cHswI5 

I agree this is a bit of an edge case and I will probably change the default file name I am using so it doesn't include the colons, but I'd rather not have to check the file name provided by a user.

**Comment by miguelpruivo** [comment]
@Jazzin just tried with it and even though I can get the file to keep the `:` in the name on my Google Drive folder (only on device), as soon as I copy/move it to the device storage, gets its `:` replaced with `_`. Picking from Google Drive with `:` works fine though.

To perfectly replicate your conditions (which are quite hard as you see 😄) I need to download the file with that name directly to my download folder. Could please share with me a WeeTransfer (or sort of) file with that name? It's very hard to keep it with that name as most of the time it will get replaced with a valid character.

**Comment by Jazzin** [comment]
As you say, it looks like it is quite difficult to get everything to pass on the file without changing the name. You can try this one.. https://we.tl/b-qHCwe8LYUC but is suspect you will have the same problem. I think I will just change my code so it doesn't use the colon. It was a bad idea anyway. If you can add some protection, that would be good. Thanks for looking.

**Comment by miguelpruivo** [comment]
Yes, you can be safe that most of the users won’t have files with that name and even though if they will, eventually it will get automatically renamed to something with a `_` instead. 

But I’ll keep looking into this on #172 which is the same problem but with another character. You can follow that on.

Thank you anyway for reporting, definitely it can result in an optimization.
