### ISSUE TITLE
 Will the web adapt to the future?

### ISSUE THREAD

**Issue by YourksChan** [miguelpruivo/flutter_file_picker#167]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS)
2. OS version
3. File type (filter)
4. Steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Hi @YourksChan, there is plans for web already. You can check the #99 for the requested features.

Thank you.
