### ISSUE TITLE
Want to add file directory selection

### ISSUE THREAD

**Issue by YourksChan** [miguelpruivo/flutter_file_picker#168]
I wanted to choose a folder, but I didn't find a method

**Comment by miguelpruivo** [comment]
@YourksChan this is not possible and I doubt it will because iOS doesn’t currently support this. Please see #99 before opening new feature requests that are already there.

Thank you.

**Comment by neckaros** [comment]
> @YourksChan this is not possible and I doubt it will because iOS doesn’t currently support this. Please see #99 before opening new feature requests that are already there.
> 
> Thank you.

I think it is now possible with https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories right?
