### ISSUE TITLE
Lo

### ISSUE THREAD

**Issue by kukvy** [miguelpruivo/flutter_file_picker#170]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS)
2. OS version
3. File type (filter)
4. Steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Sorry, you've just opened an issue without any description from you. Feel free to reopen if you have any details.

Thank you.
