### ISSUE TITLE
Hover run error

### ISSUE THREAD

**Issue by Murtuzakabul** [miguelpruivo/flutter_file_picker#174]
After updating to latest version of Go as well as latest version of File_picker, failed to execute Hover run.

**Issue details**
1. Platform - Desktop / Windows
2. OS - Windows 10
3. Steps to reproduce

- Create a new flutter project with flutter create
- Add hover 
- Add File picker plugin
- run it with "hover run"

**Error Log**
go: finding github.com/miguelpruivo/plugins_flutter_file_picker/go latest
verifying github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/go.mod: github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/go.mod: reading https://sum.golang.org/lookup/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1: 410 Gone
hover: Go build failed: exit status 1

**Screenshots and/or video**
![image](https://user-images.githubusercontent.com/17959034/68991995-1c825000-088b-11ea-90a4-adce0bc4a97c.png)

**Flutter Version details**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.4)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by miguelpruivo** [comment]
Hi @Murtuzakabul, would you mind to `flutter clean` and try today? Just deployed an update on `go-flutter` for this [1.4.2+1](https://pub.dev/packages/file_picker#-changelog-tab-).

Thank you.

**Comment by Murtuzakabul** [comment]
I'm doing it in a while. Actually I had downgraded version to make it run.
Let me update it again along with go version.

**Comment by miguelpruivo** [comment]
Ok just let me know if it fixed for you @Murtuzakabul and feel free to close this if so.

**Comment by Murtuzakabul** [comment]
Working perfectly now. Thanks.
