### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by duindain** [miguelpruivo/flutter_file_picker#179]
**Describe the bug**
Updated to latest version of plugin 1.4.3, flutter, android studio
Could not resolve all files for configuration ':file_picker:debugCompileClasspath'.

**Issue details**
1. Platform (Android/iOS)
Android
2. OS version
10 
3. File type (filter)
Error during debugging/starting the app no file type selected
4. Steps to reproduce
Just including the latest version and running start

**Error Log**
Please, post the _full_ console log of your issue, if applicable.
`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':file_picker:debugCompileClasspath'.
> Failed to transform file 'flutter.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
   > Failed to transform '/Users/miguelruivo/devtools/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=/Users/miguelruivo/devtools/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar, to=/home/myusername/.gradle/caches/transforms-1/files-1.1/flutter.jar/9afef581093e6e9f893ed802aa62bdd7/jetified-flutter.jar)'. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1`
**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/myusername/Software/Dev/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/myusername/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/myusername/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/myusername/Software/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!`

**Additional context**

Looks like its trying to run a transform on a local folder from your machine which doesn't exist elsewhere?
'/Users/miguelruivo/devtools/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar'

I've read of similiar issues in the past I tried adding mavenCentral() in 
```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}
```
But it didn't change anything

Any ideas?

**Comment by ac130kz** [comment]
Versions 1.4.2-3 fail for me as well. Version 1.4.0 builds just fine

Flutter dev channel v1.12.4

**Comment by mllyx** [comment]
file_picker 1.4.2+1 with flutter 1.9.1+hotfix.6 work for me.
but file_picker 1.4.3 not

**Comment by ismadev** [comment]
Same here.

file_picker 1.4.3 doesn't work.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':file_picker:debugCompileClasspath'.
> > Failed to transform file 'flutter.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
>    > Failed to transform 'C:\projects\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.4.3\android\Users\miguelruivo\devtools\flutter\bin\cache\artifacts\engine\android-arm64\flutter.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=C:\projects\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.4.3\android\Users\miguelruivo\devtools\flutter\bin\cache\artifacts\engine\android-arm64\flutter.jar, to=C:\Users\Ismael\.gradle\caches\transforms-1\files-1.1\flutter.jar\d282452929c47624e51badaa5a94d2ab\jetified-flutter.jar)'. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 21s

But file_picker 1.4.2+1 works fine.

**Comment by miguelpruivo** [comment]
Hi guys, sorry I’ve committed one dev dependency that I that I shouldn’t on the last version. I’ll remove it in a few minutes and let you know.

Thank you for reporting.

**Comment by miguelpruivo** [comment]
Hi guys, [1.4.3+1](https://pub.dev/packages/file_picker#1431) is now on pub.dev. Please make sure that you run a `flutter clean` before building again or explicitly make it `file_picker: 1.4.3+1` on your pubspec just to make sure that is picking the last version and let me know if it's working for you.

Were this happening on the example app only? Because I found that only the example app had a file checked into the version control that shouldn't (flutter_environment) so this shouldn't affect inclusions on user apps.

Thank you!

**Comment by MaikuB** [comment]
Had this issue as well but won't get to try 1.4.3+1 until tomorrow. This wasn't an issue that I saw happen with the example app but in our own app. Interestingly the issue wasn't there when the plugin was referenced via git or a path that points to a cloned repository.

**Comment by miguelpruivo** [comment]
@MaikuB thank you for the input. The only reference to a local engine (which is reported on the logs) was in the new `flutter_environment` file that I had on the example app (iOS folder). 

Did that happen on iOS builds or Android as well? Because I can't relate to anything else but let someone give it a try just to make sure it is working now.

**Comment by MaikuB** [comment]
Believe it was just on Android. Will confirm tomorrow

**Comment by miguelpruivo** [comment]
@MaikuB ok, just checked directly with the artifacts from `pub.dev` and version `1.4.3` has a dependency that prevents build on Android.

For those that experience this issue do a `flutter clean` and set the version in the pubspec.yaml to `file_picker: 1.4.3+1` and it should be all good now.

I'll leave this open until further reports that it's working as expected. Thank you all.

**Comment by duindain** [comment]
Thanks @miguelpruivo I've run flutter clean and changed the reference to 
`file_picker: ^1.4.3+1`
And it is compiling and running once more

Thanks for such a quick response too

Cheers

**Comment by miguelpruivo** [comment]
Glad that it worked @duindain. I thank you for reporting.

**Comment by MaikuB** [comment]
The fix worked for us as well
