### ISSUE TITLE
Not asking Permissions

### ISSUE THREAD

**Issue by Renatinaveen** [miguelpruivo/flutter_file_picker#183]
**Describe the bug**
In IOS it's not asking for permissions from user and it's not showing the permissions required even after adding the required keys in info.plist file.
**Issue details**
1. Platform (iOS)
2. OS version 13.1.2
3. File type (all)

**Comment by miguelpruivo** [comment]
Hi @Renatinaveen never had something like this reported, which is odd. Do you have access to the files anyway? If so, that's because you already had permissions. Try to completely delete the app and then re-install it. 

Thank you.

**Comment by Renatinaveen** [comment]
<key>NSPhotoLibraryUsageDescription</key>`

	<string>$(PRODUCT_NAME) does not have access to your photos. To enable access, tap Settings and turn on Photos. </string>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>GoldLane Partners</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	</dict>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Not using location service anywhere in this build</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Not using location service anywhere in this build</string>
	<key>UIBackgroundModes</key>
	<array>
	<string>fetch</string>
	<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationPortraitUpsideDown</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by Renatinaveen** [comment]
This is my info.plist file

I have added the photo permission and ui background also. When i Installed the app it doesn't ask for permissions it just opens photos. Even in the settings the photos permissions doesn't show. So i have added a plugin permission_handler to check permission and display dialog.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>$(PRODUCT_NAME) does not have access to your photos. To enable access, tap Settings and turn on Photos. </string>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>GoldLane Partners</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	</dict>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Not using location service anywhere in this build</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Not using location service anywhere in this build</string>
	<key>UIBackgroundModes</key>
	<array>
	<string>fetch</string>
	<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationPortraitUpsideDown</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by Renatinaveen** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>$(PRODUCT_NAME) does not have access to your photos. To enable access, tap Settings and turn on Photos. </string>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>GoldLane Partners</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	</dict>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Not using location service anywhere in this build</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Not using location service anywhere in this build</string>
	<key>UIBackgroundModes</key>
	<array>
	<string>fetch</string>
	<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationPortraitUpsideDown</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by Renatinaveen** [comment]
I have added the permissions. It doesn't ask for permission dialog when i perform operation to get images from photo library. 

It doesn't show required permissions under the application.

I have added the permission handler plugin to handle the permission dialog in iOS

**Comment by miguelpruivo** [comment]
Have you managed to solve this @Renatinaveen ?

**Comment by miguelpruivo** [comment]
@Renatinaveen which permissions are you asking for? Because so far, all the permissions should be handled within the plugin itself (iOS doesn't require runtime permissions, only entitlements and Android are asking for it).

**Comment by Renatinaveen** [comment]
Android I didn't have any issues. I was asking permissions for storage and
photos. In iOS it wasn't asking for permissions it was directly opening
files or photos if I choose to open something.

**Comment by miguelpruivo** [comment]
@Renatinaveen that's because you already had the entitlements in your info plist. I don't see that as an issue. Do you wanted to _explicitly_ ask for permissions? Is that it?

**Comment by Renatinaveen** [comment]
I have added the entitlements in info.plist yeah. But when the user
installed the app and when he clicks on the image upload button it should
ask for permission right? That was not happening it just directly take the
user to photos app.

**Comment by miguelpruivo** [comment]
@Renatinaveen yeah it should on the first access, but if for some reason they’re being granted access, that’s because the permissions were already given somehow.

**Comment by Renatinaveen** [comment]
So what should I do now? For Android I wasn't having any issues for iOS
alone I have this. And I am working live project so I used permission
handler package and continued. If you got any solution please let me know.

**Comment by miguelpruivo** [comment]
Well... if you have permissions already I wouldn’t bother in forcing them. 

Which iOS version are you testing under?

**Comment by Renatinaveen** [comment]
iOS 13

When I install app and check permissions nothing will be visible and I open
app do the Operation and check the permissions again it'll be there and
allowed. And If I disable there and go back to app and perform operation
nothing happens.

Using permission handler when I install app I can see what permissions the
app requires.

**Comment by miguelpruivo** [comment]
I'm not sure if I have clearly understand what's happening with you, yet, after all this debate. Let's break it down.

If you completely delete the app, install it, and access the files that you want to access, what happens? You can access it without being asked for permissions? Is that it?

**Comment by eriklueth** [comment]
Hey,
for me its the same on android 10.0.0 with Flutter Channel dev, v1.13.0. When I call await FilePicker.getFile(fileExtension: 'pdf') it does nothing. In the console it prints: 
I/FilePicker(13680): Checking permission: android.permission.READ_EXTERNAL_STORAGE
I/FilePicker(13680): Requesting permission: android.permission.READ_EXTERNAL_STORAGE
but doesn't ask for permissions. Also uninstalled the app and reinstalled it, but it is still not working.

**Comment by miguelpruivo** [comment]
@eriklueth what if you try in a different device or go into the settings manually of the app and grant permission? Android 10 introduced some nuances that were already addressed in later versions. 

Also, make sure you’re running the latest plugin version. 

Thank you.

**Comment by eriklueth** [comment]
I'am running your latest version. On android 10 I can't give the permission manually, if it isn't defined in the Android Manifest. Should I add it there? In your setup documentation it says nothing about it. I will try with the emulator with Android 9 in a second.

**Comment by miguelpruivo** [comment]
@eriklueth just add the permission manually (to read and write external memory) on your manifest and give it a shot.

**Comment by eriklueth** [comment]
Tried it, but also doesn't work. Not even showing in the app permission area in settings, to grant it manually. Haven't really looked into android 10 until now, but looks like it works different now.

**Comment by Renatinaveen** [comment]
Yes, that's exactly what's happening.

**Comment by xal** [comment]
@Renatinaveen Did you use multi-file selection on iOS? In this case library open simple file chooser without access to photo library
@miguelpruivo Could you add an exception for multi-select audio/video on ios before implementation will be implemented? I can PR If you want. It is not easy to understand what going wrong. It is easy to miss one line about this in readme

**Comment by miguelpruivo** [comment]
Yes I’ll add it @xal

**Comment by Renatinaveen** [comment]
No i am not using the multiple selection.

**Comment by mhmoudsabry** [comment]
iam not using getMultiFilePath 
iam using getFilePath
and my ios version is  11.3.1
cannot access gallery to get file
any help ???

**Comment by miguelpruivo** [comment]
@mhmoudsabry  you must use `getFileType(type: FileType.IMAGE)` explicitly for that.

**Comment by mhmoudsabry** [comment]
> @mhmoudsabry you must use `getFilePath(type: FileType.IMAGE)` explicitly for that.
> 
> You may want to take a look to the [API on the plugin's Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api).

i need to import any file type like pdf  or image how can i??

**Comment by miguelpruivo** [comment]
You can’t get PDF files from gallery. Either let your user pick a PDF and use `FileType.ALL` or pick an image and use `FileType.IMAGE`. Just ask them first if they want to pick PDF or image.

**Comment by mhmoudsabry** [comment]
> File

will try and tell you thanks for help

**Comment by mhmoudsabry** [comment]
> You can’t get PDF files from gallery. Either let your user pick a PDF and use `FileType.ALL` or pick an image and use `FileType.IMAGE`. Just ask them first if they want to pick PDF or image.

i will try and tell you 
thanks for help :)

**Comment by mhmoudsabry** [comment]
how to access on my files foldor and get files from 
this is my preview cannot access all my files
https://www.dropbox.com/s/0vjhu1f32yafq4u/t.jpg?dl=0

**Comment by miguelpruivo** [comment]
That’s correct. On iOS with any you open the file explorer where you can pick files from any cloud (or locally) but not from gallery. For that, you have to use type image. It’s impossible to show both file explorer and gallery at the same time on iOS.

**Comment by mhmoudsabry** [comment]
i  thought  it is possible and my client asking me for it
https://support.apple.com/library/content/dam/edam/applecare/images/en_US/icloud/ios13-iphone-xs-files-browse-locations-more-edit.jpg

**Comment by miguelpruivo** [comment]
You are opening exactly the same on your first link. Sometimes local doesn’t comes up because it needs to have some files, try on a real device with files on it. You might have to first enable those locations on the files app itself.
