### ISSUE TITLE
multiple types

### ISSUE THREAD

**Issue by kleinpetr** [miguelpruivo/flutter_file_picker#190]
1) How can I allow multiple types, for example IMAGE and VIDEO together?

2) How can I choose multiple images from gallery in iOS? 

Thank you

**Comment by kleinpetr** [comment]
Anything?

**Comment by miguelpruivo** [comment]
Hi @kleinpetr, 

For picking images from gallery on iOS just use `FileType.IMAGE`.

As for picking vídeos and images at same time, currently is not supported. You’ll have to use both `FileType.IMAGE` and `FileType.VIDEO` individually.

There are already a feature request (#99) to support multiple types at same time, just hadn’t the time yet to implement it. I hope that by the next days I’ll have time to do so. 

Thank you!

**Comment by kleinpetr** [comment]
@miguelpruivo 

> As for picking vídeos and images at same time, currently is not supported. You’ll have to use both FileType.IMAGE and FileType.VIDEO individually.

Yes its working when you can pick only one file. When I use this `FilePicker.getMultiFilePath(type: FileType.IMAGE)` on ios, its open the documents instead gallery

**Comment by miguelpruivo** [comment]
@kleinpetr yes, that’s also mentioned in that feature request. Currently will only work for _single_ pick.

**Comment by miguelpruivo** [comment]
As of now, with version [1.6.0 released just now](https://pub.dev/packages/file_picker#160) you can start filtering multiple extensions at once. There are breaking changes, so have in mind that from now on you'll need to provide an `List` of file types instead of a single one with `FileType.custom`.

Example:
```
 List<File> files = await FilePicker.getMultiFile(
          type: FileType.custom,
          allowedExtensions: ['jpg', 'pdf', 'doc'],
        );
```
Thank you.
