### ISSUE TITLE
Multiple selection doesn't working

### ISSUE THREAD

**Issue by dvasea1** [miguelpruivo/flutter_file_picker#191]
Downloaded example. Tested on Android, multiple file picker don't working.

**Comment by miguelpruivo** [comment]
@dvasea1 you must tap and hold on files to activate multiple selection.

**Comment by miguelpruivo** [comment]
Did it worked for you @dvasea1 ? If so, feel free to close this. 

Thank you.

**Comment by miguelpruivo** [comment]
Since no further response has been given, I'll close this for now. Feel free to reopen it if you still have an issue related to this.

Thank you....
