### ISSUE TITLE
For Desktop i'm facing following issue: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker) 

### ISSUE THREAD

**Issue by AnandSaran** [miguelpruivo/flutter_file_picker#192]
flutter: [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method IMAGE on channel file_picker)
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method IMAGE on channel file_picker)

**Comment by miguelpruivo** [comment]
Hi @AnandSaran, desktop is only supported currently via go-flutter. Please, refer to the wiki. 

Thank you.

**Comment by AnandSaran** [comment]
Hi  @miguelpruivo i tried with Go Flutter but still same issue
