### ISSUE TITLE
Mac osascript select file output does not contains ":" so that couldn't pick the file on mac!

### ISSUE THREAD

**Issue by AlienwareHe** [miguelpruivo/flutter_file_picker#193]
**Describe the bug**
when use the file picker on mac,the file_darwin.go 
```
output, err := exec.Command(osascript, "-e", `choose file of type {`+filter+`} with prompt "`+title+`"`).Output()
```
output is such as:
```
alias /Users/alienhe/Documents/空白模版.xlsx
```
so use 'pathParts := strings.Split(trimmedOutput, ":")' to split result is "/"!

and if i want to fix the issue, how can i do  it?(I am a flutter newer from  china, my english is poor...lol)

hope you can help me ~ thanks!!

**Comment by miguelpruivo** [comment]
@GeertJohan do you know what might be?

**Comment by miguelpruivo** [comment]
@AlienwareHe any news on this?

**Comment by AlienwareHe** [comment]
i compact the two splitter ("  "  and the ":") to resolve it temporarily, thanks to attention my question~
