### ISSUE TITLE
Fails for files named with colons. (on Android)

### ISSUE THREAD

**Issue by sgehrman** [miguelpruivo/flutter_file_picker#194]
**Describe the bug**

Fails for file names with colons.

file named:  (DateTime toString).json
'2020-01-02 16:24:18.021099.json'

File file = await FilePicker.getFile();

await file.readAsString();

FileSystemException (FileSystemException: Cannot open file, path = '/storage/emulated/0/Android/data/re.distantfutu.therapist_training/files/2020-01-02 16' (OS Error: No such file or directory, errno = 2))

I'm on Android, the file works fine on the device.  It can be read/modified.

**Comment by miguelpruivo** [comment]
@sgehrman there was already been reported a similar issue, which you can see the discussion on #166.

Basically, using `:` on file names is invalid in most systems. If you try to rename the file on your device it shouldn’t allow you to insert `:`. That also happens on Windows/Mac naming. I tried to replicate it multiple times to fix the above reported issue and I couldn’t find a reliable way yet.

**Comment by sgehrman** [comment]
I save the file in Android/flutter using
var file = File('/path/to/file:with:colons.txt');
file.writeAsString(contents);

That works when saving to Android.  And the file works and shows up on Android.  

I already fixed my code to remove colons from the name before saving, but it would be good if your code handled it.

Thanks

**Comment by miguelpruivo** [comment]
@sgehrman that somehow could open potential issues as it contains forbidden characters. Would rather let the user be presented with an error so he could be warned about invalid file name. 

Anyhow, for handling it, you can see why it wasn’t implemented yet on #166.

Thank you.
