### ISSUE TITLE
Add support for Android V2 embedding

### ISSUE THREAD

**Issue by TheHemantKaushik** [miguelpruivo/flutter_file_picker#196]

**Comment by Boehrsi** [comment]
Some context:

- How to: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration
- Why: Apps using the v2 embedding can't use the file_picker plugin, as it stops functioning
- More information: https://github.com/miguelpruivo/flutter_file_picker/issues/195#issuecomment-575018902

**Comment by miguelpruivo** [comment]
Closing this as a dup of #195. You can follow the discussion there.
