### ISSUE TITLE
Pass theme data to file picker

### ISSUE THREAD

**Issue by chitgoks** [miguelpruivo/flutter_file_picker#197]
this is more of a feature request.

when i open the file picker, it would be nice to have a way to pass themedata so that the color scheme will be the same.

**Comment by miguelpruivo** [comment]
Hi, thank you @chitgoks, I'm not sure if that's possible in iOS at all (or even Android) because they disallow custom theming for native File Explorer (at least, I haven't seen one).

**Comment by chitgoks** [comment]
ok thank you for the info
