### ISSUE TITLE
I can't select images form Gallery 

### ISSUE THREAD

**Issue by talanaji** [miguelpruivo/flutter_file_picker#201]
I try to select images from Gallery to pick multi files, 
but it's not work 
I can only select one image form Gallery or and folder on my device 
but I can select multi images from recent images only 
my device is Galaxy Note 8

**Comment by miguelpruivo** [comment]
Are you holding the files? In some Android versions you need to tap and hold before the multi pick comes out.

**Comment by talanaji** [comment]
I know that , I hold before pick 
but just select one picture 
not multi

**Comment by miguelpruivo** [comment]
How are you calling it?

**Comment by talanaji** [comment]
Future openFileExplorer() async {
     try {
      _path = null;
      //if (_multiPick) {
      _paths = await FilePicker.getMultiFilePath(
          type: FileType.IMAGE, fileExtension: _extension);
      //String numofimgs = _path.length.toString();
      // Alert(title: "تم اختيار "+numofimgs, context: context).show();
      setState(() {
        _imgspaths = _paths;
      });
      /*  } else {
        _path = await FilePicker.getFilePath(
            type: _pickType, fileExtension: _extension);
        setState(() {
          _imge = _path;
        });
        //Alert(title: "تم اختيار صورة واحدة", context: context).show();

      }*/
    } on PlatformException catch (e) {
      print("Unsupported operation" + e.toString());
    }
    if (!mounted) return;
    setState(() {  
    });
  }



---------------
  Future uploadImage(File videoFile, String ads_id) async {
    var uri =
        Uri.parse("https://khod-shokran.com/uploadphoto.php?ads_id=$ads_id");
    var request = await new http.MultipartRequest("POST", uri);

    var multipartFile =
        await http.MultipartFile.fromPath("video", videoFile.path);
    request.files.add(multipartFile);
    http.StreamedResponse response = await request.send();
    response.stream.transform(utf8.decoder).listen((value) {
      print(value);
    });
    if (response.statusCode == 200) {
      print("Video uploaded");
    } else {
      print("Video upload failed");
    }
  }

---------------
Container(
                            width: MediaQuery.of(context).size.width,
                            padding: EdgeInsets.all(10.0),
                            decoration: BoxDecoration(
                                color: Colors.grey.shade100,
                                border: new Border.all(
                                    color: Colors.grey.shade200,
                                    width: 1.0,
                                    style: BorderStyle.solid),
                                borderRadius:
                                    BorderRadius.all(Radius.circular(5))),
                            child: OutlineButton(
                                onPressed: () => openFileExplorer(),
                                child: new Column(
                                  children: <Widget>[
                                    Text("اختر الصور",
                                        style: GoogleFonts.tajawal(
                                            fontWeight: FontWeight.bold,
                                            color: Color(0xff4c6f74))),
                                    showImages(),
                                  ],
                                )),
                          ),
------------
  Widget showImages() {
    if (_path != null || _paths != null) {
      List<Widget> list = new List();

      /*  if (_multiPick) {
        list.clear();*/
      _paths.forEach((fileName, filePath) => {
            list.add(Image.file(
              File(filePath),
              height: 100,
            )) //  upload(fileName, filePath)
          });
      return Column(
          crossAxisAlignment: CrossAxisAlignment.stretch, children: list);
      /*} else {

        list.clear();
        return Image.file(
          File(_path),
          width: 50,
          height: 50,
        );
      }*/
    } else {
      return Text(" ");
    }
  }

**Comment by miguelpruivo** [comment]
Just try to not use `_extension` when you are explicitly providing the type (`FileType.IMAGE`).

**Comment by talanaji** [comment]
doesn't work

**Comment by talanaji** [comment]
I also trying to test the original example but didn't work 
same problem

**Comment by miguelpruivo** [comment]
Have you managed to solve it?

**Comment by talanaji** [comment]
no not solved sorry ,,

**Comment by miguelpruivo** [comment]
Could you provide a code sample so I could try to replicate? And the running device where you are trying.

Thank you.

**Comment by EddieLi** [comment]
same problem here, when i open file picker, it takes me to icloud file storage instead of photo gallery in iOS, but works fine for android

**Comment by miguelpruivo** [comment]
@EddieLi like mentioned [in the Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api#filepickergetmultifilepath) currently picking multiple files on iOS gallery isn’t supported, so it falls back to Files app. 

This may come in a near future. I have plans to add some new missing (and requested) features on this soon.

Thank you.

**Comment by talanaji** [comment]
See , 
when I choose photo from green arrow as shown  in image below , I can pick multi images , but if I choose photo from red arrow I can pick only one image 
I test it in another android device its the same problem 

https://drive.google.com/file/d/1j1xIvdoYz7Eiim9B9-da-obdHhknvMQ3/view?usp=sharing

**Comment by miguelpruivo** [comment]
@talanaji that’s probably because Google photos is only allowing single picks despite of having multi pick enabled. Even though the Android intent contains it, it’s possible that some providers may ignore it, unfortunately, and there’s not much you can do. 😞

**Comment by DebugTheCode** [comment]
> @EddieLi like mentioned [in the Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api#filepickergetmultifilepath) currently picking multiple files on iOS gallery isn’t supported, so it falls back to Files app.
> 
> This may come in a near future. I have plans to add some new missing (and requested) features on this soon.
> 
> Thank you.

That would be a very nice feature. I hope you'll integrate it very soon. Thanks in advance.

**Comment by miguelpruivo** [comment]
Please, follow #233 to track this. Thanks!
