### ISSUE TITLE
Accept more than one file extension

### ISSUE THREAD

**Issue by erperejildo** [miguelpruivo/flutter_file_picker#203]
Is this currently possible?

**Comment by miguelpruivo** [comment]
It’s a work in progress yet. See #99 

Thank you.

**Comment by erperejildo** [comment]
That's referring to getMultiFilePath() (https://github.com/miguelpruivo/flutter_file_picker/issues/68). Will this be available also for getFile()?

**Comment by miguelpruivo** [comment]
Yeah, sure. When available, it will transversally be supported by all of those methods.
