### ISSUE TITLE
Application initializing document picker is missing the iCloud entitlement.

### ISSUE THREAD

**Issue by basnetjiten** [miguelpruivo/flutter_file_picker#205]
I am getting the following error on Xcode for ios vs below 11.0:
Although I set up iCloudKit , iCloudDocuments , Containers and Key-value Storage checked.

Couldn't launch documents file picker. Probably due to iOS version being below 11.0 and not having the iCloud entitlement. If so, just make sure to enable it for your app in Xcode. Exception was: Application initializing document picker is missing the iCloud entitlement. Is com.apple.developer.icloud-container-identifiers set?
* -[FilePickerPlugin resolvePickDocumentWithMultipleSelection:] [Line 81]

**Comment by miguelpruivo** [comment]
Based on the exception itself it looks like you are missing the plist entitlements. I would recheck those, clean and build.

**Comment by basnetjiten** [comment]
I just added these two requirements:
<key>UISupportsDocumentBrowser</key>
	<true/>
	<key>LSSupportsOpeningDocumentsInPlace</key>

Now it's complaining about :

Passed in type public.item doesn't conform to either public.content or public.data. If you are exporting a new type, please ensure that it conforms to an appropriate parent type.
*** Assertion failure in -[UIDocumentPickerViewController _commonInitWithCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UIDocumentPickerViewController.m:78

**Comment by miguelpruivo** [comment]
Have you managed to solve it @basnetjiten?

**Comment by basnetjiten** [comment]
No luck!!! It works well above Ios version 10/11

**Comment by miguelpruivo** [comment]
@basnetjiten which type of file are you trying to filter?

**Comment by miguelpruivo** [comment]
Closing due to no further info, let me know if you still have an issue with this.
