### ISSUE TITLE
Theme/Colors: text not visible due to theme colors.

### ISSUE THREAD

**Issue by cormalenv** [miguelpruivo/flutter_file_picker#207]
Text of files/folder and search bar very difficult to read due to theme colors (on certain devices). 

1. Platform (Android/iOS) - Android
2. OS version - 8.1.0
3. File type (filter) - Any
4. Steps to reproduce - 

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: RaisedButton(
          child: Text('Run'),
          //onPressed: () => FilePicker.getFile(type: FileType.CUSTOM, fileExtension: 'json'), //json file not valid'
          onPressed: () => FilePicker.getFile(type: FileType.ANY),
        ),),);}}

![File_Picker_Theme_Issue](https://user-images.githubusercontent.com/56389408/75031009-708b7900-54f9-11ea-9c93-be3eff69d3cd.jpg)

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.476], locale en-AU)
    • Flutter version 1.12.13+hotfix.8 at ...
    • Framework revision 0b8abb4724 (10 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at ...
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi 6 • 672382f37d26 • android-arm • Android 8.1.0 (API 27)

• No issues found!

**Comment by miguelpruivo** [comment]
Hi @cormalenv this is related to your device's app theme (check your Android styles) and not the plugin itself. The plugin only calls the native picker and doesn't override any kind of style on it.

**Comment by cormalenv** [comment]
Hi @miguelpruivo. I'm guessing we cannot override this. We just have to force users to change their theme. Thanks for the clarity.
