### ISSUE TITLE
Invalid MethodChannel name on IOS

### ISSUE THREAD

**Issue by viplifes** [miguelpruivo/flutter_file_picker#211]
v1.5.0+1
on IOS MethodChannel name is - file_picker
https://github.com/miguelpruivo/flutter_file_picker/blob/master/ios/Classes/FilePickerPlugin.m#L19

on flutter MethodChannel name is - miguelruivo.flutter.plugins.file_picker
- https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/file_picker.dart#L16

**Comment by miguelpruivo** [comment]
@viplifes good catch, I've updated it on Android forgot on iOS. In a few minutes it will be fixed.

Thank you.

**Comment by miguelpruivo** [comment]
Done. Fixed with [1.5.0+2](https://pub.dev/packages/file_picker#1502).

Thank you.
