### ISSUE TITLE
FilePicker.getMultiFile(type: FileType.image) does not return list of images

### ISSUE THREAD

**Issue by ArpitAwasthiQV** [miguelpruivo/flutter_file_picker#217]
I was trying to get multiple images
List<File> files = List();
files = await FilePicker.getMultiFile(type: FileType.image);

but i only get one image.
I also tried getting multiple pdf files and it successfully return a list

**Comment by miguelpruivo** [comment]
@ArpitAwasthiQV are you on iOS or Android?

**Comment by ArpitAwasthiQV** [comment]
android

**Comment by miguelpruivo** [comment]
@ArpitAwasthiQV tap and hold on image files when you are selecting them.

**Comment by ArpitAwasthiQV** [comment]
@miguelpruivo I'm selecting multiple images but still it returns only one file

**Comment by miguelpruivo** [comment]
@ArpitAwasthiQV which version of Android are you on? Does that happen on both device and simulator?

**Comment by ArpitAwasthiQV** [comment]
android version 9. device - samsung galaxy j6.
Im using this device for testing. not using simulator. 
Havent even tried it on ios device yet.

**Comment by miguelpruivo** [comment]
iOS doesn't support multiple picking from gallery as of now, that's why I asked.

Nevertheless, that shouldn't happen at all. Could you please try with:

a) Simulator or other device;
b) With the example app provided with the plugin;

Thanks!

**Comment by ArpitAwasthiQV** [comment]
So it seems that the problem is with the samsung device. tested it on lg g7 thinq and working perfectly.

**Comment by miguelpruivo** [comment]
@ArpitAwasthiQV some Samsungs break some of the Android guidelines. This is a no-issue as far as I'm concerned, otherwise would happen in other devices with same Android version (that's why I asked you for trying in a different device).
