### ISSUE TITLE
getMultiFile() Returns Null ( , and getMultiFilePath) [Desktop hover run darwin ]

### ISSUE THREAD

**Issue by iamsabet** [miguelpruivo/flutter_file_picker#218]
hi im using flutter beta 
and flutter_file_picker 1.5.0+2
and building with Hover go for mac os

using .getFile , .getFilePath methods are ok

but .getMultiFile() , .getMultiFilePath() , does not work , Returns NULL
only on desktop  (Mac OS)

**Comment by miguelpruivo** [comment]
Hi @iamsabet, have you managed to solve it?

**Comment by miguelpruivo** [comment]
@iamsabet mind to try with `file_picker: 1.6.2`? Thank you.

**Comment by miguelpruivo** [comment]
@iamsabet this should now be fixed with `1.6.3`, as some issues were found on Go side of plugin's implementation.

Please, report if you find something else.
Thanks!
