### ISSUE TITLE
[FilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null)

### ISSUE THREAD

**Issue by pureimpro** [miguelpruivo/flutter_file_picker#219]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform : IOS 13.3 on Simulator iPhone11 pro max + iPhone8
2. OS version : MacOS Catalina 10.15
3. File type (filter) : `audio`
4. Steps to reproduce

1- add this code to your flutter app in the onTap method of a button : `File file = await FilePicker.getFile(type: FileType.audio);`

2- Nothing happens.

3- Click a second time to catch the platform error : 
`[FilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null)`

Note that this works well for videos or photos picking. Only happens with **audio filter**.

**Flutter Version details**
```
/Users/zaz/Bombtrack/appli_bo % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E264b, locale en-FR)
    • Flutter version 1.12.13+hotfix.8 at /Users/zaz/Bombtrack/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zaz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.4, Build version 11N132i
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • C3F697EF-DA10-46F8-9EA6-1D16E7D0E5E9 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Additional context**
I noticed on the console of the iPhone Simulator the following error : 
![image](https://user-images.githubusercontent.com/54768647/77693822-45d58a00-6fa9-11ea-8565-0f9343cae495.png)

The system does not seem to find the appropriate "com.apple.Music.MediaPicker" plugin !

Thanks for your support

**Comment by miguelpruivo** [comment]
@pureimpro maybe I should document that as well. I'm afraid that it will only work when you have Music app installed with actually some content. Mind to try on a real device?

Thank you!

**Comment by pureimpro** [comment]
thank you @miguelpruivo for your quick response !
Unfortunately I do not own any IOS physical device.
You are right, I do not have any audio content on my Virtual MacOs.
I tried to download a mp3 sample from the internet, and ITunes plays it nicely. But the console still complains about missing "com.apple.Music.MediaPicker".
What do you advice me to do in such a case ? Is it a plugin problem or a MacOs content oriented problem ?
I don't know much about MacOS, I don't know where to find  "com.apple.Music.MediaPicker" and neither initialize it !

**Comment by miguelpruivo** [comment]
@pureimpro don’t worry. Picking áudio requires actually a music app with not DRM audio protected files on it so they can be picked. I’d try on a real device just to make sure whenever possible.

Also, make sure you didn’t forget about the audio entitlement that is required for such type picking.

**Comment by pureimpro** [comment]
@miguelpruivo thank you for your hints ! After googling a while, I just discovered that IOS Simulators do **NOT** have access to appStore and have just a minimal application set, excluding music app :(
Picking audio in a simulator is therefore impossible, with any flutter plugin, I think.
I did not find a website providing "IOS simulator music app friendly" download.
If you know one of them, let me know ! Or if you can provide yourself a music app for IOS Simulator, you're welcome ;)

I confirm that the audio entitlement is checked for my Xcode project  target : 
![image](https://user-images.githubusercontent.com/54768647/77778987-247ca880-7052-11ea-83c5-2aaffaa84655.png)

If you can try "audio pickup" on a real device, it would be nice.

**Comment by miguelpruivo** [comment]
@pureimpro the thing is that picking audio from iOS is restricted to official Apple Music app, regardless of the files being yours, as they’re also imported to it. That means that there’s no way that other player would solve it anyway. 

I’m closing this as it’s not probably an issue, but feel free to reopen it if you try on a real device and the problem persists. Other than that, we can further continue de discussion here.

Thank you!
