### ISSUE TITLE
NullPointerException on Cursor.close()

### ISSUE THREAD

**Issue by DenchikBY** [miguelpruivo/flutter_file_picker#222]
Hi! Please add null check.

![Selection_346](https://user-images.githubusercontent.com/5912200/78130668-6a56b980-7422-11ea-9670-1a498b52c850.jpg)

https://github.com/miguelpruivo/flutter_file_picker/blob/8eb61af343b988bf0c523263199c53f6bfd2480b/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L170

**Comment by miguelpruivo** [comment]
Good catch, I wonder why no one has never come across this. Thank you @DenchikBY.

**Comment by miguelpruivo** [comment]
Fixed and deployed with [1.6.0](https://pub.dev/packages/file_picker#160) that also supports multiple file extensions at once. 

Thank you!
