### ISSUE TITLE
csv file type doesn't work

### ISSUE THREAD

**Issue by laurij95** [miguelpruivo/flutter_file_picker#226]
**Describe the bug**
I wanted to be precise in the type of file a user can select but when I put  
'_path = await FilePicker.getFilePath(type: FileType.custom, fileExtension: 'csv'); ', it does not work because even type .csv files are greyed out

**Issue details**
Flutter on Android Studio
Trying to access file on phone storage and google drive via emulator

**Comment by miguelpruivo** [comment]
Closing as a dup of #24.

**Comment by itassets** [comment]
Any clue on that? Still can´t find the solution. Thanks in advance.
