### ISSUE TITLE
please Don't expose data with Log.i Log.e

### ISSUE THREAD

**Issue by erlangp** [miguelpruivo/flutter_file_picker#227]

**Comment by miguelpruivo** [comment]
Hi, may I know the details for requesting this one? There isn’t any sensitive data exposed with it at least that I’m aware of. 

Actually the logs exposed most of the times are just handy steps or uris of what’s happening and definitely can help on debug/release builds.

Thank you.

**Comment by erlangp** [comment]
BuildConfig.DEBUG :)

**Comment by miguelpruivo** [comment]
@erlangp once again, logger.d should only appear on debug builds and .i on both with relevant information for both release and debug.

Also, I believe that you could turn off the logs for debug/release builds on your own build config settings and let up to the developer to decide.

Is there any particular reason why you would want to remove them at all?

**Comment by erlangp** [comment]
Thanks for your response @miguelpruivo sir..
For me personally, usually I comment on all the Log code that is on android (to not expose in the logger). But I send the error log directly to the server using error reporter like ACRA..
