### ISSUE TITLE
how to add 2 extention in FileType.CUSTOM 

### ISSUE THREAD

**Issue by klokoleva** [miguelpruivo/flutter_file_picker#228]
dear teams, 
kindly help me to train how to allowed 2 extention after file epolorer opened.. 

this schema..
1. i clik button 'choose file'
2. open file explorer with 2 extentention file (PDF and image)
3. only PDF and image showing (others like apk file is hidden)

thankyou

**Comment by miguelpruivo** [comment]
Hi. This is a requested feature that will be added soon. 

Closing as this is being followed on #199 

Thank you!

**Comment by miguelpruivo** [comment]
This has already been added @klokoleva. Check version 1.6.0.

Thank you!
