### ISSUE TITLE
[Feature] Support scoped storage on Android

### ISSUE THREAD

**Issue by miguelpruivo** [miguelpruivo/flutter_file_picker#234]
# Motivation
[Scoped storage](https://developer.android.com/training/data-storage#scoped-storage) was introduced with API 29 and was motived to abstract devs from directly handling absolute paths.

I'm aware that as convenience, having absolute paths allows you to instance a `File` object directly on Flutter and handle it from there, however, this is not always possible and cached files (copies) act as fallback. 

This may result in some devs being confused whether they are picking the original file or copies and also, in the later, prevents original file from being manipulated directly. Supporting scoped storage will allow files to always being directly manipulated through platform calls, instead of creating a `File` instance.

A lot of discussion has been made around this on some issues, such as #169. This solution aims to act as an alternative and absolute paths will still exist for those that want or below API 29.

**Comment by hpoul** [comment]
Out of curiosity, do you already have any plans how to implement this (API wise), or have you started?
I'm thinking about having a go on it as well.. I have a few user reports ([@AuthPass](https://github.com/authpass/authpass/)) because of that problem and not much to solve it without touching the plugin.

**Comment by miguelpruivo** [comment]
@hpoul yes, I have been drafting something but's not yet on origin, this is on my top priorities alongside with #229 and #233, so that's probably next on the line.

**Comment by hpoul** [comment]
that is great to hear, so i'll just wait it out.. one thing, do you know that the same exact problem exists on iOS devices? Right now the plugin uses: `UIDocumentPickerModeImport` when opening `UIDocumentPickerViewController`. This basically only returns a copy in the applications `Inbox` directory. As far as I understand it, to be able to read and (re)write. it, one would have to use `UIDocumentPickerModeImport` and then [use secure bookmarks](https://developer.apple.com/documentation/foundation/nsurl/1417795-bookmarkdata) to keep the. permission to write the data on subsequent launches.

So maybe when planning the API for android it would make sense to keep this in mind.

**Comment by miguelpruivo** [comment]
@hpoul good point. Anyway, I’m not sure if that will be necessary on iOS side as you _always_ an absolute path to handle. That makes it easier for Dart to manipulate a `File` object directly.

**Comment by hpoul** [comment]
not sure what you mean exactly.. as I see it, both the iOS and android plugin would need to pass back to the caller two informations 1. file path containing content 2. some opaque token to identify the original loaded file by the plugin (for refreshing the content in the future, as well as writing back to it) - on android this is a content provider URI, on iOS this is a secure bookmark URL.

**Comment by hpoul** [comment]
fyi, i tried to add support for writable storage to the plugin, but it felt like your plugin was made for a completely different purpose (ie. importing files into the app, rather than "opening" them for manipulation).. So i've gone the route of implementing only exactly that in a [separate plugin](https://github.com/hpoul/file_picker_writable/).. it's sole purpose is to let the user choose a file for editing, and keeping a stable reference to it, to be able to read it after restarts and overwrite it as well.. (ie. no support of gallery imports, multi files, etc. - which made it quite a bit easier)..

**Comment by miguelpruivo** [comment]
That's nice to hear @hpoul, I actually have plans to add it into the file_picker as well, just hadn't the time yet with all of other requested features/issues and the time I have to maintain it (as I'm the only maintainer of the plugin).

I'll probably take a look into yours when implementing it.

Thank you!

**Comment by bradyt** [comment]
Hmm, just want to ping this thread, as I attempted to write a plugin that allows user to pick a file and have persistent read/write access to it. I noticed at least that file_picker_writable uses ACTION_OPEN_DOCUMENT somewhere. If any part of my project at cone/uri_picker is needed, please have at it. (Maybe open_document would have been a better name for my plugin... I think iOS documentation has some openDocument function, I'm not sure if that's the right fit for my app.)

The plugin I wrote manages to not require user to give permissions to entire device. Will this be possible with these plugins?

I would like to port uri_picker to iOS, but then as little progress as I've made at it, I'm also hoping someone manages to implement the features I'd like before I do.

I hope to take another longer look at both projects soon. Thank you both for your work on these.

- https://github.com/bradyt/cone/tree/v0.2.20/uri_picker

**Comment by braysonjohn148** [comment]
is this feature done.

**Comment by miguelpruivo** [comment]
Hi @braysonjohn148. No, I haven't much time lately and this will require some structural refactoring.

**Comment by braysonjohn148** [comment]
> Hi @braysonjohn148. No, I haven't much time lately and this will require some structural refactoring.

ok. thank you. Hope you working on it, most of my clients are really complaining failing to upload files on the app.

Is there any work around we can do temporarily, like getting the copy of the file and its path rather than not at all..? hope to hear from you soon.

**Comment by hpoul** [comment]
@braysonjohn148 if you don't need file multi select you might want to try out [file_picker_writable](https://pub.dev/packages/file_picker_writable) it supports read/write access on android and iOS. both for opening existing files and creating them.

**Comment by miguelpruivo** [comment]
@braysonjohn148 what @hpoul said. For the time being is the best option until I add that functionality to this as well.

Thank you!

**Comment by braysonjohn148** [comment]
thank you soo much. Let me check it out

**Comment by lakshyab1995** [comment]
@miguelpruivo , I modified the file picker code to support the Android OS for API 29 and above. I have added a SDK level check in plugin. 
In brief, I made changes to **FilePickerDelegate.java** class, while getting the path it will first check if the current OS is Android Q and above, if so then it will call **FileUtils.getUriFromRemote** method -
`fullPath = FileUtils.getUriFromRemote(FilePickerDelegate.this.activity, uri);`
otherwise **FileUtils.getPath** method-
`fullPath = FileUtils.getPath(uri, FilePickerDelegate.this.activity);`

I have checked this implementation on Android Q as well as OS below Android Q, it is working as expected.

**Comment by navaronbracke** [comment]
Since the above commit was merged, can we expect a version bump soon-ish?

**Comment by miguelpruivo** [comment]
@navaronbracke it’s already published with 1.13.1. Thanks!

**Comment by navaronbracke** [comment]
@miguelpruivo It seems that the new implementation from the commit only works with images. If I want to pick a custom file for example, I get an `UnimplementedError`.

**Comment by miguelpruivo** [comment]
@navaronbracke do you have a replicable example?

**Comment by navaronbracke** [comment]
Not sure what was going on earlier, but I can confirm, it does work with custom files.

**Comment by miguelpruivo** [comment]
@navaronbracke probably some bad cache or so.

**Comment by navaronbracke** [comment]
Yeah I think so.

**Comment by braysonjohn148** [comment]
I/FilePickerUtils( 4490): File loaded and cached at:/data/user/0/com.xcgx.droopy/cache/file_picker/89141
I/FilePickerDelegate( 4490): Absolute file path:/data/user/0/com.xcgx.droopy/cache/file_picker/89141
I/flutter ( 4490): CacheManager: Failed to download file from  with error:
I/flutter ( 4490): Invalid argument(s): No host specified in URI

**Comment by miguelpruivo** [comment]
FYI: I'm already working on this along with #234, expect a release this week. 🎉

**Comment by miguelpruivo** [comment]
**Update:** [check comment](https://github.com/miguelpruivo/flutter_file_picker/issues/358#issuecomment-690812563).

**Comment by miguelpruivo** [comment]
Update is now live with [2.0.0](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) please, [see the changelog for details](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) of what have changed.

Let me know if you find any issue! 🎉 

Thank you!
