### ISSUE TITLE
can't  select multiple pictures

### ISSUE THREAD

**Issue by gaoyong06** [miguelpruivo/flutter_file_picker#239]
Thank you very much to the author for completing such a useful plugin, I want to complete the following features. 

1. Open the mobile album, if you choose the video is, you can only select 1 video, the other can not choose.
2. Open  the mobile album If you select a picture, choose up to 9 pictures. 
3. When you select a picture (or video) to re-enter the album, it's still selected. 
4. Click on the selected picture, you can go to the "Details page", the details page in the upper right corner has a "delete (unselect) " button, click to cancel the picture selection. When I finish feature 1, I come across the api that enters the album and can only select one picture at a time, and there is no selection icon, and then I use the api to select multiple pictures

code:

List<File> resultFileList;
resultFileList = await FilePicker.getMultiFile(type: FileType.image); 

![GZTDS_P9B$OF{H@_P5}9EFI](https://user-images.githubusercontent.com/1861256/79059184-989d8a00-7ca9-11ea-87a9-48fc91a96d76.jpg)
![H%V8 5PG(65B8YJ_)(HWGTF](https://user-images.githubusercontent.com/1861256/79059191-9e936b00-7ca9-11ea-9a5f-a6cd6862dee0.jpg)

**Comment by miguelpruivo** [comment]
Dup of #238
