### ISSUE TITLE
Error on building flutter go application

### ISSUE THREAD

**Issue by marchellodev** [miguelpruivo/flutter_file_picker#241]
Cannot build the flutter go application, using the latest versions of hover and flutter_file_picker

```
github.com/miguelpruivo/flutter_file_picker/go
# github.com/miguelpruivo/flutter_file_picker/go
../../../../go/pkg/mod/github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20200408114506-d67b36971552/file_linux.go:4:2: imported and not used: "strings"
../../../../go/pkg/mod/github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20200408114506-d67b36971552/plugin.go:25:27: not enough arguments in call to fileFilter
        have (string)
        want (string, []string, int)
hover: Go build failed: exit status 2

```

**Comment by miguelpruivo** [comment]
Thank you @marchellodev, that was due to a quick refactor, I'll deploy a fix later today. Sorry for the inconvenience.

**Comment by marchellodev** [comment]
Hello, @miguelpruivo, any updates?

**Comment by miguelpruivo** [comment]
Sorry, just hadn't the time yet @marchellodev. I'll try it today.

**Comment by miguelpruivo** [comment]
@marchellodev I looked into this today but actually found a limitation on Go side that I'm already working on. 

For now, I suggest you to use a version that doesn't support multiple file picking, such as 1.5.0+2.

Sorry for the inconvenience, I'll keep you updated.

**Comment by bohrasankalp** [comment]
Is this the reason it's ending with missing plugin exception on the flutter-desktop version?

**Comment by miguelpruivo** [comment]
@bohrasankalp no, this is only for versions above 1.5.0+2 and will thrown an error due to invalid method calls. 

For that missing plugin exception looks like you forgot to `hover init` before calling `hover run` (check the [steps](https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#--desktop-go-flutter) for installation.

**Comment by miguelpruivo** [comment]
@marchellodev @bohrasankalp issues were addressed and file picker can again be used with Go, with multiple file extension support, see [1.6.3](https://pub.dev/packages/file_picker#163). 

Please, be aware that on Darwin (MacOS) multiple extensions won't work (I'll add to Wiki) as of now, on Windows/Linux if someone find something please report me as I didn't have a chance to try on those environments, but it should be fine.

Thank you!

**Comment by marchellodev** [comment]
@miguelpruivo, the latest version still doesn't work

```
go: downloading github.com/miguelpruivo/flutter_file_picker/go v0.0.0-20200417112135-83bda1f2f6aa
github.com/miguelpruivo/flutter_file_picker/go
# github.com/miguelpruivo/flutter_file_picker/go
../../../../go/pkg/mod/github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20200417112135-83bda1f2f6aa/plugin.go:40:27: too many arguments in call to fileFilter
        have (string, []string, int, bool)
        want (string, []string, int)
hover: Go build failed: exit status 2
```

**Comment by miguelpruivo** [comment]
@marchellodev sorry, you are correct. I've only tested on MacOS, that's why I couldn't find that I forgot the new args for the other platforms. Already deployed `1.6.1+1` with a fix. Let me know if it's working for you.

Nevertheless, don't forget to clean up your cache (it should be under `~/go/pkg/mod/github.com/miguelpruivo/flutter_file_picker/`

Thanks.

**Comment by marchellodev** [comment]
@miguelpruivo I can't find this update on github, how can I add it to hover?
