### ISSUE TITLE
Android: Saving back to the selected file

### ISSUE THREAD

**Issue by hpoul** [miguelpruivo/flutter_file_picker#244]
Right now, especially on later android versions the file cannot be resolved to a local path, but has to be fetched by the content provider / URI and so the file picker plugin has to create a cached version of it.
but .. 

1. The Plugin does not communicate to the caller that the file is just a cached copy of the original file.
2. The dart code has absolutely no way to change the original file.

It would be nice if the plugin would also return the original URI of the file and provide a way to write to that URI.

Or are there any workarounds for that problem? Right now it just looks like my app is not saving at all, because it is just changing a copy without knowing it.

**Comment by miguelpruivo** [comment]
Hi @hpoul! You are completely right and I’ve already created an issue with feature purposely regarding this that I’ll implement in a near future. Check #234.

I welcome you to post any suggestions/questions there.

Thank you!

Closing as a dup of #234.

**Comment by hpoul** [comment]
@miguelpruivo thanks for your fast response. I have actually seen the other issue before, but it sounded to be a bit of a broader scope.. :) thanks, will follow the other issue.
