### ISSUE TITLE
File picker not showing cloud files but only photo gallery

### ISSUE THREAD

**Issue by ifanchu** [miguelpruivo/flutter_file_picker#245]
**Describe the bug**
On iOS, I followed the setup and the picker came up correctly but there is no way to show cloud files like iCloud, Google Drive, and etc. Tried this on both simulator and actual devices. I must be missing some very basic configuration here...please help. 

**Issue details**
1. Platform (Android/iOS) iOS
2. Platform OS version: 13.3.1
3. File type (filter) — when applicable: Image
4. Detailed steps to reproduce. 

In iOS info.plist I have 

`
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Export images to camera roll.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Select picture to send.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>
`

and then I called file_picker in flutter like this

`
image = await FilePicker.getFile(type: FileType.image);
`

**Error Log**
There is no error. 

**Screenshots and/or video**

**Flutter Version details**
`
> flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/ifanchu/Projects/flutter
    • Framework revision 0b8abb4724 (9 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ifanchu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Evan’s iPhone XI  • 00008030-000E58AC1ED0802E            • ios • iOS 13.3.1
    • iPhone 11 Pro     • 26472200-3CBF-4E23-BB99-ADF86CD58E4B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone 11 Pro Max • 21DD5906-A9DE-40B4-BEA5-9D0E8F881C57 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
`

**Comment by miguelpruivo** [comment]
Hi @ifanchu, no problem. Like mentioned in the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#filters), when using `FileType.image` on iOS, it will open the photos app and not the files app, that’s why you can’t see it.

You need to use either `FileType.any` or, if you still want to restrict to images only, `FileType.custom` and provide a list of image extensions that you want to allow.

Thank you!

**Comment by ifanchu** [comment]
Thank you very much, I feel embarrassed that I missed this, thank you again for your timely response. It works now.

**Comment by ifanchu** [comment]
So if I use 

`image = await FilePicker.getFile(type: FileType.custom, allowedExtensions: ['jpg', 'png', 'HEIC']);`

It will open Files but not Gallery, so I can't get both here? Like starting with gallery and able to navigate up to Files?

**Comment by miguelpruivo** [comment]
@ifanchu that's right. On iOS you can't switch between Files app and Gallery, they are two different system apps.

**Comment by pmrajani** [comment]
@miguelpruivo i need to open Photo app while i set like this 

`image = await FilePicker.getFile(type: FileType.custom, allowedExtensions: ['jpg', 'png', 'HEIC', 'mp4']);`

How to do this?

**Comment by miguelpruivo** [comment]
@pmrajani thats not currently supported and it would require a custom view for photos app on iOS side to make it achievable.

If you want to pick photos from gallery you need to use `FileType.image` and extensions will be ignored. Sorry for any inconvenience.

**Comment by jeansoula** [comment]
Hi @miguelpruivo ! 

For me it is totally the opposite, on my simulator device I arrive instantly on Icloud drive... But I want to have access to camera and pictures from gallery.

Here is my command: 
`final List<File> files = await FilePicker.getMultiFile(type: FileType.image);`

Ios Simulator version : 13.4.1 

Where did I make a mistake ? 

_ps: I followed the tutorial in the wiki._

**Comment by miguelpruivo** [comment]
Hi @jeansoula, liked pointed [here on the Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#filepickergetmultifilepath), when using multiple picker on iOS, it will _always_ open the Files app as currently is not supported multiple picks from gallery app. If you want to open gallery, just use `getFile` instead.

There's an ongoing issue that you can follow that will add multiple picks on gallery as well (#233) and I have plans to have it added soon.

Thanks!

**Comment by jeansoula** [comment]
Thank you for your fast answer ! 👍 
I will be waiting your next release soon ;)
