### ISSUE TITLE
Open selective path with optional argument

### ISSUE THREAD

**Issue by bohrasankalp** [miguelpruivo/flutter_file_picker#249]
I am now sure if it could be an enhancement, Is it possible to pass a selective path while opening folder? Let me more explanatory, `file_picker` open base path depending on OS. If the option could be pass to reach a selective folder and open, and fallback to the base path.

like expected to open `/home/user/some-folder/` and case if it doesn't exist open folder `/home/user` current behavior?

**Comment by miguelpruivo** [comment]
Hi, thanks for your suggestion, but I’m not sure if I understood it properly.

I can’t really see how’d it happen to never have a path, as it’s up to the system to decide which starting path will be (based on type is iOS). On Android it’s just an intent. I don’t really specify a starting folder anywhere.
