### ISSUE TITLE
Absolute file path:/data/user/0/<app id>/cache/8636 Cache has no extension, so i cannot get the file extension

### ISSUE THREAD

**Issue by braysonjohn148** [miguelpruivo/flutter_file_picker#250]
**Describe the bug**
When i do:

 File file = await FilePicker.getFile(type: FileType.ANY);
file.path.toString().split('.').removeLast().toString())

Its bringing null. What can i do

**Issue details**
1. Platform (Android/iOS)

**Comment by miguelpruivo** [comment]
Hi, you can use `split('\').last` instead. That should give you the file name. However, this might be related to #234.

**Comment by braysonjohn148** [comment]
> Hi, you can use `split('\').last` instead. That should give you the file name. However, this might be related to #234.

The string that comes has no the extension at the end, so how can i split it

**Comment by braysonjohn148** [comment]
notesdoc.path.toString().split('.').removeLast(); Still i cannot get the file extension. Because the absolute path has not extension at the end

**Comment by braysonjohn148** [comment]
still couldn't get a work around for this, am still facing the same challenge: 
`Absolute file path:/data/user/0/<app id>/cache/8636`

So when i run  split('\').last on the path, as you can see. there is no extension.

I made follow up on #234  but couldn't get a write way to fix this. I understand its because of scoped storage permission but hoe to a work around it.

i tried android:requestLegacyExternalStorage="true" in the manifest but failS to build.

**Comment by miguelpruivo** [comment]
@braysonjohn148 I'm sorry. As of now there won't be a way around this for folders that require scoped storage, even with legacy support flag. 

This will likely happen on a few directories and you should ignore extensions for those files. I know that's not the best solution if you really need it. 

I'll try to add scoped storage support as fast as possible, really hadn't much time for personal projects.
