### ISSUE TITLE
I want to select multiple audio files, but I can only choose one at present

### ISSUE THREAD

**Issue by zhangruiyu** [miguelpruivo/flutter_file_picker#252]
I want to select multiple audio files, but I can only choose one at present
code:
List<File> file = await FilePicker.getMultiFile(
                    type: FileType.custom,
                    allowedExtensions: ['mp3', 'm4a', 'wav', 'aac']);

**Comment by miguelpruivo** [comment]
If this is on Android, you need to tap and hold when selecting on some devices in order to open the start the multi picker.

**Comment by miguelpruivo** [comment]
@zhangruiyu have you managed to solve this?

**Comment by miguelpruivo** [comment]
I'll assume you've managed to solve it. If not, feel free to reopen it with more details. Thank you.
