### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by aadarsh-patel** [miguelpruivo/flutter_file_picker#254]
**Describe the bug**
During build of the app.  I am getting the following warning on debug console.
>Note: C:\Users\Aadarsh\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_picker-1.6.3+2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerDelegate.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Issue details**
1. Android (Oneplus 6)
2. Android Pie
3. Filetype.custom

I am using the 'file_picker' package in this way,
`_selectedFiles = await FilePicker.getMultiFile(
      type: FileType.custom,
      allowedExtensions: ['sfb'],
    );`

**Error Log**
>Launching lib\main.dart on ONEPLUS A6000 in debug mode...
Note: C:\Users\Aadarsh\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_picker-1.6.3+2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerDelegate.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(31663): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(31663): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(31663): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(31663): Attaching FlutterEngine to the Activity that owns this Fragment.
W/FlutterView(31663): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterView(31663): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
D/FlutterView(31663): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@421766c
D/FlutterActivityAndFragmentDelegate(31663): Executing Dart entrypoint: main, and sending initial route: /

**Flutter Version details**
>[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.719], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
>
>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Aadarsh\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.
>
>[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>
>[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\Aadarsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1
>
>[√] Connected device (1 available)
    • ONEPLUS A6000 • 9361d496 • android-arm64 • Android 10 (API 29)
>
>• No issues found!

**Comment by miguelpruivo** [comment]
Thank @aadarsh-patel that's actually _not an issue_, it's due to the fact that it's using an old method API to retrieve the absolute file paths whenever possible — follow feature proposal #234. 

Anyway, that shouldn't have any impact on your app, it's just a deprecation warning.

Thank you!
