### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by Niubaobao** [miguelpruivo/flutter_file_picker#257]
When upgrading, please consider backward compatibility. Every time this component is hung, it will affect the user experience

**Comment by miguelpruivo** [comment]
@Niubaobao what do you mean? It supports all iOS versions (supported by Flutter, since 8.0).

**Comment by Niubaobao** [comment]
非常抱歉，应该不是你那边的问题，我在打包ios执行 pod install的时候发现找不到flie_pick最新版本的，导致无法打包，所以我现在是锁住了flie_pick的版本。等后面再看看吧

**Comment by Niubaobao** [comment]
I'm really sorry that it should not be your problem. When I was packing Ios to perform pod install, I found that I could not find the latest version of flutter_file_picker, so I cannot pack it. Therefore, I have locked the version of flutter_file_picker, and I will have a look at it later

**Comment by miguelpruivo** [comment]
No problem. If you are using the latest version don’t forget to add the `use_frameworks!` on your iOS/Podfile.
