### ISSUE TITLE
[Feature] Cleaning up files after use

### ISSUE THREAD

**Issue by jamesdixon** [miguelpruivo/flutter_file_picker#259]
Hi, not a suggestion but not a bug either, maybe more of a question?  

I noticed that on iOS (haven't looked at Android) that files are saved using `NSTemporaryDirectory()`. I realize this is cleaned up periodically via the OS but I'd like to be able to clear this after usage as many of the users of my phones tend to have low storage to begin with, which ends up in more support requests for me 😄

That said, would it be possible to offer an option to clear files after usage?

Or would it make more sense to move these files into the Flutter temporary directory since we can access that via `path_provider`? That would reduce reliance on your package to handle it.

Thoughts? Suggestions?

Thanks for all of your great work! Cheers.

**Comment by miguelpruivo** [comment]
Yes, I can add a call to prune those files, seems like a good option indeed.

**Comment by miguelpruivo** [comment]
@jamesdixon here you have it, landed on [1.9.0](https://pub.dev/packages/file_picker#190). You can now use `FilePicker.clearTemporaryFiles()` to prune those cached files explicitly.

Thanks for the suggestion!

**Comment by jamesdixon** [comment]
@miguelpruivo 🙏 appreciated!
