### ISSUE TITLE
File Picker rotates to portrait mode even when app is set to landscape mode

### ISSUE THREAD

**Issue by premingiet** [miguelpruivo/flutter_file_picker#262]
**Describe the bug**
My app is in landscape mode and when i use file picker to choose a file, it rotates to potrait mode.

**Flutter Version details**
>*output of* __flutter doctor -v__
```dart
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\premi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\premi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • E • G350RT058157000F • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Comment by miguelpruivo** [comment]
@premingiet have you tried on a different device? There’s no orientation set at all on the picker (you can check the plugins manifest file).

What’s probably happening is that the ROM you are using on your device, has a picker implementation that doesn’t honor orientation. This plugin only invokes the system picker. 

Simply try running in a simulator and see if it still happens.

Thanks!

**Comment by miguelpruivo** [comment]
Tried to see if I could replicate it but, in an official device, as I suspected it doesn't. This seem to be one of those issues where the Android rom file explorer doesn't have support to landscape and automatically rotates. Remember, this plugin _only_ asks for a system file explorer and provides it with the file restrictions and gives you the results, it doesn't implement a picker on its own. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/27860743/80817838-13cbcf00-8bca-11ea-83e9-9e417c0c422e.gif)

**Comment by premingiet** [comment]
thanks for reply, i did check, and figured out that if phone is set to portrait mode and not on auto-rotate mode, then even if app is set to landscape, still file picker gets into portrait mode. Once i set my device to auto-rotate mode, picker works as normal. I guess this is because picker relies on messages from native handle and not from application orientation.
