### ISSUE TITLE
Can not select csv

### ISSUE THREAD

**Issue by 3eggert** [miguelpruivo/flutter_file_picker#263]
**Describe the bug**
I'm writing a csv importer and want to choose the files to import. I started with your example code and modified it:
```
  void _openFileExplorer() async {
    setState(() => _loadingPath = true);
    try {

      _paths = null;
      _path = await FilePicker.getFilePath(
          type: FileType.custom,
          allowedExtensions:  ['csv', 'pdf']);
    } on PlatformException catch (e) {
      print("Unsupported operation" + e.toString());
    }
```
The extension 'pdf' is only added to check if I can select anything.
When I now tap on 'Open file Picker' I can select PDF-files but CSVs are greyed out.

**Issue details**
1. Platform Android
2. Platform OS version: 7.1.2
3. File type (filter) : csv

**Error Log**
D/FilePickerUtils( 8120): Allowed file extensions mimes: [text/comma-separated-values, application/pdf]
D/FilePickerDelegate( 8120): Type*/*

**Flutter Version details**
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0-3.2.pre at /home/eggert/flutter
    • Framework revision 2a7bc389f2 (9 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/eggert/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /home/eggert/Android/Sdk
    • Java binary at: /home/eggert/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/eggert/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • SM N910F   • 3fa465bc   • android-arm    • Android 7.1.2 (API 25)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by miguelpruivo** [comment]
@3eggert hi, I got to take a look but I’m afraid that csv is one of those  extensions that doesn’t map to any MIME and thus, won’t produce any effect. But it’s always a good idea to print something on the logs when this happens.

**Comment by 3eggert** [comment]
In the log I pasted is: 

 D/FilePickerUtils( 8120): Allowed file extensions mimes: [text/comma-separated-values, application/pdf]

I think text/comma-separated-values is the MIME, or am I wrong?

**Comment by miguelpruivo** [comment]
Yes! It should work unless the explorer itself is not honering properly. Does that happen when using the emulator? Or other device with a pure android rom?

**Comment by 3eggert** [comment]
I use a real device with a resurrection rom

**Comment by miguelpruivo** [comment]
Can you try in a different on? Or event emulator? There’s not warranty that MIME types are respected from all file explorers within each rom. Actually, even Photos from google doesn’t respect it, so it’s always up to the developer to add an extra protection if the user picks other formats.

**Comment by miguelpruivo** [comment]
Ok, @3eggert just tried with a Nexus 5X (API 29) and it works just fine as shown in the screenshot which are the 2 only files enabled to pick, which is correct as the MIME type is identified. 

![Captura de ecrã 2020-05-01, às 16 20 09](https://user-images.githubusercontent.com/27860743/80816555-a28b1c80-8bc7-11ea-8032-7d5beeeb1c56.png)

There's nothing I can further do here because every system file explorer handles the intent for picking files with _those_ restrictions, then, it's up to it to honor or not them. Sometimes they do, sometimes they don't. Also, have in mind, that this applies to Android only as iOS don't allow custom file explorers on its own.

I'll add this to the Wiki as this is not the first time that someone has issues with 3rd party file explorers not respecting the MIME types.

Thanks!

**Comment by 3eggert** [comment]
Thank you for your quick help. I think it is quite an important info, since I would say it means you can not rely that it is working on android to select a mime type. Which is not obvious since an extension is selected.

**Comment by miguelpruivo** [comment]
Indeed @3eggert, that has been an issue for Android developers for a long time. You _should_ always restrict as much as possible by providing the custom extensions, but you also _should_ protect the files after picking by iterating over them and see if those contain any invalid extension.

You just gave me an idea right now: I should be able to add a flag that will let the developer choose if I must enforce the types or not and when set to `true`, I'd return a specific error instead. That will at least remove the dev's boilerplate of iterating through the picked files and will have only the job of creating an alert if that error is thrown.

**Comment by Aravin** [comment]
It happens for me too.

**code**

```
_paths = (await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowMultiple: false,
        allowedExtensions: ['csv'],
      ))
```

**screenshot**

![Screenshot_1604762399](https://user-images.githubusercontent.com/4869265/98444965-f197a880-213a-11eb-939c-8330eb052d2b.png)
