### ISSUE TITLE
iOS file picker dialog not showing up

### ISSUE THREAD

**Issue by ravivlb** [miguelpruivo/flutter_file_picker#264]
file picker not showing up.

**Issue details**
1. iOS 
2. 13.4.1
3. Any
4. iOS warring pop up when trigged file picker

Attempt to present <UIDocumentPickerViewController: 0x10c60f6d0> on <FlutterViewController: 0x11000f800> whose view is not in the window hierarchy!

Flutter version 1.18.0-9.0.pre.98
Dart version 2.9.0 (build 2.9.0-5.0.dev c3ce873556)

**Comment by miguelpruivo** [comment]
@ravivlb how are you picking it?

**Comment by ravivlb** [comment]
@miguelpruivo file = await FilePicker.getFile( type: FileType.any);

**Comment by miguelpruivo** [comment]
Does that happen with the example app?

**Comment by ravivlb** [comment]
@miguelpruivo I am facing only in my code. I have fixed in Appdelegate of mine. Its due to view controller override issue.

**Comment by topjx** [comment]
I have the same problem, but can not find the cause, can you elaborate on your solution?

**Comment by topjx** [comment]
> @miguelpruivo I am facing only in my code. I have fixed in Appdelegate of mine. Its due to view controller override issue.

I have the same problem, but can not find the cause, can you elaborate on your solution?
