### ISSUE TITLE
Ios 13 getting Empty gallery for custom file type

### ISSUE THREAD

**Issue by rajeevjaiswal** [miguelpruivo/flutter_file_picker#268]
Below is the code snippet.

`void _openFileExplorer() async {
    var allowedExtensions = ["pdf", "png", "jpg", "jpeg"];
    _onLoading();

    try {
      _filePath = await FilePicker.getFilePath(
          type: FileType.custom, allowedExtensions: allowedExtensions);
    } on PlatformException catch (e) {
      debugPrint("Unsupported operation" + e.toString());
    }
    Navigator.pop(context);
    debugPrint("$_filePath");

    if (_filePath != null && _filePath.isNotEmpty) {
      _fileName = _filePath.split('/').last;
      _attachmentFile = new File(_filePath);
      var _fileExtension = _fileName.split('.').last;
      _fileExtension = _fileExtension.toLowerCase();
      int fileLength = await _attachmentFile.length();
      if ((_fileExtension == "jpeg" ||
              _fileExtension == "jpg" ||
              _fileExtension == "png" ||
              _fileExtension == "pdf") &&
          fileLength <= 5000000) {
        if (_fileExtension == "pdf") {
          isPdfFile = true;
        }
        setState(() {
          ViewUtils.showToast("Attachment added");
        });
      } else {
        _fileName = "";
        _filePath = null;
        _attachmentFile = null;
        ViewUtils.showToast("Only 5mb size of image or pdf is supported");
        _openFileExplorer();
      }
    } else {
//      ViewUtils.showToast("Attachment not added");
    }
  }`

**Comment by miguelpruivo** [comment]
What do you mean by blank screen? Would you mind to post a video/screenshot?

**Comment by rajeevjaiswal** [comment]
@miguelpruivo  I mean the iPhone gallery gets open but I don't see any files even though its present in the phone

**Comment by rajeevjaiswal** [comment]
@miguelpruivo yes the files app is blank. So Do I need to handle it differently for android and ios? because in android it works properly. Should I use FileType.any?

**Comment by miguelpruivo** [comment]
@rajeevjaiswal no, you should stick the same way, but if the Files app on iOS shows blank, that's because you don't have any files on iOS.

**Comment by andydean565** [comment]
a somewhat related issue, image trying to access a user's photos but nothing comes up unlike the apple 'photos'. do I need to set up 'cloudkit' for this?

**Comment by rajeevjaiswal** [comment]
@andydean565 May be you can open actionsheet and prompt user to either select Photo Library or File from the options and then depending on the option you can use FileType.image or FileType.custom.  Probably for your use case maybe you can direct set  FileType.image

**Comment by miguelpruivo** [comment]
@andydean565 you need to use `FileType.image` for that.

**Comment by andydean565** [comment]
@miguelpruivo  im already using `FileType.image` but images from the camera/photos arent appearing.

**Comment by miguelpruivo** [comment]
@andydean565 which version are you on?

**Comment by andydean565** [comment]
I was working on '1.5.0+2' as the latest was crashing on android but have just tried the latest on IOS and it works great and have retried it on android and the crashing seems to be gone and could be related to something else.

**Comment by miguelpruivo** [comment]
That’s good to know @andydean565. Sometimes it’s good to remove cached packages as they’ll leave trace of a lot of artifacts that could then conflict with newer versions.
