### ISSUE TITLE
Bug androidx.lifecycle..DefaultLifecycleObserver not found

### ISSUE THREAD

**Issue by ProFive** [miguelpruivo/flutter_file_picker#269]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS): Android 
2. Platform OS version:  10
3. File type (filter) — when applicable
FilePickerPlugin.java
4. Detailed steps to reproduce

Please add         implementation "androidx.lifecycle:lifecycle-common-java8:2.1.0"
https://stackoverflow.com/questions/55819499/androidx-lifecycle-defaultlifecycleobserver-not-found

**Comment by miguelpruivo** [comment]
Please, update to `file_picker: 1.9.0+1` and check the troubleshooting section for Android on the wiki. It has details for this there.

**Comment by ProFive** [comment]
Dear @miguelpruivo , 
This still error in my project. Please see the detailed log or help me with how to fix it. Thanks

See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
18 actionable tasks: 18 executed
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:10: error: cannot find symbol
import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  symbol:   class DefaultLifecycleObserver
  location: package androidx.lifecycle
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:20: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:36: error: cannot find symbol
            implements Application.ActivityLifecycleCallbacks, DefaultLifecycleObserver {
                                                               ^
  symbol:   class DefaultLifecycleObserver
  location: class FilePickerPlugin
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:43: error: method does not override or implement a method from a supertype
        @Override
        ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:47: error: method does not override or implement a method from a supertype
        @Override
        ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:51: error: method does not override or implement a method from a supertype
        @Override
        ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:55: error: method does not override or implement a method from a supertype
        @Override
        ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:59: error: method does not override or implement a method from a supertype
        @Override
        ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:64: error: method does not override or implement a method from a supertype
        @Override
        ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:258: error: cannot find symbol
            this.lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(activityBinding);
                             ^
  symbol:   variable FlutterLifecycleAdapter
  location: class FilePickerPlugin
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:259: error: incompatible types: FilePickerPlugin.LifeCycleObserver cannot be converted to LifecycleObserver
            this.lifecycle.addObserver(this.observer);
                                           ^
.pub-cache/hosted/pub.dartlang.org/file_picker-1.9.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:267: error: incompatible types: FilePickerPlugin.LifeCycleObserver cannot be converted to LifecycleObserver
        this.lifecycle.removeObserver(this.observer);
                                          ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: The plugin file_picker could not be built due to the issue above.
Exited (sigterm)

**Comment by miguelpruivo** [comment]
This is a dup of #223. You can see all the discussion there. I would like indeed to help you but that error that you have seems to be directly related with the resolution of some dependencies within your project. I’d first try to update Flutter to latest stable (1.17) and check #223 

I was never able to replicate that in any devices anyway.

**Comment by candyguy242** [comment]
same here, tried a lot but no help
