### ISSUE TITLE
Filetype.audio on iOS does not return File

### ISSUE THREAD

**Issue by herrmayr** [miguelpruivo/flutter_file_picker#273]
I'm not sure if I ran into bug when trying to pick an audio file from the iTunes Library on iOS with file_picker (1.6.3+2):

When trying to  get a file through

`File file = await FilePicker.getFile(type: FileType.audio);`

to copy/convert/work with it, the console logs

> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = 'ipod-library://item/item.mp3?id=779226311661032906' (OS Error: No such file or directory, errno = 2)

The file is downloaded in the Music Library, playable in the Music App, and it's not a drm-protected file but even a self-recorded test mp3 copied to the library.

Maybe I'm just doing something wrong (if, then sorry for this bug report! Any hints are appreciated ;) ), but maybe it's really a bug?

**Comment by miguelpruivo** [comment]
@herrmayr those files are not easy to handle, a quick search for getting paths for iPod-library files will let you find that. However, there’s a way and that is by loading directly the data from it and then creating a cached file.

How did you managed to get a file as iPod-library? Are you using an iPod device? I’m asking this because I wanted to replicate it so I can further investigate this but couldn’t get an iPod-library my own.

Thanks!

**Comment by herrmayr** [comment]
Thanks for the quick reply!

To get the ipod-library:// file, I simply used the getFile(type: FileType.audio) method from your package and launched my app on my iPhone.

As expected, when calling the method, the file picker loaded the library from the Music app where I could see all the downloaded audio files which are playable from within the Music app on the iPhone. When I select any track to pick it, the above mentioned error is printed to the console.

It would be great to be able to pick these files from the Music app as simply as it is with the other Filetypes :)

**Comment by rishabhshukla7** [comment]
flutter: [FilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null)
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      FilePicker._getPath (package:file_picker/file_picker.dart:85:39)
#4      FilePicker.getFile (package:file_picker/file_picker.dart:50:15)
#5      _UploadState.handleGalleryAudio (package:focal/pages/upload.dart:136:34)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestu<…>




My problem also seem as same as yours 
Did you have any Solution?

**Comment by herrmayr** [comment]
In fact, the problem continues to be the same for me ... I hope @miguelpruivo can find a solution; apart from that, the package works just perfectly :)

**Comment by miguelpruivo** [comment]
Hi guys, I’m not sure if it will possible to handle iPod-library files, I’ve been quite busy lately so hadn’t the chance to investigate, but I’m afraid they are handled as protected files and can’t be resolved to a path neither copy allowed — so I can cache and give you a path.

But, I’m yet not sure about this, so I’ll investigate before reaching an end conclusion.

Thank you for your comprehension!

**Comment by krishnaprasadgandrath-nooor** [comment]
Any update Yet?

**Comment by jignesh-mi** [comment]
Any Update?
