### ISSUE TITLE
..image selection screen?

### ISSUE THREAD

**Issue by gulmensedat** [miguelpruivo/flutter_file_picker#274]
Can we change the design of the image selection screen?

**Comment by miguelpruivo** [comment]
@gulmensedat actually that's not possible. The plugin asks the platform to launch an app to pick files (typically the native one). It doesn't actually renders a picker. So basically, you may expect users to have different pickers based on what they have installed on their Android phones. iOS will always be the same (native).

**Comment by gulmensedat** [comment]
> @gulmensedat actually that's not possible. The plugin asks the platform to launch an app to pick files (typically the native one). It doesn't actually renders a picker. So basically, you may expect users to have different pickers based on what they have installed on their Android phones. iOS will always be the same (native).

Not possible with flutter? This event is available in apps like Vsco and Instagram?

**Comment by miguelpruivo** [comment]
@gulmensedat you'd have to create your own — which is a lot of effort, as you'd have to query/stream assets from device to Flutter side, or, create it natively for both Android & iOS.

Typically, Instagram or VSCO use their own created galleries.
