### ISSUE TITLE
about `use_frameworks!`

### ISSUE THREAD

**Issue by WangJiaJun8922** [miguelpruivo/flutter_file_picker#275]
hi，if i have another framework, but it not support `use_frameworks!` how to solve？

**Comment by miguelpruivo** [comment]
@WangJiaJun8922 it must. If you are using packages that depend on swift modules, you’ll need that.

You can try using it along with `use_modular_headers!` as well and see if it helps, but bottom line, I’d say that I can’t see a reason for your app not supporting `use_frameworks!`. 

Alternatively, you can use any version below 1.7.0 that won’t require that, but you will miss features such as picking multiple files from iOS gallery at once.

**Comment by WangJiaJun8922** [comment]
@miguelpruivo thanks
