### ISSUE TITLE
Add hint about overwriting onActivityResult

### ISSUE THREAD

**Issue by beevelop** [miguelpruivo/flutter_file_picker#277]
Even though, this issue is not directly related to `flutter_file_picker` it might impact the usage of the plugin. If the user overrides the `onActivityResult` in his `MainActivity` and forgets to call `super.onActivityResult(...)`, the plugin fails silently when picking a file.

This exact thing happened in our case and it took us a few hours to get a hint about the origin of this issue. Unfortunately, there is no exception thrown to the user and it's quite hard to debug.

I'd like to suggest adding a quick disclaimer about this side-effect in the Android setup instructions:
> If your are overriding `onActivityResult` in your `MainActivity`, make sure to call `super.onActivityResult(...)` for unhandled activities. Otherwise picking a file might fail silently.

## Related
- https://github.com/flutter/flutter/issues/19103

**Comment by miguelpruivo** [comment]
Thank you for the insight @beevelop. I'll add it right away.

**Comment by beevelop** [comment]
Awesome, thank you 🍻
