### ISSUE TITLE
values.xml: error: file not found.

### ISSUE THREAD

**Issue by simone40love** [miguelpruivo/flutter_file_picker#278]
I downloaded the example, opened the following folder in Visual Studio Code 

C:\code\test\flutter_file_picker-master\flutter_file_picker-master

And tried to run the app.

I got this error with targetSdkVersion 29, but seems to work with 28. 

    defaultConfig {
        applicationId "com.mr.flutter.plugin.filepickerexample"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\code\test\flutter_file_picker-master\flutter_file_picker-master\example\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml: error: file not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by miguelpruivo** [comment]
Looks like some incompatibility with your build config settings. Can't really tell what at this moment as it doesn't happen with me, but you can stick with targetSdk 28 as of now.
