### ISSUE TITLE
getMultiFile ignores allowedExtensions

### ISSUE THREAD

**Issue by DebugTheCode** [miguelpruivo/flutter_file_picker#280]
When using FilePicker's getMultiFile function on Android with the given allowedExtensions "jpg, jpeg, png" I still can pick any mp4 (from Gallery).

**Issue details**
1. Platform - Android
2. Platform OS version - 10.0
3. File type (filter) — mp4
4. Call FilePicker.getMultiFile(type: FileType.custom, allowedExtensions: ['jpg', 'jpeg', 'png']); And pick a mp4 file. It'll pass.

Flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale nl-NL)
    • Flutter version 1.17.1 at /Users/x/flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/x/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/x/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • SM G960F • 213b8734c00b7ece • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by miguelpruivo** [comment]
Only mp4 or any other type?

**Comment by DebugTheCode** [comment]
As far as I tested mp4, but I think it's any other type.

**Comment by miguelpruivo** [comment]
Ok, if it's any other type as well, that's up to Android (system) to honor. There's nothing we can do about it other than showing an alert to the user or discarding invalid types. I've this [detailed on the wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue).

**Comment by DebugTheCode** [comment]
@miguelpruivo I'll give it a go on another device. I've tested it on a Samsung Galaxy S9, which has the highest marketshare as far as I know. It's a shame Samsung doesn't support it then...

**Comment by miguelpruivo** [comment]
@DebugTheCode yes it is. Even Google unfortunately doesn't support it in some of their apps (such as Google Photos picker when available fro the side bar).
