### ISSUE TITLE
Unable to Pick Pdf or any other document except the Image

### ISSUE THREAD

**Issue by Arpitjain7293** [miguelpruivo/flutter_file_picker#282]
In android the File Picker is working perfectly but when I run the same code in iOS I am unable to pick the file for now I am selecting pdf

**Issue details**
1. Platform (Android/iOS) - iOS
2. Platform OS version- 13.1
4. Detailed steps to reproduce - Select **ANY** from the filter type and try to select pdf or any doc it will not select screen will remain intact no process will be done

**Flutter Version details**
Flutter version 1.17.1

**Comment by miguelpruivo** [comment]
@Arpitjain7293 looks like it can be an issue with the file or/and it’s stored on the cloud. 

Native iOS picker handles quite well the files so it’s quite hard for it to “fail” picking. Try on a different device and see if that still happens or wait a bit more after selecting the file as it might be downloading.

**Comment by Arpitjain7293** [comment]
I was checking in iOS simulator.Can you please check in that and let me know if you get any soluation

**Comment by miguelpruivo** [comment]
Please record a video showing me what’s happening. Thank you.

**Comment by Arpitjain7293** [comment]
Please check this out. when clicking on any file weather it is from iCloud drive or from device nothing happend

**Comment by miguelpruivo** [comment]
@Arpitjain7293 thanks! That's weird. May you post the details of that simulator (version and model)? Did you try on a difference device?

**Comment by Arpitjain7293** [comment]
@miguelpruivo  may be this is the issue of OS version 13.1. Can you Please check this out I need this very much.

I am using xcode 11.1. so can this issue is from this xcode?

**Comment by miguelpruivo** [comment]
@Arpitjain7293 could you please try on a different device?

**Comment by Arpitjain7293** [comment]
ok let me check

**Comment by Arpitjain7293** [comment]
I have checked in another simulator the issue is same. Actually I dont have a real device.

I have checked with another swift document picker code it is working properly

**Comment by miguelpruivo** [comment]
Have you tried on a real device?

**Comment by Arpitjain7293** [comment]
I don't have real device

**Comment by Arpitjain7293** [comment]
Can you please let me know which flutter and xcode version you are using ?

**Comment by miguelpruivo** [comment]
Latest stable and latest Xcode version (non-beta).

**Comment by Arpitjain7293** [comment]
ok thanks

**Comment by Arpitjain7293** [comment]
@miguelpruivo Issue has been resolved. It was an issue of Mojave OS I have updated my OS and issue has been resolved.

Thanks for the support.
