### ISSUE TITLE
Read content of file

### ISSUE THREAD

**Issue by quetool** [miguelpruivo/flutter_file_picker#283]
Hi! I am trying to read the content of a csv file (could be txt either, doesn't matter) on Flutter Web

I'va added both plugins
```
file_picker: ^1.9.0+1
file_picker_web: ^1.0.0
```

How can I read the content? I can only get the name and the extension

**Comment by quetool** [comment]
For now I am doing it with javascript, but I do not like it. Not at all...


flutter side...
```
html.File f = await FilePicker.getFile();
js.context.callMethod("readFileContent", [
  html.Blob([f])
]);
this.timer = Timer.periodic(Duration(milliseconds: 500), (Timer t) {
  if (!mounted) return;
  String fileContent = js.context.callMethod('returnFileContent');
  if (fileContent != "") {
    print(fileContent);
    this.timer.cancel();
    this.timer = null;
  }
});
```

javascript side in index.html
```
var fileContent = ""
function readFileContent(blob) {
  var reader = new FileReader();
  reader.readAsText(blob, "UTF-8");
  reader.onload = function (evt) {
    fileContent = evt.target.result;
  }
  reader.onerror = function (evt) {
    fileContent = "error"
  }
}
function returnFileContent() {
  return fileContent;
}
```

If there is a better way to doing it natively with Dart please let me know

**Comment by miguelpruivo** [comment]
Closing as this is a non-issue, but we can further continue with the discussion.

As for your question, no, I don't really know a better way for it as of now. I've only managed to add flutter web support but didn't played with it much.

**Comment by quetool** [comment]
Thanks! I will try to find time in order to take a look at the code and maybe do a PR! Thanks!

**Comment by miguelpruivo** [comment]
@quetool feel free for it! Thank you!
