### ISSUE TITLE
Permission Granted Storage and Access Media Location OS Error: Permission denied, errno = 13 

### ISSUE THREAD

**Issue by visual-velocity** [miguelpruivo/flutter_file_picker#284]
I cannot select image from gallery. This is my logcat
FileSystemException: Cannot open file, path = '/storage/emulated/0/DCIM/s9camera/Pic_2020_06_04_19_36_15.jpg' (OS Error: Permission denied, errno = 13).
I'm using permission_handler package for handle permission. Storage and Access Media Location permission has already granted by user but the issue is generated every time when pick image or video from external storage. Inside manifest file we have added android:requestLegacyExternalStorage="true"
Suddenly i get issue on the production app , please support us

**Comment by miguelpruivo** [comment]
@visual-velocity does that happen only for that file? Could you please try reproduce it with the example app and provide me with the details for it?

**Comment by visual-velocity** [comment]
Actually this issue is generated on my company product app code. Due to
company protocol i'm not able to share the code.
only i shared you plugin name and what permission i called -
permission_handler and list Of android Permission =
[Permission.storage,Permission.accessMediaLocation];

**Comment by miguelpruivo** [comment]
Make sure that you `await` when checking the permission:
```
await Permission.storage.status;
                  if (!status.isGranted) {
                    await Permission.storage.request();
                  }
```
And also that you have the manifest entitlement:
```
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by visual-velocity** [comment]
hi,
i added
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission
android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission
android:name="android.permission.ACCESS_MEDIA_LOCATION"/>

**Comment by visual-velocity** [comment]
let me check the status

**Comment by visual-velocity** [comment]
All permission have PermissionStatus.granted

**Comment by miguelpruivo** [comment]
@visual-velocity remove the permission handler request/check before picking, you don't need that and might be conflicting with the plugin somehow.

**Comment by visual-velocity** [comment]
Ok buddy let me check

**Comment by visual-velocity** [comment]
I removed the permission handler request/check before picking, before that
I uninstalled the app and tested it again but again the same issue happened.

**Comment by miguelpruivo** [comment]
Please, try reproduce it with the plugin's example app. If it doesn't happen with it, then there must be something on your project, but it's hard to help you without any further details.

Make sure you are on the latest version of both plugins as well.

**Comment by visual-velocity** [comment]
yup! i have latest version

**Comment by miguelpruivo** [comment]
@visual-velocity see if you can make that issue happen with the example app please, otherwise, it will be hard to help you.

**Comment by visual-velocity** [comment]
I'm finding the issue please upgrade your library with Android 29.
Upgrade
compileSdkVersion 28 to compileSdkVersion 29 in build file
targetSdkVersion 28 to targetSdkVersion 29 (It's optional) in build file
android:requestLegacyExternalStorage="true" in Manifest file

**Comment by visual-velocity** [comment]
I'm so sorry Please ignore my last message or comment. Thank you for your
support. It's really appreciated.

**Comment by miguelpruivo** [comment]
Hi, what do you mean? It’s been using sdk 29 for a long time. [See here](https://github.com/miguelpruivo/flutter_file_picker/blob/b1f8cd60649ce8d34f50d2ad47e7333f0a782156/android/build.gradle#L25).

**Comment by visual-velocity** [comment]
Yes you are right that's why i post a comment that "Ignored my last
message".

**Comment by visual-velocity** [comment]
But when i added

android:requestLegacyExternalStorage="true" inside my manifest file and
passed the file path to Image.file widget that time the issue is generated.

**Comment by miguelpruivo** [comment]
Which android version is your device running on?

**Comment by visual-velocity** [comment]
Android 10 and Compile SDK Version 29

**Comment by miguelpruivo** [comment]
Does that happen only on _that_ device?

**Comment by visual-velocity** [comment]
Yes. It's happening on this device. We add
android:requestLegacyExternalStorage="true"
inside Manifest file inside my production app.

**Comment by miguelpruivo** [comment]
Yes, that is required on SDK 29+.

**Comment by miguelpruivo** [comment]
Does that happen when picking different files or only that one?

**Comment by visual-velocity** [comment]
It happened on every file

**Comment by miguelpruivo** [comment]
What's the brand of the device? Don't tell me it is a Motorola.

**Comment by visual-velocity** [comment]
One Plus One custom OS

**Comment by miguelpruivo** [comment]
Does that open with other device OS?

**Comment by visual-velocity** [comment]
No.

**Comment by miguelpruivo** [comment]
This looks like it's related to device's OEM rom and it might be one of those Android edge cases that would force you to weird workarounds in the code just to "try" to protect it. 

Actually, I'm not sure if there is much that we can do here. 😞

**Comment by visual-velocity** [comment]
Hi,
 First of all thank you so much for your response,

With Android SDK 29, if you add/enable
android:requestlegacyexternalstorage="true" to the manifest file of the app
then It shows the address/path of the file but is unable to load it inside
the image.file or any imageprovider.
When I removed the attributes from the manifest file so it's working fine.

Thanks
Miguel

**Comment by miguelpruivo** [comment]
@visual-velocity thats the weird thing, because with Android 29, you should need the request legacy flag set to true. 🤷‍♂️

**Comment by visual-velocity** [comment]
When I enable the attributes inside the manifest file then the path of the
file is not not accessible by any image provider.It is showing exception
"OS Error: Permission denied, errno = 13"

**Comment by visual-velocity** [comment]
It is running without enabling/needing the request legacy flag.

**Comment by miguelpruivo** [comment]
@visual-velocity this is weird, but well, if it worked for you, then let it be. 😄

Thank you!

**Comment by Hareshupw** [comment]
i'm facing same issue on iOS... Anyone has solutions?
then please tell me...

Thank you!
