### ISSUE TITLE
Desktop support of getDirectoryPath

### ISSUE THREAD

**Issue by DenchikBY** [miguelpruivo/flutter_file_picker#294]
**Describe the bug**
There is no go-flutter implementation for `getDirectoryPath` method, please add it.

**Error Log**
go-flutter: recovered from panic while handling call for method 'dir' on channel 'miguelruivo.flutter.plugins.filepicker': interface conversion: interface {} is nil, not map[interface {}]interface {}

**Comment by miguelpruivo** [comment]
Hi @DenchikBY this is not currently supported as mentioned on the [wiki here](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#-filepickergetdirectorypath).

But may be added on the feature.

**Comment by miguelpruivo** [comment]
@DenchikBY anyway, feel free to issue a PR if you manage to add it as I don't have much time right now.
