### ISSUE TITLE
App crashes on install from App Store (Android Only)

### ISSUE THREAD

**Issue by antmyers** [miguelpruivo/flutter_file_picker#297]
**Describe the bug**
I'm running into an issue where the app crashes on install but only for Android users. Also anyone who has an older version of the app and updated it is also experiencing this crashing problem.

**Issue details**
1. Platform: Android only. Works just fine on iOS, Works on android simulator, Works on a physical android device, both debug and release

**Error Log**
<img width="923" alt="Screen Shot 2020-06-17 at 12 42 09 PM" src="https://user-images.githubusercontent.com/44888349/84942921-73a60880-b098-11ea-89e1-0470421fe320.png">

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Flutter doctor -v output: Don't worry about the web versioning, im not concerned about that.

[✓] Flutter (Channel master, 1.19.0-5.0.pre, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.19.0-5.0.pre at /Users/andrewmyers/Developer/flutter
    • Framework revision 7519c383f9 (11 days ago), 2020-06-07 02:33:01 -0400
    • Engine revision 5709dc5318
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 578fa6bee9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andrewmyers/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Web Server • web-server • web-javascript • Flutter Tools

**Additional context**

**Comment by miguelpruivo** [comment]
@antmyers looks like you are running into similar issue of #296 and #293 which is a recent Flutter issue on latest versions. Other than that, it can also be a bad (or lack of) Android V2 migration. See [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-2) details on the Wiki.

**Comment by josephx86** [comment]
I have run into the same issue and I thought 7598d4608f9f4bf456a0130e88ccc8adfadb69b8 had fixed the issue. After checking crash logs, it seems there is a null value being passed to unregisterActivityLifecycleCallbacks.

**Comment by Theunodb** [comment]
Having the same issue in live. So far the crash reports are for Huawei devices only.

**Comment by antmyers** [comment]
Hey y’all. Just letting you know I fixed this issue by downgrading to Android plugin 3.6.2

**Comment by miguelpruivo** [comment]
@antmyers what do you mean by android plugin?

**Comment by altafkhan8719** [comment]
following version help me

change distributionUrl in gradle-wrapper.properties

distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

change the gradle version in android/build.gradle

classpath 'com.android.tools.build:gradle:3.6.0'

use the following version of file_picker
pubspec.yaml
file_picker: ^2.1.0
