### ISSUE TITLE
FilePicker.getMultiFilePath Not working in iOS Device

### ISSUE THREAD

**Issue by TulsiKavathiya** [miguelpruivo/flutter_file_picker#300]
getting error like 'Lost connection to device.'

**Comment by miguelpruivo** [comment]
This has not to do with the plugin. This is a relatively common issue with Flutter sometimes.

Try cleaning the project and then build it again. If the error persists, try building with Xcode instead and see what happens.

Thank you.

**Comment by miguelpruivo** [comment]
Any news on this @TulsiKavathiya ?

**Comment by TulsiKavathiya** [comment]
Yes it's working now

**Comment by miguelpruivo** [comment]
Thank you. Feel free to reopen this if you still experience any issue related to it.

**Comment by TulsiKavathiya** [comment]
Thank you for your support.
