### ISSUE TITLE
Cannot select fb2 extension

### ISSUE THREAD

**Issue by fassel** [miguelpruivo/flutter_file_picker#304]
First, thanks for the great library!

I have 4 extensions ('epub', 'pdf', 'fb2', 'mobi') and I can not choose one of them **fb2**

```
File file = await FilePicker.getFile(
      type: FileType.custom,
      allowedExtensions: ['epub', 'pdf', 'fb2', 'mobi'],
    ).catchError((error) async {...}
)
```

**Issue details**
1. Platform: Android and iOS
2. Platform OS version, Android: 10 and iOS: 13.5
3. File type (filter) — fb2

**Screenshots and/or video**
[
<img width="368" alt="Screenshot 2020-06-27 at 12 07 12" src="https://user-images.githubusercontent.com/4815246/85920149-95aa4280-b871-11ea-811d-f07e3d701970.png">
](url)

**Flutter Version details**
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-DE)
    • Flutter version 1.17.3
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at ~/Android/sdk
    • Platform android-29, build-tools 30.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by miguelpruivo** [comment]
Hi, 

I’m sorry that you are experiencing this. As mentioned [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1) on the Wiki you can see that extension filters won’t always be honoured by all Android devices. In fact, this works both ways. You can either have some devices not preventing other extensions from being selected or some extensions that you want to allow (your use case) and not being respected as well.

This doesn’t mean that all devices won’t do it, probably some will. But that’s up to the explorer installed on the device to handle/support this. The plugin only asks the underlying platform to launch a file picker (whichever that might be installed) and handle those extensions.

So, a rule of thumb, is that file picker will do a first filter with provided extensions but you should always validate that your picked files met your extension requisites and/or discard with a custom error for example, so your users can pick it again.

Thank you.

**Comment by fassel** [comment]
ok, thank you for the explanation
