### ISSUE TITLE
PlatformException when special character in file name

### ISSUE THREAD

**Issue by bdoubleu86** [miguelpruivo/flutter_file_picker#305]
I am using file_picker 1.12.0 on a real android device. I didn't test on iOS so far.

I know this is bad naming, but when I have special character in a file name e.g. video**%**xxx.mp4 which I copied from Windows to my device, then I get this bug when I try _await FilePicker.getFilePath(type: FileType.video)_:
```
[MethodChannelFilePicker] Platform exception: PlatformException(unknown_path, Failed to retrieve path., null)
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(unknown_path, Failed to retrieve path., null)
```
Is this a know issue? Is there any workaround or is this a (hopefully unlikely) scenario I have to accept?

Thanks in advance for your help!

**Comment by miguelpruivo** [comment]
Yes, there’s already an issue reported by that where names couldn’t be sanitized. I must say that for me it’s almost impossible to have a file name with forbidden characters such as that one. If you try on Mac, Linux, Android or iOS, won’t accept that file name as those are system restricted.

I’m surprised that windows allows you to do so. Nevertheless, I’ve tried solutions around it without success and it’s probably better for users to be aware they don’t have a proper file name to avoid future undesired scenarios IMO.
