### ISSUE TITLE
file picker doesnt work in Edge / Internet Explorer

### ISSUE THREAD

**Issue by Freundschaft** [miguelpruivo/flutter_file_picker#306]
flutter_file_picker_web doesnt work for edge

no error is thrown, the function just never returns

`File _file = await FilePicker.getFile(type: FileType.custom, allowedExtensions: ['.pdf']);`

**Comment by miguelpruivo** [comment]
Is it working on other browsers? I'm afraid you need to be on `master` Flutter channel for it to work on Edge.

**Comment by Freundschaft** [comment]
yes its working on other browsers. do you have an issue or merge request you can refer to on the flutter github?

**Comment by miguelpruivo** [comment]
Yes, [see here](https://github.com/flutter/flutter/issues/45162#issuecomment-580215456).

**Comment by Freundschaft** [comment]
well the app works in general for me, its only the file uploader prompt that fails,

**Comment by miguelpruivo** [comment]
@Freundschaft ok, that might be something related with Windows integration. I don't have a way to test on Edge as I'm a Mac owner, but feel free to issue a PR or purpose a solution if you come up with it. Thank you!

**Comment by Freundschaft** [comment]
alright, will try some things today and report back later

**Comment by Freundschaft** [comment]
@miguelpruivo I think I foudn the bug:

in https://github.com/miguelpruivo/flutter_file_picker/blob/master/file_picker_web/lib/file_picker_web.dart#L50

.onChange is assigned after .click().

if I turn it around, first assigning onChange, and then running .click() the event fires in edge.

shall I do a merge request or will you add the fix yourself?
