### ISSUE TITLE
The plugin file_picker could not be built due to the issue above.

### ISSUE THREAD

**Issue by KanwarpreetS** [miguelpruivo/flutter_file_picker#310]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
[✓] Connected device (1 available)

• No issues found!

At time of build;

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
18 actionable tasks: 1 executed, 17 up-to-date

/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:10: error: cannot find symbol
import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  symbol:   class DefaultLifecycleObserver
  location: package androidx.lifecycle
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:20: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:38: error: cannot find symbol
            implements Application.ActivityLifecycleCallbacks, DefaultLifecycleObserver {
                                                               ^
  symbol:   class DefaultLifecycleObserver
  location: class FilePickerPlugin
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:45: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:49: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:53: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:57: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:61: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:66: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:275: error: cannot find symbol
            this.lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(activityBinding);
                             ^
  symbol:   variable FlutterLifecycleAdapter
  location: class FilePickerPlugin
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:276: error: incompatible types: FilePickerPlugin.LifeCycleObserver cannot be converted to LifecycleObserver
            this.lifecycle.addObserver(this.observer);
                                           ^
/Users/tedkomputers/.pub-cache/hosted/pub.dartlang.org/file_picker-1.12.0/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:284: error: incompatible types: FilePickerPlugin.LifeCycleObserver cannot be converted to LifecycleObserver
        this.lifecycle.removeObserver(this.observer);
                                          ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin file_picker could not be built due to the issue above.
Process finished with exit code 1

**Comment by miguelpruivo** [comment]
@KanwarpreetS I don't want to sound rude, but please, I'm constantly answering to the same issues when the solutions are already posted on the documentation. 😢 

Please, check it before opening a new issue. For this particular one, a possible solution is described [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-3).

Thanks!
