### ISSUE TITLE
Add limit to maximum selection

### ISSUE THREAD

**Issue by aditya21** [miguelpruivo/flutter_file_picker#314]
I encourage you to add new suggestions that you think that can make file_picker even a better package.

Can you please add a way to limit maximum number of selected items?

**Comment by miguelpruivo** [comment]
Hi, @aditya21 this has a limitation that was already explained in #118 and #287.

**Comment by miguelpruivo** [comment]
I may end up adding, but then I suspect that new issues will arise with: _"max files limit is not working on Android"_.

**Comment by aditya21** [comment]
Thanks @miguelpruivo.
