### ISSUE TITLE
iOS: Could not instantiate codec via image_provider, while picked .mp4

### ISSUE THREAD

**Issue by DebugTheCode** [miguelpruivo/flutter_file_picker#317]
When picking a .mp4 file from the `Photos` app into a Video player, the following error occurs: 

```
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:4419:5)
#1      instantiateImageCodec (dart:ui/painting.dart:1722:10)
#2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
#3      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:862:24)
<asynchronous suspension>

```
It throws this error because my app tries to detect if it's a video or image. When it's a video it uses the `VideoPlayer` widget, otherwise it'll display the image. Because it thinks it's not a video, it'll try to display it as an image, but obviously it could not display a video as an image.

Using the Files app and picking the exact same file, it works fine.

I see there's a difference between te file path when picking from the Photos and Files app.

Photos:
`/private/var/mobile/Containers/Data/Application/8A8AC7BF-A1D9-4B27-880D-0F468F30C9B8/tmp/DKImageAssetExporter/REZBOThDNDMtRDQ0Ni00RTNFLUE3QTctQzI3OEMxNkJDRDkxL0wwLzAwMQ==/615808393.598785/AVAssetExportPresetHighestQualitycom.apple.quicktime-movie/IMG_6062.MP4`

Files: `/private/var/mobile/Containers/Data/Application/8A8AC7BF-A1D9-4B27-880D-0F468F30C9B8/tmp/[package_name]-Inbox/35fc8452-bf87-11ea-8807-064f10a873a6.mp4`

In the Photos path there's a .apple.quicktime-movie extension that's probably causing this.

P.s.: copying the file to another directory does not solve the problem.

**Issue details**
1. Platform iOS
2. Platform OS version 13.5.1
3. Detailed steps to reproduce: Pick a .mp4 file from the Photos iOS app and try to play it with the `video_player` package. The error occurs. Try picking the same file via the Files iOS app and play it. Works as it should.

**Flutter Version details**
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale nl-NL)
    • Flutter version 1.17.5 at /Users/x/flutter
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/x/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/x/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone • 00008030-0006654021E8802E • ios • iOS 13.5.1

! Doctor found issues in 1 category.

```

**Comment by miguelpruivo** [comment]
Does that happen with your movie file? Might be related with that particular one.

**Comment by miguelpruivo** [comment]
Anyway, it could also be related with DKImageController (the 3rd party lib used to pick content from iOS). In that case, a issue might be filled on its own repo.

**Comment by DebugTheCode** [comment]
@miguelpruivo It happens with every .mp4 file picking with the Photos app. About the DKImageController lib, I didn't use it before, so I don't know how and what it could be. Surely I want to file an issue, but I don't know the ins and outs of using it.

**Comment by miguelpruivo** [comment]
Well, if this is happening with all mp4 files and this is an issue with the plugin, that could affect all users but so far no one as reported it so could it be related to your app/device?

Do you have a replicable steps for it?

**Comment by DebugTheCode** [comment]
@miguelpruivo You've made me think about it again and I fixed the issue. Apple is apparently having it's own version of the h264 codec: aac . I wasn't checking for that. The reason why I filed it here is because I thought there was a difference with the Photos and Files pickers.

**Comment by miguelpruivo** [comment]
@DebugTheCode yes, that makes sense, because Photos app converts automatically all media inside it to be supported by Apple.
