### ISSUE TITLE
question: mocking plugin

### ISSUE THREAD

**Issue by jamesdixon** [miguelpruivo/flutter_file_picker#318]
Hello @miguelpruivo!

I had a quick question for you:

Do you have any suggestions on how to mock this plugin?

Basically, I'm trying to create an integration test to open and pick images over and over again to simulate a real-world scenario where a user may pick (or take a photo) hundreds of times in the span of 1 or 2 hours. I want to evaluate memory usage, etc.

Let me know your thoughts.

Cheers.

**Comment by miguelpruivo** [comment]
Hi @jamesdixon!

That’s a good question, this is a tricky one if we want to actually simulate a lot of different picks. Usually, with Flutter and mockito I mock my dependency calls  with results I want to test.

That’s possible here as well, but you’ll probably be retrieving the same file every time which isn’t realistic. With integration tests you may be able to actually tap in different files and pick them (just like a real use case) but I’m not sure about how easy it could be.

Have you checked how if image_picker plugin has some examples? If so, it should be exactly the same (with minor adaptations of course).

Let me know your findings as I’m also interested in this as well.

Miguel

**Comment by miguelpruivo** [comment]
That’s what I suspected. Any suggestions?

**Comment by jamesdixon** [comment]
In the interest of time, I've basically bypassed the file picker and am just loading an image from the asset bundle and then saving it to the photo gallery. My goal is to get some idea of memory usage when loading lots of images over a long period of time so I think this at least gives me a few data points!

**Comment by miguelpruivo** [comment]
If you don’t need to automate it, I’d suggest you to run the app in profiling mode and check the memory consumption after multiple picks.

**Comment by jamesdixon** [comment]
Yep, that is exactly what I'm doing! Fun stuff :)

**Comment by miguelpruivo** [comment]
Let me know if you find any performance issue related to the plugin itself.

Thank you!

**Comment by IkhwanSI13** [comment]
Hi @jamesdixon & @miguelpruivo 
Currently, I try to mock file_picker in my integration test, but it does not work for now. I try this [solution](https://stackoverflow.com/questions/56588555/how-to-test-imagepicker-in-flutter-driver) and check the image_picker one, but don't know how to mock file_picker correctly. Can I know how you guys did it?

**Comment by miguelpruivo** [comment]
@IkhwanSI13 you'll have to mock a channel response like you'd do for any other platform channel plugin, I'd say.

**Comment by IkhwanSI13** [comment]
@miguelpruivo thank you for the response. I tried it now, and got an error like: 
>[MethodChannelFilePicker] Platform exception: PlatformException(error, Invalid argument: Instance of 'FilePickerResult', null, null)". 

I don't know how to set the return value properly and actually, it's my first time to mock at flutter. I decided to create a question about it at [stackoverflow](https://stackoverflow.com/questions/69030659/platformexception-invalid-argument-after-trying-to-mock-file-picker-for-integra). I hope you can check it, thanks.
