### ISSUE TITLE
Ios FileType.custom don't show images

### ISSUE THREAD

**Issue by kartercs** [miguelpruivo/flutter_file_picker#319]
Hello,

I'm not sure if it's a bug or if it's an Ios limitation but i can't select any image typer when i use the FileType.custom like this : 

    File file = await FilePicker.getFile(type: FileType.custom, allowedExtensions: ['jpg','png','doc','pdf']);

It's working fine on android and i can select whatever i need. but in ios it only show me the explorer with files like pdf and doc inside. I can use FileType.media for images/videos and it works well but i would like to be able to select all 4 FileTypes in one screen. 

Else i guess i need to have two buttons one for the files and the other for images, but it will be the first time i need to check for platform on flutter and it feel like it's going against it's purpose. 

Thanks in advance for your help.

**Comment by miguelpruivo** [comment]
Hi, please check the wiki as there you have details about each `FileType` filter. Anyway, using `FileType.custom` on iOS will always open Files app. The gallery only opens with `FileType.media`, `FileType.image` or `FileType.video` types.

And yes, for the gallery itself right now it’s not possible to support extension filters, only for the Files app.

Thank you for your comprehension.

**Comment by kartercs** [comment]
Thanks for you quick answer. 

Yeah i looked at the wiki and it clearly shows a gif with an Iphone where it select ttf, jpg and doc in the same Files app, that's why i taught that was possible. I looked at the example files and in the gif it uses a getMultiFilePath() with type: FileType.custom, and allowedExtensions: ['jpg', 'ttf', 'doc'] when i do exactly the same i do not have access to the images on my device.

But thanks anyway, i'll try to make 2 buttons on Iphone.

**Comment by kartercs** [comment]
Thanks for your quick answer.

Yeah i looked at the wiki and it clearly shows a gif with an Iphone where it select ttf, jpg and doc in the same Files app, that's why i taught that was possible. I looked at the example files and in the gif it uses a getMultiFilePath() with type: FileType.custom, and allowedExtensions: ['jpg', 'ttf', 'doc'] when i do exactly the same i do not have access to the images on my device. Of course when i do a FileType.media, i do have access to the images.

I also tried adding NSPhotoLibraryUsageDescription and UIBackgroundModes in Info.plist in case it helped but it did not sadly.

I've found out that it's not a problem with the display of the images it's just that images are not in same folder as other files when you take them, that's why i couldn't see it event thought the image picker find it.

But thanks anyway, i'll try to make 2 buttons on Iphone.

**Comment by boiyelove** [comment]
@miguelpruivo  Has there been a solution to this yet?
I'm experiencing the same problem. Can only select custom filetypes with FileType.custom on IOS.
It's not showing images

**Comment by miguelpruivo** [comment]
@boiyelove that's not an issue, that's how it works. On iOS you can't "specify" file types for the camera roll, you only can for the Files app (which is opened with the `FileType.custom`).

If you want to pick images/videos you need to use the `FileType.image`, `FileType.video` or `FileType.media` for both. Check the docs, you have all it there.
