### ISSUE TITLE
Cannot get the file extension.

### ISSUE THREAD

**Issue by NaingMyoThawNMYT** [miguelpruivo/flutter_file_picker#322]
Cannot get the file **extension**.

**Comment by miguelpruivo** [comment]
@NaingMyoThawNMYT I'm not sure exactly what do you mean by this. Do you want to extract the file extension from picked files? Because if so, you have a few ways to do so.

**Comment by miguelpruivo** [comment]
@NaingMyoThawNMYT you should have the same. Print the file path after picking it.

**Comment by NaingMyoThawNMYT** [comment]
No it doesn't. I already tried with your demo code too. And file path end with just filename and not include extension.

And file name is also number and not actual filename.

**Comment by miguelpruivo** [comment]
@NaingMyoThawNMYT that happens when for some reason file name can't be resolved and a copy is cached/returned with a random number. You are probably picking it from downloads folder or similar. Try on a different folder.

**Comment by NaingMyoThawNMYT** [comment]
Other folder and GDrive is ok. Just for download folder is not ok.
I hope you can fix that.
Good Luck!

**Comment by miguelpruivo** [comment]
@NaingMyoThawNMYT it's a permission limitation, I'm afraid there isn't much a I can do there. Sorry. 😞
