### ISSUE TITLE
Files are not returned in the order they are selected

### ISSUE THREAD

**Issue by pbie42** [miguelpruivo/flutter_file_picker#325]
**Describe the bug**
Multiple file selection files are not returned in the order they are selected as shown in the Example App. 

**Issue details**
1. Platform (Android/iOS) - iOS
2. Platform OS version - 13.4 then updated and tested with 13.6
3. File type (filter) — FileType.custom - allowed extensions ['wav']
4. Detailed steps to reproduce - Using either getMultiFile or getMultiFilePath, files are never returned in the order they are selected. The order appears to be completely random.

**Error Log**
N/A

**Screenshots and/or video**
N/A

**Flutter Version details**
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4, locale en-US)
    • Flutter version 1.17.5 at /Users/pbie/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/paulbie/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • PB iPhone • numbers • ios • iOS 13.6

• No issues found!

**Additional context**
N/A

**Comment by miguelpruivo** [comment]
Hi @pbie42 it's up to the OS to determine this. I'm afraid I can't do anything about it. iOS delegates just give you with the picked list and that is returned immediately to the Flutter side in the same order as it is received.
