### ISSUE TITLE
Method to serialize Object Files in web plugin

### ISSUE THREAD

**Issue by lennhv** [miguelpruivo/flutter_file_picker#326]
I've working in a project for mobile and web using both plugin version depending on the platform, in web version i not found a way to serialize file object to show file preview or upload throw async call using some library like http.  Diving the documentation i not found how convert Blob object to byte object (List<int>), i suggest include a method to get serialized object.

**Comment by miguelpruivo** [comment]
@lennhv do you have any suggestions? I haven't worked much with web side so any contributions will be welcome.

**Comment by lennhv** [comment]
Excellent, i implement it.

**Comment by miguelpruivo** [comment]
Closing as this should be traced on #328.
