### ISSUE TITLE
iOS video pick compression

### ISSUE THREAD

**Issue by cataCostea** [miguelpruivo/flutter_file_picker#327]
Is there a way to turn off the compression when choosing a video, or at least to get it at a better resolution, maybe at 1920×1080 resolution?

**Comment by miguelpruivo** [comment]
Hi @cataCostea, yes that is. I may add it.

**Comment by cataCostea** [comment]
Do you have a timeline for this? An approximate date please?

**Comment by miguelpruivo** [comment]
Today if I got the time. Have in mind that `video compression` label will still appear briefly but no compression will be applied.

**Comment by cataCostea** [comment]
This is not a problem for me. Thank you very much.

**Comment by miguelpruivo** [comment]
I'll keep you posted.

**Comment by miguelpruivo** [comment]
@cataCostea version `1.13.0` is published and now has a `allowCompression` property when picking that will set whether to return the uncompressed file or compressed based on it. Defaults to `true`.

Thank you!

**Comment by cataCostea** [comment]
Hello. Thank you very much for the update, it solves the compression property, we can get it not compressed. However, although the video is not compressed, the "compressing" label is being displayed a long time on the screen as if the compression is being done. I know that de compression label should only flash, is there anything that can be done?

**Comment by miguelpruivo** [comment]
There is no way to remove that. Other iOS users have complained about it. You can see [here](https://stackoverflow.com/a/48643954/6919963). It shouldn't be on screen for much time anyway. 

Can you confirm that videos aren't being compressed? Hadn't much time to test it after implementing but it was just a flag.

**Comment by cataCostea** [comment]
Yes, I confirm that the video is not compressed but when loading the video it acts like it is compressing, and takes the same time to load as if the video is compressing.

**Comment by miguelpruivo** [comment]
@cataCostea I'm sorry to hear that. That's on OS end at that point, on the plugin I'm just waiting for the delegate to return the paths after being selected.

If you manage to find a way to go around it, I'd be happy to add it as well.

**Comment by cataCostea** [comment]
Ok, thank you for your help. If I find a way to solve the problem I'll tell you.

**Comment by cataCostea** [comment]
I made a test, after all it looks like the OS is still doing some kind of compression. The picked file was 4k 60 fps with the size of 494 Mb and the file that loaded in the app was 4k 60 fps with the size of 348 Mb (these large files are only to test the limits).
