### ISSUE TITLE
How to pick image from gallery on iOS?

### ISSUE THREAD

**Issue by leszekkrol** [miguelpruivo/flutter_file_picker#329]
Hello, Is it possible to pick image from gallery on iOS?

**Comment by miguelpruivo** [comment]
Hi @leszekkrol, sure, you can [check the documentation](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#methods) to find out to use it.

Anyway, you just need to use `type: FileType.image` or `type: FileType.media`.

**Comment by leszekkrol** [comment]
@miguelpruivo Thanks for help, That's right I found it in the documentation, but I wasn't sure if FileType.media takes the user to the gallery
