### ISSUE TITLE
App crashes as soon as i select a file

### ISSUE THREAD

**Issue by Baksman** [miguelpruivo/flutter_file_picker#330]
App crashes as soon as i select a file(pdf) it has been working fine for over 5 months , all of a sudden it stopped working

**Comment by miguelpruivo** [comment]
@Baksman hi, what would make it stop working magically? I need more details. Thanks!

**Comment by Baksman** [comment]
It was logging cant be able to read lenght as at yesterday today it doesnt log anything, its really surprising how the plugin coukd break

**Comment by miguelpruivo** [comment]
I suspect from the file/phone itself otherwise it wouldn't stop working without any change. 

Anyway, in order to help you out, I need more details such as stack trace, phone model, OS, etc.

**Comment by miguelpruivo** [comment]
Have you manage to solve it?

**Comment by Baksman** [comment]
No i havent , it doesnt log any message , just crashes, may be you should try at your end with pdf, i am using samsung a5 and s7 both are version 7+ android deveices

**Comment by miguelpruivo** [comment]
In my end is working properly but I only have one Android real device.

If you manage to replicate it with the simulator, please provide me with the steps.

**Comment by Baksman** [comment]
show me the snippet of code u use to pick the pdf, just that part u use in picking the pdf

**Comment by Baksman** [comment]
i guess the issue is from your update, before it only exposes pdf when i open my file explorer now ot shows all files

**Comment by miguelpruivo** [comment]
What version are you using?

**Comment by Baksman** [comment]
file_picker: ^1.13.0+1 ,

**Comment by miguelpruivo** [comment]
How are you picking?

**Comment by Baksman** [comment]
await FilePicker.getFile(type: FileType.custom,allowedExtensions:["pdf"]);

**Comment by Baksman** [comment]
formerly i was using this await FilePicker.getFile(type: FileType.CUSTOM, fileExtension: "pdf"); and it was working, but while i was building the  app for release mode it threw a syntax error i had to change it to the one above

**Comment by miguelpruivo** [comment]
I need you to post logs of what's happening when your app crashes.

I'm afraid you aren't running on Flutter 1.17 or above. If so, please update and see if it still happens.

**Comment by Baksman** [comment]
Thank you soo much it nows works fine after i upgraded my flutter
