### ISSUE TITLE
Error: No named parameter with the name 'allowCompression'

### ISSUE THREAD

**Issue by VagnerWillian** [miguelpruivo/flutter_file_picker#333]
Compiler message:
/C:/Users/USUARIO/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/file_picker-1.13.0/lib/file_picker.dart:38:9: Error: No named parameter with the name 'allowCompression'.
        allowCompression: allowCompression,
        ^^^^^^^^^^^^^^^^
/C:/Users/USUARIO/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/file_picker-1.13.0/lib/file_picker.dart:67:9: Error: No named parameter with the name 'allowCompression'.
        allowCompression: allowCompression,
        ^^^^^^^^^^^^^^^^
/C:/Users/USUARIO/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/file_picker-1.13.0/lib/file_picker.dart:84:7: Error: No named parameter with the name 'allowCompression'.
      allowCompression: allowCompression,
      ^^^^^^^^^^^^^^^^
/C:/Users/USUARIO/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/file_picker-1.13.0/lib/file_picker.dart:104:7: Error: No named parameter with the name 'allowCompression'.
      allowCompression: allowCompression,
      ^^^^^^^^^^^^^^^^

I tried:
flutter clean
flutter cache repair
nothing fix :(

**Comment by bgetsug** [comment]
This combination of versions is working for me when compiling for web:
```yaml
# pubspec.yaml
  file_picker: 1.12.0 # temporary fix for file_picker_web >=1.0.1 ?
  file_picker_web: ^1.0.1+2
```

**Comment by VagnerWillian** [comment]
Fixed. Thanks!

**Comment by miguelpruivo** [comment]
@VagnerWillian are you trying to compile for web or mobile?
