### ISSUE TITLE
Difference in behavior of flutter_file_picker

### ISSUE THREAD

**Issue by prihodulkin** [miguelpruivo/flutter_file_picker#336]
Hi! I ran into problem. In old versions of your plugin (like '0.6.5+3') pickImage() on Android returned File with his path in the file system of device. But on IOS I had got a file with the path after caching. In new versions I note that in both tasks I get caching File. Can I get information about original address of picked file in the device file system?

**Comment by miguelpruivo** [comment]
Hi, is this on the right place? Because I've never had a `pickImage()` method.

Thanks!

**Comment by prihodulkin** [comment]
Oooooops. I'm sorry :)
