### ISSUE TITLE
Getting file on IOS

### ISSUE THREAD

**Issue by prihodulkin** [miguelpruivo/flutter_file_picker#337]
Hello! It's me again. Now I use your plugin to pick file paths but I've faced with the same troubles on IOS. I tried to pick one file many times but I got a File with different path everytime. For example, I've got

Users/admin/Library/Developer/CoreSimulator/Devices/4A7CEE0B-1C82-42AF-8C13-CCD0052C57B4/data/Containers/Data/Application/CDD33BAC-E66D-4F37-8CDA-93F4E6141645/tmp/B177A10D-92DD-417A-974D-11DEFD12CA37.jpeg

and

Users/admin/Library/Developer/CoreSimulator/Devices/4A7CEE0B-1C82-42AF-8C13-CCD0052C57B4/data/Containers/Data/Application/CDD33BAC-E66D-4F37-8CDA-93F4E6141645/tmp/BEAEE1E5-20C4-4FF6-99DC-9B526656C828.jpeg

for one image in gallery. Do you now, what is the reason of this behavior? I suppose that it is depend on caching files because of "/tmp/" in path.  Thanks for attention.

**Comment by miguelpruivo** [comment]
Hi @prihodulkin, iOS doesn't allow you to get the original file path, the delegate always provides you with a cached copy. Then it's up to the developer to keep it in a different directory (for example, in the app's content folder) or just consume the file for any purpose (upload, send, modify or whatever) and then the OS releases the cache whenever needed.

The plugin also offers you with the `cleanTemporaryFiles()` method if you want to force a cache cleanup for some reason.

Closing as WAI.
