### ISSUE TITLE
Does this package require any permissions

### ISSUE THREAD

**Issue by Arjunraj-k** [miguelpruivo/flutter_file_picker#338]
Does this package require any permission to be added on android manifest? Cant see any in documentation.

**Comment by miguelpruivo** [comment]
Hi @Arjunraj-k you have a whole section just for describing what you need on manifest or info.plist file 😁

Check it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup).

**Comment by Arjunraj-k** [comment]
I Saw that but my question is does it require permissions with permission tag, Like READ_EXTERNAL_STORAGE permission?

**Comment by miguelpruivo** [comment]
It was once required, but at this point it shouldn't, as the plugin should take care of it on its own.

**Comment by Arjunraj-k** [comment]
ook, Thank you for your time and this wonderful package.
