### ISSUE TITLE
In IOS. I can only select files from iCloud. Is it possible to select file from the mobile device?

### ISSUE THREAD

**Issue by VagnerWillian** [miguelpruivo/flutter_file_picker#345]
In IOS. I can only select files from iCloud. Is it possible to select file from the mobile device?

**Comment by miguelpruivo** [comment]
@VagnerWillian sure, use the filter type for what you need. Refer to the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api) for more details.

Thanks!

**Comment by VagnerWillian** [comment]
but on IOS, it only opens iCloud files, that is, if I am logged in to it and not the local files.

**Comment by miguelpruivo** [comment]
@VagnerWillian what do you mean by local files? If you use `FileType.any` it will show you the Files app where you can browse both iCloud + offline files.

If you want to pick from gallery, you need to use `FileType.media`.

**Comment by VagnerWillian** [comment]
Do I need to configure any Container?

**Comment by miguelpruivo** [comment]
@VagnerWillian what do you mean? It's not mandatory. What kind of files are you trying to pick?

**Comment by VagnerWillian** [comment]
I'm sorry I'm brazilian. I'm translating through Google Translate.
So, I need the user to select pdf, in addition to images. However, I don't know much about IOS. When I tap to select the file, it asks for login to iCloud, does it mean that it is only possible to select file from the cloud?

**Comment by miguelpruivo** [comment]
@VagnerWillian não é obrigatório ter sign-in com a iCloud mas quase todos os utilizadores iOS (para não dizer todos, cerca de 99%) terão uma conta iCloud associada/logada portanto não haverá esse problema.

De todo o modo, em iOS não é possível aceder à galeria e ao mesmo tempo à pasta de ficheiros (Files app) onde estará eventualmente o PDF. Portanto sugiro que no fluxo da app seja pedido primeiro uma imagem, e aí usas o picker com o tipo `FileType.image` e então depois `FileType.custom` com o filtro para a extensão pdf.

Se pedir sign-in com iCloud (é possível que peça) podes fazer à vontade, mas como disse, quase todos os utilizadores iOS terão sempre uma conta iCloud para tirar partido das funcionalidades do iPhone. Um bocado como no Android todos terão conta Google associada.

**Comment by VagnerWillian** [comment]
E a questão do Container do IcloudKit?, pra que seria. Vi na documentação, fiquei curioso. Pode me dizer?

**Comment by VagnerWillian** [comment]
https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#ios

[...]Note: Any iOS version below 11.0, will require an Apple Developer Program account to enable CloudKit and make it possible to use the document picker (which happens when you select FileType.all, FileType.custom or any other option with getMultiFilePath()). You can read more about it here.
