### ISSUE TITLE
Single plugin for Android/IOS/Web

### ISSUE THREAD

**Issue by edandaria** [miguelpruivo/flutter_file_picker#346]
After many hours of investigation I now know how to make a plug-in for the three platforms. You only need to make very small changes in 5 files. I have tested it. Let me know if you want me to send details.

**Comment by miguelpruivo** [comment]
@edandaria if you are speaking of stubbing it won’t properly because `File` instance must be different on both html and io. But I’d be glad to know!

**Comment by edandaria** [comment]
I made a local copy and used relative references (ie path in .yaml), so you will have to adapt.

in file_picker.dart, change line 10 to:
final FilePickerPlatform _filePickerPlatform = FilePickerPlatform.instance;

in file_picker/pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.6
  file_picker_platform_interface:
    path: ../file_picker_platform_interface
  file_picker_web:
    path: ../file_picker_web

in file_picker_platform_interface.dart, line 56, add to method getFiles parameter: bool allowCompression = true,

in file_picker_web class name cannot be same as in file_picker, so I changed to:
class FilePickerWeb

in file_picker_web/pubspec.yaml
flutter:
  plugin:
    platforms:
       web:
        pluginClass: FilePickerWeb       <--- new class name 
        fileName: file_picker_web.dart

And that's it. Let me know if it helps.

**Comment by sidrao2006** [comment]
Hey @edandaria , why don't you open a pull request

**Comment by miguelpruivo** [comment]
FYI: I'm already working on this along with #234, expect a release this week. 🎉

**Comment by miguelpruivo** [comment]
Update is now live with [2.0.0](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) please, [see the changelog for details](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) of what have changed.

Let me know if you experience any issue! 🎉 

Thank you!
