### ISSUE TITLE
Android studio runs file_picker error

### ISSUE THREAD

**Issue by kelaisile** [miguelpruivo/flutter_file_picker#348]
Hello, I am running the latest version, file_picker: ^1.13.0+1
The following error is reported when running on a real Android machine, please help to see it, thank you

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/zhouqianjun/Desktop/zhouqianjun/OA/oa_flutter/build/image_picker/intermediates/library_manifest/debug/AndroidManifest.xml:16:13-18:75: AAPT: error: resource xml/provider_paths (aka com.htkj.oaflutter:xml/provider_paths) not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Exception: The plugin file_picker could not be built due to the issue above.

**Comment by miguelpruivo** [comment]
You need to [set your Android SDK environment variable](https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil) and also make sure you have Android X support (check it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-3)).

**Comment by kelaisile** [comment]
I have set the Android SDK environment variables, have migrated to Androidx, and still report the same error

**Comment by kelaisile** [comment]
iOS can run normally

**Comment by kelaisile** [comment]
This is the build.gradle file

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

//def keystoreProperties = new Properties()
//def keystorePropertiesFile = rootProject.file('key.properties')
//if (keystorePropertiesFile.exists()) {
//    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
//}

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))


android {
    compileSdkVersion 28

    allprojects{
        gradle.projectsEvaluated{
            tasks.withType(JavaCompile){
                 options.compilerArgs  <<  "-Xlint:unchecked"  <<
                 "-Xlint:deprecation"
            }
        }
    }


    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.htkj.oaflutter"
        minSdkVersion 17//16 or 17
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            //选择要添加的对应 cpu 类型的 .so 库。
            abiFilters 'armeabi', 'armeabi-v7a', 'x86', 'x86_64', 'mips', 'mips64', 'arm64-v8a'
//                        abiFilters 'armeabi-v7a'
        }

        manifestPlaceholders = [
                JPUSH_PKGNAME: applicationId,
                JPUSH_APPKEY : "096168f958494c99ecde644c", // NOTE: JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL: "developer-default", //暂时填写默认值即可.
        ]
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

**Comment by kelaisile** [comment]
The problem has been solved, thank you

**Comment by miguelpruivo** [comment]
@kelaisile what was it? Glad it’s working now for you.

**Comment by danielmessi13** [comment]
What is the solution ?

**Comment by Joao-b4** [comment]
I have the same problem, what is the solution?

**Comment by kelaisile** [comment]
My reason is that the third-party widget configured before has not been deleted completely

发自我的iPhone

**Comment by Joao-b4** [comment]
sorry, but I could not understand the reason, can you demonstrate the solution to your problem, so I can see if it applies to mine?
