### ISSUE TITLE
getMultiFilePath loads endlessly when tested on IOS (emulator)

### ISSUE THREAD

**Issue by jamorajj** [miguelpruivo/flutter_file_picker#349]
Good Day!

Just want to ask here if anyone experienced the same scenario. Was testing out the following snippet

```
Map<String, String> files = await FilePicker.getMultiFilePath(
                  type: FileType.custom,
                  allowedExtensions: ['pdf', 'png', 'jpg'],
                );
```

Works well on Android. However, on IOS, when the Files App is opened, and I select some files, it does not return to the app and loads endlessly on the Files app. (Screenshot below)
![Screen Shot 2020-08-03 at 7 19 17 PM](https://user-images.githubusercontent.com/2688631/89238999-882f6780-d62a-11ea-81c7-948e7cb511b8.png)

I also tried executing the [example project](https://github.com/miguelpruivo/flutter_file_picker/tree/master/file_picker/example) but it still happens

Unfortunately, there was no logs being listed on the console when I'm doing these steps. Could there be an additional setup to be done? Or is this something that others have experienced?

Flutter doctor -v output:
![Screen Shot 2020-08-04 at 8 26 32 AM](https://user-images.githubusercontent.com/2688631/89239606-456e8f00-d62c-11ea-894b-c1266ab66c49.png)

Thanks!

**Comment by miguelpruivo** [comment]
@jamorajj never seen this actually! Does that happen on a real device? It looks like the files are being downloaded. Anyway, this is being totally handled by the Files app, not the plugin. The plugin just gets the returned paths from it.

**Comment by miguelpruivo** [comment]
@jamorajj have you managed to fix it?

**Comment by jamorajj** [comment]
@miguelpruivo I haven't tested this on a real device though. An apple dev account is needed for that right? 

And yes it looks like the files are being downloaded. Tried waiting for it to finish for a bit but it was really just stuck there.

Haven't found a way to fix it, though if this is handled by the files app, maybe I can just opt in to use the plugin for images.

Thanks for your response :)

**Comment by miguelpruivo** [comment]
@jamorajj this shouldn’t happen at all, but I’m quite sure this could be a simulator issue. Try on a different simulator or with a valid iCloud account as I doubt that there’s any iOS users without it (Apple sort of forces you to when you setup an iPhone).

**Comment by jamorajj** [comment]
@miguelpruivo cool, will test this on a physical device and let you know how it comes up. Thanks :)

**Comment by jamorajj** [comment]
@miguelpruivo Just tested this on a physical device and an updated emulator (had to update the mac os, xcode, emulator updated as well) and it works now. Issue was I was using old versions of IOS I guess? 

Thanks for your help on this :)

**Comment by miguelpruivo** [comment]
No problem @jamorajj, glad it worked! 🙂

Let me know if you still have any issue.

Thanks!
