### ISSUE TITLE
Directory absolute path: '/' when directory selected from downloads.

### ISSUE THREAD

**Issue by ayush-srivastava-03** [miguelpruivo/flutter_file_picker#355]
FilePicker.getDirectoryPath()
Functon returns correct directory absolute path if selected from sd card, but returns '/' if selecting directory in "Downloads".

Redmi K20 running Android 10
gradle:
minSdkVersion 26
compileSdkVersion 29

Log:
I/FilePickerDelegate(32030): [SingleFilePick] File URI:content://com.android.providers.downloads.documents/tree/downloads/document/downloads
W/om.test_mobil(32030): Accessing hidden method Landroid/os/storage/StorageManager;->getVolumeList()[Landroid/os/storage/StorageVolume; (greylist, reflection, allowed)
W/om.test_mobil(32030): Accessing hidden method Landroid/os/storage/StorageVolume;->getPath()Ljava/lang/String; (greylist, reflection, allowed)
I/FilePickerDelegate(32030): Absolute file path:/

Flutter Version details:
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.1 at /Users/webwerks/flutter
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/webwerks/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/webwerks/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Redmi K20 (mobile) • 38773d07 • android-arm64 • Android 10 (API 29)

**Comment by miguelpruivo** [comment]
Hi. Downloads folder sometimes doesn’t actually contain the file but instead a reference for it or a previously downloaded file. It’s one of the few directories that can be handled most of the times unless #234 is implemented.

You can track it from there. As of now, I suggest you to present a message to your user letting him know that the file couldn’t be picked or similar.

Sorry for any inconvenience. Thanks.

**Comment by ayush-srivastava-03** [comment]
@miguelpruivo Thanks for the reply.
