### ISSUE TITLE
Is it possible to set the initial directory?

### ISSUE THREAD

**Issue by KavenWork** [miguelpruivo/flutter_file_picker#359]
I encourage you to add new suggestions that you think that can make file_picker even a better package.

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

**Comment by miguelpruivo** [comment]
@KavenWork on Android might be possible. On iOS I'm not actually sure.

**Comment by miguelpruivo** [comment]
Closing as there is no reliable to do so on iOS.
