### ISSUE TITLE
Remove NSAppleMusicUsageDescription permission

### ISSUE THREAD

**Issue by bhavinwebdesk** [miguelpruivo/flutter_file_picker#360]
Can you make the NSAppleMusicUsageDescription permission optional because that may the case when we want to allow only image and video files but not the music file?

If it is not the case, Can I disable somehow as I don't need NSAppleMusicUsageDescription?

**Comment by miguelpruivo** [comment]
@bhavinwebdesk all permissions are optional. You actually **_must only_** add those for the types that you want to. You can [check here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#optional-permissions) the details for each of it.

**Comment by bhavinwebdesk** [comment]
@miguelpruivo 

Thanks for the response but look like the code is still there. I have submitted the App to the App store with file_picker and it got rejected due to NSAppleMusicUsageDescription permission.

But look like my case is a special case so I will ask on StackOverflow or any other forum. Thanks for the great plugin.

**Comment by miguelpruivo** [comment]
Did you remove it of your plist? Make sure you are not picking audio in your app. Otherwise it will be required.

**Comment by bhavinwebdesk** [comment]
@miguelpruivo I have not added and I am not picking audio in my app still Apple force to add it.

**Comment by miguelpruivo** [comment]
@bhavinwebdesk if that’s happening that’s because the plugin is actually able to pick audio and so on. However, if you don’t pick audio you’ll never have your app requesting for audio permissions so it shouldn’t have any impact.

If I remove it from the plugin then it won’t be able to pick audio from users that actually want to.
