### ISSUE TITLE
How to display chosen file types after picking from gallery

### ISSUE THREAD

**Issue by kinuy123** [miguelpruivo/flutter_file_picker#362]
Just like  paths are displayed on screen,
 How can i  display chosen file types on screen eg  multiple videos selected and displayed on screen.

What I need to add in this function to achieve that?

static Future<List<File>> getMultiFile({
    FileType type = FileType.any,
    List<String> allowedExtensions,
    Function(FilePickerStatus) onFileLoading,
    bool allowCompression,
  }) async {
    final Map<String, String> paths = await _filePickerPlatform.getFiles(
      type: type,
      allowMultiple: true,
      allowedExtensions: allowedExtensions,
      onFileLoading: onFileLoading,
      allowCompression: allowCompression,
    );

    return paths != null && paths.isNotEmpty
        ? paths.values.map((path) => File(path)).toList()
        : null;
  }

**Comment by miguelpruivo** [comment]
Sorry, I didn't get your question. May you elaborate a bit better?

**Comment by kinuy123** [comment]
My question , I am able to select multiple videos from gallery,

I want to display those selected videos on screen.

**Comment by miguelpruivo** [comment]
@kinuy123 you need to do that on your app’s end. This plugin only lets you pick them.

**Comment by kinuy123** [comment]
Thanks for response.
