### ISSUE TITLE
How can I use the same code for Android and for Web

### ISSUE THREAD

**Issue by Wylarel** [miguelpruivo/flutter_file_picker#363]
Hello! I'm trying to do everything so that my application can use the same code to run on android and web, except that for the moment I manage to run on one or the other by importing one or the other package but for xemple I can't import file_picker_web on Android even if I don't use it. I use `kIsWeb` to to use one package or another depending on the platform. Here is the idea:

```dart
import 'package:file_picker/file_picker.dart' as SharedFilePicker;
import 'package:file_picker_web/file_picker_web.dart' as WebFilePicker;

File file;
if(kIsWeb)
       file = (await WebFilePicker.FilePicker.getFile()) as File;
else
       file = await SharedFilePicker.FilePicker.getFile();
```

**Details**
1. Platform (Android & Web)

**Error Log**
Here is the error log I get when I'm importing `file_picker_web` on Android: https://pastebin.com/raw/ntrbQtZU

**Flutter Version details**
```
[√] Flutter (Channel beta, 1.20.2, on Microsoft
    Windows [version 10.0.18362.1016], locale fr-BE)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (6 days ago),
      2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
[!] Android toolchain - develop for Android devices
    (Android SDK version 29.0.3)
    • Android SDK at
      C:\Users\timje\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program
      Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To
      resolve this, run: flutter doctor
      --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program
      Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at
      C:\Users\timje\AppData\Local\Programs\Microsof
      t VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 •
      android-x86    • Android 11 (API 30)
      (emulator)
    • Web Server (web)        • web-server    •
      web-javascript • Flutter Tools
    • Chrome (web)            • chrome        •
      web-javascript • Google Chrome 84.0.4147.125
```

PS: I guess that's not really an issue with the package itself (which, by the way, is wonderful, it works great in general) but I'm just really not sure how to do what I want to do...

**Comment by miguelpruivo** [comment]
Hi, this is a known limitation that also came across  #346. I’m yet to find a solution for it. I wish I could have it bundled on one package only, but having dart:html mixed with dart:io makes it impossible to achieve it.

**Comment by Wylarel** [comment]
Oh I was scared of that, but yeah, I understand. So it is really impossible ?

**Comment by miguelpruivo** [comment]
@Wylarel probably not, I might have to rethink of an implementation that could make it go around it. As of now, you'll need to stub on your end.

This is, create a conditional import to prevent that from happening, replace your imports with:
```
import 'package:file_picker/file_picker.dart' as SharedFilePicker 
if (dart.library.html) 
'package:file_picker_web/file_picker_web.dart' as WebFilePicker;
```
If this alone doesn't work, you may need to wrap your pickers on a common class (that can be used in both environments).

**Comment by Wylarel** [comment]
Yes, conditional import worked like a charm! That was all I needed 😃

This is my version of it:
`import 'package:file_picker_web/file_picker_web.dart' if (dart.library.io) 'package:file_picker/file_picker.dart';`

**Comment by miguelpruivo** [comment]
Glad it worked for you @Wylarel. 🎉
