### ISSUE TITLE
file.name is incorrectly set on IOS devices for file_picker_web

### ISSUE THREAD

**Issue by Freundschaft** [miguelpruivo/flutter_file_picker#366]
I am using file_picker_web and generally it works fine, but when I browse my flutter web application with an IOS device and select a file, the file.name result is incorrectly set.
In my case I am selecting .pdf files

`File _file = await FilePickerWeb.FilePicker.getFile(type: FileType.custom, allowedExtensions: ['.pdf']);`

so when I select a file, e.g. 'mycustomfile.pdf', I expect _file.name to be 'mycustomfile.pdf'.
Instead _file.name is set to 'mycustomfile.pdf.pdf', so it seems like the .pdf extension is appendended twice.
This only happens on IOS and not on windows/android devices.

**Issue details**
IOS

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
```
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version
    10.0.18363.1016], locale de-DE)
    • Flutter version 1.19.0-4.3.pre at C:\repos\flutter
    • Framework revision 8fe7655ed2 (7 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\android-sdk\
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\android-sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

**Comment by miguelpruivo** [comment]
Any news on this?

**Comment by Freundschaft** [comment]
not yet I am still waiting on the testers to report back

**Comment by miguelpruivo** [comment]
FYI: I'm already working on this along with #234, expect a release this week. 🎉

**Comment by Freundschaft** [comment]
thanks! according to the testers, the issue doesnt exist on Safari on MacOS

**Comment by miguelpruivo** [comment]
**Update:** [check comment](https://github.com/miguelpruivo/flutter_file_picker/issues/358#issuecomment-690812563).

**Comment by miguelpruivo** [comment]
Update is now live with [2.0.0](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) please, [see the changelog for details](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) of what have changed.

Don't forget to use only `file_picker` from now on.

Let me know if it fixed for you!
