### ISSUE TITLE
Error when trying to open file chooser.

### ISSUE THREAD

**Issue by ronytesler** [miguelpruivo/flutter_file_picker#369]
From the browser's console:
File chooser dialog can only be shown with a user activation.

**Comment by sidrao2006** [comment]
Hey @ronytesler , are you trying to open the native file picker directly without user interaction (clicking a button or something else)?

**Comment by ronytesler** [comment]
I have a InkWell with this code inside its 'onTap':
PickedFile pickedFile = await ImagePicker().getImage(source: ImageSource.gallery);
So the user is clicking, but not on the html <input> element.
I will try to reproduce it again and write the exact steps.

**Comment by ronytesler** [comment]
How to reproduce:
1. have this line in code:
 PickedFile pickedFile = await ImagePicker().getImage(source: ImageSource.gallery);
2. put a breakpoint in image_picker_for_web.dart on line 66 (    html.FileUploadInputElement input = createInputElement(accept, capture);)
3. important - close your project if running
4. run the project locally, then make the code in step 1 run (I have an InkWell with onTap that's running the code on step 1).
5. after the breakpoint is reached, press F7 on the keyboard ('Step Into' in Android Studio).
6. then press F9 ('Resume Program' in Android Studio).
You should see this on the console (and the file chooser dialog is not opened):
"File chooser dialog can only be shown with a user activation.      image_picker_for_web.dart:158"

**Comment by miguelpruivo** [comment]
@ronytesler you're misleading plugins here. `ImagePicker` is a [different plugin](https://pub.dev/packages/image_picker), this one is the `FilePicker`. 

Also, `image_picker_for_web` is a [different plugin](https://pub.dev/packages/image_picker_for_web).

<h5> But, you may want to try this one as it seems to solve your problem. So the solution might be replacing those plugins with `file_picker` and `file_picker_web`. 👀 😄 </h5> 

Closing as this doesn't apply here and OP might want to report on the linked plugins.

Thank you!

**Comment by ronytesler** [comment]
Sorry. But it still happens so:

1. have this line in code:
    await FilePicker.getFile(type: FileType.image);
2. put a breakpoint in file_picker_web.dart on line 45( final Completer<List<html.File>> pickedFiles = Completer<List<html.File>>();)
3. important - close your project if running
4. run the project locally, then make the code in step 1 run (I have an InkWell with onTap that's running the code on step 1).
5. after the breakpoint is reached, press F9 ('Resume Program' in Android Studio).
    You should see this on the console (and the file chooser dialog is not opened):
    "File chooser dialog can only be shown with a user activation. image_picker_for_web.dart:158"

**Comment by miguelpruivo** [comment]
I'm sorry, @ronytesler but you are still posting logs that point towards `image_picker` which is not _this_ plugin. Look at your step 5.

Might be some caching issue. Try cleaning and build again.

**Comment by ronytesler** [comment]
file_picker_web.dart is this plugin, right?
My mistake, sorry. The log is:
"File chooser dialog can only be shown with a user activation.        file_picker_web.dart:51"

**Comment by ronytesler** [comment]
@miguelpruivo Am I wrong?

**Comment by miguelpruivo** [comment]
@ronytesler no, you're not, but I'm afraid I can't really help you with this at the moment as I'm not able to replicate it. If you manage to replicate it on MacOS provide me with all of steps so I should be able to do so.

Thank you!

**Comment by LovelyYing** [comment]
I came across the same scene.
![image](https://user-images.githubusercontent.com/17565446/151125380-422b813c-81f1-4e2e-839d-6a71406b8b67.png)
![image](https://user-images.githubusercontent.com/17565446/151125138-28b3ff82-4c45-47ca-9825-690b7ec0f6d8.png)

**Comment by PaoloGi** [comment]
Same problem with Chrome on Windows.
Chrome on MacOS working fine

**Comment by braleyman** [comment]
I get the same exact results as @LovelyYing, using Chrome on MacOS, if I just try to arbitrarily open the file picker without any type of action, like a button press, to invoke it; however, it will work for me in the end because I only want to invoke it based on a user action anyways.
