### ISSUE TITLE
'source' is ignored on web.

### ISSUE THREAD

**Issue by ronytesler** [miguelpruivo/flutter_file_picker#371]
Inside image_picker_for_web.dart:
@override
  Future<PickedFile> pickImage({
    @required ImageSource source,
    double maxWidth,
    double maxHeight,
    int imageQuality,
    CameraDevice preferredCameraDevice = CameraDevice.rear,
  }) {
    String capture = computeCaptureAttribute(source, preferredCameraDevice);
    return pickFile(accept: _kAcceptImageMimeType, capture: capture);
  }

'source' is ImageSource.gallery, so computeCaptureAttribute returns null.

When running on mobile, the user is still able to use the camera.
Maybe there's no way to prevent it on mobile web?

**Comment by miguelpruivo** [comment]
Hi @ronytesler, the code you are posting is related to [image_picker](https://pub.dev/packages/image_picker) and not file_picker — which is this plugin, you probably mislead as the names are quite similar.

You may want to file an issue there.

Thank you!
