### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tndevl** [miguelpruivo/flutter_file_picker#373]
\flutter_windows_1.17.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FileUtils.java uses or overrides a deprecated API.

**Comment by miguelpruivo** [comment]
Hi, this is not an issue, just a warning about a deprecated method which as of now, is essencial, but everything should work as expected.

Thanks!

**Comment by bradsb** [comment]
Hi there, @miguelpruivo. The flutter team just merged in a pull request and released an update to suppress these warnings in [`url_launcher`](https://pub.dev/packages/url_launcher/changelog)

https://github.com/flutter/plugins/pull/3132

Would there be a reason to avoid that here?
