### ISSUE TITLE
Problem in handling more than 80+ images

### ISSUE THREAD

**Issue by SaiKrishnaReddy644** [miguelpruivo/flutter_file_picker#377]
The problem with this plugin is that when I tried pick more than 80 images the application is crashing. It is specifically happening in Iphone and oppo, vivo android phones.  Is there anyway to solve this issue. and also handling the format like heic files

**Comment by miguelpruivo** [comment]
@SaiKrishnaReddy644 this looks like a won’t fix here. I believe there is nothing I can do at the moment regarding this. On Android basically only paths are being referenced (mostly) if it crashes its probably even before delivering the results to the picker. 

On iOS, it uses DKImageController behind the scenes, you can try opening an issue there regarding this, but 80 pictures is a lot for a single pick, specially if you are trying to load all of them at once on your app (I suspect this).

Thank you for your comprehension.
