### ISSUE TITLE
Only working in debug mode 

### ISSUE THREAD

**Issue by lohitbura** [miguelpruivo/flutter_file_picker#379]
It's working fine in debug mode . But couldn't open the storage to pick image in release mode .
I am using targetSdk : 30
Using latest version of flutter and file_picker

**Comment by miguelpruivo** [comment]
@lohitbura never tried it with targetSdk 30 as most of the plugins are only yet supporting 29. I'll take a look.

**Comment by lohitbura** [comment]
> @lohitbura never tried it with targetSdk 30 as most of the plugins are only yet supporting 29. I'll take a look.

It's not even working in targetSdk 29 too
Also tried to use requestLegacyExternalStorage flag to true but not working in release mode

**Comment by miguelpruivo** [comment]
@lohitbura hum, I suspect there is something related with your app then, otherwise wouldn't work for anybody else for a while. 😄

What happens on release mode?

**Comment by lohitbura** [comment]
In release mode it's just asking access for media . But after clicking on allow nothing is happening . In debug mode it's going inside phone storage to pick files but not in release mode.

**Comment by miguelpruivo** [comment]
Use logcat to print what's happening when you try to launch it on release mode and post it here.

**Comment by lohitbura** [comment]
How can I track it after building an apk ?
It's working when I am using flutter run --release command but not when creating apk using flutter build apk 
I am sorry I am new in this .

**Comment by miguelpruivo** [comment]
If you have it connected you should be able to see it on the console as well. Run `flutter run --release`.

**Comment by lohitbura** [comment]
Just a sec

**Comment by lohitbura** [comment]
On first click it's not showing anything but allow media acess and nothing is happening after that. But when I am clicking again it's showing this 

I/flutter ( 3010): [MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null)
E/flutter ( 3010): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(already_active, File picker is already active, null)
E/flutter ( 3010): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
E/flutter ( 3010): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)
E/flutter ( 3010): <asynchronous suspension>
E/flutter ( 3010): #2      MethodChannelFilePicker._getPath (package:file_picker_platform_interface/method_channel_file_picker.dart:69)
E/flutter ( 3010): <asynchronous suspension>
E/flutter ( 3010): #3      FilePicker.getFile (package:file_picker/file_picker.dart:81)
E/flutter ( 3010): <asynchronous suspension>
E/flutter ( 3010): #4      _AddPostPage._pickImageFromGallery (package:sec2hand/ui_screens/addPostPage.dart:31)
E/flutter ( 3010): <asynchronous suspension>

**Comment by miguelpruivo** [comment]
@lohitbura looks like you're calling it multiple times on your app's code. Could you please show me the snippet where you use it?

**Comment by lohitbura** [comment]
this is the code where i am using file picker


import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';


import '../staticdata.dart';
import '../theme.dart';
import 'menu.dart';
import 'package:file_picker/file_picker.dart';


class AddPostPage extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return _AddPostPage();
  }

}


class _AddPostPage extends State<AddPostPage>{
  File _image;
  var _formKey = GlobalKey<FormState>();
  TextEditingController _desc = TextEditingController();
  GlobalKey<ScaffoldState> scaffoldKey = GlobalKey();

  var image;
  String postStatus = "Post";
  _pickImageFromGallery() async {
    try {
      image = await FilePicker.getFile(
        type: FileType.image,
      );

      setState(() {
        _image = File(image.path);
      });
    }catch(e){
      print(e.toString());
    }
  }

  Dio dio = new Dio();
  @override
  Widget build(BuildContext context) {
    final maxLines = 5;
    return Scaffold(
      key: scaffoldKey,
      appBar: AppBar(
        backgroundColor: Colors.white,
        leading: InkWell(
            onTap: (){Navigator.of(context).pop();},
            child:Icon(Icons.arrow_back_ios, color: Colors.black,)),
        title:  Text(
          "Sec2Hand",
          style: ThemeApp().appBarTheme(),
        ),),
      body: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            _getImage(),
            Text("Add Image", style: ThemeApp().textTheme(),),
          Form(
              key: _formKey,
              child:  Container(
                margin: EdgeInsets.all(12),
                height: maxLines * 30.0,
//            color: Colors.white30,
                child: TextFormField(
                  validator: (value) {
                    if (value.isEmpty) {
                      return 'Required';
                    }
                    return null;
                  },
                  maxLength: 139,
                  maxLines: maxLines,
                  controller: _desc,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                    hintText: "Write Something About it...",
                    fillColor: Colors.grey[300],
                    filled: true,
                  ),
                ))),
            Container(
              padding: EdgeInsets.fromLTRB(30, 0, 30, 0),
              width: double.infinity,
              margin: EdgeInsets.fromLTRB(0, 30, 0, 30),
              child: RaisedButton(
                onPressed: () {
                  if(postStatus=="Post") {

                    setState(() {
                      postStatus = "Uploading...";
                    });

                    if (!_formKey.currentState.validate()) {
                      return;
                    }
                    if (_image == null) {
                      final snackBar = SnackBar(
                        content: Text('Please Add a Picture'),
                      );
                      scaffoldKey.currentState.showSnackBar(snackBar);
                      return;
                    }
                    postPic();
                  }
                },
                color: Color(0xff005ad2),
                child: Text(
                  postStatus,
                  style: ThemeApp().buttonTextTheme(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  _getImage() {
    return Container(
        margin: EdgeInsets.all(12),
        child: Column(children: <Widget>[
          _image != null
              ? InkWell(
              onTap: () {
                _pickImageFromGallery();
              },
              child: Container(
                  width: 200.0,
                  height: 200.0,
                  child: new Image.file(
                    _image,
                    width: 200,
                    height: 200,
                  )))
              : InkWell(
              onTap: () {
                _pickImageFromGallery();
              },
              child: Container(
                  width: 100.0,
                  height: 100.0,
                  decoration: new BoxDecoration(
                      shape: BoxShape.circle,
                      image: new DecorationImage(
                          fit: BoxFit.fill,
                          image: new AssetImage("assets/logo.png"))))),
        ]));
  }

  void postPic() async {
    Response response;
    try {
      FormData formData = FormData.fromMap({
        "description": _desc.text,
        "image": await MultipartFile.fromFile(image.path, filename: image.path)
      });
      response = await dio.post(postAddApi, data: formData, options: Options(
        contentType: 'application/json',
        headers: {HttpHeaders.authorizationHeader: "Token " + token},
      ));

      if (response.statusCode == 200 || response.statusCode == 201) {
        final snackBar = SnackBar(
          content: Text('Post Uploaded Successfully'),
        );
        scaffoldKey.currentState.showSnackBar(snackBar);

        var profileResponse = await dio.get(profileApi, options: Options(
          contentType: 'application/json',
          headers: {HttpHeaders.authorizationHeader: "Token " + token},
        ));
        profileData = profileResponse.data;
        Navigator.of(context).pushReplacement(
            MaterialPageRoute(builder: (context) => Menu(1)));
      }
      else {
        final snackBar = SnackBar(
          content: Text('Something went wrong...'),
        );
        scaffoldKey.currentState.showSnackBar(snackBar);
      }
    } catch(e){
      setState(() {
        postStatus = "Post";
      });

      final snackBar = SnackBar(
        content: Text('Something went wrong...'),
      );
      scaffoldKey.currentState.showSnackBar(snackBar);
    }
  }

}

**Comment by lohitbura** [comment]
I am pretty sure that I am implemeting it right . I guess problem is in scoped storage.

**Comment by lohitbura** [comment]
I applied following permission to my menifest file  

  <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
 <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="appname"
        android:icon="@mipmap/launcher_icon"
        android:requestLegacyExternalStorage="true"
        >

**Comment by miguelpruivo** [comment]
@lohitbura hum nop that should work with scoped storage as well. Like I said, I’d have a lot of issues regarding this is this wouldn’t work with Android 10 (including some of my projects).

Would you mind running the example project and see if it works?

**Comment by lohitbura** [comment]
I created a new project and copy paste all the code and it worked . I don't know how. I tried everything in my previous project including flutter clean and all . But it worked in my new project. That's very strange but I am closing this issue for now . Thank you for helping me .

**Comment by miguelpruivo** [comment]
@lohitbura new projects are fully created with Android X support as a well as updated dependencies, might be something related.

Anyway, glad it fixed for you!
