### ISSUE TITLE
Migrate Go (Desktop) to support unified plugin changes

### ISSUE THREAD

**Issue by miguelpruivo** [miguelpruivo/flutter_file_picker#382]
Self explanatory.

**Comment by DenchikBY** [comment]
Any ETA for this? GO part isn't work too long time already...

**Comment by miguelpruivo** [comment]
@DenchikBY I'm sorry, but I hadn't the time yet as the only maintainer of this. Feel free to issue a PR if you have the time. Other than that, I don't have ETA, can be anytime actually, as soon as I have some room to work on it.

Thank you for your comprehension.

**Comment by miguelpruivo** [comment]
@DenchikBY did #542 completely fixed this?

**Comment by DenchikBY** [comment]
> @DenchikBY did #542 completely fix this? I hadn't the chance to test it out.

Yes, desktop works now again 🙂

**Comment by miguelpruivo** [comment]
Thank you for your contribution @DenchikBY. 🎉

**Comment by jlubeck** [comment]
hey @DenchikBY is this supposed to make the plugin work on macOS? 

I'm getting this error when trying to use it:

```
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method image on channel miguelruivo.flutter.plugins.filepicker)
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method image on channel miguelruivo.flutter.plugins.filepicker)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:35)
<asynchronous suspension>
#2      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:88:32)
<asynchronous suspension>
#3      _NewPostScreenState.build.<anonymous closure> (package:wippple/screens/new_post.dart:87:27)
<asynchronous suspension>


```

**Comment by FakenMaster** [comment]
@DenchikBY @miguelpruivo 
It looks like go-flutter can't recognize JSONMethodCodec in file_picker_io.dart [line 14](https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/src/file_picker_io.dart).
When run in macOS, got the error:

`
go-flutter: handling message on channel miguelruivo.flutter.plugins.filepicker failed: failed to decode incoming message: failed to decode method name: invalid message value type
`

**Comment by FakenMaster** [comment]
> hey @DenchikBY is this supposed to make the plugin work on macOS?
> 
> I'm getting this error when trying to use it:
> 
> ```
> flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method image on channel miguelruivo.flutter.plugins.filepicker)
> [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method image on channel miguelruivo.flutter.plugins.filepicker)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
> <asynchronous suspension>
> #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:35)
> <asynchronous suspension>
> #2      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:88:32)
> <asynchronous suspension>
> #3      _NewPostScreenState.build.<anonymous closure> (package:wippple/screens/new_post.dart:87:27)
> <asynchronous suspension>
> ```

You need to use go-flutter, the command is 'hover run'. Just check the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#desktop-go-flutter).
