### ISSUE TITLE
file picker version 2.0.0 is crashing for android 6.0 but works with new android versions

### ISSUE THREAD

**Issue by premingiet** [miguelpruivo/flutter_file_picker#387]
**Describe the bug**
I just updated to file_picker version 2.0.0 but now as soon as i pick file it crashes on android 6.0 device but works on android 10.0

**Issue details**
1. Platform (Android)
2. Platform OS version - Android 6.0
3. I tried on real android 6.0 physical device and android 10 emulator. But on android 6.0 its crashing

**Flutter Version details**
```dart
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.3 at C:\flutter
    • Framework revision 216dee60c0 (11 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\premi\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\premi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • XT1068 (mobile)                    • ZX1D63PNMH    • android-arm • Android 6.0 (API 23)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

**Comment by miguelpruivo** [comment]
@premingiet I’ve tried only on a few Android versions but I’m not sure about 6.0 (even if it should be ok). Could you please post your logs when it crashes? (You may need to use `adb logcat` if trace is not being logged on Flutter).

Thank you!

**Comment by premingiet** [comment]
okay let me try to get `adb logcat` logs and i will post here in few minutes

**Comment by premingiet** [comment]
I think it was issue with my phone, i was adding some delay deliberately for some testing to simulate a laggy device and i guess that was the issue, because i tested by creating another sample app and there was no issue. I also tested with android 5.0.2 motorola physical device and it has no issues too. But yes, previous version 1.13.3 still works well with that app no matter which device i test with.

This issue can be closed now.
