### ISSUE TITLE
Chrome OS/Android FolderPicker returns null. 

### ISSUE THREAD

**Issue by LibertyBeta** [miguelpruivo/flutter_file_picker#394]
**Describe the bug**
Flutter

**Issue details**
1. Android(Chrome OS)
2. 83
3. Attempt to Pick a Directory

**Error Log**
I/FilePickerUtils( 5453): Caching from URI: content://com.android.externalstorage.documents/tree/primary%3Akanso/document/primary%3Akanso
I/DecorCaptionView( 5453): Choosing forced status bar color.
E/FilePickerUtils( 5453): Failed to retrieve path: read failed: EISDIR (Is a directory)
I/flutter ( 5453): [MethodChannelFilePicker] Could not resolve directory path. Maybe it's a protected one or unsupported (such as Downloads folder). If you are on Android, make sure that you are on SDK 21 or above.
I/flutter ( 5453): null

**NOTES**
So, this seems to an issue with the android/chrome os bridge handling.

**Comment by miguelpruivo** [comment]
@LibertyBeta does this happen only with Chrome OS?

**Comment by LibertyBeta** [comment]
I'm running a few more tests, but looks like it.

**Comment by miguelpruivo** [comment]
I’ll take a look ASAP, despite not having a chrome os to test it out.

I’ll keep you updated. Let me know if you find more details.

**Comment by a-l-e-x-d-s-9** [comment]
I have a similar problem with my device(Android 9, with SDK 30).
I use "await FilePicker.platform.getDirectoryPath();" to choose a folder, but it returns null.
In the logs I get:
``` log
D/FilePickerDelegate(31186): [SingleFilePick] File URI:content://com.android.externalstorage.documents/tree/primary%3Aprojectflutter/document/primary%3Aprojectflutter
I/FilePickerUtils(31186): Caching from URI: content://com.android.externalstorage.documents/tree/primary%3Aprojectflutter/document/primary%3Aprojectflutter
E/FilePickerUtils(31186): Failed to retrieve path: read failed: EISDIR (Is a directory)
I/flutter (31186): [MethodChannelFilePicker] Could not resolve directory path. Maybe it's a protected one or unsupported (such as Downloads folder). If you are on Android, make sure that you are on SDK 21 or above.
``` 
I tried to choose folders that application can definitely access and write to.
Interestingly, the same code does work on an emulated device with Android 11.
Any ideas what might be the problem?

**Comment by miguelpruivo** [comment]
@a-l-e-x-d-s-9 this is actually odd. But I’ve yet to add sdk 30 support (even though it should be a straight implementation).

Which device are you trying on? Are you picking the same directory on both simulator and device?

**Comment by a-l-e-x-d-s-9** [comment]
Actually, I think that I'm not using 30 yet, I'm still with Android SDK Build-Tools 28.0.3.
It's not working on my OnePlus A3010 device, Android 9. And working on emulated Pixel 3a, Android 11.
Yes, I'm picking the same directory. On the both devices the app is writing to this directory, so I don't think there should be a problem to access this directory with getDirectoryPath.

**Comment by miguelpruivo** [comment]
@a-l-e-x-d-s-9 but by looking at your logs, the path can’t be retrieved on sdk 30, am I right?

**Comment by a-l-e-x-d-s-9** [comment]
Sorry for the confusion, I don't use SDK 30 at all, only SDK 28.
I fixed my original comment.
The problem with getDirectoryPath appears with SDK 28, as described in previous comments.

**Comment by LibertyBeta** [comment]
So, I've done a LOT of rooting around in the android API, and its limited to 11. I THINK it has to do with the way flutter is handled the scoped storage, which is to say, its not. By setting the legacy flag the app can run under the pre-11 versions of the permissions, which were more pervasive.

Looks like I might have to write my own impl. to take this into account. Honestly, this is all kind of a mess, and scoped storage needs better support in flutter.

**Comment by miguelpruivo** [comment]
@LibertyBeta if I could tell you the amount of issues I’ve seen with the way Android handles files  compared with iOS, you’d be surprised. Actually, I’d bet that 80%+ issues open here are related to Android due to its fragmentation or custom roms behaving differently in a way that sometimes you can’t even understand — for example, null pointers in variables that can’t be null.

Plus, some explorers honour filters where others don’t. This is terrible as it seems like a plugin issue and makes it unreliable somehow.

Anyway, if there’s anything that you find that can also contribute to help better improve the plugin, just let me know.

Thank you!

**Comment by LibertyBeta** [comment]
I'll let you know what my final work results in. I think one of the reasons scoped storage is a thing is to force a layer on top of the system level access.

**Comment by a-l-e-x-d-s-9** [comment]
Anything new regarding this problem, workarounds, suggestions?

**Comment by miguelpruivo** [comment]
@LibertyBeta any news on this?

**Comment by LibertyBeta** [comment]
I've been working on it, and thus far I've had to write my own solution
that uses a different method for accessing the files. It's not perfect, and
it has a lot of other issues with inter-opts.
-- 
Rainer Paskiewicz

**Comment by miguelpruivo** [comment]
Closing as this is quite low priority as of now and likely won’t be implemented anytime soon.

I’ll reopen if a considerable number of users is affected with it.

Nevertheless, thank you for your feedback!

**Comment by LibertyBeta** [comment]
No worries. I hope to share my code at some point, and I'll link it back
here if I can.
-- 
Rainer Paskiewicz
