### ISSUE TITLE
Unable to get absolute file path of files from SDCARD

### ISSUE THREAD

**Issue by premingiet** [miguelpruivo/flutter_file_picker#398]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS) - Android
2. Platform OS version - Android 10.0
3. File type (filter) - any
4. Detailed steps to reproduce - Try with the example app of file_picker. On selecting a file in SDCARD, instead of giving absolute path, it caches file into memory and then gives the cache location. This is causing an issue with my app, because i am actually saving the file location so when user opens the app next time, that file automatically loads. Now with this cache issue, i cant store the cache location, because next time that file might not be available in cache. So how should i store the file location of files that are in SDCARD ?

**Flutter Version details**
```dart
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.1 at C:\flutter
    • Framework revision 2ae34518b8 (7 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\premi\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\premi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1
```

**Comment by miguelpruivo** [comment]
@premingiet this was an intended updated behavior. Previously on iOS it used cached files and on Android it was trying to get the absolute path from original file and use it — and sometimes that path couldn’t even be retrieved.

Android team suggests that you should always use a cached file path if you need a path or use the file’s URI which points to the original file.

However, you are able to do whatever you want with that file. This is, if you need to store it in the SD card or any other location, just copy/move the given file into it after picking it.

On iOS for example Apple don’t even allows you to access the original path, this makes the plugin more reliable and consistent across platforms and was one of the requested features under #234.

Let me know if you managed to get it done. 

Thank you!
