### ISSUE TITLE
Filepicker Configure in ios 

### ISSUE THREAD

**Issue by rajorange** [miguelpruivo/flutter_file_picker#399]
Can anyone know how can i configure File Picker in ios ? i have use this code and i got wrong path. 

List<PlatformFile> pathsCustom = (await FilePicker.platform
              .pickFiles(type: FileType.any, withData: true))
          ?.files;
File  nFileCata = File(pathsCustom.first.path);

How i got the correct path in ios. it is working fine in android. Thanks in advance

**Comment by miguelpruivo** [comment]
@rajorange what do you mean by wrong path? If you get a path, then it's the correct path. 🙂

**Comment by rajorange** [comment]
Sir i can't access the private path. i am picking file from the icloud.

**Comment by miguelpruivo** [comment]
But what's the path that you get if you print it?

**Comment by miguelpruivo** [comment]
Closing as more information is required. Feel free to reopen with further details if you still have an issue.

Thank you!
