### ISSUE TITLE
iOS 14 PHPickerViewController support

### ISSUE THREAD

**Issue by espresso3389** [miguelpruivo/flutter_file_picker#400]
On iOS 14, UIImagePickerController has certain limitation and the UI gets a little misleading.
Do you have any plan to support PHPickerViewController?

**Comment by miguelpruivo** [comment]
@espresso3389 mind to detail which limitations do you see? I haven't got the time to migrate it to iOS 14 yet, but will do this week.

**Comment by espresso3389** [comment]
Yes, it still works on iOS 14. But it shows a dialog something like the following one:

![image](https://user-images.githubusercontent.com/1311400/93783836-29b85a00-fc67-11ea-9817-2ec922d0eef9.png)

And certain percentage of the users may mistakenly tap on the first "Select Photos..." button to get into trouble. It limits the app to select only subset of the photos and it's too difficult to get access to all the photos again.

It's a long story and I could not explain everything here but you can see what's UIImagePickerController on the following article:

[3 Reasons to Upgrade to iOS 14 Photo Picker](https://medium.com/macoclock/3-reasons-to-upgrade-to-ios-14-photo-picker-689e7171d7d9).

**Comment by miguelpruivo** [comment]
@espresso3389 but I believe that this is intended. I mean, if the user wants to allow only specific images to be accessed, will have to change it through settings to allow all.

All of the other apps I've seen so far, ask permissions the same way. I think the users will (or should) be familiar with it. What do you suggest as an alternative?

Have in mind that playing around it, might have the other side of the coin, where some devs want it to behave exactly like in the screenshot, this is, letting the users decide which permission to grant.

**Comment by miguelpruivo** [comment]
@espresso3389 I rad the article and it seems that we can actually access the pictures without granting permission, am I right? I highly doubt that Apple allows photo access (read) without granting permissions anyway.

**Comment by espresso3389** [comment]
> but I believe that this is intended. I mean, if the user wants to allow only specific images to be accessed, will have to change it through settings to allow all.
> All of the other apps I've seen so far, ask permissions the same way. I think the users will (or should) be familiar with it. What do you suggest as an alternative?

Yes, the change is intentional. But I think it's not intuitive... and I believe other apps will incorporate PHPickerViewController as soon as possible. (iOS 14 just got out suddenly and developers are just struggling with the change now...)

> I rad the article and it seems that we can actually access the pictures without granting permission, am I right?

Yes, you're right. Interestingly enough, their new security model permits us to choose pictures without any permission but it disables any intrusive access to the photo library.

Anyway, the change may be "breaking-change" so I think there should be some optional parameter to enable PHPickerViewController  support.

**Comment by miguelpruivo** [comment]
@espresso3389 I'll take a look into it. However, this would only work (as of now) for single picks, because multi picks are being made through a 3rd party package (DKImageController) which needs to implement it as well, otherwise would make it misleading to have permissions required on multi picks and not on single.

May make sense to implement on both at the same time. I will leave it for now, but consider it for a future update as soon as DKImageController has it on its end.

Thank you!

**Comment by miguelpruivo** [comment]
@espresso3389 added with [file_picker 2.0.1](https://pub.dev/packages/file_picker/changelog#201).

From now on, iOS 14 devices will have the same interface for both single and multi picks from gallery (image, video or both). 

Thank you for your suggestion!

**Comment by espresso3389** [comment]
@miguelpruivo 
After updating the plugin to 2.0.1, I found that I cannot access the file path returned by `FilePickerResult.files`.
And the reason seems apparent; the [loadFileRepresentation](https://developer.apple.com/documentation/foundation/nsitemprovider/2888338-loadfilerepresentation) document says that:

> This method writes a copy of the file’s data to a temporary file, which the system deletes when the completion handler returns.

And [the handler](https://github.com/miguelpruivo/flutter_file_picker/blob/24b4337d39b5a22b28b47a3578c88a264ab6fb2e/ios/Classes/FilePickerPlugin.m#L370) seems to complete before Flutter code actually accessing the file.

**Comment by miguelpruivo** [comment]
@espresso3389 this has been fixed with 2.0.1+2. Could you please give it a try?

**Comment by espresso3389** [comment]
@miguelpruivo Now it works for JPEG files but not for PNG files. I don't know what's the difference.

**Comment by miguelpruivo** [comment]
@espresso3389 weird! That should make no difference at all as it's using `public.item` UTI which should cover all files.

What do you get with PNG?

**Comment by espresso3389** [comment]
I was wrong. The behavior was same regardless of file type.
But if I just take a screenshot, or a camera picture, they cannot be accessible even with the file path...

**Comment by miguelpruivo** [comment]
@espresso3389 I'll have to do some more tests. I can't find much documentation/examples about this yet so I'll have to dig a little bit.

**Comment by espresso3389** [comment]
2.0.6 works fine! Thanks for your work!
