### ISSUE TITLE
File Picker 2.0 Web File Object Instantiation from PlatformFile Example

### ISSUE THREAD

**Issue by rmadugula** [miguelpruivo/flutter_file_picker#401]
Hello,

I'm new to flutter and using your extension.  I'm trying to use File Picker 2.0 with Flutter Web.  I see no clear, working, examples for web (the mobile work fine)

I am obtaining FilePicker Result:

    FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowMultiple: false,
      allowedExtensions: ['csv'],
      withData: true, //optional, i'm having the same problem either way
    );

I get a PlatformFile from FilePickerResult:

     PlatformFile fileresult = result.files.first

Using 'dart:html' I try and instantiate a File object:

    final File file = new File(
      fileresult.bytes,
      fileresult.name, //I've tried .path too, my understanding is that for web, it doesn't matter
    );

If I try and get the content of the file now using FileReader()... I just get a bunch of numbers, not the text in the file...

    final reader = FileReader();
    reader.readAsText(file);

Like so (example/extract/partial):
546991111094444441310869711044661089799107109971104478101116119111114116104328210197108116121321111023267104105999710311144444444444444444055495141325148494555545148324077111981051081014144444411897110641101011161191111141161049910410599971031114699111109444444131075101108115101121446710497108105110449011110411132671111141121111149711610511111044444444444444444055515541325049564556525252324077111981051081014144444410710110811510112164122111104111991111141124699111109444444131077971161161041011194467111114110105115104448411110932749710910111544444444444444444053495341325548554553545452324077111981051081014144444410946991111141101051151046411611110910697109101115469911110944444413106710497114105116121446711710910910511010311544679710810598101114327211110910132761119711011544444444444444444052495541325657524552495751324077111981051081014144444

I cannot for the life of me figure out what I'm doing wrong. 

Help? Advice? 

Thank you!

**Comment by miguelpruivo** [comment]
On the web you need to use the `bytes` property to create/upload whatever you want. Typically on Web you don't need `File` instances.

What are you trying to achieve?

**Comment by rmadugula** [comment]
Ok, thank you, you actually answered my question.  I simply took the bytes and converted to String for any future novices like me.

    String s = new String.fromCharCodes(fileresult.bytes);

And thank you again for your work on this plugin.

Kind Regards.

**Comment by miguelpruivo** [comment]
No problem, glad it worked for you @rmadugula! Let me know if you have any further doubts.
