### ISSUE TITLE
iOS how to get photo gallery option to select file

### ISSUE THREAD

**Issue by dpdev3** [miguelpruivo/flutter_file_picker#408]
I am using file_picker: 2.0.0

For iOS : How to get Photo Gallery to select file (Photos ) by using Flutter file_picker library ?

I have try following simple syntax, it is just opening Browser window to allow to select files from 'On My iPhone', 'iCloud Drive' options.

FilePickerResult filePickerResult = await FilePicker.platform.pickFiles(allowMultiple: true);

**Comment by miguelpruivo** [comment]
@dpdev3 you need to set the `type` property to `FileType.image` if you want images, `FileType.vídeo` if you want videos or `FileType.media` if you want to allow both. 

This is all well explained on the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#filters). 🙂
