### ISSUE TITLE
FileSystemException: Cannot retrieve length of file.

### ISSUE THREAD

**Issue by truongduy2611** [miguelpruivo/flutter_file_picker#409]
Getting, Unhandled Exception: FileSystemException: Cannot retrieve length of file.

**Issue details**
1. Platform iOS: Simulator and iPhone 6s
2. Platform iOS 14.0
3. Multiple Image Picker - file_picker 2.0.2
4. Error comes from  http.MultipartFile.fromPath

It works perfectly before  updating from v1.13.3 to v2.0.0

flutter doctor
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.4 at /Users/admin/flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 8E0F2686-6436-4EF9-B518-0C81C0370F0F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 2 categories.

**Comment by miguelpruivo** [comment]
Hi! Would you mind posting your stack trace as well as the lines you are using when encountering this error?

Thanks.

**Comment by truongduy2611** [comment]
This is an exception when I tried to get http.MultipartFile from your file path. 

FileSystemException (FileSystemException: Cannot retrieve length of file, path = '/Users/admin/Library/Developer/CoreSimulator/Devices/8E0F2686-6436-4EF9-B518-0C81C0370F0F/data/Containers/Shared/AppGroup/079159B6-F748-45CE-9DDE-B717CD48F967/File Provider Storage/photospicker/version=1&uuid=CC95F08C-88C3-4012-9D6D-64A413D254B3&mode=compatible.jpeg' (OS Error: No such file or directory, errno = 2))

**Comment by miguelpruivo** [comment]
Ok, this is related to #406. You can follow it from there.

Thank you!
