### ISSUE TITLE
Is there a way to know when the FilePicker has been cancelled ?

### ISSUE THREAD

**Issue by sallypeters** [miguelpruivo/flutter_file_picker#410]
Currently we use this syntax for grabbing a file :
```

 var imageResult = await FilePicker.platform.pickFiles(
          type: FileType.image,
        );
```

We would then check imageResult for null before proceeding.

However - if we wanted to provide error reporting to the user , there is no way to tell whether the user cancelled the FilePicker or whether there was an issue returning the File path , since imageResult (FilePickerResult) does not contain a flag informing of the operation status (Whether a file was picked, whether the user cancelled the operation etc).

**Comment by miguelpruivo** [comment]
@sallypeters typically whenever the user cancels the picker, it will return `null`. If an error is thrown, then you get an exception.

So you can assume that this is a reliable way to achieve what you’re looking for:
```
try {

    FilePickerResult result = await FilePicker.platform.pickFiles();

    if (result == null) { 
       print(“user canceled picker”);
    } else { 
       // do something with result
   }

} catch (ex) {
   print(“there was an error when picking: $ex”);
}

**Comment by AbdulRafaySiddiqui** [comment]
@miguelpruivo  I tried your code above but when I canceled the picker, I just never reached the condition to check the result if its null or not, the code just exists in the middle, I am on Web. I tried to use [this StackOverflow answer](https://stackoverflow.com/questions/56252856/how-to-pick-files-and-images-for-upload-with-flutter-web?rq=1) but still the same issue, I just want to set the **isBusy** property a/c to the picker state, any ideas?

```
                InputElement uploadInput = FileUploadInputElement();
                uploadInput.click();

                uploadInput.onChange.listen((e) {
                  // read file content as dataURL
                  final files = uploadInput.files;
                  if (files.length == 1) {
                    final file = files[0];
                    FileReader reader = FileReader();

                    reader.onLoadEnd.listen((e) {
                      imageBytes = reader.result;
                      widget.onImageSelect(reader.result);
                      setState(() {
                        isBusy = false;
                      });
                    });

                    reader.onAbort.listen((event) {
                      setState(() => isBusy = false);
                    });

                    reader.onError.listen((fileEvent) {
                      DialogService.showErrorDialog(
                          message: "Failed to pick file");
                      setState(() {
                        isBusy = false;
                      });
                    });

                    reader.readAsArrayBuffer(file);
```

**Comment by miguelpruivo** [comment]
@AbdulRafaySiddiqui that’s correct. This is only supported on iOS or Android, I’m afraid that on the web this isn’t supported at all because there aren’t any web events when the picker window is cancelled, unfortunately.

I’m sorry for any inconvenience.

**Comment by AbdulRafaySiddiqui** [comment]
oh, bad for me :(
