### ISSUE TITLE
A version with no DKImagePickerController please

### ISSUE THREAD

**Issue by systemcode** [miguelpruivo/flutter_file_picker#412]
Hi 

I'm trying to submit to AppStore and get ths...

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

My app does not need to load images so it will be odd for teh users to have to be presented with a primpt on load asking for image library permission.

Is there any way of not including DKImagePickerController stuff?

Otherwise great plugin BTW - Thanks.

**Comment by miguelpruivo** [comment]
@systemcode if your app doesn’t pick pictures from gallery, it won’t ever ask for permissions, don’t worry. 

Apple analyses binaries and if detects that some package uses a particular functionality, you must provide an info.plist entitlement just in case it has to prompt somehow. 

If yours don’t, then don’t worry.

**Comment by systemcode** [comment]
Ok thanks. Great plugin!
