### ISSUE TITLE
no handler found for channel miguelruivo.flutter.plugins.filepicker Mac OS

### ISSUE THREAD

**Issue by iamsabet** [miguelpruivo/flutter_file_picker#413]
hi I'm using this repo for the app I used to config this for version 1.3.0 back then I managed to handle for all platforms
now it does not work on mac os after upgrading hover and flutter_file_picker to 2.0.3
and error is : 
no handler found for channel miguelruivo.flutter.plugins.filepicker

flutter channel beta upgraded to the latest
hover version : 0.43.0

I appreciate an answer, ty

**Comment by miguelpruivo** [comment]
Hi, right now, you need to use any version below 2.0.0. I’ve created an issue already #382 to migrate the desktop as well.

You can track it from there.

**Comment by iamsabet** [comment]
ty, it worked pretty well <3
had to remove file_picker on go.mod so it would produce it again flutter clean did not work

**Comment by honglei92** [comment]
> ty, it worked pretty well <3
> had to remove file_picker on go.mod so it would produce it again flutter clean did not work

what 3

**Comment by shareef-dweikat** [comment]
If anybody still facing this issue, just upgrade to latest flutter_file_picker version
