### ISSUE TITLE
File Picker on Web (Beta)

### ISSUE THREAD

**Issue by 3rsin3rgul-Corplife** [miguelpruivo/flutter_file_picker#414]
Hello,
I am trying to pick file for upload to firebase db but always having this error;
Invalid argument(s) (path): Must not be null
    at Object.throw_ [as throw]

This is my code:
    FilePickerResult result = await FilePicker.platform
        .pickFiles(type: FileType.custom, allowedExtensions: ['svg', 'pdf']);

    if (result != null) {
      File file = File(result.files.first.path);
      print(result.files.first.path);
    }

Thanks in advance

**Comment by miguelpruivo** [comment]
Web doesn’t use paths, you’ll have to upload using the `bytes` property. 🙂

Let me know if you need further help.
