### ISSUE TITLE
Crashing on iOS 9.3 (iPhone 4s)

### ISSUE THREAD

**Issue by guit4eva** [miguelpruivo/flutter_file_picker#415]
**Describe the bug**
`FilePickerResult result = await FilePicker.platform.pickFiles(allowMultiple: true, withData: true, type: FileType.image);`

results in:

**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: checked_background)**

**Issue details**
1. iOS
2. Version 9.3
3. FileType.image

**Flutter Version details**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.14.6 18G103, locale en-ZA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (2 available)

• No issues found!

**Additional context**
Have tried:
- Using latest version of File Picker (2.0.3)
- Flutter clean
- [Deep clean (wiki)](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-possible-solution-5)

**Comment by miguelpruivo** [comment]
@guit4eva hi, does that happen if you set `withData` to `false`?

**Comment by guit4eva** [comment]
> @guit4eva hi, does that happen if you set `withData` to `false`?

I'm busy trying now (also with allowMultiple: false), will post back in a mo

**Comment by guit4eva** [comment]
It works now if I set withData to false. Although I need to keep that on to upload the file to Firestorage. It works correctly on Android - is there a workaround for iOS?

**Comment by miguelpruivo** [comment]
@guit4eva using `withData` needs to be carefully used, as it completely loads the files into memory which may overload, depending of multiple factors such as device being used, number of picked files and size of each.

I always recommend you to set `withData` to `false` unless you are completely safe of what's going to be picked. See this just as a convenience property.

You can get all of your file data to upload to Firebase by using the Dart's `File` instance, which you may do iteratively — opposing to the picked files, which loads all at once (for example, if you pick 50 files with `withData` set to `true`, all of those files bytes will be available on memory, which I suspect that can easily overpass the available heap).

**Comment by guit4eva** [comment]
> @guit4eva using `withData` needs to be carefully used, as it completely loads the files into memory which may overload, depending of multiple factors such as device being used, number of picked files and size of each.
> 
> I always recommend you to set `withData` to `false` unless you are completely safe of what's going to be picked. See this just as a convenience property.
> 
> You can get all of your file data to upload to Firebase by using the Dart's `File` instance, which you may do iteratively — opposing to the picked files, which loads all at once (for example, if you pick 50 files with `withData` set to `true`, all of those files bytes will be available on memory, which I suspect that can easily overpass the available heap, specially with an iPhone 4S).

That works a treat, thanks so much for both the solution and the stellar support, much appreciated!

**Comment by guit4eva** [comment]
> @guit4eva using `withData` needs to be carefully used, as it completely loads the files into memory which may overload, depending of multiple factors such as device being used, number of picked files and size of each.
> 
> I always recommend you to set `withData` to `false` unless you are completely safe of what's going to be picked. See this just as a convenience property.
> 
> You can get all of your file data to upload to Firebase by using the Dart's `File` instance, which you may do iteratively — opposing to the picked files, which loads all at once (for example, if you pick 50 files with `withData` set to `true`, all of those files bytes will be available on memory, which I suspect that can easily overpass the available heap, specially with an iPhone 4S).

Hi again @miguelpruivo, I've done some further testing and have discovered that it is actually `allowMultiple: true` that is the culprit here. If I set that to false and still keep `withData: true` (for testing only),  then it works correctly (albeit, single image only). With `allowMultiple: true` and removing `withData`, I get the original error:

**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: checked_background)**

**Comment by miguelpruivo** [comment]
@guit4eva do you have the full stack trace?

**Comment by guit4eva** [comment]
> @guit4eva do you have the full stack trace?

Xcode:
```
W0928 18:29:26.756307       1 commandlineflags.cc:1503] Ignoring RegisterValidateFunction() for flag pointer 0xcefae8: no flag found at that address
Sep 28 18:29:29  Runner[939] <Error>: 6.26.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
Sep 28 18:29:29  Runner[939] <Notice>: 6.26.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
	https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
	to ensure proper integration.
Sep 28 18:29:29  Runner[939] <Notice>: 6.26.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
Sep 28 18:29:29  Runner[939] <Notice>: 6.26.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60600000 started
Sep 28 18:29:29  Runner[939] <Notice>: 6.26.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Sep 28 18:29:31  Runner[939] <Warning>: 6.26.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
Sep 28 18:29:32  Runner[939] <Notice>: 6.26.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2020-09-28 18:30:43.201 Runner[939:121139] Received memory warning.
2020-09-28 18:30:59.094 Runner[939:121139] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: checked_background)'
*** First throw call stack:
(0x21c8b91b 0x21426e17 0x21bdc359 0x21bdc1ef 0x2cb665d 0x2cb5e3f 0x2c521b7 0x2c52131 0x2c527c1 0x2c5287f 0x26228af5 0x2c74151 0x2cb791d 0x2c516e9 0x2c51ded 0x26a03fa7 0x2626ce05 0x2c5da45 0x2c5ee49 0x2c5ef83 0x269fcad9 0x2626cd57 0x2626aed3 0x26265fe9 0x26202a73 0x2429abcd 0x24296375 0x24296209 0x242956d1 0x242953a5 0x2428eb2b 0x21c4d6c9 0x21c4b9cd 0x21c4bdff 0x21b9b229 0x21b9b015 0x2318bac9 0x2626f189 0x6e53f 0x21843873)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

VSCode:
```
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (os/kern) invalid argument
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: checked_background)'
        *** First throw call stack:
        (0x21c8b91b 0x21426e17 0x21bdc359 0x21bdc1ef 0x2cb665d 0x2cb5e3f 0x2c521b7 0x2c52131 0x2c527c1 0x2c5287f 0x26228af5 0x2c74151 0x2cb791d 0x2c516e9 0x2c51ded 0x26a03fa7 0x2626ce05 0x2c5da45 0x2c5ee49 0x2c5ef83 0x269fcad9 0x2626cd57 0x2626aed3 0x26265fe9 0x26202a73 0x2429abcd 0x24296375 0x24296209 0x242956d1 0x242953a5 0x2428eb2b 0x21c4d6c9 0x21c4b9cd 0x21c4bdff 0x21b9b229 0x21b9b015 0x2318bac9 0x2626f189 0x6e53f 0x21843873)
```

**Comment by miguelpruivo** [comment]
@guit4eva this looks like an underlying issue from DKImagePicker controller (which is used for multipick on devices under iOS 14).

Issue was already reported [here](https://github.com/zhangao0086/DKImagePickerController/issues/550). You can track it from there.

Sorry for any inconvenience. 😞
