### ISSUE TITLE
How to use on Flutter Web?

### ISSUE THREAD

**Issue by BirjuVachhani** [miguelpruivo/flutter_file_picker#416]
https://github.com/miguelpruivo/flutter_file_picker/blob/d2ecbd3d303a53ee8b1f103c8f02b24cfb1b54a4/lib/src/file_picker.dart#L35

@miguelpruivo I see that this library claims to support Flutter web, but when I run it on the web, it doesn't work. I was going through the source code and I found the above code that always uses `FilePickerIO()`. 

Could you please guide me on how to make it work with Flutter web?

**Comment by miguelpruivo** [comment]
@BirjuVachhani you shouldn’t have to worry about it. Platform is handled automatically. Just use `FilePicker.platform.pickFiles()`.

**Comment by BirjuVachhani** [comment]
@miguelpruivo I just tried it again and it worked just fine! so closing this issue now. Although I am facing some issues related to IOS. I create a separate issue for that!

Thank you for your help 😄
