### ISSUE TITLE
 [MethodChannelFilePicker] Unsupported operation when using at Ubuntu Desktop

### ISSUE THREAD

**Issue by Maledikt** [miguelpruivo/flutter_file_picker#417]
Using the example Code for picking one file
`FilePickerResult result = await FilePicker.platform.pickFiles();`

results in an exception:
`flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: type 'String' is not a subtype of type 'List<dynamic>?' in type cast`

**Issue details**
Happens in combination with go and hover on Ubuntu 20.04.1 LTS
Selected file or file type does not matter, exception occurs even when closing the dialog without selecting any file.

I removed all other lines using FilePicker or the FilePickerResult result so it's just this one line...

**Flutter Version details**
FilePicker: ^2.0.6
Flutter: Channel beta, 1.22.0-12.3.pre, on Linux, locale en_US.UTF-8
GO: go version go1.15.2 linux/amd64
Hover: v0.43.0
OS: Ubuntu 20.04.1 LTS

**Additional context**
flutter clean didn't help ;)

Thanks a lot!

**Comment by miguelpruivo** [comment]
@Maledikt if you are using Go for Desktop you need any of the versions below 2.0.0 until #382 is resolved. 

Sorry for any inconvenience.

**Comment by Maledikt** [comment]
> @Maledikt if you are using Go for Desktop you need any of the versions below 2.0.0 until #382 is resolved.
> 
> Sorry for any inconvenience.

Okay!
Thanks for the fast reply!

**Comment by honglei92** [comment]
> > @Maledikt if you are using Go for Desktop you need any of the versions below 2.0.0 until #382 is resolved.
> > Sorry for any inconvenience.
> 
> Okay!
> Thanks for the fast reply!

can you fix you program

**Comment by miguelpruivo** [comment]
I didn’t have the time yet. Feel free to issue a PR.
