### ISSUE TITLE
File Extension filter is not working for some File-Manager Apps on Android.

### ISSUE THREAD

**Issue by AshishCodEx** [miguelpruivo/flutter_file_picker#418]
` FilePickerResult filePickerResult = await FilePicker.platform.pickFiles( `
  `                                                         type: FileType.custom, `
   `                                                     allowedExtensions: ['csv'],`
     `                                                   withData: false,`
    `                                                    onFileLoading: (status) {`
     `                                                     if (status == FilePickerStatus.done) {`
  `                                                          setState(() {`
   `                                                           progressDialog.hide();`
`                                                           });`
      `                                                    } `
    `                                                    }); `

I have requirement for uploading .csv file to server from Android as well as iOS, for that I am using this Library.
**In Android**
When i use **allowedExtensions: ['csv']** with **type: FileType.custom** , device's default File-Manager picker intent displays files with .csv extension properly but **When I use other File-Manager App, I can also pick files with .jpg, .jpeg & all other type of extension from that App**.

**It should disable all other files to pick from intent.**

This **allowedExtensions: ['csv']** does not works for some Android File-Manager Apps with File Picker Intents.

**Comment by miguelpruivo** [comment]
Hi @AshishCodEx, that is one of the known limitations of Android filters that is well explained on [troubleshooting section for Android](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1).

Unfortunately you can’t force other explorers to respect your filters, it’s up to them. 😞

**Comment by AshishCodEx** [comment]
OK, satisfied with your answer. Thanks!
