### ISSUE TITLE
File Picker throw error with iOS Build pod-install #flutter

### ISSUE THREAD

**Issue by pandeykamlendra42** [miguelpruivo/flutter_file_picker#420]
Unable to build iOS app when I am using **file_picker** as a dependency. It is throwing the following error during **pod install**

### Error

```
**ArgumentError - invalid byte sequence in US-ASCII**
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:283:in `split'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:283:in `block in ensure_versions_file_loaded'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:282:in `each'
.
.
.
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
and 20 more at:
https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

===================================================================================

### Simple Way to reproduce:

- Create a new flutter project, build for both Android & iOS it will work

- And then add file_picker as a dependency, do the pub upgrade

- Now build the project, it will work with Android but in the case of iOS build it is throwing the following error  

===================================================================================

I have tried following GitHub thread but unable to solve this problem.

 - Missing install instructions for linux (install deps)
   https://github.com/CocoaPods/CocoaPods/issues/9956 [open] [0 comments]
   01 Aug 2020

 - ArgumentError - invalid byte sequence in US-ASCII
   https://github.com/CocoaPods/CocoaPods/issues/2385 [closed] [5 comments]
   3 weeks ago

 - Pod install fails on invalid byte sequence while having LANG=en_US.UTF-8 in profile
   https://github.com/CocoaPods/CocoaPods/issues/5780 [closed] [9 comments]
   07 Jul 2020

It will be a great support if anyone can fix this problem or can provide an alternative to build the iOS apps.

**Comment by miguelpruivo** [comment]
Can you try with cocoapods 1.9.3?

**Comment by miguelpruivo** [comment]
@pandeykamlendra42 did you managed to fix it?

**Comment by pandeykamlendra42** [comment]
It worked! thank you Man 👍 
Will it work only with 1.9.3? I mean what is the actual issue?

**Comment by miguelpruivo** [comment]
@pandeykamlendra42 you had it outdated. Sometimes dependencies might conflict with each other, it was just a guess but I’m glad it worked for you!

Let me know if you find any issue related to this.
