### ISSUE TITLE
Platform exception: PlatformException(invalid_format_type, Can't handle the provided file type., null, null)

### ISSUE THREAD

**Issue by peppix2010** [miguelpruivo/flutter_file_picker#424]
Hi,
just trying the plugin on Android. 
Once I call the following code :

```
FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.any,
);
```

Pubspec.yaml:
```
permission_handler: 5.0.1+1
file_picker: ^2.0.6

```
I have the following error on the console:
D/FilePickerDelegate(23428): Selected type */*
E/FilePickerDelegate(23428): Can't find a valid activity to handle the request. Make sure you've a file explorer installed.
I/flutter (23428): [MethodChannelFilePicker] Platform exception: PlatformException(invalid_format_type, Can't handle the provided file type., null, null)
E/flutter (23428): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(invalid_format_type, Can't handle the provided file type., null, null)

Flutter Doctor:
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-GB)
    • Flutter version 1.22.0 at C:\Users\peppi\Desktop\programs\flutter
    • Framework revision d408d302e2 (5 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
    • Android SDK at C:\Users\peppi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\peppi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (2 available)
    • CUBOT X18 (mobile)          • C509XXBH81121264 • android-arm • Android 7.0 (API 24)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86 • Android 11 (API 30) (emulator)

If I look into FilePicker I see:
/// The interface that implementations of file_picker must implement.
///
/// Platform implementations should extend this class rather than implement it as `file_picker`
/// does not consider newly added methods to be breaking changes. Extending this class
/// (using `extends`) ensures that the subclass will get the default implementation, while
/// platform implementations that `implements` this interface will be broken by newly added
/// [FilePicker] methods.
abstract class FilePicker extends PlatformInterface {

Does this mean I have to create the implementation of FilePicker?
Thanks!

Am I missing something?

**Comment by miguelpruivo** [comment]
@peppix2010 hi, the error is pretty clear. You must have a file_explorer installed on your device or else it won't work. The plugin just asks the OS to launch any available file explorer to handle the picks. You can try installing ES File Explorer for example and let me know if it worked for you.

**Comment by peppix2010** [comment]
> @peppix2010 hi, the error is pretty clear. You must have a file_explorer installed on your device or else it won't work. The plugin just asks the OS to launch any available file explorer to handle the picks. You can try installing ES File Explorer for example and let me know if it worked for you.

Oh yes....the emulaor I was using to test it had no file explorer intalled.
Not iw works perfectly.

Thanks for your hard work!
