### ISSUE TITLE
After swiping the picker with the modal on ios 14, an error occurs after the next startup

### ISSUE THREAD

**Issue by michcio53** [miguelpruivo/flutter_file_picker#431]
**Describe the bug**
After swiping the picker with the modal on ios 14, in the next startup of picker error occures and does not allow to recall picker.
- at the moment when this modal is swiped and I do not hold my finger on cancel while swiping, then the modal will run after the second call (it will throw an error at the first one),
- when the modal is swiped and held on cancel when swiping, it suspends the possibility of calling it again, unless you exit and enter page

**Issue details**
***1. Platform (Android/iOS)***
iOS

***2. Platform OS version***
14

***3. File type (filter) — when applicable***
```
FileType.media
```

***4. Detailed steps to reproduce***
- Call the modal with the picker
- Swip down modal with picker instead of canceling
- When trying to call modal again, error is occuring

**Error Log**
```
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
flutter: PlatformException(multiple_request, Cancelled by a second request, null, null)
```

**Flutter Version details**
```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-PL)
    • Flutter version 1.22.0 
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK 
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME 
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone SE (1st generation) (mobile) • 47B9EA4B-3866-452F-ACFD-D3E308FF26D6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)

• No issues found!
```

**Additional context**
[Maybe that might help](https://stackoverflow.com/questions/60809825/detect-if-imagepickercontroller-is-closed-with-swipe-down-gesture-with-objective)

**Comment by hectorAguero** [comment]
I'm facing the same problem with filetype.image  and filetype.video.

The issue here is that dismiss the gallery picker with a swipe down, don't return null, like the **cancel button**  in the top left corner.

**Comment by miguelpruivo** [comment]
@hectorAguero I must investigate this.

**Comment by miguelpruivo** [comment]
@michcio53 @hectorAguero This has been fixed and published with 2.0.8. Thank you for reporting!

**Comment by michcio53** [comment]
@miguelpruivo now the app crashes on iOS 14 when I click "cancel" and after selecting photos I click "add"

**Comment by miguelpruivo** [comment]
@michcio53 hum that’s really weird. I’ll take a look in a while.

**Comment by miguelpruivo** [comment]
@michcio53 you were correct. There was an issue with it (I missed one little thing which was the presentation style). It should be all fine now with `2.0.8+1`.
