### ISSUE TITLE
Original file path along with cache path. 

### ISSUE THREAD

**Issue by NaveenAluri** [miguelpruivo/flutter_file_picker#434]
Please return the original file path along with the temp path.

**Comment by miguelpruivo** [comment]
@NaveenAluri I'm sorry, but this isn't possible anymore and won't be, unless Android team change the way they handle files. As of now, there are two only approaches that I already described multiple times, you can check [this answer](https://github.com/miguelpruivo/flutter_file_picker/issues/411#issuecomment-699482714).

If for some reason you still want to use the original path, you can try one of the previous versions of the plugin prior to 2.0.0 which does exactly that. However, have in mind that after Android SDK 30, it won't be possible at all and as of SDK 29, only works with `useLegacyStorage = true` flag.

**Comment by NaveenAluri** [comment]
**@miguelpruivo**, Is there any possibility to return the original File URI atleast?

**Comment by miguelpruivo** [comment]
@NaveenAluri yes that’s possible. I didn’t included it because I don’t really think it will be useful for a Flutter app and could let people to misuse it. How are you planing to use?

**Comment by NaveenAluri** [comment]
**@miguelpruivo,** actually my requirement is, need to allow to pick the file from different folders with the same file name, but I have seen your code that you are storing the selected files in the cache folder. So it is not allowing to upload the different files with the same name.

**Comment by miguelpruivo** [comment]
@NaveenAluri I don't believe that File URI will help you there then. You can try one of the previous versions before 2.0.0. Those won't cache files and return the original instead, however, won't work for SDK 30, have in mind.

**Comment by NaveenAluri** [comment]
**@miguelpruivo,** yeah I tried to access the file path with URI but it doesn't support some folders like Downloads, it won't help at all.
And selecting the file from different folders with the same file name is an edge case scenario. So I'm going with the plugin as it is.

Thanks for this amazing plugin **@miguelpruivo**

**Comment by miguelpruivo** [comment]
@NaveenAluri I'm sorry that I can't help you any further. If you wish to make it persistent, just move/copy the files into your app's directory files (using path_provider) and then delete the cache files immediately using `cleanTemporaryFiles()` from `file_picker`. That way you will kept a single persistent copy of that file.
