### ISSUE TITLE
Module file_picker can not be found

### ISSUE THREAD

**Issue by rj76** [miguelpruivo/flutter_file_picker#439]
When building for iOS, the module file_picker can not be found.

**Issue details**
iOS
Xcode version: 12.0.1

**Error Log**
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/builder/clone/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'file_picker' not found
    @import file_picker;
     ~~~~~~~^~~~~~~~~~~


**Flutter Version details**
[✓] Flutter (Channel stable, 1.22.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.1 at /home/richard/bin/flutter
    • Framework revision f30b7f4db9 (3 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/richard/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/richard/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/richard/bin/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM A505FN (mobile) • R58M55VD53Y • android-arm64 • Android 10 (API 29)

• No issues found!

Does anyone have any idea why this happens?

**Comment by miguelpruivo** [comment]
This is likely because you either don’t have `use_frameworks!` on your Podfile or because you are opening the xcodeproj instead of xcodeproj.workspace.

**Comment by rj76** [comment]
Removing `use_frameworks!` didn't help. I don't have a Mac, so I'm editing the files manually; what exactly do you mean with "opening the xcodeproj instead of xcodeproj.workspace."?

**Comment by miguelpruivo** [comment]
@rj76 if you don’t have a mac ignore the second point. As for the `use_frameworks!` you _**must**_ use it. Not remove it. Along with `use_modular_headers!`.

**Comment by rj76** [comment]
It looks like it might be related to this issue [#53573](https://github.com/flutter/flutter/issues/53573)

**Comment by miguelpruivo** [comment]
@rj76 hum, might be. Let me know if you find a fix.

**Comment by rj76** [comment]
Removing the ios/Podfile worked for me!

**Comment by 3bugs** [comment]
If you have a Mac with Apple M1 processor, open terminal and enter this command:
sudo arch -x86_64 gem install ffi

then cd into the 'ios' directory under project's root directory, and enter this command:
arch -x86_64 pod install

**Comment by boylenssen** [comment]
make sure you have set the minimum iOS version in XCode to the same you have set in the Podfile as mentioned here: https://github.com/flutter/flutter/issues/53573#issuecomment-786932766

**Comment by ZubairKh** [comment]
I was having the same issue. I noticed the deployment info in Xcode **Runner** --> **General** Tab was not matching with Podfile and also **MinimumOSVersion** in **Runner/Flutter/AppFrameworkInfo.plist** 

Align All versions the same then remove Pods/ folder and Podfile.lock, then pod install again

See screenshots below
<img width="1093" alt="Screenshot 2021-12-09 at 11 22 03 AM" src="https://user-images.githubusercontent.com/10397305/145344917-b784e183-a83f-4b30-b7d9-75f2ee62a960.png">
<img width="631" alt="Screenshot 2021-12-09 at 11 22 59 AM" src="https://user-images.githubusercontent.com/10397305/145344932-9199678d-9e33-4fb7-8de1-2635bfadeae9.png">
<img width="906" alt="Screenshot 2021-12-09 at 11 21 06 AM" src="https://user-images.githubusercontent.com/10397305/145344943-1f076f7f-1ee5-4cf0-b8c5-874b25811774.png">

**Comment by amjad07** [comment]
> I was having the same issue. I noticed the deployment info in Xcode **Runner** --> **General** Tab was not matching with Podfile and also **MinimumOSVersion** in **Runner/Flutter/AppFrameworkInfo.plist**
> 
> Align All versions the same then remove Pods/ folder and Podfile.lock, then pod install again
> 
> See screenshots below <img alt="Screenshot 2021-12-09 at 11 22 03 AM" width="1093" src="https://user-images.githubusercontent.com/10397305/145344917-b784e183-a83f-4b30-b7d9-75f2ee62a960.png"> <img alt="Screenshot 2021-12-09 at 11 22 59 AM" width="631" src="https://user-images.githubusercontent.com/10397305/145344932-9199678d-9e33-4fb7-8de1-2635bfadeae9.png"> <img alt="Screenshot 2021-12-09 at 11 21 06 AM" width="906" src="https://user-images.githubusercontent.com/10397305/145344943-1f076f7f-1ee5-4cf0-b8c5-874b25811774.png">

@ZubairKh this solution worked for me

**Comment by MuhammadRahman2** [comment]
i have same when i see above comment my version is same to above screen then i update version 12.0 i keep the it  wok
if you your version follow the above still give you error then increase the version in podfile, and also Xcode change **developemt info**  write 12.0
it help for me hopely it will be work

**Comment by saimawan213** [comment]
> i have same when i see above comment my version is same to above screen then i update version 12.0 i keep the it wok if you your version follow the above still give you error then increase the version in podfile, and also Xcode change **developemt info** write 12.0 it help for me hopely it will be work

It is working fine for me
