### ISSUE TITLE
Path is always null on Web

### ISSUE THREAD

**Issue by marccantwell** [miguelpruivo/flutter_file_picker#443]
Path is always null on Chrome build Version 85.0.4183.121 (Official Build) (64-bit) macOS.
Same code works on iOS

```
Future getImage() async {
    Navigator.pop(context);
    try {
      FilePickerResult pickedImage = await FilePicker.platform.pickFiles();
      File tmpFile = File(pickedImage.files.single.path);
      if (tmpFile != null) {
        setState(() {
          _image = tmpFile;
        });
      } else {
        print('No path to image...');
      }
    } catch (e) {
      print('$e');
    }
  }
```

**Comment by miguelpruivo** [comment]
@marccantwell paths aren’t supported on web. It’s a web limitation actually, not the plugin. You must use the `bytes` property instead when picking files using flutter web.

Closing this as non-issue. Sorry for any inconvenience.

**Comment by marccantwell** [comment]
Thanks @miguelpruivo! Might be helpful to add an example with platform specific examples. I'll play with that to see how to make it work with the bytes property.

**Comment by miguelpruivo** [comment]
@marccantwell basically you just need to pick up the `bytes` and send it using a Multipart file, for example, for your BE. Or you can a `html.File` instance.

Might add some examples in the future. Thank you!
