### ISSUE TITLE
Plugin does not return the real file path

### ISSUE THREAD

**Issue by abdaizs** [miguelpruivo/flutter_file_picker#447]
**Describe the bug**
The problem is, that the result is not good. It is a cache file, so the plugin does not return a real file path.
Is this an Android issue / flutter_file_picker issue or something is wrong with my Android setup?

**Issue details**
1. Platform: Android
2. Platform OS version: 10
3. File type (filter) — when applicable
4. Detailed steps to reproduce

Just using your code snippet:

 FilePickerResult result = await FilePicker.platform.pickFiles();

          if(result != null) {
            File file = File(result.files.single.path);
          }

**Log**
D/FilePickerUtils(18209): File loaded and cached at:/data/user/0/com.example.example/cache/file_picker/20201016_104833.jpg

The 20201016_104833.jpg is not there of course, but also in Picture folder on my phone.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
[√] Flutter (Channel unknown, v1.14.1, on Microsoft Windows [Version 10.0.19041.572], locale hu-HU)
    • Flutter version 1.14.1 at C:\flutter
    • Framework revision c88320458e (9 months ago), 2020-01-15 11:38:02 -0500
    • Engine revision bc41ab5139
    • Dart version 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Zsolt\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\Zsolt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM T860 • R52MA0LZYZX • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by miguelpruivo** [comment]
@abdaizs I've a section on the Wiki explaining this. Check [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

There's a reason why the original path isn't retrieved and a cached file instead, that's how Android team wants us to do so. Previously (until 2.0.0) I was giving you the original paths, but that could result in a lot of more issues and SDK 29+ deprecates it. After SDK 30 I highly doubt that you'd be able to actually access original paths. On iOS was never possible.
