### ISSUE TITLE
Set .opus not included in the allowedExtensions, but .opus still shown on the list.

### ISSUE THREAD

**Issue by jonilaw** [miguelpruivo/flutter_file_picker#449]
**Describe the bug**
Set .opus not included in the allowedExtensions, but .opus still shown on the list.

**Issue details**
1. Android 10, PocoPhone F1, Latest firmware.

**Screenshots and/or video**
![image](https://user-images.githubusercontent.com/20550525/96390802-806e7080-11e0-11eb-9767-1d76c7f24743.png)

**Flutter Version details**
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (10 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

**Comment by miguelpruivo** [comment]
Hi @jonilaw. This is a [known limitation](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1). I’m sorry for any inconvenience.

Thank you.

**Comment by jonilaw** [comment]
Hi @miguelpruivo. Thank you, you've done a very good job.
