### ISSUE TITLE
Improvement in documentation.

### ISSUE THREAD

**Issue by asknishant** [miguelpruivo/flutter_file_picker#450]
Showing a message when no files are selected by the developer.
'''
if(result != null) {
   PlatformFile file = result.files.first;
   
   print(file.name);
   print(file.bytes);
   print(file.size);
   print(file.extension);
   print(file.path);
}'''
 by adding an else case when no files are selected

'''
else {
  print('No file selected');
}'''

Can i add this to the documentation?

**Comment by miguelpruivo** [comment]
Hi @asknishant, this is already mentioned [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#-pickfiles) in other words.

Thank you for the suggestion. Might add it as well on the readme.
