### ISSUE TITLE
Android resource linking failed 

### ISSUE THREAD

**Issue by JAICHANGPARK** [miguelpruivo/flutter_file_picker#455]
**Describe the bug**
- Build Failed

**Issue details**
1. Platform (Android/iOS) : Android
2. Platform OS version : Oreo 

**Error Log**
```
build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
1.23.0-18.1

**Additional context**

**Comment by imtoori** [comment]
https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#android

**Comment by JAICHANGPARK** [comment]
@imtoori Thanks I will try that

**Comment by miguelpruivo** [comment]
Thank you @imtoori. Don’t get me wrong guys but I don’t know why I actually take time to write the stuff down on changelog and/or wiki. 😅

@JAICHANGPARK you need to update your gradle to support the latest manifest features. Thank you!
