### ISSUE TITLE
A problem occurred configuring root project 'file_picker'

### ISSUE THREAD

**Issue by MohammadElKhatib** [miguelpruivo/flutter_file_picker#458]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/mohammadalkhatib/_Freelance/ChallengeKicks/Application/Mobile/ChallengeKicks/challengekicks/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin file_picker...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by jagritjkh** [comment]
same issue, I think plugin is android x incompatible.

**Comment by MohammadElKhatib** [comment]
@jagritjkh 

that is right it is working normally on IOS but not working when building android
I am stuck for a couple of hours

**Comment by callingmybluff** [comment]
Same here, happened after upgrading Flutter.

**Comment by miguelpruivo** [comment]
@MohammadElKhatib @jagritjkh the plugin supports all Android features up to Android 11 (SDK 30). Android X is supported on it for more than a year I’d say.

Your logs show that you don’t have the Android environment variable set. Try running the example app provided with the plugin and let me know if it works for you.

If it does, it’s either related with the project or environment variable.

**Comment by jagritjkh** [comment]
solved! just changed the android plugin gradle version to 3.6.4 in build.gradle and gradle version to 5.6.4 in gradle-wrapper.properties

**Comment by miguelpruivo** [comment]
@MohammadElKhatib waiting for your input. If it works for you, feel free to close the issue.

Thank you!

**Comment by MohammadElKhatib** [comment]
Sorry i did not get the time to check it, today willl try and share my feedback

**Comment by deep-na** [comment]
i am also getting the same error

**Comment by miguelpruivo** [comment]
@deep-na try the suggested fixes. Thank you.

**Comment by MohammadElKhatib** [comment]
@miguelpruivo I checked the solution and the SDK is already defined in the local.properties

also, I tried to upgrade flutter, upgrade android Gradle but nothing worked, the next step I will create an empty project with only the file_picker library to check if it will work

**Comment by MohammadElKhatib** [comment]
> solved! just changed the android plugin gradle version to 3.6.4 in build.gradle and gradle version to 5.6.4 in gradle-wrapper.properties

@jagritjkh your solution works for me also, Thank you

**Comment by miguelpruivo** [comment]
Regarding the downvotes on my last answer, don’t get me wrong but I’m the only maintainer of the plugin and I work on this on my after work hours. I’ve always helped everyone here even when sometimes they don’t take a minute to read all the stuff I write on the wiki to prevent unnecessary issues.

Most of the times there are like tons of the same issue being opened, some of which have the solutions posted already. Don’t get me wrong, but if you had people constantly opening issues for the same things when a quick search in the issues could result in immediately finding the solution, you’d probably had enough of it as well. I’m sorry, if I sound harsh, wasn’t my intention, but we all win if people do a quick search before.

Thank you for your comprehension and I’m glad it’s working for you now. I’ll probably add that relative info on the wiki as well.

**Comment by MohammadElKhatib** [comment]
@miguelpruivo I appreciate your work and I normally don't open an issue before searching for a solution, but I could not get any solution while searching hours.

thanks for your time and no worries.

**Comment by cunjin** [comment]
> solved! just changed the android plugin gradle version to 3.6.4 in build.gradle and gradle version to 5.6.4 in gradle-wrapper.properties
thanks @jagritjkh 

this worked for me.
my problem was: 

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring root project 'file_picker'.
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by khallediRA** [comment]
> solved! just changed the android plugin gradle version to 3.6.4 in build.gradle and gradle version to 5.6.4 in gradle-wrapper.properties

Worked for me thankyou

**Comment by jagritjkh** [comment]
Thank you @miguelpruivo for such a great plugin!

**Comment by abgrano** [comment]
Only change in build.gradle from classpath 'com.android.tools.build:gradle:3.5.0' to classpath 'com.android.tools.build:gradle:3.6.4'. In gradle-wrapper.properties you can choose the latest one 6.7.1 version. It's worked for me.

**Comment by onedash-test** [comment]
solved! just changed the android plugin gradle version to 3.6.4 in build.gradle and gradle version to 5.6.4 in gradle-wrapper.properties
