### ISSUE TITLE
How can  I  pop the file picker page when I not select file without backbutton

### ISSUE THREAD

**Issue by link1206** [miguelpruivo/flutter_file_picker#460]
I encourage you to add new suggestions that you think that can make file_picker even a better package.

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

How can  I  pop the file picker page when I not select file without backbutton

**Comment by miguelpruivo** [comment]
@link1206 hi, May your elaborate? I don’t actually get what you’re asking for.

The plugin only requests an installed picker from the device, this means that if the picker has the capability to be “cancelled” without the back button, that you should be fine.

**Comment by miguelpruivo** [comment]
Closing as this is likely a no-op. Let me know if you have more details.

Thank you!
