### ISSUE TITLE
Error on build 

### ISSUE THREAD

**Issue by phuongphally** [miguelpruivo/flutter_file_picker#461]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by miguelpruivo** [comment]
Hi, this is dup or related to #435 #454 #456 #459. 

Likely like a bad gradle version. You can try one of the suggested versions.

Thank you.
