### ISSUE TITLE
[Flutter Web] -  handle canceled the picker not working

### ISSUE THREAD

**Issue by echomartha** [miguelpruivo/flutter_file_picker#464]
**Issue details**
1. Platform Web

**File Picker Version**
file_picker: ^2.0.11

**MyCode**
```
filePickImage() async {
    setLoading(true);
    FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      allowMultiple: true,
    );

    if (result != null) {
      _editProductImageBloc.add(PickImage(result.files));
      setLoading(false);
    } else {
      print("else");
      setState(() {
        isLoading = false;
      });
    }
  }
```

**Flutter Version details**
![image](https://user-images.githubusercontent.com/71472725/97259609-29a70d80-1856-11eb-96b7-d66b5fe2466a.png)

**Additional context**
```
 else {
      print("else");
      setState(() {
        isLoading = false;
      });
    }
```
doesn't print anything in here when I try to canceled file picker dialog

**Comment by miguelpruivo** [comment]
Hi! That’s correct, I forgot to add to the docs that Web doesn’t trigger any event when the picker is cancelled. This is a web platform limitation, hence, there’s nothing to do here.

I’m sorry for any inconvenience.

**Comment by echomartha** [comment]
hi,@miguelpruivo . thanks for your response
okayy , thanks
