### ISSUE TITLE
can not build with cloud firestore for android

### ISSUE THREAD

**Issue by sadaqatkarimi** [miguelpruivo/flutter_file_picker#467]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed

**Comment by miguelpruivo** [comment]
@sadaqatkarimi I’m sorry but I don’t see here anything related to the plugin itself and it should compile properly with any other plugin as far as I know.

Try cleaning and/or updating your gradle version. Check the troubleshooting area of the wiki as well might have something.

Thank you!
