### ISSUE TITLE
Error: unexpected element <queries> found in <manifest>

### ISSUE THREAD

**Issue by pulstar** [miguelpruivo/flutter_file_picker#469]
**Describe the bug**
I installed the latest version of the plugin, I ran flutter clean, etc., but when I did try to build my application, it displays the error below.

**Issue details**
1. Platform: Android
2. Platform OS version: 9
3. File type (filter) — images

**Error Log**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\my_app\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Flutter Version details**
[√] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [version 10.0.18363.1139], locale pt-BR)
    • Flutter version 1.23.0-7.0.pre at C:\src\flutter
    • Framework revision db6e2d8aa5 (5 weeks ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio

[√] Connected device (5 available)
    • Vivo XI (mobile)  • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)  <<<=== this device
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [version 10.0.18363.1139]
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 86.0.622.48

**Aditional context**
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.mr.flutter.plugin.filepicker" >

    <uses-sdk android:minSdkVersion="16" />

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <queries>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />

            <data android:mimeType="*/*" />
        </intent>
    </queries>

</manifest>
```

**Comment by miguelpruivo** [comment]
Hi @pulstar, this is on the changelog and also on the top of [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

You’ll have to update your gradle version to one or the compatible versions that has the latest queries tags (which were introduced with Android 11).

Thank you.

**Comment by pulstar** [comment]
Thank you very much.

**Comment by pulstar** [comment]
Do you know if this update in Graddle imply any change in my project? By
the way, which Java version are you using?

Em qua, 28 de out de 2020 22:11, Miguel Ruivo <notifications@github.com>
escreveu:
