### ISSUE TITLE
Properties name and bytes are not set at returned PlatformFile

### ISSUE THREAD

**Issue by Tobi696** [miguelpruivo/flutter_file_picker#470]
Properties **bytes** and **name** are null on returned **PlatformFile**

```dart
case "document":
FilePickerResult result =
await FilePicker.platform.pickFiles();
if (result == null) return;
final file = result.files.first;
print(file.name);
break;
```

Output when selecting a sample pdf: **null**
![Debugger view of returned PlatformFile](https://user-images.githubusercontent.com/44548981/97624341-3dee3480-1a27-11eb-883b-61c3dbbe26de.png)

**Comment by miguelpruivo** [comment]
@Tobi696 `bytes` are only available if you set the property `withData` to `true`, but I don't recommend you to do so unless you are aware of what you're picking, as it might consume a lot of memory. It is always better to just have the path and then create a `File(path)` instance.

As for the name, looks like that file indeed doesn't have a name, if it can't be handled (the name) it might not be retrieved. See if there is any exception on the logs.

You may want to take a look into the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#parameters) for detailed description about on how to use the different parameters.
