### ISSUE TITLE
Can't retrieve bytes from photo on iOS

### ISSUE THREAD

**Issue by jesusrp98** [miguelpruivo/flutter_file_picker#473]
Trying to retrieve the bytes that constitute a photo picked from the iOS image picker retrieves a 'null' object.
The other parameters,  such as path, work fine.
Note that Im working with an iPad emulator.

Code:
```
onPressed: () async => await FilePicker.platform
    .pickFiles(type: FileType.image)
    .then((result) {
  print(result.files.single.bytes);
}),
```
Version of file_picker: 2.11

**Comment by miguelpruivo** [comment]
@jesusrp98 that’s pointed out in the documentation. You need to set `withData: true` on `pickFiles()`. 

Have in mind that picking huge files with it might result in memory issues as you’ll be loading all into memory.
