### ISSUE TITLE
Can add maxDuration?

### ISSUE THREAD

**Issue by syssam** [miguelpruivo/flutter_file_picker#476]
Can add maxDuration for video and audio?

**Comment by miguelpruivo** [comment]
@syssam hi! Nop, unfortunately that’s impossible to prevent selecting files from those properties. 😔

**Comment by syssam** [comment]
@miguelpruivo why image_picker can do that.

**Comment by miguelpruivo** [comment]
For video might be possible, but for audio I'm not sure. I'll have to take a look.

**Comment by miguelpruivo** [comment]
Closing as this is a no-op with no ETA. Will re-open if needed.
