### ISSUE TITLE
Can't run in android device

### ISSUE THREAD

**Issue by Lykeosovandara** [miguelpruivo/flutter_file_picker#479]
**Describe the bug**
When i install this package and run the project it show "SDK location not found".

**Issue details**
1. Platform (Android)

**Screenshots and/or video**
<img width="797" alt="image" src="https://user-images.githubusercontent.com/28288016/98063198-0e558700-1e82-11eb-8137-0c7d027c7590.png">

**Flutter Version details**
Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E287 x86_64,
    locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/keodara/Documents/flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

**Comment by ShurikuS57** [comment]
Upgrading gradle to version 3.5.4 helped me.

**Comment by miguelpruivo** [comment]
@Lykeosovandara there are a lot of similar issues here and seems to be all related with gradle versions and/or dependencies conflicts.

Try cleaning, changing gradle version to one of those suggested in the troubleshooting area and let me know if it worked for you.

Thanks!

**Comment by Lykeosovandara** [comment]
It works now when I upgrade gradle to version 3.5.4 like ShurikuS57 mention.
