### ISSUE TITLE
不能编译执行

### ISSUE THREAD

**Issue by BitleTeng** [miguelpruivo/flutter_file_picker#480]
![image](https://user-images.githubusercontent.com/38198173/98076691-bdf21f80-1ea9-11eb-9369-5d320f71d6e5.png)
![image](https://user-images.githubusercontent.com/38198173/98076704-c2b6d380-1ea9-11eb-88bd-11f29e7dbd8a.png)

**Comment by miguelpruivo** [comment]
Hi, you must have your project fully migrated to Android X. [Check here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4) some solution steps.

**Comment by BitleTeng** [comment]
> 嗨，您必须将项目完全迁移到AndroidX。[在此处查看](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4)一些解决方案步骤。

thanks for you,It's solved
