### ISSUE TITLE
Google Play detected NullPointerException

### ISSUE THREAD

**Issue by kaciula** [miguelpruivo/flutter_file_picker#482]
Google Play reported some crashes and the stacktrace is the following.

![Screenshot 2020-11-04 at 16 07 45](https://user-images.githubusercontent.com/18688/98121451-fa2c7c80-1eb7-11eb-8158-ccc387df57f9.png)

I am using **file_picker: ^2.0.10** 

The crashes are on Motorola Moto and Samsung Galaxy S9.

**Comment by miguelpruivo** [comment]
@kaciula what's the file_picker version that's being used on that release?

**Comment by kaciula** [comment]
@miguelpruivo I am using file_picker 2.0.10 in that release.

**Comment by miguelpruivo** [comment]
Ok, this is fixed with #298 I believe.

**Comment by kaciula** [comment]
Cool. It seems to be the same issue as mine. Waiting for the new release to confirm. Thanks.

**Comment by miguelpruivo** [comment]
Fixed and published with [2.0.12](https://pub.dev/packages/file_picker/changelog#2012).

Thank you for reporting!
