### ISSUE TITLE
Version 2.0.12 compilation error

### ISSUE THREAD

**Issue by jeromekai** [miguelpruivo/flutter_file_picker#484]
I'm using latest version of Flutter 1.22.3 and Android Studio 3.5.2  
 What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     xxxxx\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by miguelpruivo** [comment]
Hi, this is likely a compatibility issue in your gradle or such. 

Try changing to one of the recommended gradle versions and cleaning.

**Comment by theAkshay60** [comment]
This happened with me as well. All of my plugins work, except this one. It was working fine until I updated my flutter SDK today. Below is the error I got.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Aksha\OneDrive\Desktop\IdeaSailor\mla_sanjay_jagtap\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by miguelpruivo** [comment]
You can search on the issues for similar logs and you’ll find plenty with no “particular fix” other than cleaning, updating dependencies and trying to build again.

I can’t help you much further than this as this doesn’t seems to be plugin related but project instead. I’m sorry for any inconvenience.

**Comment by amani27** [comment]
I had the same issue after upgrading to Flutter: 1.20.4, downgrading the file_picker package version to ^1.4.0+1 solved the issue for me.

**Comment by miguelpruivo** [comment]
@amani27 plugin's version currently is quite above that. It's better to understand what might be causing the issue with the latest version in order to fix it.

**Comment by jeromekai** [comment]
@amani27 @theAkshay60 
Upgrade the version in gradle-wrapper.properties to 6.1.1>=,
/android/build.gradle upgrade to 4.0.1>= ;Refer to the configuration of plug-in demo, file_picker: 2.0.12， I got it
