### ISSUE TITLE
viewController maybe nil

### ISSUE THREAD

**Issue by iStarEternal** [miguelpruivo/flutter_file_picker#486]
Hello，the author

I am A Chinese. If I use Chinglish, Please forgive me.

I am working on a project to integrate Flutter with iOS/Android.
I added register code in AppDelegate-application(_:didFinishLaunchingWithOptions:)),
but AppDelegate.window hasn't been created yet at this time.

So when FilePickerPlugin init, We can't find the viewController.

I recommend changing the viewController property to a get-only method.

Thanks

**Comment by miguelpruivo** [comment]
@iStarEternal hi, you can see [here](https://github.com/miguelpruivo/flutter_file_picker/blob/master/ios/Classes/FilePickerPlugin.m#L30) that I'm not creating a new view controller, I'm just getting the shared view controller. With that said, I'm not sure what's the issue you're experiencing.
