### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':app:processDebugResources'. > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade    > Android resource linking failed      /home/user/Desktop/Flutter/tasksigma/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by Nandan-Wewhare** [miguelpruivo/flutter_file_picker#490]
This exception occurs every time and I can't build my project.
Flutter v1.22.1, channel: beta, IDE: VSCode

**Comment by miguelpruivo** [comment]
@Nandan-Wewhare I'm sorry that you're experiencing this. But that's because you haven't yet migrated your gradle to fully support the new `<queries>` tag.

That information is both on CHANGELOG and [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue).

Basically just replace your gradle version with: 4.0.1 for example and your gradle-wrapper.properties with:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

Thank you.

**Comment by Nandan-Wewhare** [comment]
@miguelpruivo didn't solve the problem still it occurs.
FAILURE: Build failed with an exception.

*** What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/user/Desktop/Flutter/tasksigma/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org**

**Comment by Nandan-Wewhare** [comment]
This is my gradle.wrapper.properties file:

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

**Comment by miguelpruivo** [comment]
You need to update your build.gradle to a compatible version as well. Try 4.0.1.

**Comment by Nandan-Wewhare** [comment]
Yup, it worked! Thank you so much. Cheers!
