### ISSUE TITLE
Dart analyze warning "Don't import implementation files from another package."

### ISSUE THREAD

**Issue by BaR488** [miguelpruivo/flutter_file_picker#493]
**Describe the bug**
Dart analyzer find issue: "Don't import implementation files from another package." in generated_plugin_registrant.dart.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.
![image](https://user-images.githubusercontent.com/14288495/98734968-8a8d2480-23c4-11eb-850b-b9ad3b4f67a1.png)

**Comment by miguelpruivo** [comment]
Hi, I don’t see a reason why you should have this error. Never actually have seen this before with the package.

Have you tried importing in some other way?

**Comment by BaR488** [comment]
Hi, as i understand, this file generate automatically. 
I think import from not main library dart file not safe,  and warning about this.
Mb add export `'./src/file_picker_web.dart';` to 
![image](https://user-images.githubusercontent.com/14288495/98742810-dfcf3300-23d0-11eb-8c95-edb3e54f1174.png) resolve a problem.

**Comment by BaR488** [comment]
I test it,  `export './src/file_picker_web.dart';` in `flutter_file_picker/lib/file_picker.dart` fix it

**Comment by miguelpruivo** [comment]
@BaR488 ok, I found the issue. You shouldn't be using `file_picker_web` directly on your imports but `file_picker` instead as it will resolve automatically to the `file_picker_web` under the hood, hence the reason why I haven't yet seen the warning and it should keep that way, as the `file_picker` properly delegates to the underlying platform.

Nevertheless, thank you for your contribution on #494.

**Comment by BaR488** [comment]
@miguelpruivo OK, how can i fix this warning?

**Comment by BaR488** [comment]
`generated_plugin_registrant.dart` generated on each build, set `import 'package:file_picker/src/file_picker_web.dart';` and print warning

**Comment by miguelpruivo** [comment]
@BaR488 just import `file_picker` instead of `file_picker_web`. It will be using the web automatically.

**Comment by BaR488** [comment]
@miguelpruivo import where? `generated_plugin_registrant.dart`  - generated automatically, i can't edit this file manually.

**Comment by miguelpruivo** [comment]
@BaR488 why do you want to edit that file?

**Comment by BaR488** [comment]
@miguelpruivo because i have warning in this  😄 
![image](https://user-images.githubusercontent.com/14288495/98865087-b378ec80-248c-11eb-8eb2-8cdfb276f85b.png)

**Comment by miguelpruivo** [comment]
But that’s a generated file, you shouldn’t worry with it. The generated file will pick the right src.

**Comment by BaR488** [comment]
@miguelpruivo You're right, but `flutter analyze` return issue, and i have problem with CI, i need manually check pipeline state on new issue instead of see that job passed.

**Comment by BaR488** [comment]
@miguelpruivo can u reopen issue?

**Comment by miguelpruivo** [comment]
@BaR488 what’s your suggestion then?

**Comment by BaR488** [comment]
@miguelpruivo if my PR is incorrect, i suggest separate platform code on deferent packages in mono repo (like in [shared_preferences](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/pubspec.yaml)). Is this available?

**Comment by miguelpruivo** [comment]
@BaR488 it was previously available (before 2.0.0) and then reverted as it made it very hard to maintain for those that wanted to have an app that could run on both web and IO at the same time. Your PR is welcome but didn't make any difference I believe.

I'm still finding hard to understand why's that that warning bothers you so much. You may want to add a static analysis options to suppress that warning.

**Comment by BaR488** [comment]
@miguelpruivo  OK, mb u are right.
I just exclude `generated_plugin_registrant` from analuze.

analysis_options.yaml:
`
analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart`

**Comment by miguelpruivo** [comment]
Your welcome @BaR488! 👍

**Comment by maurozadu** [comment]
you could also add a comment before the import
```
// ignore: implementation_imports
import 'package:file_picker/src/file_picker_web.dart';
```

**Comment by rootasjey** [comment]
> you could also add a comment before the import
> 
> ```
> // ignore: implementation_imports
> import 'package:file_picker/src/file_picker_web.dart';
> ```

Yes but since `generated_plugin_registrant.dart` is a static generated file, your added line would be deleted repeatedly.
Karabanovbs' solution is definitive.

**Comment by kamleshwebtech** [comment]
I have added "// ignore: implementation_imports" but still facing "Don't import implementation files from another package" issue in console panel. This error comes again and again on every compilation of app. 

IT IS VERY IRRITATING ISSUE, DEV TEAM, DO YOU HAVE ANY SOLUTION TO FIX THIS ISSUE? OTHER PACKAGES ARE WORKING WELL BUT WHEN I USE THIS PACKAGE, FACING THIS HORRIBLE ERROR. LOTS OF DEVELPERS POSTED THIS ISSUE HERE BUT STILL NOT GET ANY PROPER SOLUTION YET. 

DEV TEAM, WITH DUE RESPECT PLEASE CHECK THIS ISSUE AND FIX IT ON HIGH PRIORITY. THANKS A LOT. LOOK FORWARD TO HEAR FROM YOU SOON.

**Comment by miguelpruivo** [comment]
@karabanovbs there's no need to scream, I also have my full time job and also try to maintain this as much as I can on my spare time. If you read the previous comments you'd see that a definite solution is just creating an `analysis_options.yaml` on your project's root folder and then add this to it:
```
analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart```
```

**Comment by karabanovbs** [comment]
@miguelpruivo why me? 😢

**Comment by miguelpruivo** [comment]
Sorry @karabanovbs, it was for @kamleshwebtech. 😄
