### ISSUE TITLE
file path is null (flutter web)

### ISSUE THREAD

**Issue by sultanmyrza** [miguelpruivo/flutter_file_picker#495]
![](https://media.giphy.com/media/pw7laGoniUdAOHeUxL/giphy.gif)

## example project 
[https://github.com/miguelpruivo/flutter_file_picker/tree/master/example](https://github.com/miguelpruivo/flutter_file_picker/tree/master/example)
## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.0)
[✓] Connected device (2 available)

• No issues found!

```
### tested on browsers

1. `**Google Chrome** Version 86.0.4240.193 (Official Build) (x86_64)`
2. `**Firefox** Release 82.0.2 (October 28, 2020)`
3. `**Safari** Version 14.0 (15610.1.28.1.9, 15610)`

#### also tried to run in release mode still not working
`flutter run -d Chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release`

**Comment by miguelpruivo** [comment]
Hi! It’s described on the wiki and also I believe it throws an exception as well saying that paths aren’t supported on the web.

It’s a web limitation since browsers use fake paths. You need to use the `bytes` property instead to access your file’s data.

**Comment by hwakstar** [comment]
please more detail.
I didn't solve the problem on web flutter.
