### ISSUE TITLE
Can't build for iOS simulator due to dependency deployment target difference

### ISSUE THREAD

**Issue by Shtille** [miguelpruivo/flutter_file_picker#498]
I build my project for iOS simulator (iOS 14.0).
The project has deployment target 11.0.
The message I get:
```
project/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 11.0:
project/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
```
Is ther any suggestion of fixing the issue without setting my project target to 9.0?

**Comment by miguelpruivo** [comment]
@Shtille for some reason this has been happening lately. Rebuilding sometimes makes it work. I’m still trying to understand what’s causing this though.

**Comment by dannycortesv** [comment]
Hello, i'm also facing this issue, any solution around?

**Comment by miguelpruivo** [comment]
Try cleaning and rebuilding or running `pod repo update` on your /ios folder.

**Comment by nemoryoliver** [comment]
same issue for me here...

**Comment by dannycortesv** [comment]
I could solve the problem by switching to stable channel, something is broken on beta one

**Comment by nemoryoliver** [comment]
> I could solve the problem by switching to stable channel, something is broken on beta one

worked when I switched to **stable** channel! Thank you

**Comment by miguelpruivo** [comment]
This plugin is only tested and ensured to work with the stable channel. Make sure you are on it.

**Comment by basilmariano** [comment]
similar issue and fixed here
https://github.com/miguelpruivo/flutter_file_picker/issues/436

**Comment by miguelpruivo** [comment]
Closing as this is likely a cached build conflict issue. Feel free to reopen if you still experience any problem related to it.

Thanks!
