### ISSUE TITLE
There is a problem with the cache directory returned by filepicker

### ISSUE THREAD

**Issue by jeromekai** [miguelpruivo/flutter_file_picker#501]
There is a problem with the cache directory returned by filepicker. In the test on a real Android device, the plug-in returns the wrong directory such as: /data/user/0/org.xxx.xxx.xxx/cache/file_picker/test.mp4
The real directory /data/data/package/cache/file_picker/test.mp4 is this directory.

Why is there such a prefix /data/user/0?
I read the document https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ, the same is that the copy cache directory is parsed incorrectly on the android device.
error:File loaded and cached at:/data/user/0.......

  This is similar to the closed bug #446, #447,

**Comment by miguelpruivo** [comment]
@jeromekai I'm sorry but even after so much digging around the way some Android devices handle their own files, make me feel like I don't have an answer for you. I'm following the good practices as per docs, but for some reason, every now and then people with different Android devices (across multiple versions) seem to experience random issues such as this one. I can't really tell you the reason why. 

Sometimes I wish that Android file management would be more restrict as iOS where there is in fact a standard followed by all devices.

Let me know if you find the issue and I'd be glad to help you, but as of now I can't really answer to your question.

**Comment by jeromekai** [comment]
> @jeromekai I'm sorry but even after so much digging around the way some Android devices handle their own files, make me feel like I don't have an answer for you. I'm following the good practices as per docs, but for some reason, every now and then people with different Android devices (across multiple versions) seem to experience random issues such as this one. I can't really tell you the reason why.
> 
> Sometimes I wish that Android file management would be more restrict as iOS where there is in fact a standard followed by all devices.
> 
> Let me know if you find the issue and I'd be glad to help you, but as of now I can't really answer to your question.



For android, I suggest to point the directory to /data/data/package/cache/file_picker/, which is also obtained by most applications, otherwise the files are actually cached here(v2.0.13), which is not compatible with some devices, unfortunately.

**Comment by miguelpruivo** [comment]
@jeromekai I'm not sure if that's doable or should be done as I'm using the default cache directory used by OS, you can see it [here](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L113).

I'm afraid that manipulating those directories manually could result in even worse bugs due to underlying permissions for accessing some paths.

**Comment by jeromekai** [comment]
> @jeromekai我不确定这是否可行还是应该做，因为我使用的是操作系统使用的默认缓存目录，您可以[在此处查看](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L113)。
> 
> 恐怕由于对某些路径的潜在访问权限，手动操作这些目录可能会导致更严重的错误。
