### ISSUE TITLE
Exception: 

### ISSUE THREAD

**Issue by aadarshadhakalg** [miguelpruivo/flutter_file_picker#503]
I had just pulled package to my app, not used yet. App runs fine in debug build But whenever I do 
`flutter run --release`

Then this error shows up. 

`
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Exception: The plugin file_picker could not be built due to the issue above.`

My local.properties file

`sdk.dir=/home/aadarsha/Android/Sdk
flutter.sdk=/home/aadarsha/snap/flutter/common/flutter
flutter.buildMode=release
flutter.versionName=1.0.0
flutter.versionCode=1`

**Comment by miguelpruivo** [comment]
Hi, please check the [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting). There's likely a solution for it there.

Thank you!

**Comment by Zfinix** [comment]
`FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ] 
/Users/chiziaruhoma/projects/socket_chat/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9
:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 39s
[ +463 ms] Running Gradle task 'assembleDebug'... (completed in 41.7s)
[   +2 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using
Jetfier to
           solve the incompatibility.
[   +7 ms] Building plugin file_picker...
[   +4 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[   +3 ms] /Users/chiziaruhoma/flutter/bin/cache/artifacts/gradle_wrapper/gradle/wrapper/gradle-wrapper.jar mode:
33188 rw-r--r--.
[   +1 ms] /Users/chiziaruhoma/flutter/bin/cache/artifacts/gradle_wrapper/gradlew mode: 33261 rwxr-xr-x.
[        ] /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew mode:
33188 rw-r--r--.
[        ] Trying to give execute permission to
/Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew.
[   +9 ms] /Users/chiziaruhoma/flutter/bin/cache/artifacts/gradle_wrapper/gradlew.bat mode: 33188 rw-r--r--.
[        ] Using gradle from
/Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew.
[        ] /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew mode:
33261 rwxr-xr-x.
[        ] executing: [/Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/]
/Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew
-I=/Users/chiziaruhoma/flutter/packages/flutter_tools/gradle/aar_init_script.gradle
-Pflutter-root=/Users/chiziaruhoma/flutter -Poutput-dir=/Users/chiziaruhoma/projects/socket_chat/build/app
-Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64
assembleAarRelease
[+12175 ms] Starting a Gradle Daemon (subsequent builds will be faster)


                     FAILURE: Build failed with an exception.

                     * What went wrong:
                     A problem occurred configuring root project 'file_picker'.
                     > SDK location not found. Define location with sdk.dir in the local.properties file or with an
                     ANDROID_HOME environment variable.

                     * Try:
                     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
                     more log output. Run with --scan to get full insights.

                     * Get more help at https://help.gradle.org

                     BUILD FAILED in 10s
[   +1 ms] Running Gradle task 'assembleAarRelease'... (completed in 12.2s)
[   +1 ms] Starting a Gradle Daemon (subsequent builds will be faster)
           
[        ] 
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'file_picker'.
           > SDK location not found. Define location with sdk.dir in the local.properties file or with an
ANDROID_HOME environment variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 10s
           
[  +10 ms] Exception: The plugin file_picker could not be built due to the issue above.
[   +3 ms] "flutter run" took 64,835ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:608:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1075:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +270 ms] ensureAnalyticsSent: 255ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
chiziaruhoma@Chiziaruhomas-MacBook-Pro-2 socket_chat % `

**Comment by Zfinix** [comment]
> ```
> [        ] * What went wrong:
> [        ] Execution failed for task ':app:processDebugResources'.
> [        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> [        ]    > Android resource linking failed
> [        ] 
> /Users/chiziaruhoma/projects/socket_chat/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9
> :5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
> [        ] * Try:
> [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
> output. Run with --scan to get full insights.
> [        ] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 39s
> [ +463 ms] Running Gradle task 'assembleDebug'... (completed in 41.7s)
> [   +2 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using
> Jetfier to
>            solve the incompatibility.
> [   +7 ms] Building plugin file_picker...
> [   +4 ms] Running Gradle task 'assembleAarRelease'...
> [        ] gradle.properties already sets `android.enableR8`
> [   +3 ms] /Users/chiziaruhoma/flutter/bin/cache/artifacts/gradle_wrapper/gradle/wrapper/gradle-wrapper.jar mode:
> 33188 rw-r--r--.
> [   +1 ms] /Users/chiziaruhoma/flutter/bin/cache/artifacts/gradle_wrapper/gradlew mode: 33261 rwxr-xr-x.
> [        ] /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew mode:
> 33188 rw-r--r--.
> [        ] Trying to give execute permission to
> /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew.
> [   +9 ms] /Users/chiziaruhoma/flutter/bin/cache/artifacts/gradle_wrapper/gradlew.bat mode: 33188 rw-r--r--.
> [        ] Using gradle from
> /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew.
> [        ] /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew mode:
> 33261 rwxr-xr-x.
> [        ] executing: [/Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/]
> /Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.0.13/android/gradlew
> -I=/Users/chiziaruhoma/flutter/packages/flutter_tools/gradle/aar_init_script.gradle
> -Pflutter-root=/Users/chiziaruhoma/flutter -Poutput-dir=/Users/chiziaruhoma/projects/socket_chat/build/app
> -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64
> assembleAarRelease
> [+12175 ms] Starting a Gradle Daemon (subsequent builds will be faster)
> 
> 
>                      FAILURE: Build failed with an exception.
> 
>                      * What went wrong:
>                      A problem occurred configuring root project 'file_picker'.
>                      > SDK location not found. Define location with sdk.dir in the local.properties file or with an
>                      ANDROID_HOME environment variable.
> 
>                      * Try:
>                      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
>                      more log output. Run with --scan to get full insights.
> 
>                      * Get more help at https://help.gradle.org
> 
>                      BUILD FAILED in 10s
> [   +1 ms] Running Gradle task 'assembleAarRelease'... (completed in 12.2s)
> [   +1 ms] Starting a Gradle Daemon (subsequent builds will be faster)
>            
> [        ] 
>            FAILURE: Build failed with an exception.
>            
>            * What went wrong:
>            A problem occurred configuring root project 'file_picker'.
>            > SDK location not found. Define location with sdk.dir in the local.properties file or with an
> ANDROID_HOME environment variable.
>            
>            * Try:
>            Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
> output. Run with --scan to get full insights.
>            
>            * Get more help at https://help.gradle.org
>            
>            BUILD FAILED in 10s
>            
> [  +10 ms] Exception: The plugin file_picker could not be built due to the issue above.
> [   +3 ms] "flutter run" took 64,835ms.
> [   +9 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
>            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:608:7)
>            <asynchronous suspension>
>            #2      FlutterCommand.verifyThenRunCommand
> (package:flutter_tools/src/runner/flutter_command.dart:1075:18)
>            #3      _rootRunUnary (dart:async/zone.dart:1198:47)
>            #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
>            #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
>            #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
>            #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
>            #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
>            #12     _rootRunUnary (dart:async/zone.dart:1198:47)
>            #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
>            #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
>            #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
>            #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
>            #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
>            #21     _rootRunUnary (dart:async/zone.dart:1198:47)
>            #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
>            #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
>            #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
>            #28     _rootRun (dart:async/zone.dart:1190:13)
>            #29     _CustomZone.run (dart:async/zone.dart:1093:19)
>            #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
>            #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
>            #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
>            #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
>            #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
>            #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
>            
>            
> [ +270 ms] ensureAnalyticsSent: 255ms
> [   +1 ms] Running shutdown hooks
> [        ] Shutdown hook priority 4
> [   +2 ms] Shutdown hooks complete
> [        ] exiting with code 1```
> ```

This was the error i got

**Comment by bdevay** [comment]
Same issue here:
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\bdeva\AndroidStudioProjects\gui\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org```

**Comment by miguelpruivo** [comment]
@bdevay the solution for your issue is the second on the [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) list.
