### ISSUE TITLE
Compress image after pick 

### ISSUE THREAD

**Issue by SachinTanpure** [miguelpruivo/flutter_file_picker#505]
How to compress an image with max width and height, after picking image from file picker? Compression is only needed for images and not for other types.

**Comment by miguelpruivo** [comment]
Hi, you should use an image compressor plugin for that. There are a lot of options available on pub.dev like [this one](https://pub.dev/packages/flutter_image_compress).

**Comment by d-apps** [comment]
> Hi, you should use an image compressor plugin for that. There are a lot of options available on pub.dev like [this one](https://pub.dev/packages/flutter_image_compress).

Is there another solution for web compression? this package is not compatible with web only mobile.

**Comment by miguelpruivo** [comment]
@d-apps I’m sorry, I’m not aware of any.
