### ISSUE TITLE
Excuse me,how i Get paths to all PDFS?

### ISSUE THREAD

**Issue by pheromone** [miguelpruivo/flutter_file_picker#507]
I encourage you to add new suggestions that you think that can make file_picker even a better package.

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

如果我只是要获取设备中所有的PDF的路径？
What if I just want to get the path to all the PDFS on the device?

**Comment by miguelpruivo** [comment]
The plugin allows you to filter for types. Use `FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: [‘pdf’]);`

Then you can access the paths. Check the documentation for more details.

Thank you.
