### ISSUE TITLE
android build fail

### ISSUE THREAD

**Issue by pheromone** [miguelpruivo/flutter_file_picker#508]
android build fail
![image](https://user-images.githubusercontent.com/14305431/99652497-dca00b00-2a92-11eb-801e-458761ddd84e.png)

**Comment by miguelpruivo** [comment]
Hi, this is not an issue. That’s the new queries API introduced on Android 30. You have details on this on the [troubleshooting section](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1).

Thank you.
