### ISSUE TITLE
Null safety upgrade

### ISSUE THREAD

**Issue by Yegorisa** [miguelpruivo/flutter_file_picker#510]
Since Null Safety is in beta, it is time to update File Picker library to support null safety. Are there any timelines on this? Thanks!

**Comment by miguelpruivo** [comment]
Yes, it’s on my plans as soon as possible.

**Comment by miguelpruivo** [comment]
@Yegorisa this is implemented on `feature/null-safety` branch, I just need to run a few more tests to make sure it doesn't break anything.

**Comment by Yegorisa** [comment]
@miguelpruivo awesome! Thanks a lot

**Comment by miguelpruivo** [comment]
@Yegorisa let me know if it’s working everything as intended.

**Comment by Yegorisa** [comment]
@miguelpruivo sorry, I currently can not test the implementation as I have not started migrating my app to null safety due to that some of the core dependencies do not have nullability support yet. If they will migrate fast, I will try File Picker with null safety. Thanks a lot!

**Comment by miguelpruivo** [comment]
@Yegorisa null safety has been added and published to pub.dev as pre-release `3.0.0-nullsafety.0`. 🎉
