### ISSUE TITLE
The getter 'platform' isn't defined for the type 'FilePicker'.  

### ISSUE THREAD

**Issue by ramaraju439** [miguelpruivo/flutter_file_picker#511]
Try importing the library that defines 'platform', correcting the name to the name of an existing getter, or defining a getter or field named 'platform'.

**Comment by miguelpruivo** [comment]
Hi @ramaraju439 I don’t understand what’s your issue. You must invoke using `FilePicker.platform.pickFiles()` and making sure you’re importing it.
