### ISSUE TITLE
windows run  make error

### ISSUE THREAD

**Issue by honglei92** [miguelpruivo/flutter_file_picker#512]
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: type 'String' is not a subtype of type 'List<dynamic>?' in type cast
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'String' is not a subtype of type 'List<dynamic>?' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
#3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:79:47)
#4      FilePickerIO.pickFiles (package:file_picker/src/file_picker_io.dart:29:7)
#5      _MyStatefulWidgetState._press (package:text_demo/app.dart:52:35)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
#21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
#24     _rootRunUnary (dart:async/zone.dart:1206:13)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _invoke1 (dart:ui/hooks.dart:265:10)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by miguelpruivo** [comment]
Looks like it’s a dup of #452.
