### ISSUE TITLE
Can not run with file_picker: ^2.1.0

### ISSUE THREAD

**Issue by NifalNizar** [miguelpruivo/flutter_file_picker#513]
![image](https://user-images.githubusercontent.com/6696455/99900850-5ecd4100-2cd8-11eb-8b8f-db314b54a3a0.png)

**Comment by miguelpruivo** [comment]
Hi @NifalNizar this has a solution described in the [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).

Thank you.
