### ISSUE TITLE
when i use hover run it can work, but if i input flutter run -d windows ,it cant open file choose system,and log is such as:

### ISSUE THREAD

**Issue by honglei92** [miguelpruivo/flutter_file_picker#514]
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelrui
vo.flutter.plugins.filepicker)
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:78:38)
#3      FilePickerIO.pickFiles (package:file_picker/src/file_picker_io.dart:29:7)
#4      _MyStatefulWidgetState._press (package:text_demo/app.dart:53:35)
#5      _MyStatefulWidgetState.build.<anonymous closure> (package:text_demo/app.dart:135:48)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
#21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
#24     _rootRunUnary (dart:async/zone.dart:1206:13)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _invoke1 (dart:ui/hooks.dart:265:10)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by miguelpruivo** [comment]
Hi. You need to use any version bellow 2.0.0 until #387. 

Thank you and sorry for any inconvenience.

**Comment by honglei92** [comment]
> Hi. You need to use any version bellow 2.0.0 until #387.
> 
> Thank you and sorry for any inconvenience.

when i use 1.13.3  it also theme error
