### ISSUE TITLE
flutter: Bad state: No element on selecting photo IOS 

### ISSUE THREAD

**Issue by xWorldx** [miguelpruivo/flutter_file_picker#515]
I am using the latest version of flutter_file_pickere and whenever I choose an image I keep getting this error after I have chosen it >>>
flutter: Bad state: No element 

I am using M1 processor with master flutter channel on iOS simulator

my code :
pickImage() async {
try {
      FilePickerResult image = await FilePicker.platform
          .pickFiles(type: FileType.image);
      if (image != null) {
        File imageFile = File(image.files.first.path);
        changeImageBefore(compressedFile.path);
      } else {
        print("er...");
      }
    } catch (error) {
      print(error);
    }
}

I already tried flutter clean and flutter build I also added the permission to my Info.plist

flutter -v:

Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                     Print this usage information.
-v, --verbose                  Noisy logging, including all shell commands executed.
                               If used with --help, shows hidden options.
    --quiet                    Reduce the amount of output from some commands.
    --[no-]wrap                Toggles output word wrapping, regardless of whether or not the output is a terminal.
                               (defaults to on)
    --wrap-column              Sets the output wrap column. If not set, uses the width of the terminal. No wrapping occurs if not writing to a terminal. Use --no-wrap to turn off wrapping
                               when connected to a terminal.
-d, --device-id                Target device id or name (prefixes allowed).
    --version                  Reports the version of this tool.
    --machine                  When used with the --version flag, outputs the information using JSON.
    --[no-]color               Whether to use terminal colors (requires support for ANSI escape sequences).
                               (defaults to on)
    --[no-]version-check       Allow Flutter to check for updates when this command runs.
                               (defaults to on)
    --suppress-analytics       Suppress analytics reporting when this command runs.
    --packages                 Path to your "package_config.json" file.

Local build selection options (not normally required):
    --local-engine-src-path    Path to your engine src directory, if you are building Flutter locally.
                               Defaults to $FLUTTER_ENGINE if set, otherwise defaults to the path given in your pubspec.yaml dependency_overrides for sky_engine, if any.
    --local-engine             Name of a build output within the engine out directory, if you are building Flutter locally.
                               Use this to select a specific version of the engine if you have built multiple engine targets.
                               This path is relative to --local-engine-src-path/out.

Options for testing the "flutter" tool itself:
    --show-test-device         List the special 'flutter-tester' device in device listings. This headless device is used to
                               test Flutter tooling.

Available commands:
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  attach            Attach to a running app.
  bash-completion   Output command line shell completion setup scripts.
  build             Build an executable app or install bundle.
  channel           List or switch Flutter channels.
  clean             Delete the build/ and .dart_tool/ directories.
  config            Configure Flutter settings.
  create            Create a new Flutter project.
  daemon            Run a persistent, JSON-RPC based server to communicate with devices.
  devices           List all connected devices.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  drive             Run integration tests for the project on an attached device or emulator.
  emulators         List, launch and create emulators.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  precache          Populate the Flutter tool's cache of binary artifacts.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.
  test              Run Flutter unit tests for the current project.
  upgrade           Upgrade your copy of Flutter.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.

**Comment by miguelpruivo** [comment]
Hi, replace `if (image != null)` with `if (image != null && image.files.isNotEmpty)`. For some reason you're getting empty content when picking files.

**Comment by xWorldx** [comment]
Hello, thanks for replying, I did that and I even trying to count how much files I get if I enabled allowMultiple and turns out I always get zero 
Here is my example code:  
pickImage() async {
    try {
      FilePickerResult image = await FilePicker.platform
          .pickFiles(type: FileType.image, allowMultiple: true);

      print(image.count);

      // if (image != null && image.files.isNotEmpty) {
      //   File imageFile = File(image.files.first.path);
      //   changeImageBefore(imageFile.path);
      // }
    } catch (error) {
      print(error);
    }
}

Console:
flutter: 0

for the whole day I have been stuck in this any help Will be really appreciated. thanks in advance.

**Comment by miguelpruivo** [comment]
Can you record it?

**Comment by xWorldx** [comment]
yes sure

**Comment by xWorldx** [comment]
sorry for the delay, I had some problems 
![ezgif-5-766346ec71c5](https://user-images.githubusercontent.com/70700918/100032173-b2827c00-2df7-11eb-99db-c641fdd7c5ae.gif)

**Comment by miguelpruivo** [comment]
Does that happen with a real device?

**Comment by xWorldx** [comment]
Unfortunately, can't test it on a real device..

**Comment by jlubeck** [comment]
It's so weird, I've been having this issue and it seems to be random. Some times it happens and some times it doesn't... is there any way to troubleshoot it?

**Comment by miguelpruivo** [comment]
After further investigation on this I believe that is related with an iOS 14 issue in some versions (not plugin) which results in HDR pictures not being properly handled by the platform. 

Please check if this only occurs with HDR pictures.

**Comment by jlubeck** [comment]
I'm using the demo images that come on the simulator. They ALL work except for one. The first one with the pink flowers:
<img width="643" alt="Screen Shot 2020-12-14 at 12 43 56 PM" src="https://user-images.githubusercontent.com/3067603/102115931-397cb000-3e0a-11eb-8701-46690eb96209.png">


Hopefully that will allow you to replicate the issue?

**Comment by miguelpruivo** [comment]
@jlubeck yes, has been discussed a few times in different threads. Somehow, iOS 14 has an issue retrieving HDR pictures (which that one is). I'm not sure if this happens on the simulator only, but that's an iOS issue.

**Comment by abdullah432** [comment]
On the simulator, I'm getting this error when trying to load an image.
```
VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      FilePickerService.pickFile (package:atlast/services/file_picker_service.dart:30:37)
<asynchronous suspension>
```

**Comment by miguelpruivo** [comment]
@abdullah432 there’s a glitch with the first image of simulator (pink flowers) that doesn’t actually load. But that’s related with an iOS 14 HDR bug, actually.

**Comment by abdullah432** [comment]
@miguelpruivo thank you for replying. I read all of your replies on different issues before posting that comment. For me non of the images work. I import some other images to a simulator and those also didn't work but the same code is working in android.

**Comment by miguelpruivo** [comment]
@abdullah432 you probably wan’t to try out with a different simulator or reset the simulator content. Looks like an issue with it. Does that happen with a real device?

**Comment by jigarfumakiya** [comment]
I am having the same issue
Any update here?
