### ISSUE TITLE
File path is empty for web.

### ISSUE THREAD

**Issue by ArpitSharma2800** [miguelpruivo/flutter_file_picker#520]
I tried latest version of file-picker in web and app both, it gives proper file name , file path in mobile app version but in web version it gives file size, file name except file path.
Flutter: “(path): must not be null”;

FilePickerResult result = await FilePicker.platform.pickFiles();

if(result != null) {
   File file = File(result.files.single.path);
} else {
   // User canceled the picker
}

file_picker: ^2.1.0

**Comment by miguelpruivo** [comment]
Hi! Paths don’t exist on the web. They are just fake paths. It’s on the docs. 🙂

Thank you!

**Comment by Albert-Jan** [comment]
Just faced the same issue and switched to using bytes, however bytes are empty on mobile. So you'll have to differtiate with an platform specific upload logic. Eg:

```
if (UniversalPlatform.isWeb) {
    firebase_storage.FirebaseStorage.instance
        .ref('$filename.png')
        .putData(filePickerResult.files.first.bytes, firebase_storage.SettableMetadata(contentType: 'image/png'))
        .then((taskSnapshot) => print(taskSnapshot.ref.getDownloadURL().then((value) => print(value))));
  } else {
    firebase_storage.FirebaseStorage.instance
        .ref('$filename.png')
        .putFile(File(filePickerResult.files.first.path), firebase_storage.SettableMetadata(contentType: 'image/png'))
        .then((taskSnapshot) => print(taskSnapshot.ref.getDownloadURL().then((value) => print(value))));
  }
```
