### ISSUE TITLE
MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null, null)

### ISSUE THREAD

**Issue by kyounglee** [miguelpruivo/flutter_file_picker#523]
file_picker I use is version 2.1.0
I did `flutter clean` and `flutter build` many times.
But the same exception is reported( as the title PlatformException already_active...)
whenever both 
1) final FilePickerResult picker = await FilePicker.platform.pickFiles(allowMultiple: true)
and
2) final PickedFile f = await ImagePicker().getImage(source: ImageSource.camera);
are called.
These routines have worked well. But the errors start to be reported after upgrading flutter version
(flutter channel release(now has some probs.) -> flutter channel dev(I use)), 
I think they are not due to the individual module, but platform specifics or module interfacing.

My environment:
>flutter doctor -v
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale ko-KR)
    • Flutter version 1.24.0-10.2.pre at C:\flutter
    • Framework revision 022b333a08 (11 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\D-174\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM N960N (mobile) • 2958a1d5be1c7ece • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 86.0.622.48

• No issues found!

>flutter upgrade
Flutter is already up to date on channel dev
Flutter 1.24.0-10.2.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (11 days ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

>flutter channel
Flutter channels:
  master
* dev
  beta
  stable

**Comment by miguelpruivo** [comment]
Hi! Can you please try on stable channel?

**Comment by kyounglee** [comment]
I will drop the issue.

**Comment by miguelpruivo** [comment]
What do you mean @kyounglee ?

**Comment by kyounglee** [comment]
public class MainActivity extends FlutterActivity {
I mean the problem solved.
    @override
    protected void onActivityResult(int requestCode, int resultCode, @nullable Intent data) {
       if ( data == null ) {
            super.onActivityResult(requestCode, resultCode, data);
       }
    }
}

**Comment by miguelpruivo** [comment]
Glad to know you’ve managed to fix it. 👍🙂

Feel free to reopen this if you still experience anything related with it.
