### ISSUE TITLE
Whenever I add the package to my project and run the app I get the following error

### ISSUE THREAD

**Issue by niteesh1215** [miguelpruivo/flutter_file_picker#528]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\MY_PROJECTS\flutter_projects\sabr_health_app\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Exception: The plugin cloud_firestore could not be built due to the issue above.

**Comment by miguelpruivo** [comment]
Hi! You need to have your app fully migrated to support Android X. [Check here](https://flutter.dev/docs/development/androidx-migration).

Thank you.
