### ISSUE TITLE
File Name issue. 

### ISSUE THREAD

**Issue by NaveenAluri** [miguelpruivo/flutter_file_picker#529]
Hi @miguelpruivo, if I pick the file contains the name like this **1234#1234.png**, it is displaying the file name as **1234** only after selecting in the mobile. 
I need complete file name even if the file name contains **#**.

Could you please help me on this?

**Comment by miguelpruivo** [comment]
Hi. What if you use the path? Is that correct?

**Comment by NaveenAluri** [comment]
Yes, I'm using the path only to extract the file name.

**Comment by miguelpruivo** [comment]
So the path is correct, but the name isn’t. Is that right?

**Comment by NaveenAluri** [comment]
No, even the path is also trimmed.

**Comment by miguelpruivo** [comment]
Ok. That can be a limitation then.  I’m not sure why the # isn’t being sanitised by the underlying platform as those names come from it.

**Comment by NaveenAluri** [comment]
@miguelpruivo, let's try it once, rename any file and place **#** inbetween the file name and try to pick that file. Then you will get better Idea.

**Comment by miguelpruivo** [comment]
<img width="716" alt="Captura de ecrã 2020-12-13, às 16 10 20" src="https://user-images.githubusercontent.com/27860743/102017255-b69e1b80-3d5d-11eb-9c63-014f476baa5b.png">
Just tried so and doesn't seem to be an issue for me. Check the screenshot.

**Comment by miguelpruivo** [comment]
Related to #487.
