### ISSUE TITLE
PickFile path is null

### ISSUE THREAD

**Issue by grammatnMcK** [miguelpruivo/flutter_file_picker#530]
I have installed the package and after using the sample code, I get a null for the path (result.files.single.path)

Flutter for Web running on a Mac. Everything in on the latest version. flie_picker: 2.1.0
<img width="220" alt="Screenshot 2020-12-04 at 11 30 56" src="https://user-images.githubusercontent.com/39949354/101153176-5d7b0d00-3624-11eb-9a22-598a6ba36c40.png">

**Comment by miguelpruivo** [comment]
Hi, that’s supposed. It’s documented on the wiki. The browsers don’t allow real paths, so paths aren’t supported on it. You must use `bytes` property on web.

Thank you.
