### ISSUE TITLE
Limiting file pick count, File Size and Video Duration

### ISSUE THREAD

**Issue by gouthamravella** [miguelpruivo/flutter_file_picker#532]
Please add a maximum number of files a user can pick at a time. And also throw the error when file size exceeds certain limit and also video duration exceeds certain limit(seconds, minutes, hours etc.)

**Comment by miguelpruivo** [comment]
Hi, thank you for your suggestion, but this has already been discussed. You can then follow those issues.

Closing as dup of #476 and #388.
