### ISSUE TITLE
A problem occurred configuring root project 'ext_storage'.

### ISSUE THREAD

**Issue by kvadrakot** [miguelpruivo/flutter_file_picker#534]
Аfter add 
  dependencies:
  file_picker: ^2.1.0

run build and recive
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ext_storage'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

Exception: The plugin ext_storage could not be built due to the issue above.`

In my Manifest
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.project.iptv.playlist.iptv_playlist_checker">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**Comment by miguelpruivo** [comment]
Hi, you likely have a solution for it in the [troubleshooting area](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).

Thank you.
