### ISSUE TITLE
Not Working on Latest Version

### ISSUE THREAD

**Issue by vanshg395** [miguelpruivo/flutter_file_picker#540]
**Description**
When Using File Picker v^2.1.0 with Flutter v1.22.0, Building the app fails.

**Error Log**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/vansh/Development/Projects/Flutter/gaius_flutter_2/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

Exception: The plugin file_picker could not be built due to the issue above.
Exited (sigterm)

**Flutter Version details**
Flutter v1.22.0

**Comment by miguelpruivo** [comment]
Hi, you likely have a solution for this on the [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).

There are a lot of similar issues here if you search, mostly related with wrongly project migration to Android X.

Thank you.

**Comment by vanshg395** [comment]
@miguelpruivo the solution you mentioned states that migrate the code to Android X, but this project was created recently and all new projects created are by default AndroidX.

**Comment by miguelpruivo** [comment]
@vanshg395 then you likely have to update your gradle version to support the `<queries>` tag on manifest introduced with Android 30. Check [here](https://stackoverflow.com/a/62969918/6919963).
