### ISSUE TITLE
FileType.custom return empty file explorer on iOS

### ISSUE THREAD

**Issue by FetFrumos** [miguelpruivo/flutter_file_picker#541]
I use last version plugin

       file_picker: ^2.1.0

This is my code:

    `FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png', 'pdf'],
    );`

It working on Android. But I have empty file explorer on iOS(14.2). If I use it:

      `FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      );` 

I have file in explorer.  
How I can use  FileType.custom on iOS?

**Comment by miguelpruivo** [comment]
Custom files on iOS always refer to the Files app. If you want to use the gallery, you need to use `FileType.image`. You have more details about it on the Wiki.

Thank you.
