### ISSUE TITLE
MissingPluginException with gradle:4.0.1

### ISSUE THREAD

**Issue by zs-dima** [miguelpruivo/flutter_file_picker#544]
MissingPluginException appear with gradle:4.0.1
gradle downgrade to 3.6.2 works well, but you recommends gradle up to 4.0.1 on plugin WiKi:
https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting

Reproduced with:
   file_picker: ^2.1.0
   file_picker: ^2.1.1
   file_picker: ^2.1.3

Flutter 1.25.0-8.0.pre

Exception on run release:
"MissingPluginException" "No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider"

**Comment by miguelpruivo** [comment]
You need to update your gradle-wrapper.properties accordingly as well.

**Comment by zs-dima** [comment]
gradle-wrapper.properties had been updated as documented:
> https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting
> For example, for gradle 4.0.1, you should have:
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by miguelpruivo** [comment]
Try with:
```
classpath 'com.android.tools.build:gradle:3.5.4'
```
and
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
```

**Comment by zs-dima** [comment]
@miguelpruivo  
As I mention in issue description gradle:3.6.2 works fine, but according WiKi gradle:4.0.1 have to work fine as well

**Comment by miguelpruivo** [comment]
@zs-dima I only recommend it if you are using Android SDK 30 because it is required for <queries> tag on manifest. Other than that, you can stick with what you have as long as it works. 🙂

**Comment by zs-dima** [comment]
@miguelpruivo 
Could I kindly ask what you recommend?
Downgrade gradle or fix manifest somehow?

**Comment by miguelpruivo** [comment]
You can stick with 3.6.2 if it's working for you. You should only update to one of the recommended one if you are experiencing the [described issue](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).

**Comment by zs-dima** [comment]
@miguelpruivo 
What about remove gradle:4.0.1 from WiKi if it does't work with the latest flutter_file_picker and default Flutter setup

**Comment by zs-dima** [comment]
this settings works with the latest Flutter dev + IDEA/Android Studio + flutter_file_picker:
```
classpath 'com.android.tools.build:gradle:3.6.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```
- but settings you providing in the WiKi are not
