### ISSUE TITLE
 MissingPluginException with gradle:4.0.1

### ISSUE THREAD

**Issue by zs-dima** [miguelpruivo/flutter_file_picker#546]
all other plugins, including sentry_flutter require correct gradle versions to work well:
```
classpath 'com.android.tools.build:gradle:4.0.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

but file_picker plugin works only with certain gradle versions:
```
classpath 'com.android.tools.build:gradle:3.6.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

more over WiKi recommends gradle up to 4.0.1:
https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting

Reproduced with:
   file_picker: ^2.1.0
   file_picker: ^2.1.1
   file_picker: ^2.1.3
   file_picker: ^2.1.4
   file_picker: ^3.0.0-nullsafety.0

Flutter 1.25.0-8.0.pre

Exception on run release:
"MissingPluginException" "No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider"

related to https://github.com/miguelpruivo/flutter_file_picker/issues/544

**Comment by miguelpruivo** [comment]
Hi, the exception thrown has nothing to do with `file_picker` but with `path_provider` instead. Maybe you should file an issue there.

Thank you.

**Comment by zs-dima** [comment]
@miguelpruivo 
I have no issue with path_provider and gradle:4.0.1
sentry_flutter require correct gradle version (gradle:4.0.1) and works well why file_picker fire issue then?

**Comment by zs-dima** [comment]
@marchellodev 
thanks for reply
I created related path_provider issue, I guess they will complain back to the file_picker plugin:
https://github.com/flutter/flutter/issues/72353

**Comment by marchellodev** [comment]
@miguelpruivo I should just change my nickname at this point :)

**Comment by zs-dima** [comment]
@miguelpruivo 
Fixed with latest Flutter dev by Flutter team, thanks a lot
