### ISSUE TITLE
My App losing focus on file picker open.(android)

### ISSUE THREAD

**Issue by sarry173** [miguelpruivo/flutter_file_picker#547]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS)
2. Platform OS version
3. File type (filter) — when applicable
4. Detailed steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Hi @sarry173 that's probably normal, since it's launching an activity to handle the files. If this is an issue for you, just request back the focus `FocusScope.of(context).requestFocus(yourNode);`.

I'm sorry for any inconvenience.
