### ISSUE TITLE
Android not support this library

### ISSUE THREAD

**Issue by AnujWebhopers** [miguelpruivo/flutter_file_picker#549]
* dependencies:
  file_picker: ^2.1.4

When I am using this dependency Andriod not support this library and on iOS it's working fine.
After that I add these library classes to my project then I get this error. Below error shown

**Error**:
Unhandled Exception: MissingPluginException(No implementation found for method custom on channel miguelruivo.flutter.plugins.filepicker)

**Comment by miguelpruivo** [comment]
Hi, this needs more info, but I suspect it may be related with #545. You may want to take a look into the discussion there.

Thanks.
