### ISSUE TITLE
Android release apk get crashed on start

### ISSUE THREAD

**Issue by Priyalkothari** [miguelpruivo/flutter_file_picker#550]
**Issue details**
1. Platform (Android)

**Error Log**

**Flutter Version details**
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.685], locale en-IN)

**Additional context**
I am using latest version of plugin 2.1.4, It runs perfectly in debug mode but it get crashed in release mode. In release mode I am getting error "java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver". Is there any solution for that?

**Comment by miguelpruivo** [comment]
Hi @Priyalkothari, you can check the troubleshooting section of the Wiki for details regarding this, but I suspect that this may be a similar issue of #545. You may want to check the discussion there.

Thank you.
