### ISSUE TITLE
SwityGif error iOS

### ISSUE THREAD

**Issue by zsyphon** [miguelpruivo/flutter_file_picker#551]
I am currently experiencing this error: Compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0. I've tried deployment versions on my runner and pods project but nothing is working. Does anyone have a suggestion on how to get around this error? I've also run pod update in my ios folder. 

The error occurs because of the SwitfyGif import in file DKPhotoBaseImagePreviewVC.swift

[✓] Flutter (Channel master, 1.25.0-4.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.52.0)
[✓] Connected device (4 available)

**Comment by miguelpruivo** [comment]
Hi! Go to your `/ios` folder and run `pod repo update` after cleaning your project.

**Comment by zsyphon** [comment]
Thank you. I was able to fix it using the pod file too.

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

     if 'DKImagePickerController' == target.name
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          end
      end
      if 'DKPhotoGallery' == target.name
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          end
      end
  end
end
