### ISSUE TITLE
Generated plug registrant generates warning.

### ISSUE THREAD

**Issue by bsutton** [miguelpruivo/flutter_file_picker#552]
I'm using  file_picker: ^2.1.4 and file_picker_cross: ^4.2.6

file_picker generates a file:

generated_plugin_registrant.dart 

which includes the following code:

```dart
//
// Generated file. Do not edit.
//

import 'package:file_picker/src/file_picker_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  FilePickerWeb.registerWith(registrar);
  registrar.registerMessageHandler();
}


```

The first import line:
``` dart
import 'package:file_picker/src/file_picker_web.dart';
```
generates a lint warning:
```
Don't import implementation files from another package.
```

This is caused by the import referencing to a file in the 'src' directory.

As I understand the dart guides this file should either be exported from the lib/file_picker.dart file or if it needs to be conditionally included then should be moved from the src folder into the lib folder.

**Comment by miguelpruivo** [comment]
Hi @bsutton this is a generated file, you can ignore it your static analysis rules. There’s no way to avoid this other than exporting an internal file from the lib that shouldn’t be exported (only for the generated because requires it).

I’m sorry for any inconvenience.

**Comment by bsutton** [comment]
I would argue that if its used by a generated file then it actually forms part of the api and therefore should be exported.

**Comment by miguelpruivo** [comment]
@bsutton no because you don’t need to import the file_picked_web directly since the platform is automatically handled at runtime. This prevent misleading imports making it uniform for the dev. You only need to import `file_picker`. That’s all, regardless of the platform.

**Comment by bsutton** [comment]
There is a balance point somewhere here.

The method you have used means that everyone sees the lint error and has to
deal with it.

If you expose it as part of the formal api then most people won't even
notice it. You can then document the api and note that it's only required
for the generated code.
I think this approach would actually be less invasive for developers than
the current method.
