### ISSUE TITLE
file picker not working

### ISSUE THREAD

**Issue by jafar260698** [miguelpruivo/flutter_file_picker#554]
Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
E/flutter (19823): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

**Comment by miguelpruivo** [comment]
Closing as dup of #544.
