### ISSUE TITLE
in android problem

### ISSUE THREAD

**Issue by jack-xiaobaicai** [miguelpruivo/flutter_file_picker#557]
On the Android platform, if the type is selected as Image, there will be no response if multiple selection is turned on, only single selection can be made, and multiple selection can only be made if the number is any. Please kindly solve my doubts, thank you

**Comment by miguelpruivo** [comment]
Hi @jack-xiaobaicai, I’m sorry you’re experiencing an issue, but I need more details. This shouldn’t happen. Does that happen with multiple devices? Have you trying cleaning and rebuilding?

**Comment by jack-xiaobaicai** [comment]
I'm very sorry that I don't have a real Android device here, but the real ios device is normal, so the Android emulator will not be able to choose more than one device

**Comment by FakenMaster** [comment]
Some image applications can't accept multiple selections. If you use a real Android device, different photo choose applications will have different actions.
