### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by odejinmi** [miguelpruivo/flutter_file_picker#558]
**Issue details**
1. Platform (Android/iOS) Android
2. Platform OS version version 9
3. File type (filter) — when applicable
4. Detailed steps to reproduce

**Error Log**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\TOLULOPE\AndroidStudioProjects\megacheapdata\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 1s

**Comment by misaelriojasftf** [comment]
Same issue here !

**Comment by misaelriojasftf** [comment]
hey if you look into troubleshooting page you will find the fix 

https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1

**Comment by misaelriojasftf** [comment]
also there are many duplicated issues like this which are closed so this should be too. check old issues

**Comment by miguelpruivo** [comment]
Hi! Thank you for finding the answer @misaelriojasftf. Have a nice Christmas. 🎄
