### ISSUE TITLE
Question related to flutter go implementation

### ISSUE THREAD

**Issue by long1eu** [miguelpruivo/flutter_file_picker#559]
If I build the macOS app and distribute it do my users need to also install go or the app has all it needs?

**Comment by miguelpruivo** [comment]
That’s a good question. Cc: @DenchikBY @GeertJohan

**Comment by GeertJohan** [comment]
Just the app. It works standalone. They don't need the Go compiler. Just like they don't need the Dart compiler :)

**Comment by miguelpruivo** [comment]
Thank you @GeertJohan! Have a nice Christmas!

**Comment by GeertJohan** [comment]
No problem @miguelpruivo. Happy days!
