### ISSUE TITLE
Still unusable since 1.7 on IOS (cant compile)

### ISSUE THREAD

**Issue by cyberpwnn** [miguelpruivo/flutter_file_picker#562]
Podfile

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'false'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

Note that this is in there.
```
target 'Runner' do
  use_frameworks!
```

`Compiling for iOS 9.0, but module 'DKPhotoGallery' has a minimum deployment target of iOS 10.0: /Users/??????/Library/Developer/Xcode/DerivedData/Runner-bqkfvlambbuetjbspiblwaqybgcj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/DKPhotoGallery/DKPhotoGallery.framework/Modules/DKPhotoGallery.swiftmodule/armv7-apple-ios.swiftmodule`

I am compiling with IOS 10, I dont know what the problem is, Don't care for multiple images if I can't even use it. And it's impossible to use anything before 1.7 because its not exactly stable on web anymore.

Also, I tried https://github.com/miguelpruivo/flutter_file_picker/issues/551#issuecomment-748566195. Same error, no difference.

**Comment by miguelpruivo** [comment]
I’m sorry that you’re experiencing this, but given the number of users using this plugin and none seem to complain about the same, it should be related with your project somehow, otherwise a lot of issues should point towards the same direction.

Try creating a whole new project and see if it works there, if so, try digging what dependencies might be different than your old one.

**Comment by FloPMT** [comment]
@cyberpwnn I feel your pain. Finally resolved this by automatically removing custom deployment targets after pod install. Change your Podfile's post install script to this:

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' #Remove custom deployment targets
    end
  end
end`
