### ISSUE TITLE
Build failing with below error

### ISSUE THREAD

**Issue by gouthamravella** [miguelpruivo/flutter_file_picker#563]
I am using latest file_picker:'2.1.4'. And I'm getting the below issue while running the app in debug mode.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/username/cheers/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
```

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.

**Comment by miguelpruivo** [comment]
Hi, the solution for this [is described on the wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1).

Thank you.
