### ISSUE TITLE
(path): Must not be null

### ISSUE THREAD

**Issue by mickySignNow** [miguelpruivo/flutter_file_picker#564]
Hi there, 
I am using flutter **web** on a **macBook.**

trying to get a CSV file.

when I pick a file it prints its name, but then shows an error.

<img width="483" alt="Screen Shot 2020-12-30 at 12 24 27" src="https://user-images.githubusercontent.com/75248001/103345401-f8d39680-4a99-11eb-8cd5-9f1d90a82432.png">

<img width="683" alt="Screen Shot 2020-12-30 at 12 25 00" src="https://user-images.githubusercontent.com/75248001/103345431-0e48c080-4a9a-11eb-9216-d2f87d568cb2.png">

**Comment by miguelpruivo** [comment]
Hi. As described on the wiki, paths don’t work on web because of browsers restrictions. You need to use the `bytes` property to access the file data instead.

**Comment by mickySignNow** [comment]
Awesome, thanks!



בתאריך יום ד׳, 30 בדצמ׳ 2020, 13:52, מאת Miguel Ruivo ‏<
notifications@github.com>:

**Comment by mickySignNow** [comment]
Hi miguel sorry to bother you,

can you give me a short implementation of how to get a CSV file to flutter
web, and off course read it.

thank again for your awesome package, great job!

‫בתאריך יום ד׳, 30 בדצמ׳ 2020 ב-14:52 מאת מיקי קרויטרו <‪micky@signow.org
‬‏>:‬

**Comment by miguelpruivo** [comment]
@mickySignNow unfortunately `.csv` is unsupported as a single filter. You need to use `FileType.all` when picking files and you should be able to see your `.csv` files.
