### ISSUE TITLE
Want to Get files from local storage

### ISSUE THREAD

**Issue by Dam0n-DX** [miguelpruivo/flutter_file_picker#565]
Hey I'm building an app which related to Document manager in flutter
i want to show all doc types files in my app from mobile local storage , since File picker show me that we need to pick files and we get that files path as well, 
But I don't want to pick some file , i want my application to search files(like .pdf ,pptx, .doc etc. )  show these files in a grid view or list view like any file manager in our phone 
Does this file picker can help me out in this or some another package I need , please help me out ..
till now i cannot figure any help in this problem from file picker plugin 

I'm show a prototype down here which shows files from local storage , and move anywhere in the folder
![Screenshot_2020-12-19-16-34-02-81_4aed3257f278fcf7bfa3abd644e23333](https://user-images.githubusercontent.com/68112998/103349556-25e86f00-4ac3-11eb-8357-2ab159daca6a.jpg)

https://user-images.githubusercontent.com/68112998/103349569-313b9a80-4ac3-11eb-9aeb-ba5aa9cb9432.mp4

**Comment by miguelpruivo** [comment]
Hi! Looks like you want to build a Flutter file explorer yourself. This plugin is not suitable for that and you’ll have to search for some plugin that gives you a listing of files. I’m not sure if there is even something for that already available.
