### ISSUE TITLE
Error: Invalid argument(s) (path): Must not be null

### ISSUE THREAD

**Issue by Buildex** [miguelpruivo/flutter_file_picker#566]
Hey, I can't get the file out of the picker on Flutter Web. The output says:
`Error: Invalid argument(s) (path): Must not be null`

But I am sure that I did everything right...
```
// On a button
onPressed: () async {
              FilePickerResult result = await FilePicker.platform.pickFiles();
              if (result != null) {
                print(result.files.single.name);
                File file = File(result.files.single.path);
                await uploadFile(file, context);
              }
            }
```

**Comment by Buildex** [comment]
I am able to get the size and the file name, as well as the bytes. But not the path.

When I try uploading the bytes to firebase storage, it uploads just a 9 bytes file. Maybe it is a firebase storage issue but I am not able to get the path in the picker so...

**Comment by rlee1990** [comment]
@Buildex did you resolve this?

**Comment by gOzaru** [comment]
How did you resolve this? Please share your update. THank you.
