### ISSUE TITLE
Not working in newly create project... in vs code... but when I try to run sample it works fine.. but when I create new project and installs this plugin.. the does not launch in android. here is the full log in debug,,

### ISSUE THREAD

**Issue by nextcodelab** [miguelpruivo/flutter_file_picker#567]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS)
2. Platform OS version
3. File type (filter) — when applicable
4. Detailed steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by nextcodelab** [comment]
`Launching lib\main.dart on SM G955N in debug mode...
 lib\main.dart
Parameter format not correct -

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Robel\Documents\Flutter Projects\FlutterApp\flutter_app\android\Projects\FlutterApp\flutter_app\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 24s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: The plugin file_picker could not be built due to the issue above.
Exited (sigterm)
`

**Comment by miguelpruivo** [comment]
Hi, solution for that is described on the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1).

Thank you and happy new year.

**Comment by nextcodelab** [comment]
I downloaded file_picker 1.1.0 and now it seem works fine... if I migrate to androidx my other packages will be broken or there are other essues will come out..
