### ISSUE TITLE
path on PlatformFile returns null

### ISSUE THREAD

**Issue by VikramAdi** [miguelpruivo/flutter_file_picker#568]
**Issue details**
Platform - Web on MacOS- Big Sur 11.1
Following the standard example from the documentation, I am able to pick the file, get other attributes on the file like name, size, extension, however, I am unable to get the path of the file using platformFile.path.

**Flutter Version details**
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64,
    locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/aditya/flutterdev/flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52
      -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    • Android SDK at /Users/aditya/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/aditya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Users/aditya/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

**Additional context**

**Comment by msoham123** [comment]
Same problem but on Windows. Also using Flutter Web!

**Comment by miguelpruivo** [comment]
Hi. I’ve posted here multiple times and also have this on the wiki explained: on web paths don’t work because browsers don’t allow it. You need to use `bytes` property. The exception when accessing the path is intended.

Thank you.
