### ISSUE TITLE
Show the progress of files being downloaded from cloud

### ISSUE THREAD

**Issue by filipedfs** [miguelpruivo/flutter_file_picker#572]
This could be useful especially when downloading large files from Dropbox, Google Drive, etc.

**Comment by miguelpruivo** [comment]
Hi @filipedfs I'm not quite sure if this is possible on both platforms — I recall having some issues with it, hence the reason why it's not implemented, but I might as well be wrong.

**Comment by filipedfs** [comment]
Thank you for your reply @miguelpruivo. I don't think this is a big problem, but because my app deals with video files, sometimes the size of the file is big and this feature could be useful. But I rely on plugins because I don't know native code. It is ok if this is really impossible.

**Comment by Iradukunda-Nadia** [comment]
@miguelpruivo could this be implemented for files that are downloaded from iCloud?
