### ISSUE TITLE
file.size

### ISSUE THREAD

**Issue by sm2017** [miguelpruivo/flutter_file_picker#573]
Why `file.size`  is  in KB? How can I have it in `Byte` without checking file size again?

**Comment by miguelpruivo** [comment]
Hi. You just need to multiply by 1024 and you’ll get the size in bytes. 😬

**Comment by sm2017** [comment]
@miguelpruivo it's not correct, As `size` ins `int` and it lost precision 
`1023 byte` is equal to `0 KB`

**Comment by sm2017** [comment]
@miguelpruivo event if you change `size` type` to `double` , `kb *1024` is not precise

**Comment by miguelpruivo** [comment]
Then open a `File` descriptor and check the size from there. I don't believe there is other way around. Typically people display the file size in the UI in kb, hence the reason why it is in kb.

I might change it to bytes later if more people ask it though.

**Comment by sm2017** [comment]
@miguelpruivo I think it is a not good reason
To have a precise byte size, we must check file size again and it is a redundant calculation
If you add a size in `Byte` , you can convert it to `KB` without problem, you can also add a `getter` method

It is not only the UI, to upload large files, in most servers there is a chucked upload technique that you must start uploading creating an upload session,   To create upload session the server is need to know the size of file

**Comment by miguelpruivo** [comment]
I’ll update it then.

**Comment by miguelpruivo** [comment]
@sm2017 done with [2.1.5](https://pub.dev/packages/file_picker/changelog#215).

Thank you for your suggestion.

**Comment by sm2017** [comment]
@miguelpruivo Thanks for your update
I think it's a breaking change, If you follow semver it's better to update major version
