### ISSUE TITLE
Stuck in the pod install

### ISSUE THREAD

**Issue by liuchenglove** [miguelpruivo/flutter_file_picker#575]
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...

**Comment by miguelpruivo** [comment]
Hi, I'm sorry that you having an issue, but this has nothing to do with the plugin itself. That's just part of any Flutter build for iOS and it may take a while if you have multiple dependencies and your connection is slow.

If you want to check the details for it, you can run `pod install` manually on your project and check each dependency being installed.
