### ISSUE TITLE
Question READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by sm2017** [miguelpruivo/flutter_file_picker#576]
Can you please tell me why you add [READ_EXTERNAL_STORAGE](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/AndroidManifest.xml#L3)

**Comment by miguelpruivo** [comment]
@sm2017 because if you want to access external storage files, you might need those permissions. 🙂

**Comment by sm2017** [comment]
@miguelpruivo as far as I remember pickers is not using external storage files!! May be I'm wrong!

**Comment by miguelpruivo** [comment]
@sm2017 in some devices, where you can have attached SD cards for example, you may also want those to be available on the explorer as well.

**Comment by bmahuvi** [comment]
Is there a way to disable READ_EXTERNAL_STORAGE?
