### ISSUE TITLE
Support drag and drop feature

### ISSUE THREAD

**Issue by derrick56007** [miguelpruivo/flutter_file_picker#578]
![drag-drop-upload-1](https://user-images.githubusercontent.com/5177280/103962233-5b1c3f00-510b-11eb-85dc-f2a9955f2f90.gif)

It would be nice if this package could include a drag and drop implementation as shown above

**Comment by miguelpruivo** [comment]
@Derrick56007 feel free to issue a PR with that and I’d be glad to review it. 👍
