### ISSUE TITLE
when file_picker is added to pubspec.yaml, flutter pub get shows error

### ISSUE THREAD

**Issue by Chronoviser** [miguelpruivo/flutter_file_picker#581]
I added the file_picker package to my project, earlier it was working fine
But when I added some more packages, `flutter pub get` started showing an error.
whenever I remove the file_picker package, `flutter pub get` against works perfectly.

It is showing some 'flutter_plugin_android_lifecycle' problem.

my pubspec.yaml
![image](https://user-images.githubusercontent.com/52380781/104093296-b6873200-52af-11eb-9cd9-ada2ec69e3ff.png)
 
error i am facing
![image](https://user-images.githubusercontent.com/52380781/104093315-d4549700-52af-11eb-87e0-8f84ab74a24d.png)

my flutter doctor -v
`[√] Flutter (Channel master, 1.24.0-8.0.pre.143, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)
    • Flutter version 1.24.0-8.0.pre.143 at C:\src\flutter
    • Framework revision e4d94f7ccd (9 weeks ago), 2020-11-07 12:15:22 +0100
    • Engine revision 1e3ceb037f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)
    • Pub download mirror https://pub.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\91628\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: G:\Android Studio Installed\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at G:\Android Studio Installed
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at G:\IntelliJ\IntelliJ IDEA Community Edition 2020.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code
    • VS Code at C:\Users\91628\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • Mi A2 (mobile) • 4ae9e34 • android-arm64 • Android 10 (API 29)

• No issues found!

`

**Comment by miguelpruivo** [comment]
Hi @Chronoviser I’m sorry that you’re having issues with it, but there a lot of other similar issues on this repo and likely there’s a fix in the troubleshooting.

This is typically due to the fact that the project could be wrongly migrated to Android X.

**Comment by Chronoviser** [comment]
can you share some link, on how to solve this issue

**Comment by miguelpruivo** [comment]
Check [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).
