### ISSUE TITLE
image bytes.length and size is not equal on Android.

### ISSUE THREAD

**Issue by lfbrunke** [miguelpruivo/flutter_file_picker#582]
When I pick an image on iOS and Web the bytes.length and the size is always equal.
When I do the same on android they differ (Think the bytes.length is wrong), since the picked images is always "a little" corrupt. (Corrupt JPEG data: premature end of data segment)

> PlatformFile: this.bytes != this.size, (Android)

BR
Lars Brunke, Webstream.

**Comment by miguelpruivo** [comment]
@lfbrunke how different they are?

**Comment by lfbrunke** [comment]
I think it can be up to 10%. But the final images can always be viewed. But with errors like:
Corrupt 'JPEG data: premature end of data segment' or 'CorruptImageProfile'
The issue don't happens all the time. A few times after a rebuild there is no problems.

**Comment by miguelpruivo** [comment]
Hum, I have my doubts that this could be related with the plugin itself. Never seen nothing like this before. Have you tried with other device/files?

**Comment by lfbrunke** [comment]
I have seen the issue on a virtual Nexus phone and on a real tablet.
I will do more tests, to see what can cause this

**Comment by lfbrunke** [comment]
Now I have done some testing. And I am pretty sure that the problem is that all data is not read from a picked file when FilePicker.platform.pickFiles returns. I use withData set to true. The problem only occurs on older slow devices - I think.

I use:

FilePickerResult result = await FilePicker.platform.pickFiles(
      withData: true,
);

My solution har been to make a delay on some seconds after this call. Then that bytes.length and size is always equal.

**Comment by miguelpruivo** [comment]
You shouldn’t use `withData` as much as possible. That flag only exists because web actually needs it and it’s just part of a convenience to help with smaller files.

As a suggestion, you can pick the files and then load on the fly when they are required or you can use streamed data.

**Comment by lfbrunke** [comment]
Can you write a short example where you receive streamed data.

 FilePickerResult result = await FilePicker.platform.pickFiles(
     withReadStream: true,
 );

......

**Comment by miguelpruivo** [comment]
Sorry for being late on this, I hope you've figured it by yourself by now. Anyway, here you have it:
```
    result.files.first.readStream.listen((bytes) {
         // Do whatever you want with the file byte chunks, such as uploading
      });
```

**Comment by lfbrunke** [comment]
Hi

Yes I have solved it.

I think you should include in your examples on GitHub. And make clear that 'You shouldn’t use withData as much as possible’, because of the reason your specifies.

BR
Lars Brunke
