### ISSUE TITLE
getFile doesnt work at all.

### ISSUE THREAD

**Issue by ZAE3600** [miguelpruivo/flutter_file_picker#583]
file = await FilePicker.getFile(type: FileType.image);

pubspec.yaml

dependencies:
  firebase_core: ^0.6.0
  firebase_storage: ^6.0.0
  permission_handler: ^5.0.1+1
  file_picker: ^2.1.5+1

this is error it shows: error: 
The method 'getFile' isn't defined for the type 'FilePicker'. (undefined_method at [real_time_data_transfer] lib\send.dart:30)

can someone please help me out.

**Comment by miguelpruivo** [comment]
You need to check the documentation. You are using the plugin wrongly.
```
FilePicker.platform.pickFiles(type: FileType.image);
```

**Comment by ZAE3600** [comment]
Thanks. But I cannot see the documentation text hyperlinked on the website at all. 

https://pub.flutter-io.cn/packages/file_picker

**Comment by ZAE3600** [comment]
I'm facing an error after using the plugin, properly,

This is what it shows after running the program: 


The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker...
Running Gradle task 'assembleAarRelease'...


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin file_picker could not be built due to the issue above.


Can anyone please help me with this.

**Comment by miguelpruivo** [comment]
You need to make sure you have your project fully migrated to Android X. Check the [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).

**Comment by ZAE3600** [comment]
Yes, I have migrated my project completely to androidX and have also checked the solutions in the troubleshooting section too. But it didn't work at all.

It still shows the same error.

**Comment by miguelpruivo** [comment]
@ZAE3600 try creating a new project and add only this plugin and build. If it works, you’ll need to dig down what may be conflicting with it. There a lot of other similar issues if you search on this repo that ended up being something related with the project.

**Comment by ZAE3600** [comment]
I created a new project and did as you said and it still shows the same error.

here is what it shows:


Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     Z:\applications\file_picker_ex\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker...
Running Gradle task 'assembleAarRelease'...


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin file_picker could not be built due to the issue above.

**Comment by ZAE3600** [comment]
yeah, I did and got an error and got the solution for it in the troubleshooting section and it works fine now, thanks.
