### ISSUE TITLE
File selection problem

### ISSUE THREAD

**Issue by misskter** [miguelpruivo/flutter_file_picker#584]
When I use this plug-in, even if I set it up 
```
  FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: [ 'pdf'],
    );
```
But I can still choose JPG and other formats。

My development environment is Android。

[√] Flutter (Channel unknown, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (2 available)

file_picker: 2.0.0

When I use the latest version, I can't use it. Some build errors are prompted. So I'm using version 2.0.0。

When I choose a file format that is not included in allowedExtensions many times, the application will exit. I don't know why.

**Comment by miguelpruivo** [comment]
Hi! That might be one the things that [is described on the troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-3).

I’m sorry for any inconvenience.
