### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by ashwin31** [miguelpruivo/flutter_file_picker#585]
I tried this on flutter 1.26 and got error.

```
Note: /home/ashwin/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-2.1.5+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java uses or overrides a deprecated API.
```

can you fix it in next release?

**Comment by miguelpruivo** [comment]
@ashwin31 thats not actually an issue. Just a warning over deprecated API’s. Check the latest version. Thank you.

**Comment by ashwin31** [comment]
file_picker-2.1.5+1 is the latest version isn't it? and flutter 1.26
can you tell me what am I missing here?
I tried file_picker-3.0.0-nullsafety.2 too but getting same warning.
