### ISSUE TITLE
Get data using file path on IOS

### ISSUE THREAD

**Issue by Gibrat-Erisov** [miguelpruivo/flutter_file_picker#586]
I am doing a project with a native module on IOS.
And I ran into a problem that I do not know how to get data using an absolute path.

I have an example, but it doesn't use the absolute path to the file.
```
let xmlData = NSData(contentsOfFile: Bundle.main.path(forResource: "test", ofType: "xml") ?? "") as Data?
let pkcs12_path = Bundle(for: self).path(forResource: "test", ofType: "p12")
fp = fopen(pkcs12_path?.utf8CString, "rb")
```

How can i get file data using File_Picker path in swift?

**Comment by miguelpruivo** [comment]
@Gibrat-Erisov this plugin is suppose to be used only with Flutter projects on Flutter side.

I'm sorry for any inconvenience.
