### ISSUE TITLE
null file ptch

### ISSUE THREAD

**Issue by saeed1366** [miguelpruivo/flutter_file_picker#587]
can not file patch in flutter web 

![Screenshot (62)_LI](https://user-images.githubusercontent.com/25414852/104733923-ad391200-5754-11eb-8944-149fed4c9006.jpg)

**Comment by miguelpruivo** [comment]
@saeed1366 paths could't be retrieve in the web because browsers don't allow it. You need to access `bytes` property instead. That's detailed in the documentation (Wiki).

Thank you.
