### ISSUE TITLE
Can't pick folder on Android 11

### ISSUE THREAD

**Issue by boomerkuigi** [miguelpruivo/flutter_file_picker#589]
Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
On Android 11 . I can't pick folder (created by system or even created by me for this purpose) on my device storage - it return "/"

**Issue details**
1. Platform (Android/iOS) : Android
2. Platform OS version : 11
3. File type (filter) — when applicable : Folder
4. Ran the demo to test out folder picking

**Error Log**
D/FilePickerDelegate(11364): [SingleFilePick] File URI:content://com.android.externalstorage.documents/tree/primary%3APictures%2FNetEaseGame/document/primary%3APictures%2FNetEaseGame
W/cal_zip_manage(11364): Accessing hidden method Landroid/os/storage/StorageVolume;->getPath()Ljava/lang/String; (greylist-max-q,test-api, reflection, denied)
I/flutter (11364): /

(the last print is by me on the pickFolder method after Future resolved)

**Screenshots and/or video**

**Flutter Version details**
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.25.0-8.1.pre at /home/boomer/dev/flutter
    • Framework revision 8f89f6505b (5 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/boomer/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/share/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /usr/local/share/android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/share/android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM G770F (mobile) • 192.168.1.19:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

**Additional context**

**Comment by miguelpruivo** [comment]
Does that happen for all folders?

**Comment by boomerkuigi** [comment]
Yes all folders

**Comment by AnjalaD** [comment]
I am having a similar issue in Android 10.
But I m only getting this issue ( returning "/" ) when I directly select the downloads folder.
If I select folders by going through the storage it works. (including downloads folder)

**Comment by miguelpruivo** [comment]
@AnjalaD that's a known behavior, since Downloads folder are actually one of those "protected" types AFAIK.

**Comment by AnjalaD** [comment]
@miguelpruivo Is there a way to work around that.

**Comment by miguelpruivo** [comment]
@AnjalaD I'm sorry, I don't believe there is. But let me know if you come up with something else.

Thank you and sorry for any inconvenience.
