### ISSUE TITLE
Upload files limit and also showing count for selected files

### ISSUE THREAD

**Issue by SaiKrishnaReddy644** [miguelpruivo/flutter_file_picker#590]
showing the file upload limit and showing count while selecting the files would be good. showing alert on selecting more than limit of files

**Comment by miguelpruivo** [comment]
Hi. The first one is a dup of #64. The second unfortunately is not possible at all, since the picker uses the native pickers from the underlying platform, so it’s up to them to choose wether or not to show the selected files counter.

I’m sorry for any inconvenience.
