### ISSUE TITLE
Path is null or incorrectly populated on Web (chrome browser)

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [miguelpruivo/flutter_file_picker#591]
**Describe the bug**

Using the copy and pasted example code for picking a single file.
After picking a file the path is null, but the data is populated and filename.
If I set withData:false and withReadStream:false the path is populated, however its with the file data base64 encoded!

**Issue details**

**Flutter Version details**
✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.2.pre at /Users/leehiggins/development/flutter
    • Framework revision b0a2299859 (2 weeks ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/leehiggins/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

**Additional context**
None

**Comment by miguelpruivo** [comment]
Hi @LeeMatthewHiggins, similar issues have been opened multiple times and this is documented on the wiki as well as thrown an exception saying that paths aren't supported on web.

This is a browser limitation so paths can't be used on web. You must use the `bytes` property instead when picking files from web.

Sorry for any inconvenience.

**Comment by LeeMatthewHiggins** [comment]
I see, thanks for the quick response. Keep up the good work !
Just found the FAQ ;)
