### ISSUE TITLE
Overrides deprecated API

### ISSUE THREAD

**Issue by melaLetics** [miguelpruivo/flutter_file_picker#594]
Using Version ^2.1.5+1 on Android (minSdkVersion 26 and targetSdkVersion 29) there is a note while building my app in debug or release mode:
Note: C:\Users\[...]\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.5+1\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java uses or overrides a deprecated API.

I'm on flutter Channel master, 1.26.0-2.0.pre.168.
The plugin works as expected in debug mode but in release mode the app does not start (stops at splash screen).

My result from flutter doctor -v:
[√] Flutter (Channel master, 1.26.0-2.0.pre.275, on Microsoft Windows [Version 10.0.18363.1316], locale de-DE)
    • Flutter version 1.26.0-2.0.pre.275 at C:\Users\melak\ws\flutter
    • Framework revision d9044a8a61 (2 weeks ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\melak\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\melak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Pixel 5 (mobile) • 0B281FDD4006NT • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)       • edge           • web-javascript • Microsoft Edge 87.0.664.55

• No issues found!

**Comment by miguelpruivo** [comment]
Hi @melaLetics this is not an issue and is actually required to use that deprecated API. 

I believe you can suppress those warnings on your build gradle compile flags.

I’m sorry for any inconvenience.
