### ISSUE TITLE
Cannot create file flutter web

### ISSUE THREAD

**Issue by RomanSoviak** [miguelpruivo/flutter_file_picker#595]
![image](https://user-images.githubusercontent.com/26696190/105876869-0aac4900-6008-11eb-8072-793a7e805d68.png)
Hi! Thanks for the nice lib!
I cannot create file in web like you wrote in README. 
Could you clarify lib description. 
How can I create the file by using this awesome picker?

**Comment by miguelpruivo** [comment]
Hi @RomanSoviak, `File` objects in web are different. They are just blobs. 

You need to use the `bytes` property instead if you want to load your File or upload to somewhere else. :)

**Comment by RomanSoviak** [comment]
@miguelpruivo thanks, how can I do that?

**Comment by RomanSoviak** [comment]
@miguelpruivo thanks, how can I do that?

**Comment by RomanSoviak** [comment]
@miguelpruivo, could you clarify your documentation for flutter web?

**Comment by miguelpruivo** [comment]
@RomanSoviak sorry I’ve been quite busy lately. If you search on the repo issues you’ll find some examples I believe. 

Since you have the bytes for the picked token you should be able to create any kind of object with it. Also, uploading to BE for example, typically requires you to send the bytes, so this means that they are also ready to send.

**Comment by RomanSoviak** [comment]
I want to send bytes by using `FileReader` from `dart.html`. How can I do that?
I used `reader.readAsDataUrl(file)` by using previous version of lib. How can I make the same thing by using `bytes`?

**Comment by RomanSoviak** [comment]
So, after long ignoring, I cannot recommend this lib for Flutter-web, cause the old version does not working on Safari and the new one does not create file.
If you want to create the file and upload it, use the following code:

`InputElement uploadInput = FileUploadInputElement();
    uploadInput.accept = 'image/*';
    uploadInput.click();
    document.body.append(uploadInput);
    uploadInput.addEventListener('change', (e) async {
      final files = uploadInput.files;
      final file = files[0];
        final reader = new FileReader();
        reader.onLoad.listen((e) async {
          var fileExtension = "." + file.name.split(".").last;
          var bytes = reader.result.toString();
          var decoded = base64Decode(bytes.split(',').last);
          
       ....
        });
        reader.readAsDataUrl(file);`
