### ISSUE TITLE
A value of type 'FilePickerResult' can't be assigned to a variable of type 'File'.

### ISSUE THREAD

**Issue by ZAE3600** [miguelpruivo/flutter_file_picker#596]
Here is my code.

class _sendHomePageState extends State<sendHomePage> {
  String fileType = '';
  File file;
  String fileName = '';
  String operationText = '';
  bool isUploaded = true;
  String result = '';
  String StorageReference;

  Future filePicker(BuildContext context) async {
    try {
      if (fileType == 'image') {
        file = await FilePicker.platform.pickFiles(type: FileType.image);
        setState(() {
          fileName = p.basename(file.path);
        });
        print(fileName);
        _uploadFile(file, fileName);
      }
      if (fileType == 'audio') {
        file = await FilePicker.platform.pickFiles(type: FileType.audio);
        fileName = p.basename(file.path);
        setState(() {
          fileName = p.basename(file.path);
        });
        print(fileName);
        _uploadFile(file, fileName);
      }
      if (fileType == 'video') {
        file = await FilePicker.platform.pickFiles(type: FileType.video);
        fileName = p.basename(file.path);
        setState(() {
          fileName = p.basename(file.path);
        });
        print(fileName);
        _uploadFile(file, fileName);
      }
      if (fileType == 'pdf') {
        file = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['pdf']);
        fileName = p.basename(file.path);
        setState(() {
          fileName = p.basename(file.path);
        });
        print(fileName);
        _uploadFile(file, fileName);
      }
      if (fileType == 'others') {
        file = await FilePicker.platform.pickFiles(type: FileType.any);
        fileName = p.basename(file.path);
        setState(() {
          fileName = p.basename(file.path);
        });
        print(fileName);
        _uploadFile(file, fileName);
      }
    } on PlatformException catch (e) {
      showDialog(
          context: context,
          builder: (BuildContext context) {
            return AlertDialog(
              title: Text('Sorry...'),
              content: Text('Unsupported exception: $e'),
              actions: <Widget>[
                FlatButton(
                  child: Text('OK'),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                )
              ],
            );
          });
    }
  }

Can i get some help please.

**Comment by miguelpruivo** [comment]
Hi @ZAE3600, `FilePicker.platform.pickFiles()` returns a `FilePickerResult` which on its turn has the picked files. You have multiple examples on how to pick files properly in the README file and Wiki.
```
FilePickerResult result = await FilePicker.platform.pickFiles();

if(result != null) {
   File file = File(result.files.single.path);
} else {
   // User canceled the picker
}
```

**Comment by ZAE3600** [comment]
Thanks but after this i got another error. that states:

E/flutter (11449): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'path' was called on null.
E/flutter (11449): Receiver: null
E/flutter (11449): Tried calling: path

**Comment by miguelpruivo** [comment]
That’s probably because you have either cancelled or not selected any file.

**Comment by ZAE3600** [comment]
I did select the file. This error only occurs after I select the file only.

here is the edited code:

if (fileType == 'image') {
        FilePickerResult result =
            await FilePicker.platform.pickFiles(type: FileType.image);
        setState(() {
          fileName = p.basename(file.path);
        });
        print(fileName);
        _uploadFile(file, fileName);
      }
