### ISSUE TITLE
[Question] How to create file in local / iCould ?

### ISSUE THREAD

**Issue by FlashTang** [miguelpruivo/flutter_file_picker#598]
Hi ,I just run flutter_file_picker example successfully on iOS
But how can I create file in the local or iCloud ? 
just like we use UIDocumentBrowserViewController in iOS native, there will be a file icon(with "+" symbol ) which used to create new document

Thanks

**Comment by miguelpruivo** [comment]
Hi @FlashTang. This plugin serves only to allow you to pick files and use it on your app. Not to actually save files on external sources.

I’m sorry for any inconvenience.
