### ISSUE TITLE
Can't support in ios when video pick from gallery 

### ISSUE THREAD

**Issue by abhuzz** [miguelpruivo/flutter_file_picker#599]
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary
 file could not be created, null, null)
flutter: Unsupported operationPlatformException(file_picker_error, Temporary file could not be created, null, null)

![IMG_56A1B1F096DB-1](https://user-images.githubusercontent.com/6681394/106115041-5250e300-6176-11eb-8440-aa1e6ebd668c.jpeg)

**Comment by miguelpruivo** [comment]
Hi @abhuzz I'm not sure what's happening here, can you please elaborate?

**Comment by abhuzz** [comment]
When I select a video from the iOS gallery and click on choose that time this app crashed 
1. I attached a screenshot of the crash event.
2. the Second screenshot is about the crash detail I logged from the code debug.

![IMG_6022AD9DF9CB-1](https://user-images.githubusercontent.com/6681394/106147576-074ac600-619e-11eb-8410-3e8e448db3e9.jpeg)

![Screenshot 2021-01-28 at 7 07 05 PM](https://user-images.githubusercontent.com/6681394/106147622-1598e200-619e-11eb-855f-706f83dbc083.png)

Thanks

**Comment by miguelpruivo** [comment]
Hum, looks like somehow it's failing to cache the temporary file. Do you have permissions allowed on your app settings? What iOS version does this happen?

**Comment by abhuzz** [comment]
Yes, I allowed permissions to read and write (Photos), I test in a device having iOS version 12.5.1.

**Comment by abhuzz** [comment]
@miguelpruivo thanks for your support.
I search everywhere there is not Flutter library error but it's an **iPhone glitch** so I solve this error with **Restore iPhone**.  
This is the link to how to restore iPhone: https://youtu.be/7s8-zLG9ySQ

**Comment by miguelpruivo** [comment]
Thank you for sharing your solution @abhuzz! 👍
