### ISSUE TITLE
Multi-select for iOS not working

### ISSUE THREAD

**Issue by mohsinsurani** [miguelpruivo/flutter_file_picker#603]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Multi-select of files NOT working in iOS**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**iOS**
- [] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**14.3**
What version did it happen?

**iPad device?**
```
Please, post the snippet here
```

**Run your project in iOS**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**1.22.6**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
How are you picking?

**Comment by mohsinsurani** [comment]
It navigates to Files screen, I keep holding the icons but its not allowing to select multiple.

**Comment by mohsinsurani** [comment]
I found it and its able to select all. Closing the issue!

**Comment by aqueebqazi** [comment]
Hi i am having the issue on the latest version 5.3.3 on ios unable to multi select image here is a sample code
 result = await FilePicker.platform.pickFiles(
          allowMultiple: true,
          type: FileType.custom,
          allowedExtensions: [
            'jpg',
            'png',
            'pdf',
            'jpeg',
            'mp4',
            'mp3',
            'aac',
            'heic',
            'hevc'
          ]);
