### ISSUE TITLE
FilePickerResult does not return anything when closing picker-dialog on Web

### ISSUE THREAD

**Issue by ymerdrengene** [miguelpruivo/flutter_file_picker#605]
When user cancels the picker-dialog on Web, it seems pickFiles does not return anything (not even null, which is expected)
`final FilePickerResult result = await FilePicker.platform.pickFiles();
`

![image](https://user-images.githubusercontent.com/5994028/107010797-1da4e300-6797-11eb-93c9-988f2542d40f.png)

**Comment by miguelpruivo** [comment]
Hi @ymerdrengene, this is not the first time this is asked. There is no way to know when the user cancels the pickers on the Web. This is a browser limitation. [Check here](https://stackoverflow.com/a/4628563/6919963).

However, there are some workarounds, so it seems.
