### ISSUE TITLE
Does file picker support flutter for web?

### ISSUE THREAD

**Issue by buffalus** [miguelpruivo/flutter_file_picker#607]
I use the folloiwng code to upload images successfully in Mobile. But in web, when click the choosing file button, it suddenly close the browser. On terminal, it shows the message of "application finished".

Can anyone advise if file picker support flutter for web?
If yes, please provide an example. Thanks !

`PlatformFile file;`

`  void selectFile() async {`
    ` progress = "";`
`    FilePickerResult result = await FilePicker.platform.pickFiles();`
 `   if (result != null) {`
 `     setState(() {`
 `      file = result.files.single;`
`      });`
`    }`
`  }`

Thanks !

**Comment by miguelpruivo** [comment]
Hi @buffalus, try with a different file to see if it works.

**Comment by buffalus** [comment]
> Hi @buffalus, try with a different file to see if it works.

Thank you for your comment.

Not sure your meaning. 
My problem is when click the choosing file button which invokes FilePicker.platform.pickFiles(), the chrome browser suddenly close.  It does not open the file browser so as to choose a file.

I've tried the github demo sample and encounter the same problem.

So I ask if file picker support flutter for web? or anything I am missing.

Thanks

**Comment by Jonan2813** [comment]
What version of Flutter are you using?. I'm using Flutter in the Dev Branch, Flutter 1.26.0-18.0.pre.99 and I don't have any issue. Try upgrading flutter to the Dev Branch to see if you solve the problem.

**Comment by rahulkushwaha-techconfer** [comment]
@Jonan2813  ,I am getting the same issues . Actually I am trying to print 
      print(file.name);
      print(file.size);
      print(file.extension);
      print(file.path);

I am getting this as result 👍🏿 
[           sample.pdf
3028
pdf
null](url)

**Comment by buffalus** [comment]
> What version of Flutter are you using?. I'm using Flutter in the Dev Branch, Flutter 1.26.0-18.0.pre.99 and I don't have any issue. Try upgrading flutter to the Dev Branch to see if you solve the problem.

I used Flutter beta and Ubuntu 2010. After your advice, I upgrade to dev branch and now I can successfully open file browser and upload images on web.

Thanks a lot for your comments.

**Comment by miguelpruivo** [comment]
This plugin is only tested against `stable` channels, so there's no warranty that it will be fully compatible with other channels, despite being already migrated to support null-safety which is only available on other channels.
