### ISSUE TITLE
Build error with newand existing project: SDK location not found / error in manifest

### ISSUE THREAD

**Issue by herrmayr** [miguelpruivo/flutter_file_picker#608]
I cannot build any projects with file_picker 2.1.6 anymore and I have no idea why:

**Two ways to reproduce**
I first noticed the issue with an existing and prior-working project, where the following error occurs when building/running for Android:

>Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/christianmayr/development/projects/mediaconverterflex/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
2
>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
>BUILD FAILED in 24s

I created a completely new flutter project and only added the file_picker plugin. When running the new project, the following error occurs:

> AILURE: Build failed with an exception.
> * What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>* Get more help at https://help.gradle.org
>BUILD FAILED in 0s
>The plugin file_picker could not be built due to the issue above.

**Flutter doctor output**

> [✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale de-DE)
>     • Flutter version 1.22.6 at /Users/christianmayr/development/flutter
>     • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
>     • Engine revision 2f0af37152
>     • Dart version 2.10.5
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/christianmayr/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 44.0.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.53.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.19.0
> 
> [✓] Connected device (1 available)
>     • Redmi Note 7 (mobile) • 112cd80b • android-arm64 • Android 10 (API 29)
> 
> • No issues found!

**Comment by miguelpruivo** [comment]
Hi, this has a solution described [in the wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-2).
