### ISSUE TITLE
getDirectoryPath option to pick the immediate folder

### ISSUE THREAD

**Issue by BernardinD** [miguelpruivo/flutter_file_picker#609]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

I'm not able to pick the immediate folder that opens with the function call. Is this intentional? I am attempting to call this function, and followed immediately `pickFiles` so that I am get the name of the directory the files come from

**Platform**
- [x] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
What version did it happen?
Windows 10

**How are you picking?**
```
await FilePicker.platform.getDirectoryPath();
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
```
Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.23.0-7.0.pre at C:\src\flutter
    • Framework revision db6e2d8aa5 (5 months ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\deziu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.1316]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 1 category.

```
**Additional context**

**Comment by miguelpruivo** [comment]
Hi! I believe that when you are picking directories on Android, it shows an option like “use this directory” or something like that. But it might depend on the sdk version.

Can you try on a different device?

**Comment by BernardinD** [comment]
I tried changing the targetSDK and the issue still exists. I also tried a simulator instead of my device and same thing. The issue that I'm having is that this "use this folder" button isn't available immediate after opening the folder selector. I have to leave the immediate directory and then go back in order to select it

**Comment by miguelpruivo** [comment]
@BernardinD that's just an issue with the native picker, I'd say. As long as you open the picker, you are out of the Flutter context, hence, the plugin can't play a role there.

I believe there isn't much else to do here. But feel free to issue a PR if you find any way around.

I'm sorry for any inconvenience.
