### ISSUE TITLE
getDirectoryPath() always return empty path "/"

### ISSUE THREAD

**Issue by kuchienkz** [miguelpruivo/flutter_file_picker#613]
**getDirectoryPath() always return empty path "/"**
Permissions are given, I can navigate through the directories, but I still can't pick any folder path on Android 11, it always return empty path "/". I know there are some protected directories such as Downloads folder, I let the user know that they can't pick this directories so this is not the problem. My app is something like wallpaper manager, it needs to load images from some specified folders to do it's job. Those folders could be located anywhere (except protected ones), I don't want to restrict my user for the locations. Picking files is working thought, so I don't think its related to Permissions, or is it? Am I missing something?

**The snippet**
```
await FilePicker.platform.clearTemporaryFiles();
String dirPath = await FilePicker.platform.getDirectoryPath(); // returns "/"
```

**Flutter Version details**
```
[√] Flutter (Channel beta, 1.26.0-17.4.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-17.4.pre at C:\Flutter\flutter
    • Framework revision 48c9d3e0e1 (17 hours ago), 2021-02-10 11:46:09 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Kuchienkz\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\Kuchienkz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi Note 8 Pro (mobile) • 192.168.1.69:5555 • android-arm64 • Android 11 (API 30)

• No issues found!
```

**Comment by miguelpruivo** [comment]
Hi @kuchienkz this is a known limitation that has been researched multiple times when implementing this feature. For some reason, some Android versions handle some folders as protected and hence the `/` directory.

If you find the reason why, feel free to issue a PR for it, but for now I believe there isn't much else I can do, I'm sorry.
