### ISSUE TITLE
File path is always getting null from flutterweb.

### ISSUE THREAD

**Issue by rahulkushwaha-techconfer** [miguelpruivo/flutter_file_picker#614]
Hi sir You are doing great. I am implementing this library in my project but I am getting null as file path from web.
So , I request you to please add and resolve this asap. I am using latest version of Android Studio and latest version of Flutter .

**Comment by miguelpruivo** [comment]
Hi,

You can’t use paths on web. That’s in the documentation and it’s due to how browsers work. You should use the bytes property instead.

Regards,
Miguel
