### ISSUE TITLE
Add size limit?

### ISSUE THREAD

**Issue by Tamerlanchiques** [miguelpruivo/flutter_file_picker#615]
Whats about add max file size limit? Is it possible to integrate file size restrictions inside native files picker?

**Comment by miguelpruivo** [comment]
@Tamerlanchiques hi, I believe this was already been asked before and the answer is no. At least that works transversely for all the platforms. This should be handled on your end after picking by discarding the files bigger/smaller according to your restrictions.

I’m sorry for any inconvenience.
