### ISSUE TITLE
[Request] Additional field for PlatformFile

### ISSUE THREAD

**Issue by jasonlaw** [miguelpruivo/flutter_file_picker#617]
Could you please add an additional placeholder field for PlatformFile?
I need a field to store the file ID (from database) value.
The field could be Object/Dynamic type, or even a Map<String, dynamic> so that multiple values can be stored.

**Comment by miguelpruivo** [comment]
@jasonlaw I don’t get what you’re asking for. You are probably looking for a wrapper object to the Platform file so you can add whatever properties you want.

**Comment by jasonlaw** [comment]
Hi @miguelpruivo ,

Yes, a wrapper object could help, but I thought it would be more convenient to have it directly in PlatformFile object.
Here is my use case:
1. I keep uploaded files in database, with a GUID primary key.
2. The user can retrieve the files, work on something and upload back the file.
3. In this case, I need to keep track the file primary key.

Understand this may not be the ideal solution, any suggestion/advice is mostly welcome.

Thank you very much.
