### ISSUE TITLE
Require update

### ISSUE THREAD

**Issue by leszekkrol** [miguelpruivo/flutter_file_picker#620]
Because no versions of file_picker match >2.1.6 <3.0.0 and file_picker 2.1.6 depends on plugin_platform_interface ^1.0.1, file_picker ^2.1.6 requires plugin_platform_interface ^1.0.1.
And because geolocator >=7.0.0 depends on geolocator_platform_interface ^2.0.0 which depends on plugin_platform_interface ^2.0.0, file_picker ^2.1.6 is incompatible with geolocator >=7.0.0.

**Comment by miguelpruivo** [comment]
Hi @leszekkrol, you need to respect versioning across multiple packages by finding compatible ones. This is not actually an issue, it’s just how version resolution works.
