### ISSUE TITLE
plugin_platform_interface blocking upgrade of other things because of limited to less than 2.0

### ISSUE THREAD

**Issue by JohnGalt1717** [miguelpruivo/flutter_file_picker#621]
**Describe the bug**
In the latest null safety release the plugin_platform_interface is limited to v1.x. This causes problems with other null safe implementations because they almost all use V2.  Please update to either allow >= 1.0.1 & < 3.0.0 

**Flutter Version details**
2.12.0-0

**Additional context**
This is required for successful use with null safety

**Comment by miguelpruivo** [comment]
Ok thank you for the input!

**Comment by kostaa** [comment]
Hi, could you let me know what your plans are? This is a blocker for me.

**Comment by miguelpruivo** [comment]
@kostaa I’ll need to update it. Just hadn’t the time yet. Feel free to issue a PR if you want.

**Comment by miguelpruivo** [comment]
@kostaa published with 3.0.0-nullsafety.3. Let me know if it's working for you.

Thank you.

**Comment by kostaa** [comment]
@miguelpruivo - thanks for that. I have not managed to test it yet as I have a couple of thousand syntax errors to deal with :-).
One thing I have noticed though is that the flutter version is still limited to flutter: ">=1.10.0 <2.0.0".   Could you change that please?
