### ISSUE TITLE
File picker plugin doesn't work on IOS Simulator (M1 Apple)

### ISSUE THREAD

**Issue by xWorldx** [miguelpruivo/flutter_file_picker#622]
I am trying to use File Picker plugin to pick a single file(image) from my IOS simulator but i receive an error but 
I also tried the plugin on a real device it works.

**Platform**
- [] iOS

**IOS 14.4**

Debug Console:

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      ProductBloc.pickImageNew

pickImageNew() async {
    FilePickerResult file;
    file = await FilePicker.platform.pickFiles(
      type: FileType.image,
      allowCompression: false,
      allowMultiple: false,
    );
    print(file.files.first.path);
  }

> [✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2.1 20D74 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-17.6.pre at /Users/xbee/documents/dev/flutter
    • Framework revision a29104a69b (7 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

>[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xbee/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/xbee/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

>[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

>[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

>[✓] Connected device (2 available)
    • Eman’s iPhone. (mobile)    • a0c70e1181dde87352135cd8f88f4ac9a3b36f5e • ios • iOS 14.4
    • iPhone 12 Pro Max (mobile) • 6210C9A8-AA76-4CA0-8E1E-5A8E4E641AE6     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

>• No issues found!

![ezgif-7-9e0c8b79abaf](https://user-images.githubusercontent.com/70700918/108906556-50692b00-7621-11eb-879c-95fd7f733e8d.gif)

**Comment by miguelpruivo** [comment]
I don’t have a M1 Mac and since it works on devices I’ll assume that it could be just a temporary issue that could be easily resolved with an update. 

Feel free to reopen this if it happens on a real device.

**Comment by abdullah432** [comment]
Same issue on M1

**Comment by xWorldx** [comment]
> I don’t have a M1 Mac and since it works on devices I’ll assume that it could be just a temporary issue that could be easily resolved with an update.
> 
> Feel free to reopen this if it happens on a real device.

can we fix that? i mean i can share my screen with you, if you are free !

**Comment by miguelpruivo** [comment]
I’m not really concerned if this is working on real devices (which is what matters). However, try adding different pictures to the simulator (not the ones that come with it) and see if it makes any difference.

Does that also happens with the example app?

**Comment by rumred** [comment]
I have the same issue with M1 chip, but it's working on a real device which is good.
