### ISSUE TITLE
flutter_file_picker returning null in path of picked file in flutter web

### ISSUE THREAD

**Issue by SalishKumar** [miguelpruivo/flutter_file_picker#623]

**Comment by miguelpruivo** [comment]
@SalishKumar it’s working as intended. Please, read the Wiki before creating new issues. On Flutter Web you must use `bytes` property since browsers don’t allow paths. Thank you.

**Comment by Marmik123** [comment]
How to use bytes to upload file on Parse Server

**Comment by SalishKumar** [comment]
> How to use bytes to upload file on Parse Server

there is a function 'multipart.frombyte' i used that and it is working quick well

**Comment by miguelpruivo** [comment]
@JohnGalt1717 feel free to PR a solution with a working `path` for a blob as  a complement from to `bytes`, it would be great and I'd glad to review it.

Let me know your thoughts.

**Comment by JohnGalt1717** [comment]
So I looked into this more deeply. You can return this as Url.createObjectUrl(file) around line 77. Unfortunately, Dart hasn't gotten around to allowing you to create a URL from the type of url thus you can't create a file from it. (you should be able to)

The line that will get you a path is: final path = Url.createObjectUrl(file);  Not 100% sure that this should be passed as it might cause problems because it can't be used by dart:io.

Might be worth opening a bug with dart/lang to expand this, because there's no reason that a dart:io file can't be created from a web blob given that a web blob exposes a stream if you want it to.

**Comment by Marmik123** [comment]
Thanks, but Url.createObjectUrl is not working; it is giving me TypeError:Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.

**Comment by Marmik123** [comment]
I am asking for uploading in parse server through flutter and i am using ParseWebFile to upload the file. It is uploading successfully but when i try to open the file from parse dashboard it shows file not found .

**Comment by Marmik123** [comment]
How to get the url from the FilePickerResult as i will need URL to pass in the ParseWebFile function.

**Comment by JohnGalt1717** [comment]
In file_picker_web.dart of this project find the files.foreEach(File file) line.

replace that entire foreach with this:

```
      files.forEach((File file) {
        final path = Url.createObjectUrl(file);
        if (withReadStream!) {
          addPickedFile(file, null, path, _openFileReadStream(file));
          return;
        }

        if (!withData!) {
          addPickedFile(file, null, path, null);
          return;
        }

        final FileReader reader = FileReader();
        reader.onLoadEnd.listen((e) {
          addPickedFile(file, reader.result as Uint8List?, path, null);
        });
        reader.readAsArrayBuffer(file);
      });
```

This will cause the path to be set to the Url of the webfile.

This can be used in a web context but Dart:io still doesn't understand it. When I have time I'll file a bug with them to convince them to unify this stuff.

**Comment by Marmik123** [comment]
After changing the forEach function in file_picker_web.dart file i am getting error it is dependent on filepicker latest version 3.0.1 so i have updated my pubsec.yaml file but parse_server_sdk_flutter depends on path_provider_package 1.6.27 while file_picker 3.0.1 depends on path_provider 2.0.0 so version solving error is coming. Please help what to do now?

**Comment by JohnGalt1717** [comment]
Don't know. Just pull master and update the foreach and it works. Again you can't do much with the URL it produces outside of pure web code.

**Comment by Marmik123** [comment]
I Have made changes and i am getting the blob url and the image file is uploaded on server but on clicking the url to see the uploaded image file it shows file not found.
![SharedScreenshot](https://user-images.githubusercontent.com/73093114/114509414-172d5e80-9c53-11eb-9e97-dc2bb44eb6ba.jpg)

**Comment by Marmik123** [comment]
This is the URL i am getting.
![image](https://user-images.githubusercontent.com/73093114/114509524-388e4a80-9c53-11eb-8dea-2fd6cdb274a6.png)

**Comment by JohnGalt1717** [comment]
@Marmik123 As I noted, the URL is only useful within the context of your javascript on the same page and only within Web blobs. It will not work with anything else in flutter (yet) nor is it something that you can use as a URL on an Anchor as an example. It has only one purpose. Please read up on the wc3 on it.
