### ISSUE TITLE
Cannot get the response when the user click "Cancel" or "Close"

### ISSUE THREAD

**Issue by eranganovade** [miguelpruivo/flutter_file_picker#624]
Method `pickFiles` future is not getting resolved in flutter web if the user clicks "Cancel" without selecting any file. 

**Platform**
- [] Android
- [] iOS
- [x] Web
- [] Desktop (Go)

**Platform OS version**

MacOS
- System Version:	macOS 11.2.1 (20D74)
- Kernel Version:	Darwin 20.3.0

**How are you picking?**
```dart
final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['pdf'],
);
print('this code line is never executed');
```

**Details to reproduce the issue**
- Open up the file picker on the web
- Click "Cancel" without selecting any file

**Error Log**
N/A

**Screenshots and/or video**
N/A

**Flutter Version details**
```shell
->> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

• No issues found!
```

**Additional context**
N/A

**Comment by miguelpruivo** [comment]
Hi. I believe this is documented as well in the wiki. If not, it was already mentioned here in the issues somewhere. Basically there’s no web events when the user cancels the native picker. Looks like a browser limitation unfortunately, but let me know if you find a way.

Sorry for any inconvenience.

**Comment by eranganovade** [comment]
@miguelpruivo No problem. Thank you!
