### ISSUE TITLE
Upgrade ASAP to flutter 2.0.0

### ISSUE THREAD

**Issue by pablo-threadable** [miguelpruivo/flutter_file_picker#625]
Flutter 2.0.0 request flutter_plugin_android_lifecycle ^1.0.6 and it's not possible to upgrade to use flutter 2.0.0 and file picker as file picker is still not prepared for Flutter 2.

**Comment by pablo-threadable** [comment]
BTW: really thanks for this component. :-D

**Comment by gabdsg** [comment]
plugin_platform_interface too

**Comment by miguelpruivo** [comment]
Dup of #621. I'll update it today.

**Comment by phackwer** [comment]
VALEU!!!! :-) Need help? Precisa ajuda?  Necesitas ayuda? :-)

**Comment by miguelpruivo** [comment]
@phackwer no problem, it's already done. But thank you for the availability. 😃 

Published with 3.0.0-nullsafety.3. Let me know if it's working for you.

Thank you.

**Comment by zelliot** [comment]
Not working unfortunately.

It's just a small change in Line 22 of `file_picker_result.dart`:
`  List<String?> get paths => files`

**Comment by viplifes** [comment]
> ../../../../../.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.0-nullsafety.3/lib/src/file_picker_result.dart:27:8: Error: A value of type 'List<String?>' can't be returned from a function with return type 'List<String>' because 'String?' is nullable and 'String' isn't.
> 'List' is from 'dart:core'.
      .toList();

**Comment by nialljvs** [comment]
Following

**Comment by pablo-threadable** [comment]
Still breaks for me as the android lyfecycle is too old too. Check my output.

Because image_picker >=0.6.3 <0.7.0-nullsafety depends on flutter_plugin_android_lifecycle ^1.0.2 and local_auth >=1.1.0 depends on flutter_plugin_android_lifecycle ^2.0.0, image_picker >=0.6.3 <0.7.0-nullsafety is incompatible with local_auth >=1.1.0.
So, because giy depends on both local_auth 1.1.0 and image_picker ^0.6.7+21, version solving failed.

**Comment by pablo-threadable** [comment]
Sorry, I misread image_picker as file_picker. Just woke up and still "booting", hahahaha.

**Comment by zelliot** [comment]
@pablo-threadable just upgrade to image_picker: ^0.7.2

**Comment by pablo-threadable** [comment]
Yeah I realised my error just after a cup of coffee. :-D
