### ISSUE TITLE
upgrade lib to flutter_plugin_android_lifecycle ^2.0.0

### ISSUE THREAD

**Issue by denkoul** [miguelpruivo/flutter_file_picker#627]
Tried out to "pub get" but got red text.
`Because image_picker >=0.7.0 depends on flutter_plugin_android_lifecycle ^2.0.0 and file_picker 2.1.7 depends on flutter_plugin_android_lifecycle ^1.0.6, image_picker >=0.7.0 is incompatible with file_picker 2.1.7.`

Imo lib flutter_plugin_android_lifecycle needs to be set to flutter_plugin_android_lifecycle ^2.0.0, because it is creating conflicts with other libs that are using the same dep. 

Thanks

**Comment by miguelpruivo** [comment]
@denkoul image_picker 0.7.0 or above uses nullsafety, hence, you need to use a nullsafety compatible version for file_picker as well, which in this case is the `3.0.0-nullsafey.3`.

For some reason the Flutter team didn't published the null safety version of image_picker as a pre-release when they should, as per their guidelines.
