### ISSUE TITLE
[iOS] Crash when selecting an image (^3.0.0-nullsafety.4)

### ISSUE THREAD

**Issue by Albert-Jan** [miguelpruivo/flutter_file_picker#629]
**Describe the bug**
When trying to select an image on iOS the app crashes when you select an image. Something seems to be wrong with the 'didFinishPicking'.

I've also made sure to have added the required key in info.plist

	<key>NSPhotoLibraryUsageDescription</key>
	<string>Upload profile pictures for users</string>

Current version: ^3.0.0-nullsafety.4

**Platform**
- [] Android
- [x] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
iOS 14.4 - Emulator

**How are you picking?**
``
Please, post the snippet here
`await FilePicker.platform
      .pickFiles(type: FileType.image, allowMultiple: false)
      .then((filePickerResult) => uploadImage(organisationId, userId, filePickerResult));`

**Details to reproduce the issue**
Select the button to upload an image, the iOS image picker opens, select an image ==> CRASH

**Error Log**
`***** Picker:<PHPickerViewController: 0x7fe8a3178f70> didFinishPicking:(
    "<PHPickerResult: 0x600003991200>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 381]
2021-03-04 15:51:56.197029+0100 Runner[90170:2352012] -[NSNull data]: unrecognized selector sent to instance 0x7fff8002ef10
2021-03-04 15:51:56.197736+0100 Runner[90170:2352012] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull data]: unrecognized selector sent to instance 0x7fff8002ef10'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   Runner                              0x000000010d3a05eb __100-[FLTFirebaseStoragePlugin startFIRStorageObservableTaskForArguments:andFLTFirebaseStorageTaskType:]_block_invoke + 491
	6   libdispatch.dylib                   0x00000001146d97ec _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x00000001146da9c8 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00000001146e1296 _dispatch_lane_serial_drain + 796
	9   libdispatch.dylib                   0x00000001146e1f67 _dispatch_lane_invoke + 439
	10  libdispatch.dylib                   0x00000001146edde2 _dispatch_workloop_worker_thread + 882
	11  libsystem_pthread.dylib             0x00007fff61167499 _pthread_wqthread + 314
	12  libsystem_pthread.dylib             0x00007fff61166467 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull data]: unrecognized selector sent to instance 0x7fff8002ef10'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 8 (FDCEAC84-8715-4403-867A-D30E90EBBE87) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 8`

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-NL)

**Additional context**

**Comment by miguelpruivo** [comment]
@Albert-Jan this is really weird. Could you please try on a real device? What is the image you are trying to pick from the simulator?

**Comment by Albert-Jan** [comment]
Tried on a real device but still getting an error. It seems like there is a bit more information to it now. iOS 14.4 - iPhone SE

```
***** Picker:<PHPickerViewController: 0x154bef040> didFinishPicking:(
    "<PHPickerResult: 0x280040780>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 381]
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
-[NSNull data]: unrecognized selector sent to instance 0x1f3ebca00
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull data]: unrecognized selector sent to instance 0x1f3ebca00'
*** First throw call stack:
(0x19573086c 0x1aa74bc50 0x19563795c 0x195733438 0x195735740 0x10060bbb0 0x19532324c 0x195324db0 0x19532c10c 0x19532cc5c 0x195336d78 0x1e125d814 0x1e126476c)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #29, queue = 'io.flutter.plugins.firebase.storage', stop reason = signal SIGABRT
    frame #0: 0x00000001c3702414 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1c3702414 <+8>:  b.lo   0x1c3702434               ; <+40>
    0x1c3702418 <+12>: pacibsp 
    0x1c370241c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1c3702420 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by Albert-Jan** [comment]
Figured it out, the issue was a result of providing null bytes on `firebase_storage` using `.putData()`.

However the underlying issue/misconception I faced was that it resulted in empty bytes I tried to upload, as `filePickerResult.files.first.bytes` is empty on **mobile** and `filePickerResult.files.first.path` is empty on **web**. So you'll have to differtiate with a platform specific upload logic. Eg:

```
if (UniversalPlatform.isWeb) {
    firebase_storage.FirebaseStorage.instance
        .ref('$filename.png')
        .putData(filePickerResult.files.first.bytes, firebase_storage.SettableMetadata(contentType: 'image/png'))
        .then((taskSnapshot) => print(taskSnapshot.ref.getDownloadURL().then((value) => print(value))));
  } else {
    firebase_storage.FirebaseStorage.instance
        .ref('$filename.png')
        .putFile(File(filePickerResult.files.first.path), firebase_storage.SettableMetadata(contentType: 'image/png'))
        .then((taskSnapshot) => print(taskSnapshot.ref.getDownloadURL().then((value) => print(value))));
  }
```

**Comment by miguelpruivo** [comment]
Glad you've managed to fix it. 🎉 Feel free to reopen if you still experience an issue.
