### ISSUE TITLE
Flutter 2.0 integration

### ISSUE THREAD

**Issue by Henzelix** [miguelpruivo/flutter_file_picker#631]
When will `file_picker` be compatible with Flutter 2.0? My app heavily depends on that plugin and I wanted to upgrade my web app and mobile app to Flutter 2.0.

**Comment by marchellodev** [comment]
I believe the latest pre-release version already supports null-safety

**Comment by miguelpruivo** [comment]
Hi. You already have the 3.0.0 version published yesterday. Just update on your pubspec.

Thank you.
