### ISSUE TITLE
compatibility with flutter_graphql:^4.0.1

### ISSUE THREAD

**Issue by OscarHenry** [miguelpruivo/flutter_file_picker#632]
**Describe the bug**
I'm trying to make an application with flutter + graphql, I need to get a file and I get this error: 

**Platform**
- [] Android
- [] iOS

**Error Log**
Because graphql_flutter >=4.0.0-alpha.0 depends on path_provider ^1.6.10 which depends on path_provider_platform_interface ^1.0.1, graphql_flutter >=4.0.0-alpha.0 requires path_provider_platform_interface ^1.0.1.
And because path_provider_platform_interface <2.0.0-nullsafety depends on plugin_platform_interface ^1.0.1 and file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0, graphql_flutter >=4.0.0-alpha.0 is incompatible with file_picker >=3.0.0-nullsafety.3.
So, because guadalupe depends on both graphql_flutter ^4.0.1 and file_picker ^3.0.0, version solving failed.
pub get failed (1; So, because guadalupe depends on both graphql_flutter ^4.0.1 and file_picker ^3.0.0, version solving failed.)

**Flutter Version details**
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [VersiÃ³n 10.0.19042.844], locale es-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.1)
[√] Connected device (4 available)

![image](https://user-images.githubusercontent.com/45606401/110225494-ee77b380-7eb3-11eb-9cbe-7d8d341bd162.png)

**Comment by miguelpruivo** [comment]
Hi @OscarHenry, that’s just a normal error for multiple conflicts with version handling.

You need to dig down and try to find compatible versions for each plugin of your project. I believe this has nothing to do with file_picker.
