### ISSUE TITLE
Not compatible with other packages

### ISSUE THREAD

**Issue by kamleshwebtech** [miguelpruivo/flutter_file_picker#633]
When I installed this package, am getting below error:

[testappflutter] flutter pub get
Running "flutter pub get" in testappflutter...
Because file_picker >=3.0.0 depends on flutter_plugin_android_lifecycle ^2.0.0 and image_picker 0.6.7+22 depends on flutter_plugin_android_lifecycle ^1.0.2, file_picker >=3.0.0 is incompatible with image_picker 0.6.7+22.

Kindly suggest how can I solve it. Thanks.

**Comment by kamleshwebtech** [comment]
Also getting warning in console:

generated_plugin_registrant.dart
Don't import implementation files from another package.

any suggestion? Please share.

**Comment by miguelpruivo** [comment]
Hi. You need to update your image_picker to 0.7.2 as well. File_picker is updated to latest versions, so it’s normal that you may find conflicts with other plugins that you have and may need to be updated as well.

As for your second question, that’s a generated file, there’s nothing to do about it other that adding a rule to ignore generated files to your static analysis.
