### ISSUE TITLE
file_picker: 3.0.0 : FilePickerPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by deacon78** [miguelpruivo/flutter_file_picker#634]
Hello Miguel

THis morning, I have updated to Flutter 2.0 and file_picker: 3.0.0.

When I compile, I got this warning message : 
`Running Gradle task 'assembleDebug'...
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-3.0.0\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

Thank you

**Comment by miguelpruivo** [comment]
Hi. That warning has been there for a long time and it is required because it uses one deprecated API that is required for it to work properly.

Just ignore it for now. :)
