### ISSUE TITLE
Support for file paths on web

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [miguelpruivo/flutter_file_picker#635]
This plugin is apparently missing support for getting the file paths on web.

This is, however, supported by [`file_picker_cross`](https://pub.dev/packages/file_picker_cross).

---

We would love to use `file_picker`, however, this is not possible as we need the file paths to extract MIME types for example.

**Comment by miguelpruivo** [comment]
@creativecreatorormaybenot this is a great addition since it is a missing part from web implementation. 

If you are open to create a PR to add support to it (picking the same logic already implemented for all other platforms) it'll be great. Other than that, I may add it but I can't really tell you when.

**Comment by miguelpruivo** [comment]
I've checked the implementation and it should be quite easy to add it anyway. I'll add it later today if I have time. 👍

**Comment by creativecreatorormaybenot** [comment]
@miguelpruivo Thanks a lot 🙏 Really looking forward to that 🚀

**Comment by miguelpruivo** [comment]
@creativecreatorormaybenot sorry I misunderstood your OP. Looks like you want the paths, but browsers only delegate fake paths that can't be instanced anyway, hence the reason I removed it completely to not confuse developers.

How are you using the paths from `file_picker_cross` can you provide me an example?

Thank you.

**Comment by creativecreatorormaybenot** [comment]
@miguelpruivo As I tried to say above, only for the file name.

This allows both having semantics (because you keep the original file name the uploader chose) and also **more importantly** gives you access to the MIME type.

```dart
  final filePickerResult = await FilePickerCross.importFromStorage();

  final filePath = filePickerResult.path,
      originalName = p.basename(filePath),
      suffix = p.extension(filePath).toLowerCase(),
      data = filePickerResult.toUint8List(),
      type = mime(filePath),
      fileString = randomId + suffix;

  switch (suffix) {
    case '.svg':
      // ...
    case '.jpg':
    case '.png':
      // ...
  }
```

**Comment by miguelpruivo** [comment]
@creativecreatorormaybenot you still have access to mime types with `file_picker`. You don't need the path, neither you need the name. Actually, based on your snippet, you have much more effort with `FilePickerCross` to retrieve the data, than you have with the `file_picker` as it is. :)

You just need to do like in the example:
```
   FilePickerResult result = FilePick.platform.pickFiles();
   PlatformFile file = result.files.first;
   
   print(file.name);
   print(file.bytes);
   print(file.size);
   print(file.extension);
```
