### ISSUE TITLE
IOS App Issue.

### ISSUE THREAD

**Issue by Lalitchaudhary2** [miguelpruivo/flutter_file_picker#636]
Hello sir,

Android works good and the ios app file picker opens but not an image see. 
What is the issue please help me?

**Comment by miguelpruivo** [comment]
@Lalitchaudhary2 make sure you are using the right `FileType`. You probably want to use `FileType.media` or `FileType.image` instead.

Check the [documentation](https://github.com/miguelpruivo/flutter_file_picker/wiki/api).
