### ISSUE TITLE
Better documentation for iOS when writing files

### ISSUE THREAD

**Issue by grundid** [miguelpruivo/flutter_file_picker#637]
I came across an exception when I used the picker to let the user get a directory to write a file on iOS. For example when the user selects the Downloads directory you get the following error:

`flutter: FileSystemException: Cannot open file, path = '/private/var/mobile/Containers/Shared/AppGroup/9C02CA33-F836-4ADE-83C5-884B5B517907/File Provider Storage/Downloads/myfile.csv' (OS Error: Operation not permitted, errno = 1)`

After some research I found out that you need the UISupportsDocumentBrowser property set to YES in the iOS config.
(https://developer.apple.com/documentation/bundleresources/information_property_list/uisupportsdocumentbrowser)
This way iOS creates an app folder for the app and the user can create and pick directories within the folder and the app has the permission to write here.

One could also mention the LSSupportsOpeningDocumentsInPlace property if somebody needs it
(https://developer.apple.com/documentation/bundleresources/information_property_list/lssupportsopeningdocumentsinplace)

**Comment by miguelpruivo** [comment]
@grundid thank you, I didn't know about it actually, that's why it isn't probably documented. 😄 

I'll add it right away.
