### ISSUE TITLE
Unsupported operation. Method not found. The exception thrown was: MissingPluginException

### ISSUE THREAD

**Issue by wellbranding** [miguelpruivo/flutter_file_picker#641]
Just added a plugin to android and immediately got an internal error:

MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
E/flutter ( 6524): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
E/flutter ( 6524): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6524): <asynchronous suspension>
E/flutter ( 6524): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:35)
E/flutter ( 6524): <asynchronous suspension>
E/flutter ( 6524): #2      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:88:33)
E/flutter ( 6524): <asynchronous suspension>
E/flutter ( 6524): #3      _SubmissionWidgetState.pickFiles (package:ess_front/music/ContractCreationPage.dart:24:31)
E/flutter ( 6524): <asynchronous suspension>

I initially used grade 4.1.2, ten switched to recommended 4.0.1, and wrapped properties to 6.1.1, but the issue exists.

**Comment by miguelpruivo** [comment]
Hi, I’m sorry you’re experiencing this, but it’s likely related with your project dependencies. 

Try cleaning, checking the wiki’s troubleshooting or looking for similar issues here in the repo (which are reported sometimes and ending up fixed by the reporters themselves).

I’m sorry for any inconvenience.

**Comment by jonesw5** [comment]
I had the same issue. After reviewing all of the similarly closed issues, I assume the issue tends to appear after one upgrades their flutter in the midst of an already established project. This is what happened with me, I upgraded to Flutter 2.0 the other day and then tried to install this plugin on a project I created a while ago when I was using Flutter 1.#.#
The problem seemed to be resolved by starting a fresh project and copying all code from original project into the new freshly created flutter project. This is not the fix most people want but it works.

Thanks @miguelpruivo for the awesome package!

**Comment by jonnyjohnson1** [comment]
@TomasJohansson What about in swift? I have built some method channels and my thoughts were somehow that my use of them had overridden the method channel the file picker was working from. Is that true, and where could that be corrected in the swift code?
