### ISSUE TITLE
versions conflict with flutter_appauth: ^0.9.2+6

### ISSUE THREAD

**Issue by JuriSalesski** [miguelpruivo/flutter_file_picker#642]
Because flutter_appauth_platform_interface 2.0.0 depends on plugin_platform_interface ^1.0.2 and no versions of flutter_appauth_platform_interface match >2.0.0 <3.0.0, flutter_appauth_platform_interface ^2.0.0 requires plugin_platform_interface ^1.0.2.
And because file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0, file_picker >=3.0.0-nullsafety.3 is incompatible with flutter_appauth_platform_interface ^2.0.0.
And because flutter_appauth 0.9.2+6 depends on flutter_appauth_platform_interface ^2.0.0 and no versions of flutter_appauth match >0.9.2+6 <0.10.0, file_picker >=3.0.0-nullsafety.3 is incompatible with flutter_appauth ^0.9.2+6.
So, because usg_online depends on both flutter_appauth ^0.9.2+6 and file_picker ^3.0.0, version solving failed.
pub get failed (1; So, because usg_online depends on both flutter_appauth ^0.9.2+6 and file_picker ^3.0.0, version solving failed.)

**Comment by miguelpruivo** [comment]
Hi @JuriSalesski. This plugin is updated to support up to Flutter 2.0 so if there’s a conflict with other plugin’s version I suggest you to ask their owners to update theirs as well.

Flutter 2.0 is the latest version hence every plugin will eventually be updated to support it. If you are struggling managing the dependencies, I suggest you to use the file_picker 2.1.7 in the meantime or dependency overrides.

Thank you for your comprehension.
