### ISSUE TITLE
Conflict with Alice ^0.1.12 dependency

### ISSUE THREAD

**Issue by thasafarian** [miguelpruivo/flutter_file_picker#643]
Because alice >=0.1.12 depends on flutter_local_notifications ^4.0.1+1 which depends on flutter_local_notifications_platform_interface ^2.0.0+1, alice >=0.1.12 requires flutter_local_notifications_platform_interface ^2.0.0+1.
And because flutter_local_notifications_platform_interface >=2.0.0-beta.1 <3.0.0-nullsafety.0 depends on plugin_platform_interface ^1.0.2 and file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0, alice >=0.1.12 is incompatible with file_picker >=3.0.0-nullsafety.3.
So, because flutter_arch_component depends on both file_picker ^3.0.0 and alice ^0.1.12, version solving failed.
Running "flutter pub get" in flutter-arch-component...                  
pub get failed (1; So, because flutter_arch_component depends on both file_picker ^3.0.0 and alice ^0.1.12, version solving
failed.)

**Comment by miguelpruivo** [comment]
Dup of #642. See explanation there.

Thank you.
