### ISSUE TITLE
 warning from generated_plugin_registrant

### ISSUE THREAD

**Issue by piratejoe** [miguelpruivo/flutter_file_picker#644]
Clean Flutter 2 SDK and default project install on Mac M1. Doctor green. Added latest Firebase core, auth, cloud, storage, Google sign-in, Rxdart. All good. Then file_picker 3.0.0 caused this warning: 

generated_plugin_registrant.dart giving me a warning: "Don't import implementation files from another package. dart(implementation_imports) [8, 8]. 

Great package! Thank you!

**Comment by miguelpruivo** [comment]
Hi @piratejoe, that’s normal. That’s from a generated file, I can’t do anything about it and you shouldn’t worry about it as well.

You can add a rule to ignore generated files on your static analyse file if you want.

Thank you!
