### ISSUE TITLE
Getting error at installation time

### ISSUE THREAD

**Issue by kamleshwebtech** [miguelpruivo/flutter_file_picker#645]
Hi @miguelpruivo ,

I am trying to include this "file_picker: ^3.0.0" version package in pubspec.yaml file in my project but getting an error in console:

Don't import implementation files from another package.

Kindly check and suggest what is the issue and how can I remove it. Thanks a lot. Look forward to hear you.

**Comment by miguelpruivo** [comment]
Hi, that’s a warning from a generated file. You shouldn’t worry with it and you can add a rule to ignore it to your static analysis file.

Sorry for any inconvenience.
