### ISSUE TITLE
Firbase Core Error when using file_picker in release mode

### ISSUE THREAD

**Issue by razua-com** [miguelpruivo/flutter_file_picker#647]
I've try using version 2.1.7 and 2.1.4. All return same error when app start : 
MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)

No problem with debug version.

**Comment by miguelpruivo** [comment]
@razua-com hi, by looking at your log, the issue is with the firebase plugin, not this one.

You may need to update it or check for similar issues on their repo.

Thank you.
