### ISSUE TITLE
"Don't import implementation files from another package." error in "generated_plugin_registrant.dart" file

### ISSUE THREAD

**Issue by kamleshwebtech** [miguelpruivo/flutter_file_picker#649]
Dear this did not help me /solved my problem. I am using file_picker package and importing it as you suggested:

import 'package:file_picker/file_picker.dart' show FilePicker, FilePickerResult, FileType;

but still getting "Don't import implementation files from another package." error in "generated_plugin_registrant.dart" file.

Kindly suggest what is the issue and how can we fix it. Thanks a lot.

**Comment by kamleshwebtech** [comment]
I have deleted "generated_plugin_registrant.dart" file for now to solve this issue but still do not know how to fix it if it is raised again in future. Please share any suggestion /experience. Thanks.

**Comment by miguelpruivo** [comment]
Hi, this is not an issue. You should ignore this warning because it comes from a generated file or add a rule to ignore it on your static analyses file.

Sorry for any inconvenience.

**Comment by kamleshwebtech** [comment]
@miguelpruivo Thanks for your reply. I have deleted generated_plugin_registrant.dart file then this package works in debug mode but when I compile app and upload it to Google Play Store in live mode then it does not work and no permission is asked. Could you please suggest me what is the issue, while it works in debug mode. Thanks again. Look forward to hear you.

**Comment by kamleshwebtech** [comment]
Any update @miguelpruivo  Kindly see my last message and suggest me to fix this issue. Thanks.

**Comment by miguelpruivo** [comment]
Hi, you can't delete `generated_plugin_registrant.dart` that is a required file and it's generated, not from me, but from the Flutter tooling itself. I'm afraid we can't do anything around it but there is no problem at all of having that warning.
