### ISSUE TITLE
IWB file(*.iwb) can't be selected 

### ISSUE THREAD

**Issue by excess4** [miguelpruivo/flutter_file_picker#652]
I want to open *.iwb file under iOS using below codes.
FilePickerResult result = await FilePicker.platform.pickFiles(
          type: FileType.custom,
          allowedExtensions: ['iwb'],
        );
But the file can't be selected. Btw other file extension works well.

**Comment by miguelpruivo** [comment]
@excess4 hi, I'm sorry that you are experiencing this, sometimes some specific extensions cannot be handled from the native side — this is, not resolved to a valid UTI, which result in that behavior.

I'm afraid you'll have to allow all types and then discard invalid files after picking on your end.

Sorry for any inconvenience.
