### ISSUE TITLE
Question on how to upload a mp3 file in memory after user selects

### ISSUE THREAD

**Issue by syleishere** [miguelpruivo/flutter_file_picker#655]
For the web my understanding is javascript in general cannot read a users directory for say songs to play them on it's own due to security. Which makes sense. So seems only way around this to play playlists on web is to let user select  songs in a directory then upload them say to a python fastapi script. Then music player could play them at a network url.

So my question then is what is best way to do this? I see we get file.bytes which I assume is a Uint8List from documentation, what would be correct way to upload this file to a fastapi? Doesn't it need to be a regular file first?

**Comment by miguelpruivo** [comment]
@syleishere hi, I'm not familiar with fastapi actually, but I'd say you should be able to use the `bytes` directly. This is, you have all the file bytes, so it's just a matter of uploading to there or you should probably be able to load it directly from the bytes into a player, for example.
