### ISSUE TITLE
Slow while selecting mov file not yet fixed

### ISSUE THREAD

**Issue by SubashManian** [miguelpruivo/flutter_file_picker#658]
**Describe the bug**
Duplicate of #531 
I think this issue is not yet fixed still it's slow to pick mov files. Below log are shown in console. any other solution for this?

**Below Added a Video on that you can see the type of video is picking both are mov formats, but one is applied with slow motion effects getting slow to pick**

Happening iOS Physical Device

**Platform**
- [] iOS

**How are you picking?**
Picking mov format file from the photo library

**Details to reproduce the issue**
directly select the mov file that which is recorded from iOS mobile with slow motion effects

**Error Log**
***** Picker:<PHPickerViewController: 0x1208d7b00> didFinishPicking:(
"<PHPickerResult: 0x283b466a0>"
)
-[FilePickerPlugin picker:didFinishPicking:] [Line 381]

**Flutter Version details**
2.0.1

**Screenshots and/or video**
https://user-images.githubusercontent.com/45756921/112493814-80cef100-8da8-11eb-8c84-119497ad0934.MP4

**Comment by miguelpruivo** [comment]
What’s the size of the file being picked? How are you picking (the method call)?

**Comment by SubashManian** [comment]
**File size** 
57MB 

**Method used for picking file**

`try {
      FilePickerResult result = await FilePicker.platform.pickFiles(
        allowMultiple: true,
        type: FileType.media,
        withData: false,
      );
}`

@miguelpruivo

**Comment by miguelpruivo** [comment]
Ser `allowCompression` to `false`

**Comment by SubashManian** [comment]
same Delay is there no improvement

**Comment by miguelpruivo** [comment]
@SubashManian if you could debug and understand what might be causing it, I’d be happy to fix it. It should be easier for you since you can always replicate it.

**Comment by garlicPasta** [comment]
I am running also in the same problem. The waiting time is proportional to the size of the file on my device.
I am using the following code:
```
    FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.media,
        withData: false,
        allowMultiple: true,
        allowCompression: false);
```
This issue should not be close so people can know that the problem is there.

**Comment by miguelpruivo** [comment]
If the file is being picked/fetched from iCloud (or any other cloud provider) it's possible that it could take a while until is ready to use. You can always check the status with the callback.

**Comment by kartik1225** [comment]
I have found that if the video is in slow-mo (recorded from the iPhone) then we can reproduce this delay while picking that file. 

I am not native iOS dev so I also can't help but authors can reproduce the delay in order to create some workaround for this issue. Hope it resolve soon.
