### ISSUE TITLE
file_picker incompatibility with video_player package

### ISSUE THREAD

**Issue by sobhan15** [miguelpruivo/flutter_file_picker#659]
hi,
The problem I encountered is related to the two packages [file_picker](https://pub.dev/packages/file_picker) and [video_player](https://pub.dev/packages/video_player).
In Debug Build, everything works fine.
But in the release mode, package[ video_player](https://pub.dev/packages/video_player) shows this error:

```
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0 VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:177)
```

After deleting package [file_picker](https://pub.dev/packages/file_picker), this problem does not exist and everything works fine.
These two packages seem to be incompatible.
Any Solution?

**Platform**
- [] Android

**Flutter Version details**

```
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.utf8)
    • Flutter version 2.0.2 at /home/sobi/snap/flutter/common/flutter
    • Framework revision 8962f6dc68 (2 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/sobi/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by miguelpruivo** [comment]
Hi, I’m sorry if you’re experience any issue, but you say that if you remove file_picker it works, but I say the opposite, if you remove the video_player it works as well. 😬

It seems that the video_player is the one throwing an exception so it seems that the issue is only related with it. I’d suggest you opening an issue there, but so far, I’ve noidea of incompatibilities between these two plugins.

I’m sorry for any inconvenience.

**Comment by bsbilal** [comment]
any updates?

**Comment by bsbilal** [comment]
any updates? i can't play local videos which was selected on file_picker.

**Comment by bsbilal** [comment]
@sobhan15 @miguelpruivo  

the video path returns File: '/data....'. you have to remove some characters.


be like
` selectedFilePath=  selectedFilePath.toString().replaceAll("\'", "");
   Navigator.push(context, MaterialPageRoute(builder: (context) => ScreenVideoPreview("${selectedFilePath.toString().substring(6)}")));
     `
