### ISSUE TITLE
Pick from Gallery for Images (Android)

### ISSUE THREAD

**Issue by tmthecoder** [miguelpruivo/flutter_file_picker#661]
When utilizing the `.image` filetype on FilePicker, I'm opened to the File Explorer window and am wondering whether there is any way to utilize the Android device's default gallery as the picker defaults to the user's documents directory in my case when any file picker action is started. If this is possible, which I think should be using the MediaStore API, I could write a PR if needed. iOS already does this, but android doesn't, leaving me with where I picked in a custom file on another filepicker call

**Comment by miguelpruivo** [comment]
If this is possible on both iOS and Android, feel free to purpose an API and I’d be glad to implement it. Seems useful if possible.

**Comment by tmthecoder** [comment]
Just submitted a PR outlining the above

**Comment by miguelpruivo** [comment]
Closing as this is already implemented.

Thank you.
