### ISSUE TITLE
Image is not selecting on iOS 14 simulator

### ISSUE THREAD

**Issue by Abhishek01039** [miguelpruivo/flutter_file_picker#664]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
Image is not selecting on the simulator

Code:
```
final FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      
      allowMultiple: true,
    );
    if (mounted) {
      setState(() {
        if (result != null) {
          for (final item in result.paths) {
            _image.add(File(item!));
            // _image = _image.toSet().toList();
          }
        }
      });
    }
```

<img width="564" alt="image" src="https://user-images.githubusercontent.com/56479665/112713909-b1746f00-8efd-11eb-8ae7-a35967f30236.png">

**Platform**
- [] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
IOS 14.3

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2 20D64 darwin-arm, locale en-IN)
    • Flutter version 2.0.3 at /Users/abhishek/sdks/flutter2/flutter
    • Framework revision 4d7946a68d (8 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/abhishek/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • D9CA119B-B70F-461F-B4E3-514AA31F5459 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3
      (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

**Additional context**

**Comment by Abhishek01039** [comment]
Hello @miguelpruivo 
can you please take a look at this issue?
Thanks

**Comment by miguelpruivo** [comment]
You’re probably picking the first image (pink flowers) if so, then that’s a known iOS simulator issue when picking that HDR picture. That shouldn’t be an issue with a real device though.

**Comment by Abhishek01039** [comment]
Hello @miguelpruivo 
I have tested it on a real device and it is working fine.
but whatever image I have selected from the gallery in the simulator. this is not working.

**Comment by miguelpruivo** [comment]
Yes, this is a known issue. I suspect on some issue related with iOS version of simulator. If it happens to happen on a real device, let me know.

Sorry for any inconvenience.

**Comment by Abhishek01039** [comment]
Yeah, Thanks @miguelpruivo
