### ISSUE TITLE
dependency incompatible

### ISSUE THREAD

**Issue by MedwinCorreo** [miguelpruivo/flutter_file_picker#667]
![image](https://user-images.githubusercontent.com/16618565/112744870-56627b00-8fd6-11eb-9919-084123ce0b3b.png)

**Platform**
- [] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.
> upon execution of flutter run 

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

![image](https://user-images.githubusercontent.com/16618565/112744918-b9541200-8fd6-11eb-9973-5eb9eaf9f7b8.png)

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, make sure you update your other dependencies to latest versions as well. This plugin is updated to support up to latest versions, so if you have any issue, it's likely with another plugin stuck in a old version. Is this case, I suspect of `path_provider`.

Closing as this is likely a dependency resolution issue with other plugins that need to be updated as well.
