### ISSUE TITLE
readStream always returns null on Flutter Web. 

### ISSUE THREAD

**Issue by ChristianConstantNel** [miguelpruivo/flutter_file_picker#671]
When trying to convert the file to a Stream<List<int>> it always returns null.
I've tried multiple different files but, it never works.

Below is the code for the issue.

```
 FilePickerResult result = await FilePicker.platform.pickFiles();
 if (result != null) {
     final input = result.files.single.readStream;
     print(input); //* Always null
  }
```

**Comment by jhancock4d** [comment]
On pickFiles if you pass withReadStream: true you get the stream you're looking for.
