### ISSUE TITLE
Allowed Extensions Failed to work for 'csv'

### ISSUE THREAD

**Issue by mcgaryp** [miguelpruivo/flutter_file_picker#672]
When attempting to use the this package I attempted to filter the options of files the user can pick from with the csv file. The file picker opens but does not allow any files to be selected.

Using: 
- Android Tablet
- FileType.custom
- extensionAllowed: ['csv']

**Comment by miguelpruivo** [comment]
Hi, `csv` unfortunately is one of those edge cases that isn't resolved to any type of valid MIME/UTI, which then happens to let you pick anything.

The only way at this moment is for you to discard/ignore all the non `csv` files after picking by iterating through them and checking the `extension` property.

Sorry for any inconvenience.
