### ISSUE TITLE
My application get crashed on launch in release mode - Android

### ISSUE THREAD

**Issue by uc-dve** [miguelpruivo/flutter_file_picker#674]
**I am using file_picker 3.0.0 with flutter 2.0.3**

`flutter run --release`

file_picker plugin is causing the issue, I have removed it and now it is working fine.

> Running Gradle task 'assembleRelease'... Done 351.2s
> ✓ Built build/app/outputs/flutter-apk/app-release.apk (79.4MB).
> Installing build/app/outputs/flutter-apk/app.apk... 8.2s
> Error: ADB exited with exit code 1
> Performing Streamed Install
> Installing build/app/outputs/flutter-apk/app.apk... 12.9s
> 
> Flutter run key commands.
> h Repeat this help message.
> c Clear the screen
> q Quit (terminate the application on the device).
> E/AndroidRuntime(14207): FATAL EXCEPTION: main
> E/AndroidRuntime(14207): java.lang.IllegalAccessError: Interface androidx.lifecycle.c implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in /data/app/com.flutter.ucertifyLearn-oZWPRFNZtCMouBh8DZMrtg==/base.apk)
> E/AndroidRuntime(14207): at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:69)
> E/AndroidRuntime(14207): at com.flutter.ucertifyLearn.MainActivity.m(Unknown Source:5)
> E/AndroidRuntime(14207): at io.flutter.embedding.android.f.k(Unknown Source:58)
> E/AndroidRuntime(14207): at io.flutter.embedding.android.e.onCreate(Unknown Source:13)
> E/AndroidRuntime(14207): at android.app.Activity.performCreate(Activity.java:7224)
> E/AndroidRuntime(14207): at android.app.Activity.performCreate(Activity.java:7213)
> E/AndroidRuntime(14207): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
> E/AndroidRuntime(14207): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
> E/AndroidRuntime(14207): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
> E/AndroidRuntime(14207): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> E/AndroidRuntime(14207): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> E/AndroidRuntime(14207): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> E/AndroidRuntime(14207): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
> E/AndroidRuntime(14207): at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(14207): at android.os.Looper.loop(Looper.java:201)
> E/AndroidRuntime(14207): at android.app.ActivityThread.main(ActivityThread.java:6806)
> E/AndroidRuntime(14207): at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(14207): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> E/AndroidRuntime(14207): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by miguelpruivo** [comment]
Hi, there are a lot of similar issues on the repo and solutions already described [on the Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting). Please, check there.

Sorry for any inconvenience.
