### ISSUE TITLE
PlatformFile.path is null in web.

### ISSUE THREAD

**Issue by Mhsanjib** [miguelpruivo/flutter_file_picker#677]
I am getting a null path while running the following code in macOS(flutter web).
```
FilePickerResult result = await FilePicker.platform.pickFiles();
PlatformFile file = result.files.single;
print(file.path); //prints null
```

**Comment by niravmandani** [comment]
I got the same issue in flutter web

**Comment by ndungudedan** [comment]
Same issue on flutter web..but its working fine on android

**Comment by ndungudedan** [comment]
This [stackoverflow thread](https://stackoverflow.com/a/65759028) might help.

**Comment by miguelpruivo** [comment]
Guys, don’t get me wrong, but that has been answered A LOT of times in a lot of similar issues.

That is on the documentation and also the exception itself throws a message saying that’s unsupported.

But once again, you can’t access paths on web browsers, you need to use the bytes property.
