### ISSUE TITLE
array buffer allocation failed

### ISSUE THREAD

**Issue by masseelch** [miguelpruivo/flutter_file_picker#678]
**Describe the bug**
Picking a file greater than ~500MB on the web results in `array buffer allocation failed` in chrome js-console. The file is then passed to http to be uploaded to a remote server. 

I do not know if this is related to this package, http or flutter itself and I am missing the skills to check myself. If this is wrong here I can open this at the flutter repo. 

**Platform**
- [x] Web

**Platform OS version**
Linux 5.4.108-1-MANJARO #1 SMP PREEMPT Wed Mar 24 18:24:35 UTC 2021 x86_64 GNU/Linux

**Reproducibe example**
```dart
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          child: Text('Select Files'),
          onPressed: () async {
            final pickedFiles = await FilePicker.platform.pickFiles(
              type: FileType.media,
              withReadStream: true,
            );

            final req = MultipartRequest('POST', Uri.parse('httpbin.org/post'));

            req.files.add(MultipartFile(
              'file',
              pickedFiles!.files.single.readStream!,
              pickedFiles.files.single.size!,
            ));

            await req.send();
          },
        ),
      ),
    );
  }
}

```

**Error Log**
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at Function._create1 (http://localhost:42427/dart_sdk.js:29546:14)
    at Function.new (http://localhost:42427/dart_sdk.js:29518:49)
    at convert._ByteCallbackSink.new.add (http://localhost:42427/dart_sdk.js:44181:59)
    at _RootZone.runUnaryGuarded (http://localhost:42427/dart_sdk.js:37017:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:42427/dart_sdk.js:30951:22)
    at _DelayedData.new.perform (http://localhost:42427/dart_sdk.js:34223:28)
    at _StreamImplEvents.new.handleNext (http://localhost:42427/dart_sdk.js:34327:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:42427/dart_sdk.js:34088:16)
    at Object._microtaskLoop (http://localhost:42427/dart_sdk.js:37332:13)
    at _startMicrotaskLoop (http://localhost:42427/dart_sdk.js:37338:13)
    at http://localhost:42427/dart_sdk.js:33109:9
```

**Comment by miguelpruivo** [comment]
Hi, honestly, I don't see what could be causing this. Have you found a solution so far?

**Comment by masseelch** [comment]
Sadly no. But i found a related [issue in the flutter repo ](https://github.com/flutter/flutter/issues/76036). That plugin seems to have the same bug, oddly enough [file_picker_cross](https://pub.dev/packages/file_picker_cross) does not. But I do not know where they differ in the implementation.

**Comment by miguelpruivo** [comment]
Closing as it should be low priority as of now. I'll reopen if anyone else experiences this issue.

Sorry for any inconvenience.

**Comment by CubitSpeed** [comment]
> Closing as it should be low priority as of now. I'll reopen if anyone else experiences this issue.
> 
> Sorry for any inconvenience.

I'm also running into this

**Comment by nwparker** [comment]
> > Closing as it should be low priority as of now. I'll reopen if anyone else experiences this issue.
> > Sorry for any inconvenience.
> 
> I'm also running into this

+1

**Comment by nwparker** [comment]
I opened https://github.com/flutter/flutter/issues/88465

It's probably the same core issue

**Comment by ledjoncili** [comment]
> Closing as it should be low priority as of now. I'll reopen if anyone else experiences this issue.
> 
> Sorry for any inconvenience.

I am also running into this.

**Comment by nicolaspernoud** [comment]
Same here !

**Comment by Cellularhacker** [comment]
I'm also still same here !

**Comment by vidhi002** [comment]
same issue
