### ISSUE TITLE
Flutter Web -> Invalid argument(s) (path): Must not be null

### ISSUE THREAD

**Issue by gOzaru** [miguelpruivo/flutter_file_picker#679]
Hello guys, 
I have checked previous closed issues and still found no solution to this error. 
I am on Flutter Web. 
Anyone know where I went wrong?
I followed the example on Wiki.
I am also using dart:io for this. 

```
void selectSong() async {
    try {
      FilePickerResult result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['mp3']);
      File song = File(result.files.single.path); 
      print("Name: $song.name");

      if (song != null) {
        setState(() {
          songPath = basename(song.path);
          uploadSongFile(song.readAsBytesSync(), songPath);
          print("setState Song");
        });
      } else {
        print("User cancelled.");
      }
    } catch (e) {
      print("Song error: $e");
    }
  }
 
  Future<String> uploadSongFile(List<int> song, String songPath) async {
    ref = FirebaseStorage.instance.ref().child(songPath);
    StorageUploadTask uploadTask = ref.putData(song);
    await uploadTask.future.whenComplete(() => null);
    print("uploadSongFile is processing...");
    return songURL = await ref.getDownloadURL();
  }
```

**Platform**
Web

**Platform OS version**
Windows 10

Here is the screenshot:
[https://pasteboard.co/JWx7HuO.jpg](https://pasteboard.co/JWx7HuO.jpg)

**Comment by gOzaru** [comment]
It seems we can't use dart:io for Flutter web. 
We have to use dart:html instead. 
Just figure it out. 
But I don't know how to use File from dart:html. 
Is there any example I can learn with? 
Thank you.

**Comment by miguelpruivo** [comment]
Hi, you need to use the `bytes` property on web. There are a few examples if you search on this repo’s issues.
