### ISSUE TITLE
Can it be used as an multi-image-picker?

### ISSUE THREAD

**Issue by fzyzcjy** [miguelpruivo/flutter_file_picker#680]
It is very common that we want to pick multiple images. However, the officail image_picker [does not support](https://github.com/flutter/flutter/issues/25508) it. In addition, [this library](https://github.com/Sh1d0w/multi_image_picker) has been archived.

Therefore, I wonder whether flutter_file_picker can be used to pick multiple images? This would be a very commonly used feature, and by supporting it, this library will have more users!

From the example, it seems that non-image files also appears at the UI, therefore it is not that satisfactory to the users.

**Comment by Ahmadre** [comment]
> It is very common that we want to pick multiple images. However, the officail image_picker [does not support](https://github.com/flutter/flutter/issues/25508) it. In addition, [this library](https://github.com/Sh1d0w/multi_image_picker) has been archived.
> 
> 
> 
> Therefore, I wonder whether flutter_file_picker can be used to pick multiple images? This would be a very commonly used feature, and by supporting it, this library will have more users!
> 
> 
> 
> From the example, it seems that non-image files also appears at the UI, therefore it is not that satisfactory to the users.

Try media_gallery plugin or multi_image_picker.

**Comment by FloPMT** [comment]
> Try media_gallery plugin or multi_image_picker.

Those don't support Flutter Web.. I think @fzyzcjy is right, would be a great addition

**Comment by miguelpruivo** [comment]
@fzyzcjy you can use this plugin with `FileType.image` filter and `allowMultiple: true` and you should be able to pick multiple images at once.
