### ISSUE TITLE
Can't select file from gallery

### ISSUE THREAD

**Issue by JenishEmpiric** [miguelpruivo/flutter_file_picker#682]
I can pick file from download folder,Google Drive ,Recent Files but i can not select file from galeery,music,audio

**Comment by gbbest15** [comment]
my boss notices this, i cant wait to see his response.....

**Comment by miguelpruivo** [comment]
I assume you are having this "issue" on iOS.

That's just how it works for selecting files, you can't access both gallery and files app at the same time, so you'll have to choose by using the a filter property. Check the documentation [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/API#filters).

**Comment by JenishEmpiric** [comment]
> my boss notices this, i cant wait to see his response.....

did you get his response?
