### ISSUE TITLE
Don't import implementation files from another package.

### ISSUE THREAD

**Issue by appsbykuldeep** [miguelpruivo/flutter_file_picker#685]
I am making an android app..
I Got Don't import implementation files from another package. error...
I checked all closed issued regarded this issue but my problem is still same...
when I removed file_picker: ^3.0.1 package  ....error gone
I was also tried // ignore: implementation_imports this is use less

Help Me Please !!!

**Comment by miguelpruivo** [comment]
Hi, just ignore that. It happens because of a generated file that we don't have control of. I can't prevent it from creating that import.

Sorry for any inconvenience.

**Comment by kamleshwebtech** [comment]
I have deleted generated_plugin_registrant.dart file then this package works in debug mode but when I compile app and upload it to Google Play Store in live mode then it does not work and no permission is asked. Could you please suggest me what is the issue, while it works in debug mode. Thanks again. Look forward to hear you.
