### ISSUE TITLE
Crash on IOS

### ISSUE THREAD

**Issue by EjazAmir** [miguelpruivo/flutter_file_picker#686]
Mulitple times app got crashed on Tapping Add button when user select the multiple images and videos. the firebase crash reported is:
file_picker
-[FilePickerPlugin picker:didFinishPicking:]
<img width="780" alt="Screenshot 2021-04-15 at 9 32 45 AM" src="https://user-images.githubusercontent.com/25684301/114814393-8b8c0d00-9dcd-11eb-954f-6591c54dd9d1.png">

**Comment by miguelpruivo** [comment]
Hi, unfortunately this is one of those edge cases that can't be replicated and likely are related with the picked file or device where it is running. Let me know if you manage to replicate it always and provide me with a steps to do so.

Thank you.
