### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: No top-level getter '_registerPlugins' declared.

### ISSUE THREAD

**Issue by adam12west23** [miguelpruivo/flutter_file_picker#689]
**Describe the bug**
When calling the pickFiles method and once selected a file to pick, the following exception araises:

Exception has occurred.
NoSuchMethodError (NoSuchMethodError: No top-level getter '_registerPlugins' declared.
Receiver: top-level
Tried calling: _registerPlugins)

in errors_patch.dart, static method _throwNew.

Please help.
Thanks

**Platform**
- [X] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
Andriod version 9

**Details to reproduce the issue**
Add those dependencies in pubspec.yaml:
   permission_handler: ^6.1.3
   file_picker: ^3.0.1
and run this code:
  import 'package:file_picker/file_picker.dart';
  import 'package:permission_handler/permission_handler.dart';

  Future<bool> _checkStoragePermission() async {
    var status = await Permission.storage.status;
    if (!status.isGranted) {
      status = (await [
        Permission.storage,
      ].request())[Permission.storage]!;
    }
    return status.isGranted;
  }

  Future<void> test(BuildContext context) async {
    if (!await _checkStoragePermission()) return;
    await FilePicker.platform
        .pickFiles(type: FileType.custom, allowedExtensions: ['xml']);
    // here the exception araises
  }

**Error Log**
No log reported, the app just crashes and restarts.

**Flutter Version details**
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.18363.1441], locale it-IT)
    • Flutter version 2.0.3 at c:\Flutter SDK
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\dbelsole\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\dbelsole\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\dbelsole\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 88.0.705.68

**Comment by miguelpruivo** [comment]
Hi, this looks like an issue related with your local build. Try cleaning and rebuild again or check any of other dependencies that might be conflicting.
