### ISSUE TITLE
add localIdentifier field in PlatformFile

### ISSUE THREAD

**Issue by Fnalsk** [miguelpruivo/flutter_file_picker#691]
My use case is that I want to select a bunch of files, then add them to an album on the device.

The way iOS handles albums is that each album contains pointers to the image assets instead of containing copies of the image files themselves. Using the [photo_manager](https://pub.dev/packages/photo_manager) package it would be very easy to accomplish my intended goal if i had access to the `localIdentifier` field that identifies assets on iOS. 

[wechat_assets_picker](https://pub.dev/packages/wechat_assets_picker#:~:text=Flutter%20WeChat%20Assets%20Picker&text=An%20assets%20picker%20which%20looks,the%20state%20of%20the%20picker.) implements such a solution using the value `PhotoKit > PHObject > localIdentifier`. However I'd like the file picker to look native to the device and not have a custom wechat theme, so I can't use that. 

I'd look into adding this feature into file_picker myself, but I'm not yet familiar with the current codebase here nor do I have experience with swift for the ios side. 

As a side note - on the wechat_assets_picker package it seems to indicate that there is a Database _id column for android? not entirely sure what that is but maybe someone will find a need for that later on.

**Comment by Fnalsk** [comment]
The android comment was more of an afterthought. I just noticed that a different package included it, so there's probably someone else that finds that piece useful. For my purposes though I would only need the ios bit.

If i had the identifier, I'd use [photo_manager](https://pub.dev/packages/photo_manager) to do something like:

```
PhotoManager.editor.copyAssetToPath(asset: identifierForThePhoto, pathEntity: albumIveAlreadyCreated);
```

this would add the photo to the album, which is what I wanted to accomplish.

**Comment by miguelpruivo** [comment]
Ok then, I think I can easily add it.

**Comment by Fnalsk** [comment]
do you have an eta on this?

**Comment by miguelpruivo** [comment]
Yes, today. 👍

**Comment by miguelpruivo** [comment]
Well, I was looking into this, and looks like I have to think in a good way to make it easy to understand when using the `PlatformFile`, since this seems to be related only with PHAssets, which refer to media files on iOS, hence, any other kind of files, won't have an `identifier` which may confuse some.

This seems to be an edge case, nevertheless, I'm willing to implement a solution that suits your needs.

**Comment by Fnalsk** [comment]
You could name it `iosAssetIdentifier` and have a comment saying why the field is null for other types of files.

Realistically i think someone would only look into using this field when they are dealing with media files on ios, so i dont think there will be much confusion.

**Comment by Reymai** [comment]
Any updates?

**Comment by miguelpruivo** [comment]
Closing in favor of #617 which is similar.
