### ISSUE TITLE
File type = Image with allowMultiple:true results in one less image getting picked

### ISSUE THREAD

**Issue by envyram** [miguelpruivo/flutter_file_picker#693]
FilePickerResult result = await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: true,
      );

**//Results in 1 file less getting picked**
      print(result.files.length); 

**Platform**
- [] iOS

**Platform OS version**
What version did it happen?

**How are you picking?**
```
      FilePickerResult result = await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: true,
      );
```

**Flutter Version details**
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.0.1 20B50 darwin-x64, locale en-CA)
    • Flutter version 2.0.2 at /Users/vinayak/SDK/flutter
    • Framework revision 8962f6dc68 (6 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/vinayak/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 5203842F-1729-474C-AB85-6767E96ECCE7 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

**Comment by miguelpruivo** [comment]
Hi, if you are relating to the first image on the simulator (the one with the pink flowers) that's just an issue with the simulator and HDR pictures since iOS 14. It shouldn't happen on real device though.

Let me know if this is the case and feel free to close the issue.

Thanks!
