### ISSUE TITLE
IOS folders

### ISSUE THREAD

**Issue by diegopereira99** [miguelpruivo/flutter_file_picker#694]
I can't access other folders on the iphone other than "recent" and "icloud". I would like to access gallery, downloads, common folders.

**Comment by miguelpruivo** [comment]
Hi @diegopereira99, for that you should use the corresponding filter by providing the `type` property. Check the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api).

**Comment by diegopereira99** [comment]
Even passing the "custom" type and filtering the file types, on ios only the "recent" and "iCloud" folders are available to me.
![image](https://user-images.githubusercontent.com/53828569/115898100-8bc28300-a433-11eb-9ca7-ea0ee8dc6f56.png)

**Comment by miguelpruivo** [comment]
@diegopereira99 that's correct. That's just how iOS works. You can't access the photo roll and the files app at the same time — thus, if you want any custom file types you can only specify those on the Files app. If you want to pick media files (from photo roll) you need to use `FileType.media`, `FileType.image` or `FileType.video`. You can't combine those. That's just an OS limitation of native pickers.

Sorry for any inconvenience.
