### ISSUE TITLE
The app does not work in parallel with permissions_handler 

### ISSUE THREAD

**Issue by dancb10** [miguelpruivo/flutter_file_picker#697]
Doesn't work with the latest permissions_handler packet. I've tried going with with several versions of permissions_handler and still i get the same issue. Do you know with what version it works?

**Describe the bug**
Because file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0 and permission_handler_platform_interface <2.0.1 depends on plugin_platform_interface ^1.0.1, file_picker >=3.0.0-nullsafety.3 is incompatible with permission_handler_platform_interface <2.0.1.
**Platform**
- [x] Android
- [x] iOS
- [x] Web
- [x] Desktop (Go)

**Platform OS version**
  file_picker: ^3.0.1

**Comment by miguelpruivo** [comment]
Hi, just use the latest official versions. In this case, use `file_picker: 3.0.1` instead of the pre release version.

Thanks!
