### ISSUE TITLE
Expose original uncached 'uri' in PlatformFile

### ISSUE THREAD

**Issue by vlsim** [miguelpruivo/flutter_file_picker#700]
I would like to suggest to expose the original 'uri' that is used by the picker to PlatformFile. I understand that the file is cached as soon as the picker receives it, but it may be useful to expose this information as it will allow to show this information to the user, even if the content is actually cached already somewhere else.

**Comment by miguelpruivo** [comment]
Ok, this will be added. It’s part of #691.
