### ISSUE TITLE
Customize the native picker color?

### ISSUE THREAD

**Issue by dancb10** [miguelpruivo/flutter_file_picker#704]
How can we customize the native picker color? Seems like if my app is color green but I use this picker, when the native picker opens it's set to blue by default on android. Can we change that?

**Comment by miguelpruivo** [comment]
Hi, sorry, I'm afraid that that isn't possible, since the plugin uses the native pickers. Check [here](https://stackoverflow.com/a/32250940/6919963) for a similar question.

Sorry for any inconvenience.
