### ISSUE TITLE
allowMultiple don't work

### ISSUE THREAD

**Issue by lqmminh** [miguelpruivo/flutter_file_picker#707]
Hi
I have an issues on **file_picker: ^3.0.1** about allowMultiple property
My code:
FilePickerResult result =
        await FilePicker.platform.pickFiles(allowMultiple: true);
But I can only choose one file. Please help me!

**Comment by miguelpruivo** [comment]
Hi. If you are experiencing this on Android likely you are missing its usability. You need to tap & hold in order to let the selector appear.

**Comment by lqmminh** [comment]
Ohhh. Haha thank you for the reply. That's it <3

**Comment by mkhtradm01** [comment]
I have the same issue on iOS below is my code:

    var result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowMultiple: true,
      withReadStream: true,
      allowedExtensions: ['doc', 'pdf', 'zip', 'docx', 'odt', 'txt', 'svg', '.xlsx'],
    );

file_picker: ^3.0.3
Flutter Doctor:

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-AE)
    • Flutter version 2.2.2 at /Users/mac/Developer/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Aderm’s iPhone (mobile) • 118a4c71038902eaedaf5b7bcaf46acad390fcd7 • ios
      • iOS 14.6
    • macOS (desktop)         • macos                                    • darwin-x64
      • macOS 11.4 20F71 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript
      • Google Chrome 91.0.4472.114

• No issues found!

**Comment by miguelpruivo** [comment]
On iOS it should allow multiple selection if you tap the select option in the upper right option.
