### ISSUE TITLE
Caching files from URI path received through Android intents

### ISSUE THREAD

**Issue by brightseagit** [miguelpruivo/flutter_file_picker#709]
Hello,
Would it be possible for you to add a way through which we could provide a URI path string instead of a file path and then cache that file. With this, we can use the cached file path for various uses.

Thanks for providing this awesome plugin 👍

**Comment by miguelpruivo** [comment]
Hi, mind to give an example of how you'd use it?

**Comment by brightseagit** [comment]
Hello, thanks for your response.

I'm working on an X app. In which the core concept is that when a user tries to open a pdf file on his device then the device provides an option to open the file using the X app. And to do that I'm using the `ChannelPlatform`, I get the data from the File Viewer app, and through that data, I get the URI path of the file. Now what I'm looking for is a way to cache the file in the app directory using the URI path so that I can easily further modify it. 
But recently I found out that there is no clear explanation in flutter on how to do that and also there is some kind of restriction from API 30.

So, I was thinking if you can add an option through which we can auto pick a file using the URI path then it would be a great help to me as I don't know how to do that. And if you want a working example of obtaining a URI path then I can provide that. 

Sorry, as I'm not sure if this is even possible to do.
Thanks
