### ISSUE TITLE
Problem in the release

### ISSUE THREAD

**Issue by Sipioteo** [miguelpruivo/flutter_file_picker#710]
So, when it comes to build the release, the final all always return "null" from the picker. I tried to check if there were any other informations (even using sentry) but the only error is the "null" one. I had the same problem with the official "image_picker".

I don't know how to solve it, and In debug mode it perfectly works. 

Latest stable flutter version
Target Android 30
Latest plugin version.

Thank you, I'll wait for suggestions.

**Comment by miguelpruivo** [comment]
Hi. I’m not sure what you mean. Is it retuning null always in release mode, despite of what you’re picking?

You may want to take a look into adb logcat logs so you can see if you pick something in release mode.

**Comment by Sipioteo** [comment]
> Hi. I’m not sure what you mean. Is it retuning null always in release mode, despite of what you’re picking?
> 
> You may want to take a look into adb logcat logs so you can see if you pick something in release mode.

Exactly, I'm trying to pick a simple image from the gallery (jpg). If I'm in debug mode it works, when I install the signed release version it doesn't. 
The logcat is not giving me any useful information, and only shows the "null" error. 🤷🏻

**Comment by miguelpruivo** [comment]
@Sipioteo could you please try with a different device? Which one are you trying with?

**Comment by Sipioteo** [comment]
> @Sipioteo could you please try with a different device? Which one are you trying with?

Yes, so after some time I figured out where the problem was.
We compile the final apk with a GitHub action and we forgot to upgrade the flutter version. 

Sorry, my bad I didn't thought that we forgot to update flutter there.😓😓😓
