### ISSUE TITLE
Browse documents

### ISSUE THREAD

**Issue by diegopereira99** [miguelpruivo/flutter_file_picker#711]
When a document is downloaded from Whatsapp, it does not go to the DOWNLOADS folder but to a folder inside Whatsapp.
Using file_picker, how would I go about accessing that folder? 

When I am looking for an image, I can navigate between the WhatsApp images as shown below. However, when it comes to documents, it is not possible.

![WhatsApp Image 2021-05-14 at 16 17 20](https://user-images.githubusercontent.com/53828569/118318593-f8c7b680-b4cf-11eb-93ca-34f42c0dab19.jpeg)

**Comment by miguelpruivo** [comment]
Hi. I don't think that since Android 10 this can be possible with 3rd party apps. Please [check here](https://stackoverflow.com/a/65935034/6919963).

However, if you find a way, please let me know so I can reopen this issue.

**Comment by diegopereira99** [comment]
But why it is possible when i openning the images?. Look in the print, there is the folder "WhatsApp Images".

**Comment by miguelpruivo** [comment]
That's because images are shared folders (different permissions) that documents. It's all up to where the WhatsApp saves its content I'd say.
