### ISSUE TITLE
pickFIles always returns empty list on iOS emulator

### ISSUE THREAD

**Issue by Jamesfleming1** [miguelpruivo/flutter_file_picker#712]
I am calling pickFiles with multiple false and type: FileType.image. 

I am using code almost identical to demo code but every time I call result.files it is empty despite the gallery of photos opening and allowing me to click on one. 
Setting allowMultiple to true doesn't help as result.files is still empty. 
I check that I indeed have the permissions using permission_handler package but despite having permissions I still can't get any photos using the file picker. 

if FilePickerResult result = await FilePicker.platform.pickFiles(etc)
result is not null but result.files is empty 

Any help is much appreciated. Let me know what else would be useful in figuring out what is wrong

I am using iOS Simulator
It does work on my physical iPhone 7.

**Comment by miguelpruivo** [comment]
Hi, I suspect you are clicking on the pink roses of the iOS simulator. That picture has an issue with the simulator since iOS 14. It's not actually an issue with the plugin.

**Comment by robert-virkus** [comment]
For me it does not matter which photo I chose. I tried both with and without multiple files.

**Comment by Jamesfleming1** [comment]
Yeah I tried multiple different images

**Comment by miguelpruivo** [comment]
Is it working properly on a real device? What is the version that you are running on the simulator?

**Comment by Jamesfleming1** [comment]
Yea seems to be working fine on the real device. Most recent version filePicker

**Comment by Jamesfleming1** [comment]
On Simulator with iOS 14.5

**Comment by Jamesfleming1** [comment]
https://stackoverflow.com/questions/66103715/unable-to-select-image-using-flutter-image-picker-on-ios-simulator 

While this is a different package, looks like this is potentially an issue because of M1 Macs which I have.... @robert-virkus  are you on an m1 Mac

**Comment by robert-virkus** [comment]
Yes, sorry for not having mentioned that earlier. I work with an M1 Mac.

**Comment by Jamesfleming1** [comment]
Okay sounds like this is definitely an apple m1 issue

**Comment by miguelpruivo** [comment]
Please, keep me posted if any change needs to be made on my end.

Thank you!

**Comment by lam-nv** [comment]
Hi @miguelpruivo,

I have the same issue as @Jamesfleming1 when I integrated this package into our app
Also use chip apple m1, but I tried and work well with example from package.

**Comment by miguelpruivo** [comment]
Hum, this seems to affect only M1 Macs. Is that it @lam-nv?

**Comment by CrissGib** [comment]
Hi Guys, this is NOT an M1 Mac issue, I am still using an intel based mac and the issue still remains
