### ISSUE TITLE
Device Local File Pick: [DocumentManager] Error: Failed to associate thumbnails for picked URL in iOS

### ISSUE THREAD

**Issue by CellCS** [miguelpruivo/flutter_file_picker#714]
**Describe the bug**
file_picker: ^3.0.1
IPad - 6th generation,  14.4 iPadOS.
Select one local image file, shows the following exception" 

```
[DocumentManager] Failed to associate thumbnails for picked URL 
file:///private/var/mobile/Containers/Shared/AppGroup/E6513050-3611-4C6A-A876-56A3E5965544/File%20Provider%20Storage/Testing%20filesScreenshot%202021-04-28%20at%201.46.24%20PM.png with the Inbox copy file:///private/var/mobile/Containers/Data/Application/6884FD05-C394-4899-B909-BCD2A1D88A6B/tmp/com.domain.appname-Inbox/Screenshot%202021-04-28%20at%201.46.24%20PM.png: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2830807e0 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
```

**Platform**
- [] Android
- [X] iOS : ipadOS 14.4
- [] Web
- [] Desktop (Go)

**Platform OS version**
ipadOS 14.4

**How are you picking?**
```
 FilePickerResult result = await FilePicker.platform.pickFiles()
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**

Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64

Dart version 2.12.3

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, does the image get picked?

**Comment by miguelpruivo** [comment]
Right. This is a known "issue" that appears in the logs and yet without a define solution but also it shouldn't impact the usage at all. If it does, please, feel free to reopen it.

**Comment by MrBologna** [comment]
[VITALCC.ZIP](https://github.com/miguelpruivo/flutter_file_picker/files/14749591/VITALCC.ZIP)
