### ISSUE TITLE
File not picking on Android with a log message - User cancelled the picker request 

### ISSUE THREAD

**Issue by krishnakumarcn** [miguelpruivo/flutter_file_picker#717]
When trying to pick a file from Android it is not picking it but ending the session with a log message:

```
D/FilePickerDelegate(30037): Selected type */*
I/FilePickerDelegate(30037): User cancelled the picker request


```

This behavior is occurring for me in two cases:
1.  When File type is image, this is the behavior on most of the android versions, but works partially on Android 11.
2.  From file type as 'any' and opens another third party file manager from the picker window. its not picking the file, sometime its not closing the third party file manager also.

**Comment by miguelpruivo** [comment]
@krishnakumarcn please, provide more details and a sample where this issue can be reproduced.

**Comment by krishnakumarcn** [comment]
I tried to reproduce this with the repository's example app but its working fine there. The only change I could find it on my side is the flutter sdk. I'm still not made the min sdk to 2.12.0. Will this be the cause for the issue?
@miguelpruivo  Sorry for the trouble if any.

**Comment by miguelpruivo** [comment]
@krishnakumarcn it shouldn't, but there can be something else (with other dependencies) conflicting with your project. I don't know. Try creating a new project and add file picker only and see if it's working properly. If it is, then it shouldn't be either from the plugin and SDK but something else that you must try to dig down.

**Comment by krishnakumarcn** [comment]
Sure, thanks @miguelpruivo . I'll check.

**Comment by krishnakumarcn** [comment]
After a little bit of inspection the culprit is Android's singleInstance MainActivity launch mode.

`activity android:name=".MainActivity" android:launchMode="singleInstance" `

When setting the launchMode to singleInstance, 
```

await FilePicker.platform.pickFiles(allowMultiple: true, type: FileType.any)
```

 returns `null` when we are picking file after opening a third party app from the file picker window.
There is a log message also in the console

```
D/FilePickerDelegate(29145): Selected type */*
I/FilePickerDelegate(29145): User cancelled the picker request

```

**Comment by miguelpruivo** [comment]
@krishnakumarcn good point. I believe that because you have a single instance, it doesn't allow you to launch another activity on your app's context, hence the reason it cancels without content.

**Comment by krishnakumarcn** [comment]
@miguelpruivo  Again, this is a valid use-case, right? For deep linking scenarios the `singleInstance` is something everyone uses when we don't want to open up a new instance of the app even if the app is running on a separate instance.

Is there any limitation to support this from the plugin by design or is there any workarounds?

**Comment by miguelpruivo** [comment]
@krishnakumarcn that's correct. There should be a way to handle this, but I have yet to search. Let me know if you come up with something and I'd be glad to fix it otherwise I don't have a ETA for this, I'm sorry.

**Comment by krishnakumarcn** [comment]
sure ✌️

**Comment by miguelpruivo** [comment]
@krishnakumarcn check my edit.

**Comment by krishnakumarcn** [comment]
That's super quick. Let me see. @miguelpruivo

**Comment by krishnakumarcn** [comment]
And that worked. 
Changing from `android:launchMode="singleInstance"` to `android:launchMode="singleTask"` solved this issue.
