### ISSUE TITLE
Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by Yoda-Man** [miguelpruivo/flutter_file_picker#719]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-3.0.1\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by miguelpruivo** [comment]
Dup of #653.
