### ISSUE TITLE
ios HDR images

### ISSUE THREAD

**Issue by biancashouse** [miguelpruivo/flutter_file_picker#720]
Using ipad simulator... All images accepted when using FileType.image, except the wildflowers sample, which shows HDR above, meaning it's a High Dynamic Range.

Just FYI.

**Comment by miguelpruivo** [comment]
Hi, thank you, this is a known issue from the simulator since iOS 14 I believe. It shouldn't affect the usage on a real device. Anyway, if you experience any issue on a real device regarding this, let me know.

**Comment by biancashouse** [comment]
Great news. Thanks for the reply. Good to know (I only have the simulator
right now for testing).
