### ISSUE TITLE
Get directory with write access on Android

### ISSUE THREAD

**Issue by minusium** [miguelpruivo/flutter_file_picker#721]
Hey. I have been writing an app, which asks user to select a directory. then the app put multiple files on that directory and these files are not media. I have a problem here, because your library doesn't have any parameter request these.
When I use `getDirectoryPath()`, I get a path for a directory, which can be wrong if the user selects a directory from a storage provider (like google drive), Also I can't write any file there, even if I request `WRITE_EXTERNAL_STORAGE` permission, I'll get `OS Error: Operation not permitted` error.
I'm using `MANAGE_EXTERNAL_STORAGE` for workaround but please add parameters to `getDirectoryPath()` to request persistable and write permission.

Look at this code, from [Signal Android App](https://github.com/signalapp/Signal-Android):
```java
Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
if (Build.VERSION.SDK_INT >= 26) {
    intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI, SignalStore.settings().getLatestSignalBackupDirectory());
}
intent.addFlags(Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION |                                     
                          Intent.FLAG_GRANT_WRITE_URI_PERMISSION |
                          Intent.FLAG_GRANT_READ_URI_PERMISSION);
try {
    fragment.startActivityForResult(intent, requestCode);
} catch (ActivityNotFoundException e) {                 
    Toast.makeText(fragment.requireContext(), R.string.BackupDialog_no_file_picker_available, Toast.LENGTH_LONG).show();
}
```

**Comment by miguelpruivo** [comment]
I'll take a look into it. Thank you!

**Comment by brightseagit** [comment]
Hello, @miguelpruivo do you have any updates on this issue.
Also, recently Google stated:
> Starting August 2021, new apps will be required to target API level 30 (Android 11) and use the Android App Bundle publishing format. Starting November 2021, all app updates will be required to target API level 30 (Android 11). 

So with this change we were no longer able to use api 29 to bypass these restrictions.

**Comment by miguelpruivo** [comment]
@brightseagit so, there is nothing we can do here?

**Comment by brightseagit** [comment]
@miguelpruivo Well, I don't really know how to request write access to the directory path. But as google stated in the rejection email that there are ways to have continuous access to a directory path through privacy-friendly options like SAF so they can't grant my app to have MANAGE_EXTERNAL_STORAGE permission to just get continuous access to a directory.

So, as an alternative, I'm allowing my app users who are using android 10 and below to save files to their desired directory by checking the API of their device. And for users above android 10, I'm using a plugin that allows saving files to the downloads directory.

**Comment by vauvenal5** [comment]
Why not implement it in a similar way like Signal is handling it? Am I missing something?

**Comment by miguelpruivo** [comment]
@vauvenal5 what do you mean?

**Comment by vauvenal5** [comment]
It has been a while since I took a look into the code. But I was under the impression that only the intent flags were missing.

**Comment by minusium** [comment]
Instead of using this plugin, i wrote a FileStorageProvider for my own project and used method channels, but it's very specific for my project and it's a private project.

**Comment by brightseagit** [comment]
> Instead of using this plugin, i wrote a FileStorageProvider for my own project and used method channels, but it's very specific for my project and it's a private project.

Can you please share a sample project showcasing how you did that?
Thank you.

**Comment by minusium** [comment]
> Can you please share a sample project showcasing how you did that?
> Thank you.

Well it's not a clean code and best practice, but it works.

android_file_interface.dart:
```dart
import 'dart:typed_data';

import 'package:flutter/services.dart';

import 'file_storage.dart';

class AndroidInterface extends FileStorageInterface {
  // Channel methods:
  // root getPersistRoot()
  // root selectDirectory()
  // void releaseDirectory(root)
  // root createDirectory(root, name, overwrite)
  // void writeFile(root, subdir, name, type, overwrite, bytes)

  final _platform = MethodChannel('madamin.subtitles/Main');
  final _errors = {
    'no persist document tree': FileOperationError.noSavedPersistRoot,
    'pending': FileOperationError.pending,
    'access error': FileOperationError.accessError,
    'exists': FileOperationError.alreadyExists,
    'creation failed': FileOperationError.creationFailed,
    'canceled': FileOperationError.canceled,
  };

  String? _root;

  // invoke a method with given arguments
  Future<FileOperationResult<String>> _invoke(
    String method, {
    bool returnVoid = false,
    String? root,
    String? subdir,
    String? name,
    Uint8List? bytes,
    bool? overwrite,
  }) async {
    try {
      final result = await _platform.invokeMethod<String>(method, {
        'root': root,
        'subdir': subdir,
        'name': name,
        'bytes': bytes,
        'overwrite': overwrite,
      });
      if (result != null || returnVoid)
        return FileOperationResult(result: result);

      return FileOperationResult(error: FileOperationError.unknown);
    } on PlatformException catch (e) {
      final error = _errors[e.code] ?? FileOperationError.unknown;

      return FileOperationResult(
        error: error,
        result: e.code,
        message: e.message,
      );
    }
  }

  @override
  Future<FileOperationResult<String>> getPersistRoot() async {
    final result = await _invoke('getSavedRoot');
    if (result.error == FileOperationError.success) _root = result.result;
    return result;
  }

  @override
  Future<FileOperationResult<String>> selectDirectory() async {
    final result = await _invoke('selectDirectory');
    // release currently selected directory if new directory selected successfully
    if (result.error == FileOperationError.success) {
      if (_root != null)
        await _invoke('releaseDirectory', root: _root, returnVoid: true);
      _root = result.result;
    }
    return result;
  }

  @override
  Future<FileOperationResult<String>> createDirectory(
    String root,
    String name, [
    bool? overwrite,
  ]) async {
    final result = await _invoke(
      'createDirectory',
      root: root,
      name: name,
      overwrite: overwrite,
    );
    return result;
  }

  @override
  Future<FileOperationResult> writeFile(
    String root,
    String subdir,
    String name,
    Uint8List bytes, [
    bool? overwrite,
  ]) async {
    final result = await _invoke(
      'writeFile',
      root: root,
      subdir: subdir,
      name: name,
      bytes: bytes,
      overwrite: overwrite,
      returnVoid: true,
    );
    return result;
  }
}
```

MainActivity.kt
```kotlin
package madamin.subtitles

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.util.Log
import androidx.annotation.NonNull
import androidx.documentfile.provider.DocumentFile
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import java.io.FileDescriptor
import java.io.FileOutputStream

class MainActivity : FlutterActivity() {
    private val CHANNEL = "madamin.subtitles/Main"
    private var pendingResult: MethodChannel.Result? = null

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            val handlers = mapOf(
                    "getSavedRoot" to ::getSavedRoot,         // root getSavedRoot()
                    "selectDirectory" to ::selectDirectory,   // root selectDirectory()
                    "releaseDirectory" to ::releaseDirectory, // void releaseDirectory(root)
                    "createDirectory" to ::createDirectory,   // root createDirectory(root, name, overwrite)
                    "writeFile" to ::writeFile                // void writeFile(root, name, type, overwrite, bytes)
            )
            if (call.method in handlers) {
                handlers[call.method]!!.invoke(call, result)
            } else {
                result.notImplemented()
            }
        }
    }

    private fun getSavedRoot(call: MethodCall, result: MethodChannel.Result) {
        val persistedPermissions = contentResolver.persistedUriPermissions
        for (p in persistedPermissions) {
            if (p.isWritePermission) {
                // we assume it's a document tree as we don't request anything else
                result.success(p.uri.toString())
                return
            }
        }
        result.error("no persist document tree", null, null)
    }

    private fun selectDirectory(call: MethodCall, result: MethodChannel.Result) {
        try {
            if (pendingResult != null) {
                result.error("pending", "Already there's a pending request", null)
                return
            }
            val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
            intent.addFlags(Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION or
                    Intent.FLAG_GRANT_WRITE_URI_PERMISSION
            )
            startActivityForResult(intent, 100)
            pendingResult = result
        } catch (e: Throwable) {
            Log.e("MainActivity::selectDirectory", "Unhandled error", e)
            result.error(e.javaClass.name, e.message, null)
        }
    }

    private fun releaseDirectory(call: MethodCall, result: MethodChannel.Result) {
        try {
            val rootUri = Uri.parse(call.argument<String>("root")!!)
            contentResolver.releasePersistableUriPermission(rootUri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
        } catch (e: Throwable) {
            Log.e("MainActivity::releaseDirectory", "Unhandled error", e)
            result.error(e.javaClass.name, e.message, null)
        }
    }

    private fun createDirectory(call: MethodCall, result: MethodChannel.Result) {
        try {
            // get root directory
            val rootUri = Uri.parse(call.argument<String>("root")!!)
            val root = DocumentFile.fromTreeUri(context, rootUri)
            if (root == null || !root.canWrite()) {
                result.error("access error", "Directory doesn't exist or it's not writable", null)
                return
            }

            // get arguments
            val name = call.argument<String>("name")!!
            val overwrite = call.argument<Boolean>("overwrite")

            // create directory, or just return found directory if overwrite==true
            val foundFile = root.findFile(name)
            if (foundFile != null && overwrite == null) {
                result.error("exists", "$name already exists", null)
                return
            }
            val file = if (foundFile != null && overwrite == true) foundFile else root.createDirectory(name)
            if (file == null) {
                result.error("creation failed", "Can't create directory $name", null)
                return
            }

            // return directory uri
            result.success(file.uri.toString())
        } catch (e: Throwable) {
            Log.e("MainActivity::createDirectory", "Unhandled error", e)
            result.error(e.javaClass.name, e.message, null)
        }
    }

    private fun writeFile(call: MethodCall, result: MethodChannel.Result) {
        try {
            // get root directory
            val rootUri = Uri.parse(call.argument<String>("root")!!)
            val root = DocumentFile.fromTreeUri(context, rootUri)
            if (root == null || !root.canWrite()) {
                result.error("access error", "Directory doesn't exist or it's not writable", null)
                return
            }

            // get arguments
            val fileName = call.argument<String>("name")!!
            val bytes = call.argument<ByteArray>("bytes")!!
            val fileType = call.argument<String>("type") ?: "*/*"
            val overwrite = call.argument<Boolean>("overwrite")

            // get subdirectory
            val dirName = call.argument<String>("subdir")!!
            val dir = root.findFile(dirName)
            if (dir == null || !dir.isDirectory()) {
                result.error("invalid_subdir", "$dirName is not a valid subdirectory", null)
                return
            }

            // create new file, or just return found file if overwrite==true
            val foundFile = dir.findFile(fileName)
            if (foundFile != null && overwrite == null) {
                result.error("exists", "$fileName already exists", null)
                return
            }
            val file = if (foundFile != null && overwrite == true) foundFile else dir.createFile(fileType, fileName)
            if (file == null) {
                result.error("creation failed", "Can't create file $fileName", null)
                return
            }

            // write bytes to file
            contentResolver.openFileDescriptor(file.uri, "w").use { fd ->
                FileOutputStream(fd!!.fileDescriptor).use { os ->
                    os.write(bytes)
                    os.flush()
                }
            }

            result.success(null)
        } catch (e: Throwable) {
            Log.e("MainActivity::writeFile", "Unhandled error", e)
            result.error(e.javaClass.name, e.message, null)
        }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        if (pendingResult == null || requestCode != 100) {
            super.onActivityResult(requestCode, resultCode, data)
            return
        }
        val result = pendingResult!!
        pendingResult = null
        try {
            if (resultCode == Activity.RESULT_OK && data != null) {
                val uri = data.data!!
                contentResolver.takePersistableUriPermission(uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
                result.success(uri.toString())
            } else {
                result.error("canceled", null, null)
            }
            return
        } catch (e: Throwable) {
            result.error(e.javaClass.name, e.message, null)
        }
    }
}
```

**Comment by brightseagit** [comment]
@minusium Thank you very much for the code, but what is ```file_storage.dart``` in ```android_file_interface.dart```.

**Comment by minusium** [comment]
> @minusium Thank you very much for the code, but what is `file_storage.dart` in `android_file_interface.dart`.

It contains FileStorageInterface abstract class and FileOperationError enum, part of my application.

**Comment by brightseagit** [comment]
@minusium hey Thanks for the info I did try the code above but I still got ```OS Error: Operation not permitted, errno = 1``` when trying to create a file to the directory after selecting the directory.
Here is how I used your code so please let me know if I'm doing something wrong here:-
```dart
final _platform = MethodChannel('package/Main');
await _platform.invokeMethod<String>('selectDirectory'); // selecting test directory only
File('/storage/emulated/0/Test/test.txt').create(recursive: true);
```
Thanks

**Comment by minusium** [comment]
> @minusium hey Thanks for the info I did try the code above but I still got `OS Error: Operation not permitted, errno = 1` when trying to create a file to the directory after selecting the directory.

You should use writeFile method instead of File(...).create()

**Comment by miguelpruivo** [comment]
Has this been solved in the meantime?

**Comment by SomeoneAndNoone** [comment]
Please add this feature ASAP!

**Comment by Tisamu** [comment]
I encounter the same problem,

Added `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` to the `AndroidManifest.xml` file and `android:requestLegacyExternalStorage="true"` to the `<application>` tag. 👍 

But the problem is persisting, Flutter throw me a "permission denied" error after allowing the access to the Download directory from the device UI (triggered by `FilePicker.platform.getDirectoryPath()`). 🤔 

I'm looking for an alternative method for users to save files generated by my App. 😕 

Thanks for you work. 👍

**Comment by Tisamu** [comment]
Hello,

I've been working on other parts of my app until coming back to this problem,

 **And I finally solved it.  :+1:**

- I've installed the [permission_handler](https://pub.dev/packages/permission_handler) package.
- I just left the `WRITE_EXTERNAL_STORAGE` permission to the AndroidManifest file.

Then in the code :

```dart

if (!await Permission.storage.request().isGranted) {
      await Permission.storage.request();
    }
    final dir =
        await FilePicker.platform.getDirectoryPath(); // Choose directory Dialog
    // final dir = await getExternalStorageDirectory();
    if (dir != null) {
      // print('DIR IS "$dir/myFile.gpx"');
      final file = File("$dir/myFile.gpx");
      return file.writeAsString(gpxData.toString()).then((_) {
        setState(() {
          _gpxSaved = true;
        });
      });
    }

```

And then in the Download folder of my device, the file is correctly written and does not return a permission denied error anymore. :ok_hand: 


I'm kinda curious why the permission handler fixed the thing because the permission to write to the device was already managed by the FilePicker package, and no additional dialog has been shown after the permission_handler addition. :thinking: 

But anyway, it's now working, I hope that could help you to solve the problem. :+1:

**Comment by vauvenal5** [comment]
I believe this has not actually been solved in a sustainable way.

@xmine64 pls correct me but it seems to me that your approach is more like a custom workaround then an actual fix of the issue? Since it is still not possible to explicitly request permissions for a give directory from Flutter itself?

@Tisamu which API are you targeting in your app?

**Comment by alejandrogiubel** [comment]
I have same issue. Can't write in selected path. Any update?

**Comment by Sispheor** [comment]
Same here.
Another [ref](https://github.com/Baseflow/flutter-permission-handler/issues/877#event-7071399233)

**Comment by Sispheor** [comment]
Still the perm issue

Tested with files and dicrectory
```dart
String? selectedDirectory = await FilePicker.platform.getDirectoryPath(initialDirectory: createdPath);
if (selectedDirectory == null) {
  // User canceled the picker
  return false;
}
FilePickerResult? result = await FilePicker.platform.pickFiles(allowMultiple: true, initialDirectory: createdPath);
if (result == null) {
  return false;
}
```

Here I don't pass through the return false`, meaning that the user gave the perm. But I still get the `FileSystemException`
```
Unhandled Exception: FileSystemException: Cannot open file, path = '/storage/emulated/0/Documents/SlothDay/buckets.hive' (OS Error: Permission denied, errno = 13)
```

**Comment by xmine64** [comment]
Somebody should update this library to make it compatible with Android 11.
https://developer.android.com/about/versions/11/privacy/storage

**Comment by Sispheor** [comment]
@xmine64 I tried with your proposed code but still perm issue. Even if the intent was well asking for perm on the folder.

Here it ask to select the folder
![Screenshot_20220728-222534_Files](https://user-images.githubusercontent.com/2573405/181631160-b3fbecc9-881a-4423-a615-ed69e8ef4d25.jpg)

Here it ask for write perm
![Screenshot_20220728-222545_Files](https://user-images.githubusercontent.com/2573405/181631189-9420eac0-27f0-4afc-98d7-b7ea7a568ac8.jpg)


But still....
```
E/flutter (20838): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: Cannot open file, path = '/storage/emulated/0/Documents/SlothDay/buckets.hive' (OS Error: Permission denied, errno = 13)
```

I thing I'll publish my app without this feature and I'll see later if a lib finally propose a solution for that.

**Comment by brightseagit** [comment]
I know it's closed but I'm writing this for those who are still stuck. I have successfully resolved this issue **without any requirement of permission** from the user's device through my package.

It's not an advertisement for my package as my package is too small and only supports android(Android 5.0 and later), it doesn't come anywhere near file_picker but it's an attempt to solve this specific issue for the time being.

If anyone wants to save single and multiple files in android then give a try to my package [pick_or_save](https://pub.dev/packages/pick_or_save) which is heavily inspired by flutter_file_dialog.

With [pick_or_save](https://pub.dev/packages/pick_or_save) when saving multiple files you can allow users to choose a directory where you want files to be saved and for saving single files you can allow users to choose a location and file name.

Just like others, I have struggled with this issue for more than 1 year but due to my lack of knowledge in Android and Kotlin and being very new to flutter I was unable to solve it up until now. So, I hope it helps someone like me out there.

Thank you.

**Comment by brightseagit** [comment]
I know it's closed but I'm writing this for those who are still stuck. I have successfully resolved this issue without any requirement of permission from the user's device through my package.

It's not an advertisement for my package as my package is too small and only supports android(Android 5.0 and later), it doesn't come anywhere near file_picker but it's an attempt to solve this specific issue for the time being.

If anyone wants to save single and multiple files in android then give a try to my package [pick_or_save](https://pub.dev/packages/pick_or_save) which is heavily inspired by flutter_file_dialog.

With [pick_or_save](https://pub.dev/packages/pick_or_save) when saving multiple files you can allow users to choose a directory where you want files to be saved and for saving single files you can allow users to choose a location and file name.

Just like others, I have struggled with this issue for more than 1 year but due to my lack of knowledge in Android and Kotlin and being very new to flutter I was unable to solve it up until now. So, I hope it helps someone like me out there.

Thank you.
