### ISSUE TITLE
File Picker not working 

### ISSUE THREAD

**Issue by SalishKumar** [miguelpruivo/flutter_file_picker#722]
I am using latest version "3.0.1" but its not working. i have attached the console ouput.

Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/macbook/Desktop/freelannce/darat_app/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by miguelpruivo** [comment]
Hi, this is because you are missing some configs on your Android project. Check [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-2) how to properly update your gradle to support the `<queries>` tag.
