### ISSUE TITLE
Directory path returns '/' instead of directory

### ISSUE THREAD

**Issue by adrifcastr** [miguelpruivo/flutter_file_picker#724]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
On Android 9+, when selecting a directory with `getDirectoryPath()` the path will return as `/` instead of an actual path. This is very prominent on Android 10, happens occasionally on Android 9

**Platform**
- [x] Android

**Platform OS version**
What version did it happen?
10/9
**How are you picking?**
```dart
 final path = await FilePicker.platform.getDirectoryPath();
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.
Pick a folder, log the result to your console
**Error Log**
Please, post the _full_ console log of your issue, if applicable.
```
D/FilePickerDelegate(31368): [SingleFilePick] File URI:content://com.android.providers.downloads.documents/tree/downloads/document/downloads
I/flutter (31368): FGBGType.foreground
D/EGL_emulation(31368): eglMakeCurrent: 0xdca8f840: ver 2 0 (tinfo 0xdc4d3050)
I/flutter (31368): DIRECTORY /
```
**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-DE)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 90.0.818.66
```
**Additional context**
On Android 9 this only happens when picking the default 'Downloads' directory that opens, on Android 10 this applies to every directory.

**Comment by miguelpruivo** [comment]
Hi, this is described on the Wiki [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-7).

It's actually working as intended, since there are a couple of protected directories, which Downloads is one of those.
