### ISSUE TITLE
Bug with FileType.custom doesn't allow to set allowedExtensions

### ISSUE THREAD

**Issue by eliseiml** [miguelpruivo/flutter_file_picker#725]
**Describe the bug**
Combination of the `type: FileType.custom` and `allowedExtensions` parameters throws the following exception: 
> _Exception (Exception: You are setting a type [FileType.custom]. Custom extension filters are only allowed with FileType.custom, please change it or remove filters.)

This exception actually means that I'm using FileType.custom when I have to use FileType.custom.
I'm just using code example from docs:
`FilePickerResult result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf', 'txt'],
        allowMultiple: true);`

![Снимок экрана 2021-05-26 в 11 36 04](https://user-images.githubusercontent.com/33155612/119631716-d52e3580-be18-11eb-95a9-59d93dfef90c.png)

I guess the problem is located in "file_picker_io.dart" file. `FileType fileType` converts to `String type` on line 72 and then compares to `FileType.custom` on line 73. Surely in my case this expression returns `true` and trows an exception.

![Снимок экрана 2021-05-26 в 11 35 40](https://user-images.githubusercontent.com/33155612/119631106-3f92a600-be18-11eb-9dde-bb439de23a75.png)

If I remove `allowedExtensions` from `pickFiles()` calling - it works fine.
I tested in on Android emulator only but I think it will work the same way on any platform.

**Platform**
- [+] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Comment by huylethanh** [comment]
yeah. I got the same issue. Just did a debug and see the mistake like @eliseiml found. the type is string ("custom"). please fix it.

**Comment by godwintrav** [comment]
Yes please I am also having the same issue.

**Comment by miguelpruivo** [comment]
Yes, this is a regression. I'll publish a quick fix in a few minutes.
