### ISSUE TITLE
 You are setting a type [FileType.custom]. Custom extension filters are only allowed with FileType.custom, please change it or remove filters.

### ISSUE THREAD

**Issue by 97loser** [miguelpruivo/flutter_file_picker#726]
Hello,
  I have an issue with the updated version (3.0.2).
  what have I tried?
  
  FilePickerResult result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
      allowedExtensions: ['jpg', 'pdf', 'doc','jpeg'],
      allowMultiple: false
    );

**Comment by miguelpruivo** [comment]
Hi, this regression was fixed a few minutes ago with `3.0.2+1`. Dup of #725.

Sorry for any inconvenience.
