### ISSUE TITLE
Cannot pick pictures and videos on iOS devices

### ISSUE THREAD

**Issue by LSG-6** [miguelpruivo/flutter_file_picker#731]
On Android devices, when I use the following method, I can achieve my goal.
FilePicker.getMultiFile(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png', 'jpeg', 'mp4', 'avi', 'mov'],
    );
However, on iOS devices, I cannot access any pictures or videos in my album by this method.
By the way, I'm using Version 1.9.0. Has this problem been fixed in newer versions?

**Comment by miguelpruivo** [comment]
Hi, you can actually can. On iOS it works differently, to access the media files from the camera roll you need to use `FileType.image`, `FileType.video` or `FileType.media`. In your case, you want the `FileType.media`. You can't specify formats of files from camera roll, only from the Files app (when using custom types).

You can read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/api).
