### ISSUE TITLE
getDirectoryPath function always return '/' 

### ISSUE THREAD

**Issue by Bravo2x** [miguelpruivo/flutter_file_picker#732]
getDirectoryPath function always return '/' tried onGalaxy Tab S6 Lite  1 devices and emulator 

**Platform**
- [✓] Android
- [] iOS
- [] Web
- [] Desktop (Go)

  pathToSave = await FilePicker.platform.getDirectoryPath();

**Flutter Version details**
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.0.1 20B50 darwin-x64, locale en-UA)
    • Flutter version 2.2.1 at /Users/andreybraverman/flutter/flutter
    • Framework revision 02c026b03c (18 hours ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/andreybraverman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = /Users/andreybraverman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • SM P610 (mobile) • R52N90AJB1E • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 91.0.4472.77 beta

• No issues found!

**Comment by miguelpruivo** [comment]
Hi, this has been discussed multiple times in other issues. Some directories are protected, hence you can't write directly on them, check [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-7) more info.

Sorry for any inconvenience.
