### ISSUE TITLE
How to retrieve lost data in Android when it kills the MainActivity?

### ISSUE THREAD

**Issue by letsar** [miguelpruivo/flutter_file_picker#733]
Sorry if this has already been asked, I searched, but I didn't find something related to what I'm looking for.

For the moment I use https://pub.dev/packages/image_picker to get images from the user gallery, but I want the user to be able to open any file. So this package seems to fit my needs. However, on Android if the flutter activity is killed  after the user confirmed their selection, I don't know how to get these files.

image_picker has a retrieveLostData method to get this kind of things (https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android). Does this package has something related to this feature?

**Comment by miguelpruivo** [comment]
Hi @letsar, I believe there is a pending PR regarding this, however, it’s been a while and I believe it may need to be redone.

Currently there isn’t such feature, but it should be added.
