### ISSUE TITLE
Cannot run gradle sync in android studio because deprecated settings

### ISSUE THREAD

**Issue by hafizhrf** [miguelpruivo/flutter_file_picker#734]
**Describe the bug**
i want to use custom java library with platform channel, when i sync gradle files, this error popped out and crash the gradle sync, because of that i can't use snippet & autocomplete, any suggestion? 
i'm facing this error in my gradle.properties too, and comment this code fixed it
```android.enableR8=true```

**Platform**
- [] Android

**Details to reproduce the issue**
sync gradle

**Error Log**
```
The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Affected Modules: file_picker
```

**Flutter Version details**
2.2.0

**Screenshots and/or video**
<img width="1162" alt="Screen Shot 2021-05-31 at 15 47 45" src="https://user-images.githubusercontent.com/52806525/120170433-267c6180-c22b-11eb-989f-307ded168969.png">

**Comment by miguelpruivo** [comment]
Hi, this is just a warning telling that after Gradle 5.0 R8 will _always_ be enabled by default even If the user sets it to `false` manually, hence this warning has no effect at all in this project, other than being displayed.

I may remove it in a future update, but since a lot of people can be using lower gradle versions, it should be there to ensure R8 is enabled.

**Comment by vishu24vjr** [comment]
Hey!
because of this problem 'generate signed apk/app bundle' in build doesn't show

**Comment by miguelpruivo** [comment]
@vishu24vjr sorry I didn’t understand you.

**Comment by HoustonMuzamhindo** [comment]
It seems Build is failing because it keeps bringing up the error but do not know where it is located. Deleted it in the gradle.properties file but it keeps coming up with that error.

**Comment by cosminstoinescu** [comment]
hello, have you manage to resolve this problem?

**Comment by jansvanda** [comment]
why is this closed? i have the same problem

**Comment by miguelpruivo** [comment]
It's highly unlikely that this has to do with the plugin, otherwise no most people wouldn't be able to build.

**Comment by jansvanda** [comment]
Sorry, i thought I was in the official flutter repo.
