### ISSUE TITLE
Add compression/quality level params

### ISSUE THREAD

**Issue by SebastienBtr** [miguelpruivo/flutter_file_picker#735]
It would be nice to have some params to choose a desired image quality or compression level on picked medias, the same way it is done on `image_picker` package with the `imageQuality` param

**Comment by miguelpruivo** [comment]
@SebastienBtr you actually have it with `allowCompression` flag. Have in mind that `imageQuality` param in the image_picker applies mostly for camera shots which this plugin doesn’t have, hence, it may not have any purpose.

**Comment by SebastienBtr** [comment]
@miguelpruivo Yes I know there is `allowCompression` but we have no option to control it and choose how much we want to compress and willing to lose in quality. And `imageQuality` on image_picker applies really well when selecting images in the gallery, you can easily choose the value that makes sense for your use case. For me, it totally makes sense to have the same feature in this package

**Comment by dernoun** [comment]
@miguelpruivo  This feature is really wanted specially when we pick and upload an image to the web, it will reduce the image size without loosing the quality and also reduce the upload time.

**Comment by SebastienBtr** [comment]
@miguelpruivo I believe this issue should not be closed

**Comment by eldarkk** [comment]
compression control is needed guys please (at least for images from Gallery)

**Comment by miguelpruivo** [comment]
Sorry, I don't have any ETA for this as I've been a bit busy lately. I'll take a look whenever I can.

**Comment by riveraj33** [comment]
Hello All. I just wanted to see if there was any movement on this? Unfortunately I don't know how to help but adding this is desperately needed. TYIA

**Comment by keanallen** [comment]
me too. I wanted that feature ;)

**Comment by skully-coder** [comment]
Yes this is needed very much

**Comment by harshitha0193** [comment]
any update on this ?

**Comment by Umar1312** [comment]
@miguelpruivo I'm working on the PR for this, but I couldn't find any usage of compression on the Android side, there is for iOS though. Am I missing something or it was never implemented on the Android Side. 

Thanks

**Comment by miguelruivo** [comment]
Hi @Umar1312 yes it’s only on the iOS side.

**Comment by miguelpruivo** [comment]
Hi @Umar1312 yes it’s only in the iOS side.

**Comment by Umar1312** [comment]
https://github.com/miguelpruivo/flutter_file_picker/pull/1426 
@miguelpruivo

**Comment by miguelpruivo** [comment]
Merged. Closed. Thanks!
