### ISSUE TITLE
File picker is already active

### ISSUE THREAD

**Issue by Shakhboz95** [miguelpruivo/flutter_file_picker#736]
Sometimes picking files will not work. I don't know when. 1-2 times it works, after that stops working and shows this error:

I/flutter (25833): [MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null, null)
E/flutter (25833): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(already_active, File picker is already active, null, null)

is there any solution for this?

**Comment by miguelpruivo** [comment]
Hi, I need more details on how to replicate this.

**Comment by Shakhboz95** [comment]
```
     chooseZipFile({bool` isUpdate = false, int index}) async {
        var result = await FilePicker.platform.pickFiles(
        type: FileType.custom, allowedExtensions: ["doc", "xls", "pdf", "zip"]);

    if (result != null) {
      File file = File(result.files.single.path);
      int sizeInBytes = file.lengthSync();
      double sizeInMb = sizeInBytes / (1024 * 1024);
      print("file name:  " + result.files.first.name);
      if (sizeInMb > 5) {
        ToastUtils.toastErrorGeneral("file size is exceeded", _context);
      } else {
        if (isUpdate) {
          _zipTitle[index] = (result.files.first.name);
          _zipChosen[index] = true;
        } else {
          _zipTitle.add(result.files.first.name);
          _zipChosen.add(true);
        }
        notifyListeners();
      }
      // file.
    } else {
      // User canceled the picker

    }
  }
```
  
  
  Here is the code. The logic is Users can pick another file if they need after one file.

**Comment by dala00** [comment]
I got same message on Android & file_picker: 2.1.7. But may be not same way of this issue.
I called pickFiles and disallow permission and pickFiles again.

**Comment by miguelpruivo** [comment]
Does the issue applies to iOS or Android?

**Comment by Shakhboz95** [comment]
Unfortunately, I dont have any info about this issue on IOS, I tested it only on android platform, 3 devices displayed this error

**Comment by indrajit-roy** [comment]
Facing the same issue in file_picker: 2.1.7. Using the demo app, it seems like, just on the release version, the Future,

 (await FilePicker.platform.pickFiles(
        type: _pickingType,
        allowMultiple: _multiPick,
        allowedExtensions: (_extension?.isNotEmpty ?? false)
            ? _extension?.replaceAll(' ', '').split(',')
            : null,
      ))

does not complete and the Circular Progress Indicator keeps spinning.

This does not happen in debug. Only on release and build apk.

My device is the Samsung S10 lite, API 30. flutter version 2.0.5.

**Comment by miguelpruivo** [comment]
Ok, thank you for the input. I’ll have to replicate it on release, might be related.

**Comment by Pato05** [comment]
I am experiencing the same problem also on debug builds, it seems like the `FilePicker.platform.pickFiles()` future never completes..

**Comment by sumanwebidigital** [comment]
It is still not working, when I install app for first time.

**Comment by miguelpruivo** [comment]
@Pato05 this is one of those issues that some have it some don't and without easy way to replicate it, hence, this make me believe that could be user-implementation related — like it happened to you.

**Comment by miguelpruivo** [comment]
Closing since this likely is related to the app's implementation that is requesting multiple pickers before closing the previous one.

**Comment by fryyd** [comment]
You can replicate this on iOS by having `allowCompression: true`, then pick a large file (the file i picked was hevc encoded). While this process is running, call the `FilePicker.platform.pickFiles` method again, and this time the error will be thrown:
`I/flutter (25833): [MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null, null)`

**Comment by lore-co** [comment]
Problem is still there and happens lot of times

**Comment by CodeHiSmile** [comment]
https://github.com/CodeHiSmile/demo_error_file_picker @miguelpruivo you can get my code. I don't choose file when add library fluttertoast: ^8.0.9 in project. I need support. Thank you very much!

**Comment by CodeHiSmile** [comment]
![image](https://user-images.githubusercontent.com/59526085/166898329-15df659b-ff76-4b7c-a05a-3d5b8afe5292.png)

**Comment by aucshow-wjb** [comment]
The issue already happened many times to me.... not ended yet.

**Comment by tuckerww** [comment]
> Closing since this likely is related to the app's implementation that is requesting multiple pickers before closing the previous one.

There is no provided method anywhere to actually close filePickers, as far as I can tell.  As soon as one throws an AbortError, no further filePickers can be used.  If there's a way to close them, please let me know :)

**Comment by ElHyperion** [comment]
This issue is still there, I just got this report to Crashlytics:
```Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(already_active, File picker is already active, null, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:648)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at MethodChannel.invokeListMethod(platform_channel.dart:520)
       at FilePickerIO._getPath(file_picker_io.dart:103)
       at ModelsController.onImportTap.<fn>(models_controller.dart:138)
       at ModelsView.build.<fn>.<fn>.<fn>(models_view.dart:64)
```
My app code is simply doing ``FilePicker.platform.pickFiles().then((result) async { ...`` which the line :138 points to, so I have no idea how to handle this issue. Apparently it even caused a crash, as it's a fatal issue.
