### ISSUE TITLE
file_picker 2.1.7-3.0.2+2 multi picking not working in folder "Gallery" on Android 10 and Emulator API Level 28

### ISSUE THREAD

**Issue by jens-coding** [miguelpruivo/flutter_file_picker#737]
**Describe the bug**
file_picker 2.1.7 multi picking not working in folder "Gallery" on Android 10 and Emulator API Level 28.

**Platform**
- [x] Android (including emulator on api level 28)
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
1. Android SDK built for x86 64 in debug mode with emulator on api level 28
2. Samsung xcover 3, SM-G398FN, Android 10

**How are you picking?**
```
Click the 3 bars on the top left corner, click on Gallery (Galerie on german devices), try to select multiple elements not working.
```

**Details to reproduce the issue**

1. FileType.custom, 
2. Click the 3 bars, click on Gallery (Galerie on german devices) try to select multiple elements not working.

**Error Log**
No errors thrown.

**Screenshots and/or video**
![gallery_folder_emulator](https://user-images.githubusercontent.com/16591362/120497618-d930f900-c3be-11eb-9dd5-49ca4f5505e8.png)

**Flutter Version details**
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.985], locale de-DE)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (3 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:/Users/jens/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\jens\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!

**Additional context**
|-- file_picker 2.1.7
|   |-- flutter...
|   |-- flutter_plugin_android_lifecycle 1.0.11
|   |   '-- flutter...
|   |-- flutter_web_plugins...
|   '-- plugin_platform_interface 1.0.2
|       '-- meta...

**Comment by jens-coding** [comment]
Same problem for file_picker 3.0.2+2 on Target Android 9.0 / API Level 28:

|-- file_picker 3.0.2+2
|   |-- flutter...
|   |-- flutter_plugin_android_lifecycle 2.0.2
|   |   '-- flutter...
|   |-- flutter_web_plugins...
|   '-- plugin_platform_interface 2.0.0
|       '-- meta...

**Comment by jens-coding** [comment]
SO https://stackoverflow.com/questions/19585815/select-multiple-images-from-android-gallery
"Ther is no multi select in the native gallery, but you can do it with this library: " https://github.com/luminousman/MultipleImagePick

**Comment by miguelpruivo** [comment]
@jens-coding one of the main features and purposes of this lib is to strictly follow the native guidelines and default pickers. I know that it can have some limitations for some features based on some versions (like is happening to you) but I rather have those than mixing 3rd party libraries with custom UIs. I hope you understand.

Nevertheless, I find it weird that this is the first time that someone reports that there are a version that doesn’t support multiple selection. What if you try in a different device/OS?

**Comment by jens-coding** [comment]
@miguelpruivo this problem doesnt occur on Android 11. 

Got to change my app logic to allow repicking.

**Comment by miguelpruivo** [comment]
So, is this solved?

**Comment by jens-coding** [comment]
Yes, solved due native guidelines and default pickers not supporting multipciking of certain folders on API Level <=28.
