### ISSUE TITLE
Some file extensions missing

### ISSUE THREAD

**Issue by zhukeev** [miguelpruivo/flutter_file_picker#740]
**Some files don't have an extension but **
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**
- [X] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
Android 9, Xiaomi Note 5

**How are you picking?**
```
 void openFilePicker() async {
    if (await Permission.storage.isGranted) {
      final filePicker = await FilePicker.platform.pickFiles(
        type: FileType.any,
        allowMultiple: false,
      );
      final pickedFile = filePicker?.files?.first;

      print('picked file' '${pickedFile?.path}');

      if (pickedFile == null) return;
      setState(() {
        isLoading = true;
      });

      await uploadFileToCC(File(pickedFile.path));
    } else {
      final status = await Permission.storage.request();
      if (status == PermissionStatus.granted) {
        openFilePicker();
      }
    }
  }
```

**Details to reproduce the issue**
Just open picker and try to choose for example audio (in audio section) (it gives without en extension)

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
[video](https://drive.google.com/drive/folders/1861mxyG1pcWRdBVIeauYHOEEfh0XQH20?usp=sharing)

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, what's the issue? I saw the videos, but didn't get it.

**Comment by zhukeev** [comment]
@miguelpruivo Sometimes it's not returning file extension

**Comment by miguelpruivo** [comment]
@zhukeev some files may not have an extension. Make sure the file name does. The extension is retrieved from the file name.

**Comment by zhukeev** [comment]
@miguelpruivo That file had an extension. In that videos I show different approach to exact the file, from downloads and from recents. It is the exact same file but file picker behaves differently, please try to reproduce it

**Comment by miguelpruivo** [comment]
@zhukeev the extension is always extracted from the file name. If for some reason the file name isn’t resolved with an extension, it won’t work.

Please provide me with a sample and a file that you know you’re experiencing this issue with so I can easily dig down the problem, otherwise it won’t be easy. Might be device related.

**Comment by zhukeev** [comment]
I attached the link with two videos where I picked the same file in two different ways. In one video reached the music file from downloads(it was downloads) and it gives WITHOUT extension (You can notice that It shows an error if there's no extension). In another video I reached the file from Audio Item in drawer menu and it gives WITH extension;

**Comment by devibrahimkarahan** [comment]
This issue should be reopened, i got same error with this path "/data/user/0/package_id/cache/file_picker/Maluma, The Weeknd - Hawái (Remix - Official Video)" but in file explorer i can see Maluma, The Weeknd - Hawái (Remix - Official Video).mp3

**Comment by miguelpruivo** [comment]
Are you able to reproduce the file nevertheless?
