### ISSUE TITLE
Getting original path of the file

### ISSUE THREAD

**Issue by Dev-vamsidhar** [miguelpruivo/flutter_file_picker#741]
How to get original path of the file instead of cached file.Let me know is it possible or not .Trying a lot for this funtion from few days

**Comment by miguelpruivo** [comment]
Hi, this has been described multiple times. This is not possible since SDK 30 on Android. You can read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

Sorry for any inconvenience.
