### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by majdew** [miguelpruivo/flutter_file_picker#743]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_file_picker-1.2.0-nullsafety.0/lib/src/form_builder_file_picker.dart:161:36: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
          allowCompression: widget.allowCompression,
                                   ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_file_picker-1.2.0-nullsafety.0/lib/src/form_builder_file_picker.dart:242:38: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
                        files[index].name!,
                                     ^

**Comment by miguelpruivo** [comment]
Hi, you'll need to have null safety support in your project or use a version without it.
