### ISSUE TITLE
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

### ISSUE THREAD

**Issue by janithcooray** [miguelpruivo/flutter_file_picker#744]
when Running on Desktop. I get this error when opening the relevant class where the file pickinf code exists.

flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

I did flutter clean` and `flutter build. Nothing Changed!

Crashes the linux desktop debug  session with the error :
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

But when I run the project as web it Works!

**Platform**
- [] Web
- [] Desktop (Go)

**Platform OS version**
KDE Plasma 5.19 (Kernel Linux 5.10.7-3)

Code:
`FilePickerResult? result = await FilePicker.platform.pickFiles();`
Steps to reproduce:

> Run on Linux in debug mode
> Open Window with File Picker Code

**Error Log**
Connecting to VM Service at ws://127.0.0.1:33699/Ub3PnlkUvOI=/ws
flutter: [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
Application finished.
![image](https://user-images.githubusercontent.com/50979590/121820448-6e31cd00-ccb0-11eb-8900-3d1a5bd11245.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/50979590/121820469-8efa2280-ccb0-11eb-9604-668e93d0f7ca.png)

**Flutter Version details**
flutter doctor -v

**File Picker Version**
file_picker: ^3.0.2+2

> [✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_GB.UTF-8)
>     • Flutter version 2.2.1 at /home/nova/snap/flutter/common/flutter
>     • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
>     • Engine revision 0fdb562ac8
>     • Dart version 2.13.1
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
>     • Android SDK at /home/nova/Android/Sdk
>     • Platform android-30, build-tools 30.0.1
>     • Java binary at: /home/nova/Global/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
>     • cmake version 3.10.2
>     • ninja version 1.8.2
>     • pkg-config version 0.29.1
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /home/nova/Global/android-studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] IntelliJ IDEA Community Edition (version 2020.2)
>     • IntelliJ at /usr/share/idea
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] Connected device (1 available)
>     • Linux (desktop) • linux • linux-x64 • Linux
> 
> ! Doctor found issues in 2 categories.

**Additional context**
Only Occurs when on Linux-debug
Does not Occur in Web (Works fine)

I checked a few issues with the same error in this repo. but most of them are solved after cleaning and rebuilding the project. mine did not. I'm guessing it's a platform related issue.

**Comment by malviys** [comment]
[MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: Unsupported operation: Platform._operatingSystem.

Getting this error on Google Chrome but work properly on Microsoft Edge.

Operating system: Windows 10 x64
Platform: Web

**Comment by janithcooray** [comment]
> [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: Unsupported operation: Platform._operatingSystem.
> 
> Getting this error on Google Chrome but work properly on Microsoft Edge.
> 
> Operating system: Windows 10 x64
> Platform: Web

It works fine for me in Win 10 x64 on Chrome Version 91.0.4472.77 (Official Build) (64-bit).
also works fine for me in Linux 5.10 Manjaro on Chrom Version 81.~

did you try flutter clean & build ?

**Comment by malviys** [comment]
> > [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: Unsupported operation: Platform._operatingSystem.
> > Getting this error on Google Chrome but work properly on Microsoft Edge.
> > Operating system: Windows 10 x64
> > Platform: Web
> 
> It works fine for me in Win 10 x64 on Chrome Version 91.0.4472.77 (Official Build) (64-bit).
> also works fine for me in Linux 5.10 Manjaro on Chrom Version 81.~
> 
> did you try flutter clean & build ?

Thanks @janithcooray I tried cleaning and build it worked on next run.

**Comment by janithcooray** [comment]
The issue was closed without any info or how to fix it. ?

**Comment by miguelpruivo** [comment]
@janithcooray sorry my bad. I rad that someone managed to fix it and assumed that it was solved for you as well. Is this still an issue?

**Comment by janithcooray** [comment]
> @janithcooray sorry my bad. I rad that someone managed to fix it and assumed that it was solved for you as well. Is this still an issue?

One user got his problem fixed on the web platform. this issue is regarding the desktop.

**Comment by ed-mota-teixeira** [comment]
@janithcooray I had the same issue issue, but regarding Android (emulator). `Flutter clean` solved the problem.

**Comment by miguelpruivo** [comment]
@janithcooray native desktop isn’t supported by the plugin. Only through Flutter GO.
