### ISSUE TITLE
[Android] - Can pick any file type even I use *allowedExtensions*

### ISSUE THREAD

**Issue by damienissa** [miguelpruivo/flutter_file_picker#755]
**Describe the bug**
There is the ability to choose any file type on Android devices even I use *allowedExtensions*

**Platform**
- [android-arm64  • Android 10 (API 29)] Android

**How are you picking?**
``` 
    final result = await FilePicker.platform
        .pickFiles(type: FileType.custom, allowedExtensions: [
      'jpeg',
      'jpg',
      'png',
      'tif',
      if (Platform.isIOS) 'tiff',
      'pdf',
    ]);
```

**Details to reproduce the issue**
My files > More > Audio > Select *mp3*

**Error Log**
D/FilePickerUtils( 3263): File loaded and cached at:/data/user/0/**************/cache/file_picker/sultan_laguchev_-_mezhdu_nami_vojna_(z2.fm).mp3
D/FilePickerDelegate( 3263): File path:[com.mr.flutter.plugin.filepicker.FileInfo@3bf3d2c]

**Screenshots and/or video**
![photo_2021-06-23 16 10 25](https://user-images.githubusercontent.com/17296142/123102361-a5854400-d43d-11eb-949f-ef0c276f7f18.jpeg)
![photo_2021-06-23 16 10 28](https://user-images.githubusercontent.com/17296142/123102379-aa49f800-d43d-11eb-832d-0302ee6e5234.jpeg)

**Flutter Version details**
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.2 20D80 darwin-x64, locale en-UA)
    • Flutter version 2.2.2 at /Users/dmitryvirych/flutter
    • Framework revision d79295af24 (12 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dmitryvirych/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • M2004J19C (mobile)         • 3f5d07ae0408                         • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • AA93B11B-1DE5-4101-BB6D-9F42CAE3EDB6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, this is a known limitation. Check [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4). Unfortunately there isn’t much to be done here.

I’m sorry for any inconvenience.
