### ISSUE TITLE
Allowed csv extension greyed out on Google Drive

### ISSUE THREAD

**Issue by DavidAriza** [miguelpruivo/flutter_file_picker#760]
First of all I need to mention that I'm using file_picker 2.1.7 because the project hasn't been migrated to Flutter 2.0. 

**Describe the bug**
I can pick csv files from device storage, however when it comes to Google Drive, all files are greyed out. 

**Platform**
- Android - Xiaomi Redmi Note 8 Pro

**How are you picking?**
`FilePickerResult result = await FilePicker.platform.pickFiles( type: FileType.custom, allowedExtensions: ['csv']);`

**Screenshots and/or video**
![image](https://user-images.githubusercontent.com/42550598/123988188-6ac76280-d98d-11eb-8dc8-347e6aee02d4.png)

**Flutter Version details**
Flutter 1.22.6

**Comment by miguelpruivo** [comment]
Hi, csv extension is one of the known extensions that for some reason can’t be properly resolved by the OS as a valid MIME.

There is nothing I can do here. You’ll need to switch the type to `FileType.all` and discard all but the csv files after picking.

Sorry for any inconvenience.
