### ISSUE TITLE
Android release build crashing 

### ISSUE THREAD

**Issue by rashmisridar** [miguelpruivo/flutter_file_picker#767]
While picking the pdf document file picker crashing in android

**Comment by miguelpruivo** [comment]
Hi. I need more details… is this still an issue?

**Comment by rashmisridar** [comment]
After adding this line in proguard-rules issue was resolved.  I think it's better to add in the document also 
 -keep class com.shockwave.**  . Thanks

**Comment by miguelpruivo** [comment]
@rashmisridar did that happen only with PDF files?

**Comment by rashmisridar** [comment]
@miguelpruivo  Yes
