### ISSUE TITLE
Use showOpenFilePicker() first in the web

### ISSUE THREAD

**Issue by chentianxin** [miguelpruivo/flutter_file_picker#770]
use ***[showOpenFilePicker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker)*** first in the web
This api can monitor the user to cancel the selection, I think it can be used first, if this api is not supported, consider switching to ```<input type="file"/>``` to select the file

**Comment by miguelpruivo** [comment]
This should resolve #756.

**Comment by miguelpruivo** [comment]
@chentianxin this doesn't seem to be available on dart:html, AFAIK.
