### ISSUE TITLE
iOS - Not able to pick RSA token file with extension 'sdtid' 

### ISSUE THREAD

**Issue by vim1486** [miguelpruivo/flutter_file_picker#773]
FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['sdtid'],
    );
    if (result != null) {
      file = result.files.first;
      return file;
    }
![testRSATokenImport](https://user-images.githubusercontent.com/2766891/126185441-fb2b7c4e-6c6e-4495-a2b6-da22cedd1b11.jpeg)

iPhone 11 (iOS - 14.4)
Same code works well for Android.

Error receive while picking .sdtid file 
***** [Skipping type] Unsupported file type: dyn.age81g3dyrfwa
* +[FileUtils resolveType:withAllowedExtensions:]

Solution works for .pdf files
***** Custom file type supported: com.adobe.pdf
* +[FileUtils resolveType:withAllowedExtensions:] [Line 59]

Flutter Details   
MacBook-Pro ~ % flutter doctor      
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

• No issues found!

**Comment by miguelpruivo** [comment]
Hi, unfortunately this happens because the file extension can’t be resolved to a valid MIME/UTI. It’s a platform limitation.

You’ll need to allow all types by choosing `FileType.all` and then manually discard all non RSA files (you can iterate after picking and check the extension).

I’m sorry for any inconvenience.

**Comment by vim1486** [comment]
> Hi, unfortunately this happens because the file extension can’t be resolved to a valid MIME/UTI. It’s a platform limitation.
> 
> You’ll need to allow all types by choosing `FileType.all` and then manually discard all non RSA files (you can iterate after picking and check the extension).
> 
> I’m sorry for any inconvenience.

Thanks, it worked.
