### ISSUE TITLE
[MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null, null)

### ISSUE THREAD

**Issue by topjx** [miguelpruivo/flutter_file_picker#775]
- [] Android

 FilePickerResult result = await FilePicker.platform.pickFiles();
        if(result != null) {
          File file = File(result.files.single.path);
        } else {
          // User canceled the picker
        }

Open File Manager for the first time

The second time it won't open and an error is reported

[MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null, null)

**Comment by miguelpruivo** [comment]
Dup of #736.
