### ISSUE TITLE
Can i get the original path of the images?

### ISSUE THREAD

**Issue by MimiBoo** [miguelpruivo/flutter_file_picker#776]
Hi I'm working on a project and I need to get the list of paths to the selected images, so I was wondering if there is a way to do it using file picker? and thanks in advanced

**Comment by miguelpruivo** [comment]
Hi, yes you can access the `path` property of each `PlatformFile`.

**Comment by MimiBoo** [comment]
> Hi, yes you can access the `path` property of each `PlatformFile`.
> 
> You may want to take a look at the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki) for the full documentation.

but that path is for the cashed images not the original location of the image

**Comment by miguelpruivo** [comment]
@MimiBoo you can't get the original path for integrity reasons. On iOS was never possible and on Android it was only possible to retrieve the original path until SDK 30. That's described on the [FAQ](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ) as well.

**Comment by Jakuzeisme** [comment]
@MimiBoo 
Pls did you find a workaround for this?

**Comment by mimib00** [comment]
Nope sorry
