### ISSUE TITLE
File picker crashes on M1 Mac

### ISSUE THREAD

**Issue by NZhlebinkov** [miguelpruivo/flutter_file_picker#778]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

**Describe the bug**
When trying to pick a file, the app crashes.

**Platform**
- [] Android
- [x] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
14.4

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform
        .pickFiles(type: FileType.custom, allowedExtensions: ['xlsx']);
```

**Details to reproduce the issue**
Add the code snippet from above to any place in the code and observe that as soon as it's executed the app crashes.
It doesn't happen to my colleagues so it's likely connected to my laptop having an M1 chip.

**Error Log**
```
 final List<Map>? result = await _channel.invokeListMethod(type, {
        'allowMultipleSelection': allowMultipleSelection,
        'allowedExtensions': allowedExtensions,
        'allowCompression': allowCompression,
        'withData': withData,
      });

```
in `file_picker_io.dart` is where the app crashes when I go in with the debugger.

**Flutter Version details**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.1 20D74 darwin-arm, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/lionbrunch/Development/Flutter/flutter_SDK
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lionbrunch/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Edward's (mobile) • C253F3BC-39D9-42F0-A0EA-BF941DDCE029 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)      • chrome                               • web-javascript
      • Google Chrome 92.0.4515.107

• No issues found!

**Additional context**
I'm on an M1 mac.

**Comment by miguelpruivo** [comment]
Does that happen on a real device?

**Comment by slorop41314** [comment]
Same issue with me, only happen on simulator with type Custom, works fine on real device

**Comment by miguelpruivo** [comment]
This seems to be an issue related with simulators build on M1, shouldn't impact real devices and it's probably happening as well when implementing native code (despite Flutter). For that reason, I'll assume there isn't anything to do on the plugin side. If this is still an issue after a few xcode updates, let me know so we can further investigate this.

Thank you.

**Comment by SwissCheese5** [comment]
This happens on a macos window for me as well. (M1)

**Comment by tannermeade** [comment]
This is an issue for me on the M1.

**Comment by StefanRademakers** [comment]
Same here, FilePicker sometimes crashes on M1 Mac.... sort of a show stopper.
