### ISSUE TITLE
Custom File Type CSV not support in Android

### ISSUE THREAD

**Issue by RasikDasinfomedia** [miguelpruivo/flutter_file_picker#782]
**Platform**
- [] Android
![image](https://user-images.githubusercontent.com/61238070/127470133-2ac7f171-7be4-4e73-bfce-f4b673015ada.png)

**Comment by miguelpruivo** [comment]
Hi, CSV is one of the file types that the OS can't support as a filter, it's a limitation. [See here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4). I recommend you to allow all types and then after picking iterate through all of them by checking the `extension` property and whitelist only those that fit your needs.
