### ISSUE TITLE
NSPhotoLibraryUsageDescription required for iOS even when only using FileType.custom

### ISSUE THREAD

**Issue by stephanie-finch** [miguelpruivo/flutter_file_picker#783]
TestFlight notified us that `NSPhotoLibraryUsageDescription` is required even though we only have one FilePicker call that doesn't request for photos. The documentation in https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#ios says it should only be required for image/video file types.

```
final FilePickerResult? result = await FilePicker.platform.pickFiles(
   type: FileType.custom, 
   allowedExtensions: ['zip'],
);

```

Message from TestFlight:
"ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs."

**Comment by miguelpruivo** [comment]
Hi, it seems that now devs should add the entitlements that the app (or any plugin) could attempt to use. Since the plugin uses API for accessing those features, you'll need to add it as well, however, it won't prompt a permission warning to your users unless you actually use it at runtime.
