### ISSUE TITLE
FilePickerResult is always null on Flutter Web

### ISSUE THREAD

**Issue by JRamirezSB** [miguelpruivo/flutter_file_picker#794]
**Describe the bug**
FilePickerResult is always null when I do `FilePickerResult? result = await FilePicker.platform.pickFiles();` while on Flutter Web. I have tested my code in the Android Emulator with no issue. It is Web where I am having issues. Is there something that I am missing?

Thank you.

**Platform**
- [] Android
- [] iOS
- ✔ Web
- [] Desktop (Go)

**Platform OS version**
Google Chrome
Version 92.0.4515.131 (Official Build) (64-bit)

**How are you picking?**
```
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';

class ScreenHome extends StatefulWidget {
  @override
  _ScreenHomeState createState() => _ScreenHomeState();
}

class _ScreenHomeState extends State<ScreenHome> {
  Image? mypic;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text('Screen 1', style: GoogleFonts.secularOne()),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () async {
                FilePickerResult? result =
                    await FilePicker.platform.pickFiles();

                print(result);

                if (result != null) {
                  Get.rawSnackbar(
                    message: 'You picked a file.',
                    backgroundColor: Colors.green,
                  );
                  File file = File(result.files.single.path!);

                  setState(() {
                    mypic = Image.file(file);
                  });
                } else {
                  Get.rawSnackbar(
                    message: "You did not pick a file.",
                    backgroundColor: Colors.red,
                  );
                }
              },
              child: Text('Pic File'),
            ),
            Container(
              height: 100,
              width: 100,
              child: mypic,
            ),
          ],
        ),
      ),
    );
  }
}

```

**Details to reproduce the issue**
These are the pub.dev packages in my pubspec.yaml, although I have the same problem with a new `flutter create` project.
  get:
  reactive_forms:
  file_picker:
  google_fonts:
  font_awesome_flutter:
  flutter_spinkit:
  hive:
  hive_flutter:
  equatable:

**Flutter Version details**
`[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1110], locale en-US)
    • Flutter version 2.2.3 at C:\tools\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\jramirez\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code, 64-bit edition (version 1.59.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!`

**Comment by JRamirezSB** [comment]
Yes, when picking the value of result is null and the code in the else statement is executed.

**Comment by miguelpruivo** [comment]
You’ll need to make a reproducible example. Which browser are you trying on?

**Comment by JRamirezSB** [comment]
I just tried it on another computer, and it worked like it should. The problem is not with this package, it lies somewhere else. Thank you for helping me out though.

**Comment by miguelpruivo** [comment]
No problem! Glad it's working now. Let me know if you still have any issue.

**Comment by eae1212** [comment]
This error occurs on my laptop and doesn't occur on two other comps.
My environment is :

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19041.1288], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[!] Android Studio (not installed)
[√] VS Code (version 1.61.2)
[√] Connected device (3 available)

**Chrome 95.0.4638.54**

**pubspec.yaml:**
    environment:
      sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ...
  file_picker: 4.1.6
  ...
I use FilePicker in many modules, so wrapped it in function
Future<PlatformFile> getFilePickerResult(
    {List<String> allowedExtensions = const [
      'jpg',
      'jpeg',
      'gif',
      'png'
    ]}) async {
  FilePickerResult result = await FilePicker.platform
      .pickFiles(type: FileType.custom, allowedExtensions: allowedExtensions);
  print('filepicker: ${result?.files?.single?.name}');
  return result?.files?.single;
}
During debug I recieve FilePickerResult = null

**Comment by eae1212** [comment]
After updating flutter sdk (2.5.3), FilePicker (4.2.0), Chrome (95.0.4638.69) to last versions I have the same error.

**Comment by WymanY** [comment]
I had the same problem, but on iOS by the m1 MAC emulator.
My environment is :

Sytem: m1 MacOS 12.01
Device: emulator on computer
Flutter SDK: 2.5.3 
file_picker: ^4.2.0

When i choosed video,the FilePickerResult is always null. But I used other libraries to display the results normally，liked image_picker。
