### ISSUE TITLE
E/flutter (14132): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'FilePickerResult' is not a subtype of type 'File' in type cast

### ISSUE THREAD

**Issue by vincent9725** [miguelpruivo/flutter_file_picker#795]
E/flutter (14132): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'FilePickerResult' is not a subtype of type 'File' in type cast

**Comment by miguelpruivo** [comment]
You are probably assigning the result to a `File` instance. Please, check the README file or the Wiki, you have there examples on how to use the plugin to pick files.

Thank you.
