### ISSUE TITLE
Can I use this package to get files via URI specified ?

### ISSUE THREAD

**Issue by radha1990kumari** [miguelpruivo/flutter_file_picker#796]
I have associated my app with `.foo` file type and so whenever another app (for example file manager ) gets this extension it will launch my app to view this file . I am doing this by following instructions from this : https://stackoverflow.com/questions/67064178/how-to-open-a-file-with-a-custom-file-extension-from-another-app-with-my-flutter

Is there any way I could open that file via file_picker ?

**Comment by miguelpruivo** [comment]
Hi, no. Currently there is no such way to open/filter by a custom type. However, you can pick those file types (by using `FileType.all` filter and discard anything else the user picks, by iterating the `extension` property of picked files).

**Comment by radha1990kumari** [comment]
@miguelpruivo , I think you misunderstood my question , I have a file URI (location) for example `storage/0/emulated/data.foo` and as we do in dart `File(path)` using `dart:io` ,similarly can I pass file path to open using file_picker

**Comment by miguelpruivo** [comment]
Yes, you can.
