### ISSUE TITLE
[ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it."

### ISSUE THREAD

**Issue by palarax** [miguelpruivo/flutter_file_picker#800]
file_picker: ^4.0.0

**Describe the bug**
When using pickFiles with FileType of FileType.media, to pick videos, the app either crashes or freezes.
When debugging from Xcode, the following error can be seen: 

[ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }

Another error that has been noted is:

PlatformException(multiple_request, Cancelled by a second request, null, null)

(image_picker has this problem as well, potentially related)

**Platform**
-  iOS

**Platform OS version**
iOS [iPhone] [14.7.1]

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
            type: FileType.media,
            onFileLoading: (FilePickerStatus status) {
              if (status == FilePickerStatus.picking) {
                setState(() {
                  isBusy = true;
                });
                Get.back();
              } else {
                setState(() {
                  isBusy = false;
                });
              }
            });

        if (result != null) {
          PlatformFile file = result.files.first;
          selectedPath = file.path;
        } else {
          // User canceled the picker
        }
```

**Details to reproduce the issue**
The issue happens when FileType.media is picked, and user picks a video file

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/palarax/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/palarax/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/palarax/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • MyIos (mobile)              • 00008101-0004155E2251001E            • ios            • iOS 14.7.1
    • iPad Pro (9.7-inch) (mobile) • 55A8CEC1-FBE0-4FE7-984F-9BCD21ED5D52 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

**Currently working workout**
Separating video and photo library access seems to resolve the issue.

```
 FileType fType = isImage ? FileType.image : FileType.video;
        FilePickerResult? result = await FilePicker.platform.pickFiles(
            type: fType,
            onFileLoading: (FilePickerStatus status) {
              if (status == FilePickerStatus.picking) {
                setState(() {
                  isBusy = true;
                });
                Get.back();
              } else {
                setState(() {
                  isBusy = false;
                });
              }
            });

        if (result != null) {
          PlatformFile file = result.files.first;
          selectedPath = file.path;
        } else {
          // User canceled the picker
        }
```

**Additional context**
The following permissions are requested

    Map<Permission, PermissionStatus> status =
        await [Permission.photos, Permission.mediaLibrary, Permission.photosAddOnly, Permission.storage].request();

**Comment by palarax** [comment]
> **workout**

workaround

**Comment by miguelpruivo** [comment]
Hi, this is a known "log issue" that shouldn't have any impact in the app usage or file picking. The only problem here is the
```
PlatformException(multiple_request, Cancelled by a second request, null, null)
```
Which could be triggered with multiple requests. Please, create a sample app where it can be reproduced.

**Comment by miguelpruivo** [comment]
After further investigation this seems to be related with the permission_handler, since by using the file_picker _only_ the issue doesn't happen.
