### ISSUE TITLE
Android Crash once open File-picker(by using /example codes) 

### ISSUE THREAD

**Issue by CellCS** [miguelpruivo/flutter_file_picker#801]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

The crash happens when open Google Drive or a local file folder (there are some files which size is around 25M) on Android.

Then crash happens and auto-restarts when be activated from background running. 

**Platform**
- [X] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
What version did it happen?
Android 9

**How are you picking?**
Using plugin GitHub codes miguelpruivo/flutter_file_picker

miguelpruivo/flutter_file_picker/example <br> flutter run<br>

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

1. Store some files like pdf, jpg, size is more than 25M in Google Drive, and local device storage.
2. prepare codes
```
git clone https://github.com/miguelpruivo/flutter_file_picker.git
cd flutter_file_picker/example
flutter run
```
3. Click **Open file picker** and select one pdf or image file which is larger than 25M.
4. Crash could happen
5. After this crash happen, the APP will auto-start again.  then put to run at the background, view setting or some other app, then put file-picker app activate again from running background.  The app crashes again and restart.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

```
D/FilePickerDelegate(20376): Selected type */*
Lost connection to device.
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

https://user-images.githubusercontent.com/16886624/129733639-c44a4d2d-a8e6-4ffc-ad74-ddab552c3d0c.mp4

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Please, use `adb logcat` to catch the system exception.

**Comment by AresVampire** [comment]
It crashes when picking a large amount of files, like 15 files of video.

**Comment by miguelpruivo** [comment]
How are you picking, please post it.

**Comment by AresVampire** [comment]
Yes, right. 
```
E/AndroidRuntime( 4865): java.lang.OutOfMemoryError: Failed to allocate a 10598528 byte allocation with 3632224 free bytes and 3547KB until OOM, target footprint 201326592, growth limit 201326592
E/AndroidRuntime( 4865): 	at com.mr.flutter.plugin.filepicker.FileUtils.loadData(FileUtils.java:106)
E/AndroidRuntime( 4865): 	at com.mr.flutter.plugin.filepicker.FileUtils.openFileStream(FileUtils.java:168)
E/AndroidRuntime( 4865): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:97)
E/AndroidRuntime( 4865): 	at java.lang.Thread.run(Thread.java:923)
I/io.palgo.app( 4865): Waiting for a blocking GC Alloc
```
Any solution for this?

**Comment by miguelpruivo** [comment]
Do you have `withData` set to `true`? If so, you shouldn't. That's only for very specific use cases because it will completely load all the picked files into memory instead of loading it on demand.

**Comment by mauriziopinotti** [comment]
This also happens if you turn on the "Don't keep activities" flag in the developer options.

**Comment by FaizIkhwan** [comment]
How to fix this issue? I have the same issue.

**Comment by miguelpruivo** [comment]
I'm yet to understand what the issue actually is, could someone please elaborate? Thank you.

**Comment by sz7i** [comment]
It could be related to https://github.com/miguelpruivo/flutter_file_picker/issues/1170
