### ISSUE TITLE
Should update the wiki docs

### ISSUE THREAD

**Issue by ngoluuduythai** [miguelpruivo/flutter_file_picker#805]
I encourage you to add new suggestions that you think that can make file_picker even a better package.
In currently IOS version. 
```
<key>UISupportsDocumentBrowser</key>
<bool>true</bool>
```
change to
```
<key>UISupportsDocumentBrowser</key>
<true/>
```
same with another permission:
```
        <key>UISupportsDocumentBrowser</key>
        <true/>
        <key>LSSupportsOpeningDocumentsInPlace</key>
        <true/>
        <key>LSSupportsOpeningDocumentsInPlace</key>
        <true/>
```

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

**Comment by miguelpruivo** [comment]
Thank you for the suggestion. Done!
