### ISSUE TITLE
How to pick video only from Files App in iOS

### ISSUE THREAD

**Issue by DamonChen117** [miguelpruivo/flutter_file_picker#807]
When the type is FileType.video, it picks videos from Photo Library.
When the type is FileType.any, it picks files from the Files App.
How to pick video only from Files App?

**Comment by miguelpruivo** [comment]
You'll need to use `FileType.custom` and then specify the allowed extensions, in this case: `['mp4', 'avi', 'mpg']` etc.

It's one of those iOS caveats.
