### ISSUE TITLE
[Android] Potential security issue when a malicious application returns app-private area file

### ISSUE THREAD

**Issue by innim98** [miguelpruivo/flutter_file_picker#808]
I encourage you to add new suggestions that you think that can make file_picker even a better package.
There are 2 topics.

1. Exposing app-private files

Let's guess there is a malicious application installed in the device.
This application declared android.intent.action.GET_CONTENT in it's AndroidManifest.xml file.
Once GET_CONTENT intent comes, this application returns URI like below.

>Intent data = new Intent();               data.setData(Uri.parse("file:///data/data/../data/com.mr.flutter.plugin.filepicker.example/database.db"));
setResult(RESULT_OK, data);

Then the 'file_picker' plugin will copy the file to below path and deliver the file path to Flutter application side.

> /data/data/com.mr.flutter.plugin.filepicker.example/cache/file_picker/database.db

By this way, the malicious application can trigger to do something with db file.
If the application is sending this file to network without validation, it could be privacy-leakage issue.
For the application developer, there is no way to determine if this file is from the app-private container of it or not.
I believe that 'file_picker' need to do below validations before passing it to application.

Potential path traversal "/../" pattern should be removed before processing
The file should not be passed to the application when the file is in app-private area.

2. Overwriting app-private files

A malicious application can support content-provider to overwrite app-private files like db/shared-prefs.
In FileUtils.java openFileStream() method reads the file name from FileUtils.getFileName()

> final String fileName = FileUtils.getFileName(uri, context);
final String path = context.getCacheDir().getAbsolutePath() + "/file_picker/" + (fileName != null ? fileName : new Random().nextInt(100000));

This path is used to make a cache file within app-private area.
"fileName" comes from getFileName() method which doesn't rid out path-traversal pattern "../"
When the "fileName" is "../cache/file_picker/database.db", the "path" will be like below.

> /data/data/com.mr.flutter.plugin.filepicker.example/file_picker/../cache/file_picker/database.db

Finally overwriting below file.

> /data/data/com.mr.flutter.plugin.filepicker.example/cache/file_picker/database.db

**Comment by miguelpruivo** [comment]
What would be your solution? In iOS I highly doubt it will be possible for any other application to modify the picked files, since those are private and restrict to each app container.

On Android it _could_ be an issue though. What do you suggest?

**Comment by innim98** [comment]
I agree. In iOS code, I don't see any way to manipulate the path or overwrite some files.

For Android, I suggest to fix two point of code.

1. FileUtils.java line 124 (openFileStream)
   If the URI delivered is for "file://" scheme, it might pick up the app-private files. We need to check if the file URI is under the app-private path after nomalizing URI. In Android, File.getCanonicalFile() can be used to get real path, so we can simply compare with appDataDir and filter dangerous files.
   
2. FileUtils.java line 78 before existing "try" clause in "getFileName" method
  We need to validate the value "result" which comes from "OpenableColumns.DISPLAY_NAME" in a content provider.
  I guess you can simply filter out '/' character or replace it to any safe character.
