### ISSUE TITLE
[ IOS] Does not open file explorer using file_picker in flutter

### ISSUE THREAD

**Issue by remmss** [miguelpruivo/flutter_file_picker#815]
I am using file_picker plugin for document pick from device but it doesn't work

I am getting this error below steps:

1. **First time click on button and trying to open file explorer but did not open. i mention error below**

[Presentation] Attempt to present <UIDocumentPickerViewController: 0x10c736ca0> on <UINavigationController: 0x10d80e000> (from <FlutterViewController: 0x10c816800>) whose view is not in the window hierarchy.

2. **Second time click on button and getting this error below**

flutter: [MethodChannelFilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
flutter: Unsupported operationPlatformException(multiple_request, Cancelled by a second request, null, null)
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      _LessionAttachmentState._openFileExplorer.<anonymous closure> (package:tutors_app/Screens/tutor/TabBarItems/Dashboard%20items/LessionAttachment.dart:72:30)
#1      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
#2      _LessionAttachmentState._openFileExplorer (package:tutors_app/Screens/tutor/TabBarItems/Dashboard%20items/LessionAttachment.dart:70:5)
<asynchronous suspension>

**I have tested on real device while getting error. I mention above**

Please any suggestions.

Thanks in advance.

**Comment by miguelpruivo** [comment]
Hi, this have already been opened and it’s likely related to an implementation issue on the app’s side. Just make sure you’re calling the picker once and awaiting for the result before invoking again.

**Comment by arindammitra06** [comment]
Same issue here while navigating to another page
