### ISSUE TITLE
SLOW IN WEB: FilePicker.platform.pickFiles

### ISSUE THREAD

**Issue by gjmg2303** [miguelpruivo/flutter_file_picker#816]
Hi, I run this abstract class on a web platform: FilePicker.platform.pickFiles,
The problem I have is that the first time I load an image, it takes longer than necessary. The second time I invoke the image loads very fast. How can I make the image load fast the first time?
Thanks very much and thanks for this solution for web flutter and images, 
Gastón

**Comment by miguelpruivo** [comment]
Hi, I believe that it’s not the picker itself that is doing that. It’s actually the file blob being handled by the browser that is cached hence loads faster the second time.

**Comment by gjmg2303** [comment]
Thank you very much for your interest and response. I will try to improve the cache, if possible.
Greetings
