### ISSUE TITLE
Couldn't find zenit on build flutter app on Linux

### ISSUE THREAD

**Issue by khismatullin** [miguelpruivo/flutter_file_picker#818]
**Describe the bug**
Appear exception about missing package 'zenity'. Need install separately. Not built-in in app for deploy app

**Platform**
- [] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
Debian 10

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
```
sudo apt-get update -y
sudo apt-get install -y zenity
```

**Comment by dalewking** [comment]
While installing zenity does make it work, it really should be documented in the documentation as a requirement.
