### ISSUE TITLE
file limit on multiple files and file size validation

### ISSUE THREAD

**Issue by uc-dve** [miguelpruivo/flutter_file_picker#824]
First of all thanks for giving this extraordinary package.
I have a few suggestions it will be more useful if implemented.

1. can you please provide a field where we can pass maximum files that can be picked if multiple allowed.
2. other one is file size validation while choosing file like maxFileSize: 200 // kb

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

**Comment by miguelpruivo** [comment]
Hi, thank you for the suggestion, but this is a dup of #64.
