### ISSUE TITLE
Can we able select folder in flutter web?

### ISSUE THREAD

**Issue by hayashi-tz** [miguelpruivo/flutter_file_picker#827]
Dear developers,

I am a beginner at developing in flutter web, so I would like to ask some questions.

Can we able to select the folder in flutter web in this library or any other libraries.

Thank you very much in advance!

**Comment by miguelpruivo** [comment]
Hi, I don't think this is possible. I'm sorry for any inconvenience.

**Comment by hayashi-tz** [comment]
Thank you very much for your reply. 🙏
