### ISSUE TITLE
ios- Picking multiple images and videos directly from Gallery.

### ISSUE THREAD

**Issue by RAMSHEER** [miguelpruivo/flutter_file_picker#83]
Hi guys, I am trying to Pick Multiple Images and Videos from the gallery. In ios its only opening files folder. Is there a way to open gallery and pick multiple images? Thanks.

**Comment by miguelpruivo** [comment]
Hi @RAMSHEER, not at this point. Right now you are only able to pick multiple files from the files app in iOS. In android you are free to choose whatever folder you want.

I may add this possibility in the future. As of now, to pick from gallery, you must select files individually with `FileType.IMAGE`.

Thank you.

**Comment by PINHOf** [comment]
@RAMSHEER +1
@miguelpruivo I'm having the need as well for picking multiple-images in the Gallery of iOS.

Thanks

**Comment by lifenautjoe** [comment]
Yes please!

Tested all these packages

-     https://pub.dev/packages/photo_manager
-     https://pub.dev/packages/photo
-     https://pub.dartlang.org/packages/multi_image_picker
-     https://pub.dartlang.org/packages/flutter_multiple_image_picker
-     https://pub.dartlang.org/packages/custom_multi_image_picker
-     https://pub.dartlang.org/packages/multiple_image_picker

None of them support this and the Flutter team refers to these packages as the reason not to build multi picker support on the `image_picker` library...

**Comment by miguelpruivo** [comment]
@lifenautjoe none of those support it? They look like they’re exactly what you’re looking for. 👀

Anyway, this is a requested feature that might be implemented in the feature.

**Comment by lifenautjoe** [comment]
None of them do, the only one that I could have used to build my own multi image picker: https://pub.dev/packages/photo_manager , has a critical memory management bug ... Could you provide some orientation into how would you build this?

Perhaps I can give it a try, not really an iOS dev though 😬

**Comment by miguelpruivo** [comment]
This could be implemented in the future, but currently it will have to wait as I don't have much time right now for it. 😞  I'm closing this because it is already mentioned in the #99.
