### ISSUE TITLE
How i can track "WidgetsBindingObserver", if file picker is showing?

### ISSUE THREAD

**Issue by FDhunterz** [miguelpruivo/flutter_file_picker#830]
i have problem when use "WidgetsBindingObserver" to block activity, when file picker window appears i can't use "WidgetsBindingObserver"

**Comment by philenius** [comment]
@FDhunterz can you give some more details? What platform are you working on (Android, iOS, Linux, macOS, or Windows)? What are you expecting to happen or what is missing so that you cannot use `WidgetsBindingObserver`? I'm not familiar with this widget.

**Comment by FDhunterz** [comment]
> @FDhunterz can you give some more details? What platform are you working on (Android, iOS, Linux, macOS, or Windows)? What are you expecting to happen or what is missing so that you cannot use `WidgetsBindingObserver`? I'm not familiar with this widget.

im using Android and **WidgetsBindingObserver** is a abstract class

**Comment by FDhunterz** [comment]
![image](https://user-images.githubusercontent.com/50565177/134442499-296894c8-a475-4b2b-b80b-184fe4a55dbd.png)

the above example **block = true**, how when the **filepicker** window is open, the lifecycle does not change?

**Comment by philenius** [comment]
@miguelpruivo can you check that? This is an Android-related issue.

**Comment by miguelpruivo** [comment]
I'm not sure if this is an issue at all. The app enters background mode due to the new activity being launched (the picker).
