### ISSUE TITLE
Windows App crash when choose many files.

### ISSUE THREAD

**Issue by wwawrzy** [miguelpruivo/flutter_file_picker#831]
When I choose 10 or 20 files in FilePicker my app close (crash). 

**Platform**
- [] Android
- [] iOS
- [] Web
- [x] Desktop (Go)

**Platform OS version**
Windows 10

**How are you picking?**
```
   print("choosePgnFiles 1");
    FilePickerResult? result = await FilePicker.platform.pickFiles(allowMultiple: true, type: FileType.custom, allowedExtensions: ['pgn']);
    print("choosePgnFiles 2");
```

**Error Log**
I didn't see any error. Just app close. (I'm new in Flutter and I don't know how to get more info)

**Screenshots and/or video**
[https://drive.google.com/file/d/1m74IGb_0w-ZoNoWW2cBmf9aN-86tHRik/view?usp=sharing](https://drive.google.com/file/d/1m74IGb_0w-ZoNoWW2cBmf9aN-86tHRik/view?usp=sharing)

**Flutter Version details**
C:\Programowanie\git\ChessMaestro\src\Flutter\flutter_chess_analyser>flutter doctor -v
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1237], locale pl-PL)
    • Flutter version 2.5.0 at C:\Programowanie\IDE\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (12 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Wojciech Wawrzyniak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1237]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.47

**Comment by philenius** [comment]
hi @wwawrzy, could you please update your version of `file_picker` to `4.1.0` which was published this morning?
```yaml
dependencies:
  file_picker: ^4.1.0
```

I noticed this bug as well and fixed it yesterday. At least on my Windows machine, I can pick > 20 files now. Please repeat your test and let me know whether it works now!

**Comment by wwawrzy** [comment]
I have just tested and it's ok now. 

Thanks,

best regards
