### ISSUE TITLE
Flutte web 

### ISSUE THREAD

**Issue by kananikalpesh** [miguelpruivo/flutter_file_picker#833]
Please see this video 

https://www.loom.com/share/c6dfb954208644c484670d5f36f17c09

i was use this version. file_picker: ^3.0.0 , ^4.0.1 , ^4.1.0, ^4.1.1. 

choose file button display in another screen after navigation to another screen 

 (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165],

**Comment by miguelpruivo** [comment]
@kananikalpesh this must be some issue with your app's implementation. There isn't any UI associated with this plugin on all supported platforms. It only asks the OS to launch the available pickers and that's it.

Please take a look at your app's implementation and check what is doing after you're done with the submission.
