### ISSUE TITLE
Image picking fails for live images on newer IOS. 

### ISSUE THREAD

**Issue by Jamesfleming1** [miguelpruivo/flutter_file_picker#835]
**Describe the bug**
The image picker returns an error when trying to pick a live image on iOS . 

**Platform**

- [] iOS

**Platform OS version**

iOS 15.0

**How are you picking?**
Both single image and multi image from gallery fail when trying to pick a live image 

**Details to reproduce the issue**
Try to pick a live image from the gallery. 

**Additional context**
Running on actual iPhones via TestFlight on iOS.

**Comment by miguelpruivo** [comment]
Could you please post the stacktrace?

**Comment by Jamesfleming1** [comment]
Okay I will get on that, I guess I need to update my environment to run iOS 15 so that might take me a bit.

**Comment by brunoda6** [comment]
Hi,
I'm with the same problem here it is my stacktrace:

`***** Picker:<PHPickerViewController: 0x119516d00> didFinishPicking:(
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 377]
***** FilePicker canceled
* -[FilePickerPlugin picker:didFinishPicking:] [Line 382]
***** Picker:<PHPickerViewController: 0x104250240> didFinishPicking:(
    "<PHPickerResult: 0x28196bd60>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 377]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("image")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      isImage
package:galerafm/global/global_functions.dart:156
#2      _ScreenAdicionarState.pickFiles
package:galerafm/…/Adicionar/adicionar.dart:103
<asynchronous suspension>
`

hope it helps ty :)

**Comment by miguelpruivo** [comment]
Thank you I’ll take a look!

**Comment by miguelpruivo** [comment]
Just tried it with a simulator and it works just fine with iOS 15 and live photos. What are the environment you are running on? And how are you picking?

**Comment by Jamesfleming1** [comment]
Ios 15, I'm running on an iPhone 7, have reports of it on iPhone 12 mini and iPhone 12 all on iOS 15. 

***** Picker:<PHPickerViewController: 0x1049def70> didFinishPicking:(
    "<PHPickerResult: 0x2803a5e00>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 381]

**Comment by Jamesfleming1** [comment]
Are you able to try on an actual device?

**Comment by miguelpruivo** [comment]
Yes, just tried it on a device running iOS 15 and it works just fine. Could you please try sharing the picture you are trying to pick on? (you'll have to export it while keeping the original data so it doesn't converts to JPEG).

**Comment by Jamesfleming1** [comment]
Here is my call in code 

FilePickerResult result = await FilePicker.platform
      .pickFiles(
          type: FileType.image,
          allowMultiple: allowMultiple,
          allowCompression: true)
      .onError((error, stackTrace) {
    print(error);
    print(stackTrace);
    return Future.error("PickingError");
  });

And it gives me this issue 
flutter: FileSystemException: Cannot open file, path = '/private/var/mobile/Containers/Data/Application/008FA7A9-1A0E-4930-8E34-D4D0420BC846/tmp/IMG_0020.pvt' (OS Error: Is a directory, errno = 21)

Hopefully that happens. I'm not sure how to actually send a Live Photo without converting it to live image. But it happens on every single live image so I really don't think its an issue with specific image

**Comment by shreymahendru** [comment]
Was investigating this today. This happens because `.pvt` is somewhat of a directory, and it contains 3 files. Check the. ![image](https://user-images.githubusercontent.com/14631262/135202169-346050d6-aef9-4544-b5c0-3b09ca5c8cc1.png)

 The `HEIC` (The Image), `.MOV` (The video), and a metadata file. So when you copy over the file the `.pvt` "file" is a directory, with 3 files in it. 

I am working on a workaround for that where I covert the image into a JPEG and return an updated file URL rather than a `.pvt`.

**Comment by miguelpruivo** [comment]
In my testing, the files picked where actually the `.pvt` which are expected. It's up to the developer to then extract/handle those files. The picker only allows you to pick the files as they are.

The problem is that after picking, you may need to extract, like @shreymahendru. The only two approaches I can see here is leaving as it is, or converting it automatically to JPEG, for example, but then again, some devs may want to the live photo for their applications and this would prevent it.

**Comment by miguelpruivo** [comment]
As a purposed solution whenever the developer has `allowCompression` set to `true` I'll extract it to JPEG and if the dev wants the `.pvt` file, just need to set the `allowCompression` to `false` and the file is fetched as it is.

How does that sound to you?

**Comment by brunoda6** [comment]
for me it's perfect thanks

**Comment by davidfranquet** [comment]
> As a purposed solution whenever the developer has `allowCompression` set to `true` I'll extract it to JPEG and if the dev wants the `.pvt` file, just need to set the `allowCompression` to `false` and the file is fetched as it is.
> 
> How does that sound to you?

looks great to me!

I saw this issue on ios 15. on ios 14 seems to work fine. Got lot of crashes on sentry during this week

Good catch guys!

**Comment by miguelpruivo** [comment]
Fixed and published with 4.1.3. I took advantage of some of the work that @shreymahendru made by converting Live Photos into static JPEG. Thank you! 🎉

**Comment by davidfranquet** [comment]
thanks!!!

**Comment by urusai88** [comment]
Can you fix it to work without compression?

**Comment by ioridev** [comment]
https://github.com/flutter/flutter/issues/24954

Compression is discussed in this thread
