### ISSUE TITLE
[Linux] Unable to pick files without extension

### ISSUE THREAD

**Issue by cachapa** [miguelpruivo/flutter_file_picker#836]
Calling `pickFiles` with `FileType.any` will automatically set the extension filter to `*.*` which effectively filters out files without extension.

I tried getting around it by using `FileType.custom` and `allowedExtensions: ['']` but that results in a `*.` filter which also ignores files without extension (as they're missing the trailing dot).

I only tested this on Linux, so I don't know if the issue also exists on other platforms.

Tested with file_picker 4.1.1

**Comment by philenius** [comment]
@cachapa thanks for reporting this bug. The problem does not exist on Windows nor on macOS.

**Comment by cachapa** [comment]
Thanks. I just tested the PR locally and can confirm it's working as expected now.

**Comment by miguelpruivo** [comment]
@cachapa published with 4.1.2. Thank you once again @philenius. 👍🏻

**Comment by cachapa** [comment]
Isso foi rápido. Obrigado 🙂
