### ISSUE TITLE
pickFiles never resolves when passing `allowMultiple` and `withReadStream` together on web

### ISSUE THREAD

**Issue by haradakunihiko** [miguelpruivo/flutter_file_picker#843]
**Describe the bug**
On Web (Chrome browser), when I pass `allowMultiple` and `withReadStream` together, the Future never resolves. Is this a bug or designed?

**Platform**
- [x] Web

**Platform OS version**
chrome on mac OS 11.4 

**How are you picking?**

```dart
print('start pick');
final result = await FilePicker.platform
    .pickFiles(allowMultiple: true, withReadStream: true);
print('this never called');
```

**Flutter Version details**
2.5.1

**Comment by miguelpruivo** [comment]
Could be a bug. Might have to look into it.

**Comment by zambetpentru** [comment]
Hi, I had a quick look and 4.1.0 is fine and I can see that it is broken in 4.1.1.

**Comment by JaviBonilla** [comment]
Hi, I have the same issue when `allowMultiple` and `withReadStream` are both enabled. 

I tested on `Chromium Version 94.0.4606.81 (Official Build) snap (64-bit)` on Linux and up to version `3.0.4` is working, for `4.0.0` and above it is not.
