### ISSUE TITLE
File picker is already active

### ISSUE THREAD

**Issue by hayatbangash55** [miguelpruivo/flutter_file_picker#845]
I am getting same issue on Android Platform after adding some native code for android side.

While compiling project from android side I got this error
"The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Affected Modules: file_picker"

Solutions that I have already tried

downgraded gradle to '3.5.1'
upgraded gradle to '7.0.2' (latest)
flutter clean & flutter pug get
added supper.onActivityResult in onActivityResult function of MainActivity
But none did work.

Currently I am using gradle '4.1.0' with dist 'gradle-6.7-all.zip' and kotlin version = '1.6.0-M1'

Here is flutter doctor result
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-PK)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[!] Android Studio (version 4.1)
X Unable to determine bundled Java version.
[√] VS Code (version 1.59.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by miguelpruivo** [comment]
Are you sure you're not opening multiple instances? Typically this will only happen when you request the picker to be opened when it's already active. Check your source logic to detect wether it's not being called twice or not (add a `print()` before the picker is launched, for example).
