### ISSUE TITLE
I cannot select the picture or video in the iphone photo album

### ISSUE THREAD

**Issue by shichunlei** [miguelpruivo/flutter_file_picker#862]
**Platform**
- [] iOS

**Platform OS version**
4.2.0

**How are you picking?**
```
FilePickerResult result = await FilePicker.platform.pickFiles();

if (result != null) {
  PlatformFile file = result.files.first;
} else {
  // User canceled the picker
}
```

**Error Log**
I cannot select the picture or video in the iphone photo album

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.0 at /Volumes/D1/workspace/flutter
    • Framework revision b22742018b (6 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/dev6/Library/Android/sdk
    • Java binary at: /Users/dev6/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

**Additional context**

**Comment by shichunlei** [comment]
I want to get attached files including pdf, pictures, videos and other files, but when type=FileType.any, I cannot select pictures in the album

**Comment by miguelpruivo** [comment]
@shichunlei that’s not an issue and that’s just how iOS works. It’s a platform limitation. iOS natively doesn’t allow you to select both files from Files app and Photos app.

You’ll have to choose and/or create two options in your app for selecting documents (use the any here and pick the pdf) and select media (use the media type and pick from photos app).

On Android though you can select both at the same time.

**Comment by shichunlei** [comment]
ok.  thanks!
