### ISSUE TITLE
Testing on simulator

### ISSUE THREAD

**Issue by amee13bit** [miguelpruivo/flutter_file_picker#865]
Picker crashes the app on ios simulator (ios 15/iPhone 13 pro).
is it runnable simulator or do I have to test on a real device?

**Comment by miguelpruivo** [comment]
You should be able to run in on the simulator as well. Could you please post your logs?

**Comment by amee13bit** [comment]
Its not showing any logs while running android studio, its just crashes the simulator (Lost connection).
but when I try to run from xcode it shows  'Module file picker not found'

**Comment by miguelpruivo** [comment]
Looks like you have some issues in your build, run:
```
flutter clean
flutter pub get
rm -rf ios/Pods
rm ios/Podfile.lock
cd ios && pod install
rm -rf ~/Library/Developer/Xcode/DerivedData
```
And try again.

**Comment by amee13bit** [comment]
still the same.
xocde version : 13.1
ios simulator : IPhone 13

**Comment by miguelpruivo** [comment]
Typically this issue (or any other similar) are related with any project artefacts that you might have on your build machine, it can be hard to dig down to the cause and it's a bit around trial & error by cleaning your derived data, project data, pods, pub-cache etc.

I'm sorry if can't help you any further.

**Comment by amee13bit** [comment]
it works on a real device
don't know why its not working on simulator.

**Comment by MichelMelhem** [comment]
I'm facing the same issue, could it be related to the emulator running on apple silicon ?

**Comment by miguelpruivo** [comment]
> I'm facing the same issue, could it be related to the emulator running on apple silicon ?

Yes, it is.

**Comment by Stanley-Park-DEV** [comment]
same issue here. crashes the simulator with an "lost connection to device" Exited (sigterm). and no log. im on a m1 max macbook pro. I can confirm, same code works perfectly on my 2017 27" intel imac. so something odd with the m1 machine or the version of the simulator on m1.
