### ISSUE TITLE
Module 'file_picker' not found (X-code)

### ISSUE THREAD

**Issue by dwaynetino** [miguelpruivo/flutter_file_picker#866]
**Describe the bug**
I am using the latest file picker, and latest version of flutter but i am getting the error 'Module 'file_picker' not found' in xcode when i try to run a release version but the debug version runs without any problem. I tried removing derived data, deleting Pods and reinstalling, but all in vain

**Platform**
- [] iOS

**Platform OS version**
Iphone 13

**Comment by miguelpruivo** [comment]
Does that happen on a real device?

Closing as dup of #865.

**Comment by dwaynetino** [comment]
I tried it on emulator

**Comment by miguelpruivo** [comment]
@dwaynetino that seems to be an issue with the simulator — same happened in #865. I'm yet to understand what may be causing the issue. Good think is that it shouldn't happen on a real device though.
