### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '/private/var/mobile/Containers/Data/Application/31609356-B2FF-4E41-8576-D0D46E7D0DF3/tmp/com.loancloud.fund1-Inbox/form_template.pdf' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by Nolan1357** [miguelpruivo/flutter_file_picker#867]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**
- [] Android
- [] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by Nolan1357** [comment]
There is a problem with the IOS phone, and the Android does not appear 
Occasional bug

**Comment by Nolan1357** [comment]
Hope to find out and solve it in time, thank you sir

**Comment by miguelpruivo** [comment]
I’m sorry but I didn’t get your issue. You seem to be trying to open a file that doesn’t exist on iOS.

**Comment by Nolan1357** [comment]
![Uploading image.png…]()

**Comment by Nolan1357** [comment]
sorry 
English  not  good
but  you can 
#261 


FileSystemException: Cannot retrieve length of file,(OS Error: No such file or directory, errno = 2)  #261

**Comment by miguelpruivo** [comment]
Give [this](https://github.com/miguelpruivo/flutter_file_picker/issues/261#issuecomment-857335455) a try.

**Comment by Nolan1357** [comment]
I tryed 
thank you  very match

**Comment by miguelpruivo** [comment]
Did it work?

**Comment by Nolan1357** [comment]
No  sir

**Comment by miguelpruivo** [comment]
What if you try with a different file/device?

**Comment by expertdev-designer** [comment]
Hii @miguelpruivo @Nolan1357 

i also getting this issue.

Please help.

**Comment by Nolan1357** [comment]
> Hii @miguelpruivo @Nolan1357
> 
> i also getting this issue.
> 
> Please help.

Sorry ,

**Comment by Nolan1357** [comment]
> Hii @miguelpruivo @Nolan1357
> 
> i also getting this issue.
> 
> Please help.
这几天
我从 Dio File_path 
flutter_file_picker
找出问题
如果我发现了哪里出现的BUG
我会第一时间 发布

**Comment by expertdev-designer** [comment]
@miguelpruivo Please look into this issue.

It's urgent.

**Comment by miguelpruivo** [comment]
I’m not sure how to replicate this and also seems that to be an edge case.

**Comment by Nolan1357** [comment]
复制一下 就没问题了
static Future<File> copyFile(String result) async{
    File file = File(result);
    final documentPath = (await getApplicationDocumentsDirectory()).path;
    file = await file.copy('$documentPath/${path.basename(file.path)}');
    print(file.path);
    print(file.existsSync());
    return file;
}

**Comment by Nolan1357** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/867#issuecomment-983269041

**Comment by expertdev-designer** [comment]
@miguelpruivo getting this issue only on iphone devices occasionally.Android working perfect.

**Comment by expertdev-designer** [comment]
> > Hii @miguelpruivo @Nolan1357
> > i also getting this issue.
> > Please help.
> > 这几天
> > 我从 Dio File_path
> > flutter_file_picker
> > 找出问题
> > 如果我发现了哪里出现的BUG
> > 我会第一时间 发布



> 复制一下 就没问题了 static Future copyFile(String result) async{ File file = File(result); final documentPath = (await getApplicationDocumentsDirectory()).path; file = await file.copy('$documentPath/${path.basename(file.path)}'); print(file.path); print(file.existsSync()); return file; }

not working 
FileSystemException: Cannot copy file to '/var/mobile/Containers/Data/Application/96B6B6B1-C250-4770-B215-920D4D11B2B2/Documents/application-of-appendix-iii-to-marine-species.pdf', path = '/private/var/mobile/Containers/Data/Application/96B6B6B1-C250-4770-B215-920D4D11B2B2/tmp/<bundle id>-Inbox/application-of-appendix-iii-to-marine-species.pdf' (OS Error: No such file or directory, errno = 2)

**Comment by miguelpruivo** [comment]
That seems to be only happening occasionally with some and with a few files, does that happen for all files?

**Comment by expertdev-designer** [comment]
@miguelpruivo No it's not happening with all file ..sometime that file working fine sometime error happening with same file.

**Comment by miguelpruivo** [comment]
How long does it go between picking and the error?

**Comment by expertdev-designer** [comment]
@miguelpruivo not too much .. within few sec maximum 1 min
i think the error is because of Inbox copy of that you created for file . Not sure 100 % sure
** Cannot retrieve length of file, path = '/private/var/mobile/Containers/Data/Application/31609356-B2FF-4E41-8576-D0D46E7D0DF3/tmp/com.loancloud.fund1-Inbox/form_template.pdf**

**Comment by expertdev-designer** [comment]
@miguelpruivo Please check this issue

**Comment by expertdev-designer** [comment]
@miguelpruivo @jamesdixon @marchellodev @maxzod @Nolan1357 

Please check this issue 

when we take some time  after uploading the pdf files the issue will come at merge.
Look into the video
https://drive.google.com/file/d/1jxsia1H2FL47HC6Zr8wzPGB7p7DJbAQh/view?usp=sharing

Android studio logs
Launching lib/main.dart on Elint’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X7PXVCSP9H
Running Xcode build...
Xcode build done.                                           99.5s
Installing and launching...
(lldb) 2021-12-03 17:42:31.657268+0530 Runner[58593:3196859] [Firebase/Crashlytics] Version 8.0.0
8.0.0 - [Firebase/Analytics][I-ACS023007] Analytics v.8.0.0 started
8.0.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
8.0.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
8.0.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
8.0.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[connection] nw_endpoint_handler_set_adaptive_read_handler [C1.1 2404:6800:4002:82c::200a.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C1.1 2404:6800:4002:82c::200a.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Debug service listening on ws://127.0.0.1:62003/4OG53LTeyk4=/ws
Syncing files to device Elint’s iPhone...
flutter: _appLocale Null en
flutter: _kTestingCrashlytics false  kReleaseMode false
flutter: 375.0
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized



***** FilePicker canceled
* -[FilePickerPlugin documentPickerWasCancelled:] [Line 558]
[connection] nw_endpoint_handler_set_adaptive_read_handler [C2.1 2404:6800:4002:807::200e.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C2.1 2404:6800:4002:807::200e.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
[connection] nw_endpoint_handler_set_adaptive_read_handler [C3.1 2404:6800:4002:807::200e.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C3.1 2404:6800:4002:807::200e.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/asset-9230647_LEDVANCE_BIOLUX_-_Focusing_on_people_with_Human_Centric_Lighting.pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/asset-9230647_LEDVANCE_BIOLUX_-_Focusing_on_people_with_Human_Centric_Lighting.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2825bd2c0 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/asset-9230647_LEDVANCE_BIOLUX_-_Focusing_on_people_with_Human_Centric_Lighting.pdf
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/lecture4bw_03.pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/<bundle id>-Inbox/lecture4bw_03.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2825b5920 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/lecture4bw_03.pdf
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/traffic_pub_gen19.pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/traffic_pub_gen19.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2825ba730 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/traffic_pub_gen19.pdf
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/Regular%20Color%20Auto%20Cropped%20(1).pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/Regular%20Color%20Auto%20Cropped%20(1).pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2825b8810 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/Regular Color Auto Cropped (1).pdf
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/application-of-appendix-iii-to-marine-species.pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/application-of-appendix-iii-to-marine-species.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x28258c330 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/application-of-appendix-iii-to-marine-species.pdf
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/Black%20and%20White%20Auto%20Cropped%20(1).pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/Black%20and%20White%20Auto%20Cropped%20(1).pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2825b3ea0 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/Black and White Auto Cropped (1).pdf
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/asset-13033385_the_new_streetlight_flex_range_flyer_september_2021.pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/asset-13033385_the_new_streetlight_flex_range_flyer_september_2021.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x2825b3780 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
flutter: ShadiaFile /private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/asset-13033385_the_new_streetlight_flex_range_flyer_september_2021.pdf
flutter: Failed to get platform version. FileSystemException: Cannot retrieve length of file, path = '/private/var/mobile/Containers/Data/Application/5673A08C-EB40-4111-9429-979F44D93901/tmp/project.mobile.treadStoneUs-Inbox/asset-9230647_LEDVANCE_BIOLUX_-_Focusing_on_people_with_Human_Centric_Lighting.pdf' (OS Error: No such file or directory, errno = 2)
[GETX] OPEN SNACKBAR
[GETX] CLOSE SNACKBAR


Please check asap it's urgent.
Thanks

**Comment by miguelpruivo** [comment]
What if you don’t pick files from the recents folder?

**Comment by expertdev-designer** [comment]
Let me check ... you mean browse folder?

**Comment by expertdev-designer** [comment]
@miguelpruivo Same issue occur.

**Comment by miguelpruivo** [comment]
How are you picking?

**Comment by expertdev-designer** [comment]
@miguelpruivo 
Please check this https://drive.google.com/file/d/1jxsia1H2FL47HC6Zr8wzPGB7p7DJbAQh/view?usp=sharing

**Comment by expertdev-designer** [comment]
@miguelpruivo 
Please update

**Comment by expertdev-designer** [comment]
@miguelpruivo Please check

**Comment by expertdev-designer** [comment]
Hii @miguelpruivo did you check this?

**Comment by miguelpruivo** [comment]
I did, sorry, I don’t know how to help you right now as I don’t have the time to further investigate it.

**Comment by sproutlyCaleb** [comment]
I had a problem like this while trying to upload. I fixed it by passing `file.readAsBytesSync().lengthInBytes` directly into the content-length of the Headers for my HTTP upload.

I tried

```
var fileLength = file.readAsBytesSync().lengthInBytes;
Assert(fileLength != 0)
```


and that didn't work for some reason the assert kept getting hit. But if I put it directly in the header instead of declaring in a var first it worked.. Hope this helps.

so my fix was 

`    new http.StreamedRequest('POST', uri)
      ..headers.addAll({
        'Authorization' : jwt, //authHeaders['Authorization']!
        'Content-Length' : utf8.encode(body).length.toString(),
        'Content-Type' : 'application/json; charset=UTF-8',
        'X-Upload-Content-Type' : 'image/jpeg',
        'X-Upload-Content-Length' : file.readAsBytesSync().lengthInBytes.toString(),
      });`

instead of

`    new http.StreamedRequest('POST', uri)
      ..headers.addAll({
        'Authorization' : jwt, //authHeaders['Authorization']!
        'Content-Length' : utf8.encode(body).length.toString(),
        'Content-Type' : 'application/json; charset=UTF-8',
        'X-Upload-Content-Type' : 'image/jpeg',
        'X-Upload-Content-Length' : fileLength,
      });`

**Comment by expertdev-designer** [comment]
> I did, sorry, I don’t know how to help you right now as I don’t have the time to further investigate it.
> 
> Edit: try replicating it with the example app in the plugin to see if it happens.

Okay i will check this

**Comment by expertdev-designer** [comment]
> I had a problem like this while trying to upload. I think the reason I was having trouble was that it takes time to copy the images to local storage, and since I was checking the length before the image was created it kept on failing. The way I fixed it was by creating a function to keep checking for the length until it finds it otherwise I would just retry my upload.
> 
> ```
>   Future<int> _getPhotoLength({int iteration = 0, required File file}) async {
>     var length = file.readAsBytesSync().lengthInBytes;
>     if (length > 0) {
>       return length;
>     }
>     if (iteration == 3) {
>       return 0;
>     }
>     await Future.delayed(Duration(seconds: iteration * 2));
>     return _getPhotoLength(file: file, iteration: iteration + 1);
>   }```
> ```

Thanks i will try this

**Comment by YDA93** [comment]
Same issue. Found irreproducible crash in crashalytics in ios device.

Everything working perfect in android but not ios.

This can't be replicated because it happens occasionally.

Please look into this.

```
Fatal Exception: FlutterError
0  ???                            0x0 (null)._rootRunUnary (dart:async)
1  ???                            0x0 (null).multipartFileFromPath + 15 (multipart_file_io.dart:15)
2  ???                            0x0 ApiBaseHelper.uploadFiles + 236 (api_base_helper.dart:236)
3  ???                            0x0 AdService.createComment + 279 (service_ad.dart:279)
```

@[Nolan1357](https://github.com/Nolan1357) Did you find a workaround?

**Comment by Elhan98** [comment]
Hi @miguelpruivo , I've the same problem. It seems that after 1/2 minutes that i picked the image, in the temporary storage that file is deleted becuse it isn't use. I think it's releted to this: https://stackoverflow.com/questions/62766286/temporary-files-are-being-removed-during-execution-on-ios. For example if i pick one image, get the path, then wait 1/2 minutes and try to get that image by the path , it goes in error because it has been deleted

**Comment by gibahjoe** [comment]
I just experienced this issue or similar issue

```
/Users/[redacted]/Library/Developer/CoreSimulator/Devices/B3A65624-67B1-45B3-AB3E-18268068212C/data/Containers/Data/Application/090BFD9E-6EF0-40D1-92C5-4820D930DDCB/tmp/[redacted]/jwkwjwi_iwiwi.pdf' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
```

I discovered it happens after using hot reload. 

Just incase anyone has similar issues.

**Comment by oguz-bektas** [comment]
Your App name code (B3A65624-67B1-45B3-AB3E-18268068212C) changes at each run. This issue happens when you save the name code locally and try to read previous name
