### ISSUE TITLE
Refacto into a singleton

### ISSUE THREAD

**Issue by Pierre-Monier** [miguelpruivo/flutter_file_picker#868]
The package use static method, this make file_picker harder to mock in unit test. If we do some refactoring and transform file_picker into a singleton, it will be easier to mock. I can make this change if you want

**Comment by miguelpruivo** [comment]
Hi, it's already a singleton.

When you do `FilePicker.platform` it [handles which platform is running](https://github.com/miguelpruivo/flutter_file_picker/blob/908efe50d15f3c36ba1b36967e1a76fc73e93f7d/lib/src/file_picker.dart#L41) on at runtime and then creating a single instance for it which is kept until the app finishes.

**Comment by Pierre-Monier** [comment]
My bad ^^
