### ISSUE TITLE
Can't Run on a Real Device.

### ISSUE THREAD

**Issue by SinaMN75** [miguelpruivo/flutter_file_picker#870]
I'm using the package and it's working perfectly on simulator but not on real device.

here is my output:

`Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS, id:ee60165aad4017ff27540ed3bc14b979b6d62f33, name:Sina’s iPad, error:Device is busy (Making Sina’s iPad ready for development, Processing cache files from device) }
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:5BD9EB00-6AAF-41AB-8B84-9FC3B1CD9366, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:39C6DB33-1FA0-406A-B4C8-747B658BA86E, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:98FF3E8A-B6B9-462C-B4B7-FA3852727309, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:8BE7E753-A443-463D-BDBE-EDC6C6E1877D, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:959BCF5F-9AF8-47F0-9CC7-D5683032BBA2, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:B8CD813B-4831-4DEC-A924-894052B16CD3, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:DD0F20F8-2092-4889-9F67-D4364A561A6D, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:FDE0DAC7-8EC9-4878-BBBF-ABC97AA75987, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:5DEEE6D7-4F40-4C7D-85CA-DF1602AFBEBA, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:FE36A75E-9587-477A-AF1F-F879CD33FDF8, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:054243A8-04B9-474C-8056-A436B98ACC4D, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:2940BF4E-70A6-4657-A370-BA22BD8A4B7D, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:7C0CF525-1107-4E31-8ACD-AD47A53C95C4, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:6878878F-82CC-4DE5-856D-CB01B6CCF6DF, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:4F31D364-C302-4C46-BE52-CCDC9DBDF9BC, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:BF41C8B0-9F37-4D15-88E4-EE1C7293C99F, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:0FE19388-11A7-4E08-8E34-0CBD2EE7B250, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:FA9A668A-5A10-40A3-BD78-6C39BF6DC10B, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:47E8AB64-218E-4332-8390-A426FA1979A2, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:A74A668E-0EFA-4C8E-8EEE-EB3C4B759E18, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:8583DCB3-90A4-4669-A0EF-19189DB442DF, OS:15.0, name:iPod touch (7th generation) }
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/sinamn75/Documents/Apptech/medgram/medgram_flutter/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:39:52: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDataSource: class {
                                                       ^~~~~
                                                       AnyObject
    /Users/sinamn75/Documents/Apptech/medgram/medgram_flutter/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:55:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/sinamn75/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.2+1/ios/Classes/FilePickerPlugin.m:316:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentAtURL:(NSURL *)url{
    ^
    In module 'UIKit' imported from /Users/sinamn75/Documents/Apptech/medgram/medgram_flutter/ios/Pods/Target Support Files/file_picker/file_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIDocumentPickerViewController.h:27:1: note: method 'documentPicker:didPickDocumentAtURL:' declared here
    - (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentAtURL:(NSURL *)url API_DEPRECATED_WITH_REPLACEMENT("documentPicker:didPickDocumentsAtURLs:", ios(8.0, 11.0));
    ^
    1 warning generated.

    Failed to package /Users/sinamn75/Documents/Apptech/medgram/medgram_flutter.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the precompiled application for the device.

Error launching application on Sina’s iPad.`

**Comment by vitulgoyani** [comment]
i setted deployment target to 11.0 and it is work for me
