### ISSUE TITLE
File extension filter not enforced on Windows

### ISSUE THREAD

**Issue by iamkunalpitale** [miguelpruivo/flutter_file_picker#871]
Allowed extensions work only on macOS and not in window nor in ubuntu
Please suggest me or fix this - 

` FilePickerResult? result =
                                      await FilePicker.platform.pickFiles(
                                    type: FileType.custom,
                                    allowedExtensions: [
                                      'jpg',
                                      'pdf',
                                      'png',
                                      'jpeg'
                                    ],
                                  );`

**Comment by philenius** [comment]
I'm afraid that I don't understand what is not working. Please provide more details:
* Screenshots or screencasts
* Detailed description of what is going wrong
* Do you have any logs? Errors?
* Which version of file_picker do you use?
* What is your Windows version and Linux distribution?

I tested it a few seconds ago with the latest file_picker version 4.2.2+1 on Windows 10 and on Ubuntu 20.04. As expected, the filter filter is correctly set to `jpg`, `pdf`, `png`, and `jpeg` files and only these type of files can be selected in the dialog. Here are the screenshots:

![Screenshot 2021-11-13 123936](https://user-images.githubusercontent.com/9049899/141642779-e4aa79ad-4b39-4571-9576-7ddac61fa71e.png)

![Screenshot from 2021-11-13 12-55-25](https://user-images.githubusercontent.com/9049899/141642823-01ed334e-53b5-4c5d-b68d-3fd9b0cb4c75.png)

**Comment by iamkunalpitale** [comment]
Screenshots or screencasts
<img width="480" alt="Screenshot 2021-11-25 at 10 44 26 AM" src="https://user-images.gith
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/26413565/143383916-6f06670b-7bde-43bf-9876-34790c145640.png)
ubusercontent.com/26413565/143383791-754993c9-81cd-47d4-9782-4f232297570b.png">


Detailed description of what is going wrong 
At the time of selecting file (Click on the dropdown -select All files) now i am able to select .xls file or .doc file too
Do you have any logs? Errors?
No, Didn't get any errors
Which version of file_picker do you use?
file_picker: ^4.2.4
What is your Windows version and Linux distribution?
Windows 10

**Comment by philenius** [comment]
@iamkunalpitale thank you for reporting this bug!

Fixed in #904 and will be soon merged + released under version `4.2.7`.
