### ISSUE TITLE
Permission Requesting reason

### ISSUE THREAD

**Issue by dovahkiin98** [miguelpruivo/flutter_file_picker#872]
Why does the plugin request permission to External Storage? Even though reading a file or picking a folder does not require External Storage permission.

For example, in Android, picking a file gives you a URI, that you can use to read data from, without needing permission.

Same for writing to file if you pick a directory, though you do need more code to do that.

If the user of this plugin wants to write to the file, and that permission is denied, that's the developer's responsibility, not the Plugin's.

**Comment by miguelpruivo** [comment]
To handle files in the Flutter side you always need to work with absolute paths to create a `File` instance, hence the reason why they are cached — the URI is only provided for those that want it for some reason.

Because of that, I'm afraid that you will always need to request read permissions.

**Comment by dovahkiin98** [comment]
You can still use native code to create a temporary file with the same data, without having to request access to the entire external storage.

As someone who uses this plugin in a very simple app, having the user see the `External Storage Permission` will most likely scare some users away

**Comment by miguelpruivo** [comment]
Does using 4.2.2 solve it for you? That version removed the read external permission from the plugin but then reverted.

**Comment by dovahkiin98** [comment]
@miguelpruivo It removed the permission declaration in the manifest, but that doesn't remove the native code requesting the permission

**Comment by miguelpruivo** [comment]
Oh, I got you. As an alternative I can refactor to add a `FilePicker.platform.requestReadPermissions()` so they have to be explicitly asked if you want to read external storage (that nowadays most of devices use) but I suspect that most devs would have to use it anyway, so that's an additional step.

**Comment by dovahkiin98** [comment]
I don't think this plugin should handle permissions at all. It's the developer's responsibility, not the plugin's.

If the application crashes or sends an error message, then the developer would know what to do, instead of adding extra responsibility to a plugin

**Comment by miguelpruivo** [comment]
@dovahkiin98 I understand your point but _most_ will need this permission anyway, I can see it being in a separate method just to provide a way to ask for the permission, however, I'm quite afraid that I'm starting to receive a lot of new issues just because people won't read the changelog/docs. But I agree with you nevertheless, I'll probably refactor it into a separate method.

**Comment by XNeverGiveUp** [comment]
Hey @miguelpruivo ,  I commented out the code related to the detection permissions, and the plugin still works fine. I am not sure why we need to check the permission? 
And the reason why I commented it out is we usually follow the minimum permissions policy, which means that if we don't need permissions, we shouldn't apply for them.
Would you consider not applying for permissions in a future version?

**Comment by sevenzees** [comment]
You shouldn't need READ_EXTERNAL_STORAGE permissions to cache the file. Is there a reason why you can't use the app-specific directories that don't require any permissions to cache the file?

https://developer.android.com/training/data-storage/app-specific#internal-access-files

![image](https://user-images.githubusercontent.com/39177575/180654853-90f08f6c-a7ca-42aa-aa74-5b5866c3eed3.png)

![image](https://user-images.githubusercontent.com/39177575/180654835-dffd443e-2982-46e5-9da2-1f432e1e076e.png)

The image_picker Flutter package does the same thing as this package (except that you can only browse for images) without requiring READ_EXTERNAL_STORAGE.

**Comment by kutear** [comment]
Do you has plan to remvoe `READ_EXTERNAL_STORAGE `? @miguelpruivo

**Comment by rcaner** [comment]
Do you have any update this issue @miguelpruivo

**Comment by Liloupar** [comment]
@miguelpruivo 
is any update? READ_EXTERNAL_STORAGE is not need. thanks
