### ISSUE TITLE
[Suggestion] Interop between PlatformFile and XFile

### ISSUE THREAD

**Issue by navaronbracke** [miguelpruivo/flutter_file_picker#875]
The plugin uses `PlatformFile` to provide a cross-platform File implementation.
This is fine by itself. However official Flutter plugins use [cross_file](https://pub.dev/packages/cross_file).
For example: a pubspec contains both `file_picker` and `camera`.
Now there are 2 different cross platform file implementations that someone could use.

Why don't we migrate to using XFile instead? This also eliminates the need for having to convert between the two. 
I.e.  the result of `CameraController.stopRecording()` doesn't have to be converted to a `PlatformFile` after recording, which in itself involves another Future for the size & bytes.

**Comment by navaronbracke** [comment]
cc @miguelpruivo

**Comment by miguelpruivo** [comment]
What would be the implications in the file picker for this?

**Comment by navaronbracke** [comment]
> What would be the implications in the file picker for this?

We would just have to return an XFile from the file picker methods. Since both `PlatformFile` and `XFile` are both wrappers around dart:io's File class, this seems doable? 

A second option would be updating the documentation on how you could create an XFile from a PlatformFile and the other way around (from XFile to PlatformFile).

**Comment by miguelpruivo** [comment]
The PlatformFile contains multiple handy features as well as being able to abstract Web implementation which doesn’t support IO imports.

Anyway, I think I can add a way to retrieve a XFile directly from the PlatformFile and that can be a plus for some.

**Comment by philitell** [comment]
It would be great if we could retrieve a XFile from file_picker because it makes it easier to use this package in combination with other packages.

**Comment by Patrick386** [comment]
Flutter WEB: 
I am using both packages in one widget.
Any news?

**Comment by sunilguptasg** [comment]
Any update or workaround - I am using XFile extensively and would like to use this package. Any way to convert PlatformFile to XFile?

**Comment by LaysDragon** [comment]
I use following code convert PlatformFile to XFile with `withData:true`
```dart
var result = await FilePicker.platform.pickFiles();
if (kIsWeb) {
    return result?.files.map((f) => XFile.fromData(f.bytes!, name: f.name, length: f.size)).toList()??[];;
} else {
  return result?.files.map((f) => XFile(f.path!, name: f.name, bytes: f.bytes, length: f.size)).toList()??[];;
}
```

**Comment by Tienisto** [comment]
I think file_picker should optionally **not** copy the file to a temporary path if the app has `MANAGE_EXTERNAL_STORAGE` permission.
Of course, this is an edge case but this should be handled by the plugin.
