### ISSUE TITLE
get null from bytes and readStream

### ISSUE THREAD

**Issue by DipakSkywave** [miguelpruivo/flutter_file_picker#876]
@miguelpruivo @tmthecoder 
if I can use bytes then get read stream get null and if use read stream then bytes get null.

How do I get both data at the time?

**Platform**
- [] Web
- [] Desktop (Go)

I am using file_picker: ^4.2.3.

This is my code:

var picked = await FilePicker.platform
        .pickFiles(withData: true, withReadStream: true, type: FileType.image);

Response:
FilePickerResult(files: [PlatformFile(, name: my_image.png, bytes: null, readStream: Instance of '_ControllerStream<List<int>>', size: 101301)])

Please help me.

Thank you in advance.

**Comment by philenius** [comment]
@miguelpruivo , correct me if I'm wrong, but this is the intended behavior of _file_picker_!

You can either retrieve the picked file as a stream of bytes **or** you can retrieve all the bytes/data immediately. The first option prevents the selected file from being loaded into memory immediately, and thereby prevents high memory usage, specially for larger files. Why would you like to have both, a stream of bytes and all the bytes simultaneously? What's the use case for that?

**Comment by miguelpruivo** [comment]
That’s correct @philenius. There’s no point of having both at the same time and that would have impact on performance as well.

**Comment by DipakSkywave** [comment]
> @miguelpruivo , correct me if I'm wrong, but this is the intended behavior of _file_picker_!
> 
> You can either retrieve the picked file as a stream of bytes **or** you can retrieve all the bytes/data immediately. The first option prevents the selected file from being loaded into memory immediately, and thereby prevents high memory usage, specially for larger files. Why would you like to have both, a stream of bytes and all the bytes simultaneously? What's the use case for that?

@philenius means  not get both data at the time?

**Comment by philenius** [comment]
> means not get both data at the time?

@DipakSkywave: correct, you cannot get both at the same time

When working with streams, it is important to know that  you cannot read twice from a stream in Dart. This is explained in the Dart docs:
> The most common kind of stream contains a sequence of events that are parts of a larger whole. [...] This is the kind of stream you get when you read a file or receive a web request. **Such a stream can only be listened to once.** 
https://dart.dev/tutorials/language/streams#single-subscription-streams

So you cannot use the same stream to upload it to a server **and** to visualize it using `Image.memory()`. Instead, here's what you need to do:
 
```dart
/// Open the file picker
final result = await FilePicker.platform.pickFiles(type: FileType.image);

/// Check the result
if (result != null &&
    result.files.isNotEmpty &&
    result.files[0].path != null) {
  /// Create a File object from the picked file path
  final imageFile = File(result.files[0].path!);

  /// This is how you can create the Image widget to visualize the picked image
  final imageWidget = Image.file(imageFile);

  /// This is how you can upload the image
  final uri = Uri.parse('<API_URL>');
  final request = http.MultipartRequest('POST', uri);
  request.files.add(
    http.MultipartFile.fromBytes(
      'file',
      await imageFile.readAsBytes(),
      contentType: MediaType('image', 'jpeg'),
    ),
  );
}
```

**Please post any further questions on StackOverflow. We are not here to answer general programming questions / questions related to Dart :wink: Thanks.**


Anyway, here's a full Flutter app that lets a user pick an image, visualizes the picked image and simultaneously uploads it to a server:
 
```dart
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:http_parser/http_parser.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Image? _imageWidget;

  Future<void> _onPressButton() async {
    final pickedFile = await _pickImage();

    if (pickedFile != null) {
      setState(() {
        _imageWidget = Image.file(pickedFile);
      });
      _uploadImageFile(pickedFile);
    } else {
      setState(() {
        _imageWidget = null;
      });
    }
  }

  Future<File?> _pickImage() async {
    final result = await FilePicker.platform.pickFiles(type: FileType.image);

    if (result == null ||
        result.files.isEmpty ||
        result.files[0].path == null) {
      return null;
    }

    final imageFile = File(result.files[0].path!);
    return imageFile.existsSync() ? imageFile : null;
  }

  Future<void> _uploadImageFile(File image) async {
    try {
      final uri = Uri.parse('<API_URL>');
      final request = http.MultipartRequest('POST', uri);
      request.files.add(
        http.MultipartFile.fromBytes(
          'file',
          await image.readAsBytes(),
          contentType: MediaType('image', 'jpeg'),
        ),
      );

      final response = await request.send();
      if (response.statusCode == 200) {
        debugPrint('Upload succesful');
      } else {
        debugPrint('Upload failed');
      }
    } catch (e) {
      debugPrint('Upload failed with exception: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          ElevatedButton(
            onPressed: _onPressButton,
            child: const Text('Upload an image'),
          ),
          const SizedBox(
            height: 100,
          ),
          _imageWidget ?? const SizedBox(),
        ],
      ),
    );
  }
}
```

**Comment by tanjunior** [comment]
> need to do:
> 
> ```dart
> /// Open the file picker
> final result = await FilePicker.platform.pickFiles(type: FileType.image);
> 
> /// Check the result
> if (result != null &&
>     result.files.isNotEmpty &&
>     result.files[0].path != null) {
>   /// Create a File object from the picked file path
>   final imageFile = File(result.files[0].path!);
> 
>   /// This is how you can create the Image widget to visualize the picked image
>   final imageWidget = Image.file(imageFile);
> 
>   /// This is how you can upload the image
>   final uri = Uri.parse('<API_URL>');
>   final request = http.MultipartRequest('POST', uri);
>   request.files.add(
>     http.MultipartFile.fromBytes(
>       'file',
>       await imageFile.readAsBytes(),
>       contentType: MediaType('image', 'jpeg'),
>     ),
>   );
> }
> ```
> 

I am guessing this wouldn't work on web? Since I am already reading the bytes on `MemoryImage`
```
FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image, allowMultiple: false, withData: true);
                                          
if (result != null && result.files.isNotEmpty) {
  PlatformFile pFile = result.files.single;
  setState(() {
    image = MemoryImage(pFile.bytes!);
  });
  Map data = await saveNewUser("id", "name", pFile: pFile);
}
```
