### ISSUE TITLE
pub.dev and github are not in sync

### ISSUE THREAD

**Issue by boldt** [miguelpruivo/flutter_file_picker#878]
On pub.dev, there is version 4.2.3 available:

![grafik](https://user-images.githubusercontent.com/750793/142161884-39e325db-9c0a-4fbd-ae5b-37ae9ba6b9ef.png)

The Changelog on pub.dev does not list the version 4.2.3:

* https://pub.dev/packages/file_picker/changelog

Also, there is no tag in github, which represents 4.2.3:

* https://github.com/miguelpruivo/flutter_file_picker/tags

[EDIT] Maybe its the 4.1.3?

![grafik](https://user-images.githubusercontent.com/750793/142162255-bcb34b37-f99a-4bf7-a8b2-a26d28ab050a.png)

**Comment by miguelpruivo** [comment]
Thank you, that was a mistake but shouldn’t have any impact on the versioning or whatsoever. I’ll fix it right away.
