### ISSUE TITLE
getDirectoryPath

### ISSUE THREAD

**Issue by JuniorFlorentino** [miguelpruivo/flutter_file_picker#880]
The getDirectory() feature doesn't work for flutter version 2.5, I tested it using minSdkVersion 21, but it brings the path only with "/"

**Comment by miguelpruivo** [comment]
You’re probably picking the downloads directory. That’s a protected one, you can’t pick it. That’s in the docs.

**Comment by JuniorFlorentino** [comment]
Can you explain why the android emulator and apple works?


Att.
José Florentino

Contato: (82) 9-8826-7829
Email: ***@***.*** / ***@***.***
Graduado: Análise e Desenvolvimento de Sistemas
Esp. Desenvolvimento Mobile



Em qua., 17 de nov. de 2021 às 15:26, Miguel Ruivo ***@***.***>
escreveu:

**Comment by miguelpruivo** [comment]
@JuniorFlorentino apple has nothing to do with this limitation, it should work on both. However, Android shouldn't allow you to pick files from downloads folder from SDK 30 and above on both real and simulator devices.

**Comment by JuniorFlorentino** [comment]
on the physical iphone it doesn't work, it gives a permission error,
on the simulator it works perfectly.

On android simulator with sdk 31 it also works perfectly for any
folder, because it asks permission for that folder every time it's
going to save, on android physical device it only works on the
download folder, on any other it gives a permission error.

Para.
José Florentino

Contato: (82) 9-8826-7829
Email: ***@***.***  / ***@***.***
***@***.***>
Graduado: Análise e Desenvolvimento de Sistemas
Esp. Desenvolvimento Mobile



Em qui., 18 de nov. de 2021 às 09:17, Miguel Ruivo ***@***.***>
escreveu:

**Comment by JuniorFlorentino** [comment]
I can make a video if you want.
Para.
José Florentino

Contato: (82) 9-8826-7829
Email: ***@***.***  / ***@***.***
***@***.***>
Graduado: Análise e Desenvolvimento de Sistemas
Esp. Desenvolvimento Mobile



Em qui., 18 de nov. de 2021 às 09:26, José Florentino <
***@***.***> escreveu:

**Comment by hs029** [comment]
I met the same issue.
