### ISSUE TITLE
NSDescription=Generation not found something wrong here 

### ISSUE THREAD

**Issue by expertdev-designer** [miguelpruivo/flutter_file_picker#883]
Custom file type supported: com.adobe.pdf
* +[FileUtils resolveType:withAllowedExtensions:] [Line 59]
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/F6EF00A1-AB50-47B5-93E5-C82356AB0617/File%20Provider%20Storage/sample-pdf-file.pdf with the Inbox copy file:///private/var/mobile/Containers/Data/Application/42A79D77-BCD6-41AC-A91E-B093264E60CC/tmp/<bundle_id>-Inbox/sample-pdf-file.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x280f9b7b0 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}

Please help

**Comment by miguelpruivo** [comment]
What kind of issue are you experiencing? If it is the logs only, then those shouldn't have any impact.
