### ISSUE TITLE
DartFormatter fails to format files with FilePicker code on Dart 2.15.0

### ISSUE THREAD

**Issue by alexvoina** [miguelpruivo/flutter_file_picker#884]
**Describe the bug**

I have successfully imported and used file_picker in my project, but my DartFormatter fails to format files where I have FilePicker code. Whenever I hit ctrl + S to trigger dart formatting vscode pops up a window in the bottom right corner saying "A request has failed. See the output for more information"

**Platform**
- [] Desktop (macOS)

**Platform OS version**
10.15.7 Catalina

**Details to reproduce the issue**

1. import file picker into my file (import 'package:file_picker/file_picker.dart';)
2. write some code (not from FilePicker), hit ctrl + S, code formatting works fine
3. add the following code to my file 

FilePickerResult? result = await FilePicker.platform.pickFiles(
                type: FileType.audio
                allowedExtensions: ['wav', 'mp3']
              );
 4. hit ctrl + S, vscode pops up a window in the bottom right corner saying "A request has failed. See the output for more information"
 5. comment the FilePicker code
 6. hit ctrl + S, code formatting works fine again

**Error Log**

[Error - 2:26:28 PM] Request textDocument/formatting failed.
  Message: An error occurred while handling textDocument/formatting request
  Code: -32001 
[Error - 2:26:28 PM] An error occurred while handling textDocument/formatting request: The formatter produced unexpected output. Input was:

... 
my code
...

Which formatted to:

... 
my code
...

#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:177:7)
#1      generateEditsForFormatting (package:analysis_server/src/lsp/source_edits.dart:94:33)
#2      FormattingHandler.formatFile (package:analysis_server/src/lsp/handlers/handler_formatting.dart:36:12)
#3      FormattingHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_formatting.dart:53:14)
#4      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#5      FormattingHandler.handle (package:analysis_server/src/lsp/handlers/handler_formatting.dart:47:17)
#6      MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:150:12)
#7      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:36)
#8      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:47)
#9      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:325:21)
#10     _rootRun (dart:async/zone.dart:1428:13)
#11     _CustomZone.run (dart:async/zone.dart:1328:19)
#12     _runZoned (dart:async/zone.dart:1863:10)
#13     runZonedGuarded (dart:async/zone.dart:1851:12)
#14     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:325:5)
#15     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:85:16)
#16     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:54:24)
#17     _rootRunUnary (dart:async/zone.dart:1436:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#24     _rootRun (dart:async/zone.dart:1420:47)
#25     _CustomZone.run (dart:async/zone.dart:1328:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#28     _rootRun (dart:async/zone.dart:1428:13)
#29     _CustomZone.run (dart:async/zone.dart:1328:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

**Flutter Version details**
[✓] Flutter (Channel unknown, 2.6.0-11.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-11.0.pre 
    • Upstream repository unknown
    • Framework revision 4b330ddbed (9 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

**Comment by alexvoina** [comment]
I forgot to mention that i'm adding file picker to my dependencies in yaml without specifying a version which should pull the latest version

dependencies:
  flutter:
    sdk: flutter

  file_picker:

**Comment by miguelpruivo** [comment]
Hi, I'm sorry that you're experiencing this issue but this isn't likely related with the plugin at all but probably with some configs in your editor.

You can always try to run `flutter format .` in your project root folder and it should work.
