### ISSUE TITLE
Get data URI from web

### ISSUE THREAD

**Issue by cmayo** [miguelpruivo/flutter_file_picker#887]
**Describe the bug**
I'm using flutter_file_picker for web. I know that _path_ is null for web but in a previous version _path_ had the data URI (i.e. data:image/png;base64,...) of the image when you set _withData_ to false but now you can't get it. I know that you can get the _bytes_ of the selected file but I can't find the way to convert the _Uint8List_ to the data URI string with the proper mime type of the file selected. Do you know how to achieve this?

**Platform**
- [] Web

**Comment by miguelpruivo** [comment]
@cmayo hi, can you point me towards a version that had it working before?

**Comment by cmayo** [comment]
@miguelpruivo With version 3.0.3 when I did:

``
final file = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png', 'jpeg'],
      allowMultiple: false,
      withData: false,
    )
``

I could get in the _path_ property of file, the data URI as this "data:image/png;base64...." but now, in the current version, the _path_ property is null. If I set _withData: true_ but I don't know how to get the data URI from there.
