### ISSUE TITLE
Only on ios - Unhandled Exception: [firebase_storage/unauthorized] User is not authorized to perform the desired action.

### ISSUE THREAD

**Issue by prashantspandey** [miguelpruivo/flutter_file_picker#888]
It works perfectly fine on android but on ios - Unhandled Exception: [firebase_storage/unauthorized] User is not authorized to perform the desired action.
What can i do?

**Comment by miguelpruivo** [comment]
Hi, I'm sorry that you are experiencing an issue, but this has nothing to do with this plugin. You may want to check firebase permissions for that user when writing into the storage or ask in the Firebase repo.
