### ISSUE TITLE
Error: Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by Wissperwind** [miguelpruivo/flutter_file_picker#889]
Hi,

I would like to privide file upload for my flutter website.
I executed: FilePickerResult? result = await FilePicker.platform.pickFiles(allowMultiple: true);
But an error occours: 
Error: Unsupported operation: Platform._operatingSystem

What happened?

**Comment by Wissperwind** [comment]
Using flutter version 2.6.0-12.0.pre.702
Try to use flutter web. On the main site it is written that this thing works for flutter web...

**Comment by Wissperwind** [comment]
Well, on 2.6.0-12.0.pre.790 it works again... strange.

**Comment by aleneum** [comment]
Just in case someone is having the same issue: Running `flutter clean` and `flutter build` solved it for me. My target is Chrome on Windows with Flutter 2.16.2.
