### ISSUE TITLE
On macOS impossible to open file with comma followed by a space

### ISSUE THREAD

**Issue by friebetill** [miguelpruivo/flutter_file_picker#890]
**Describe the bug**
Files with a comma followed by a space, e.g. "test, test.csv", cannot be opened correctly in the macOS version. The result consists of two non-existing files, even though only one file was selected.

**Platform**
- [ ] Desktop (Go)

**Platform OS version**
macOS Big Sur 11.5.2

**How are you picking?**
```dart
  final result = await FilePicker.platform.pickFiles();
```

**Comment by philenius** [comment]
@miguelpruivo I'd need a programming advice:

macOS returns the list of picked files as a string where each file is prefixed with `alias `. Multiple files are separated by comma:
```
alias macOS:Users:John:Desktop:bill.pdf, alias macOS:Users:John:Desktop:holidays.png
```

My current implementation splits the string by `, ` (comma followed by blank). Now, @friebetill gave an example where users name their files `bla, .pdf`. Obviously, it was a bad idea to split the macOS string by `, `.

I could change the implementation to split by `, alias `. This would enable users to pick files named `bla, .pdf`. But, it couldn't handle the situation where user name files like `bla, alias .pdf`.

No matter which separator I use to split the string returned by macOS, there will be some file names that won't work. Do you have a better idea than splitting by `, alias `?

**Comment by miguelpruivo** [comment]
@philenius I’d split it by `, alias macOS:` just to make sure. It’s highly unlikely that users will have files with that name.

Since we’re working with strings I’m afraid there isn’t much to do.

**Comment by philenius** [comment]
@miguelpruivo thanks for your quick response, then I'll do it that way.

Just for clarification: my example was slightly misleading. Actually, the first part that comes after `alias ` represents the name of the volume on the macOS file system. It can be any value, e.g. `macOS`, `macOS Base System`, `My USB`, `WD My Passport`, etc.
So, I cannot split by `, alias macOS:` because the `macOS` part represents the volume's name. A better example would have been:
```
alias macOS:Users:John:Desktop:bill.pdf, alias macOS Base System:bin:bash, alias MyUSB:presentation.pptx
```
