### ISSUE TITLE
allowedExtensions ignored

### ISSUE THREAD

**Issue by rulila52** [miguelpruivo/flutter_file_picker#894]
I use file_picker to attach files like this: 

```
FilePickerResult? result = await FilePicker.platform.pickFiles(
 type: FileType.custom,
 allowMultiple: true,
 allowedExtensions: [...]);
 ```

I sent the application for testing and I see that someone attached a file with a format that I did not specify in allowedExtensions (fb2). At the moment, I can't figure out which device it was done from, it's only known that it's android. what could be the reason that allowedExtensions didn't work?

**Comment by blisssan** [comment]
Yes it seems to be the same for me too.
```
FilePickerResult result = await FilePicker.platform.pickFiles(
    type: FileType.custom,
    allowedExtensions: ['pdf', 'doc'],
);
```

**Comment by blisssan** [comment]
Actually after testing for a while noticed that, within the default file picker browser the extensions are working fine. But there are shortcuts to other apps like photos app from within the file browser like shown in the image [here](https://imgur.com/a/YHJtU6K) which is where people were able to choose image. Is there anyway to disallow external apps?

**Comment by miguelpruivo** [comment]
Hi, this is described [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4). Unfortunately is a platform limitation since we can’t be sure that 3rd party pickers/providers will respect the filters.

You should always double check on your end by discarding the unwanted picked files when applicable.

**Comment by afucher** [comment]
> Hi, this is described [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4). Unfortunately is a platform limitation since we can’t be sure that 3rd party pickers/providers will respect the filters.
> 
> You should always double check on your end by discarding the unwanted picked files when applicable.

the link is pointing to a different issue. Any update on this?

**Comment by Undeadlol1** [comment]
Same problem here. Can't make a picker specifically for ebooks. All of the ebooks in the file browser are grayed out.

```dart
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['epub', 'fb2'],
      );
 ```

**Comment by adnankovacevic** [comment]
Hi, I’m experiencing the same issue with the allowedExtensions being ignored. Has anyone found a workaround or solution for this?

 ```
    final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['jpg', 'jpeg', 'png', 'svg', 'pdf']
      );
```
