### ISSUE TITLE
Missing code for FilePickerWeb

### ISSUE THREAD

**Issue by Wissperwind** [miguelpruivo/flutter_file_picker#895]
Hi,

I would like to have a look on the filer picker code used for the web platform. I can't find it here in the repository. Where is it?

**Comment by miguelpruivo** [comment]
[Here](https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/_internal/file_picker_web.dart) you have it.

**Comment by Wissperwind** [comment]
Cool Thanks! Did not looked there for some reason.
