### ISSUE TITLE
Unable to select files beacuse of a platform exception.

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [miguelpruivo/flutter_file_picker#898]
I'm using 'file_picker' plugin to select audio files from the iOS device(simulator). But the first time I click on select button it doesnt throw any exception and does nothing. second time If I try to select the file then it throws Platform exception that 
the request is cancelled by a second request.

**Platform**
-iOS

**Platform OS version**
-iOS15

**How are you picking?**
```
List<PlatformFile>? paths = (await FilePicker.platform.pickFiles(
        type: fileType,
        allowMultiple: false,
        onFileLoading: (FilePickerStatus status) => print(status),
        allowedExtensions: null,
      ))
          ?.files;
      if(paths!=null){
        debugPrint("Notnull");
      }
      else{
        debugPrint("null");
      }    
      return paths!.length > 0 ? paths[0].path : null;
    } on PlatformException catch (e) {
      _logException('Unsupported operation' + e.toString());
    } catch (e) {
      _logException(e.toString());
    }
    if (!mounted) return null
```

Steps to reproduce:
use file picker plugin to select files from storage

**Error Log**
 [MethodChannelFilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
flutter: Unsupported operationPlatformException(multiple_request, Cancelled by a second request, null, null)

**Already Tried**
-updated NSMusic access in info.plist

**Comment by miguelpruivo** [comment]
You need to have Apple Music installed on device.

Enviado do meu iPhone

**Comment by krishnaprasadgandrath-nooor** [comment]
okay.Thanks
