### ISSUE TITLE
Persistent file access for user selcted files (macOS)

### ISSUE THREAD

**Issue by alexvoina** [miguelpruivo/flutter_file_picker#899]
Hi! 

My app successfully uses File Picker to load certain files that are accessed during the same session. 

Ideally, because my app deals with lots of files (audio & videos) I would like to be able to work with the files that were once selected, **across multiple sessions** (i.e. saving the project state) without having to copy them to a folder on which I can get read permissions. 

I've seen a similar suggestion opened for Android. 

It seems there's an easy way to do this:
https://stackoverflow.com/questions/47902995/read-and-write-permission-for-user-selected-folder-in-mac-os-app

Can this feature be a part of File Picker?

**Comment by VCasecnikovs** [comment]
It would be a very nice feature!
