### ISSUE TITLE
error getting filename in recent files

### ISSUE THREAD

**Issue by tranduc3sao** [miguelpruivo/flutter_file_picker#900]
```
file_picker: 2.1.7

Flutter (Channel stable, 1.22.5, on macOS 11.5.2 20G95 darwin-x64, locale vi-VN)
    • Flutter version 1.22.5 
    • Dart version 2.10.4
```

On xiaomi, when recording the screen with the application of the file name system it will save as Screenrecorder-2021-12-01-10-15-47-81_1638328585484.mp4 but in recent files the video name becomes the application name and not file extension. How should I handle it?

**Platform**
- [] Android

**Comment by miguelpruivo** [comment]
I don’t see how can this be related with the plugin.
