### ISSUE TITLE
Unable to read files from getDirectoryPath URI

### ISSUE THREAD

**Issue by vaidarbhicontractor** [miguelpruivo/flutter_file_picker#902]
String? selectedDirectoryURI = await FilePicker.platform.getDirectoryPath();

URI =  content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fmedia%2Fcom.whatsapp%2FWhatsApp%2FMedia%2F.Statuses

how can I read all the data from above given specific folder URI ?

As its only returns folder URI but not give path for all files available in the selected folder ?

**Comment by miguelpruivo** [comment]
Hum, this shouldn't happen. Could you please try with a previous plugin version such as 4.2.0 and let me know if it still happens?

**Comment by vaidarbhicontractor** [comment]
Still happens.  When I click on Pick Folder (via FilePicker.platform.getDirectoryPath();) it only returns URI of that folder not their data. And even if I choosed "allowed" once permission popup ,  every time permission popup is open when I open an app.
 
I want to read all the files from the specific folder without user interaction with only 1 time permission popup . 

So I can show all the data in App UI every time whenever user open up the app.

**Comment by ankitparmar007** [comment]
The most recent Android API's, handle the files as a database of URI's, so we can handle it by adding support for cursor queries, as required by Android 11 or 11+ You can use SAF API to read data from a given URI but looks like package has no support for read data from a given DirectoryPath URI
I would like request @miguelpruivo to add support for read data using SAF API

**Useful Resources**
https://stackoverflow.com/questions/8646984/how-to-list-files-in-an-android-directory
https://developer.android.com/reference/android/provider/DocumentsProvider#public-methods
