### ISSUE TITLE
allowedExtensions documentation not updated in Wiki

### ISSUE THREAD

**Issue by tobiasht** [miguelpruivo/flutter_file_picker#905]
The documentation in the Wiki does not match the rest of the documentation for **allowedExtensions**. The Wiki should be updated without the use of period, in front of the file extensions. 

![image](https://user-images.githubusercontent.com/20655261/144430774-6d7b70ec-a4a6-45ac-839b-ce71398dd630.png)

**Comment by miguelpruivo** [comment]
Thank you and fixed, good catch.
