### ISSUE TITLE
How to enable pick from cloud storage option for Web & Desktop?

### ISSUE THREAD

**Issue by code-4-bread** [miguelpruivo/flutter_file_picker#906]
**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [x] Desktop

**Platform OS version**
What version did it happen?
MacOS & Chrome

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

<details>
<summary><b>Output Dump</b></summary>

The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/c4b/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (5 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/c4b/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 2 categories.

</details>

**Comment by miguelpruivo** [comment]
Hi, I’m not sure I understand your question.

**Comment by code-4-bread** [comment]
@miguelpruivo In readme, it has mentioned that we can `Pick files from cloud files (GDrive, Dropbox, iCloud)`. How can I enable this feature to be able to use the integration in Flutter Web and Desktop.

**Comment by miguelpruivo** [comment]
On web and desktop you can pick from wherever you want to. This applies only to mobile platforms where they need to fetch the files and allow 3rd party providers to be displayed to pick.

**Comment by debungle-it** [comment]
I have a similar problem using the API on the web: 

I can pick in the file browser any file, **including** from the folders linked by the Dropbox app or the G-Drive app to my local directory. Awesome ! ! !

However, if it's a cloud - stored file, I want only the Dropbox link, if it's a local file, I want to upload it to Dropbox and then get the local link. (likewise for the other cloud providers).

In that context, do you support Dropbox, G-Drive, OneNote, etc,.. or just local files, that other vendors wrote integrations for?
