### ISSUE TITLE
Q: what are "supported file extensions"?

### ISSUE THREAD

**Issue by 4ntoine** [miguelpruivo/flutter_file_picker#908]
**Describe the bug**
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
      dialogTitle: 'Open sketch',
      type: FileType.custom,
      allowedExtensions: [ 'ino' ],
    );
```
results in 
```
W/FilePickerUtils(10042): Custom file type ino is unsupported and will be ignored.
D/FilePickerUtils(10042): Allowed file extensions mimes: []
I/flutter (10042): [MethodChannelFilePicker] Platform exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)
E/flutter (10042): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)
```
The expected behaviour is to show the File picker dialog with all the files with extentions different from '.ino' not shown.

**Platform**

- [x ] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 10

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
      dialogTitle: 'Open sketch',
      type: FileType.custom,
      allowedExtensions: [ 'ino' ],
    );
```

**Details to reproduce the issue**
No special conditions. Let me know if you could not reproduce.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale ru-RU)
...
• No issues found!
```

**Additional context**

**Comment by 4ntoine** [comment]
I've also tried `type: FileType.any` but then i get the following:
```
E/flutter (10042): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: You are setting a type [FileType.any]. Custom extension filters are only allowed with FileType.custom, please change it or remove filters.
```

**Comment by 4ntoine** [comment]
BTW i think it was working as expected on desktop.

**Comment by miguelpruivo** [comment]
You’ll need to use `FileType.custom` with custom extensions. Some might not work, please read the FAQ.

**Comment by 4ntoine** [comment]
@miguelpruivo i've provided you the code snippet and as you can see i already use `FileType.custom`. Is is Android limitation.

**Comment by miguelpruivo** [comment]
@4ntoine sorry, I mean [troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-4) section.

Basically, there is only a couple of supported known MIME types. If you use one very specific you’ll need to remove the extensions property and use the `FileType.any` instead and then discard any extension that you don’t want your user to pick in your app after picking (you can iterate the extension property of the files).

**Comment by 4ntoine** [comment]
@miguelpruivo thanks for the explanation

**Comment by sunjhtrustmobi** [comment]
@miguelpruivo Why there is still an "All Files (*.*)" when I used FileType.image? And it doesn't work when I use FileType.custom and allowedExtensions.

**Comment by miguelpruivo** [comment]
When you use FileType.image the filters are ignored (it’s part of the API). When using custom, they are applied.

**Comment by sunjhtrustmobi** [comment]
@miguelpruivo I know. But when I use FileType.Image, there are two filters in FileExploer. One is Images(*.jpeg, *.png, *.gif) and the other one is All Files (*.*).

**Comment by miguelpruivo** [comment]
Hum, there should be only the images one. Where are you seeing this?

**Comment by sunjhtrustmobi** [comment]
Bottom of th window
![two filters](https://user-images.githubusercontent.com/77095254/147462168-8faae0f0-edee-4e9a-b6c8-c5b86ce16b99.png)
.

**Comment by miguelpruivo** [comment]
@philenius is there a way to prevent this?

**Comment by philenius** [comment]
@miguelpruivo , @sunjhtrustmobi this issue was already reported in #871 and fixed 26 days ago in `file_picker` v4.2.7. @sunjhtrustmobi  please upgrade your version of `file_picker`!

**Comment by sunjhtrustmobi** [comment]
@philenius Thanks a lot. I will try it.

**Comment by sunjhtrustmobi** [comment]
@philenius It does work. Thank you very much.

**Comment by MohammedSalehelShazly** [comment]
Hi, I have created my own app file extension, and will pick this extension only in (allowedExtensions) and make FileType.custom,
It's worked on desktop but not on android
any solutions instead make FileType.any !
@philenius @miguelpruivo
