### ISSUE TITLE
Android different files with same name && some file return id instead of file name

### ISSUE THREAD

**Issue by FaKenKoala** [miguelpruivo/flutter_file_picker#909]
**Platform**

- [✓ ] Android

**Describe the bug**

There are 2 bug in android.
1. The first bug is, when there are 2 files in different directories with same name, the method in [FileUtils.getFileName](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L58) will return same name. 
And then the method in [FileUtils.openFileStream Line 133](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L133) will create file with same path in cache directory. Before copying content from real path, [it checks if the cache file exists](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L135). If yes, it won't copy content.
So bang! If you select same name file last time, and the cache directory hasn't been cleared,  this time you get the wrong file. 

<strong><em>Maybe we can copy every time to solve the bug? </em></strong>

2. Some android devices in some directory, it will return the uri like `content://media/external/file/96668` instead of real path. So [getFileName](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L58) returns `96668` instead of correct file name, even though the content in the cache directory is right.
I found the gist [RealPathUtil by #tatocaster](https://gist.github.com/tatocaster/32aad15f6e0c50311626). It returns file's real path in different android version. But some files have [`java.lang.IllegalArgumentException: column '_data' does not exist`](https://gist.github.com/tatocaster/32aad15f6e0c50311626#gistcomment-2760298) problem.

<strong><em>We can use RealPathUtil to get real path, if it causes error, the we will use the plugin current getFileName method to solve the bug</em></strong>.

**Comment by FaKenKoala** [comment]
There is a [clearCache](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L87) method, so as for bug1, maybe it's the developers' responsibility to clear cache files before they select files.

**Comment by miguelpruivo** [comment]
Unfortunately there are some files where the name can’t be properly retrieved and since they’re cached you’ll receive their id instead. I’m afraid there isn’t much to do here. Sorry for any inconvenience.
