### ISSUE TITLE
Bad UTF-8 encoding found while decoding string: AwsS3Plugin: file path is: �PNG

### ISSUE THREAD

**Issue by junndobit** [miguelpruivo/flutter_file_picker#910]
First of all I am using Flutter for Web and I am using the AWS S3 plugin to put my files. This error occurs when I am trying to upload a file, specifically an image into the bucket. Here is my code:
`onTap: () {
                    chooseProfilePicture().then((result) {
                      if (result != null) {
                        //if web use bytes

                        Uint8List fileBytes = result.files.first.bytes!;
                        File file = File.fromRawPath(fileBytes);

                        uploadProfilePicture(file).then((value) {
                          setState(() {
                            isLoading = false;
                          });
                        });
                      }
                    });
                  },
Future<FilePickerResult?> chooseProfilePicture() async {
      return await FilePicker.platform.pickFiles(
          type: FileType.custom, allowedExtensions: ['png', 'jpg', 'jpeg']);
    }

Future<String> uploadProfilePicture(File selectedFile) async {
      String extension = 'png';
      String fileNameWithExtension = "$userId\\profile_pic.$extension";
      String result = "";

      AwsS3 awsS3 = AwsS3(
          file: selectedFile,
          fileNameWithExt: fileNameWithExtension,
          awsFolderPath: userImagesFolderPath,
          poolId: poolId,
          region: region,
          bucketName: bucketName);

      setState(() {
        isLoading = true;
      });

      try {
        result = await awsS3.uploadFile;
      } catch (e) {
        // print(e.toString());
        setState(() {
          isLoading = false;
        });
      }
      return result;
    }
`

I feel like it has something with the  Uint8List fileBytes = result.files.first.bytes and File.fromRawPath(fileBytes) because the compiler's additional info about the error is 
"The source bytes were:
[65, 119, 115, 83, 51, 80, 108, 117, 103, 105, 110, 58, 32, 102, 105, 108, 101, 32, 112, 97, 116, 104, 32, 105, 115,58, 32, 239, 191, 189, 80, 78, 71, 13, 10]"

Also there is no direct way in AWS S3 plugin using the bytes unlike the Firebase Storage example.

P.S. Forgive the weird way of putting the code here. I don't know why it didn't include the other code blocks

**Comment by miguelpruivo** [comment]
Hi! I’m not sure we can do much here since bytes are just raw bytes from the file, you’ll need to figure out how you’re going to use them and if your server/upload storage needs anything else.
