### ISSUE TITLE
Android issue - picked PlatformFile path.bytes is null, path.size shows correctly

### ISSUE THREAD

**Issue by selmaskopljakovic** [miguelpruivo/flutter_file_picker#913]
Hello everyone,

I have an issue with Android when picking file path.bytes are null. But, it prints size which is correct. The web works charming!

How to resolve this for Android?

Thank you,
Selma

**Comment by miguelpruivo** [comment]
You’ll need to set `withData` to `true` but I don’t recommend you to do unless you’re certain about what you’re doing.

On mobile you should instead open a `File(path).readBytesSync()` if you want to get the bytes in a safe way.

**Comment by selmaskopljakovic** [comment]
I already did this. Now it works on Android as well.  But, it would be good to have the same outcome of every method on all platforms.

**Comment by miguelpruivo** [comment]
@selmaskopljakovic you can’t have the same outcome in both because web platforms are different than mobile and desktop, each own has its limitations.

**Comment by selmaskopljakovic** [comment]
@miguelpruivo sorry, but you can. My customers expect that when they click on the download button to have a file downloaded at iPhone and Android and Web. So, I make that my app reacts the same and is successful for each platform.
I'm talking, that you can make that with a package for cross-platform to handle all cases and all platforms. It means, in the backend to override differences and nature of diff platforms.
