### ISSUE TITLE
after picking file from phone storage app is restarting on phone samsung M31 android version 11

### ISSUE THREAD

**Issue by Anupama-5105** [miguelpruivo/flutter_file_picker#914]
after picking file from phone storage app is restarting on phone samsung M31 android version 11

**Comment by miguelpruivo** [comment]
Hi. This is very vague and I’m not sure how it could be related with the plugin. Does that happen with all files?

**Comment by Anupama-5105** [comment]
> Hi. This is very vague and I’m not sure how it could be related with the plugin. Does that happen with all files?

yes, also same error is happening with image picker plugin also. when I select an image , the app get restarted.
also apps like whatsapp I can pick pictures, and there is no issues..
so I think it can be the issue of plugin.

**Comment by miguelpruivo** [comment]
If this happens with both image_picker and file_picker it can be because of Flutter is handling something related with native explorers. WhatsApp, on the other hand, uses its own explorer implementation which is a different case.

**Comment by Anupama-5105** [comment]
> If this happens with both image_picker and file_picker it can be because of Flutter is handling something related with native explorers. WhatsApp, on the other hand, uses its own explorer implementation which is a different case.

okay. Sir so how I can solve this issue. Is there any solution you can suggest?

**Comment by miguelpruivo** [comment]
> > If this happens with both image_picker and file_picker it can be because of Flutter is handling something related with native explorers. WhatsApp, on the other hand, uses its own explorer implementation which is a different case.
> 
> okay. Sir so how I can solve this issue. Is there any solution you can suggest?

Probably checking the crash logs or something and see if we can do something about it.

**Comment by Anupama-5105** [comment]
> > > If this happens with both image_picker and file_picker it can be because of Flutter is handling something related with native explorers. WhatsApp, on the other hand, uses its own explorer implementation which is a different case.
> > 
> > 
> > okay. Sir so how I can solve this issue. Is there any solution you can suggest?
> 
> Probably checking the crash logs or something and see if we can do something about it.

okay. Thanku

**Comment by johntyty912** [comment]
Hello, I'm having this problem too. and as @Anupama-5105 said, it happens with image_picker, I found a [#issue59395](https://github.com/flutter/flutter/issues/59395) on image_picker is about this, and seems it happens when you have "don't keep activities" on developer setting. And we might need to implement `retrieveLostData `method like [this](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker#handling-mainactivity-destruction-on-android)?

**Comment by Anupama-5105** [comment]
> Hello, I'm having this problem too. and as @Anupama-5105 said, it happens with image_picker, I found a [#issue59395](https://github.com/flutter/flutter/issues/59395) on image_picker is about this, and seems it happens when you have "don't keep activities" on developer setting. And we might need to implement `retrieveLostData `method like [this](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker#handling-mainactivity-destruction-on-android)?

sorry for the delay.
I have tried using retrieveLostData method , but that was not successful. did @johntyty912  used this method ?
