### ISSUE TITLE
Different Directory Picker on Windows

### ISSUE THREAD

**Issue by PeterNjeim** [miguelpruivo/flutter_file_picker#915]
Hello, I (as well as most others) seriously dislike the directory chooser/picker that was chosen for the Windows implementation of this plugin. I feel completely paralyzed using it. I always think of old programs when I see this kind of directory picker. Normally, a directory chooser should look exactly the same as a file chooser, just that the files aren't visible. This is how it's done in virtually every program I've ever used. Please consider updating to the newer Vista+ folder selector using one of the methods listed in the "edit" section of the top answer from this q&a: https://stackoverflow.com/questions/1922204/open-directory-dialog.

**Comment by PeterNjeim** [comment]
Well, I suppose 9 days is close enough to 14 for your bot there lol

**Comment by philenius** [comment]
@PeterNjeim I do understand your request. This

![Screenshot 2022-01-26 223210](https://user-images.githubusercontent.com/9049899/151250536-53112f76-01c5-4aa1-8975-25190e1556a4.png)

looks much better than that:

![image](https://user-images.githubusercontent.com/9049899/151250639-ea4f8a02-d729-4a74-8d2d-249aff8fd814.png)


Thank you for providing the link to StackOverflow. Unfortunately, we cannot reference .NET libraries (which must be pre-installed on Windows). The Win32 API is special in that these DLLs (`comdlg32.dll`, `shell32.dll`, etc.) seem to be present on every Windows installation.

Until now I couldn't figure out which API provides the modern dialog. Currently, we're using [SHBrowseForFolderW](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shbrowseforfolderw) from Win32 API which opens this old-fashioned dialog. In the remarks it says:
> For Windows Vista or later, it is recommended that you use IFileDialog with the FOS_PICKFOLDERS option rather than the SHBrowseForFolder function.  

Maybe the solution is to switch to `IFileDialog` is the solution. We'll just have to figure out how to use the `IFileDialog` API.

**Comment by PeterNjeim** [comment]
I think that's the correct next step

**Comment by b34st80y** [comment]
The pub.dev entry ( https://pub.dev/packages/file_picker ) even shows an example of the modern windows file picker: 

![image](https://user-images.githubusercontent.com/19982841/153626968-1c41fae2-2c43-4c48-a00d-ea570efccdbe.png)

I thought maybe I was doing something wrong when I got the one from windows Vista. :p

**Comment by PeterNjeim** [comment]
That's for file selection, not folder selection. And the Vista one is the new one, not the old one. I understand your comment, but since it doesn't really move the issue forward, there was really no point in posting it lol.

**Comment by philenius** [comment]
@PeterNjeim sorry for letting you wait so long. I have already found a working implementation of the modern folder picker dialog, but I have another open pull request which should be merged first. However, miguelruivo seems to be very busy as he hasn't even reacted on my latest pull request #953 within 13 days and I don't have permission to merge myself. Please be patient.

**Comment by philenius** [comment]
@PeterNjeim: the modern directory picker dialog is now available on pub.dev with `file_picker` version `4.5.0`
