### ISSUE TITLE
exif data for iOS "Live Photos"

### ISSUE THREAD

**Issue by fatherOfLegends** [miguelpruivo/flutter_file_picker#921]
I am working on a feature where I use the exif data in an image to populate some UI regarding the date the photo was taken. This works well except in the case where the photo selected is a Live Photo. 

I am not expert on this but this SO post indicates there is a jpeg available for live photos: https://stackoverflow.com/questions/36904108/apple-live-photos-metadata

I am curious if the code path can be adjusted to include the exif data from the original jpeg or if the temp jpeg can be updated with the correct exif data.

Thank you for your consideration.

**Comment by fatherOfLegends** [comment]
If I use the image_picker plugin, I am able to get the exif data. Looking at the source it appears like they needed to jump through a lot of hoops to retain this information. https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker

**Comment by fatherOfLegends** [comment]
For now I will be using both plugins. If I have permission granted I will use image_picker so I can have all metadata, if I do not have permission I will use file_picker to get the images because permission should not be required for this.

**Comment by miguelpruivo** [comment]
Hi! It could be interesting to have the exif data as part of the `PlatformFile`, however, I can see it being more useful on a dedicated image plugin (such as image_picker) while keeping focus on the file_picker to abstract file picks among all platforms.

To make it even more reliable, I’d have to implement the exif extraction on all platforms (web, desktop and mobile) which would take its time.

if you could combine this with an exif plugin it should fit the need while keeping the maintainance easier for both sides. I don’t know, let me know your thoughts.

**Comment by fatherOfLegends** [comment]
I am no suggesting adding exif data to the `PlatformFile` type, just encoding the exif data into the temporary jpeg whenever the user selects a "Live Photo".

**Comment by fatherOfLegends** [comment]
To be clear the jpeg already has a limited set of exif data, this is just making sure all of the properties from the Live Photo are included on the jpeg.

**Comment by miguelpruivo** [comment]
@fatherOfLegends oh, got it. I’ll have to investigate to see if it’s suitable/easy to add.

**Comment by rensvis** [comment]
I ran into an issue where an image uploaded from an iPhone did not contain the EXIF tags I was expecting, where it had been working fine before. With the help of this issue I figured out it had to do with the fact that this happened when selecting Live Photos. Would be great if all the EXIF tags could be included. For now I'll look into the image_picker plugin.
