### ISSUE TITLE
Receive Temporary file could not be created when trying to upload photo on Simulator Iphone 12

### ISSUE THREAD

**Issue by dancb10** [miguelpruivo/flutter_file_picker#923]
I'm trying to pick a photo from my Iphone simulator but I receive the following error. Below is the Flutter code:
```  
List<PlatformFile>? _pickedPhoto;

    try {
      _pickedPhoto = (await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: false,
      ))
          ?.files;
    } on PlatformException catch (e) {
      print("Unsupported operation" + e.toString());
    } catch (ex) {
      print(ex);
    }

    if (_pickedPhoto != null) {
      return _pickedPhoto[0];
    }
```

And below is the error I receive
`flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)`

Any thoughts on how to pass this? Tried as well with Iphone Simulator 13 same issue.

**Comment by point-source** [comment]
I am also having this issue. Same code, same simulator.

**Comment by samerset-rmn** [comment]
Same issue. Has anyone tried to reproduce it on the real iPhone 12/13? To find out if the problem is only with the simulator or the whole platform.

**Comment by samerset-rmn** [comment]
It seems that `allowCompression: false` parameter somehow resolves that issue

**Comment by dancb10** [comment]
@samerset-rmn doesn't work for me. below is my code:
`      _pickedPhoto = (await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: false,
        allowCompression: false,
      ))
          ?.files;`

I still receive:
`flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
flutter: Unsupported operationPlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)`

**Comment by point-source** [comment]
> It seems that `allowCompression: false` parameter somehow resolves that issue

This unfortunately did not work for me

**Comment by miguelpruivo** [comment]
Hi, does this work in real devices?

**Comment by masoudk2000** [comment]
I have the same issue

**Comment by dancb10** [comment]
Any news on this? was someone able to make it work?

**Comment by miguelpruivo** [comment]
I’m still waiting for someone to tell me if this happens on a real device.

**Comment by dancb10** [comment]
So I've tested on a physical device and I can pick the image but I get 
"[ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it."

Seems to be related to https://github.com/miguelpruivo/flutter_file_picker/issues/405
So I cannot validate if it works for physical device since it throws this error

**Comment by miguelpruivo** [comment]
Hi. I already checked this and doesn’t seem to cause any effect. Also, I couldn’t find a way to prevent this error and I’m not sure what causes it.

**Comment by dancb10** [comment]
What do you mean any effect? You mean that you can pick photos even if this error is thrown?

**Comment by miguelpruivo** [comment]
@dancb10 that’s correct.
