### ISSUE TITLE
No error or dialog if filename has an incorrect character

### ISSUE THREAD

**Issue by tobiasht** [miguelpruivo/flutter_file_picker#926]
I was trying to run the following code on Windows. 
```dart
final String? outputFile = await FilePicker.platform.saveFile(
    dialogTitle: 'Save as:',
    fileName: "Exported: $deviceName.json"
    allowedExtensions: ["json"],
    type: FileType.custom,
  );
```
The dialog did not open and it only returned null. I figured out that it was because i was using ":" in the filename. This might be an invalid character and might be by design. Either way, I believe it should throw an error, to easily figure out the problem.

**Comment by philenius** [comment]
@tobiasht I'm sorry, but the use of a colon `:` in a file name is generally not allowed on Windows, as Microsoft officially states here:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

> [...] except for the following:
> 
> * The following reserved characters:
>    * `<` (less than)
>    * `>` (greater than)
>    * `:` (colon)
>    * `"` (double quote)
>    * `/` (forward slash)
>    * `\` (backslash)
>    * `|` (vertical bar or pipe)
>    * `?` (question mark)
>    * `*` (asterisk)
> 
> * Integer value zero, sometimes referred to as the ASCII NUL character.
> 
> * Characters whose integer representations are in the range from 1 through 31, except for alternate data streams where these characters are allowed. For more information about file streams, see File Streams.
> 
> * Any other character that the target file system does not allow.


Windows Explorer doesn't even allow to create a file with a colon in its name:
![grafik](https://user-images.githubusercontent.com/9049899/146637465-c4cb73e5-1716-48aa-be02-547d9c9c32a1.png)

**Comment by tobiasht** [comment]
Yeah i understand that, but it would be more helpful to raise an invalid character exception. If that is possible. It will save people a lot of troubleshooting in the future.

**Comment by miguelpruivo** [comment]
@philenius do you plan to do anything regarding this?

**Comment by philenius** [comment]
@miguelpruivo please excuse my late reply. Merge request #940 adds the requested exception.
