### ISSUE TITLE
Permissions dialog not opening in some situations

### ISSUE THREAD

**Issue by davidmartos96** [miguelpruivo/flutter_file_picker#929]
**Describe the bug**
Hello, I've recently been contacted by one of the users of my app telling that a feature that opens the file picker flashes the screen and closes. After talking with him he saw that the Media permissions were not set in the app settings, so the file picker was failing because of that.
The device was a Samsung Galaxy S20 and he mentioned he used Samsung Smart Switch to migrate the data from a different phone. I'm wondering if this could interfere with the permissions logic in the package that prompts the user when the permissions are not set. In this case it didn't seem to appear automatically.

**Platform**

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 11

Flutter 2.5.3
file_picker: 4.2.3

Sorry for the lack of more information. I just wanted to share the issue in case there is a strange bug in the library. It could very well have been a localized issue in this user's phone.

**Comment by miguelpruivo** [comment]
Hi, the permissions are handled at runtime using the native API. I suspect something related with Samsung rom. Could you replicate it in another device?

**Comment by davidmartos96** [comment]
> Hi, the permissions are handled at runtime using the native API. I suspect something related with Samsung rom. Could you replicate it in another device?

I'm not able to reproduce it on my devices. This was discovered in a conversation with one of the users of the app.

**Comment by miguelpruivo** [comment]
Not being able to replicate it makes it very difficult to debug and fix. If a crash is happening check a crashlytics of your app or something in order to get the stack trace.

You can always try to ask him/her to connect the phone and use the `adb logcat` to look for an exception, but it can be a bit technical.

**Comment by davidmartos96** [comment]
> Not being able to replicate it makes it very difficult to debug and fix. If a crash is happening check a crashlytics of your app or something in order to get the stack trace.
> 
> You can always try to ask him/her to connect the phone and use the `adb logcat` to look for an exception, but it can be a bit technical.

That's understandable. Feel free to close the issue. If I get more information like a stack trace I'll post here.
Thanks!

**Comment by miguelpruivo** [comment]
Let me know if you find something else and I’ll open right away. Thank you!
