### ISSUE TITLE
Pdf file picket not  working as expected in Android

### ISSUE THREAD

**Issue by sathishmscict** [miguelpruivo/flutter_file_picker#930]
**Describe the bug**
FileType.custon with "pdf" file extension working fine with google drive but with File Manager it is not working as expected. I had recorded video for more clarity. Please let me know if you need more details on this issue.

**Platform**

=> Android - 10 with File Manager
**Platform OS version**
What version did it happen?
Android 10 : Nokia 6.1 plus device

**Details to reproduce the issue**
I had attached screen recording , to produce this issue.

**Screenshots and/or video**
Video file URL attached, please refer it.
[https://drive.google.com/file/d/1NlwJ9ZGm7b7BnyH9DYW5nlN0B3X-83fp/view?usp=sharing](https://drive.google.com/file/d/1NlwJ9ZGm7b7BnyH9DYW5nlN0B3X-83fp/view?usp=sharing)

**Flutter Version details**
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1415], locale en-US)
    • Flutter version 2.8.0 at E:\Flutter Sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (3 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

**Comment by miguelpruivo** [comment]
It looks overall ok to me. I can't give you support on 3rd party file explorers like you're using in the video.

This plugin asks the native platform to launch a file explorer and handle the requests/parameters. Some explorers (like the default/native one) is well constructed, whereas others can simply ignore some parameters.

That's up to each file explorer developer to make it better.

Sorry for any inconvenience.
