### ISSUE TITLE
Folder picker does not show cloud drives

### ISSUE THREAD

**Issue by waqdev786** [miguelpruivo/flutter_file_picker#937]
Hi,
I am using filepicker file_picker: ^4.3.0 and cloud drives for folder picker

**Describe the bug**
I am using andrio version 11 and if i use file picker then it shows me the cloud drives e.g. google drives etc but if use folder picker then it shows only local system storage and does not show cloud folders. 
Thanks

**Comment by miguelpruivo** [comment]
That's a normal behaviour and limitation. You need to use absolute (local) paths.
