### ISSUE TITLE
How to integration test picking a file (in Web)?

### ISSUE THREAD

**Issue by timovandeput** [miguelpruivo/flutter_file_picker#941]
Is there a convenient way to "bypass" the native file picking (to select a predefined test file) such that the widget can be used inside integration tests?

**Comment by miguelpruivo** [comment]
@philenius since you’ve worked with the tests on desktop, do you think that this is possible?

**Comment by philenius** [comment]
Sorry to disappoint you, but so far I've only written unit tests...

Maybe you can mock or stub the part of code which calls `FilePicker.platform.pickFiles()` and thereby make it return your predefined test file? On StackOverflow, some people claim (https://stackoverflow.com/a/43897865, https://stackoverflow.com/a/57582830) that you could mock the method channel of `file_picker`. I don't understand much of method channels so I tried it only briefly:

```dart
  test('pickFiles()', () async {
    const channel = MethodChannel('miguelruivo.flutter.plugins.filepicker');

    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      return PlatformFile(name: "test.txt", size: 123);
    });

    final result = await FilePicker.platform.pickFiles();

    expect(result?.files.first.name, equals("test.txt"));

    channel.setMockMethodCallHandler(null);
  });
```

With this approach, the file picker dialog doesn't open (which is your desired effect) but somehow the handler function is never called and therefore `pickFiles()` always returns null :thinking:
