### ISSUE TITLE
SaveFile Dialog failing when renaming in Windows 10

### ISSUE THREAD

**Issue by SirFalk** [miguelpruivo/flutter_file_picker#954]
FilePicker Version: 4.3.3
Platform: Desktop / Windows 10 

Description:
How to reproduce:

1. (Optional:) Enable "show file extension" in Windows explorer
2. Use the saveFile function with a custom file ending (for me: aescryptor)
String? path = await FilePicker.platform.saveFile(
          fileName: 'Encrypted20220203123927514998.aescryptor',
          dialogTitle: 'save_dialog_title',
          type: FileType.custom,
          allowedExtensions: ['aescryptor'],
        );
to save your File.

![image](https://user-images.githubusercontent.com/57640094/152337222-d477e654-350e-4224-a5b1-87f68a0dcf72.png)

3. Delete file name and give it a file name like 'test'. 

![image](https://user-images.githubusercontent.com/57640094/152337301-b04cf7ed-54ba-446a-9d78-6877bd9f3a34.png)

4. Hit "Save" ("Speichern") to get the path. 
5. Expected path: 'C:\Users\myname\Downloads\test.aescryptor'
   Actual path: 'C:\Users\myname\Downloads\test\\.aescryptor'

I also sometimes got 'C:\Users\myname\Downloads\test\aescryptor' (without the dot) or 'C:\Users\myname\Downloads\test' while testing. So basically every variation you don't want.

Edit: after some more testing, it also has arbitrary results when you have a file ending longer than 5 characters. So sometimes, it would also return 'C:\Users\myname\Downloads\test\\yptor'.

They way I know it from other applications, it should automatically attach the correct file extension, because it's the only allowedExtension. It's even worse when you disable 'show file extension' in Windows explorer, because you won't even be able to maunally see and add the extension.

If you have any questions about if please let me know.

**Comment by philenius** [comment]
Thanks for reporting this bug. Only one question: you wrote

> 5. Expected path: 'C:\Users\myname\Downloads\test.aescryptor'
Actual path: 'C:\Users\myname\Downloads\test.aescryptor'

I assume you meant to say that the actual path has no file extension respectively is missing the file extension?

**Comment by SirFalk** [comment]
> Thanks for reporting this bug. Only one question: you wrote
> 
> > 5. Expected path: 'C:\Users\myname\Downloads\test.aescryptor'
> >    Actual path: 'C:\Users\myname\Downloads\test.aescryptor'
> 
> I assume you meant to say that the actual path has no file extension respectively is missing the file extension?

Lol I didn't know "\" could be escaped here. I typed "\.aescryptor" but it made it say ".aescryptor". I edited it now.

**Comment by philenius** [comment]
@SirFalk, I will work on this issue in April because I'm busy right now with my Master's thesis. I plan to refactor the implementation of this dialog anyway. Hopefully, this will resolve your usability issue.

**Comment by SirFalk** [comment]
> @SirFalk, I will work on this issue in April because I'm busy right now with my Master's thesis. I plan to refactor the implementation of this dialog anyway. Hopefully, this will resolve your usability issue.

Awesome, sounds good!
