### ISSUE TITLE
File_picker not working properly in iOS 15

### ISSUE THREAD

**Issue by J4ckSk3le7on** [miguelpruivo/flutter_file_picker#955]
**Describe the bug**
I am currently using the package with iOS 15.1 and iPadOS 15.1.
It runs the file chooser, but when I add the file chooser it doesn't work and just crashes.

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
iOS 15.1

**How are you picking?**
Run the selector, it opens the native dialog to select, select the file and click the 'add' button.
after that the app simply crashes.
Please, post the snippet here

**Details to reproduce the issue**
only run the package on a device running iOS 15

**Error Log**
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 53075
This was attempt #50. Will retry in 0:00:01.600000.
VERBOSE: application/scene willResignActive
DEBUG: Application Backgrounded started
DEBUG: TimeProcessor <OSUnattributedFocusTimeProcessor: 0x28311d740> for session attributed 0
DEBUG: sendOnFocusCall unattributed with totalTimeActive 96.299715
DEBUG: OSBaseFocusTimeProcessor hasMinSyncTime getMinSessionTime: 60 activeTime: 96.299715
DEBUG: beginBackgroundFocusTask start
VERBOSE: HTTP Request (OSRequestOnFocus) with URL: https://api.onesignal.com/players/3d70eb4a-8503-11ec-b590-e60c3a1d5a45/on_focus, with parameters: {
  "direct" : false,
  "app_id" : "3b6c94ae-7594-42b3-b849-dfb7fb81fd67",
  "device_type" : 0,
  "type" : 1,
  "net_type" : 0,
  "active_time" : 96.299714803695679,
  "state" : "ping"
}
VERBOSE: network response (OSRequestOnFocus): {
    id = "3d70eb4a-8503-11ec-b590-e60c3a1d5a45";
    success = 1;
}
Request <OSRequestOnFocus: 0x2838a57a0> success result {
    id = "3d70eb4a-8503-11ec-b590-e60c3a1d5a45";
    success = 1;
}
DEBUG: sendOnFocusCallWithParams unattributed succeed, saveUnsentActiveTime with 0
DEBUG: OSUnattributedFocusTimeProcessor:endDelayBackgroundTask:1
DEBUG: endBackgroundFocusTask called
VERBOSE: application/scene didEnterBackground

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
```
j4ck@MacBook-Pro-de-Jorge ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-arm, locale es-419)
    • Flutter version 2.8.1 at /Users/j4ck/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/j4ck/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPad de Jose Angel (mobile) • 6b795b6d7487d58be00e179dae38b5fa87e0f9f4 • ios            • iOS 15.1 19B74
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

**Comment by miguelpruivo** [comment]
Hi, by looking at the logs I don’t think it’s related with the file_picker. Have you managed to solve it?
