### ISSUE TITLE
Freezing on macOS M1

### ISSUE THREAD

**Issue by tannermeade** [miguelpruivo/flutter_file_picker#957]
**Describe the bug**
File picker freezes often on macOS M1 devices on v 4.3.3 (and many versions before). This issue (https://github.com/miguelpruivo/flutter_file_picker/issues/778) should be reopened or this new issue should be used to track it. 

**Platform**

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Desktop

**Platform OS version**
What version did it happen?
Several versions, but confirmed on macOS 11.6 (20G165)

**How are you picking?**
```
var pickedFiles = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
      allowMultiple: true,
);
```

**Details to reproduce the issue**
On an M1 macOS, use the FilePicker in most any way, specifically you can use multiple files and only allow CSV and it freezes often.

**Error Log**
The app freezes. For a few seconds, the cursor stays as a click cursor until it turns to the turning beachball. Only way to stop it is to force close the app or stop the run time.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Has happened on several channels for a long time and the last several versions of Flutter, but here is my current doctor:
```
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6 20G165 darwin-arm, locale en-US)
    • Flutter version 2.10.0 at /Users/tannermeade/Coding/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tannermeade/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] VS Code (version 1.64.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Additional context**
This issue has been reported several times in this issue: https://github.com/miguelpruivo/flutter_file_picker/issues/778

**Comment by henry2man** [comment]
Hi, just my 2 cents. I'm having issues like this using both Flutter Desktop for MacOS (using a MBP M1) and Flutter Web. 

In my case I've detected that first open usually works but subsequent tries  freezes.

As a workaround I've implemented a Drag&Drop zone. It's not perfect but it works as a replacement.

**Comment by tannermeade** [comment]
@philenius thank you for the detailed help. I haven't been able to get it to freeze with just the command. I'll have to figure out how to debug it further and your direction is helpful for that. Thank you!

**Comment by mgenware** [comment]
Please stop the stale bot from closing unresolved issues. I ran into this from time to time on an M1 when doing:
```dart
FilePicker.platform.getDirectoryPath()
```

**Comment by miguelpruivo** [comment]
> Please stop the stale bot from closing unresolved issues. I ran into this from time to time on an M1 when doing:
> 
> ```dart
> FilePicker.platform.getDirectoryPath()
> ```

@philenius answer was pretty straight forward. Neither I or him can't provide any help regarding this at the moment because seems like we both don't own M1 Macs and makes it harder to replicate or even diagnose what can be done in order to prevent/fix it.

Anyone with a M1 Mac experiencing this issue, is welcome to contribute and issue a PR with a fix for it.

**Comment by oddko** [comment]
M1 Pro user here, had the issue as well but it does not seem to happen anymore on the current beta channel of flutter (2.13-pre as I speak).

**Comment by jhack7** [comment]
I am having this issue as well. I am amble to consistently reproduce the issue when calling `getDirectoryPath` if finder is open in the path to the default path of `getDirectoryPath`

unfortunately up to this point I haven't been able to debug the actual issue, I am still troubleshooting but I am curious to see if others are able to reproduce in a similar way

**Comment by FlorianGrollich** [comment]
I was able to reproduce it by calling pickFiles in an onTap function in a GestureDetector. But it only freezes if the initial directory is Recents.

Another way to reproduce it is if you call the pickFiles with the onTap Function of the GestureDetector and spam click it, but that obviously does make more sense. ^^

**Comment by sergioisair** [comment]
hello, any solution for freezing?

**Comment by stephane-archer** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/1628
