### ISSUE TITLE
Image is not getting loaded

### ISSUE THREAD

**Issue by memoriasIT** [miguelpruivo/flutter_file_picker#958]
**Describe the bug**
This bug seems to be happening only in IOS, but feel free to double check. I tried on Android as well.

There's an image that won't get loaded. The image picker will open and the selection happens but if you actually debug the _getPath() method that's inside your package you can see that the result variable is actually an empty array (no image is actually loaded).

I only encountered this for this image, others seem to work fine. I made a video with both scenarios see it below.

The image that won't load is the one that comes per default in IOS 15 emulator with purple flowers. Again, see video below for reference.

**Platform**

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
IOS 15.0 emulator

**How are you picking?**
I tried loading in memory and by picking multiple files, but the image won't load anyways.
If several files are picker they all will be picked but this one.

final image = await FilePicker.platform.pickFiles(
      type: FileType.image,
      // withData: true,
      // allowMultiple: true,
    );

**Details to reproduce the issue**
1. Call the method pickFiles
2. Select the image
3. result variable in function _getPath() will be an empty array []

**Error Log**
No errors

**Screenshots and/or video**
Video:
https://streamable.com/fugpc2

**Flutter Version details**
Important to know that this is version 2.1.7, the last one available without null safety.

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 12.0.1 21A559 darwin-x64, locale en-ES)
    • Flutter version 1.22.6 at /Users/-/fvm/versions/1.22.6
    • Framework revision 9b2d32b605 (1 year ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/-/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • SM G781B (mobile)      • -                          • android-arm64 • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • - • ios           • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
```
**Additional context**
Thanks for this package, it solved me some problems with the IOS 14 changes ❤️

**Comment by miguelpruivo** [comment]
Hi! That’s a known issue related with HDR pictures since iOS 14 on simulators, not Flutter itself. That shouldn’t happen in a real device. You should ignore it. :)
