### ISSUE TITLE
No video/visual when picking/recording videos on mobile web browser.

### ISSUE THREAD

**Issue by westdabestdb** [miguelpruivo/flutter_file_picker#963]
**Describe the bug**
When a video is recorded or picked from the gallery on mobile web, there is audio but no video.

**Platform**

- [ ] Android
- [ ] iOS
- [X] Web - mobile web
- [ ] Desktop

**Platform OS version**
Android 12

**How are you picking?**
```
 openFileExplorer() async {
    message.value = "";
    List<PlatformFile>? _paths;
    FileType inputType = FileType.media;
    if (type == PostType.VIDEO) inputType = FileType.video;
    if (type == PostType.IMAGE) inputType = FileType.image;
    try {
      _paths = (await FilePicker.platform.pickFiles(type: inputType, withData: true))?.files;
      postMedias[selectedMediaIndex] = UploadMedia(
          name: _paths!.first.name,
          bytes: _paths.first.bytes,
          path: _paths.first.path);
    } on PlatformException catch (e) {
      print("Unsupported operation" + e.toString());
    } catch (ex) {
      print(ex);
    }
  }
```

**Details to reproduce the issue**
I can pretty much pick images/videos on the web browser on the desktop and works well. However on the mobile web, images work fine but when I try to record or pick a video from the gallery, there is audio but there isn't the video.

**Comment by miguelpruivo** [comment]
Does that happen with safari or chrome?

**Comment by westdabestdb** [comment]
Actually it's both mobile browsers.
