### ISSUE TITLE
iOS FilePickerResult status

### ISSUE THREAD

**Issue by JiaoLiu** [miguelpruivo/flutter_file_picker#967]
I encourage you to add new suggestions that you think that can make file_picker even a better package.

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

Problem steps:
1、turn off the cellular data access of 'PHOTO' app.
2、pick some thumbnail images. Can't get the full data of the images.

result:
1、still return a FilePickerResult, but count = 0,  files = [];
2、debug console show some error message but I can't catch them.

**Comment by miguelpruivo** [comment]
That's probably because the photos you are picking are stored into the iCloud and you are preventing cellular access to it. If you don't have wifi, it won't be possible to fetch them.
