### ISSUE TITLE
Question: Can't pick cloud directory

### ISSUE THREAD

**Issue by caokietbk** [miguelpruivo/flutter_file_picker#969]
Hi, I can pick files from the cloud (in my case, it is Dropbox), but when I use FilePicker.platform.getDirectoryPath(), I can't select the Dropbox directory. (gray color).

Is this not supported, or am I missing some configuration?

I hope someone can answer this question for me.

Thank you for this great library 💯.

**Comment by miguelpruivo** [comment]
Hi, unfortunately this is not supported. It's not possible to pick remote directories.
