### ISSUE TITLE
Can we get the file path of the actual file, instead of the cached copy?

### ISSUE THREAD

**Issue by pvsvamsi** [miguelpruivo/flutter_file_picker#973]
Need to get the absolute path of the selected file. Currently we are getting the cached file path

**Comment by miguelpruivo** [comment]
You can't since SDK 30 on Android. That's a platform limitation. The recommended way to handle files on Android is through its URIs which Dart doesn't support. You can read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ) in the second question.
