### ISSUE TITLE
gpx file extention not allowed in allowedExtensions

### ISSUE THREAD

**Issue by basvdijk** [miguelpruivo/flutter_file_picker#975]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
Currently opening the `.gpx` file extension is not allowed. 

**Platform**

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 12

**How are you picking?**
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: ['gpx'],
);
```

**Details to reproduce the issue**
Use the snippet above to pick a `.gpx` file

**Error Log**
```
 [MethodChannelFilePicker] Platform exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.all instead., null, null)
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
```
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.3 20G415 darwin-x64, locale en-NL)
    • Flutter version 2.10.1 at /usr/local/Caskroom/flutter/2.0.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bas/Development/android/android-sdk/
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/bas/Development/android/android-sdk/
    • ANDROID_SDK_ROOT = /Users/bas/Development/android/android-sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • SM A528B (mobile) • RZCT109BTNM • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Additional context**

**Comment by vanceism7** [comment]
This seems to be a problem for custom file extensions in general

**Comment by basvdijk** [comment]
@vanceism7 it is indeed.

**Comment by miguelpruivo** [comment]
Yes, unfortunately we are always limited to what the native platforms (or pickers) handle as valid MIME types. My suggestion is to just use `FileType.any` (and not providing any filters) and then discard the unwanted ones after picking. You can iterate the extensions of the picked files.

Something that can be done as well, is implement on the plugin side this feature but I left this for the dev so you can always opt to display an error message or something if the user picks invalid files.

**Comment by sqcsabbey** [comment]
We'd like to be able to import a sqlite db (we'd actually like to use a custom extension for our db file) into our app, but that isn't supported (at least on Android, it looks like it will work on iOS, and I haven't tried other platforms). I looked through the code, and I couldn't figure out if filtering by system-supported mime types was necessary, would it be possible to just remove this existing mime type check?
