### ISSUE TITLE
it doesn't allow CSV files.

### ISSUE THREAD

**Issue by AkshayDilod** [miguelpruivo/flutter_file_picker#976]
```dart
  Future<File?> pickFile() async {
    File? file;
    try {
      FilePickerResult? result = await FilePicker.platform.pickFiles(
        allowedExtensions: ['csv'],
        type: FileType.custom,
      );

      if (result != null) {
        file = File(result.files.single.path ?? '');
        final input = File(file.path).openRead();
        print(file);
        final fields = await input
            .transform(utf8.decoder)
            .transform(const CsvToListConverter())
            .toList();
        print(fields);
      } else {
        print('Canceled');
      }
    } catch (_) {}
    return file;
  }
```

**Comment by AkshayDilod** [comment]
Android

**Comment by AkshayDilod** [comment]
> @AkshayDilod , please use our issue template. Which platform are on? Android, iOS, Linux, macOS, or Windows?

Android

**Comment by miguelpruivo** [comment]
Hi, `csv` files aren't resolved with a valid MIME type (natively). You'll have to use `FileType.all` and then discard the extensions you don't want to.

There are other issues similar to this if you search on the repo.

Sorry for any inconvenience.

**Comment by vishalpatel1327** [comment]
hello, Is there any updates?

   var result = await FilePicker.platform
                  .pickFiles(type: FileType.custom, allowedExtensions: ['csv']);
              if (result == null) return;
              
              that code working good  for internal folder
              
              but when i open download folder csv is disable.
              
              
              
![image](https://user-images.githubusercontent.com/14329287/190376371-68d73415-7cba-4850-8985-b98282f6fbff.png)

              
![image](https://user-images.githubusercontent.com/14329287/190376192-c963add6-bcfc-4374-aca7-48ec543a4725.png)

**Comment by PhilippS93** [comment]
same problem here

**Comment by philenius** [comment]
Sorry, I can't help you with Android-related bugs. Miguel is the expert.
