### ISSUE TITLE
How to pick file or directory with the same dialog?

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [miguelpruivo/flutter_file_picker#977]
How to pick a file or directory with the same dialog?

**Comment by philenius** [comment]
@Ayad-Ben-Saliem , you mean how to open a dialog that allows the user to select either a directory or file at the same time? To the best of my knowledge, this kind of dialog does not exist.

You can either open a dialog for picking files via `FilePicker.platform.pickFiles()` or for picking a directory via `FilePicker.platform.getDirectoryPath()`.
