### ISSUE TITLE
allowedExtensions issue

### ISSUE THREAD

**Issue by ghaithvaroxez** [miguelpruivo/flutter_file_picker#979]
when i filter the types of files that i can pick there is an issue when using IOS devices .
if i allow only one type ,i can pick any type of file if i long press on the file icon then the OS will show options and in this scenario if i press on the file the package pick the file and everything working fine i have the file in picked files also...
i think this should be fixed

https://user-images.githubusercontent.com/80856266/155880802-b0ecc137-6a57-4f64-8c77-3b608286711c.mov

and this is my code :
` FilePickerResult? result =
                                    await FilePicker.platform.pickFiles
                                      (
                                      type: FileType.custom,
                                  allowedExtensions: ["jpg","docx","doc","png"],
                                  allowMultiple: true,
                                );`

**Comment by miguelpruivo** [comment]
Hi, sorry, I don't actually get your issue. When you have `allowMultiple` set to `true` that means that you can indeed pick multiple files.
