### ISSUE TITLE
On iOS, when FileType.audio, Files app should be opened instead of Apple music app

### ISSUE THREAD

**Issue by jcblancomartinez** [miguelpruivo/flutter_file_picker#986]
Hi,

I'm using file_picker to select audio files. For Android, it works as expected. However, for iOS, when invoking 

`FilePicker.platform.pickFiles(type: FileType.audio);`

, it opens Apple music app instead of Files app. I would like to be able to configure this behaviour.

I want users to be able to select any audio file like voice memos recorded with Voice Memos app.

Thanks.

**Comment by jcblancomartinez** [comment]
Why are u closing it?

**Comment by miguelpruivo** [comment]
When using `FileType.audio` the correct behaviour as described in the Wiki is actually opening the Apple Music app to let you pick files from that library (for example, users with music apps that want to take advantage from it).

If you want to open the Files app, you should use:
```
FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['mp3', 'aac', 'ogg', 'mp4', 'wav', 'flac']);
```
Or any other formats that might fit your needs.

**Comment by jcblancomartinez** [comment]
@miguelpruivo thanks for the response. For future reference, could you please paste the link to the wiki you are referring to?

Thanks.

**Comment by timoffenhaeusser** [comment]
As described in the wiki on iOS, the music app needs to be installed for `FileType.audio` to work. But what happens if it is not installed. 

I want to open the music app as default, but only if the user has not installed the app, I want to open the file system instead. Is there a way to see from the error message or something if the app is installed, and if not then call filepicker with type custom instead?
Thanks for the help!

**Comment by Cornfritter** [comment]
@timoffenhaeusser - Did you find a solution? I have the same issue.

@miguelpruivo - What's the status of this? It doesn't look like FilePicker throws an error if the Music app isn't present. Nothing happens, then if I try `pickFiles` again, I get:

> [MethodChannelFilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null, null)

Thanks!!
