### ISSUE TITLE
Prompt to confirm saving when file already exists

### ISSUE THREAD

**Issue by merilec** [miguelpruivo/flutter_file_picker#989]
When selecting a location and file name to save a file to (via `saveFile`), a file with that file name might already exist. The picker should then prompt the user to confirm saving and replace it, similar to how it is done in many other programs.

![image](https://user-images.githubusercontent.com/99778788/156919044-1d5687d5-3189-4227-84da-6aa3b9501067.png)

**Comment by bhlin790** [comment]
Is there any version of this feature planned to be implemented?

**Comment by philenius** [comment]
@bhlin790, sorry for keeping you waiting so long. Contributing to open-source has been a low priority for me for the last 12 months.
The Linux implementation is ready. Now, I'm working on the macOS and Windows implementation.

**Comment by philenius** [comment]
Will be implemented with v5.2.7. Now, we're waiting for approval from Miguel :wink:
