### ISSUE TITLE
Picking large video fails :- Failed to [DocumentManager]associate thumbnails for picked URL

### ISSUE THREAD

**Issue by foxy17** [miguelpruivo/flutter_file_picker#990]
Picking a video in IOS fails with this error . The code gets stuck here and does not proceed forward.
It works fine for smaller video but fails only for this one. All the videos tested were mp4 extension MPEG-4. The only difference between this and others was that the failing video was of **AVC** codec while others were **AVC1**

`  [DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Data/Application/1E2C84F6-BA3B-4416-B1E0-88D8EE89B938/Documents/Downloads/Day%201%20-%2022%20Jan%2022.mp4 with the Inbox copy file:///private/var/mobile/Containers/Data/Application/8F187F32-A53D-45AA-9339-8D96B6F7D958/tmp/com.qoohoo.qoohoo-app-Inbox/Day%201%20-%2022%20Jan%2022.mp4: Error Domain=QLThumbnailErrorDomain Code=102 “(null)” UserInfo={NSUnderlyingError=0x282e26af0 {Error Domain=GSLibraryErrorDomain Code=3 “Generation not found” UserInfo={NSDescription=Generation not found}}}`

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
IOS 15.3.1 

**How are you picking?**
```
final result = await Picker.FilePicker.platform.pickFiles(
      type: Picker.FileType.any,
      allowCompression: false,
      withData: false,
    );
```

**Details to reproduce the issue**
The video was downloaded from drive its of around 247 mb, saved on the iphone and not on icloud. Testing on real device.

**Error Log**
```
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Data/Application/1E2C84F6-BA3B-4416-B1E0-88D8EE89B938/Documents/Downloads/Day%201%20-%2022%20Jan%2022.mp4 with the Inbox copy file:///private/var/mobile/Containers/Data/Application/8F187F32-A53D-45AA-9339-8D96B6F7D958/tmp/com.qoohoo.qoohoo-app-Inbox/Day%201%20-%2022%20Jan%2022.mp4: Error Domain=QLThumbnailErrorDomain Code=102 “(null)” UserInfo={NSUnderlyingError=0x282e26af0 {Error Domain=GSLibraryErrorDomain Code=3 “Generation not found” UserInfo={NSDescription=Generation not found}}}```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.8.1 at /Users/foxy17/code/flutter_versions/flutter_2.2.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2


[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)


[✓] Connected device (1 available)
    • Arnav's iPhone (mobile) • 00008030-00125DA81A10C02E • ios • iOS 15.3.1 19D52

**Additional context**
Add any other context about the problem here.

**Comment by miguelpruivo** [comment]
Hi, could you please provide me a sample project with a file?

Thank you.

**Comment by foxy17** [comment]
Hi @miguelpruivo  after further debugging found out that this error was non blocking, but the files for which this error occurred I was unable to fetch the meta data properly from my end. Closing the issue.
