### ISSUE TITLE
If the extension of the zip file is other than "zip", it will be disabled.

### ISSUE THREAD

**Issue by katana-yu** [miguelpruivo/flutter_file_picker#996]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
Extension of the zip file is other than "zip" are disabled only when you select a file from Google Drive on iOS. For example, mxl file.
Similar to #571 .

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

iOS14.6
iOS15.1

**How are you picking?**
```
await FilePicker.platform.pickFiles();
```

**Details to reproduce the issue**
There is no problem with Dropbox on iOS. , Or Android is fine.
Only in the case of iOS + Google Drive, it is disabled and the file cannot be selected.

How can the file be activated?

thank you.

**Error Log**
No error.

**Screenshots and/or video**

**Flutter Version details**
[✓] Flutter (Channel master, 2.1.0-13.0.pre.223, on macOS 11.6.2 20G314 darwin-x64, locale ja-JP)
    • Flutter version 2.1.0-13.0.pre.223 at /Users/name/Development/flutter
    • Framework revision 891511d58f (12 months ago), 2021-03-23 14:57:01 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/name/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • ANDROID_HOME = /Users/name/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51

• No issues found!

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, I'm sorry, I didn't get what's the issue. Might to elaborate?

**Comment by katana-yu** [comment]
'mxl' is a compressed format for MusicXML files.
When I try to select an mxl file from Google Drive, it is grayed out like the attached image and cannot be selected.
The mxl file is actually a zip file.

You can easily reproduce it by the following method.
1. Create a zip file. (test.zip)
2. Change the extension by renaming. (test.mxl)
3. Upload to Google Drive.
4. Call `await FilePicker.platform.pickFiles();` and try to select from Google Drive.
![disable_only_mxl](https://user-images.githubusercontent.com/101535176/158490243-69784dd7-eb1c-4399-bb8d-11707fefdf05.png)
